ddev/ddev

- cmd/ddev/cmd/config.go
AppRoot was being derived from the arg[0] of the ddev execution; it should have been using os.Getcwd(). This caused the bug in #149.
One-line fix to use os.Getcwd(). Oddly, reading the line after it, it's almost certain that was intended anyway.
1. Build ddev
2. copy the ddev binary into /tmp
3. cd into a site and rm -r .ddev or just the config.yaml
4. /tmp/ddev config
You should see the AppRoot being the current directory, not /tmp
I don't think there's need to add tests for this.
[ddev mistakenly uses directory of ddev as location for .ddev instead of actual site dir](https://github.com/drud/ddev/issues/149)
Nothing is needed.
> Fix #149 by using os.Getcwd() to get AppRoot

- Makefile
The faster tests are in the 'pkg' tests, @tannerjfco mentioned he'd like to run those first.
Swap the order of the tests.
There should be no impact on anything.
> Swap order of tests so pkg tests are done before cmd

- circle.yml
- cmd/ddev/cmd/dev_sequelpro.go
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/z_rm_test.go
- pkg/cms/config/config_test.go
- pkg/cms/config/drupal.go
- pkg/cms/config/wordpress.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/utils.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/util/errcheck.go
We had a lot of functions which could return errors where the error was not being checked.
* Check the errors. In most of these we *never* expect to hit an error, so can use the new util.CheckErr(), which just checks, reports, and exits if there's a problem.
* Fix a couple of places where it was failing and never before detected
* Add standard errcheck target into circle.yml
There should be no change.
> Add error checking for everything errcheck points out, errcheck library functions

- Makefile
- README.md
- cmd/ddev/cmd/a_start_test.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/version.go
- cmd/ddev/cmd/version_test.go
- cmd/ddev/cmd/z_rm_test.go
- pkg/appports/ports.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/templates.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/templates.go
- pkg/plugins/platform/utils.go
- pkg/version/version.go
See #91 for full problem description. We want phpMyAdmin as an available tool for developers.
This PR introduces phpMyAdmin as well as exposing the correct ports on the router. 
- Compile this PR as a binary
- Ensure the site you are testing is stopped, and manually remove the .ddev/docker-compose.yaml file if one exists.
- Start a site. (optionally) import a database.
- Run `ddev describe`
- Load the URL listed under phpMyAdmin.
> Adds phpMyAdmin container

- README.md
We don't have installation instructions. Our install is simple, and we plan to provide a helper script, but we should still provide instructions for manual installation.
Provide install instructions.
> adds installation instructions

- .gitmodules
- circle.yml
- nightly_build.mak
- nightly_build_trigger.sh
We need to know that all our components work together at any given time, so we aren't surprised when we change a dependency. A nightly build is the common way of doing this, as it doesn't affect ordinary builds, but everything gets checked together every 24 hours.
* Use git submodules to  provide each container used by ddev. (Note that these are not and need not be populated in a normal developer build.)
* Add nightly_build.mak, which has the capability of building a complete set of tagged containers and then build ddev to use those.
* Add nightly_build.mak to the circle.yml
* Add a nightly-build runner script (nightly_build_trigger.sh) that can be run with a token to kick off a special build.
This should have no impact on existing behavior *except* when a nightly build is called for, in …
> ddev master build, with submodules for all containers

- build-tools/README.md
- build-tools/makefile_components/base_build_go.mak
WE WANT [codecoroner](https://github.com/3rf/codecoroner)
Update to build-tools 1.1.1
There should be no change of behavior.
> Updated build-tools to 1.1.1 (codecoroner)

- README.md
I happened to notice that the link from the circle badge went to somewhere in the sky.
Use the badge from the circle project (ddev)
> Fix link from circle badge - it went nowhere

- .gitmodules
- Makefile
- nightly_build.mak
We added docker.phpmyadmin as a new container, so it needs to be added to the nightly build.
* Add the submodule
* Add it to the nightly build
* Add DBAVersion to VERSION_VARIABLES so it can be overridden
> Add phpmyadmin submodule and add to nightly build

- README.md
- containers/README.md
[The master build PR](https://github.com/drud/ddev/pull/133) adds submodules to the project, but they're not intended to be in the developer's way (and nobody needs to init them). I pointed this out in slack, but @tannerjfco pointed out that it belonged in the README, so here it is.
* Add a note about the submodules to the readme
* Add a README to the containers directory
> Add not-to-worry about submodules/containers dir

- Makefile
- pkg/version/version.go
Upstream updates to phpmyadmin container version, v0.2.0
Bump version
> Bump DBATag (phpmyadmin container version) to v0.2.0

- cmd/ddev/cmd/root_test.go
- pkg/plugins/platform/local_test.go
With #166 we can now have config files that dont define db/web image tags.
This PR updates to releases of test sites that have db/dba/web image tags ommitted, allowing test sites to always use the default ddev image tags.
If CI succeeds, this should be safe to bring in.
> updates test site tags

- .circleci/config.yml
- docs/Adding_container.md
- nightly_build.mak
- pkg/version/version.go
I noticed in tonight's nightly build that the DBATag (tag for the phpmyadmin container) was not set correctly. The default was in use instead of latest (built in the build)
* Add DBATag to nightly_build.mak where it belongs.
* Add a document to docs/ with the steps to add a new container/submodule to the build, since it took me at least 3 commits/PRs to get it fully in there this time. 
* Bumped the canonical ddevVersion (in code, always overridden by make) to 0.3.0-dev. Hardly matters, but might as well.
> Make nightly_build work with DBATag properly

- README.md
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
- pkg/appimport/appimport_test.go
- pkg/appports/ports.go
- pkg/cms/model/drupal.go
- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/templates.go
- pkg/plugins/platform/types.go
- pkg/plugins/platform/utils.go
- pkg/testcommon/testcommon.go
- pkg/util/dockerutils.go
- pkg/util/dockerutils_test.go
- pkg/util/utils.go
The current `ddev list` command is some of the oldest code in ddev, and not particularly well written as it doesn't take advantage of a lot of the newer structs we've introduced. It's also lagging behind on things like the router update.
Let's rework this code to use the `FindContainersByLabel` function and the app interface, while updating the output to be current.
Here's some example output (from during a test run) with these changes applied:
```
1 local site found.
NAME   	TYPE   	LOCATION               	URL                      	DATABASE URL           	STATUS
drupal8	drupal8	~/Projects/ddev/drupal8	http://drupal8.ddev.local	drupal8.ddev.local:3306	running
```
Describe output:
```
NAME   	TYPE   	LOCATION               	URL                      	DATABASE URL           	STATUS
drupal8 …
```
> Rework `ddev list` command

- pkg/plugins/platform/local.go
- pkg/util/utils.go
We were using sudo to get full root privileges without expressly saying what we were doing (and without controlling the path of what we were executing), see https://github.com/drud/ddev/issues/117
* Say exactly what we're going to do
* Use the fullpath of the running executable (golang 1.8.1 os.Executable())
* Update circle.yml to install golang 1.8.1 (used in tests). Ooops. 
This does *not* stop and ask permission, which it probably could do.
* Manually remove current sitename from /etc/hosts
* Use `ddev start` to see the results
[Security: ddev can be used to sudo an arbitrary command](https://github.com/drud/ddev/issues/117)
> Be explicit about use of sudo - tell them what we're going to do

- cmd/ddev/cmd/dev_ssh.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/rm.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/utils.go
- pkg/util/dockerutils.go
There are a couple of (odd) circumstances in which we can get DockerCompose() errors that were kind of hidden before.  See [Missing error check](https://github.com/drud/ddev/issues/161).
* Add some error checking, add some output to log statements.
* removed platform.Cleanup() which was what was being done by `ddev rm` before. Please check this to see if you approve.  It didn't seem to work at all, and AFAICT was only being used in that one place.
* Introduce an error into your docker-compose.yml - any error will do
* Try `ddev rm`
It should let you know what the problem is.
[Missing error check](https://github.com/drud/ddev/issues/161)
> Handle DockerCompose() errors

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/root.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/plugins/platform/utils.go
- pkg/util/dockerutils.go
We access `platform.PluginMap` all over the place to get a reference to an application. The problem is that this is a reference to a single global App, and what we really want is a **new** Application which does not have the potential to be tainted by other code.
In the `ddev list` rework I introduced a `platform.GetPluginApp()` function which serves as an application factory. This PR updates all references to the PluginMap global to use that function.
Automated tests should be sufficient for this.
> Consistently use `GetPluginApp` to create new applications

- cmd/ddev/cmd/dev_ssh.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/rm.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
It is currently possible to start a site that has the same name of a site already running. This is undesirable, as it can apparently allow the new site's containers to replace the running site's containers without warning (per OP #136). 
This introduces a check of containers in `Start()` to see if any match the name we are about to start and are running. If there's a match, an error will return and the site won't be started.
- Have 2 sites to test
- Set site 1's name (by config.yaml or ddev config) to "testsite"
- `ddev start` for site 1 should succeed
- Set site 2's name to "testsite" (same as site 1)
- `ddev start` for site 2 should immediately fail with error.
A test case has been added to `TestLocalStart()` that attempts to start the first test site again, triggering this error.
#136 …
> requires unique names for running sites

- pkg/ddevapp/config.go
Full problem described in #97 if provided docroot value is invalid, it can not be replaced with empty value
If the directory not found condition is met, the c.Docroot value will be cleared, as it is not a valid value.
- Run "ddev config" anywhere
- Provide a non-existent path for docroot. You should receive the "No directory found" error, and a prompt again for docroot.
- You should be able to leave the 2nd docroot prompt value empty.
I'm not certain a test change is necessary for this PR, if someone feels strongly I'm happy to consider it though.
#97 OP
> reset docroot prompt val if dir invalid

- Makefile
- README.md
- cmd/ddev/cmd/logs_test.go
- pkg/version/version.go
With drud/docker.nginx-php-fpm#40 ddev logs will only output error log, but we still want to provide some info for advanced users to access other logs.
This PR updates the log section of docs to document location of access logs and php-fpm logs in the web container. It also updates the ssh section to provide instruction for accessing the db container.
These changes are intended to be the documentation component of https://github.com/drud/ddev/issues/87#issuecomment-297091699
Docs change. If it makes sense, great! If not, suggestions are welcome for improving.
Docs change, no test changes.
https://github.com/drud/ddev/issues/87#issuecomment-297091699
> expand log access docs, add db access to ssh doc

- pkg/plugins/platform/local.go
- pkg/plugins/platform/types.go
We have some dead code in the platform plugins. Specifically, none of the appbase fields are actively used at this point. The only one that may be of use is the "plugin" field, but that is already stored in the `appconfig` struct, so I don't see any reason to duplicate it.
Remove the unnecessary code to avoid confusion.
Automation should be good enough for this one.
> Remove unused appbase code

- pkg/plugins/platform/local.go
As noted in #108, WordPress sites rely heavily on the full URL of a site throughout its database, requiring search/replace of the URL across the database whenever it is changed. Our discussions to handle this scenario have led us to consider post-import hooks/commands, but this approach will need some time and further discussions to fully incubate.
This PR introduces a warning message to WordPress users after a successful database import. The message quickly explains the search-replace need and provides an example command the user can run after import.
This change is intended to be a temporary notification until such time we complete post-import functionality.
Start a wordpress site, and import a database for the site. You should see the following output:
```
Importing database...
A …
```
> provides warning for wp user to search-replace after import

- .circleci/config.yml
We've seen at least two testing timeouts (like [this](https://circleci.com/gh/drud/ddev/646)) today. To understand them, we'll let Circleci use 20m on the test instead of just the default 10m. 
Increase the timeout.
> Increase testing timeout in circle to 20m

- pkg/plugins/platform/local.go
There was a spelling error in this wp search-replace message on import. This corrects it, and adds a link to more info on search-replace as requested in https://github.com/drud/ddev/issues/108#issuecomment-299086656
This PR
Message change only, passing tests should be sufficient.
No test changes necessary.
> fix spelling error and add link to wp search-replace

- README.md
we should have the install script in the readme
here's the install script in the readme
> adds install script to readme

- .circleci/config.yml
- Makefile
* The static config in circle output makes a lot of noise
* It's a silly long unnecessary statement.
* We aren't saving the results of the build - it would be nice to have access to the binaries
* Make a single target with dependencies in Makefile
* use `make -s` so we don't have to see the full silly docker commands
* Save the build artifacts (linux and darwin) - these now show up under the "artifacts" tab on the build, and can be used to get the exact binary that was built.
> Simplify full static analysis in circleci config and Makefile, store away binaries

- build-tools/gitignore.example
- build-tools/makefile_components/base_build_go.mak
Simple upgrade to build-tools 1.3.0, which adds gometalinter and windows targets
https://github.com/drud/build-tools/releases/tag/1.3.0
> Updated build-tools to 1.3.0

- cmd/ddev/cmd/root_test.go
- pkg/appimport/appimport_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/util/files_test.go
* We upgraded to site repos without the Name: field in config.yaml - bump to new releases and test
* Now apps can have unique names instead of all having the Name: in the upstream test repo. Use unique names.
* Add the Name: provided by the test. This is done in testcommon.Prepare()
* Note that because this means testcommon.Prepare() now uses functions from ddevapp, the ddevapp config_test.go encountered circular imports. The workaround was to make config_test.go be in ddevapp_test package (instead of ddevapp) for "black box testing" that avoid the circular import. [Lesser-known features of go test](https://splice.com/blog/lesser-known-features-go-test/) has a nice paragraph on "The black box test package"
Test should run successfully; you should see properly named apps created (and then …
> Bump to new releases and make site names unique per test

- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/router.go
- pkg/plugins/platform/utils.go
Currently, the router does not shut down after you stop/remove all running sites. We should be good citizens and only be running the router when there are things to route to.
This PR introduces changes which will perform a check during stop/rm for all running containers which have a `com.ddev.platform` label. It does not care what the value of the label is. If running containers are found with that label, it leaves the proxy up. It no containers are found with that label, it stops the proxy.
- Build this binary
- Use `ddev` as you normally would. The proxy should always be up if sites are running, and it should always be down if no sites are running.
- Added a test case to ensure the router has been stopped at the end of the local platform tests.
https://github.com/drud/ddev/issues/40
> Stop router when no sites are running

- cmd/ddev/cmd/root_test.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/util/files.go
- pkg/util/files_test.go
* We were shelling out to use tar in some places, which is a fragile technique
* We had an Untar() function (yay!) but it deferred closing all the files it created until the end of the function, so we ended up with "too many open files" errors. 
* Our Untar() didn't have the capability of starting at a particular directory level in the enclosed filesystem, which we require to unpack our release tarballs.
* Untar was dropping headers like 'pax_global_header' in the root directory as files
* Improve the Untar() to close immediately
* Make it only save directories and files to solve the pax_global_header problem
* Add the ability to pull just a part of the tarball
* Improve the tests
* Change the usages that were shelling out
This should be ok if it passes tests
Tests are improved a little …
> Rework tar usage to avoid shelling out and improve Untar()

- pkg/updatecheck/updatecheck_test.go
In test code in https://github.com/drud/ddev/pull/217 there were some uses of time.Duration() that seem add complexity to the code even though they're correct (time.Duration() just casts the constant provided to the Duration numeric type). IMO this patch is more readable but not more correct. 
I apologize for being so OCD about something so simple that's not doing any harm. It was just part of my golang education.
Simple changes here should result in no behavior change.
> Simplify time durations in test

- .circleci/config.yml
The windows binary artifact isn't being built in the nightly build because that's a separate build and it does a `make clean` first.
Explicitly add windows to the build.
Look at the artifacts tab after a nightly build and see if the windows binary is there.
> Build windows on nightly build

- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/remove_test.go
- cmd/ddev/cmd/root_test.go
- pkg/util/prompt.go
ddev rm removes all data for a site, it might not be obvious to the user that they're about to lose their whole setup.
* Add confirmation step
* Add Y/N prompting mechanism (copied from bootstrap drud cli)
* Fix test to use the confirm flag
* Add a cmd-side test for ddev remove to make sure the various options work
Run ddev rm and use the options available.
A new TestDevRemove test was added. It uses a pipeline with "echo" as a very simple way to offer the option to ddev.
> Add confirmation step to ddev remove

- cmd/ddev/cmd/root_test.go
- pkg/plugins/platform/local_test.go
- pkg/testcommon/testcommon_test.go
https://github.com/drud/ddev/issues/230 requests update of our drupal8 repo to 8.3.2. This is pending in https://github.com/drud/drupal8/pull/4 - but here's the bump.
I already have a db.sql.gz ready (based on upgrade of our previous db); the files tarball doesn't change.
Tests on this will fail until https://github.com/drud/drupal8/pull/4  goes in and files/db are added to a release of 0.6.0 there.
> Bump drupal8 repo to 0.6.0 (8.3.2)

- README.md
Also includes an update to the project overview verbiage and context as to why we use a roadmap, what it means, etc. Relates to issue [Update readme to include a link to the roadmap and a stronger introduction.](https://github.com/drud/ddev/issues/212).
An end-user visiting the project page probably doesn't realize there is a roadmap as well as the expectations around it, how to submit feature requests/issues, etc.
Update the readme to link to the current wiki and provide context as to what it means and how to contribute to its future.
NA
NA
#212 
NA
> Add link to the roadmap to ddev Readme.md

- README.md
We don't have the shiny readthedocs badge on our readme
This adds the shiny readthedocs badge to our readme
> adds readthedocs badge to readme

- Makefile
- cmd/ddev/cmd/version.go
- cmd/ddev/cmd/version_test.go
We've all been bit by the version test not working correctly when the binary has been recompiled and is then used. It's not doing us any good.
* Change the version test into a non-binary test.
* Make testpkg not force a build of the binary, as testpkg doesn't rely on execution of the binary. We could probably sort out tests more - I'd kind of like to see most of the binary tests removed.
If it passes tests it should be fine.
> Change version test into non-binary test

- Makefile
- pkg/ddevapp/templates.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/router.go
- pkg/plugins/platform/templates.go
- pkg/util/dockerutils.go
- pkg/util/dockerutils_test.go
- pkg/util/files_test.go
- pkg/util/util_test.go
- pkg/version/version.go
We want to provide support for users to define their own additional services to run as part of a ddev app. We are providing support for multiple extending/overriding compose files in #198, but we also need a way to expose new ports on the router, so that users can define a new service to be available at `sitename.ddev.local:portNo`.
This PR changes how ports are exposed on the router container. Previously, each port we needed to expose was explicitly defined as a value in the router template. The new approach works by:
- Leveraging the existing `VIRTUAL_PORT` env var used to determine which ports are configured as upstreams in the router.
- Retrieving values of `VIRTUAL_PORT` from all site containers
- Retrieving existing port mappings from the router if it is running
- Reconciling the …
> determine router expose ports by parsing HTTP_EXPOSE and TCP_EXPOSE per site container

- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/plugins/platform/utils.go
Currently you cannot run describe on a stopped site. It reports the following error if you try:
`2017/05/17 13:14:27 Could not describe app: ddev site is configured but not currently running`
No longer check to ensure a site is running, and instead show the describe command with proper "status" regardless of whether it is running or not.
1. Compile the binary from this branch
2. Stop a running site
3. Run `ddev describe`. It's probably a good idea to test both `ddev describe` from the working directory, as well as `ddev describe [sitename]` from outside the working directory.
I've added automation to `local_test.go` to ensure describe reports properly when a site is stopped.
https://github.com/drud/ddev/issues/164
> Allow describe to work on a stopped site

- pkg/plugins/platform/local_test.go
- pkg/testcommon/testcommon.go
go tests provide test run times at package and test function level. This is useful information, but it does not give us a clear picture in terms of how long the functionality we are testing takes to run. This is because the run times for function-level tests include the time for any required setup and teardown for the tests. Additionally, for test functions that are iterating tests over several sites, the test function time provides the total run time of the test for all sites.
This PR introduces a new utility function for testing that allows us to surface more specific run times for tests. It implements this new function in the local platform tests, where we have most of the tests iterate over several test sites. This provides additional log outputs for the run time of each site's …
> adds run times for local tests per site

- docs/users/customization-extendibility.md
The lists on this page weren't properly formatted, so instead of lists we have a big wall of text. Additionally, I seemed to have struggled spelling Additional/Additionally correctly.
This fixes the formatting and spelling issues.
> formatting and spelling fixes for extend doc

- pkg/util/dockerutils_test.go
- pkg/util/util_test.go
The nightly build failed [last night](https://circleci.com/gh/drud/ddev/878):
`2017/05/25 01:21:03 failed to pull test image API error (404): {"message":"manifest for drud/nginx-proxy:v0.4-16-g2ca92ae5-nightly.20170525011408 not found"}`
This was a result of the TestMain in util_test.go trying to do a pre-emptive pull on an image it assumed would have been pushed (but for the nightly build is built but not pushed).
Pull an image that we know should exist on dockerhub. In this case drud/nginx-proxy:test-do-not-delete
> Pull only a known image in util_test TestMain - breaks nightly build

- Makefile
- docs/index.md
- docs/users/linux_notes.md
- pkg/ddevapp/templates.go
- pkg/plugins/platform/local.go
- pkg/version/version.go
On linux, files created or modified by the webserver are bleeding through to the host filesystem with root user/group. This is a security issue as well as an annoyance for our users, who have to use sudo to edit the files, and all kinds of things can happen.
* ddev can provide environment variables to the nginx-php-fpm-local container (on linux only)
* The nginx-php-fpm-local container can then change the uid of its 'nginx' user before launching nginx.
* All files created by the webserver are then created with the correct uid/gid of the user that ran ddev.
There is a problem with this that seems unsolvable: docker mounts filesystems *always* with uid 1000, which happens to be Ubuntu's default UID for an ordinary user. That's fine for user 1000. But other users will have trouble getting …
> Explicitly set variables for the nginx container UID/GID - fixes #131

- pkg/cms/config/config_test.go
- pkg/cms/config/drupal.go
- pkg/cms/config/wordpress.go
- pkg/plugins/platform/local.go
#260 Creation of settings.php fails after db import on Windows.
This was caused by several instances where we were not handling file paths properly. This PR replaces instances where paths were defined with slashes in string form with proper filepath.Join() usage. It also uses filepath.Dir() where we need to remove the last part of a path, instead of trimming the path as a string.
Start a site using ddev on windows. Perform a database import using the import-files command. The command should succeed as it does on Linux and Mac.
#260
> fixes file path issues writing site config on windows, fixes #260

- pkg/ddevapp/config.go
#263 docroot mount doesn't work with explicit docroot on Windows. This prevents a site using a defined docroot path from starting on Windows.
This issue stemmed from using `filepath.Join()` in a context where we always want a unix-style path defined. For this situation, it seems reasonable to simply concat ../ with the provided docroot path.
On a Windows machine, run ddev config on a site that uses a docroot folder. Run ddev start. You should be able to successfully start the site.
#263 OP
> fixes docroot mount path for windows, fixes #263

- pkg/plugins/platform/local_test.go
#205 surfaces a pain point in running tests locally. There are a few tests in our platform package that will fail if sites are running on the system before the tests start. The problematic tests are TestGetApps, TestGetAppsEmpty, and TestRouterNotRunning. TestGetApps expects the listed sites to match the number of test sites, while TestGetAppsEmpty and TestRouterNotRunning both require there to be no sites running in order to succeed.
Ideally, the tests would not fail as a result of there being sites running already. Unfortunately, this can't be achieved with TestGetAppsEmpty and TestRouterNotRunning. Both require a state of no running sites in order to truly test what they are out to test.
With that in mind, this PR introduces a check in the TestMain() for local plugin tests to see if …
> fail the local plugin tests if sites are already running

- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/exec_test.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/ssh.go
- docs/users/cli-usage.md
#68 identified some validation issues with ddev exec. Some of the issues have been addressed since the ticket was created, but the requirement to encapsulate multi-argument commands in quotes makes for a clunky experience compared to docker exec, which requires no quoting for such commands.
This PR updates the exec function, removing the requirement for users to quote commands that had multiple arguments or flags. It achieves this by disabling support for interspersed option/non-option arguments on the exec command. This means that flags for ddev exec will need to be defined prior to the command that will be exec'd in a container. The PR also introduces the "." alias for exec, allowing users to run commands like `ddev . drush status`. It also updates the help text and documentation for …
> removes requirement for exec cmds to be wrapped in quotes, updates help, fixes #68

- .circleci/config.yml
We need docker 17.05 running on CircleCI, since we're introducing that as the minimum required version for ddev in #289 
This installs the 17.05 edge release for CircleCI
It either works or it doesn't.
> installs docker 17.05 edge for circle builds

- .circleci/config.yml
- Makefile
- nightly_build.mak
- pkg/plugins/platform/local_test.go
Tests take a long time. It's good we have a lot of tests, but we probably don't need to check 3 sites for every single test run. 99% of things should be found by a single site.
- We're running "make test' twice. Removing the second run is a slam dunk for cutting out tests in half.
- We get a further reduction by using `-short` flag to reduce runtime for our normal tests, while still doing the full testing list on the nightly build. This is straight out of https://splice.com/blog/lesser-known-features-go-test/. This further reduces test times by an additional ~5 minutes (~21 to ~16).
Obviously doing step 1 is a no brainer. The usage of `-short` I could go either way on. I feel like it's probably worth it, though. We still maintain the full test list on our nightly builds so if anything …
> Reduce TestRun duration

- README.md
- cmd/ddev/cmd/root.go
- docs/index.md
- pkg/ddevapp/templates.go
- pkg/util/dockerutils.go
- pkg/util/dockerutils_test.go
- pkg/version/version.go
#253 OP, we want to add the new :cached option to the web container mount so that we can realize the performance improvements provided by it. This option was introduced in 17.04 Edge, and is targeted for the upcoming 17.06 Stable release. The option is not understood by previous versions, so we need to ensure users are running versions that understand the new option.
This PR introduces the :cached option to the web container mount.
It also introduces functionality to check the current running docker version, and see if it meets our version constraints. Currently, this constraint is defined as `>= 17.05-ce`. I chose 17.05 since none of us tested in 17.04, and it is an edge release with a shorter release cycle. We will be able to define different constraints in the future as needed, should …
> Implement user-guided caching, check docker version requirements

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
- .circleci/tag_build.sh
- .gitignore
- build-tools/README.md
- build-tools/gitignore.example
- build-tools/makefile_components/base_build_go.mak
- build-tools/makefile_components/base_build_python-docker.mak
- build-tools/makefile_components/base_test_go.mak
* Upgrade build-tools, moves us to golang 1.8.3
* Typo fix from https://github.com/drud/ddev/pull/295
> Build tools upgrade, circle followup

- install_ddev.sh
We changed to versioning the tarball filenames in https://github.com/drud/ddev/pull/295, so the install script needs to support that.
Minor fixes to the install script. 
Try it - run the script and make sure it updates correctly. 
#296 is the OP
Nothing should need to be done as the docs have people use master to obtain this script.
> Update install script to work with new tarball naming technique, fixes #296

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/sequelpro.go
- cmd/ddev/cmd/sequelpro_test.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
- docs/users/cli-usage.md
#78 OP. It's annoying to go hunt down running ddev sites, switching to their directories one at a time to describe/stop/remove them.
This PR introduces the ability to provide the sitename as an argument for ddev stop and ddev rm. This allows you to stop and remove sites without having to navigate in the terminal to the working directories of those sites. This is done by extending the functionality of getActiveAppRoot() based on similar functionality originally introduced for the describe command. Some additional cleanup was done along the way, including the removal of dead db/web image/tag flags on ddev start.
Using the binary built from this PR, start up a couple of sites. Then, navigate away from those sites in your terminal. Run ddev list to see your sites. You should be able to run …
> Allows ddev describe, stop and rm to accept sitename argument, fixes #78

- pkg/plugins/platform/local.go
- pkg/plugins/platform/router.go
- pkg/plugins/platform/templates.go
- pkg/plugins/platform/utils.go
OP [#39 Remove associated docker volumes when ddev-removing a site/app](https://github.com/drud/ddev/issues/39)
* Use -v argument with docker-compose
* Use RemoveVolumes in the failsafe cleanup
* Remove all your sites
* Remove volumes to start clean.  `docker volume ls`
* Start a site
* `docker volume ls` to see volumes
* `ddev rm -y` to kill your site
* `docker volume ls` to see that the volumes are gone now.
> Remove volumes when removing containers Fixes #39

- .gitmodules
- Makefile
- cmd/ddev/cmd/restart_test.go
- docs/users/customization-extendibility.md
- nightly_build.mak
- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
- pkg/dockerutil/dockerutils_test.go
- pkg/dockerutil/testdata/docker-compose.override.yml
- pkg/dockerutil/testdata/docker-compose.yml
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/templates.go
- pkg/plugins/platform/utils.go
- pkg/version/version.go
See [OP](https://github.com/drud/ddev/issues/288): Conflicts with drud tool, misnomer naming of containers "local"
* Rename nginx-proxy container to ddev-router (container name only, not repo name, etc.)
* Change container names to ddev-* instead of local-*
* Move to standard "testdata" test data directory from "testing" where I happened to be touching code.
Notes:
* This does not attempt to name-change the nginx-proxy repo or docker repo.
* This is somewhat of a breaking change, as older sites would want to use nginx-proxy, newer want ddev-router, and they fight over port 80.
* It's also a potentially breaking change if somebody had a database container going and found a way to upgrade that replaced the database container.
* We could actually change the name of the *platform plugin* to …
> Use ddev as container name prefix, ddev-router instead of nginx-proxy, fixes #288

- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- docs/users/cli-usage.md
- pkg/archive/archive.go
- pkg/fileutil/files.go
- pkg/fileutil/files_test.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/testcommon/testcommon.go
#287 OP. If your stuff isn't at the root of your archive, your archive is no good to us!
This PR introduces options for import-db and import-files to specify a path in an archive to extract, rather than extracting the whole archive. The extraction path can be specified with the --extract-path flag. If no flags are provided, the user gets the prompt for import asset path. If the provided asset is an archive, an additional prompt is provided, asking the user if they want to specify a location in the directory to extract.
This PR should generally let you use an archive structured in any way, so long as 1) if importing a db, you provide a path to a sql asset 2) if importing site files, you provide a path to site files.
I have added a full drush-generated archive for the kickstart test site: …
> Provides option for import to extract specific paths in archives, fixes #287

- .circleci/circle_vm_setup.sh
Mysql signing key for debian expired.
Update to the new key - affects only our circleci build.
Look at circleci build and see if this has disappeared:
```
W: GPG error: http://repo.mysql.com trusty InRelease: The following signatures were invalid: KEYEXPIRED 1487236823 KEYEXPIRED 1487236823 KEYEXPIRED 1487236823
WARNING: The following packages cannot be authenticated!
mysql-server mysql-community-server mysql-client mysql-community-client
mysql-common
```
> Update apt key for mysql to avoid errors on circleci

- pkg/plugins/platform/local.go
The mysql example in ddev describe didn't have all the options needed to make the user successful.
Give a full example.
```
$ ddev describe
NAME      TYPE     LOCATION              URL                         STATUS
randyfay  drupal7  ~/workspace/randyfay  http://randyfay.ddev.local  running
MySQL Credentials
-----------------
Username:     	db
Password:     	db
Database name:	db
Host:         	db
Port:         	3306
To connect to mysql from your host machine, use port 32868 on 127.0.0.1.
For example: mysql --host=127.0.0.1 --port=32868 --user=db --password=db --database=db
Other Services
--------------
MailHog:   	http://randyfay.ddev.local:8025
phpMyAdmin:	http://randyfay.ddev.local:8036
```
Do a `ddev describe` and then plug in the example mysql command.
This is followup on comment on …
> Improve example mysql command in ddev describe, followup on #277

- .circleci/config.yml
- .circleci/generate_artifacts.sh
- cmd/ddev_gen_autocomplete/ddev_gen_autocomplete.go
- docs/users/cli-usage.md
- install_ddev.sh
Some of us are dependent on autocompletion. OP #125 
Cobra supports bash completion, although it does not yet support (directly) zsh completion. The implementation is fairly straightforward into a separate binary.
* build for your platform
* The completions generator will be in bin/.../ddev_gen_autocomplete, for example bin/darwin/darwin_amd64/ddev_gen_autocomplete
* run the generator, `bin/darwin/darwin_amd64/ddev_gen_autocomplete` and it will create bin/ddev_bash_completion.sh 
* ddev_bash_completion.sh can be installed as `ddev` in /usr/local/etc/bash_completion.d/ddev or wherever you keep your bash completions.
After a new release (v0.8) is created, the homebrew recipe should support automatically installing the completions.
> Bash autocompletion for ddev, fixes #125

- docs/users/customization-extendibility.md
- pkg/ddevapp/templates.go
- pkg/plugins/platform/templates.go
#300 OP. If the docker daemon gets restarted, previously running site containers come back, but ddev-router doesn't.
We defined restart policies for site containers, but not for the router. This adds a restart policy of always to the router, matching policy for the site containers.
I also bumped the composer file versions to v3. I initially bumped to v3 to evaluate a restart policy option not available for v2 (unless-stopped), but decided against using that option. I went ahead and bumped the version anyways, since we don't have any incompatible usage, and we may as well upgrade sooner rather than later, potentially affecting more users.
#300 OP outlines how to reproduce the failure:
- Have ddev sites running
- Restart the docker daemon
- See no ddev-router in `docker ps`, no accessible …
> adds restart policy to ddev-router, updates to docker-compose v3, fixes #300

- Makefile
- cmd/ddev/cmd/exec_test.go
- docs/users/customization-extendibility.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/templates.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/version/version.go
#189 OP. Mounting only the docroot prevents code and assets above the docroot from being accessible to the web container. This can prevent a site from working entirely if it depends on code that resides above the docroot.
This introduces changes to mount the full codebase of the project instead of the docroot. The docroot value becomes a relative path that is provided to the web container as an environment variable. This env var is then used to set the docroot for nginx in the web container.
This will also include documentation changes to support overriding the nginx configuration file with one the user provides.
**To test this, you need to remove any pre-existing .ddev directory (minimally the docker-compose.yml). This also requires the `template-site-config` tag of the web container be …
> Mount full codebase to web container

- Makefile
- pkg/version/version.go
Our nginx-php-fpm-local container needed to be upgraded for newer drush. OP https://github.com/drud/ddev/issues/331
Sorry this will create a merge conflict with your work @tannerjfco. 
https://github.com/drud/ddev/issues/331
> Bump nginx-php-fpm-local version to get newer drush, fixes #331

- Makefile
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/sequelpro.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/router.go
- pkg/plugins/platform/types.go
- pkg/plugins/platform/utils.go
- pkg/version/version.go
OPs #313 & #318 surface issues with our current approach for determining site status, which only checks the web container's health. The router and the db service are also important and need to be running healthily, otherwise the site environment is not truly running, and this is not accurately reflected in ddev list or describe output.
This PR introduces a number of fixes related to improving site status checks:
- Adds status check of ddev-router to StartDDevRouter() to ensure the router is healthy running. If the router fails to report running, "ddev start" will provide a failure error message.
- Adds router status messaging to "ddev list" and "ddev describe". If the router is not running, an additional message will be provided to inform the user that sites are not likely to be …
> Expands status checks to account for router and db, fixes #313, fixes #318

- pkg/appimport/appimport_test.go
#203 created test folder should be unique to avoid collision
This makes the folder created in user's home directory uniquely named to prevent collision. 
This only affects tests, and there should be no discernible difference in the test. The OP identified an error that was originally showing up in our tests, but it does not appear to be present in recent builds. I'm not sure if the issue is still valid at this point, but it doesn't hurt to make the test directory unique.
#203
> use unique folder for testing ValidateAsset, fixes #203

- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/remove_test.go
- cmd/ddev/cmd/root_test.go
- docs/users/cli-usage.md
- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
- pkg/dockerutil/dockerutils.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/util/prompt.go
This is an alternative approach to #337 which uses named volumes instead of host mounted directories.
It allows MySQL data to persist even when a site is removed using `ddev rm`, but rather than host mounting the files, it uses the native docker volume functionality, https://docs.docker.com/compose/compose-file/#volume-configuration-reference. Personally, I think it will be easier to maintain in the long run if we just rely on what docker is giving us. That being said, I can also understand the potential UX benefits of exposing the volume as a directory.
I mostly put this together to prove to myself it would work as I expected and from there the changes were small enough that it made sense to just open a PR to compare the approaches.
- Start a site
- Install drupal/wordpress
- Remove the …
> Use named volumes for MySQL volume

- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/plugins/platform/local.go
#86 OP we currently accept site names allowing any/all characters. This doesn't work out so well for domain names, and attempting to start a site whose sitename contains invalid characters for a domain will result in the site failing to start.
This PR introduces validation of the site name value. Site names will now be validated as hostnames per RFC 1123. If the working directory name does not validate, it will not be suggested to the user. If the user supplies an invalid site name during "ddev config", they will be re-prompted for the site name.
This also introduces a Validate() method for config that runs during App.Init(), which will validate hostname, docroot, and apptype. If any of these values are invalid, an error will be returned to the user instructing them to resolve the invalid …
> validate sitenames, validate config during init, fixes #86

- .github/ISSUE_TEMPLATE.md
We're starting to have outside contributions in the issue queue, and we always end up having to ask them the version. We might as well get it at the beginning.
Any other suggestions on improving this for outside contributors are welcome before this goes in.
> Improve issue template for outside issue creation

- Makefile
- pkg/servicetest/servicetest_test.go
This is a fix for #365. The nightly build failed due to the docker network not being set up.
This PR adds the "ddev_default" network before running the servicetest group. Additionally, it failed more gracefully in the event that the network is not set up.
> Add fix for nightly build

- Makefile
We introduced -short in #292 in order to reduce test run duration. However, at least twice we've missed regressions until after pull because we don't test multiple sites without it. It's time to bring it back. There are a number of ways we could make things faster.
It's still easy to build with -short: `make testpkg TESTARGS="-short"`
Remove the default -short from the Makefile. If it comes back it would probably be better to put it in the circleci config.
#354 OP
#292 was the introduction of -short as default. We're not reverting anything but the default usage of -short in the build.
> Remove -short default in makefile, fixes #354

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/remove.go
- docs/users/extending-commands.md
- mkdocs.yml
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/templates.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- vendor/github.com/mattn/go-shellwords/LICENSE
- vendor/github.com/mattn/go-shellwords/README.md
- vendor/github.com/mattn/go-shellwords/shellwords.go
- vendor/github.com/mattn/go-shellwords/util_posix.go
- vendor/github.com/mattn/go-shellwords/util_windows.go
- vendor/vendor.json
OP #183 We would like to provide support for running tasks before or after some ddev commands. These tasks should be defined in the config.yml for a site.
This PR makes that happen. It adds support for an `extend-commands` key to be defined in the config.yml of a site, that then defines command hooks, with a list of tasks to run. For example:
```
extend-commands:
post-import-db:
- exec: "drush cc all"
```
The following command hooks can be defined:
- `pre-start`: Hooks into "ddev start". Execute tasks before the site environment starts.
- `post-start`: Hooks into "ddev start". Execute tasks after the site environment has started
- `pre-import-db`: Hooks into "ddev import-db". Execute tasks before database import
- `post-import-db`: Hooks into "ddev import-db". Execute tasks after database …
> Adds support for pre-/post- ddev command tasks

- README.md
Docs builds have been reporting as  failing for a long time. We don't believe this is our fault and have filed an upstream issue. Unfortunately, thus far the maintainers of readthedocs have not been very responsive on the issue.
If a failing docs badge is our "new normal", let's just remove it until the reporting gets fixed.
https://github.com/rtfd/readthedocs.org/issues/2985#issuecomment-313798290
> Remove documentation badge until builds report correctly

- .vscode/settings.json
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon.go
OP #371. Our tests in the platform package are interdependent, requiring the full package tests to be run in order to run a given individual test.
This PR breaks most of the test interdependencies. It moves start and remove functionality to the provision/cleanup handled in TestMain, so that individual tests can run without having to test the whole package. It also updates a couple tests, notably TestLocalExec, so that they can run without dependency on tests previous.
This also resolves #381, allowing ddev stop to run successfully unless there are no containers found.
There are a couple smaller tests I did not update to run independently, TestGetAppsEmpty and TestRouterNotRunning. These tests both validate a state in which no applications are running. I can update them if there's a strong …
> Local test refactor, fixes #371, fixes #381

- cmd/ddev/cmd/root.go
- pkg/dockerutil/dockerutils.go
OP #357 Our error message is not very good if we can't connect to the docker client.
This improves the error message if we can't connect to docker. It also allows the "version" and "config" commands to be run regardless of docker's state or version.
- Stop your Docker daemon
- Run a ddev command that's not version or config. You should get a clear error message that we can't connect to Docker.
- Run ddev version and ddev config. These commands should work normally without docker running.
> improve error message for no docker connection, fixes #357

- vendor/github.com/fatih/color/README.md
- vendor/github.com/fatih/color/color.go
- vendor/github.com/fatih/color/doc.go
- vendor/github.com/mattn/go-colorable/README.md
- vendor/github.com/mattn/go-colorable/colorable_others.go
- vendor/github.com/mattn/go-colorable/colorable_windows.go
- vendor/github.com/mattn/go-colorable/noncolorable.go
- vendor/github.com/mattn/go-isatty/README.md
- vendor/github.com/mattn/go-isatty/isatty_appengine.go
- vendor/github.com/mattn/go-isatty/isatty_others.go
- vendor/github.com/mattn/go-isatty/isatty_windows.go
- vendor/vendor.json
A good theory was to upgrade fatih/color to see if colors would be reported on Windows. This PR does that (and has to update related as well).
Unfortunately this does not seem to solve the problem. (Note that govendor fetch had to be coaxed along, so there may be missing dependencies still)
OP: #363 - ddev (especially ddev list) doesn't current show colors, shows raw terminal strings instead.
> Update fatih/color and related repos in vendor (Trying for #363)

- testing/ddev-perf-test.sh
I hit a couple snags with the performance test script when looking to test drud/docker.mysql-local#26. This provides fixes to get it working as expected.
- The check for "gtime" did not catch that I did not have gnu-time installed. Apparently `which` can differ quite a bit in behavior across different platforms https://stackoverflow.com/a/677212. Replaced with an approach using `command` that seems to work as expected.
- drush dl output was being redirected to a not-yet-existent file, which prevented the site from downloading as expected. It is now outputting to /dev/null, as I didn't see a reason to log the drupal download output.
- drush si credentials needed to be updated since we changed all values to "db"
> updates and fixes for performance test

- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_test.go
We have a couple of ways that ~/.ddev might not get created at the right time and it's absolutely essential for both mounts (mysql health) and updatecheck. 
Create ~/.ddev in root.go at the very beginning before the updatecheck.
rm -r ~/.ddev and then `ddev start`
This should be tested explicitly on windows.
Adds TestCreateGlobalDdev as a test - it changes the $HOME environment variable in order to much with ~/.ddev without breaking the user's system.
OP #358
> Make sure that ~/.ddev exists very early, fixes #358

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/root_test.go
- pkg/plugins/platform/utils.go
TestDescribe and friends had minor problems that caused failures on Windows.
* Fixes the ~/ format in ddev list/ddev describe so it looks the same on windows/linux/mac
* Fix various problems with order of directory deletion
> Fix TestDescribe for Windows

- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/root_test.go
- pkg/plugins/platform/local_test.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
Windows directory-copy performance is totally amazing, taking 5:40 to copy the Drupal8 test site for tests on an SSD-backed filesystem. This is true even with Microsoft's native xcopy.
Skip copying the biggest directories by default (for local dev, and short tests) by using the Wordpress tarball (10% of the files, 1400 vs 14000).
> Swap testsites to do wordpress on short/default for windows performance

- docs/users/providers/pantheon.md
- mkdocs.yml
OP #369. All that fancy new pantheon functionality needs documentation!
Here's some documentation! This PR is based on and revises the documentation @rickmanelius started in https://github.com/drud/ddev/issues/369#issuecomment-312716098. 
There are some sections I didn't include - namely the info on settings.php/wp-config.php (since it's no longer valid, and i'm not 100% on what is now valid), and Apache Solr, since I'm pretty sure we haven't attempted to use solr with a Pantheon site yet (I think this could be a follow-up item from the main pantheon work, personally). Otherwise, this should largely resemble what was being iterated in the Gdoc.
This will likely still require some changes, as development is still in progress.
#345 Pantheon Provider Plugin
#369 Pantheon Plugin Documentation
> adds docs for pantheon provider integration

- pkg/plugins/platform/local.go
#259 OP. On Windows, you will get notification to manually add hosts entry even if the hosts entry is in place.
This is due to our check for non-interactive env var and for sudo occurring before we check the hosts entries. This changes to check the hosts file before we try to check for non-interactive or sudo.
I was really hoping to find a solution for privilege escalation, but unfortunately I couldn't quite get something working. The closest I got was providing a manifest file for Windows using https://github.com/akavel/rsrc to embed in the binary. This successfully triggers a UAC prompt from the command line, but I couldn't determine how to make it happen for only a sub command, such as ddev hostname. It would trigger for every command, including ddev with no args or ddev -h, and on …
> check hosts file before checking non-interactive/no sudo, fixes #259

- Makefile
I noticed that I recently broke the testcmd build for OSX with a Makefile typo. `make testcmd` has *not* been guaranteed to use the right built ddev on OSX since that point, which is not good. It affects local testing most. But of course it broke my experiment with local CI.
Use the correct parens when building DDEV_BINARY_FULLPATH for darwin.
It also uses the easier shorthand $(PWD) which is now available from build_tools
`make testcmd` and verify that DDEV_BINARY_FULLPATH is correctly set, and that the tests report using a ddev with the correct full path.
> Fix broken Makefile for testcmd in OSX

- pkg/plugins/platform/local.go
The sudo warning was not very good, lost in the midst of a bunch of other text.
Colorize it with util.Warning()
> Colorize 'you must add to hosts' warning

- build.cmd
- build.sh
We need to test on windows and darwin at least a little bit. This is experimental, and requires some equipment deployment, but it's pretty easy. We need to see if we can make it stable enough not to be annoying though.
The [surf](https://github.com/surf-build/surf) package seems to do the job for us. 
This PR adds two scripts, build.sh and build.cmd, which are used by the build system to do what needs to be done. 
Nothing happens yet until a listener on one or more platforms is out there polling github for changes.  So the introduction of these two files means nothing unless there is a polling surf build server that tries to use them.
Note that I currently have this just running `make testcmd` so the test is a bit shorter and simpler until we're sure we want it to run a full test. And …
> Experimental: Create CI for windows and darwin using surf, fixes #254

- pkg/plugins/platform/local_test.go
- pkg/testcommon/testcommon.go
There were a couple of archive downloads (two quite large) that were still not being cached in our tests.
* Change to cache them.
* Minor improvements in variable naming to make it clearer what's going on.
Run `make testpkg TESTARGS="-run TestLocalImport"` twice, and verify that it doesn't bother to do the download the second time.
> Use caching on some remaining tarball downloads

- Makefile
- build.sh
- pkg/fileutil/files.go
- pkg/plugins/platform/local_test.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon.go
We started out just testing `make testcmd` to make sure things were shorter.  This PR tries running the whole test suite.  Minor changes made along the way.
* Switch to `make test`
* Extend (potential) test timeout for windows in Makefile
* Remove the t.skip for windows on TestLocalLogs, which turned out unnecessary.
* Remove chmod in CopyFile on windows, as golang on windows can't do that on long paths.
> Build (most) everything in automated surf tests

- mkdocs.yml
The pantheon docs aren't showing up on readthedocs due to an invalid path in the table of contents.
This fixes the invalid path.
> updates docs ToC

- pkg/updatecheck/updatecheck_test.go
github rate limiting can cause test fail, and fix typo.
* Fix typo
* Fail test on err
* Skip TestAvailableUpdates if GOTEST_SHORT is set
Note: This PR could probably be improved using the "Client Secret" approach, https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications - however, we don't really need to add complexity at this time.
It also might be able to be improved by authenticating with GITHUB_TOKEN (available on test servers) if it's available. But again, that complexity is probably not needed for this issue.
> Fix typo, fail test if AvailableUpdates() fails

- .circleci/circle_vm_setup.sh
It's time to bump our testing docker version. We ask people to install recent stable, so here we go.
> Bump docker and docker-compose versions to current stable

- LICENSE
Changing license to Apache 2.0 per Drud's decision to go with Apache 2.0 for everything, in drud/general#128 (a private repo).
Straight change of license to Apache 2.0
OP: drud/general#128
> Change license from MIT to Apache 2.0 for drud/general#128

- Makefile
- pkg/version/version.go
We've rolled a 0.7.4 version of the nginx container and need to update ddev to use it.
- Create a new site using ddev config. Ensure .ddev/config.yaml uses the v0.7.4 tag for the nginx container.
- Start the site
- Run a site install or any other command that has a prompt. E.g. `drush si --db-url=mysql://db:db@db:3306/db`
- You should still see a prompt, but it should be automatically answered with a 'y'. As in `Do you want to continue? (y/n): y`
> [nginx-tag] Bump nginx tag to v0.7.4

- .circleci/circle_vm_setup.sh
In #446 I forgot to do the *circle machine* golang upgrade, so ddev testing was done with 1.8.3. This PR updates the version of golang installed on the circleci machine.
> Forgot to update the testing-local version of golang - followup to #446

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
A couple of titles in the PR template especially needed updating. Change "The Test" to "Manual Testing Instructions". Completely minor changes, can mostly be copied into other repos, except that our ddev issue template has started to become ddev specific, since we have outsiders creating issues and we need to nail down versions.
> Minor updates to github templates for clarity

- README.md
Homebrew is the most straight forward and is the expected way of installing software for many macOS users.
This PR solves the problem by listing homebrew as the first installation instruction for macOS. Docs provide code examples to download, install, and upgrade ddev. As well as a link to the homebrew download/install instructions - that user's without homebrew may use as a reference.
#434
> Make installation via homebrew the default instructions for macOS

- pkg/ddevapp/config.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/types.go
- pkg/plugins/platform/utils.go
A reoccurring issue in `ddev list` was its failure to list sites whose directories had been removed but containers were still running. This pitfall in `ddev list` made it possible for containers (which were no longer useful) to heap up on a user's machine if they repeatedly removed sites using `rm -r <dir>` instead of `ddev rm` - which stops all containers associated with a particular site.  
**TLDR;** check to see if a site's root directory exists. If it doesn't exist, store information about the site temporarily and list it with status "not found".
`ddev list` already had visibility into the ddev containers that were running on a machine, it simply would not include sites with missing directories because those sites would raise an error when attempting to initialize from a missing root …
> "ddev list" shows sites based on container, even if directory is removed: fix for #374

- docs/index.md
Homebrew install instructions only existed in the README.md and was not present in docs/index.md which gets picked up by readthedocs.
This PR simply adds the homebrew install instructions to docs/index.md.
#434
> Add homebrew install instructions to index.md for readthedocs. Fixes #434

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
#471: We've been having an enormous number of Circleci build failures during the setup-the-vm stage, and we don't have any visibility into the failure. And Circleci now (in latest build) has a docker version we can use successfully. So:
* Stop installing docker ourselves
* Turn on set -x so we can see what's failing
* Upgrade version of docker-compose we're using
* It seems we no longer have to download the signing key for mysql as the problem has sorted itself out. Getting the key was the most common failure.
> Revert to using Circleci's docker version, upgrade docker-compose, fixes #471

- docs/users/cli-usage.md
The install docs successfully got me up and running with a Drupal site. Hurray!
The docs suggest getting drupal via `git clone git@github.com:drud/drupal8.git`. A more modern way to start a Drupal project is `composer create-project drupal-composer/drupal-project:8.x-dev [drupal8] --stability dev --no-interaction`. See https://github.com/drupal-composer/drupal-project. Among other goodies, this gets you a site local drush which is the only real supported way to run drush with drupal 8.4 (coming next month).
> Use drupal-project instead of a bare Drupal site

- cmd/ddev/cmd/root.go
OP #479: Our update strategy is not working because we only refresh the update file *if* an update is found. Thus we're regularly running afoul of github's API limit, it even broke a test today. Basically, once the update file gets older than a week, every single invocation of ddev results in a hit on github.
Instead of refreshing the update file when an update is ready, it does it every time we hit the update interval (and before we even check for an update). 
Note: This also does the docker check *before* the update check, because the docker check is fatal and the update check is not. That lets the update check just return with a warning in some situations.
* Set the date on ~/.ddev/.update back to sometime more than a week in the past, then do a ddev commands. To set the date, try …
> Refresh updatefile on each check even if we're not updating, fixes #479

- docs/index.md
OP #480: Our macOS support said "Sierra", and we need it to say "Sierra and Higher". Minor change, just docs.
> Change usage to macOS Sierra and higher, fixes #480

- cmd/ddev/cmd/config.go
The ddev response after config was always saying "you can now 'pull'", but of course you can only do that with pantheon.
This turned out to be a simple bug, assumption of the name of the default provider being "" when it's actually ddevapp.DefaultProviderName.
Change the comparison. I switched it to a "switch" as well since it seemed like clearer code.
Try a `ddev config` and also a `ddev config pantheon` and verify that the correct response is given at the end of the config input.
No changes were made.
> Fix bug where provider was always assumed, fixes #437

- install_ddev.sh
#490 OP - We have fancy colors in our install script, but they totally blew up in a fresh ubuntu install.
There were 2 main issues at hand:
- Some instances of the color variables were written as $(VAR) instead of ${VAR}, causing them to produce errors, as the var name would be invoked as a command in subshell. These have been fixed.
- We were using tput for coloring. This is present in many systems, but we've seen it not present in a few linux variants (notably as an error produced by wp-cli). I've replaced the tput usage with escape sequences. I don't _think_ this was the actual issue causing OP, but I believe it should help reduce portability issues.
Run the install script on Ubuntu. It should not esplode.
Run the install script on OSX. It should not esplode either.
> fix installer script colors, remove tput dep, fixes #490

- pkg/plugins/platform/local_test.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
OP #463 - We want to ensure ddev works with the latest drupal 8 release. 
This PR changes the archive to use the official d8 release download instead of our test/demo drupal8 repo archive. Originally, I attempted to integrate the composer-built project from drupal-composer/drupal-project, but handling through composer takes over 4m testing locally, and we don't want to slow down our tests that much. Instead, we'll use the d8 release download, and we'll just have to remember to update the URL on "major" (8.x.0) releases.
#463
> use official d8 release for testing

- .gitmodules
- nightly_build.mak
We deprecated ancestors of docker.nginx-php-fpm-local, but didn't get them out of our submodules and nightly build.
This does that.
> Remove obsolete submodules from nightly build

- cmd/ddev/cmd/config.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/pantheon_test.go
- pkg/ddevapp/providerDefault.go
- pkg/ddevapp/providerPantheon.go
- pkg/plugins/platform/local_test.go
OP #476: We need to handle config without user prompting, so we'll add new flags to `ddev config`.
* Add new flags for configuration --sitename --docroot --pantheon-environment
* Rename Pantheon's "Environment" to "EnvironmentName", since there was also an "environment" and it was impossible to figure out which was which.
* Rename Config() to PromptForConfig() to make the code more readable.
* Refactor Config() so it doesn't return an error when there's no existing config.yaml - instead it only returns an error when the existing has problems.
Start with no site .ddev file.
* Test existing config paths (`ddev config`, `ddev config pantheon`
* `ddev config --sitename=junker99`, `ddev config --sitename=junker99 --docroot=docroot`
* `ddev config pantheon --pantheon-environment=dev …
> Allow command-line arguments for "ddev config", fixes #476

- docs/assets/fix-search.js
- mkdocs.yml
OP #528 - search on our docs on readthedocs isn't working.
This PR introduces a workaround found in https://github.com/rtfd/readthedocs.org/issues/1088#issuecomment-224715045 to get working search results again.
> workaround for readthedocs broken search rtfd/readthedocs.org#1088

- docs/assets/fix-search.js
- mkdocs.yml
#530 introduced a well-shared workaround for search broken on readthedocs mkdocs sites. Unfortunately the fix applied did not resolve the search issues. I looked a bit closer at a project I knew to have working docs search and found a variation on the js fix, but more importantly a difference in how extra js is defined in mkdocs.yml. This fix has been tested against a temporary alt version of the docs site and works as expected.
> re-workaround readthedocs broken search

- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/start.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
* OP #521 describes a situation where a site is running, but its directories have been removed. That reversion is fixed here.
* Around the same time I discovered that `ddev start` in a non-site directory no longer worked. 
* Fixes both of the problems
* (Will) add tests for both of those cases
* Create a site and remove its directory, then try `ddev list`. For example:
```
cd /tmp
mkdir -p junk/sites/default
cd junk
ddev start # Tell it the apptype is drupal7
mv junk junk.bak
```
then try a `ddev list`. You should get proper output.
* Try a `ddev start` in any directory without a .ddev
(In Progress): Tests for these two situations.
OP #521
> Fix panics on ddev list and ddev start (with no config), fixes #521

- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/start.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/pantheon_test.go
- pkg/dockerutil/dockerutils.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/testcommon/testcommon.go
In #495 (Command-line args for ddev config) a failed piece of logic allowed the provider to be overridden. This broke at least ddev pull, it may have broken several other things. 
* The bug fix is in pkg/ddevapp/config.go and is a simple logic rearrangement. 
* Adds explicit test for `app.Import()` to TestPantheonPull as well.
* Refactors DockerNetworkPreRun() from root.go into dockerutils.EnsureDdevNetwork()
* Missing DRUD_NONINTERACTIVE due to shortcut TestPantheonPull structure caused lots of consternation and odd chasing (only on linux/circleci). Along the way a few error messages were improved.
* platform.Config() was refactored to platform.CreateSettingsFile() to avoid the confusion between ddev's config.yml (everywhere else we use "config") and the application settings file.
Try …
> Fix failed override of provider introduced in #495

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/root_test.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/plugins/platform/utils.go
ddev rm, describe, and stop were unable to remove sites that were missing their config.yml or sites that did not have directories associated with them. This made it impossible to cleanup corrupted sites pointed out by ddev list.
This PR solves the problem by using a site's containers to grab it's site-name and using that site-name to run Cleanup() on the site. It also checks for a missing directory and if the approot is missing it skips `app.Down()` and uses `Cleanup()`.
Test this PR using the following steps:
- Start a site using `ddev start`
- `rm -r` the site directory
- `ddev list` the site to see that it reports its status as `app directory missing:`
- Use `ddev rm <sitename>` to remove the site 
Tests for `ddev rm` are run in `TestCleanupWithoutCompose`. Tests for `ddev describe` …
> ddev rm, describe, and stop are now reliable even when a site directory is missing; fixes #459

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/list_test.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/utils.go
Reviewing ddev-ui's usage of the new json output we found two immediate flaws:
* ddev was providing a shortened approot instead of the full path, which handicapped ddev-ui, which then had to re-convert the path.
* The 'url' portion of raw desc was a concatenated http+https url. 
* desc["approot"] is now the full path. (desc["shortroot"] is also provided)
* desc["httpurl"] and desc["httpsurl"] replace desc["url"]
`ddev list -j` and `ddev describe -j` to review the changes
The various tests that relied on url and approot were changed; additional assertions were added for shortroot, etc.
Note that the json output is incompatible with previous versions, as "url" is replaced by "httpurl" and "httpsurl".
> Fix discovered json output flaws

- cmd/ddev/cmd/describe_test.go
I seem to have committed the json fix in #543 with Windows tests still failing. I don't understand how this change could have not broken all the other tests, so will look at that. But this little fixup should solve the windows tests.
> Fix missed shortroot conversion in test, broke windows test only somehow

- docs/developers/surf-testmachine-setup.md
There was a (potential) step missing in installation of a macOS surf testbot. This improves the docs.
> Improve surf testbot installation instructions

- cmd/ddev/cmd/auth_pantheon.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/stop.go
End users don't recognize backticks, so we should use single quotes instead.
Simple find and replace of backticks -> quotes in user-facing text. There are a number of places in the codebase where we still use backticks in comments, but those were left in place.
Check error messages for the following commands:
* `ddev auth-pantheon`
* `ddev config`
* `ddev describe`
* `ddev exec`
* `ddev logs`
* `ddev remove`
* `ddev ssh`
* `ddev stop`
This is just simple text changes for end users. No tests needed.
https://github.com/drud/ddev/issues/404
> Use single quotes instead of backticks for user-facing messages, fixes #404

- cmd/ddev/cmd/root.go
- install_ddev.sh
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/version/version.go
As noted in https://github.com/drud/ddev/issues/491, we don't actually check for `docker-compose` anywhere, but it's a fundamental part of the ddev environment.
* Tests for `docker-compose` in the install script
* Tests for `docker-compose` in root.go
* Remove `docker-compose` from your path and run any `ddev` command. You should see an error about `docker-compose` not being installed.
* Add `docker-compose` back into your path and repeat. See no errors.
* Remove `docker-compose` from your path and attempt to use the install script to install. You should see a message about docker-compose not being installed.
* Add `docker-compose` back into your path and repeat. See no docker-compose related message.
No test for the failure path was included here because the existing tests already use …
> Check for docker-compose at install and run time, fixes #491

- Makefile
- pkg/version/version.go
We had a nightly build failure caused by docker.nginx-php-fpm-local due to our pinning of php7.1. This bumps docker.nginx-php-fpm-local to v0.8.2
This should pass after @cweagans docker-pushes v0.8.2 but will fail right now, but that's OK. We'll just rebuild after that. I just wanted to get the PR up.
> Bump nginx-php-fpm-local version to v0.8.2

- pkg/dockerutil/dockerutils.go
The original expected outcome of the issue is:
> ddev ssh should only show an error if it failed to actually get you into the shell on the container.
However, we don't have any way of distinguishing between a failure to get a shell in the container and a failure of a command executed in that shell (for instance, if you run `asdfasdfasdf` inside the container and then immediately exit, `ddev ssh` will report an error).
At @rfay's suggestion, we're just going to completely ignore the error from docker-compose. This way, we don't erroneously report errors in non-failure cases, but this means that we also don't report errors when there actually is an error.
* `ddev ssh` should get you a shell in the container
* `ddev ssh -s asdf` should error: ERROR: No such service: asdf
* `ddev ssh` …
> "ddev ssh" inappropriately returns (and exclaims) last executed command value, fixes #527

- .circleci/config.yml
We like to have stable Circleci behavior, but also keep up-to-date with current Docker versions. This updates the Circle image to have their latest docker and docker-compose. Full information on circleci machine versions is at https://circleci.com/docs/2.0/configuration-reference/#machine
Update circleci machine version.
> Update circle machine image for later docker

- .circleci/config.yml
We currently run a jenkins job to trigger the nightly build, but Circleci now offers this as a feature. [Circleci Instructions](https://circleci.com/docs/2.0/workflows/?mkt_tok=eyJpIjoiWVdVNE4yRTRaalpoWmpObSIsInQiOiJiYWY4ZGpybmU2VUExdVdYQklBcDlvbWJZMnFZNnpsVlVPWk9ybzQ3Y1VRWGxpdjJtbDdKcktHK01STEpSOXpjWThnbjg1K3hrSTBWb0JXWnRveHVmZHlqaUNzTzNCYXhhRE45ZHFTbElqQjdIQVM2eVkyb3RjTm9aSVwvRm1TangifQ%3D%3D#scheduling-a-workflow)
Use the "trigger' feature in workflows to get circleci to automatically trigger, instead of hitting the circle API
Just look and see what happens. This is set up and testing currently on rfay/ddev, so you can see the behavior there, https://circleci.com/gh/rfay/ddev/tree/master
Unfortunately the key stanza must be on *master* so it's hard to easily test in a PR. However, it's …
> Add automation of nightly build

- cmd/ddev/cmd/version.go
- cmd/ddev/cmd/version_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/version/version.go
`ddev version` doesn't show any information about the TLD used to spin up sites.
Simple addition of the DDevTLD constant to the output of `ddev version`
Run `ddev version`
One extra assertion was added to test for the TLD in the output.
https://github.com/drud/ddev/issues/441
> Add the ddev domain to the output of ddev version

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/sequelpro.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/pantheon_test.go
- pkg/ddevapp/providerDefault.go
- pkg/ddevapp/providerPantheon.go
- pkg/ddevapp/utils.go
- pkg/output/text_formatter.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon.go
In #458 we already refactored the platform/plugin/local into ddevapp. The final step to finish that is to move the config members up as full members of the ddevapp. This PR does that move.
Everything should work as it always have. Test it out.
There should be no impact of any kind on the end user.
There is no new functionality, and no new tests.
OP #458
Refactor into ddevapp https://github.com/drud/ddev/pull/561
> Refactor all config into the ddevapp, fixes #458

- build.sh
When we push a new version of a docker image and keep the tag the same, our surf testbots never update, so may cause tests to fail because the new image is not brought down.
At the beginning of the test cycle in build.sh we update existing images with a `docker pull`
Try running build.sh. You have to have surf though. I think this is a pretty simple and low risk approach.
Really I think that just reviewing the surf results on this PR is good enough.
> Surf build.sh needs to update any images that may be cached

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
There were a couple changes in #572 that were valuable separately from switching to mariadb. They've been cherry picked into this branch.
> Improve comments and signature on 'tail' options in ddev logs testing

- pkg/dockerutil/dockerutils.go
I happened to notice in code (which I should have noticed when I reviewed) that 'Windows' is capitalized in the docker-compose version check, which means that code was never executed, which means we must not need it. So this PR removes that if that changes 'docker-compose' to 'docker-compose.exe'. 
Before this can be pulled it must be manually tested on Windows.
> Remove special windows handling for docker-compose.exe since it has a typo anyway

- Makefile
- docs/users/extend/customization-extendibility.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/testcommon/testcommon.go
- pkg/version/version.go
We'd like to be able to support more than one PHP version.
Introduce the php_version variable in our config, default it to 7.1, pass it to nginx-php-fpm-local, which as of https://github.com/drud/docker.nginx-php-fpm-local/pull/43 can support php versions 5.6-7.2
Adds a paragraph of documentation for those who want to change the php_version.
in a fresh site, set `php_version: 5.6` or whatever in your .ddev/config and start it. Note that docker-compose.yml *must* be deleted for this to work, as a new docker-compose.yml needs to be generated.
There is no new testing at this point. We may want to add tests for various PHP versions, but there is minor testing in docker.nginx-php-fpm-local to make sure we have the right versions. Currently the default version (php7.1) will be used. …
> Update to support DDEV_PHP_VERSION in config and defaults

- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
The UI needs to be updated when the site list changes (https://github.com/drud/ddev/issues/552).
This PR adds a `--continuous` flag to `ddev list`. When set, ddev won't exit, and instead will re-emit site information after a hardcoded delay of 1 second. This works for both the standard table output and JSON output.
* Run `ddev list` - should work as before
* Run `ddev list -j` - should work as before.
* Run `ddev list --continuous` -- should output table continuously. Open a separate terminal window and create a ddev environment, and you should see the output change as the site comes up.
* Run `ddev list --continuous -j` -- should output json continuously. Open a separate terminal window and create a ddev environment and you should see the output change as the site comes up.
WIP …
> Add --continuous for ddev ui

- cmd/ddev/cmd/config.go
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/wordpress.go
Apptype detection is done inline in existing code, which makes it hard to maintain. We're now moving all types of app-specific logic into its own file in ddevapp. This PR does that for drupal, wordpress, and php. 
This builds on https://github.com/drud/ddev/pull/574 (generic, extensible apptype handling)
* Add an appTypeDetect member to the appTypeMatrix,
* Implement the members for drupal and wordpress
* Create the master user DetectAppType()
Try it out on some sites. Note that only drupal7, drupal8, and wordpress (and the default "php") are currently implemented.
This adds one test for detection and updates previous tests.
#574 is the basic PR, with much background.
OP: #535
> Add generic apptype detection using apptype approach in #574

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/wordpress.go
One of the one-off things we do is a special warning about fixing the URL stuff when importing a wordpress database. This PR pulls that out of inline code and into the apptype matrix, adding a simple function to wordpress.go to handle it.
Import a db into a wordpress site. You should get the warning. Import into a Drupal site and you should not get the warning.
I didn't add any testing as there was no behavior change. However, I'm open to testing ideas.
The main tracking here is the base-level PR in #574.
The OP is #535 
I *think* this is the last thing that absolutely must be done for #535, although I expect we'll learn something from our first *new* apptypes.
> Add postImportDBAction capability to apptype matrix

- README.md
I noted that our badges/shields on  on https://github.com/drud/ddev/blob/master/README.md were looking pretty sad. It turns out the badge year seems to have to be updated periodically (like now). The Circleci failing shield is apparently a result of my experimentation with local config files, so it should be fixed with a successful build shortly. 
View the results at https://github.com/rfay/ddev/blob/20180104_fix_maintained_status/README.md
> Update maintained badge to 2018

- pkg/ddevapp/ddevapp_test.go
On darwin it seems that the golang table can write out things breaking lines in a way that we don't expect. This may have to do with terminal width expectations, although I can demonstrate it a number of ways. I don't know why it happens on some commits and not on others.
This is the output on the failed assertion. You'll have to make it really wide to see what's happening. But we're listing both http and https URLs and in the process the table manager (with a super-wide appdir) is wrapping in a way that the assertion didn't expect.
Error:		"NAME  TYPE     LOCATION                                                                                                                         URL(s)                   STATUS …
> Fix TestListWithoutDir problem on Darwin

- README.md
- docs/index.md
- docs/users/cli-usage.md
- docs/users/developer-tools.md
- docs/users/extend/additional-services.md
- docs/users/extend/custom-compose-files.md
- docs/users/extend/customization-extendibility.md
- docs/users/extending-commands.md
- docs/users/providers/pantheon.md
- docs/users/step-debugging.md
* #599 pointed out that we had inaccuracies about the use of the "remove" command. The help is right, but the docs were wrong. This fixes that.
* On a casual read-through I also edited some usage for clarity.
* For #526 (changing usage of "site" and "app" to "project" I changed "site" to "project" in a number of cases. 
* For #597 make sure it's clear that docker-compose is required.
Read the docs.
- #599: Inaccuracies about `ddev remove`
- #526: Change "site" to "project"
- #597: Make sure docker-compose requirement is explicit.
> Update docs for remove (and project/site) fixes #599, for #526

- pkg/ddevapp/ddevapp_test.go
This is another try at https://github.com/drud/ddev/pull/593, which seems to behave differently at various times. I did in fact make a mistake in the regexp in that pull, assuming that by default "." would include newline, and it doesn't by default. This fixes it. Note that this issue is currently bedeviling https://github.com/drud/ddev/pull/596, at least some of the time.
> Improve regexp so "." regex class includes newline in test

- Makefile
- cmd/ddev/cmd/config.go
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/genericapp.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/wordpress.go
- pkg/version/version.go
We need support for drupal6
* Adds d6 detection
* Improves d7 detection
* Adds d6 settings creation
* Adds capability for an apptype to override config, so for d6 this means settings the php_version
* Bring up a d6 site, review it.
* Review config.yaml
* Import a database and review settings.php or settings.local.php
* Tests are next here
After https://github.com/drud/docker.nginx-php-fpm-local/pull/47 makes it in we have to add a new commit with the new minor release on nginx-php-fpm-local
> Add support for drupal6 

- .circleci/config.yml
Our nightly build was broken by adding improved tests to the cmd/version_test.go. Instead of just using the in-code version information, the new tests actually ran ddev to get the version. Unfortunately, we had a redundant stanza of the .circleci/config.yml that tested the whole thing a second time with the special-tag executables but without overriding for comparison. Note that cmd's TestVersion was working fine in the first round of testing (when the proper variables were provided.)
I attempted to add more documentation to help everybody understand what's going on in the nightly_build stanza. 
As far as I can tell, the removed stanza had no reason to exist.
Testing: Use the instructions in .circleci/README.md to run a full nightly against this branch. Note that you have to enable …
> Fix nightly build by removing clashing circle config stanza

- cmd/ddev/cmd/config.go
In the multi-CMS rework, I seem to have made it so you can't use `ddev config --docroot=.`, for example, without specifying the apptype (you have to do `ddev config --apptype=drupal6 --docroot=.`
This problem breaks ddev-ui (which does not provide --approot)
Check to see if appRoot is empty and if so detect. The detection was already there, but the failure here was higher up.
* Run `ddev config --docroot=.` and see if it works. Try other combinations of things with ddev config. Look at `ddev config -h`.
* Test with ddev-ui. Without this patch, "add from repo" is nonfunctional. With this patch it should work OK.
OP #616
This adds a new flag --projectroot, which is the same as --approot. That should become the new standard. But since people don't use ddev config with flags, we should be ok.
> Make ddev config work with args when no --apptype provided, fixes #616

- README.md
- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/typo3.go
We want to officially detect and support typo3.
* Typo3 is detected
* Import-db and related actions work
Spin up a few typo3 sites, and import the db for them. I would imagine we'll learn something along the way. 
The assumption (enforced by the code here) is that typo3 must already have been through an installation process and a typo3conf/LocalConfiguration.php has been created *by typo3*. On import-db, we add an AdditionalConfiguration.php that overrides the database credentials.
Typo3 creates many more files and has much more outside-the-db configuration than we've experienced before, so I'm not entirely sure what the result of that will be.
Tests still being visualized.
OP #570 - "Official support for typo3"
It looks to me like typo3 is pretty specific about versions. For example. a …
> Typo3 support for ddev, fixes #570

- build-tools/Makefile.example
- build-tools/makefile_components/base_build_go.mak
- build-tools/makefile_components/base_build_python-docker.mak
- build-tools/makefile_components/base_test_go.mak
- pkg/servicetest/servicetest_test.go
It's time to move to golang v1.9.3, this brings in the new build-tools that does that. https://github.com/drud/build-tools/releases/tag/1.5.3
> Updated build-tools to 1.5.3

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/start.go
- docs/users/cli-usage.md
- docs/users/troubleshooting.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router.go
- pkg/ddevapp/router_test.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/utils.go
- pkg/ddevapp/wordpress.go
- pkg/testcommon/testcommon.go
- pkg/util/network.go
OP #481: We need to allow people to choose a different router port
New elements in config.yaml for each site allow the user to override router_http_port and router_https_port
1. Stop the project and delete the .ddev/docker-compose.yml (New respect for an environment variable in the docker-compose.yml is required)
2. Add "router_http_port: 8080" to a site's config.yaml and `ddev start`. The correct URL should show everywhere that URLs are displayed.
> Support router_http_port and router_https_port in config.yaml, fixes #481

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/ddevapp.go
At the very end of the --show-config-location add-on in https://github.com/drud/ddev/pull/618 I seem to have added a reverse piece of logic which made it not work at all.
* Fix that, to make `ddev config --show-config-location work again`
* Add a "raw" section so that ddev-ui can more easily parse the return information.
* Fix a bug I discovered where a sitename containing underscores would result in a very misleading error "no sitename provided", and where that wasn't even shown when `ddev config` was run with args.
* Verify `ddev config --show-config-location` and `ddev config --show-config-location -j` in both configured and unconfigured directories (or subdirectories)
* Verify behavior of `ddev start` and related when an invalid "name" (especially underscores) is provided in …
> Regression fix: Improve --show-config-location

- cmd/ddev/cmd/hostname.go
ddev-ui needed better output from the `ddev hostname x y -j` command, so it could determine what had actually happened (and prevent some extra permission escalation).
This changes the ddev hostname json output like this:
```
ddev hostname "d7git.ddev.local" 127.0.0.1  -j
{
"level": "info",
"msg": "",
"raw": {
"detail": "hostname already exists in hosts file",
"error": "SUCCESS"
},
"time": "2018-01-29T18:19:43-07:00"
}
rfay@Randy-Air:~/go/src/github.com/drud/ddev$ ddev hostname "d9git.ddev.local" 127.0.0.1  -j
{
"level": "fatal",
"msg": "Could not write hosts file: open /etc/hosts: permission denied",
"raw": {
"error": "WRITERROR",
"full_error": "open /etc/hosts: permission denied"
},
"time": "2018-01-29T18:19:57-07:00"
}
```
* Use `ddev hostname -j somename 127.0.0.1` where "somename" …
> Improve json output of hostname command to give explicit results

- pkg/ddevapp/settings_test.go
- pkg/ddevapp/typo3.go
TYPO3 trademark/brand name should be written uppercase.
This of course doesn't influence code, just comments and documentation.
see: https://typo3.org/about/the-trademarks/
> Correct brand name typo3,Typo3 -> TYPO3

- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/settings_test.go
Needs more ~cowbell~ Backdrop support
Adds backdrop support
Download a Backdrop tarball, use the build artifact, and stand up a site. We're looking for parity with 
None yet, but WIP.
https://github.com/drud/ddev/issues/571
* Backdrop ships with a settings.php included, so we probably shouldn't overwrite that under any circumstances. Right now, the settings file generation doesn't actually do anything. I was thinking that for backdrop, maybe we should generate a settings.local.php instead? The default settings.php includes settings.local.php OOTB if it exists, so that would be a relatively straightforward way to handle this.
* I clicked around a bit in the Backdrop interface, and everything seemed to work. It did prompt me to go through the utf8mb4 conversion though. Is there something we …
> Support Backdrop CMS

- docs/users/cli-usage.md
The wonderful @horncologne noticed we don't have TYPO3 in the list of quickstart guides at the top of this document.
Add TYPO3 to the list!
> Add TYPO3 to the list of quickstart guides

- mkdocs.yml
#630 - Troubleshooting doc missing from readthedocs site
#637 - Missing "Edit on Github" links on readthedocs pages, missing readthedocs footer
- The troubleshooting docs page was missing from the mkdocs.yml TOC. Adding it restores the missing page and fixes the link we provide in ddev that's currently broken
- Updates the mkdocs.yml metadata to get the "Edit on Github" links to show in readthedocs. From what I can tell, this update makes it a static link back to the ddev github page. The only examples of RTD sites I can find with more specific edit links are using RST. Similarly, any of the markdown driven sites I could find with the edit link were static to their repo homepages as well.
How it doesn't :( :
- readthedocs has a footer in the menu sidebar that pops-up, with links to EPUB, …
> add troubleshooting to toc, update mkdocs meta

- Makefile
- pkg/version/version.go
TYPO3 requires the intl extension
The container already has the intl extension in v0.9.2, so we should use that version.
No user facing changes other than the extension being installed. `php -i | grep intl` should return some things in the container.
No automated test changes.
https://github.com/drud/ddev/issues/634
> Add intl extension for TYPO3

- Gopkg.lock
- vendor/github.com/drud/go-pantheon/pkg/pantheon/site.go
The invited_by_id field is apparently not always what we expect, and we don't use it. So stop parsing/using it.
This PR brings in v0.1.0 of go-pantheon, which just ignores the invited_by_id, https://github.com/drud/go-pantheon/pull/14
OP: #645 
Basically we only know one person who can reproduce this. He's tested it. It's probably good to go. We don't know what the bad json looks like.
> Remove parsing of invited_by_id because it breaks and we don't use it, fixes #645

- .circleci/circle_vm_setup.sh
- cmd/ddev/cmd/logs_test.go
It's time to upgrade to golang 1.10.
I'm actually forced to this by #657 where I have a weird problem that can't be reproduced on mac or windows, and only occurs with go 1.9 on Ubuntu 14.04, or that's the conclusion I'm coming to. It builds clean on Ubuntu 14.04 with go 1.10, so I'd rather just do this upgrade than chase it. After this goes in, I'll rebase that one.
> Upgrade golang to 1.10 for testing, docker-compose 1.19

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
Drupal8-specific config values got lost in the appmatrix refactor, we need to get them back. The most obvious was the loss of `$settings["hash_salt"]`
* Splits the d7 and d8 config sections. 
* Uses the right one for the detected apptype
* Removes IsDrupal8 from the config struct
I'm not happy with the very, very not-DRY way we're doing Drupal and Backdrop settings creation. Loads of code and it's all repeated. However, it's what we've decided to go with for now, and this just does it again.  Maybe sometime when we're feeling more pure we can fiddle with it and clean it up.
* Do a ddev import-db on a d7 and d8 site, and verify the settings.local.php that gets created.
OP #647
> Make drupal 7 and drupal 8 settings distinct, recover settings[hash_salt], fixes #647

- .circleci/generate_artifacts.sh
- install_ddev.sh
For OP #501 one of the things we want is to prevent the initial docker pull that happens initially, so bundle all the containers in the artifacts we provide. 
* Change "osx" to "macos" in artifact names
* Add ddev_docker_images.tar to the artifacts, so all can be downloaded at once.
* Delete your drud containers any way you like
* Use the install script to install ddev
* Download the ddev_docker_images.tar
* Load the images with `docker load -i /path/to/ddev_docker_images.tar`
* Verify with `docker images | grep drud` that the new images were loaded
* When you do your first "ddev start" nothing should have to be pulled.
This didn't fully work out as I had hoped. I had been planning to put the images into the download tarball, but that resulted in a tarball over 1G, which would be an …
> Add docker images to artifacts for #501

- install_ddev.sh
instruction for installing bash completion shows wrong filename "ddev_bash_completions.sh"
change filename in output to "ddev_bash_completion.sh"
> [BUGFIX] fix typo in install instruction output for bash completion

- docs/users/step-debugging.md
We didn't give instructions about linux usage with xdebug.
Adds the results in #610.
Try xdebug with PHPStorm or another environment on a Linux machine, as described [here](https://github.com/rfay/ddev/blob/2fd36cf15e1ff7bbb9e9f4927f40b68c3bce8092/docs/users/step-debugging.md).
OP #610
> Add Linux xdebug instructions, fixes #610

- docs/developers/building-contributing.md
We didn't tell developers where our containers are. We should. And $GOPATH has caused more than one to stumble.
Add a bit of doc.
> Add docs info about using GOPATH and where containers are

- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/util/network.go
We didn't add the full suite of tests for d6/backdrop/TYPO3 when implementing those and it's time.
This is not intended to solve the fact that we don't currently use any of the sites that we spin up with ddev, or see if they're working. That problem is deferred to https://github.com/drud/ddev/issues/677
This PR simply fills in test tarballs and related info for other CMSs, and does some minor improvements to the testing process. New tarballs are provided in the new repo set up for their storage.
Look at the Circleci test results and make sure everything is being hit. 
Fixes #617
> Add ddevapp tests for drupal6, backdrop, TYPO3, fixes #617 Pull on 2018-03-6 #TRIVIALREVIEW

- pkg/ddevapp/templates.go
OP #676: Our web and db containers never do recover when a restart happens, so restarting them just obscures the cause. This PR changes the restart for the "working" containers from "always" to "no".
@mglaman also points out the unexpected side-effect of the current restart: always policy: A machine reboot or docker restart results in stopped projects magically starting unexpectedly. 
This change should result in more predictable ddev container behavior.
Failing containers won't restart any more.
ddev ssh into the web container. `killall supervisord`. This will ruin the container, and it will show up as unhealthy in a bit, but won't restart.
ddev ssh -s db into the db container. `killall mysqld`. This will ruin the container, and it will stop, and it will show up as stopped in `ddev list` …
> Switch restart to 'no' for main containers, fixes #676

- pkg/ddevapp/ddevapp.go
OP #478 
We used to try to delete the settings.php or settings.local.php when deleting database (`ddev remove --remove-data`) but this isn't necessary and can just create confusion. 
It also doesn't make sense to delete the settings file just because we're dropping the database.
* Create a Drupal site and use it
* check that Drupal has done its silly thing and set sites/default to 0444.
* `ddev rm --remove-data` and look for no error.
OP #478
> Don't remove settings.local.php when removing database, fixes #478 PULL 2018-03-06 #TRIVIALREVIEW

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
OP #663 - Our users would love to have docroot detected for them during `ddev config`.
Check if any of the following directories exist and default to the first one found
* web
* docroot
* htdocs
* _www (legacy Platform.sh)
* public
Run `ddev config` and see that the docroot discovery re-uses `app.Docroot` or detects an existing directory if present.
Added `TestConfigCommandDocrootDetection` which tests automatic detection of `web`, `htdocs`, and `docroot`.
#663
> Add Config docroot detection, fixes #663

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/sequelpro.go
- cmd/ddev/cmd/sequelpro_test.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
- docs/users/cli-usage.md
- docs/users/extend/custom-compose-files.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
OP #526: We're trying to use "project" everywhere when talking about a ddev site/app/whatever, in our docs and whenever ddev interacts with the user. This PR attempts to do that.
Use ddev. Look at the output. Review the docs.
OP #526
> Change "app" and "application" to "project" in user-facing docs/output, fixes #526

- docs/users/cli-usage.md
The documentation part of TYPO3 quickstart turned out not to be too helpful in terms of setup.
Links and needed information was added. Also, one misleading sentence has been removed.
Read the cli-usage part of documentation (TYPO3 quickstart).
none, it is only documentation
nothing
> Adjusted the TYPO3 quickstart section

- .circleci/generate_artifacts.sh
#724 requests xz tarballs of ddev_docker_images, this adds that packaging.
> Provide xz tarball of ddev_docker_images, fixes #724

- Gopkg.lock
- cmd/ddev/cmd/root.go
- pkg/version/version.go
- vendor/github.com/Masterminds/semver/version.go
#737: Docker-compose latest edge is 1.20.0-rc2. But [semver does not support versions with a pre unless the check has a pre](https://github.com/Masterminds/semver/issues/21). So our docker-compose version check was broken.
* Update the constraint to include a "pre" for both docker and docker-compose.
* Fix the logic about skipping pre-validation on commands like "version" and "hostname" to fix #711
With latest edge docker-compose, try `ddev version`, `ddev hostname` with and without this. 
For brute-force testing, create a script called docker-compose in a location which is *not* normally in your $PATH (like ~/tmp) with this content:
```
#!/bin/bash
echo "0.5 "
```
```
export PATH=~/tmp:$PATH
```
and run `ddev start` and `ddev list`, which should fail with that content. Run `ddev version` …
> docker-compose version check failure, fixes #711, fixes #737

- .circleci/config.yml
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
See issue #692
After writing the project config, also write a settings files via `app.CreateSettingsFile()`
#692
* No obvious break changes come to mind.
> Create settings file when configuring project, fixes #692

- Makefile
- cmd/ddev/cmd/logs_test.go
- docs/users/step-debugging.md
- pkg/version/version.go
I think this will fix #664 "TYPO3 environment extremely slow"
From https://github.com/drud/docker.nginx-php-fpm-local/pull/57 description of the container change:
People complain that ddev is slow. It was.
If we turn off xdebug by default it's 6x faster. 
I was always wrong about its impact
d8 web-based install:
macOS 10.13.3 8GB memory MacBook Pro (Retina, 13-inch, Early 2015
Processor: 2.7 GHz Intel Core i5
Docker 17.09.0-ce-mac35 (19611) default 2CPU, 2GB memory
Test: Install d8 8.5 HEAD via gui/web. "Install site"
with xdebug on: 12:34 
with xdebug off (phpdismod xdebug +killall -1 php-fpm): 2:08
6x faster
Delete your .config.yaml (or delete the web image line) and delete your docker-compose.yaml
ddev start.
Try things out.
nginx container PR: …
> Disable xdebug by default for 6x speed improvement fixes #664

- docs/users/cli-usage.md
Features in [Milestone v0.16.0](https://github.com/drud/ddev/milestone/26) required documentation.
The three issues were related as it pertains to the timing and mechanism by which DB settings files were generated. This attempts to address these deficiencies.
* [User documentation/support: settings.php/settings.local.php support](https://github.com/drud/ddev/issues/468)
* [import-db fails when unable to manage settings files, should warn instead](https://github.com/drud/ddev/issues/704)
* [Document settings file creation and what it means to users #743](https://github.com/drud/ddev/issues/743)
> Documentation updates to address #468, #704, #743

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
We were blindsided by a change made in Docker-ce stable linux in recent (near) release. We really want to be testing with current stable as that is the most likely thing people will be using.
Use docker's documented technique to install: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1
> Make circleci install current stable Docker-ce

- docs/index.md
- docs/users/linux_notes.md
- mkdocs.yml
Since #745 we Linux users don't have the writability problems they once had with files. 
However, #754 reminds us that Linux users need to do the required docker-ce setup steps.
Out with the old, in with the new. Docs only
> Docs: Remove special linux filesystem instructions, add docker-ce post-install, fixes #754

- pkg/version/version.go
I noticed in the Drupal #mentoring channel that somebody actually had Docker 17.05 and they got the bogus warning 
```
$ ddev start
The docker version currently installed does not meet ddev's requirements: 17.5.0-ce is less than 17.05.0-ce-alpha.1
```
Although we really don't want people using docker that old, still the comparison should be correct, and the typo fix here should accomplish that.
> Fix docker constraint typo

- pkg/ddevapp/ddevapp.go
Currently, if someone uses import-files on Backdrop, TYPO3, or Drupal6, ddev will destroy the entire approot. Nothing will be left.
This is a result of us never implementing import-files support for those CMSs, and of course, a rather catastrophic coding failure.
Check to see if the files directory has been set, and if it has not, halt the operation.
This is a stopgap solution only, intended to stop the bleeding. The actual solution will be done in https://github.com/drud/ddev/issues/666 but I didn't want to wait for that.
Run ddev import-files on D6 with and without this. Make a tarball of your directory first!
> Add failsafe so we don't blow away the repository when import-files on D6/TYPO3/Backdrop

- Makefile
- pkg/ddevapp/templates.go
- pkg/ddevapp/testdata/.ddev/nginx-site.conf
- pkg/version/version.go
See https://github.com/drud/docker.nginx-php-fpm-local/pull/65
There was minor confusion (especially in the TYPO3 world) when nginx moved to port 8080. There were two problems:
* It was really hard to set the trustedHostPattern to something that worked
* Redirects from "typo3" to "typo3/" tended to pick up the 8080 port, so the redirect from http://typo3git.ddev.local/typo3 would be http://typo3git.ddev.local:8080/typo3/
It turns out that the redirect problem was completely a separate problem, and it's fixed in the [nginx-php-fpm-local](https://github.com/drud/docker.nginx-php-fpm-local/pull/65) PR drud/docker.nginx-php-fpm-local#65
* Switches the internal port back to port 80
* Introduces relative redirects to avoid getting the port mixed up in the redirect.
* Normal usage with a variety …
> Put web container internal port back to port 80

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/start.go
- docs/users/extend/additional-hostnames.md
- mkdocs.yml
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
- pkg/testcommon/testcommon.go
- pkg/util/network.go
- pkg/version/version.go
We need to support multiple hostnames for multisite applications for #620 
Unlimited hostnames.
From the config.yaml self-documentation:
```
#additional_hostnames:
```
* Delete your .ddev/docker-compose.yaml
* Optionally run `ddev config` for the extra documentation it will put in config.yaml
* Add some additional_hostnames to your project, use `ddev start` and `ddev describe` to explore and hit them.
OP #620
> Multi-hostname support, fixes #620

- pkg/ddevapp/ddevapp.go
In https://github.com/drud/ddev/issues/760 @rickmanelius discovered that the output on start/restart/pull did not have proper URLs if the router_http_port or router_https_port are set. (the port specification was missing).
Add the port specification in GetAllURLs().
With ports set to 8080/8443: 
```
$ ddev start
...
Successfully started montclair
Your project can be reached at http://montclair.ddev.local:8080, https://montclair.ddev.local:8443, http://www.montclair.ddev.local:8080, https://www.montclair.ddev.local:8443, http://www1.montclair.ddev.local:8080, https://www1.montclair.ddev.local:8443, http://www2.montclair.ddev.local:8080, https://www2.montclair.ddev.local:8443, http://en.montclair.ddev.local:8080, https://en.montclair.ddev.local:8443, http://fr.montclair.ddev.local:8080, …
```
> Fix missing port on urls at startup by fixing GetAllURLs()

- docs/users/cli-usage.md
@nerdstein pointed out an error in our docs with the name of the php-fpm log. This fixes that. Docs only.
> Fix reference to php-fpm.log, docs only

- docs/users/developer-tools.md
Tell users about database management options with ddev
See #769 
Add information about the phpMyAdmin service included in ddev. 
Add explanation of `sequelpro` command
Visit
https://ddev.readthedocs.io/en/latest/users/developer-tools/.
https://github.com/drud/ddev/issues/769
> Add mention of phpMyAdmin and the Sequel Pro command

- pkg/output/output_setup.go
We've been emitting really ugly escape characters instead of colors on Windows for a long time, OP #363 
Finally outputs nicer stuff.
Run basic commands on Windows (in both cmd and git-bash), on Linux, and macOS and verify basic behavior.
The colors in cmd are not exactly the same, but IMO they're good enough.
I don't know how to test this in our current testing environment.
OP #363
> Use colors on windows instead of funny characters, fixes #363

- docs/users/extend/custom-compose-files.md
PR https://github.com/drud/ddev/pull/215 has changed the `com.ddev.container-type` label to 
`com.docker.compose.service`.
Documentation  https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/
and solr example needs to be updated.
> Remove com.ddev.container-type from documentation

- docs/users/extending-commands.md
* Remove deprecated `apt-get` function in apache container 
* Changed directory of composer.json
> [BUGFIX] Update TYPO3 Example

- .circleci/config.yml
- .circleci/generate_artifacts.sh
The xz compression of our docker images takes *forever*. It was added for quicksprint, and is only needed on releases. So remove it from normal builds.
> Only build xz images on tag build, fixes #801

- pkg/ddevapp/typo3.go
Problem:
`The current host header value does not match the configured trusted hosts pattern! Check the pattern defined in $GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] and adapt it, if you want to allow the current host header 'website.ddev.local:8080' for your installation.`
[edited by rfay]
This fixes half of #680 - support trusted hosts patterns for both TYPO3 and Drupal8
> [BUGFIX] Trusted hosts pattern for TYPO3, for #680

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
- pkg/testcommon/testcommon.go
OP #799 explains our trouble with $COLUMNS and $LINES inside `ddev ssh`.
Set those values when we use docker-compose.
`ddev ssh` with and without and observe the behavior on a long line.
> Set COLUMNS and LINES in container shell, fixes #799

- docs/users/extend/custom-compose-files.md
- docs/users/extend/customization-extendibility.md
OP #757 points out that especially TYPO3 users need to set environment variables in the container. It's actually quite easy to do (without editing the main docker-compose.yaml). This just tells how to do it.
Thanks @kaystrobach - Hope you can review this.
Adds docs with simple technique.
> Document adding extra env variables, fixes #757, also #758 (docs only)

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
There were two problems here:
1. It would pick up docker-compose* (like docker-compose.yaml.bak)
2. The docker-compose.override.yaml was being discarded, so never did any overriding at all.
* Complete logic change; a new slice is built instead of trying to re-use the old one.
* Error checking in case both docker-compose.yml and docker-compose.yaml exist, and in case docker-compose.override.yaml and yml exist. 
* Create docker-compose.*.yaml with files like this example docker-compose.1.yaml:
```
version: '3'
services:
web:
environment:
- TEST1="from docker-compose.1.yaml"
- TEST="TEST value provided by docker-compose.1.yaml"
```
* Create a docker-compose.override.yaml that overrides TEST
* Start the project, `ddev ssh`. Verify that TEST1 or related exists and has right value. Verify that …
> Revamp docker-compose file ordering and choosing, fixes #815

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/restart_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/testdata/config.yaml
- pkg/version/version.go
OP #762: 
* Stop default override of webimage etc. Now, if they are included in config.yaml, they will be respected, but they are not written by `ddev config`
* Version the config.yaml file with the ddev version.
* Pester the user if their config.yaml doesn't have the same version as ddev's version.
* Try a `ddev start` on a currently-setup project. It should complain about the config.yaml version.
* Try adding a specific webimage: yaml element, like `webimage: drud/nginx-php-fpm-local:v1.2.0` and `ddev start`. It should start with that image.
* Try `ddev config` and verify that the new config.yaml has no image statements populated.
The existing tests are probably adequate and were updated for this.
OP #762 
Related #713
> Stop using container versions in config.yaml, version the APIVersion, fixes #762, fixes #713

- cmd/ddev/cmd/logs.go
- pkg/ddevapp/ddevapp_test.go
OP #719: Currently `ddev logs` only works against running containers, so is useless when trying to debug a stopped container (perhaps stopped for a healthcheck failure). This commonly happens when people add custom config that is broken. But then `ddev logs` doesn't help them and we have to coach them on using the more arcane docker logs options.
There was an explicit stanza that forbade getting logs on stopped containers. Remove it.
* Start a project
* Stop the project
* Run `ddev logs` and `ddev logs -s db` to see the logs from the project.
I didn't add anything.
OP #719
> Make ddev logs work against stopped project/container, fixes #719

- docs/users/troubleshooting.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
OP #762: We keep having to tell people to delete docker-compose.yaml on ddev upgrades. We made the decision to take control of docker-compose.yaml
This PR addresses the changes for docker-compose.yaml, another PR will address the changes to config.yaml handling.
* Looks for docker-compose.yaml `#ddev-generated` in docker-compose. If not found, renames the file to docker-compose.yaml.bak and warns the user.
* Creates the docker-compose.yaml on every start
* Overrides can be done in docker-compose.*.yaml
* Run `ddev start` with this version
* Existing docker-compose.yaml should be renamed to .bak, and new one created.
* Run it again, with or without changes. A new one should be created. No warning should be given.
Nothing at this point.
OP #762
> Override docker-compose.yaml on ddev start, fixes #762

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
- .circleci/generate_artifacts.sh
- Makefile
- docs/index.md
- pkg/ddevapp/ddevapp.go
- winpkg/ddev.nsi
We've not had a windows installer, we need one.
This uses the excellent NSIS to build an installer (and uninstaller).  The installer is built in the regular Circleci build and is available in the artifacts on the Circleci build. For example, on https://circleci.com/gh/drud/ddev/2785#artifacts/containers/0
* Adds a windows installer (`make windows_install`) which packages ddev and sudo (#786)
* Adds sudo so we no longer make Windows users go manually edit hosts file.  (#798)
* Fixes a bug discovered at Drupalcon where a failed sudo attempt results in a stack trace, (#780)
* Remove any existing ddev instances from your %PATH%
* Install using the downloaded installer (Perhaps https://circleci.com/gh/drud/ddev/2726#artifacts/containers/0 )
* Open a new cmd or git-bash window (to get the new …
> Windows installer, fixes #786, fixes #780, fixes #798, fixes #701

- .circleci/config.yml
- pkg/ddevapp/ddevapp_test.go
https://github.com/drud/ddev/pull/787 went in last week, adding a windows installer, but the nightly and tag builds didn't include it, so the artifact script failed. Fix that.
> Add windows_install to nightly and tag builds, fix nightly build

- Makefile
- pkg/version/version.go
The bug is described in https://github.com/drud/docker.ddev-router/pull/17 - This PR just bumps the version to pull that in.
> Bump ddev-router image tag to solve problem with header too big

- .circleci/circle_vm_setup.sh
Time to upgrade docker-compose and golang (1.10.2).
> Upgrade docker-compose and golang on circleci build

- .circleci/config.yml
- Makefile
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/util/network.go
OP #837 - we're having regular failures in test that seem to be centered around ContainerWait(), which is complex with goroutines and such. This is a simpler implementation.
* Simplify ComposeCmd()
* Simplify ContainerWait()
* Simplify EnsureHTTPStatus()
* Make more generous timeouts for golang tests. It may be that much of what I was seeing was golang killing off the test and spewing lots of goroutine info. However, I'm pretty sure that means we were leaking tickers too; I like this simplified version better.
It's hard to test this. Restart a CircleCI test.
* Modest changes were made to one TestContainerWait()
OP #837
>  Simplify ContainerWait(), ComposerCmd, EnsureHTTPStatus, fix build, fixes #837

- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal8.conf
- pkg/version/version.go
#830 - Accessing update.php/selection results in a 404
This bumps the web tag for the fix introduced in drud/docker.nginx-php-fpm-local#72
Test instructions provided in drud/docker.nginx-php-fpm-local#72
> Fix d8 web update.php, fixes #830

- pkg/dockerutil/dockerutils.go
OP #859: Output from docker-compose command was no longer interactive, so it was impossible to tell what was happening as it pulled images, and it looked like it was hung.
This PR makes ComposeCmd() exactly what it was before #845 messed it up.
Use `docker rmi` to remove the nginx-php-fpm-local image. Then `ddev start`. You should see it pulling the image as it does it.
OP #859, Regression introduced in #845
> Make ComposeCmd() interactive again, fixes #859

- containers/ddev-router/nginx.tmpl
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-backdrop.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-default.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal6.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal7.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal8.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-typo3.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-wordpress.conf
- containers/nginx-php-fpm-local/files/etc/php/5.6/fpm/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.0/fpm/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.1/fpm/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.2/fpm/php.ini
- pkg/version/version.go
People debugging with xdebug (or running a long-running process) could encounter timeouts from nginx even though the web container had them set quite high. We discovered that the timeout on the ddev-router was the issue with this. 
Increase timeouts everywhere to 10m.
Debug into a project. Wait a couple of minutes. Let the debugger continue. The page should load in the browser without a timeout.
OP #844 
Related issue #672 (varbase install): I tested this with a varbase install and made it through to the end, taking the defaults. Admittedly it's with a faster machine than I tested with then, but I think this solves the problem.
>  Increase proxy_read_timeout for ddev-router, fixes #844, fixes #672

- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-backdrop.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal6.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal7.conf
- containers/nginx-php-fpm-local/files/etc/nginx/nginx-site-drupal8.conf
- pkg/version/version.go
OP #847 mentions that it's impossible to download a .mysql.gz file from backup_migrate on d8. 
It turns out looking at https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/ that this seems to be a failure of putting static files in our configuration first, when the private files handling needs to come first.
Update d7/d8/backdrop config based on https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/  
* Try to download a backup_migrate .mysql.gz archive
* Make sure all other static file situations remain correct, including private files attached to a node
OP #847
> Private files must take precedence before static files in nginx config, fixes #847

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
OP #789: Since we introduced the additional_hostnames feature, there have been a few reports of people accidentally introducing conflicting hostnames. The most common is probably where the project name is "myname", adding "myname" again in the additional_hostnames. This causes the ddev-router to freak out and fail to preprocess its nginx configs.
Make sure that the list of hostnames provided to docker-compose.yaml (and thus to ddev-router) is unique.
This PR does *not* solve the problem of multiple projects competing for one hostname.
For a project named "junk", add "junk" in additional_hostnames config. When you `ddev start` things should work. This should go down in flames in earlier versions of ddev.
This adds the broken case to TestDdevStartMultipleHostnames(), so a regression should …
> Fix conflicting hostname problem by making list unique, fixes #789

- containers/nginx-php-fpm-local/Dockerfile.in
- containers/nginx-php-fpm-local/files/etc/php/5.6/fpm/pool.d/www.conf
- containers/nginx-php-fpm-local/files/etc/php/7.0/fpm/pool.d/www.conf
- containers/nginx-php-fpm-local/files/etc/php/7.1/fpm/pool.d/www.conf
- containers/nginx-php-fpm-local/files/etc/php/7.2/fpm/pool.d/www.conf
- pkg/version/version.go
TYPO3 users perpetually need to set environment variables in php-fpm, especially TYPO3_CONTEXT=Development.  We have a [Stack Overflow article](https://stackoverflow.com/questions/50109020/how-can-i-set-environment-variables-inside-ddevs-containers) on this, but it's not strictly correct, as fpm currently ignores environment variables that are set.
* Let fpm see the environment variables (clear_env = no in fpm config)
* Make fpm config writeable by ordinary user to make these options more available in general to non-root user.
* Set an environment variable in the web container as in https://stackoverflow.com/questions/50109020/how-can-i-set-environment-variables-inside-ddevs-containers
* Verify the existence of the variable with `ddev ssh` and `echo $myvar`
* Verify the existence of the …
> Allow environment variables to propagate into php-fpm

- build.sh
Our windows build especially often fails on running tests (pkg tests require no projects running at all, which is a problem in its own right - #421, which is the whole problem with this.)
Example: https://gist.github.com/drud-test-machine-account/943c09556790ade2a7edbfc07bb6434b
Does a ddev list and docker ps to help us understand the failures we see.
Note that this PR affects *only* the macOS and Windows testbots, and nothing else, so it's pretty harmless. Just some debugging info.
> Add debugging in build.sh for running sites problem

- .circleci/config.yml
- .circleci/generate_artifacts.sh
OP #839 - the tag build didn't build ddev_docker_images.version.xz.sha256.txt
This moves the logic for doing that into the generate_artifacts script where it should have remained. And builds it.
* Look at a tag build and see if the tar.xz and tar.xz.sha256.txt gets created. Hint: See [this tag build](https://circleci.com/gh/rfay/ddev/406#artifacts/containers/0)
* Look at a regular build and see that neither gets created. (For example, https://circleci.com/gh/rfay/ddev/409#artifacts/containers/0)
> Add arg to build xz archive of ddev images, fixes #839

- cmd/ddev/cmd/auth_pantheon.go
- pkg/ddevapp/providerPantheon.go
In some situations, `ddev` would assume that the global ddev directory (`~/.ddev`) already existed, causing problems if this wasn't true -- for example, by running `ddev auth-pantheon` before `ddev config` as in #806.
These changes replace ad-hoc global ddev directory path building with the `GetGlobalDdevDir()` command, which will ensure that the global ddev directory exists before operating on/in it.
- Ensure the test system does not have a `~/.ddev` directory (`mv ~/.ddev ~/.ddev.bak`)
- Execute `ddev auth-pantheon $TOKEN` where $TOKEN is a Pantheon Machine Token
- The command will execute successfully
- Command execution will have created the missing `~/.ddev` directory
#806
> Safely get global ddev directory, fixes #806

- docs/users/cli-usage.md
The docs reference `ddev_bash_completions.sh`, but the actual filename has no 's', it's `ddev_bash_completion.sh`
Removes the 's'.
Build docs, read bash completion section.
N/A - Docs update only.
Fixes #881 
N/A - Docs update only.
> Fix bash completion filename in CLI docs, fixes #881

- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
Although the hostname "host.docker.internal" is defined and supported for Docker for Windows and Docker for Mac, it's not provided in the container on linux docker at this time. That breaks our approach to xdebug in v0.18.0, which worked great on the other situations.
On linux, use `ip address show dev docker0` to get the IP address, then add the address to `extra hosts`.
Note that this is a bit awkward, and a throwaway address is used on non-linux. This is because golang templating by default escapes the required quotes, breaking yaml :(  There are workarounds for it, but it's a bit of work (You have to treat things as HTML attributes instead of as strings in the golang templating.)
xdebug instructions should work for Linux, Mac, and Windows as shown in [our …
> Add linux deriving host.docker.internal, fixes #843

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/testcommon/testcommon.go
#136: We had made running projects have to have unique names, but that got lost somewhere. This restores it.
This does not solve:
* Duplicate project name when one is not running
* One project taking over another project's database inappropriately (databases are uniquely named as well)
* Duplicated hostnames (across projects) breaking ddev-router. (Adding an additional_hostname to one project that is already taken by another)
Take seriously when the error says there's a duplicate site.
Start a site.
In another directory, start a site with the same name. You should get a failure.
* The test for uniqueness was updated to catch this case. 
OP #136
> [regression fix] Make project uniqueness constraint work again, fixes #136

- containers/nginx-php-fpm-local/files/etc/php/5.6/cli/php.ini
- containers/nginx-php-fpm-local/files/etc/php/5.6/fpm/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.0/cli/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.0/fpm/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.1/cli/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.1/fpm/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.2/cli/php.ini
- containers/nginx-php-fpm-local/files/etc/php/7.2/fpm/php.ini
The nightly build started failing on the drupal-composer build in the nginx-php-fpm-local build. It was a simple OOM. I noted that we have memory_limit in the php cli set to 512M instead of the normal -1 (unlimited).
* cli php.ini's were symlinks to fpm. They need to be separate files, changed that.
* Set cli to unlimited memory_limit, as it should be.
* Increase fpm memory_limit; people don't need to protect their server here.
* Fix #850 by setting always_populate_raw_post_data = -1 (Such a trivial change, seemed worth throwing in here)
* Look at nightly build. See https://circleci.com/gh/rfay/ddev/457
> Increase PHP memory_limit, unlimited for cli, fixes composer OOM in nightly build, fixes #850

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
In order to access a project's web container directly, a user would need to know how to obtain the container's ephemeral port via a command like `docker ps`.
This PR adds code that queries the project's web container for its public ephemeral port and local IP, returning this direct address at the end of the URLs list presented in `ddev describe`. A user can find this address without any Docker knowledge and access this address to interact directly with the web container, bypassing the ddev router.
- `ddev start` a project 
- Execute `ddev describe` within the project
- The last address in the URLs list under Project Information should be in the format `http://<ip>:<port>`
- Visit this direct address and interact with the site, bypassing the ddev router
A basic test (`TestGetAllURLs()`) …
> Include direct web container access in GetAllURLs(), resolves #796

- containers/mariadb-local/files/etc/my.cnf
- pkg/version/version.go
Docker Toolbox/Windows 10 Home uses a completely different virtualization environment that can break Mariadb. 
This is migrated from drud/mariadb-local#63, and the comments related to it are in #854
* Turn off innodb_use_native_aio since it just doesn't work with NTFS/Windows
* log-bin=on - Fixes [a weird problem](https://dba.stackexchange.com/a/185006/149238) with Virtualbox and mariadb. 
* Use ddev with this on Windows 10 Home (dbimage: drud/mariadb-local:20180416_win_10_home)
* Use it everywhere else.
* Check for performance everywhere
OP drud/ddev#636
> Bring in drud/mariadb-local#63 to solve Windows 10 Home problem, fixes #636, fixes #854

- pkg/version/version.go
Our container code is now part of the main code tree, so during development we used temporary pushed container.
Now, though, we're about to do a release with the code in our containers. But we want to be able to test and reference the new containers (all tagged v0.19.0 on dockerhub) at the time of the tag.
To do that we have to temporarily push v0.19.0 containers, so I've just done that with the current code.
Use it, look at the tests.
The 4 containers should be re-pushed at tag time.
> Bump container versions to planned v0.19.0 for release

- README.md
- docs/index.md
The `#` in the Markdown sections discussing `#ddev` community Slack channels caused broken formatting and the Installation page had no link to where a user could find the Windows installer .exe.
This PR correctly handles the `#` character in Slack channel names and adds a link to the Github releases page, where a Windows installer can be downloaded.
#899
> Fix Slack channel formatting and add link to ddev releases page, fixes #899

- pkg/ddevapp/typo3.go
Previously, `ddev config` would fail to write `AdditionalConfig.php` if TYPO3 was not set up (specifically, the `typo3conf` directory did not exist).
This change will allow `ddev config` to create the `typo3conf` directory in order to write `typo3conf/AdditionalConfiguration.php`, even if TYPO3 has not been set up yet.
Recreate the issue by executing `ddev config` with `ddev version` v0.19.0:
- `cd` to a new TYPO3 project
- Ensure no `typo3conf/` directory exists in the project root
- `ddev config`
- Note the error message: 
`Unable to create settings file: Failed to write TYPO3 AdditionalConfiguration.php file: chmod /Users/afrench/Code/typo3.cms/typo3conf: no such file or directory`
To test the fix, build this version of `ddev` and execute `ddev config`:
- `cd` to a new TYPO3 project
- …
> Create typo3conf/ if it doesn't exist, fixes #741

- containers/nginx-php-fpm-local/Dockerfile.in
#867 requests rsync be added to the web container, and it's an easy fix. 
This was also done in PR #909, but the contributor didn't sign the CLA, and I didn't want it to go stale, so adding here and closing that one.
I also reformatted this to use spaces for indents, as it was a mix of spaces and tabs before. The only logic change is one line, adding rsync to the list of packages.
> Add rsync to nginx-php-fpm-local, fixes #867

- winpkg/ddev.nsi
#903 
Provides a description for each component of the Windows installer
Start the installer and move the mouse over the components to see the new descriptions
Works with NSIS for POSIX only as before. To use with the Windows version slashes in the file paths has to be changed to backslashes
> Provide descriptions for Windows installer components, fixes #903

- .buildkite/test_containers.sh
- containers/.gitattributes
In https://github.com/drud/ddev/pull/902 I deliberately let slide test failures on Windows of the containers. This is to fix that. Hopefully getting buildkite to check out as-on-server, with linefeeds and no CRs will solve that problem.  
I *think* the largest part of the problem was that Windows agents have to check out at least the container stuff with core.autocrlf=false, so we have shell scripts that don't have CRs in them. This meant a change in the Windows *agent* testbots:
`git-clone-flags="-v --config core.autocrlf=false"`
And that was the most important change.
> Fix broken containers resulting from CRs in scripts

- containers/nginx-php-fpm-local/Dockerfile.in
Adds ability to connect to memcached with PHP. Fixes #269 
This installs and enables the php-memcached extension on the web container.
Check that docker image builds cleanly, and memcached shows up in PHP `mods-available`.
I don't see any tests for specific PHP extensions outside of xdebug.
This adds PHP memcached support. To actually test out memcached in localdev, it will require adding a memcached container -- see the docker compose example in #269.
> Install php-memcached extension on web container

- containers/mariadb-local/test/testserver.sh
Working on reliability issues with the container build I noted possible collisions of the directory we're using, so added $SECONDS to the tmp directory name maker. We'd be better to use TMPDIR, but that provides an unusable directory on macOS.
Improve tmp directory name; should not do any harm.
> Improve reliability with a more unique tmpdir and outdir

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/drupal.go
- pkg/version/version.go
Drupal will remove write permissions from `sites/default` and `sites/default/settings.php` unless `$settings['skip_permissions_hardening'] = TRUE;` is included in generated Drupal8 settings as explained in #715.
This PR adds the `$settings['skip_permissions_hardening'] = TRUE;` line to the generated Drupal8 settings and ensures that the `sites/default` directory and the `sites/default/settings.php` file are writable upon `ddev start`.   
Using a Drupal 6/7/8 project, 
- Ensure the project is stopped with `ddev stop`
- Remove write permissions from `sites/default` and `sites/default/settings.php`
- Execute `ddev start`
- Inspect the permissions of `sites/default` and `sites/default/settings.php` via `ddev exec ls -lah sites/default`
- Confirm that `sites/default` (`.` in `exec` output) and …
> Improve Drupal 6/7/8 file permissions, fixes #715

- pkg/version/version.go
Temporarily pushing provisional v0.20.0 containers for building and testing.
The 4 containers should be re-pushed at tag time.
> Bump container verisons to v0.20.0

- pkg/ddevapp/config.go
The path to the config file (`config.yml`) is set multiple times (see https://github.com/drud/ddev/blob/master/pkg/ddevapp/config.go#L61 and https://github.com/drud/ddev/blob/master/pkg/ddevapp/config.go#L64) in config class when creating a new application.
> Remove duplicate config path resolving in ddevapp/config.go

- docs/developers/release-checklist.md
The release process checklist was found to be somewhat lacking during the v0.20.0 release, leading to some timing and ordering issues.
I've updated the release checklist to be more specific about when to create tags, when to push containers, and verifying artifact checksums.
Read the checklist and give it a sanity check.
> Update release checklist docs

- containers/mariadb-local/Dockerfile.in
- pkg/version/version.go
Apk cache remains in image and makes it larger as it must be
Use apk --no-cache parameter
> Don't use apk cache to reduce image size

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
OP #957 - On update of ddev people were getting plowed under with warnings about every project they had running, and there was no context about with config.yaml needed to be updated.
* Only warn on `ddev start`, not every single place a config is read
* Add the full path to the warning so people can understand which config.yaml is in play.
See OP #957 - Use `ddev list` and `ddev start`
OP #957
> Only complain about config.yaml version on start if necessary, fixes #957

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/typo3.go
* TYPO3 wasn't sending mail to mailhog correctly, per #924 
* TYPO3 config needed to display errors, something we'd always want in a dev environment
* TYPO3 default php version was 7.1, and 7.2 is required for TYPO3 v9 (and best elsewhere really)
* Adds config to the AdditionalConfiguration.php
* Sets default php to 7.2
* Create a TYPO3 site with composer
* `ddev config` and step through
* Check that .ddev/config.yaml has php 7.2
* `ddev start`
* Visit and install the site
* In the ENVIRONMENT section of the backend "Admin Tools", use "Test Mail Setup" to send an email. The email should be delivered to mailhog (See `ddev describe` for accessing mailhog)
No testing was added.
#924 is fixed by this
@spoonerweb's excellent #925 PR provided the start for this, but it went in a different …
> Add configuration for typo3 mail and errors, default to php 7.2, fixes #924

- cmd/ddev/cmd/sequelpro.go
The app location for looking for Sequel Pro uses wrong capitalization, breaking the command for macOS systems with case-sensitive file systems.
Change the capitalization.
Unfortunately I wasn't able to figure out an easy way to test this, so will have to ask the issue originator to test.
This is too hard and too obscure to do tests.
OP #969
> Fix case of Sequel Pro.app, fixes #969

- README.md
- docs/index.md
- pkg/version/version.go
* Docs for Win 10 Home (Docker Toolbox) were incomplete
* We didn't mention that we now support Windows 10 Enterprise (because Docker for WIndows does)
* Update minimum versions of docker (18.03) and docker-compose (1.19)
> Update docs for Windows 10 Home and Enterprise, update min docker versions, fixes #884, fixes #896

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config.go
#900 - ddev config incorrectly updates php version in some situations.
ConfigOverrideAction() really should only override on a new config, and had only been used for D7 and D6. Both places it didn't work correctly.
It now only does its job if the config doesn't already exist.
Described in OP #900 
TestPostConfigAction() tests the expected behavior of ConfigFileOverrideAction().
OP #900
> ConfigFileOverrideAction() should only override if no config exists yet, fixes #900

- docs/users/cli-usage.md
We advocated using composer on the host in our quickstart, because that's fairly easy to do on macOS and Linux.
However, users on Windows will never be able to succeed with that, and have to be much more sophisticated.
Point them to the Stack Overflow article about ddev with composer.
> Update docs about composer on Windows

- containers/nginx-php-fpm-local/Dockerfile.in
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
The web container's .my.cnf didn't work right, see #944 
Make /home/.my.cnf unwriteable in container
```
ddev ssh
mysql
```
You should be able to do anything you want at the mysql prompt; previously this would not run because the connection was not defined.
* Added TestDdevMysqlWorks to verify that the mysql command works as expected in both the web and db containers.
OP #944
> Make web container .my.cnf read-only so mysql will use it, fixes #944

- .buildkite/macos_container.yml
- .buildkite/macosdockerformac.yml
- containers/mariadb-local/test/testserver.sh
Nightly build is breaking due to changes in how we test/generate the mysql starter db. See https://circleci.com/gh/drud/ddev/3052?utm_campaign=build-failed&utm_medium=email&utm_source=notification
Try to make the output not violate fs permissions.
Run the nightly build against this PR.
> Improve mariadb-local test to work on linux without making un-deletable files

- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/remove_test.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop.go
- cmd/ddev/cmd/stop_test.go
- cmd/ddev/cmd/utils.go
- pkg/ddevapp/ddevapp.go
#952: a user was unable to act on all active sites.
Add the ability to pass a list of sites into `ddev stop` and `ddev remove`, e.g. `ddev remove site1 site2 site3`.  Additionally add the `--all`/`-a` option, acting on all running or active sites.
- Start several sites, stop them all by passing their names into one `ddev stop` command
- Start several sites, stop all at once with `ddev stop --all`
- Start several again by passing their names into one `ddev start` command
- Start all sites again with `ddev start --all`
- Start several sites, remove them all by passing their names into one `ddev remove` command
- Start several sites, remove all at once with `ddev remove --all`
Note that I've added a failsafe to prevent a user from removing all site data through `ddev remove --all …
> Allow ddev stop/rm to act on multiple/all sites, fixes #952

- pkg/ddevapp/drupal.go
#958 
Specifically check for os.IsNotExist(), remove warning output that implied a permissions change was attempted.
Remove a Drupal project's sites/default/settings.php, execute `ddev start`. No warning message is emitted.
> Improve handling of missing settings files, fixes #958

- .buildkite/test.sh
- .buildkite/test_containers.sh
- containers/.gitattributes
- containers/ddev-router/Makefile
- containers/ddev-router/test/containercheck.sh
- containers/mariadb-local/test/testserver.sh
- containers/nginx-php-fpm-local/Makefile
- containers/nginx-php-fpm-local/test/containertest.sh
- containers/phpmyadmin/Makefile
- containers/phpmyadmin/test/containercheck.sh
- docs/developers/buildkite-testmachine-setup.md
We seem to never be able to build and test our containers on WIndows *and* elsewhere. 
Trying again.
Script and docs (mostly) updates, and agent debugging
Build should run reliably on each testbot, especially windows testbots.
> Yet another round of battling building and testing containers on Windows

- pkg/ddevapp/drupal.go
Two minor settings issues that cause errors on a normal Drupal8 install.
This PR adds two lines to the generated Drupal8 settings file: the first defines a trusted hosts pattern, the second defines the config sync directory.  The existence of these settings lines prevent the errors outlined in #504 and #680.
- Install a fresh Drupal8 site
- Navigate to `<site>.ddev.local/admin/reports/status`
- Ensure no errors are presented 
#504 
#680
> Drupal8 settings improvements, fixes #504, fixes #680

- pkg/ddevapp/drupal.go
#983: Drupal sets read-only permissions on settings.local.php and services.yml.
Adds these two files to makeWritable, which will check for their existence and ensure they're writable.
- Create sites/default/settings.local.php
- Create sites/default/services.yml
- chmod both files to 400
- ddev start
- Both files have user write permissions
> Ensure write permissions of settings.local.php and services.yml, fixes #983

- .buildkite/sanetestbot.sh
- .buildkite/test.sh
- .buildkite/test_containers.sh
- docs/developers/buildkite-testmachine-setup.md
We sometimes have a broken buildkite testbot in any of a number of ways, and never find out about it until it's run forever and ever. This additional script does an initial test to see if the testbot is sane before continuing the test.
> Check testbot sanity before continuing with tests

- docs/users/extend/additional-hostnames.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
OP #868: People want to use URLs that do not container ddev.local. 
* Add additional_fqdns[] array to the config.yaml. People can then have as many URLs pointing to their project as they could ever want.
* Add docs explain it, but mentioning why to avoid this feature.
Set up config.yaml with additional_fqdns as in the docs added here. 
Added additional_fqdns testing into TestDdevStartMultipleHostnames()
OP #868 
[Make ddev-router more transparent about failures #774](https://github.com/drud/ddev/issues/774) - It's a known issue that two live sites can't share the same fqdn or additional_hostname, and it causes an annoying and hard-to-understand ddev-router failure to start.
> Allow arbitrary additional_fqdns, fixes #868

- .buildkite/test_containers.sh
test_containers.sh was leaving its temporary built containers on the testbot, where test.sh could stumble on them later. They should get cleaned up.
Reorganize test_containers.sh to always clean up on exit.
> test_containers.sh needs to clean up containers it creates, not leave temp builds on testbot

- nightly_build.mak
I should have pre-run the nightly build before pulling https://github.com/drud/ddev/pull/991
nightly_build.mak had a remaining reference to nginx-php-fpm-local in it.
Actually look in the containers directory and build what's found there.
I hope this approach is less fragile!
`make -f nightly_build.mak`
Make sure it passes the nightly build on circleci  (https://circleci.com/gh/rfay/ddev/546)
> Fix nightly_build.mak after container name change

- docs/users/cli-usage.md
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/utils.go
#468, improved management of settings files.
This PR creates settings.ddev.php, placing ddev-specific configurations in this file to preserve user settings.  The settings.php file is only modified to include settings.ddev.php.
[Randy's comment here](https://github.com/drud/ddev/issues/468#issuecomment-395548090) describes the desired behavior and was used as the template for the changes in this PR. 
For Drupal 6/7/8 and Backdrop, begin with the situation in which no settings files exist.
- Begin with no settings.php file and no settings.ddev.php file, and no .gitignore in the directory containing the settings files,
- `ddev config`
- Ensure a settings.php has been created that does nothing but include settings.ddev.php
- Ensure a settings.ddev.php has been created that contains …
> Improved management of settings files, introduce settings.ddev.php

- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/start_test.go
An args slice length check was preventing any project names from being provided to `ddev start`.
This PR removes the block of code preventing `ddev start` from accepting arguments, as that is now an accepted use case.
- Create at two projects, `p1` and `p2`
- Stop both projects with `ddev stop p1 p2`
- Start both projects with `ddev start p1 p2`
- Ensure both start as expected
`ddev start` with multiple project names as arguments has been added as a test case.
> Allow `ddev start` to accept project name arguments

- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
DDEV start/stop/remove referred to "sites", not "projects", and the CLI help text didn't relate the ability to pass multiple project names as arguments.
Updates the CLI help text.
Execute `ddev start -h`, `ddev stop -h`, `ddev remove -h`.
> Improve ddev start/stop/remove help text

- containers/ddev-webserver/Dockerfile
This PR adds php-redis module to the web container.
check in phpInfo if the redis module is installed, or check through php code `extension_loaded('redis');`
Resolves: #267
nothing to be done.
> Install php-redis module in the web container

- containers/ddev-webserver/Dockerfile
Our ddev-webserver Dockerfile has a (long-term?) scripting bug. I noticed and fixed it over in https://github.com/drud/ddev/pull/1007, but of course that one will be a while. 
I have no idea how this could ever have worked, or why a php upgrade would trigger failures that we hadn't seen before.
Fix the Dockerfile; script was completely wrong.
> Fix for loop that installs php packages

- containers/ddev-dbserver/Dockerfile
- containers/ddev-dbserver/files/docker-entrypoint.sh
- containers/ddev-dbserver/files/etc/my.cnf
- containers/ddev-dbserver/test/testserver.sh
- containers/ddev-webserver/test/containertest.sh
- pkg/ddevapp/templates.go
- pkg/version/version.go
With the move to Docker 18.06 *something* had to break, and our container test for ddev-dbserver broke on windows. It turns out that mysqld won't (at least now) read config that is world-writable, as we've run into other places on ~/.my.cnf; I don't know why this would show up with a docker version change.
* Change the *test* to mount ro
* Change so ddev generates a docker-compose.yaml that has this mount set to ro so our users don't discover this. 
* If the tests success on the windows container that's good
* For extra credit try changing config in `.ddev/mysql/<something.cnf>` ON WINDOWS and see that your change takes effect.
> Fix Windows mount of .ddev/mysql configuration (Support for Docker 18.06)

- pkg/version/version.go
There were changes made to ddev-webserver in https://github.com/drud/ddev/commit/ba7f1df0d6e5373223707fb67865e8bc132f137f
and
https://github.com/drud/ddev/commit/f6784fe02d9ba02d2a96fc0ab96939e2b538a924 and neither one got a new version pushed or version update. This just does that so we're clear that the container is changing.
> Bump ddev-webserver tag to reflect addition of php-redis and fix of Dockerfile for loop

- pkg/ddevapp/backdrop.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
A user in slack pointed out that our prompted suggestion of wp search-replace results in an error because we quote it.
The prompt says
> Wordpress sites require a search/replace of the database when the URL is changed. You can run "ddev exec 'wp search-replace [http://www.myproductionsite.example] http://wpsite.ddev.local'" to update the URLs across your database. For more information, see http://wp-cli.org/commands/search-replace/
The result if you do that is:
`ddev exec 'Failed to execute command [wp search-replace [http://www.myproductionsite.exampleto update the URLs across your da] http://wpsite.ddev.local]: Failed to run docker-compose [-f /Users/brentr
obbins/wpsite/.ddev/docker-compose.yaml exec -T web wp search-repl
ace [http://www.myproductionsite.example] …
> Fix ddev exec message offered to wp users on import

- .buildkite/test_containers.sh
- .circleci/config.yml
* There seem to be times on the buildkite testbots where docker rm or docker rmi can fail... but we're only doing it in the context of cleaning up anyway, so it shouldn't cause the tests to fail.
* Docker images should be built in testing with --no-cache. Turns out build-tools has a DOCKER_ARGS makefile variable for this exact purpose.
* Ignore failure on docker rm.
* Add --no-cache to container build in circle and buildkite tests.
> Improve buildkite test_containers.sh by not erroring if docker rm/rmi --fail

- cmd/ddev/cmd/hostname.go
- pkg/ddevapp/ddevapp.go
#831: The user's hosts file eventually becomes polluted after having many project hostnames added to it. Currently, ddev makes no effort to remove a hostname entry after it has been added.
Add the ability to remove a hostname via the `ddev hostname` command:
```
ddev hostname --remove my.host 127.0.0.1 
```
Remove hostname entries from the user's hosts file on `ddev remove --remove-data`.  Removing a hostname on `ddev remove --remove-data` and `ddev hostname --remove` mimic the output and structure of existing hostname addition code.
User-facing output in `ddev hostname` has been improved.
- Add a hostname via `ddev hostname test.host 1.2.3.4` and ensure the hostname has been added to the hosts file
- Remove the same hostname via `ddev hostname test.host 1.2.3.4 --remove` and ensure the …
> Clean up hostnames when removing project data, closes #831

- docs/users/extend/additional-services.md
- pkg/servicetest/servicetest_test.go
- pkg/servicetest/testdata/services/README.md
- pkg/servicetest/testdata/services/docker-compose.memcached.yaml
- pkg/util/network.go
Currently ddev does not provide a Memcached container. Memcached is used as a caching layer by many applications.
Adds an example docker-compose file and documentation to setup a Memcached container within a ddev environment.
Follow instructions in documentation included in PR to create a Memcached container.
This should get picked up automatically by the already-existing servicetest test script.
#269
> Add Memcached service configuration file and documentation.

- containers/ddev-webserver/files/etc/nginx/nginx-site-typo3.conf
Adds support for TYPO3 'versionNumberInFilename' configuration
#1030 
Adds a new rewrite rule to TYPO3 nginx configuration that rewrites generated filenames with enabled TYPO3 configuration `versionNumberInFilename` for backend and frontend.
1.  Install TYPO3 Version 8 via composer `composer create-project typo3/cms-base-distribution ^8 typo3`
2. Configure ddev `ddev config`
3. Add configuration to `AdditionalConfiguration.php`
```
$GLOBALS['TYPO3_CONF_VARS']['BE']['versionNumberInFilename'] = '1';
$GLOBALS['TYPO3_CONF_VARS']['FE']['versionNumberInFilename'] = 'embed';
```
4. Call TYPO3 Backend (http://typo3.ddev.local/typo3/)
You should see a normal rendered backend. Without the nginx configuration, all styles are missing.
#1030 
Adds support for TYPO3 'versionNumberInFilename' …
> Add rewrite rule to TYPO3 nginx configuration, fixes #1030

- pkg/ddevapp/typo3.go
Problem described in #1042 
The code in the template file is changed so that the array is extended instead of overwritten so that we have access to the full $GLOBALS['TYPO3_CONF_VARS']['MAIL'] array in TYPO3. 
Testing this automatically was not possible as far as I know.
> Change the TYPO3 AdditionalConfiguration.php template to extend the MAIL array - fixes #1042

- docs/index.md
- docs/users/docker_installation.md
- mkdocs.yml
#1002: Add docker installation instructions
Adds the instructions
* Read the [main page](https://github.com/drud/ddev/blob/98d7259394221ac25b314f173173b259d51f6c50/docs/index.md) and the [docker installation page](https://github.com/drud/ddev/blob/98d7259394221ac25b314f173173b259d51f6c50/docs/users/docker_installation.md)
* Do the installations
* Try the tests suggested in the testing section
> Add docker installation and testing instructions, fixes #1002

- .githooks/README.md
- .githooks/linkallchecks.sh
- .githooks/linkgofmt.sh
- .githooks/pre-push.allchecks
- .githooks/pre-push.gofmt
- .githooks/unlinkprepush.sh
The provided (optional) githooks don't provide `make staticrequired` which is one thing we'd like them to have.
Adds it.
This change affects only developers who link the pre-push hooks, it doesn't affect users, testing, etc.
> Add staticrequired to pre-push hooks

- pkg/appimport/appimport_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/providerDrudS3_test.go
- pkg/dockerutil/dockerutils_test.go
- pkg/fileutil/files_test.go
- pkg/testcommon/testcommon_test.go
In a couple of our tests we occasionally get panics because we get a nil for err and then use err.Error(). We shouldn't use a nil err.
* If err == nil, make sure we don't try to use err.Error()
This affects only tests, and only occasionally, so is a code-review.
See the fail/panic in https://buildkite.com/drud/ddev-macos/builds/489#6c3c127b-8d24-40f2-861e-9ea7704c07e3
> Don't use err when it's nil

- pkg/version/version.go
Temp images labeled v1.1.0 have been pushed, we'll push the real ones after the tag is cut.
Change version.go to refer to the v1.1.0 images.
> Bump image versions to v1.1.0 for release

- cmd/ddev/cmd/import-files.go
- pkg/archive/archive.go
The review in #994 describes some issues with import-files, namely one where a bad extraction path would return a success despite having extracted zero files into the project. 
Additionally, a regression was identified where a user would no longer be prompted for an archive extraction path when using the import-files interactive mode.
If no files match the extraction path in an archive, an error is returned to the user.
The interactive extraction path regression was fixed as well.
Provide an archive in interactive mode and ensure the extraction path prompt is presented.
Provide an invalid extraction dir and ensure an error is generated.
#944
> Improve archive extraction path error handling

- pkg/dockerutil/dockerutils.go
In the v1.1.0 release, people who did a `ddev start` on an existing project which had a database got this:
`
ddev start
Starting xxxx-xx...
Migrating bind-mounted database in ~/.ddev to docker-volume mounted database
Failed to start xxxx-xx: Failed to migrate db from bind-mounted db: failed to run migrate_file_to_volume.sh, err=failed to create/start docker container ({xxxx-xx_migrate_volume 0xc420268780 0xc42026e400 <nil> <nil>}):no such image output=
`
This seems to be a result of the ddev-dbserver image not being properly automatically pulled.
This PR pulls that image before using it.
* Recreate the user problem with v1.1.0 to understand it.
1. You'll need a bind-mounted db, you probably have some named ~/.ddev/<project>/mysql.bak out there from previous testing. To reuse them, `mv …
> Make sure we have a db image before running it; fix migration problems in v1.1.0

- .buildkite/sanetestbot.sh
This is a trivial testing-only change to sanetestbot.sh. It needs to check for disk space trouble. I wrote this little stanza for quicksprint, and had always been wanting it here.
> Add disk space check on sanetestbot.sh

- cmd/ddev/cmd/logs_test.go
We have regular failures in TestDevLogs, such as https://buildkite.com/drud/ddev-macos/builds/524#11fd5348-c02c-45eb-ab31-9c3444953b0d, but a retry usually sorts it out. We would save ourselves a lot of time by understanding this.
It seems to happen on only one project, so the first step here is to add output identifying the project.
I've manually tested and the procedure in this test works fine on d8 and wordpress. Wordpress is likely the culprit, since I think buildkite is just building one testsite on macos.
> Add some debugging so we know which project fails in TestDevLogs

- .buildkite/static.yml
- .buildkite/test_static.sh
- .circleci/circle_vm_setup.sh
- .circleci/config.yml
* We're going to need to be able to do more parallel builds for Apache webserver types, and it wouldn't do us any harm to do it for multiple CMSs.
* We need parallel of staticrequired anyway.
* It's been too long coming :)
Reorganize the circleci build
Review the builds (and look at the fancy workflows tab on circleci also, https://circleci.com/gh/drud/workflows/ddev
* This will actually let us lose the buildkite staticrequired build, so will save some resources on our buildkite stuff.
* Apache PR: https://github.com/drud/ddev/pull/1007
* After pulling this, we can disable/remove the buildkite static test.
> Parallelize Circle build

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
* In https://github.com/drud/ddev/pull/1076 I removed the explicit install of docker-compose with a recent version. The version on Circleci (1.17.1) doesn't seem to be adequate because we require a minimum of 1.18.0. At least in https://circleci.com/gh/drud/ddev/3280?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link we see a lot of complaints about version numbers and failure. (I don't know why this could have worked earlier, but it seems to have)
* The nightly and tag builds had the wrong image in them from #1076 - the new builds had it updated. But that meant that the nightly and tag builds ran with entirely wrong docker version and docker-compose version.
> Reintroduce docker-compose upgrade for circleci

- cmd/ddev/cmd/config.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/wordpress.go
#1035: The current brand-new project installation workflow requires the docroot to exist during initial configuration, which means that one can't install a site from a completely empty directory using composer from inside the web container.
This requires the site to be initially configured on the host, meaning the user has to have php and composer installed on the host system. Not unreasonable, but annoying.
Warn the user when a non-existent docroot is supplied, but allow the configuration process to continue. This allows site installation to be completed within the container using composer, which ends up being a bit slower but potentially more convenient for the user.
- Begin with an empty directory
- `ddev config` and define a new project
- Provide a docroot directory that does not …
> Provide a warning when a nonexistent docroot is supplied, closes #1035

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
The 201808-01 Circleci build image has not been working for us at all; Revert to the older image and install docker ourselves.
> Circleci: Go back to older image and install docker ourselves

- docs/users/cli-usage.md
There's a misplaced 'Stopping a project' section in the CLI documentation that was never given content.
It moves it down to the section on interacting with a project and gives it text.
Review my notation for the projectname parameter. When I looked at the diff, I realized I used the brackets from the CLI help text whereas the web based documentation for removing a project used less than / greater than signs.
> Relocate the misplaced 'Stopping a project' section and give it text.

- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/remove_test.go
#588
Prints the raw output array even if no projects are active.
Execute `ddev list -j` both with and without active projects.
> Include empty array in JSON output when no projects are active, fixes #588

- pkg/ddevapp/config.go
#1084 
Ensures the `db_snapshots/` dir is added to the generated .gitignore.
Execute `ddev config` and check that db_snapshots is included in `.ddev/.gitignore`.
> Add db_snapshots dir to generated .gitignore, fixes #1084

- pkg/ddevapp/config.go
A format string wasn't being supplied the expected string value.
Passes the format string and a value to fmt.Sprintf.
Check that the path to be created is echoed during the prompt.
> Provide value to format string in docroot creation prompt

- cmd/ddev/cmd/describe.go
#1088 
Changes the format types from strings to integers.
Execute `ddev describe` on a running project and check that the port values are properly formatted.
> Fix format string typing in ddev describe output, closes #1086

- cmd/ddev/cmd/import-files.go
- docs/users/cli-usage.md
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
App type upload dirs are currently hard-coded. If a project is using a custom upload dir, `ddev import-files` can't handle it.
If an upload dir has been defined in config.yaml (under the `upload_dir` key), that will be the import-files destination. If no custom upload dir is defined, the default will be used instead.
Attempt importing files in projects using a custom upload dir. Ensure the imported files are sent to the correct destination.  If the upload dir does not exist, the process should fail.
I've added an automated test to ensure a custom upload dir is respected.
> Provide a configurable upload dir in config.yaml

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
#1051 
There was no way to programmatically set config values through `ddev config`.
This provides flags to define relevant values from the `ddev config` command.
You can find available flags through `ddev config -h`. Configure a project using combinations of these flags and ensure that the correct values are being set in `.ddev/config.yaml`.
Note that flag validation is currently WIP.
An automated test has been added that tries each of the new flags and confirms the value written to config.yaml.
#1051
> Set additional config values with flags, closes #1051

- pkg/version/version.go
It's time for new versions on our containers. Update them; they've already been (provisionally) pushed.
> Release prep: Update container versions to v1.2.0

- docs/users/extend/customization-extendibility.md
version: '3.6' is required at the top of docker-compose.xxx.yaml files; but we have a docs example that still has version: '3'.
Fix it.
> docker-compose example should use 3.6 for version number

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
#949 actually requested the php-imagick package and we didn't do it there, and we might as well. This adds that package. The cost in size is about 2MB.
* Use `webimage: drud/ddev-webserver:20180915_php_imagick` in your config.yaml (and ddev start).
* Configure a drupal site to use ImageMagick for its image processing. (Requires the imagemagick module; `drush dl imagemagick` and `drush en -y imagemagick`. Config is in admin/config/media/image-toolkit
* Verify that it can do image processing.
This should not require anything extra
Request was in #949
> Add php-imagick to web container, fixes #949 again

- .buildkite/sanetestbot.sh
We had a broken testbot (C drive not shared in docker) and sanetestbot.sh didn't catch it.
Add a mount into the docker command.
> sanetestbot should try to mount something to prove Windows drives are shared

- containers/ddev-webserver/files/etc/group
- containers/ddev-webserver/files/etc/passwd
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
Apache doesn't work at all on Windows. 
There are two problems. 
First:  https://github.com/drud/ddev/blob/5ed08dc93b285b00fb77ab5ec35fabcaf375ad64/containers/ddev-webserver/files/etc/apache2/envvars#L49-L50 is overwritten with uid_0 (which didn't exist in /etc/passwd)
Second:
Apache just won't run as root. Period. Without recompiling.
Use uid 1000 in windows instead of using uid 0. This seems to work fine. I've checked to make sure that at least with docker-for-windows files created by the webserver come through as the correct user on the host.
Use apache-fpm as webserver_type on Windows.
OP #1109 
This changes the UID used inside the web container to UID 1000 instead of root (uid 0). Although this seems to have no detectable problems on docker for windows in terms of creating files with …
> Make apache run properly on Windows, fixes #1109

- .circleci/circle_vm_setup.sh
- build-tools/makefile_components/base_build_go.mak
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/router.go
- pkg/dockerutil/dockerutils.go
- pkg/servicetest/servicetest_test.go
- pkg/util/network.go
Golang 1.11 is out; golang-build-container and build-tools are updated.
Bump to new build-tools
* When this is pulled, we should update the buildkite testbots to golang v1.11
> Bump build-tools to get golang v1.11

- docs/index.md
- pkg/version/version.go
With ddev in version 1.20.0, you need Docker 18.06. With ddev in version 1.20.0, file docker-compose.yaml require version: '3.6', but that property is only available from docker-compose in version 1.20, which supports Docker in version 18.02 or higher. Version 1.22.0 of docker-compose supports Docker 18.06 or higher, which is also required for ddev to run, so I propose to change docs to require Docker in version 18.06 or above, and docker-compose in version 1.22.0 or above.
> Docs - change docker and docker-compose req version

- docs/index.md
- install_ddev.sh
#1114 points out that the output of "which" in the install script is shown to the user (although the script works fine). 
* Use 'command -v' and redirect the output instead of using which
* Change the suggested curl command to `curl -L`, so it follows redirects.
Run the install script as in the [Linux or macOS install section](https://ddev.readthedocs.io/en/latest/#installation)
> Use command instead of which in install script, fixes #1114

- containers/ddev-webserver/files/etc/drush/drushrc.php
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
We have long defaulted to the drush -y, assuming people were using `ddev exec` or an exec hook, but it makes people crazy when they use drush inside the container.
* Set environment variable DDEV_EXEC when "exec" is being executed
* /etc/drush/drushrc.php looks at DDEV_EXEC and only adds the -y option if in exec context.
* Run `ddev ssh` and try `drush sql-drop`. It will ask first.
* Reload db
* Run `ddev exec drush sql-drop` and it will just drop the db with -y.
OP #1118 and #455
> Don't use -y automatically on drush commands, fixes #1118, fixes #455

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
The webserver_type option could not be specified by a command line flag.
Allows a user to specify webserver_type with a flag in `ddev config`.
Test `ddev config` and pass webserver type values (nginx-fpm, apache-cgi, apache-fpm) to `--webserver-type`.  Ensure that the webserver_type value in .ddev/config.yaml is not overwritten when no `--webserver-type` value is provided.
Automated tests have been updated to test this addition.
#1103, but the `--upload-dir` flag already exists.
> Provide a flag to specify webserver type in ddev config, fixes #1103

- containers/ddev-webserver/files/etc/apache2/apache-site-default.conf
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/testdata/TestHttpsRedirection/.htaccess
- pkg/ddevapp/testdata/TestHttpsRedirection/index.php
- pkg/ddevapp/testdata/TestHttpsRedirection/landed.php
- pkg/ddevapp/testdata/TestHttpsRedirection/redir_abs.php
- pkg/ddevapp/testdata/TestHttpsRedirection/redir_relative.php
- pkg/ddevapp/testdata/TestHttpsRedirection/subdir/index.html
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/version/version.go
@ondrogo in [Typo3 slack](https://typo3.slack.com/archives/C8TRNQ601/p1536766643000100) pointed out that with apache-fpm or apache-cgi he was unable to log into the backend. The reason ended up being that both Apache and TYPO3 were redirecting to plain https, losing the context in the process.
Apache is *not* very good at being on the receiving end of a reverse proxy. But there are workarounds, as in this PR. You have to convince mod_dir not to redirect to http when operating in https, and you have to make sure that the HTTPS environment variable gets propagated to php.
The base problem is described in http://httpd.apache.org/docs/2.4/mod/core.html#servername: 
>Sometimes, the server runs behind a device that processes SSL, such as a reverse proxy, load balancer or SSL offload appliance. …
> Add rewrites for ssl so apache behaves properly

- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/testdata/phpinfo.php
#1094 promises tests for Apache webserver_type. We already run all tests against each webserver_type but this adds an explicit test to bring up under each webserver_type and make sure the results are what we expect.
If the code is OK and the test passes, we're good enough, no manual testing is probably required.
>  Add test to make sure we get the webserver we configure, fixes #1094

- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
We wait more than a minute on `ddev start`, when in reality we usually know in about 12 seconds if something's broken. See #1135.
Note when a container fails and report it.
Break a container. The easiest is to rm /var/lib/mysql/mysql/*.MYD in the db container. It really breaks it. Try a `ddev start`.
> Faster failure on startup if container fails, fixes #1135

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/typo3.go
Our documentation claimed that we'd only write an AdditionalConfiguration.php when the file either didn't exist or was ddev-managed, but that wasn't the case. 
If AdditionalConfiguration.php exists, ddev will now check that the file is ddev-managed by ensuring the usual ddev file signature exists.
Use #1053's issue recreation method to ensure that a user-managed AdditionalConfiguration.php is respected and that a warning is emitted to the user indicating this:
1. `composer create-project typo3/cms-base-distribution my-typo3-site ^8`
2. `cd my-typo3-site`
3. `echo "<?php" > public/typo3conf/AdditionalConfiguration.php`
4. `ddev config`
Now, ensure ddev can create the config file in the usual case:
1. `rm public/typo3conf/AdditionalConfiguration.php`
2. `ddev config` …
> Respect an existing user-managed AdditionalConfiguration.php, fixes #1053

- cmd/ddev/cmd/remove.go
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
#1129 describes the terrible cyclic behavior people have when trying to destroy a project but it's already hurt (like the db is broken, so the db container is down). Essentially you do a `ddev rm -R` and it tries to *start* a broken project (in order to snapshot it), which can't possibly work, therefore people end up broken all the way. (`ddev rm -RO` works in this case, but people shouldn't have to know that). 
Don't try to start project to do a snapshot. Require the project to be running in the first place.
See the break-db instructions in #1129. Break it. Do a `ddev rm --remove-data` to see the correct behavior.
> Do not try to start project for a snapshot, fixes #1129

- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
Various web projects require http/s access to the project by the projects scheme/name/port **from within the web container**, which means they have to go through the router. OP #842 
Provide access to the router using docker-compose.yaml
* Start a project
* `ddev ssh`
* Use `curl <fqdn>` to view the project.
For extra credit, use the https URL and use configurable ports. For https you'll need to use `curl -k`.
* Added TestInternalAndExternalAccessToURL(). This tests external and internal url access with a content test and also tests with nonstandard ports
* Reorganized site definition to not only get a safe static URL to hit but also check the returned content.
OP #842
> Provide access to router within web container by hostname, fixes #842

- docs/index.md
- docs/users/docker_installation.md
- docs/users/extend/customization-extendibility.md
- docs/users/troubleshooting.md
We're learning more all the time about how to improve our communication about docker problems on various platforms. This update to the Docker Installation and Troubleshooting template is just a step along the way.
The troubleshooting command should be tested on each OS.
> Improve docker and troubleshooting instructions (docs only)

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
sqlite3 is occasionally requested. Some of our best contributors and users have requested it.
Add it with a new image.  Note that any user can do this with post-start hooks.
This seems to add only about 1MB to the image size.
Use `webimage: drud/ddev-webserver:20181002_sqlite` in .ddev/config.yaml and `ddev start`.
Try configuring a ddev project with sqlite3 db; this will require overriding the ddev generated settings.
> Add php*-sqlite3 to web container

- pkg/ddevapp/ddevapp_test.go
We see intermittent failures on TestDdevRestoreSnapshot that we've never been able to chase. They happen on Docker Toolbox and I think on macOS as well. This extra debugging info should help us get more information about what is happening.
> Add debugging for intermittent failures on TestDdevRestoreSnapshot

- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/testdata/fatal.php
- cmd/ddev/cmd/testdata/logtest.php
We see regular failures of TestDevLogs (in cmd) like [this in buildkite](https://buildkite.com/drud/ddev-macos/builds/699#3b017412-feff-4644-847b-7525633310c5) - basically a million warnings like `[29-Sep-2018 22:22:36] WARNING: [pool www] child 488 said into stderr: "NOTICE: PHP message: PHP Warning:  Unexpected character in input:  ' in /var/www/html/htdocs/index.php on line 1"` which (seem?) to flood the item we're looking at, so the test fails. It's intermittent, so hard to chase. 
 
Simplify the test, use some of our newer tools (testcommon.GetLocalHTTPResponse()), and use a static fatal.php instead of writing it out.
Probably if it tests OK then it's not going to be any worse.
> Improve reliability of TestDevLogs (in cmd)

- cmd/ddev/cmd/logs_test.go
I moved too fast... and Github can in fact pull a breaking PR. I did it. 
The incompatible signature change of testcommon.GetLocalHTTPResponse() got into master in logs_test.go. 
I'll pull this when it passes. Which might be a long time.
> Emergency fix to logs_test.go for failed master

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
In #1148 (Adding TestWebserverType() to test to make sure we get the type of webserver we're expecting), I was stuck on the fact that the "Server" header was always nginx, so didn't do everything in the test I wanted. Of course the Server header was always nginx, because that's what the router runs.  Anyway, I wanted to test for the Server header!
This PR uses the direct-to-web-container approach and can check for the Server header coming directly from the web container.
It also does minor refactoring to provide easy access to the local-direct URL and port; those were previously done in inline code in app.Describe().
I think if you like the code and it passes that's good enough.
This improves TestWebserverType()
> Improve TestWebserverType()

- docs/users/cli-usage.md
For me on macOS it doesn't work without "" around the version string.. 
Further more I would suggest to update the documentation to TYPO3 9LTS.
> Adds " around the version parameter to avoid trouble with zsh, update to TYPO3 v9 (docs only)

- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/testdata/.ddev/apache/apache-site.conf
Previously we were warning about non-config files (anything in a directory) when warning about mysql and php config.
Also there was no warning about apache config overrides.
* Use a glob to only warn about files which are actually config overrides.
* Add output for apache overrides.
* Create config overrides (nginx, apache, mysql, php)
* Put things in those directories which are *not* config overrides.
* Verify that only legitimately named override files are reported.
* nginx config should only be reported for webserver_type=nginx-fpm, converse for apache config.
No new tests
OP #731
> Stop warning about non-config files in ddev start, fixes #731

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/providerDefault.go
- pkg/exec/exec.go
OP #514 - It's a standard problem new users have that they will enter a project name like "my project", which spaces or other problems that result in an invalid url. 
We should finally validate it. 
#86 also requests sanitization of hostnames; however this PR merely insists that the user choose an appropriate hostname.
The project name is validated at the point of request. If it doesn't work, a correct project name is insisted on.
* Try `ddev config` with invalid hostnames like "an invalid hostname" or "an_invalid_hostname". 
* Try `ddev config` in a directory which would be invalid
* Try `ddev config --projectname="invalid hostname"` etc
> Validate the project name when it's entered, fixes #514, fixes #86

- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/pull.go
- docs/users/providers/drud-s3.md
- docs/users/providers/pantheon.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/pantheon_test.go
- pkg/ddevapp/providerDefault.go
- pkg/ddevapp/providerDrudS3.go
- pkg/ddevapp/providerDrudS3_test.go
- pkg/ddevapp/providerPantheon.go
#405 
The entire pull process was required for each invocation of `ddev pull`, which is not ideal when file and database assets can be in the many gigabytes.
This adds several configuration flags to `ddev pull`:
- `--skip-db` does not download or import the remote database backup asset 
- `--skip-files` does not download or import the remote file backup asset 
- `--env` determines the remote environment to pull from
- `--skip-confirmation` will bypass the interactive confirmation and begin the pull
- `--skip-import` will download file or database backup assets, but skip the import
Additionally, an update was made to respect the `DRUD_NONINTERACTIVE` environment variable to bypass confirmation, and is functionally equivalent to the `--skip-confirmation` flag.
With a remote environment …
> Add configuration flags to ddev pull, fixes #405

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_druds3.go
- cmd/ddev/cmd/config_pantheon.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/errors.go
- pkg/ddevapp/pantheon_test.go
- pkg/ddevapp/providerDrudS3_test.go
- pkg/ddevapp/providerPantheon.go
- pkg/ddevapp/router_test.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/values.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon_test.go
Only certain config values were being validated before attempting to start a project, which could lead to cryptic errors. When supplying config value flags to `ddev config`, no validation was done before writing the config file. 
These changes do more to ensure that configuration values are valid before either 1) writing a config file, or 2) attempting to start a project. Additionally, many string values in the source code were constantized and a few helper functions were added as a requirement for valid value lookup.
Similarly, instead of inspecting error values, a small set of error types has been added allowing for error type comparisons, decoupling the error from its text value.
Using the CLI's config flags, ensure that invalid choices lead to validation errors:
- `--projectname …
> Validate config before writing .yaml or starting project, resolves #1095

- pkg/version/version.go
Time to bump images tags. These have been provisionally pushed, they'll be re-pushed in the release process after all PRs are in.
> Bump image versions for v1.3.0 release

- docs/users/troubleshooting.md
- pkg/ddevapp/ddevapp.go
#1170
This allows the snapshot error help text method of recovery to work by inspecting the mysql version currently being used and only failing if the current database version requires the `db_mariadb_version.txt` file to exist.
- Configure and start a project using ddev v1.2.0
- Populate the database
- `ddev snapshot`
- `ddev rm`
- Switch to ddev v1.3.0
- `ddev config`
- `ddev start`
- `ddev restore-snapshot <snapshot>`; this will fail - below are the steps recommended in the help link
- `ddev rm`
- Edit the database image in .ddev/config.yaml to be v1.2.0
- `ddev restore-snapshot <snapshot>`; this should succeed
- `ddev rm`
- Edit the database image in .ddev/config.yaml to be v1.3.0, or comment out the specific image to use the default
- `ddev start`
- Project should start successfully …
> Inspect mysql version before failing when restoring a snapshot, #1170

- pkg/ddevapp/wordpress.go
`define('WP_ENV'...` is unnecessary for local development and shouldn't be part of the generated WordPress config template.
Removes it.
With no existing wp-config.php, run `ddev config` and ensure the generated wp-config.php does not define WP_ENV.
> Remove unnecessary definition from generated WP settings

- Makefile
We wait a long time for `make staticrequired`. I've added the pre-push hook, so every push has been close to 2 minutes. 
I think we have consensus that the golangci-lint linters as currently configured do mostly what we need. If we find anything they're not doing, we'll try to improve them.
> Use faster golangci-lint only,  less linting (build/test only)

- pkg/ddevapp/ddevapp_test.go
We have some occasional timeouts in TestDdevRestoreSnapshot when a snapshot restores dynamic content and then we test the content. 
This just increases the timeout on those; the default is 20s, which you'd think would be enough, but sometimes a dynamic project takes a really long time to come up.
> Add timeouts to queries on dynamic-generated URLS (tests only), fixes #1172

- docs/users/troubleshooting.md
There is no flag --db-image or --dbimage in ddev config to alter the db image to troubleshooting the use of old snapshots with the version 1.3.0. Also there was a typo in the name of the image.
It updates the documentation to a correct way to solve the problem.
> There is no way to alter dbimage with ddev config

- docs/index.md
added a link to Docker-for-Windows installation instructions
No link to Docker-for-windows installation instructions
Added a link to Docker-for-windows installation instructions
Documentation update, no test needed.
> Add a link to docker-for-windows

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
#414 points out that we lost the Debian package openssh-client in the v1.3.0 ddev-webserver. This puts it back in there.
This image can be used with ddev v1.3.0 by adding `webimage: drud/ddev-webserver:20181017_add_ssh` to config.yaml.
> Add openssh-client to web container for #414

- pkg/ddevapp/config.go
#1216 points out that `ddev sequelpro` creates .ddev/sequelpro.spf, which can accidentally get checked in because it's not gitignored.
This adds sequelpro.spf to the gitignore.
> Add sequelpro.spf to .ddev gitignore, fixes #1216

- .github/move.yml
Clean up OKR > Epics in the repo.
This is a movebot tool that lives in the .github folder of some of our other repos and allows for moving issues to another repo. I'll use to move the OKR epics out of this repo. https://github.com/dessant/move-issues
No.
> Add move.yml for moving issues out of repo

- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/pantheon_test.go
- pkg/ddevapp/providerDrudS3_test.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/util/capture.go
- pkg/util/utils_test.go
We *very* often see and have to retry TestDevRestoreSnapshot. Something is happening in the web container that we'd rather not have happen. Probably a SIGBUS error on fpm?
This ended up moving around a lot more stuff than I had hoped. I was done with the pattern of capturing UserOut every time we needed logs into a string, so refactored and added a ddevapp.CaptureLogs(). But that forced me to move the CaptureUserOut out of testcommon into util to resolve cyclic dependencies. I do apologize for all the moving around, but think that CaptureLogs() will be very useful to us. I still think there should be a pipe-oriented way to do this with the docker client, but I couldn't get it to work.
Most important, at the end I added the code to give us the logs when TestDdevRestoreSnapshot has a fail. …
> Add debugging for TestDdevRestoreSnapshot

- .circleci/config.yml
- Makefile
- cmd/ddev/cmd/compose-config.go
- cmd/ddev/cmd/debug.go
The nightly build broke last night because it explicitly called gometalinter, which we've stopped using. And there was a golint thing in there to complain about.
* Remove the gometalinter from the circle config
* Go ahead and fix the two things it was complaining about (anyway) so it's now clean with gometalinter anyway.
I note in https://github.com/golang/lint/issues/389#issuecomment-407672415 that golangci-lint explicitly disables this particular feature of golint. So that's why we see a difference between what we're using with it and with gometalinter.
> Nightly build shouldn't use gometalinter

- docs/developers/release-checklist.md
Checking a box allows version to be explicitly listed in the ReaTheDocs version switcher.
Adds a step to the release checklist to make sure the version is listed.
#1212
> Add step to ensure new versions are listed on ReadTheDocs

- pkg/ddevapp/config.go
- pkg/ddevapp/router.go
- pkg/ddevapp/templates.go
OP #883: People who have network-mounted home directories have loads of trouble using ddev, and we don't really have any reason to be bind-mounting from there any more.
* Stop using bind-mounted router cache and use docker volume instead
* Use import-db directory in project .ddev instead of global ddev dir
Start a project
Use `docker inspect ddev-router` to check mounts
Use `docker inspect ddev-<project>-db` to check mounts
Nothing has been added. 
OP #883 
This will probably deserve a minor mention in release notes.
> Stop mounting from global ddev directory, fixes #883

- cmd/ddev/cmd/export-db.go
- containers/ddev-dbserver/files/etc/my.cnf
- docs/users/cli-usage.md
- pkg/archive/archive.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/dockerutil/testdata/test-compose-with-streams.yaml
- pkg/version/version.go
ddev has always had an import-db, but always lacked the converse export-db. 
add `ddev export-db`
Try and verify results of:
* ddev export-db -h
* ddev export-db
* ddev export-db -f /tmp/junk.sql.gz
* ddev export-db -f /tmp/junk.sql --gzip=false
* ddev export-db --gzip=false | gzip >/tmp/junk.sql.gz
* TestComposeWIthStreams()
* TestDdevExportDB()
OP #767 
* At release time the Stack Overflow article on exporting should be updated to show this technique.
* We'll want to get the upcoming article on snapshot (which also mentions the export alternative) to use this instead of the complex in-container technique.
> Add export-db command, fixes #767

- containers/ddev-router/Dockerfile
- containers/ddev-router/healthcheck.sh
- containers/ddev-webserver/files/healthcheck.sh
- containers/ddev-webserver/test/testdata/nginx-site.conf
- containers/ddev-webserver/test/testdata/php/my-php.ini
- containers/phpmyadmin/Dockerfile
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router.go
- pkg/ddevapp/ssh_auth.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/dockerutil/testdata/test-compose-with-streams.yaml
- pkg/fileutil/files.go
- pkg/fileutil/files_test.go
- pkg/version/version.go
* Our healthchecks were relying on "localhost", which requires name resolution, and we don't actually need name resolution like that for things to work.
* The router healthcheck (#774) was always questionable about giving adequate info about failures, especially missing nginx config failures.
* Use 127.0.0.1 in healthcheck
* Improve ddev-router healthcheck to check nginx config so one can use `docker inspect ddev-router` to see what went wrong.
* Add log information from container checks to give context to failures.
* Break ddev-router by configuring the same additional_hostnames[] on two projects (or `docker exec -it ddev-router bash` and edit the /etc/nginx/conf.d/default.conf to remove the healthcheck). Examine the result. 
* Break other containers with `ddev exec -it <service>` and …
> Improve healthchecks, especially ddev-router, fixes #774, fixes #1237

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/start.sh
- containers/ddev-webserver/test/containertest.sh
- pkg/ddevapp/templates.go
- pkg/version/version.go
Testing our lovely brand-new `ddev composer` reminds one how much cache matters with composer. WE WANT PERSISTENT CACHE!
* Add a docker volume for cache to docker-compose.yaml
* Mount it in the web container
* Add COMPOSER_CACHE_DIR environment var in web container to point to it. 
* Bump the version on the web image.
* Do some composer actions
* rm your container
* Start another project
* Do some related composer actions
* Watch the packages load from cache
I didn't add testing, it's worth considering. I will think about it, it could work.
OP #1027
> Add persistent composer cache docker volume, fixes #1027

- .buildkite/test.sh
- .circleci/config.yml
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
We had some minor issues with tests after #1243 (stop mounting homedir) went in. There are a couple of things showing up:
* There are unnecessary attempts to clean up ~/.ddev/Test* when it shouldn't have been used.
* Only the test for upgrade of bind-mounted databases still should be looking in there. 
* Those directories are showing up as owned by root in our macOS testbots, which really shouldn't be able to happen.  (This ends up being a [PR removal of DRUD_NONINTERACTIVE](https://github.com/drud/ddev/pull/1241/files#r231994483), so will be fixed in that PR.
* There's currently no error checking on the rm -rf ~/.ddev/Test*, so the buildkite-agent startup is not detecting the root ownership problem.
Note that [TestConfigOverrideDetection](https://github.com/drud/ddev/blob/e87a4586fba2bc9d …
> Minor cleanup of test and buildkite setup (tests only)

- README.md
- cmd/ddev/cmd/root.go
- containers/ddev-webserver/files/etc/nginx/nginx-site-backdrop.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-default.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal6.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal7.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal8.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-typo3.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-wordpress.conf
- docs/index.md
- docs/users/cli-usage.md
- docs/users/troubleshooting.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/testdata/.ddev/nginx-site.conf
- pkg/servicetest/testdata/services/README.md
Links to ReadTheDocs pointed to the 'latest' tag, which is the bleeding edge build of the master branch. Almost all users should be directed to the 'stable' tag, which points to the most recent release tag's documentation.
Updates the links to use the 'stable' tag.
> Update documentation links to use 'stable' version

- pkg/util/utils_test.go
DRUD_NONINTERACTIVE being set caused TestConfirm() to fail because Confirm() just returns true when this variable is set.
Unsets the variable for the test, then resets it after the test is complete.
> Unset/reset noninteractive env var when testing Confirm()

- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer_test.go
- Some errors weren't being correctly captured, causing silent failures
- `composer create-project` was using /tmp/composer as a target dir, causing issues on Windows
- Capture errors and fail when `mv` and `rm` fail
- Update the install directory to `/var/www/html/.tmp-composer`, deleting after install
`ddev composer create <package> [<version>]` on Windows, specifically
Errors being correctly captured mean that this should no longer fail silently on automated testing.
> Update 'ddev composer create' install directory

- cmd/ddev/cmd/composer_test.go
- containers/ddev-webserver/test/containertest.sh
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
* There were a few assertions that were backwards, still are some.
* Failure in TestComposerCmd didn't give info about the failure, improve that message.
* There was an unbound variable in containertest.sh (web container test). Not sure how that passed ever.
> Minor test fixes for assertions and an unbound env var in web containertest

- pkg/version/version.go
This is just the temporary v1.4.0 container versions preparing for release.
They should be pushed again when the official tag is cut.
> Bump container versions for v1.4.0 release

- cmd/ddev/cmd/auth-ssh.go
Testing item `#3` (ddev auth ssh) on [test plan](https://github.com/drud/ddev/issues/1188#issuecomment-438435072) I find that it completely fails because there's not space between "winpty" and "docker", thus it fails to execute "winptydocker". This is ugly and completely prevents users from doing anything. Not sure how it passed on Win 10 Pro.
It wasn't really our business to add the winpty to the command any way, git-bash will tell them about it, the same as when they use `ddev ssh`.
> Stop using winpty, let them prompt for it

- containers/ddev-webserver/Dockerfile
In testing on Win 10 Home, Drupal composer builds would always time out getting the Drupal 8 core unzipped. It seems to work if the COMPOSER_PROCESS_TIMEOUT is bumped up. This shouldn't do anybody any harm.
I am pushing the updated ddev-webserver v1.4.0 image right now. So in a sense this is already in the final result even before it gets pulled.
> Add huge COMPOSER_PROCESS_TIMEOUT for Win10 reasons

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router.go
- pkg/dockerutil/dockerutils_test.go
@mafriend caught a bad panic doing a `ddev list`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x15ea4ed]
goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).GetWebContainerPublicPort(0xc000186540, 0x9, 0x0, 0x0)
/go/src/github.com/drud/ddev/pkg/ddevapp/ddevapp.go:1145 +0x6d
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).GetWebContainerDirectURL(0xc000186540, 0x0, 0x0)
/go/src/github.com/drud/ddev/pkg/ddevapp/ddevapp.go:1133 +0xb4
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).GetAllURLs(0xc000186540, 0xc0002d7a40, 0x190ecc3, 0x8)
/go/src/github.com/drud/ddev/pkg/ddevapp/ddevapp.go:1121 +0x2f5
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Describe(0xc000186540, 0xc00025ff20, 0x0, 0x0) …
```
> Fix panic in GetWebContainerPublicPort()

- cmd/ddev/cmd/composer_test.go
The full TYPO3 composer build in first pass of TestComposerCmd took more time than warranted.
Use a simpler build
> Make TestComposerCmd run faster, fixes #1268

- pkg/ddevapp/ddevapp.go
- pkg/util/utils.go
A regression in v1.4.0 meant that macOS users (and Linux users, though less likely) with UIDs above 60000 couldn't run ddev successfully (sudo failed, see OP #1281 )
The basically reverts back to the original behavior, automatically using a uid of 1000 if the UID is above 60000. Otherwise it just tries to use the normal user uid. This is fairly safe on macOS and Windows. It's highly questionable on Linux, where an inappropriate uid can create privileged files.
* Verify correct behavior with a normal lower-numbered uid (`ddev ssh` and `id`). The uid and gid should be the same as your macOS uid/gid.
* Create a macOS user with a high UID, say 1553427339. You can do this in system prefs, users and groups. You have to right-click the user for advanced options. I called my user "largeuid"
* …
> Make large uid users run successfully on macOS, fixes #1281

- containers/ddev-webserver/files/start.sh
- containers/ddev-webserver/test/containertest.sh
Our macOS testbots now use a huge UID for the "testbot" user. In the container, we try to use a valid user for apache. But that can't work on those macOS machines. 
So this uses the default 1001 user id where necessary.
> Change to use the a usable user and group in container test

- .circleci/circle_vm_setup.sh
- docs/index.md
- docs/users/docker_installation.md
- pkg/version/version.go
In OP #1286 we discovered that the project name for a docker-compose project doesn't work as expected in versions before docker-compose 1.21.0, see [1.21.0 release notes](https://github.com/docker/compose/releases/tag/1.21.0). Basically  the project name comes out differently - instead of the expected ddev-ssh-agent, the project name is "ddevsshagent", which breaks ddev looking for the started container. The actual docker-compose issue was https://github.com/docker/compose/issues/4002 and the fix to change the behavior was in https://github.com/docker/compose/pull/5788
So bumping the min version to 1.21.0 would have prevented #1286, and this should fix it. 
If we do a point release (likely) this can go in it.
> Bump docker-compose min version for project name, fixes #1286

- pkg/ddevapp/wordpress.go
#1175: Abspath detection was broken on windows
Sometimes it takes a month to realize it's a quick oneline fix to use the correct package for Windows support.
```
mkdir -p mywp/docroot/wp
cd mywp
touch docroot/wp/wp-settings.php
ddev config 
```
`docroot/wp-config-ddev.php` should include:
```
/** WP_SITEURL location */
define('WP_SITEURL', WP_HOME . '/wp');
```
#1175
> Fix WordPress Abspath detection on Windows, closes #1175

- pkg/testcommon/testcommon.go
#1270 is for fixing or retrying or mitigating some of our intermittent test failures. 
One of the big ones is on macOS we get a 502 resulting from a SIGBUS from php-fpm. This PR is (another) attempt to mitigate that, doing a retry. We have no control (that we understand) of this behavior, so might as well give it 2 tries.
If 502 in test, wait a second and try one more time.
No way to test, as this is intermittent.
> Retry 502 errors in tests on macOS, for #1270

- cmd/ddev/cmd/config.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/php/7.3/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.3/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.3/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.3/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.3/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.3/fpm/pool.d/www.conf
- containers/ddev-webserver/files/etc/php/7.3/mods-available/xdebug.ini
- containers/ddev-webserver/test/containertest.sh
- docs/users/cli-usage.md
- docs/users/extend/customization-extendibility.md
- pkg/ddevapp/templates.go
- pkg/ddevapp/values.go
- pkg/version/version.go
PHP 7.3 will be delivered December 13, 2018, and I'm sure our community will want it. 
The current version in this PR is "PHP 7.3.0RC5 (cli) (built: Nov 12 2018 13:37:51)", we'll want to make sure the actual released version gets into the final build for release v1.5.0
* Add php7.3 to the container
* Allow 7.3 config in ddev
* Bump the version to use the pushed ddev-webserver
* Configure a site for php7.3
* Visit the site, look at phpinfo (or on Drupal, admin/reports/status/php
* Use php --version to verify version.
* Added 7.3 in container tests
Note that php7.3 does not yet support php-memcached. It's unknown whether memcached will be ready at release, see https://github.com/php-memcached-dev/php-memcached/issues/408. This means we have to let our users know, and also re-enable …
> Support php 7.3

- cmd/ddev/cmd/list_test.go
We have intermittent failures of TestListContinuous, seemingly only on macOS. This just adds a tiny bit of detail to the assertion failure so maybe SOMEDAY we'll understand why.
> Try to find out why TestListContinuous fails on macOS

- cmd/ddev/cmd/composer-create.go
- docs/users/cli-usage.md
I keep searching for "ddev composer create" on google to get the right recipe for typo3 and drupal8
Add examples to `ddev composer create -h`
```
$ ddev composer create -h
Directs basic invocations of 'composer create-project' within the context of the
web container. Projects will be installed to a temporary directory and moved to
the project root directory after installation. Any existing files in the
project root will be deleted when creating a project.
Usage:
ddev composer create [flags] <package> [<version>]
Examples:
ddev composer create drupal-composer/drupal-project:8.x-dev --stability dev
ddev composer create typo3/cms-base-distribution ^9
Flags:
--dev                Pass the --dev flag to composer create-project
-h, --help               help for create
--no-dev             Pass …
```
> Add examples to ddev composer create

- .circleci/circle_vm_setup.sh
- .circleci/config.yml
- Makefile
gotestsum looks like a promising formatter for test output. 
https://circleci.com/blog/level-up-go-test-with-gotestsum/
https://github.com/gotestyourself/gotestsum
> Use gotestsum for test output on circleci

- containers/ddev-ssh-agent/Dockerfile
- containers/ddev-ssh-agent/files/entry.sh
- pkg/version/version.go
`ddev auth ssh` only currently loads keys named "id_rsa" and "id_dsa". And that's mighty limited. It should load all private keys.
Use the "file" command to find out which files in the directory are private keys, load all of them.
* Use (or create) some extra private keys. For example `ssh-keygen -t dsa`, `ssh-keygen -t rsa -f juergen_key`, `ssh-keygen -f ~/.ssh/junk`, `ssh-keygen -t ed25519 -f ~/.ssh/ed25519_sample`
* Run `ddev auth ssh`. You should be prompted for passphrases for each key that has a passphrase.
* The keys should now be available for use in the web container.
I haven't added any testing at this point.
#1291: ddev auth ssh does not add my second ssh-key to the container
#1282: ddev auth ssh doesn't work with with ed25519 keys
> ddev auth ssh should auth all available private keys, fixes #1291, fixes #1282

- cmd/ddev/cmd/auth-ssh.go
#1284 points out the `ddev auth ssh` doesn't work in a context that doesn't have "sh", like PowerShell. It was a silly oversight that I used "sh" in there. 
Use an array for the docker args, instead of trying to put them in a shell script.
Try `ddev auth ssh` and `ddev auth ssh -d /path/to/keys` in a few contexts, including bash, cmd, and PS.
I don't think this needs more test coverage.
OP #1284 "ddev auth ssh fails in Windows Powershell"
> Fix problem running "ddev auth ssh" from PS, fixes #1284

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/root.go
- pkg/archive/archive.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/settings_test.go
In #1304 I claimed to remove vetshadow declarations, but I apparently did a poor search, and apparently didn't look much at the results. Or else I rebased some back in. But there were a lot left.
This only removes //nolint vetshadow statements; we're not checking for them any more in our static analysis.
> Wow did I miss a lot of vetshadows [ci skip]

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router.go
- pkg/ddevapp/ssh_auth.go
- pkg/ddevapp/templates.go
- pkg/dockerutil/dockerutils.go
1. ContainerWait() was sometimes waiting for a really long time when one of the containers (usually db) had already exited. (It does seem like the code already handles this. I think the actual problem is waiting too long for an *unhealthy* container; in other words, the container does not display as unhealthy soon enough. )
It turns out that this behavior was mostly because we were polling health of the web container first and waiting for its healthcheck to complete, then tried the db container, which may have long since exited.
2. People have mentioned (and I've noticed) that ddev projects use quite a lot of CPU and battery. And it's mostly the healthcheck.  (I experimented with a number of solutions to this, but all of them result in `ddev start` taking longer, which I think is probably …
> Make ContainerWait and healthchecks smarter, fixes #1287

- cmd/ddev/cmd/composer_test.go
- cmd/ddev/cmd/list_test.go
- containers/ddev-webserver/test/containertest.sh
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/utils.go
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
- pkg/util/network.go
OP #1270 : Fixing intermittent tests and giving app.Logs() output to ones we have no way to understand.
* Adds debugging to gather info on intermittent failures on TestConfigOverrideDetection() on macOS with the web container failing. We don't have any information on why. This adds the container logs when that happens.
* Removes some some debug timing output that is no longer useful now that we don't start the app in TestStart.
* Remove success log output from http checks
* Rewrites TestDdevListContinuous. I wrote it. It never did what it claimed. No idea what it was testing.
* Speeds up TestComposerCmd even more (it was still taking 15 minutes on Windows) by using smaller packages.
* Speed up web container test by using smaller composer package.
> Improve and add test log debugging for several tests - tests only, for #1270

- pkg/dockerutil/dockerutils.go
@mafriend reported a panic when testing ddev-ui for release. Full information wasn't available, but this was the gist of it:
Check the error before using the results.
> Fix reported panic in GetContainerHealth()

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/utils.go
#1158: `ddev config` fails to look in parent directories for existing configurations.
- Searches through parent directories to find an existing .ddev/config.yaml
- Updates the user interaction text to add the "project root" case
Run `ddev config` in four key scenarios:
- In the project root with no existing .ddev/config.yaml
- In the project root with an existing .ddev/config.yaml
- In a subdirectory of the project root with an existing .ddev/config.yaml
- In a directory where no .ddev/config.yaml exists in any parent directory
#1158
> Look in parent directories for an existing .ddev/config.yaml, fixes #1158

- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/testcommon/testcommon.go
OP #1312 there was an edge case that resulted in a complaint about ssh-agent volume not existing.
If omit_containers["ddev-ssh-agent"] then don't refer the the volumes
* Make sure normal use of ssh authing works correctly. `ddev auth ssh` and access a host requiring ssh auth from within the web container.
* Start with omit_containers: ["ddev-ssh-agent"]  in the ~/.ddev/global_config.yaml; the ssh agent should not start, and you should get no errors.
* Start with omit_containers: ["ddev-ssh-agent"] at the project level. You should get no errors.
Nothing was added for this one.
> Fix problem where ddev-ssh-agent volume causes error, fixes #1312

- pkg/ddevapp/drupal.go
OP#1372 points out that our standard drupal 6 config in settings.ddev.php uses the mysql:// db_url, but php 7.2 with D6LTS wants the mysqli:// db_url. 
This just changes "mysql://" to "mysqli://" in Drupal6 settings.ddev.php. It doesn't seem to affect traditional Drupal 6 configuration.
* Configure d6 traditional project, verify that it works
* Configure [D6LTS project](https://github.com/d6lts/drupal) using PHP 7.2, verify that it works. 
* Disable php-mbstring in the web container to solve the problem discussed below:
* phpdismod php-mbstring
* killall -1 php-fpm
* At this point you should be able to install d6lts
Details about php-mbstring.
Note that there is a problem with D6LTS that I don't totally understand at install time. It insists:
> Multibyte string output conversion in PHP is …
> Use mysqli in db_url for Drupal 6, fixes #1325

- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/wordpress.go
- pkg/dockerutil/dockerutils_test.go
- pkg/dockerutil/testdata/test-compose-with-streams.yaml
OP #1310 is pretty simple: It points out that even though our comment in settings.ddev.local says "managed by ddev unless you remove this comment" we overwrite it anyway.
* Greps settings.ddev.local and related files to determine if we have the right to overwrite them.
* It appears that the TYPO3 code already did this, so it's unchanged.
Per the OP, 
Foreach CMS (drupal8 drupal7 drupal6 backdrop wordpress TYPO3) 
* Use `ddev config`; verify that the ddev-specific settings file gets created if it doesn't exist
* Use `ddev config`; verify that the ddev-specific settings file gets regenerated normally (normal changes will be overwritten)
* Use `ddev config`; verify that the ddev-specific settings file does *not* get overwritten if it exists and does *not* container #ddev-generated
* Updated …
> Add respect for #ddev-generated inside settings.ddev.php, fixes #1310

- pkg/version/version.go
Bump container versions to v1.5.0 for release
> Bump container versions to v1.5.0 for release

- docs/users/cli-usage.md
@ultimike points out a problem with unclosed tag in https://ddev.readthedocs.io/en/stable/users/cli-usage/#opt-in-usage-information - this should fix it. I guess readthedocs doesn't understand [`/>`](url)
> Fix unclosed tag (at least the way readthedocs sees it) [skip ci]

- .gitattributes
I'm obviously demonstrating my novice mastery of .gitattributes, but I have learned a whole lot. 
I don't seem to quite have it yet, but here's another pass to prevent the problem with all the png files in the repo showing as modified on checkout on macOS.
> .gitattributes, again. Fix problem with png files showing up modified in index on checkout

- pkg/ddevapp/templates.go
#1352 complains about performance on v1.5.0... We lost the ":Cached" attribute on the project mount. It's a significant difference.
In https://github.com/drud/ddev/commit/a403452284fc5564c610886f6487569abc6beb12 (#1277) there was a reorganization of the bind-mount syntax and the ":cached" attribute was lost. This is one of our most important weapons in the war against docker bind-mount slowness... and we lost it.
We were so focused on the webcache improvement that we lost track of the ordinary setup
Add cached back in.
On a D8 project
* `ddev start`
* `ddev ssh`
* `time drush si -y`
Without this I get about 100s to completion. With it I get about 50-60s to completion. So the regression was 40-50%
#1352 has people complaining about performance, especially on older MBPs. I'm not sure …
> Add the cached attribute back into docker-compose mount of project dir for #1352

- docs/users/extend/additional-services.md
- pkg/servicetest/testdata/services/docker-compose.beanstalkd.yaml
> Document how to add a beanstalk queue, fixes #1313

- cmd/ddev/cmd/import-db.go
- containers/ddev-dbserver/10.1/Dockerfile
- containers/ddev-dbserver/10.2/Dockerfile
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
There is no feedback during long running database imports.
This PR uses `pv` instead of `cat` to read the database dump which provides a progress bar on stderr.
- Import a (preferably large) database dump file with `ddev import-db` and check that a progress bar is displayed.
- Import a database dump with `ddev import-db -p=false` and check the progress bar is hidden.
Changes are visual only, and require a tty, so automated testing is quite tricky.
Fixes #1348
Automated processes that use `ddev import-db` should not be affected as we detect presence of a tty and disable the progress bar in these environments. There is also the `-p=false` switch to disable the progress bar if needed.
> Use pv to show progress bar during import-db

- pkg/version/version.go
v1.5.2 gets new containers, they have  been pushed with provisional push, here comes the bump.
> Bump container version numbers to v1.5.2

- docs/users/cli-usage.md
People often are baffled with a drupal 8 checkout that does not have the vendor directory; we might as well add the `ddev composer install` to the suggested work.
This PR also will be the first to run on testbots with docker 18.09.1
> Minor docs fix to remind people to composer install when using git checkout

- .buildkite/sanetestbot.sh
- .buildkite/test.sh
* We've had a perpetual problem with  `mkdir /c: file exists` bug, apparently https://github.com/docker/for-win/issues/1560
* Try executing the `docker run` command twice in sanetestbot.sh to maybe work around it.
* Improve reporting of ddev version in test.sh (buildkite)
* Improve checking of existing ddev version in sanetestbot.sh
Just read the code and a buildkite build.
> Try docker command twice in sanetestbot.sh, minor improvements to sanetestbot

- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/utils.go
We don't know enough about why webcache tests fail and need to get some more information
* Increase the amount of time allotted for bgcache to become available.
* Gather more information (healthcheck data) when TestHttpsRedirection fails with bgsync timeout
> Improvements to bgsync/webcache debugging, testing, and behavior

- cmd/ddev/cmd/root.go
- cmd/ddev/main.go
- pkg/globalconfig/values.go
- pkg/output/output_setup.go
It's just annoying to be asked about sentry when you're developing and you do a new build. No reason to ask if DDEV_NO_SENTRY.
> Don't ask about sentry if DDEV_NO_SENTRY

- cmd/ddev/cmd/logs_test.go
- docs/developers/buildkite-testmachine-setup.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router_test.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/ddevapp/templates.go
- pkg/testcommon/testcommon_test.go
OP #1297 points out that docker toolbox can't be used with xdebug; the hostname docker.host.internal is missing on docker toolbox (and Linux).
Add the correct IP (derived from DOCKER_HOST) explicitly to docker-composer.yaml in extra_hosts if we're on docker toolbox.
It's ok with me if reviewers just try XDebug on one platform; I can try it on all 4. 
Manually use xdebug and PHPStorm to demonstrate its correct behavior on 
* Docker Toolbox
* Docker for Windows
* Linux
* macOS
This finally adds coverage in TestDdevXdebugEnabled for xdebug attempting to make the connection back to the host. Yay!  And it should work on all 4 platforms.
OP #1297
> Support xdebug on Docker Toolbox, fixes #1297

- cmd/ddev/cmd/composer.go
OP #1373 points out that even though composer may fail in `ddev composer`, ddev still returns success. Shouldn't be that way. Could also hide test failures.
Break the composer.json in a project; maybe just introduce an extra brace.
`ddev composer install`
You should get an error return.
> ddev composer should fail if composer fails, fixes #1373

- pkg/ddevapp/config.go
OP #1374: dbimage statement in config.yaml stopped working when we added mariadb version support. Seems it was just one missing if statement.
Add the if statement
You should be able to set dbimage: in config.yaml (try using `dbimage: drud/ddev-dbserver:v1.5.2-10.2` to get 1.5.2). Or if you leave it out/comment it out, you should get `drud/ddev-dbserver:20190124_sql_triggers-10.2` with current code.
I didn't add anything.
OP #1374
> Make dbimage work again in config.yaml, fixes #1374

- cmd/ddev/cmd/root.go
- pkg/globalconfig/global_config.go
We get periodic problems with people running as root, the biggest thing is they get their ~/.ddev root-ownership, which breaks everything later. It mostly happens on linux, but there are sudo-addicts out there in the mac world too. OP #1379
`ddev hostname` though usually requires sudo
* For all commands but hostname, refuse.
* Check for the situation of them creating the ~/.ddev to make global config with `sudo ddev hostname` being the first command ever run, a very unusual situation.
* Try all commands
* try `sudo ddev start` and other things. Try `sudo ddev hostname junker99.ddev.local 127.0.0.1`, it should be allowed.
* Try removing or renaming ~/.ddev and then use `sudo ddev start` - should not create that directory. `sudo ddev hostname junker99.ddev.local 127.0.0.1` should succeed, …
> Prevent running as root except for ddev hostname, fixes #1379

- cmd/ddev/cmd/describe_test.go
- pkg/updatecheck/updatecheck.go
It would be nice if we had the capability of creating prerelease versions for community testing, etc. But we don't want ddev's update check to notice them.
When traversing releases in updatecheck.AvailableUpdates(), skip versions marked as prerelease.
> Skip prerelease versions in update check

- containers/ddev-ssh-agent/files/entry.sh
- pkg/version/version.go
#1394 points out that on Docker Toolbox, `ddev auth ssh` emits a very unsatisfying description of the key for which a passphrase is required. This is due to the fact that on Docker Toolbox, mounts make everything 777, and ssh-add is completely unwilling to operate on 777 keys. So we cat them into it. 
Announce the key name when this situation is encountered:
On Docker Toolbox (Windows), do a `ddev ssh auth`. You should see the key name announced.
> ddev auth ssh should show key it's working on (docker toolbox), fixes #1394

- pkg/ddevapp/apptypes.go
OP #1416: We were saying "Oh everything is fine" even on a project that doesn't support import-files
Error when import-files is used on a project that doesn't support it.
> Notify when the project type does not support import-files, fixes #1416

- containers/ddev-dbserver/10.1/Dockerfile
- containers/ddev-dbserver/Makefile
- containers/ddev-dbserver/test/testserver.sh
- pkg/version/version.go
I note that recent container builds are all failing on ddev-dbserver 10.1, because they issued a new one. It wasn't clear to me why our pin wasn't able to resolve the issues, but this bumps. 
Also debugged a problem that the Makefile had not been stopping on build failure as it should have.
> Bump pinned mariaDB pinned version to solve container build problems

- .buildkite/sanetestbot.sh
Testbots aren't useful when docker isn't working (or isn't working yet)
We often get test failures just because a machine (or docker) is coming up still.
Make sanetestbot wait (indefinitely) for docker to be ready. 
If it doesn't become ready, this at least takes it out of the rotation.
> Make sanetestbot.sh *wait* for docker to be ready

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
I noticed a comment in the TestMain for ddevapp about deleting more volumes when webcache PR landed. This just addresses that.
Oops, also in the process discovered a bug where we don't properly remove the unisoncatalogvol in ddev rm -RO
> Minor: Better volume cleanup before running tests and full remove

- docs/users/providers/pantheon.md
I had a hard time entering a project name as I did not understand that it is not the human readable name of my project in the Pantheon dashboard but rather the machine name used in the Pantheon URL. This is probably an issue for sites with spaces in human name, not sure about capitalization. Let's better explain what is meant by 'name' here.
> Specify how project names work with Pantheon

- pkg/version/version.go
OP #1431, but original PR (we regressed :) ) was https://github.com/drud/ddev/pull/738
If docker comes out with a release number with a "pre" after it ( [semver does not support versions with a pre unless the check has a pre](https://github.com/Masterminds/semver/issues/21).), like the current edge docker-compose: `1.24.0-rc1`. 
Add a "pre" back into the docker constraints. It needs a comment saying "DON'T LOSE THE -pre!"
> Fix version constraint to have a pre, fixes #1431

- .buildkite/test.sh
- .circleci/config.yml
#1425 had a failed rename that didn't come into play until the nightly build happened.
* Fix the rename
* Add container build to nightly
Review this.
Pull it
Hope it works.
We don't have an easy way to hit the nightly build with the api at this point.
> Fix nightly build broken by #1425

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/remove_test.go
- cmd/ddev/cmd/snapshot.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop.go
- cmd/ddev/cmd/stop_test.go
- cmd/ddev/cmd/utils.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/utils.go
- pkg/testcommon/testcommon.go
#1338 describes how a project can't be deleted by name (`ddev remove <name>`) after the project's directory has been removed. 
This updates the `remove` command to no longer use a convenience method that returns full-fledged apps because that method tried to read the config to fully initialize the app. This isn't necessary when removing an app, so now we're just pulling existing containers by names found in the container tags.
`mkdir ~/project`
`cd ~/project`
`ddev config --project-type php`
`ddev start`
`cd ~`
`rm -r ~/project`
`ddev remove project`
A test case has been added to ensure a project can be removed by name after deleting the project directory. Other test cases have been added to ensure that `start`, `stop`, and `describe` return consistent help text when the project directory …
> Allow a user to remove a project by name after deleting project directory, closes #1338

- pkg/version/version.go
v1.6.0 is coming up. This bumps the container versions. Provisional v1.6.0 versions have been pushed.
> Bump release version to v1.6.0 pre-pushed containers

- .buildkite/test.sh
* We moved sanetestbot.sh check to earlier in the script
* But docker containers might still be running, preventing sanetestbot from binding to ports
* Kill docker containers both before and after sanetestbot. That way we ought to get them most of the time.
> Kill containers before sanetestbot

- pkg/ddevapp/utils.go
In testing I found a place where it complains about the NFS volume not existing on `ddev rm` with non-NFS.
Use dockerutil.RemoveVolume()
> Don't complain if can't kill nfs volume

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- Makefile
On the nightly build last night we had an issue where nssm was not downloading properly. But the failure was in the unzip, and it should have been on the download. This adds -f or --fail to the various curls used in the build process.
In passing, also:
* Moves docker-compose to brew install
* Minor change to ghr download technique
> Improve curl commands so they fail when they should on build

- docs/index.md
Docker for Mac now supports only macOS Sierra (10.12) and higher. That means we have the same constraint. So fix docs to say that.
> Increase version requirement for ddev to macOS Sierra 10.12 since docker increased theirs, fixes #1466

- scripts/windows_ddev_nfs_setup.sh
OP #1452 reports that the Windows NFS installation script fails when there are spaces in the user's names.
Use $HOME instead of ~, and put path in quotes.
> Fix Windows NFS script when username has spaces, fixes #1452

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
Golang bumped to v1.12; homebrew won't upgrade unless we ask it to upgrade. We'll want to do something more robust in the future, but for now, just invalidate the homebrew cache.
> Invalidate homebrew cache with new version

- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer_test.go
OP #1457 reported a warning (it turned out to be only a warning) that the temp directory on `ddev composer create` was not being deleted. It turns out that we had actually improved the code that moves everything, so it was no longer necessary to do the cleanup at all.
Remove the obsolete code, and the defer that called it.
```
mkdir junk && cd junk
ddev composer create --prefer-dist --no-interaction --no-dev psr/log 1.1.0
```
* You should not see a warning about failing to remove
* `ls -a` should show no leftover .tmp directory
OP #1457
> We no longer have to cleanup the temp dir as it's cleaned up in the body, fixes #1457

- cmd/ddev/cmd/import-db.go
- docs/users/cli-usage.md
OP #1483: The usage of .mysql and .mysql.gz was not documented.
* Document both
* Add both to `ddev help import-db`
> Add .mysql* to list of accepted import-db filetypes, fixes #1483

- pkg/ddevapp/templates.go
OP #1477 reported that (apparently) on import of a large db it takes longer to start up than our db healthcheck allows. This increases that time. The OP reported it solved their problem.
> Increase timeout for db startup, fixes #1477

- containers/ddev-router/nginx.tmpl
- pkg/version/version.go
Having long server names causes the ddev-router to cease working.
Error message during start:
```nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64```
This patch increases server_names_hash_bucket_size to the maximum possible size (128).
Create a server name longer than 32 characters and you should see, that none of your projects will start again.
> Make very long server names possible

- pkg/ddevapp/config.go
OP #1455:` mariadb_version: 10.1` no longer had any effect in ddev v1.6.0
This was caused by a regression introduced in #1402, which was supposed to solve the *other* problem of not being able to override mariadb_version with a custom DBImage. 
This fixes the direct problem by setting DBImage to "" before processing the config.yaml, then only overriding it if it hasn't been changed on import of the config.yaml.
I'd love to see a very generic approach to this, and we may need one as we introduce other specialty images like the 10.1 dbimage. 
* `ddev start` with `mariadb_version: 10.1` and with `mariadb_version: 10.2`. Both should result in containers that are what you asked for (see `docker ps -a | grep "ddev-.*-db$"` Note that the one that doesn't match your db (normally 10.1) will fail …
> Regression: mariadb_version should work correctly, but be overridden by DBImage, fixes #1455

- .circleci/config.yml
CircleCI was costing way too much for macOS builds.
Disable 3 of the 4 macOS builds, just keep the main nginx-fpm one.
> Remove 3/4 of macOS CircleCI tests, fixes #1487

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/values.go
PHP7.1 is outside its window of support, is in security-only, see http://php.net/supported-versions.php
So we should make our default PHP 7.2.
> Change default PHP version from 7.1 to 7.2

- build-tools/makefile_components/base_build_go.mak
GOCACHE was broken, so builds were slow
Normal build-tools and golang-build-container maintenancy to bring up to golang v1.12.1
Fix the GOCACHE issue.
> Update to build-tools 2.2.1: Golang v1.12.1 and fix GOCACHE

- pkg/version/version.go
Preparation for v1.7.0 release. The new containers have been pushed.
> Bump containers to v1.7.0

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config-global_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/debug-compose-config_test.go
- cmd/ddev/cmd/debug-nfsmount_test.go
- cmd/ddev/cmd/remove_test.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop_test.go
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.10.1
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.10.2
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.imagespec.10.1
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.imagespec.10.2
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/dbimage-10.1/.ddev/config.yaml
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/dbimage-10.2/.ddev/config.yaml
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/mariadb-version-10.1/.ddev/config.yaml
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/mariadb-version-10.2/.ddev/config.yaml
- pkg/globalconfig/global_config.go
#1517: Sadly, `ddev config --mariadb-version 10.1` creates a config.yaml with the `dbimage...10.2`... and it shouldn't even have a dbimage at all. 
In the midst of config spaghetti, this makes sure the default dbimage in config handling gets set right.
Oh, this has to be tested against every regression in its sad history.
But 
* `ddev config --mariadb-version 10.1` should work with the .ddev/config.yaml showing the right stuff (and not having a dbimage spec)
* `ddev config --mariadb-version 10.2` should do the same
* Manually changing to 10.1 or 10.2 in the config.yaml should work
* Manually setting the dbimage for 10.1 or 10.2 should work
I'm not sure if it's worth getting this into v1.7.0 or just telling people not to use `ddev config --mariadb-version` for this release. I'm not …
> Fix regression with mariadb-version arg, fixes #1517

- docs/developers/buildkite-testmachine-setup.md
Minor fix to Windows testbot setup for buildkite agent; matters only to quicksprint.
> Add fileinfo to required php extensions in docs [skip ci] [ci skip]

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
There are configuration files for posgres support in the ddev-webserver container, but the php*-pgsql packages are missing.
Updates the Dockerfile to install the needed php*-pgsql packages.
To test if pgsql is loaded, you can run `php --info | grep pgsql` in the container.
> Add missing php-pgsql packages to ddev-webserver container

- containers/ddev-dbserver/10.1/files/etc/my.cnf
- containers/ddev-dbserver/10.2/files/etc/my.cnf
- pkg/version/version.go
* We were using log-bin=on, which actually doesn't just turn on log-bin but also sets the name of the logs to "on.*". Might as well use the default.
* binlogs were never being purged because `expire-logs-days` was set to the default 0, never purge.
Minor config change.
* `ddev ssh -s db`
* `mysql` and inspect values with `SHOW VARIABLES LIKE 'expire%'` and `show variables like 'log_bin%';`
* Maybe verify that no extra files are around when you start up a day later.
Additional ideas:
* Purge logs on start with `PURGE BINARY LOGS BEFORE NOW();`
* Set `log_bin_basename = /tmp/mariadb-bin` - (credit @freelock) - that would make it so that when a new container was created the binlogs would be left behind.
> Minor improvements to mariadb binlog management

- docs/users/cli-usage.md
* There was no composer build instruction for a wordpress startup.
* Some of the other items needed a little work
* Add `ddev composer create wordpress/skeleton`
* Shorten the other composer recipes
Try out the new instructions, especially with wordpress
> Add wordpress composer recipe, simplify others, docs only [skip ci][ci skip]

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
CircleCI announced (finally) (and only 16.04?) a supported Ubuntu image, which comes with Docker set up properly on it. This is  a first try with it.
See https://discuss.circleci.com/t/default-machine-executor-image-update/29308
> Use CircleCI's new Ubuntu 16.04 machine image

- .circleci/generate_artifacts.sh
- docs/developers/release-checklist.md
OP #1516 - Homebrew bottle creation has been a big pain. With this PR, the bottle is just created via a script, instead of building it using `brew bottle` during artifact creation.
> Generate homebrew bottles for Linux and macOS for #1516

- README.md
- build-tools/README.md
- cmd/ddev/cmd/cmd_version.go
- cmd/ddev/cmd/cmd_version_test.go
- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer.go
- cmd/ddev/cmd/composer_test.go
- cmd/ddev/cmd/root.go
- containers/ddev-bgsync/README.md
- docs/developers/buildkite-testmachine-setup.md
- docs/index.md
- docs/users/developer-tools.md
- docs/users/docker_installation.md
- docs/users/performance.md
- pkg/ddevapp/raven.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/nodeps/utils.go
- pkg/util/utils.go
- pkg/version/version.go
- pkg/version/version_test.go
OP #960 : `ddev version` still needs to show the OS information
* Add OS info
* Add docker-toolbox/docker-for-windows info
* Add --version flag
Use
`ddev --version`
`ddev version`
OP #960
> Improve "ddev version" and add --version flag, fixes #960

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/hostname.go
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/pause_test.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop_test.go
- cmd/ddev/cmd/utils.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/utils.go
- pkg/globalconfig/global_config.go
OP #1523: `ddev stop -RO <projectname>` doesn't remove project from global config.
Accept a project name for deletion even if no containers are associated with it.
* `ddev config` to create a project in global list. `ddev rm -RO <name>` to get rid of it.
* `ddev config` and `ddev start` and `ddev rm` to create project and start it and stop it. Then `ddev rm -RO <project>` to verify complete cleanup (look in ~/.ddev/global_config.yaml)
I think it's probably best to cover this with some extensive testing in #642
OP #1523 
But #642 (manage global list more completely) will again touch this.
> More robust handling of ddev stop -RO, remove from global list, fixes #1523

- docs/users/extending-commands.md
In a lot of situations the previous examples in the docs don't cover an apt-get install correctly because apt-get tries to do interactive things. We don't want that. This is better.
> Improve docs with DEBIAN_FRONTEND=noninteractive in apt-get examples [skip ci][ci skip]

- docs/users/extend/customization-extendibility.md
The phrase says PHP when is a MySQL phrase
> Change PHP typo when it should be MySQL

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
OP #1235: With a single hostname (the default situation, like "somesite.ddev.local", the name was resolved from within the web container as being the ddev-router.
However, as soon as you added additional_hostnames or additional_fqdns, this feature disappeared
The docker-compose.yaml was being incorrectly generated. A separate entry in external_links: was required for each of those entries.
* Create a project with additional_hostnames and additional_fqdns.
* `ddev ssh`
* You should be able to `curl http://hostname1.ddev.local` successfully (it should be going to ddev-router)
* Verify that `ping hostname1.ddev.local` actually resolves to ddev-router's IP address.
TestInternalAndExternalAccessToURL() was updated to do *lots* of hits both inside and outside.
OP #1235 …
> Add separate lines for each external_links, fixes #1235

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
app.CaptureLogs() has long been problematic in not working on Windows and using CaptureStdout, which is awkward. But there's a fairly easy workaround.
Change it.
> Fix CaptureLogs to not use CaptureStdOut

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
OP #1553 points out that the ddev_drush_settings.php is getting created in the projectroot instead of in the settings directory.
This turns out to be a side-effect of default project creation, the project type was being set *after* the site settings file was derived.
* Move the settings file setup to after the reading of the project config.yaml
* Add test coverage
`ddev start` 
You should be able to `drush sql-cli` successfully if you have a drush8 on the host.
Or just verify that ddev_drush_settings.php got created in the (Drupal) sites/default
Added simplistic test coverage for the settings location and the ddev_drush_settings.php in TestDdevFullSiteSetup
OP #1553
>  SetSiteSettingsPaths() has to be set after we've read the config, fixes #1553

- pkg/servicetest/testdata/services/docker-compose.solr.yaml
The suggested DDEV Solr configuration at https://ddev.readthedocs.io/en/stable/users/extend/additional-services/#apache-solr does not include a persistent Docker volume.
It adds one.
1. Copy the Compose file, then run `ddev start`. DDEV will tell you that it created a volume.
1. Run `docker volume ls` and ensure that the volume is there. It will be named `ddev-PROJECTNAME-data`.
This is something the user would add. It won't break DDEV even if it's broken.
- https://github.com/drud/ddev/pull/1526
> Use docker volume in sample apachesolr config

- pkg/servicetest/testdata/services/docker-compose.solr.yaml
Updated the Apache Solr installation instructions to default to v6.6.
It also makes it more clear what the expected directory structure
should be.
Per issue #1547, the included config file for Solr installed v5.4, which is no longer supported.
This PR updates it the Solr install to v6.6 and improves the documentation.
Use the config file to install Solr. Expected results: it installs Apache Solr 6.6 instead of the previous 5.4.
None.
https://github.com/drud/ddev/issues/1547
Don't know (-:
> Improved Solr install docs, update to 6.6, fixes #1547

- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
#653 requests blackfire.io. This adds it to the web container.
We'll have to evaluate if the size difference is acceptable, https://hub.docker.com/r/drud/ddev-webserver/tags/
>  Add blackfire.io to web container, fixes #653

- pkg/servicetest/testdata/services/docker-compose.beanstalkd.yaml
- pkg/servicetest/testdata/services/docker-compose.memcached.yaml
- pkg/servicetest/testdata/services/docker-compose.solr.yaml
@damienmckenna and @mglaman point out in #1549 that we have `restart: always` in the additional service examples, but `restart: "no"` is what is actually always used in docker-compose.yaml (for a really long time). 
Changing it here.
> Use restart: no on additional service examples

- pkg/ddevapp/ddevapp_test.go
- pkg/testcommon/testcommon_test.go
There are remaining problems with intermittent test failures on Win 10 Home/Docker toolbox. 
Sometimes the TLS certificate is not respected in a few tests.
My only theory is that the notification to the ddev-router doesn't come through in time before tests are already accessing https.
Slow things down on Docker toolbox. In test situation, wait a few seconds after app.Start() before hitting it with web traffic.
> Test improvements for Win 10 Docker Toolbox

- containers/ddev-webserver/scripts/start.sh
- pkg/ddevapp/config_test.go
- pkg/ddevapp/testdata/TestPHPOverrides/.ddev/php/my-php.ini
- pkg/ddevapp/testdata/TestPHPOverrides/phpinfo.php
- pkg/version/version.go
OP #1556 - apache-cgi doesn't respect PHP overrides. 
Copy the overrides into /etc/php/*/apache2/conf.d in addition to copying into fpm and cli directories.
Added TestPHPOverrides, which tests for the PHP override on all webserver types
> apache-cgi should respect php overrides, fixes #1556

- containers/ddev-dbserver/10.1/files/docker-entrypoint.sh
- containers/ddev-dbserver/10.2/files/docker-entrypoint.sh
- pkg/version/version.go
OP #1541 points out that if mysql overrides are done, you can't do a `ddev start` after doing a `ddev pause` because of permissions problems inside the container. 
Use sudo to copy those files.
Configure mysql overrides for a project. Start the project. `ddev pause`, `ddev start`
> Use sudo to copy mysql config files, fixes #1541

- docs/users/extending-commands.md
There was a missing markdown close tag on the extending-commands.md which resulted in text rendering as code and code rendering as text.
Adds the close tag.
Look at the page in gitlab's markdown. It obviously renders broken.
https://github.com/drud/ddev/blob/master/docs/users/extending-commands.md
> Fix markdown format for hook examples.

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- containers/ddev-dbserver/10.1/files/etc/passwd
- containers/ddev-dbserver/10.2/files/etc/passwd
- docs/users/extend/customizing-images.md
- mkdocs.yml
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
- pkg/version/version.go
* Our web container gets bigger and bigger
* Users will always have new requests for containers, or for extra config
* Uses docker-compose up --build, so that a build context can be added for dynamic containers
* If .ddev/db-build/Dockerfile or .ddev/web-build/Dockerfile exists, the Dockerfile there will be used to build the web or db image. 
* config.yaml `webimage_extra_packages` and `dbimage_extra_packages` allow just adding debian packages without writing a Dockerfile.
* See the [docs](https://github.com/drud/ddev/blob/a04396fee1dc0090a8529c1c89c7c3b02cd0d95b/docs/users/extend/customizing-images.md)
TODO:
* Create a .ddev/web-build/Dockerfile with these contents:
```
ARG BASE_IMAGE=drud/ddev-webserver:latest
FROM $BASE_IMAGE
RUN touch /var/tmp/this-was-from
RUN apt-get update && …
```
> Use docker-compose build for dynamic containers, allow easier container config

- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/testcommon/testcommon_test.go
I had second thoughts about the hacky way I accommodated slow Docker Toolbox ddev-router updating. 
Do it with app.StartAndWaitForSync() instead.
> Use StartAndWaitForSync to accomodate docker toolbox slowness

- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/exec_test.go
- pkg/ddevapp/ddevapp.go
People have long been frustrated by the inability to interact with the console using `ddev exec`. But we long since have been able to do that, but didn't add it to the `ddev exec` command.
Allow interaction when doing ddev exec. Kind of makes it identical to `ddev ssh`, but no direct interaction with the container.
`ddev exec mysql`
`ddev exec vi index.php`
https://github.com/drud/ddev/issues/1023 will be adding bash interpretation to ddev exec
https://github.com/drud/ddev/issues/1162 will eventually make ddev exec handle stdout/stderr and exit values correctly
This will be an important announcement, and could conceivably affect some people's workflow.
> ddev exec command should allow tty interactions

- docs/users/cli-usage.md
People often don't "get" that ddev works fine with basic PHP projects. 
Add a "PHP quickstart" to the docs.
> Add quickstart for PHP project [skip ci][ci skip]

- docs/users/troubleshooting.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevhosts/ddevhosts.go
OP #948 explains the bug in Windows where /etc/hosts entries cease to be recognized when you hit 10 entries. 
It would be nice to completely re-do goodhosts to think in terms of a map[ip]hostname that could be written in any fashion, but goodhosts is so fundamentally line-oriented that it would be very risky.
* Detect if there are more than 9 entries on the ip address line in the hosts file on WIndows.
* Warn in that case (windows only)
* Add docs
On Windows, create multiple entries against the dockerIP (usually 127.0.0.1 on Docker Desktop)
See the warning.
Read the docs.
I don't think this is very easy to test because of the need for escalated privileges to edit the hosts file.
OP #948
> Warn windows users when hosts file has too many entries on a line, fixes #948

- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer.go
- cmd/ddev/cmd/composer_test.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/exec_test.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/ssh.go
- docs/users/extending-commands.md
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/servicetest/servicetest_test.go
People always expect a shell interpreter for `ddev exec` and exec hooks. We have used none.
Add bash in.
* `ddev exec ls`
* `ddev exec "ls -l | grep apache"`
* post-start hook `exec: "set | grep DDEV"
Everything else you can think of.
```
hooks:
post-start:
- exec: set | grep DDEV
- exec: "set | grep DDEV"
- exec: ls >/tmp/junk
- exec: ls *.php
```
OP #1023 
* I couldn't figure out how to handle existing `bash -c "..."` with this, and it seemed less complex to just ask people to remove the "bash -c" from existing hooks. So... ask them to update hooks that might include `bash -c`.
* There is an existing [stack overflow article](https://stackoverflow.com/questions/50971602/how-can-i-use-bash-constructs-like-cd-or-or-redirection-with-ddev-exe) that needs to be updated or deleted (it's now …
> Interpret ddev exec and hooks with bash, fixes #1023

- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/utils.go
- pkg/globalconfig/global_config.go
In #1574 a user reported destruction of their entire home directory by a `ddev composer create` command that mistakenly operated on the home directory.
* Revert #1275, which allowed automatic searching of parent directories for a project.
* Instead, do the search and note the results during `ddev config`
* Prevent users from using `ddev config` in their home directory.
* Remove the --no-interaction behavior from `ddev composer create` that allows wholesale destruction without the user saying "ok".
* Try `ddev config` in home directory.
* Create a ~/junk folder and `ddev config` in it. Then create ~/junk/sub1 and `ddev config` in it. It should be willing to config, but warn about the existing parent.
* Run `ddev composer create --no-interaction`. The composer portion should run without …
> Revert parent config search, prevent directory destruction, hopefully fixes #1574

- containers/ddev-webserver/files/etc/drush/drushrc.php
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
From long ago, long, long ago, `drush` defaulted to --yes when in `ddev exec` context. It wasn't probably ever reasonable behavior, but it was there to avoid the interactive prompt mostly in exec hooks.
Remove that special behavior.
`ddev exec upc --security-only` on a Drupal site that needs update, it should stop to confirm.
`ddev exec drush sql-drop` - it should stop to confirm.
OP #1584, thanks @damienmckenna 
There may be people that have counted on this in exec hooks. So release notes have to tell them to add -y to their exec hooks.
> Remove drush --yes behavior when in ddev exec behavior, fixes #1584

- pkg/version/version.go
One inconsequential change went in with a different container name for testing. Set it back to v1.8.0
This will get tested in other PRs, so not testing here.
> Re-use the v1.8.0 tag even though small change was made in web container [skip ci]

- cmd/ddev/cmd/stop.go
- cmd/ddev/cmd/stop_test.go
* A small typo in the description of ddev stop was discovered in testing.
* The completion message said the project had been "stopped and removed", which might alarm people.
* Fix the typo
* Change wording to "has been stopped"
> Fix typo in description, change completion to 'has been stopped'

- pkg/ddevapp/ddevapp.go
In assisting a user with a mkcert problem, I noted that the actual error from getCARoot() doesn't get properly reported, making troubleshooting harder.
Report it.
Break mkcert and then do ddev start:
* remove or rename mkcert
* Remove the CA (`rm -r $(mkcert -CAROOT)`)
This is just an improvement of an error message.
> Report mkcert err to user

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
We changed the default PHP version to 7.2 a while ago, but when the container is run by itself it still defaults to 7.2
Change it to 7.2 in the container (when run without ddev)
> Update PHP_DEFAULT_VERSION in web container

- .buildkite/sanetestbot.sh
ddev has been updated on the buildkite testbots, but sanetestbot.sh doesn't work with 1.8. 
Update the logic.
> Make sanetestbot.sh work with ddev v1.8

- pkg/ddevapp/config.go
- pkg/ddevapp/utils.go
OP #1580: hostname output in various places can be random (because of underlying golang map), make it standard alpha order.
* Sort the array
* Also move the https URL before the http URL in `ddev list`, as it's given priority everywhere else at this point.
* Add additional_hostnames to a project and `ddev start`. The output should be the same every time.
* Hostnames should also be added to /etc/hosts in the same correct alpha order.
* `ddev list` should show https URL first.
OP #1580
> Fixed order of hostname output, show https first, fixes #1580

- docs/users/cli-usage.md
Users are now instructed to either run the install via '/install.php' or 'druhs si'.
The quick start docs were missing the d6/d7 step of running the install script. 
Updated the doc to include those changes
> Fix d6/d7 quick start install step

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
OP #1423: Teams often share a project and don't run `ddev config` individually. So the settings.ddev.php or equivalent needs to be created on `ddev start`
Add settings creation into the post-start action.
* Remove settings.ddev.php
* ddev start
* Verify that it exists again
Unfortunately this needs to be tested in every supported CMS; TYPO3 and Wordpress and Backdrop are the most likely places for unexpected consequences.
> Create settings.ddev.php on ddev start, fixes #1423

- pkg/ddevapp/config.go
Recently we added the ability to configure the mailhog port and phpmyadmin port in config.yaml. However, it really shouldn't show as an active item by default, can confuse people thinking they should mess with it.
Do the same as we do with the images; if they're set to default, don't include them in the output config.yaml
This also makes `provider` not show in the config.yaml unless it has been overridden. Most people who aren't using Pantheon won't need to see that ever.
`ddev config`. The resultant config.yaml should not show a mailhog_port or phpmyadmin_port (although the commend shows how to do so.)
None added.
#1594 added the PHPMyAdmin and Mailhog port configuration
> MailhogPort and friends should not normally show in config.yaml

- pkg/ddevapp/config.go
#1610 points out that there is a capitalization error in the generated .ddev/.gitignore. 
Fix it
On Linux, or other case-sensitive filesystem:
* Check out a project from git
* Make sure it's clean (`ddev status`)
* `ddev config --webimage-extra-packages=php-ldap --db-image-extra-packages=vim
* `ddev start`
* Verify it's still clean `git status`
* `ls -lad .ddev/.*image*` to make sure the gitignored directories are in there.
> Fix capitalization error on gitigore webimageExtra dbimageExtra, fixes #1610

- docs/users/extending-commands.md
The docs still showed adding extra PHP modules with post-start hooks.
Update doc to use webimage_extra_packages
> Use webimage_extra_packages for PHP module addon example [skip ci][ci skip]

- cmd/ddev/cmd/root.go
- pkg/nodeps/utils.go
- pkg/output/output_setup.go
@mglaman reported that Sentry prevented ddev operation when off-internet on a plane in #1601 
Test connectivity via a DNS request before trying to:
* Use Sentry
* Check for available updates
This doesn't (yet?) attempt to anticipate docker pulls that would break. 
DDEV_NO_SENTRY environment variable should be empty or deleted
SentryDSN variable should be set properly so that it's in the executable
Instrumentation should be enabled in ~/.ddev/global_config.yaml
* Use `ddev start` when connected/not connected to internet. When connected, you should see the Sentry event come through. (Study "ddev start" and click on "events"). When not connected to the internet you should have no interruption or problem.
* Test github release check by forcing it. `touch -mt 201705010101 ~/.ddev/.update` will …
> Make sure internet is active before trying operations that might hang, fixes #1601, Fixes #431

- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/ssh.go
- docs/users/cli-usage.md
- docs/users/developer-tools.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
A couple of people ran into trouble using `ddev exec` and `ddev ssh` with 3rd-party containers that did not have bash on them in v1.8.0
* Use "sh" for `ddev ssh` except on our own containers, where we know bash is there; in that case use it.
* Use "sh" for ddevapp.Exec()
* Use ddev ssh on one of our containers and on a 3rd party container
* Use ddev exec on one of ours and on a 3rd-party container
* Make sure that an exec hook still works. 
Unfortunately, we don't have the ability to target hooks yet, so
> Use sh instead of bash for ddevapp.Exec

- containers/ddev-router/docker-entrypoint.sh
- containers/ddev-router/gen-cert.sh.tmpl
- pkg/version/version.go
If the ddev-router is paused and then started, it loses any existing certificates in the router's nginx config. It shouldn't do that; it works OK in many cases because of default "*.ddev.local" added there, but doesn't work if people have subdomains like "xx.yy.ddev.local", for example. 
Don't recreate certs in master.crt unless the file does not exist.
* Create a project with name "x.y.ddev.local"
* Verify that https works with it.
* `ddev pause`
* `ddev start`
* It should still work, even though you see the router being restarted
> Router should not blow away existing certificates on startup

- cmd/ddev/cmd/cmd_version_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/hostname.go
- cmd/ddev/cmd/logs_test.go
- docs/users/cli-usage.md
- docs/users/developer-tools.md
- docs/users/extend/additional-hostnames.md
- docs/users/extend/additional-services.md
- docs/users/extend/custom-compose-files.md
- docs/users/extending-commands.md
- docs/users/troubleshooting.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/values.go
- pkg/dockerutil/testdata/test-compose-with-streams.yaml
- pkg/servicetest/testdata/services/docker-compose.solr.yaml
- pkg/version/version.go
- pkg/version/version_test.go
It's icky messing with the hosts file and requires admin privileges.
Windows has a limit of 9 aliases on a line in the hosts file. 
OP #416 requested non-hosts-file name resolution
OP #834 requested the ability to change the TLD in use, as is provided here.
When the hostname is already resolvable, do not add it to the hosts file.
Note that this will require a transition to using "ddev.site" instead of "ddev.local"
* Remove all ddev hostnames from /etc/hosts
* `ddev start` should not result in hostnames being added, and project should work normally.
* Try additional_hostnames and additional_fqdns. additional_fqdns that resolve in DNS should work just fine anyway. (the resolved IP is not correct, so we add to /etc/hosts)
* Test offline. It won't work until a restart, the restart should add …
> Use DNS for name resolution in most cases, fixes #416, fixes #834

- .buildkite/nfstest.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
In #1616 we're changing what gets mounted by nfsd; The resulting testbot setup doesn't match what is shared, etc. So the testbots have to have some maintenance, and we need to check against what's actually shared.
Improve buildkite and circleci setup.
> Fix nfstest.sh to use home dir instead of whole /Users (Test only)

- .circleci/linux_circle_vm_setup.sh
- cmd/ddev/cmd/debug-nfsmount.go
- cmd/ddev/cmd/debug-nfsmount_test.go
- docs/users/performance.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- scripts/debian_ubuntu_linux_ddev_nfs_setup.sh
- scripts/macos_ddev_nfs_setup.sh
- scripts/windows_ddev_nfs_setup.sh
#1471 points out that our approach to NFS security is lax at best. This issue will try to improve that situation, or at least inform users on how they can do what needs to be done in their environment.
* Improve NFS install scripts with better docker recipe
* Uninstall any existing nfsd. Windows: `sudo nssm stop nfsd; sudo nssm uninstall nfsd; rm ~/.ddev/nfs_exports.txt`. Linux: `sudo apt-get remove nfs-kernel-server nfs-common; sudo rm /etc/exports`. macOS: `sudo nfsd disable; sudo rm /etc/exports`
* The NFS install scripts have to be re-tested on all 4 OS environments.
> Improve NFS security posture, fixes #1471

- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/utils.go
- docs/users/cli-usage.md
@ultimike and @rickmanelius both recommended that the new global site listing default to `ddev list --all`, as they both got caught by missing actual global projects. 
`ddev list` shows all.
`ddev list --active-only` shows only sites active in docker.
> Change ddev list to default to showing all

- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
I noted that project_tld was being displayed with its default "ddev.site" in the config.yaml, and most people don't need to be bothered with that. It's explained in the comments below.
If it's set to the default, empty it for usage in writing config.yaml
`ddev config` and see if project_tld is populated in config.yaml
> Leave the project_tld out of defaults in config.yaml

- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
#1488: "Drush launcher" has become the standard way to globally-launch drush. It picks up a site-local drush (the standard technique for drupal8) and with this installation falls back to using drush8, which will work for Drupal7 and Backdrop.
Change the install to install drush launcher and drush8
> Use drush launcher and drush8 in container, fixes #1488

- docs/users/cli-usage.md
#1635 isn't the first time somebody tried to check out the "example" git repo shown there. It's an actual issue people stumble on.
* Use the composer examples first, instead of the git examples.
* Mention that they're example repos.
> Make clearer that git clone examples are examples, fixes #1635 [skip ci][ci skip]

- docs/users/extend/additional-services.md
- docs/users/step-debugging.md
- gh-1646
- In some documentation, bolded text (e.g. `**I am some bold text**`) is used instead of headings, sometimes with only one newline after the end of the bolded section. In this situation the bold text and whatever follows are parsed as the contents of a `<p>` element.
- This PR adds an extra newline basically wherever `\*\*\n[^\n]` happens. This should enable the markdown to be parsed correctly.
- I don't know. Does readthedocs.io have a test branch? :smile:
- None--I'm not aware of any way the project has to test documentation changes.
- gh-1646
- This is only a documentation change.
> 1646 documentation not parsing markdown lists correctly

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
#1650 suggests adding global hirak/prestissimo package to make composer builds run faster. People seemed to be in favor. This adds it.
Just use `webimage: drud/ddev-webserver:20190618_prestissimo` in your .ddev/config.yaml and do a composer build.
> Add hirak/prestissimo composer package to web container, fixes #1650

- .buildkite/sanetestbot.sh
- .buildkite/test.sh
- .buildkite/test_containers.sh
- .buildkite/testbot_maintenance.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/exec_test.go
- cmd/ddev/cmd/import_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/pause_test.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/sequelpro_test.go
- cmd/ddev/cmd/share.go
- cmd/ddev/cmd/share_test.go
- cmd/ddev/cmd/stop_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/globalconfig/global_config.go
- pkg/testcommon/testcommon.go
#375 requests ngrok for sharing a view of a project. 
Spawn ngrok with proper config to share config, using `ddev share`
* Install ngrok
* Create an account on ngrok.com
* Set up, https://dashboard.ngrok.com/get-started
* Start a project and `ddev share`
* Experiment with additional args other than --subdomain by adding them to `ngrok_args` in .ddev/config.yaml
* Consider a paid account to experiment with additional features (required for --subdomain)
* Experiment with `ddev share` with no account (Just comment out the token in ~/.ngrok2/ngrok.yml). It should work, but with a warning.
* TestShareCmd tests basic unauthenticated use of `ddev share`
OP #375 
The testbots have to have ngrok on them, they were updated by this PR. First time buildkite testbot maintenance via PR.
> Add ddev share command, fixes #375

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/php/5.6/apache2/php.ini
- containers/ddev-webserver/files/etc/php/5.6/cgi/php.ini
- containers/ddev-webserver/files/etc/php/5.6/cli/php.ini
- containers/ddev-webserver/files/etc/php/5.6/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.0/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.0/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.0/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.0/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.1/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.1/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.1/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.1/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.2/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.2/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.2/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.2/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.3/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.3/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.3/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.3/fpm/php.ini
- containers/ddev-webserver/scripts/start.sh
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
- pkg/version/version.go
People have long needed the timezone to be more easily managed in the container and PHP environment.
#1658 requests that the default timezone for PHP be UTC
#1417 requests configuration of the timezone in config.yaml
#709 requested that it automatically be derived from user TZ, but that's a little hard
* Add timezone option to config.yaml
* If TZ is set in container (as result of config.yaml) then update php.ini files with the named timezone
* Start without extra config. `ddev ssh` and `date` should show time in UTC, `php -r 'print  date_default_timezone_get();'` should show the UTC tz for php, as should `grep -r timezone /etc/php`
* Use `ddev config --timezone=America/Denver` to set timezone to Denver; `ddev ssh` to use `date` in the container; `date` should show time in UTC.  `php -r …
> Support timezone in container and PHP, fixes #1658, fixes #1417, #709

- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
Our webimage is quite large, and downloading a new one takes some time, especially on a slower internet connection.
#1656 points out that we could at least provide some feedback while that's happening. `docker-composer up` is not that good at doing this; `docker-compose pull` can be forced to. But rather than that, 
Implement dockerutil.Pull() to pull the image with feedback, and do that on Start (if the container doesn't exist) 
* Stop all projects, `ddev rm -a`
* Find out the current web image using `ddev version` and delete it, for example `docker rmi drud/ddev-webserver:20190622_timezone`
* ddev start
You should see a wonderful amount of feedback about the download
Nothing added
OP #1656
> Provide docker pull input on ddev start, fixes #1656

- cmd/ddev/cmd/share.go
I noticed in testing:
* There were 2 random ngrok exit instrumentations that the user doesn't care to see.
* The --subdomain flag wasn't working
Remove the exit instrumentation. Fix the --subdomain flag.
`ddev share --subdomain <something>` (with a paid ngrok account)
It should use the correct subdomain at ngrok.io
> Minor fixups for ddev share

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/share.go
- pkg/ddevapp/templates.go
Testing for v1.9.0 release [here](https://github.com/drud/ddev/issues/1595#issuecomment-505458860) found a couple of problems with `ddev share`:
* extra arguments on the command line were being passed into ngrok
* Flags from config.yaml `ngrok_args` were being put in the wrong place in the ngrok command line.
* Remove the handling of `args` from the command
* Allow a single argument of projectname to be specified; if specified, use it.
* Put the flags from ngrok_args *after* the http section
See [release testing](https://github.com/drud/ddev/issues/1595#issuecomment-505458860)
> Fix ddev share anomalies

- docs/developers/release-checklist.md
- pkg/version/version.go
v1.9.0 needs new container versions. Here they are.
> Bump container versions for v1.9.0 release

- docs/users/performance.md
- scripts/debian_ubuntu_linux_ddev_nfs_setup.sh
The "improved" Linux NFS setup script is very strict, and might not work out for real people in a DHCP environment.
And nfsmount_enabled is not particularly useful on Linux anyway.
See Testing for v1.9.0 release [here](https://github.com/drud/ddev/issues/1595#issuecomment-505458860) 
Add docs and info in the script to help Linux users to measure and respond to these issues.
> Improve linux setup script and docs [skip ci][ci skip]

- cmd/ddev/cmd/root.go
- pkg/globalconfig/global_config.go
A user upgrading from v1.5 to v1.9.0 had a nasty crash on every command. 
```
$ ddev config
You are reconfiguring the project at /Users/rfay/workspace/d8git.
The existing configuration will be updated and replaced.
Project name (d8git):
The docroot is the directory from which your site is served.
This is a relative path from your project root at /Users/rfay/workspace/d8git
You may leave this value blank if your site files are in the project root
Docroot Location (current directory):
Found a drupal8 codebase at /Users/rfay/workspace/d8git.
Project Type [php, drupal6, drupal7, drupal8, wordpress, typo3, backdrop] (drupal8):
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/drud/ddev/pkg/globalconfig.ReservePorts(0xc0001dd128, 0x5, 0x22bc008, 0x0, 0x0, 0xc0004b2000, …
```
> Fix crash encountered with old global_config.yaml

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
#1672 suggests that we enable a few common apache modules by default
Enable headers, expires
* configure a project for apache-fpm and `ddev start`
* `ddev ssh`
* `apachectl -M` shows modules enabled; expires and headers should be in that list now.
OP #1672
> Pre-enable common apache modules, fixes #1672

- pkg/ddevapp/config.go
- pkg/dockerutil/dockerutils.go
There are occasional cases where the docker0 interface is DOWN on Linux. I've seen this  a few times. It means we cannot detect the correct address for host.docker.internal, and thus it doesn't get into docker-compose.yaml extra_hosts, and then xdebug can't work and nfsmount_enabled can't work.
Report this situation and suggest options.
On linux, `sudo ip link set docker0 down` and then `ddev start`. Hopefully you'll see the error.  The problem happens when `ip address show dev docker0` doesn't display an IP address.
No idea how this would be testable.
> Improve handling of linux case where docker0 is down

- containers/ddev-dbserver/10.1/Dockerfile
- containers/ddev-dbserver/10.1/files/docker-entrypoint.sh
- containers/ddev-dbserver/10.1/files/healthcheck.sh
- containers/ddev-dbserver/10.2/Dockerfile
- containers/ddev-dbserver/10.2/files/docker-entrypoint.sh
- containers/ddev-dbserver/10.2/files/healthcheck.sh
- containers/ddev-router/Dockerfile
- containers/ddev-router/docker-entrypoint.sh
- containers/ddev-router/healthcheck.sh
- containers/ddev-ssh-agent/Dockerfile
- containers/ddev-ssh-agent/files/entry.sh
- containers/ddev-ssh-agent/files/healthcheck.sh
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/scripts/healthcheck.sh
- containers/ddev-webserver/scripts/start.sh
- pkg/ddevapp/templates.go
- pkg/dockerutil/dockerutils_test.go
- pkg/version/version.go
#1663 complains about the constant running of the ddev-ssh-agent healthcheck, which uses CPU and battery. But really most of the containers have this problem, and with the other ones it multiplies.
Docker provides us only the "interval" configuration for healthcheck, which is *both* the time to wait before the first healthcheck *and* how often to run it after that. 
In ddev, we mostly care about when it *first* becomes ready and usable, and it doesn't often need to be checked after that, but we were always stymied by Docker's design mistake here.
This is admittedly a hacky approach, but
* Use a 1 second interval. Docker will wait only 1 second before trying it the first time, and will try thereafter every 1 second.
* Use a long 120s timeout, meaning docker will wait that long for a …
> Quiet down healthchecks to save battery and CPU usage, fixes #1663

- cmd/ddev/cmd/ssh.go
#1681 notes that `ddev ssh` will display an error on exit if the last shell command returned an error. 
Stop reporting the results of ExecWithTty() when using it in the ssh command.
`ddev ssh`, cause an error with `ls /tmp/junk`, then "exit" or <ctrl-d>
You should not see an error.
No testing changes
OP #1681
Note that this removes all error checking on the ExecWithTty() command.
> Stop reporting last status from ddev ssh, fixes #1681

- pkg/ddevapp/router.go
- pkg/ddevapp/templates.go
ddev-router was binding its ports on all network interfaces, see #1662. This allowed everybody on the local network to access http, https, and most importantly phpMyAdmin without any controls at all. 
Bind the web and phpMyAdmin (and mailHog) ports only on the docker IP.
* Start a project
* Attempt to access from another computer or direct to non-docker ip. 
For example, if your laptop's main IP address is `192.168.1.140` then `curl http://192.168.1.140:80` should not connect (assumes ddev is listening on 80)
* No new tests
OP #1662
https://github.com/drud/ddev/pull/1502 fixed this for an earlier set of ports, based on #1491 
* Announce in release notes
* Note that the local ephemeral binding mailhog (to 127.0.0.1) goes away here, it didn't seem to be necessary.
> Bind router functions only on docker interface (usually localhost), fixes #1662

- cmd/ddev/cmd/exec_test.go
- pkg/ddevapp/ddevapp.go
Fixes #1690
Related to https://github.com/mattn/go-isatty/issues/38
> [FIX] Use Stdin for tty detection, fixes #1690

- pkg/ddevapp/typo3.go
In order to configure system to process images. Otherwise possible
existing project configuration within LocalConfiguration.php might
prevent processing, due to configured GraphicsMagick or different paths.
Resolves: #1710 
I've didn't find instructions how to execute existing tests, therefore none were executed or adjusted or added.
#1710
> Add TYPO3 GFX configuration for ImageMagick6

- pkg/dockerutil/testdata/TestComposeWithStreams/test-compose-with-streams.yaml
- pkg/dockerutil/testdata/docker-compose.yml
Some dockerutil tests occasionally give odd results, perhaps because the docker-compose.yaml used doesn't provide proper healthcheck intervals that match current containers.
Update to what we use in the regular docker-compose.yaml
> Use testdata with longer timeouts on dockerutil tests (tests only)

- pkg/ddevapp/instrumentation.go
- pkg/globalconfig/global_config.go
There will be times like developer work where we might as well have an identifiable user in segment. This adds an optional global_config.yaml item `instrumentation_user`
> Add optional real username for instrumentation

- docs/users/extend/config_yaml.md
- mkdocs.yml
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/templates.go
* #1691 points out that config.yaml timezone didn't get documented anywhere
* In lots of cases we don't have anything in the official documentation about configuration options.
* Windows can't validate the timezone, but it was making a really annoying statement to this effect every time any ddev command was launched
* Add docs to config.yaml (update with `ddev config`)
* Add docs to ddev.readthedocs.io
* Turn off the complaint about validation on Windows. Invalid timezones are ignored (and UTC is used) by both Linux and PHP.
Read the docs. 
No changes
> Timezone docs in config.yaml and add config docs to documentation, fixes #1691

- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
* @cyberswat pointed out the other day that `ddev restart` should take project args (and -a). Just a matter of consistency.
* Also `ddev ssh` has always needed a project arg, so you can run it even if you're not in the directory.
Add the args
* `ddev restart -a`
* `ddev restart <project1> <project2>
* ddev ssh 
* ddev ssh <project>
I didn't add any tests.
> Add target app arguments to ddev restart and ddev ssh

- Makefile
We've had an enormous instability trying to download nssm's zip from nssm.cc in recent weeks, so forked nssm into drud/nssm and put the executable there.
> Use ddev fork of nssm to download exe file

- pkg/ddevapp/instrumentation.go
#1684 put us on notice that if things go wrong with sentry or segment, there's no reason to expose that to the customer.
For a limited set of things, use output.Userout.Debugf() instead of anything else (like util.Warning()). That at least limits the possibilities, and those things will only be shown if DRUD_DEBUG=true
> Only output segment/sentry info when DRUD_DEBUG=true, fixes #1684

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/restart_test.go
- cmd/ddev/cmd/start.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
#1711 requested easy access to the http URLs
#1685 requested URLs that could be clickable without possible dangling commas
* `ddev start` and `ddev restart` now output space-separated list of URLs on start
* `ddev describe` provides a table of *all* URLS, including both http and https, even if mkcert is in action.
* Improved verbiage around mysql access in ddev describe
```
ddev start d8git
Starting d8git...
...
Successfully started d8git
Project can be reached at https://a.ddev.site https://d8git.ddev.site https://127.0.0.1:32773
```
```
ddev describe d8git
NAME   TYPE     LOCATION           URL                      STATUS 
d8git  drupal8  ~/workspace/d8git  https://d8git.ddev.site  running
Project Information
-------------------
PHP version:   	7.2 
MariaDB version	10.2
URLs
---- …
```
> Improve URL presentation in start/restart/describe, fixes #1711, fixes #1685

- cmd/ddev/cmd/root.go
- pkg/ddevapp/instrumentation.go
Now that Segment is integrated for instrumentation, the "Usage:" reports to Sentry are obsolete. Remove those. Leave the error pushes in there.
Removes the Usage: push to Sentry.
> Remove Sentry 'Usage' sends

- cmd/ddev/cmd/ssh.go
It would be more natural for ddev to use a login shell on `ddev ssh`, so use `bash -l` instead of just `bash` for `ddev ssh`.
Add "-l" to the command invocation.
> Make ddev ssh use a bash login shell

- cmd/ddev/cmd/poweroff.go
- cmd/ddev/cmd/stop.go
People just want to shut it all off. They don't want to remember `ddev stop -a --stop-ssh-agent`
Lando pioneered "poweroff" and people resonate to it.
Add poweroff which is the same as `ddev stop -a --stop-ssh-agent`
> Add ddev poweroff command, fixes #1588

- pkg/ddevapp/typo3.go
On first install, $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default'] could be still unset.
This sets this value to an empty value (not using null coalesce, thus PHP5-compatible) in that case.
> TYPO3 AdditionalConfiguration.php: fix warning in array_merge()

- docs/users/cli-usage.md
TYPO3 installation doesn't work with https URL; sometimes it's a silent 500 err with 
```
2019/07/25 18:01:55 [error] 2071#2071: *453 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The current host header value does not match the configured trusted hosts pattern! Check the pattern defined in $GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] and adapt it, if you want to allow the current host header 't3v9composer.ddev.site' for your installation. in /var/www/html/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php:2830
Stack trace:
#0 /var/www/html/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php(2882): TYPO3\CMS\Core\Utility\GeneralUtility::getIndpEnv('HTTP_HOST')
#1 …
```
> Update typo3 quickstart with warning about https url [skip ci][ci skip]

- pkg/ddevapp/backdrop.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
#1740 requests that .ddev/config.yaml not lose EOL at end of file.
Try to fix it everywhere.
> Make sure EOL at end of file is there in config.yaml, fixes #1740

- pkg/ddevapp/typo3.go
This sets trustedHostsPattern to all configured hosts + "localhost" and "127.0.0.1".
Please excuse my zero Go skills and correct me where needed.
> Get rid of TYPO3 trustedHostsPattern warning, fixes #1739

- cmd/ddev/cmd/delete-images.go
- cmd/ddev/cmd/delete.go
- cmd/ddev/cmd/poweroff.go
#1464 requests instructional copy about cleaning up orphaned containers. Mostly this is solved with `ddev poweroff`.
#1465 requests a way to clean up project data; the OP had not been familiar with `ddev stop --remove-data` 
#1562 requests a ddev delete command that can clean up unused docker images
* Add `ddev delete [project...]`
* Add subcommand `ddev delete images`
Make backups before you use `ddev delete project --omit-snapshot`
* `ddev delete project1 project2`
* `ddev delete --all`
* `ddev delete images`
* `ddev delete project1 --omit-snapshot`
> Add ddev delete command to kill projects and images, fixes #1465, fixes #1562, fixes #1464

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/stop.go
- pkg/ddevapp/ddevapp.go
#1716 points out that custom command handling when the project is not running is really ugly; it tries to take action, but finds no container to execute in.
* For both host and container commands, if the project is not running, start it.
* `ddev mysql` with project stopped.
* Enable the host-side `phpstorm` command by `cd .ddev/commands/host && ln -s phpstorm.example phpstorm` and `ddev phpstorm`. It should start the project first. mysqlworkbench is more fun with this, because it actually wants the mysqlserver running, but it runs on the host.
* No changes, it seems this is really just finesse.
> Take correct action on custom commands if project not running, fixes #1716

- .circleci/macos_circle_vm_setup.sh
Docker Desktop 2.1.0.0 (19.03.1) doesn't let you install as root
This breaks our macOS installation on CircleCI.
This uses 18.09 docker instead on CircleCI. Pretty sad.
This PR reverts back to earlier docker desktop for use on CircleCI. 
Docker issues: 
* https://github.com/docker/for-mac/issues/2359
* https://github.com/docker/for-mac/issues/882
> Docker Desktop 2.1.0.0 (19.03.1) doesn't let you install as root

- .circleci/trigger_release.sh
#1750 shows that macos signing didn't work in the last two prereleases. The script did not have the correct option, so either a rebase failure happened somewhere or something. This adds the option, and removes a redundant version of the windows signing password.
> Fix release trigger script, fixes #1750

- .circleci/generate_artifacts.sh
The current artifacts script, running on macOS, can't generate the image tarballs for release. It's also broken wrt bash completion generation. See #1749 
Use the OS to determine where to run ddev from
* Make sure valid image tarballs get generated when a release is created
* Make sure valid bash completion is included where it should be.
> Fix artifacts script to use correct path to execute ddev, fixes #1749

- Makefile
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/testdata/TestHostDBPort/showport
OP #1747: host_db_port was no longer working.
* Make sure that DDEV_HOST_DB_PORT is always set properly for docker-compose.yaml
* Make sure it's set for custom commands.
* Make sure the default ephemeral port also works.
* Try with `host_db_port: <something>` and without
* `ddev start` and `ddev describe` should show you what you expect on the port
* Make sure that `ddev mysqlworkbench` works for each (requires having that going)
* Adds TestHostDBPort, which is a fairly robust exploration of this.
> Make sure that DDEV_HOST_DB_PORT is properly set where needed, fixes #1747

- Makefile
The Makefile had a change earlier to support long versions that doesn't work with a simple version (no -), like v1.10.0.
This fixes that one line in the makefile.
> Fix Makefile problem with no_v_version [skip ci]

- pkg/ddevapp/config.go
Issue #1762 
.sshimageBuild and .bgsyncimageBuild are not ignored by default after performing a `ddev config`
Adjusts the `pkg/ddevapp/config.go` file to ignore the directories
`ddev config` should add `.sshimagebuild` and `.bgsyncimagebuild` to the `.ddev/.gitignore` file
Tests were not added due to the simplicity of the change.
Issue: #1762 
A new `ddev config` run should add the `.`s to the filenames in the `.gitignore` file in `.ddev` if the file is marked to be auto generated/altered.
> Ignore .sshimageBuild and .bgsyncimageBuild directories by default, fixes #1762

- pkg/ddevapp/config.go
.example and README.txt files are recreated by ddev on `ddev start` and do not need to be versioned.
The same is true for commands/db/mysql actually, but as that actually is a custom command, I tend to leave it.
> add 1.10 example files to .gitignore

- pkg/ddevapp/config.go
The default shell is not currently being set when a user is created. This doesn't seem to have any practical problems, but it might as well be right.
This PR adds /bin/bash as the shell when creating the user.
> Useradd should set bash shell for user

- containers/ddev-ssh-agent/files/etc/group
- containers/ddev-ssh-agent/files/etc/passwd
- pkg/version/version.go
A user with the username "mail" reported trouble starting the ssh-agent; it turns out the ddev-ssh-agent already had that as a group name, which it doesn't need.
````
PS C:\Users\mail\ddev\test> ddev start                                                                                  Starting test...
Building ddev-ssh-agent
Service 'ddev-ssh-agent' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m --gid "$username" --comment '' "$username")' returned a non-zero code: 9
Failed to start test: failed to start ddev-ssh-agent: Failed to run docker-compose [-f C:\Users\mail/.ddev/ssh-auth-compose.yaml -p ddev-ssh-agent up --build --force-recreate …
```
> Pre-seed passwd and group files for ddev-ssh-agent

- containers/ddev-webserver/files/etc/profile
- containers/ddev-webserver/files/etc/skel/.bashrc
- containers/ddev-webserver/files/etc/skel/.profile
- containers/ddev-webserver/files/usr/local/bin/disable_xdebug
- containers/ddev-webserver/files/usr/local/bin/enable_xdebug
- pkg/version/version.go
#1772 points out that `enable_xdebug` and `disable_xdebug` don't work in container context (if you `ddev ssh` and then run them. They do run with `ddev exec enable_xdebug`
There's a switch in the default .profile that doesn't include /usr/sbin for an ordinary user. 
Remove that switch from the default .profile and always put /usr/sbin in the path.
I also changed the scripts so that they explicitly add /usr/sbin just in case.
`ddev ssh` and run `enable_xdebug` and `disable_xdebug`. They should work
`ddev ssh` and `echo $PATH`, it should include /usr/sbin
> Make sure /usr/sbin and friends are in PATH, fixes #1772

- pkg/version/version.go
Preparing for a v1.10.2 release; two images have changed version.
> Bump ddev-webserver and ddev-ssh-agent to v1.10.2

- .circleci/config.yml
- .circleci/macos_circle_vm_setup.sh
#1773 we discovered that the release-build (in macOS) didn't build a usable windows installer. 
Revert to an older version (prior to https://github.com/Homebrew/homebrew-core/pull/39928)
This uses the homebrew recipe as it was before that PR.
Build a release. Test it.
> Revert to older makensis for homebrew, fixes #1773

- pkg/ddevapp/config.go
@thomaskieslich pointed out in https://github.com/drud/ddev/issues/1715#issuecomment-519569449  that our implementation in the dockerfile build of *image_extra_packages should have `--no-install-recommends` to lighten the install load. 
Add the --no-install-recommends
Per the quoted issue, add cron and verify its operation.
> Use --no-install-recommends for apt-get install of *image_extra_packages

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/apache2/conf-available/php7.4-cgi.conf
- containers/ddev-webserver/files/etc/apache2/conf-available/php7.4-fpm.conf
- containers/ddev-webserver/files/etc/php/7.3/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.4/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.4/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.4/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.4/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.4/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.4/fpm/pool.d/www.conf
- containers/ddev-webserver/files/etc/php/7.4/mods-available/xdebug.ini
- containers/ddev-webserver/test/containertest.sh
- pkg/ddevapp/templates.go
- pkg/ddevapp/values.go
- pkg/version/version.go
PHP7.4 beta is out, and included in this build. `ddev config --php-version=7.4` will now work (and `php_version: 7.4` in config.yaml)
The container test now includes 7.4, this isn't a very serious test, but at least it tries. 
I think we should be testing more PHP versions in the regular ddevapp tests
It's important to note that as of right now, none of these extensions are ready for php7.4:
* apcu 
* memcached 
* redis 
* xdebug
We'll try to pay attention to when these become available and update as needed.
> PHP7.4 (beta) for ddev (missing apcu, memcached, redis, xdebug)

- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
Earlier we had added a pull of the web and db images during start (if they didn't exist), but I noticed that the first-time pull of the ddev-ssh-agent and dba and router images also caused a mysterious pause during upgrade. 
This PR just adds all the key images to the download.
> Pull all important images during start if needed, friendlier to users

- cmd/ddev/cmd/poweroff.go
I keep typing `ddev powerdown` instead of `ddev poweroff`
Add a `powerdown` alias for `poweroff`
Try `ddev powerdown` as well as `ddev poweroff`
> Add powerdown alias for poweroff, because I keep trying to use it

- pkg/ddevapp/typo3.go
with the implementation of the "ddev share" option accessing the page via *.ngrok.io
throws an exception and the trustedHostsPattern must be altered manually.
> Add ngrok.io domain to trustedHostsPattern in TYPO3 config

- docs/users/extend/custom-commands.md
A directory must have been changed at some point.
Also, file links in Github seems to have 'blob' instead of 'tree' in the path.
Fixes the name and URLs to make them work.
Do the links work?
None. Only change is to the documentation.
Maybe the example name is used somewhere else as well? I did not check.
> Fix example name and Github links for all examples

- .circleci/linux_circle_vm_setup.sh
mkcert v1.4.0, recently released, is broken on Ubuntu 16.04, see PR https://github.com/FiloSottile/mkcert/pull/193 and issue https://github.com/FiloSottile/mkcert/pull/192
We use Ubuntu 16.04 for our CircleCI linux builds. 
The PR https://github.com/FiloSottile/mkcert/pull/193 solves this. Until it or something related comes through, we'll have to dodge with a private build (from https://github.com/rfay/mkcert/releases/tag/v1.4.1-alpha1)
See if CircleCI builds
> Temporarily use a custom-built mkcert that works on Ubuntu 16.04 for CircleCI

- cmd/ddev/cmd/list.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mkcert.go
- pkg/dockerutil/dockerutils.go
- pkg/globalconfig/global_config.go
@ultimike pointed out in Slack that ddev start and ddev list seem to take longer than they used to. I took a little time to look and found that there were serious problems with two things:
* dockerutil.Pull() uses dockerutil.ImageExistsLocally(), for every important image, on every start. And ImageExistsLocally() was mighty slow.
* GetCAROOT() for mkcert was running `mkcert -CAROOT` at least once on every start and list, and that command is mightily slow, taking almost 2 seconds. 
* Improve and speed up ImageExistsLocally() quite radically. Much simpler now too.
* Store CAROOT in global config, so we don't have to run mkcert to find it out. 
`ddev start` with and without this
`ddev list` with and without this.
There are two other things I discovered studying this that are not covered by …
> Improve ddev start and ddev list performance

- docs/users/extend/custom-commands.md
It is typically recommended to use `#!/usr/bin/env bash` in shebang lines so that the correct version of Bash gets used. I'm updating the host example here. I've left the container examples alone because we have more knowledge of the container.
I think clarifying that these scripts ought to work with any programming language that can be executed from the command line (e.g. PHP) would also be good, but I'm not sure if I'm correct on that or if it's a useful addition.
> Make shebang lines more portable in host example.

- Makefile
The chocolatey build has a "no-v" view of version reality. We've tried to work around this again and again. But in https://github.com/drud/ddev/pull/1809 we just stopped building chocolatey on routine builds because it's so tweaky and has unknown version constraints. That solved the immediate problem.
However, the code that was in the makefile for the version transformation wasn't adequate and results in failures for tags like "v1.11.0-alpha1".
Stop doing anything but removing the initial v. That works for real releases of almost all types. WE CAN HOPE.
> Simplify NO_V_VERSION, should work with real tags

- .circleci/generate_artifacts.sh
* The Circleci build has been creating image tarballs for every single build. We only need them on release builds.
Change the default behavior
* Make sure that tarballs aren't built in normal circle build
* Do a dummy release to make sure that they *are* built on a release build (if specified by the script)
> Stop building image tarballs by default

- docs/users/troubleshooting.md
Within the docs on https://ddev.readthedocs.io/en/stable/users/troubleshooting/ an a-Tag is not closed properly which leads to wrong formatted texts.
This PR closes the a-Tag.
Simply open https://ddev.readthedocs.io/en/stable/users/troubleshooting/ and scroll to "Windows-Specific Issues"
Doc related only.
> [BUGFIX] Add closing tag on troubleshooting page

- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer_test.go
- pkg/ddevapp/composer.go
#1737 points out that `ddev composer create` doesn't allow passing very many flags to composer create-project, and it causes all kinds of trouble.
* Stop validating flags
* Pass everything directly to composer create-project
* Turn on tty if available, so authentication can happen
Try the operations in `ddev composer create -h`, which should cover all these things. The --no-install and --repository options are probably the most annoyances at this time.
* Added a --no-install example into the TestComposerCmd
OP #1737
> Make composer create accept any flags or args, and run interactively, fixes #1737

- Makefile
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/main.go
- pkg/globalconfig/values.go
- pkg/output/output_setup.go
- pkg/output/text_formatter.go
Sentry's initialization can actually call home, and it's not inside our code that prevents that.
* Move sentry initialization to where it's actually needed (which isn't much any more)
* Change the DDEV_NO_SENTRY environment variable (normally used only by developers) to DDEV_NO_INSTRUMENTATION
* With instrumentation turned off via DDEV_NO_INSTRUMENTATION create an error (like ddev start in uninitiialized directory). Verify that it doesn't come through on Sentry.
* With instrumentation turned off in global_config.yaml do the same thing. Should not come through on sentry.
* Do the converse of each of these and make sure the sentry error comes through.
* With instrumentation turned off, make sure that a ddev command like start doesn't come through on segment. Use the debug tab in segment to …
> Don't let sentry call home if not needed

- cmd/ddev/cmd/composer-create.go
- docs/users/cli-usage.md
- docs/users/developer-tools.md
`  [InvalidArgumentException]
Could not find package typo3/cms-base-distribution with version 9.`
> Escape composer versions in docs so they work in Windows cmd

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config-global_test.go
- docs/users/extend/config_yaml.md
- pkg/ddevapp/router.go
- pkg/ddevapp/templates.go
- pkg/globalconfig/global_config.go
OP #1798: In ddev v1.10, the feature/bug where ddev bound to all network interfaces was removed. Previously everyone on a local network could access ddev sites (and PHPMyAdmin). 
It was a surprise to find out that there were people relying on this feature/bug to share projects with others or to use ddev for CI/CD/Staging applications.
Allow a new global configuration option  in ~/.ddev/global_config.yaml: `router_bind_all_interfaces: true` that uses the original behavior. 
```
ddev poweroff
ddev config global --router-bind-all-interfaces=true
ddev start
```
* Inspect ~/.ddev/router_compose.yaml; you should see the port bindings without IP addresses specified.
* Access project from an IP address on the machine that is *not* localhost
* Adds testing only for the ddev config global option; …
> Allow users to bind router on all network interfaces, fixes #1798

- pkg/version/version.go
> Bump containers to tags to v1.11.0 for release

- docs/users/extend/config_yaml.md
There was a broken link on the config.yaml page to the extending commands section.
> Fix broken link to extending commands, docs only [skip ci][ci skip]

- .circleci/generate_artifacts.sh
For quicksprint, we need mkcert bundled into the tarballs. People will need it from time to time anyway.  This adds mkcert in those tarballs.
> Add mkcert to os-specific packages

- cmd/ddev/cmd/stop.go
@gilbertsoft pointed out that `ddev stop` self-docs could be improved, especially saying that `ddev stop --remove-data` removes the listing in global config.
Add a little doc.
> Improve ddev stop docs

- cmd/ddev/cmd/import-db.go
#1690 (ddev import-db accepting stdin) was long ago resolved, but the ability to accept stdin was never added to the `ddev import-db` help. 
Adds it to help.
> Add examples and improve help to show stdin usage with ddev import-db, fixes #1690

- .buildkite/nfstest.sh
- cmd/ddev/cmd/debug-nfsmount.go
- cmd/ddev/cmd/debug-nfsmount_test.go
- docs/developers/buildkite-testmachine-setup.md
- docs/users/performance.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils_test.go
- scripts/macos_ddev_nfs_setup.sh
OP #1869 points out that nfs_mount_enabled is broken in macOS Catalina. 
On fresh Catalina (and other macOS, but should be covered by automated testing)
* Read/review the [new docs](https://github.com/drud/ddev/blob/2c3fcb59d32d3c57b6a589cab00b5c4245147d93/docs/users/performance.md) about how to upgrade and debugging technique.
* On Catalina or pre-Catalina, run the [nfs setup script](https://raw.githubusercontent.com/drud/ddev/2c3fcb59d32d3c57b6a589cab00b5c4245147d93/scripts/macos_ddev_nfs_setup.sh)
* Use `showmount -e` to verify that the directory is now being shared.
* In a project directory, use `ddev debug nfsmount` to verify that it's successful and shows the mounted volume.
* In a project directory with `nfs_mount_enabled: true` do a `ddev start` and visit the site to make sure …
> Change nfs mounting for macOS Catalina, fixes #1869

- .circleci/linux_circle_vm_setup.sh
In https://github.com/drud/ddev/pull/1880 @gilbertsoft noted that the Circleci/Linux makensis we're using is really old. It seems we were getting it from apt-get (and those testbots are Ubuntu 16.04, a few years old). 
* Use homebrew to build makensis
* Unzip the standard 3.04 nsis tarball into /usr/local/share/nsis so that we get Stubs
> Use nsis from linuxbrew (3.04) instead of from apt-get (ancient)

- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
There are some trailing extraneous spaces in 
This PR removes the trailing extraneous spaces from the files.
> Remove trailing extraneous spaces

- containers/ddev-router/docker-entrypoint.sh
- pkg/version/version.go
There was one cert in the router that did not have "*.ddev.site". It really only showed up on https://127.0.0.1, so probably didn't matter.
Add "*.ddev.site" to that one situation.
> More robust initial cert for ddev-router

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Add sqlite3 to base webserver image.
With the addition of build tests to drupal core, it would be nice to be able to run build tests that leverage sqlite and drush without needing to remember that sqlite3 isn't installed by default.
See https://www.drupal.org/project/drupal/issues/3082230
It installs the package.
Adds sqlite CLI for being able to test things leveraging sqlite inside of the docker instance.
> Add sqlite3 to web container

- cmd/ddev/cmd/config.go
- pkg/ddevapp/composer.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/task.go
#1818 points out that there are cases where an exec task fails and no output is provided
#1765 requests clearer feedback about the problem when an exec task fails, instead of giving a bunch of docker-compose gobbledygook.
* Show output of hook task whether or not it fails (#1818)
* Don't show a bunch of docker-compose nonsense
* Add a warning explaining that this is configuration that failed (#1765)
* A failed task does not fail the entire operation.
Try this in your config.yaml:
```
hooks:
pre-start:
- exec-host:  ls junker100
post-start:
- exec: ls junker99
```
and do a `ddev start`
* The pre-start hook should fail with appropriate information
* The post-start `ls junker99` should fail with appropriate information
No new testing is added here.
#1818 
#1765
Add to release notes:
* …
> Improve exec hook output/behavior, fixes #1818, fixes #1765

- pkg/ddevapp/typo3.go
Several recent PRs have tried to catch up with TYPO3 v1.10's rejection of ".*" as trustedHostsPattern, and it's gotten super complex.
Since TYPO3 only checks and complains about the literal `.*` we might as well fool it by using `.*.*`. It's for development after all!
Install TYPO3 v10 using composer, then do an install
* Test with various hostnames/fqdns
* Test with ngrok/ddev share
> Use much simpler TYPO3 trustedHostsPattern

- pkg/servicetest/testdata/services/docker-compose.beanstalkd.yaml
- pkg/servicetest/testdata/services/docker-compose.memcached.yaml
- pkg/servicetest/testdata/services/docker-compose.solr.yaml
There seems to be a docker bug or (misunderstanding?) about the correct use of a service lookup, as reported by @yanniboi in https://twitter.com/yanni_boi/status/1186941678885703682
If you do *not* add a "links:" stanza to the web service, then it may find "solr" at the wrong project. This was discovered about the "db" container in https://github.com/drud/ddev/issues/813 and so we used "links:" to make sure it was explicit. 
So currently, as was described by @yanniboi , if you have two projects with a solr container, and you `ddev ssh` into each, then `ping solr` you may get random results, sometimes referring to one project's solr container, sometimes referring to the other. 
Add explicit "links:" to the 3rd-party service definitions to prevent this.
Start two projects that have solr …
> Make solr/memcached name lookup refer exclusively to the right container

- containers/ddev-webserver/scripts/start.sh
- pkg/version/version.go
#1848 points out that in some cases if `mkcert -install` has not been run on the host, the web container might fail to run `mkcert -install` on startup due to permissions issues. 
Make sure the $CAROOT directory has been created and is at least readable
> Make sure CAROOT exists, fixes #1848

- docs/users/extend/additional-services.md
- docs/users/extend/custom-compose-files.md
- docs/users/extend/customization-extendibility.md
As discussed on Slack, people don't always know to look at ddev-contrib for support of relatively common, but not built-in, services.
This PR updates three pages to add references to ddev-contrib recipes for things like Blackfire, MongoDB, and older versions of PHP.  It also links to ddev-contrib from the "defining additional services" page so people can use them as examples.
> Added links to ddev-contrib for some extra services and old PHP

- .readthedocs.yml
- mkdocs.yml
readthedocs didn't like a couple of changes in a509531a82bb7cadde34595739d8bc5cd2ecc979 and the build failed; it uses an incomprehensibly old version of mkdocs.
Remove the offending changes
> Minor docs changes to pacify readthedocs

- pkg/ddevapp/config_test.go
There was a sensitive use of IST in  TestTimezoneConfig that didn't work when daylight time ended (timezone reported GMT). This just changes to use Europe/Paris and CET for the tested timezone.
> Minor fix to TestTimezoneConfig, tests only

- pkg/ddevapp/typo3.go
This will make it easier for developers to add keys or new sections to
the TYPO3_CONF_VARS. Also it won't run into problems when keys are not
set by the DefaultConfiguration.php
> [TASK] Combine all TYPO3_CONF_VARS into one recursively merged array

- cmd/ddev/cmd/export-db.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/snapshot.go
`ddev import-db`, export-db, and snapshot were missing from autocomplete, and were not in the instructions of ddev help.
Put them back in,.
> Fix missing commands (import-db, export-db) when outside project, fixes #1872

- cmd/ddev/cmd/export-db.go
`ddev export-db ` was willing to start the project for people... But the output of starting the project came out in the file, making it invalid. #1892 
Don't allow export-db when project isn't started
> Don't allow export-db if project not started, fixes #1892

- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
The [nightly build is broken](https://circleci.com/gh/drud/ddev/19578?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link). The problem shows up in TestDdevFullSiteSetup with "ERROR 1273 (HY000) at line 25: Unknown collation: 'utf8mb4_unicode_520_ci". This is a result of one of the other tests (I think TestDdevAllDatabases) leaving the Wordpress site in a state with mariadb_version or mysql_version with an old version.
Defer a cleanup of the mariadb_version and mysql_version.
> Fix nightly build - config.yaml left with unusable mariadb version, tests only

- pkg/ddevapp/wordpress.go
Every time I run `ddev config`, DDEV overrides the `wp-config-ddev.php` for the `WP_HOME` constant, and uses HTTP protocol for that URL.
However DDEV already defaults to secure URLs, this setting should match that too. 
Changes `DeployURL` to use a secure URL, so that `WP_HOME` can inherit that too.
> WordPress: Use the secure URL for `WP_HOME`

- docs/users/performance.md
It turns out you have to explicitly allow /sbin/nfsd "Full Disk Access" on macOS Catalina if you want to work inside ~/Documents.
https://twitter.com/randyfay/status/1194303593559425024
> [docs only] Catalina ~/Documents problem [skip ci][ci skip]

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
In #1805 we had to go to a custom-made mkcert because v1.4 did not work right on Ubuntu 16.04 (which is what runs our CircleCI tests)
This reverts commit 95ab5532f1d35246a6d1433cfb7bf46135012a65.
Note that mkcert v1.4.1 has been released, which works OK with Ubuntu 16.04
This should be OK if CircleCI tests pass.
> Revert "Temporarily use a custom-built mkcert that works on Ubuntu 16.04"

- winpkg/chocolatey/ddev.nuspec
We've been telling people complicated things to install ngrok. We *bundle* nssm and mkcert in the installer, but they should probably also be dependencies.  
Note that #1925 also proposes to add ngrok to the installer, which is appropriate.
Make those 3 things dependencies for ngrok.
This will have to be tested with a real pre-release in choco.
#1925 proposes to bundle ngrok with the installer, which I still think is fine. 
I'm concerned about the lack of version requirements. My assumption is that chocolatey upgrades to current when you upgrade ddev.
> Ngrok, nssm, mkcert should be a dependency of ddev, why not?

- winpkg/chocolatey/tools/chocolateyinstall.ps1
- winpkg/ddev.nsi
Installing DDEV with Chocolaty should prefer the tools installed as dependencies instead of the ones bundled with the DDEV Windows installer
Skips mkcert and nssm from installation in the new choco mode /S /C
Run the installer with options /S /C and check the tools are not installed. If they are already present they will be kept and prefered by DDEV
#1935
> Skip tools installation in chocolatey mode (Windows installer)

- cmd/ddev/cmd/ssh.go
- docs/users/extend/additional-services.md
- pkg/servicetest/testdata/services/docker-compose.solr.yaml
There's always been a lot of magic involved with our docker-compose.solr.yaml and instructions. This PR attempts to improve the docs and the docker-compose.solr.yaml so people can understand what's important and how to change it.
* Much addition to [docker-compose.solr.yaml](https://github.com/drud/ddev/blob/e1c0ad3cd17371acc1e671791c0d40f9771f295d/pkg/servicetest/testdata/services/docker-compose.solr.yaml)
* Much addition to the [solr docs](https://github.com/drud/ddev/blob/e1c0ad3cd17371acc1e671791c0d40f9771f295d/docs/users/extend/additional-services.md)
* Defaults to bash shell when using `ddev ssh -s solr`
* Work through it all from scratch.
> SOLR: Improve docs and docker-compose.solr.yaml

- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/wordpress.go
#1736 (ddev pull fails on Wordpress site) is just one description of the problem here. It seems to affect almost all current WordPress-type sites. 
```
An existing user-managed wp-config.php file has been detected!
Project ddev settings have been written to:
/Users/rfay/workspace/ddevwptest/wp-config-ddev.php
Please comment out any database connection settings in your wp-config.php and
add the following snippet to your wp-config.php, near the bottom of the file
and before the include of wp-settings.php:
// Include for ddev-managed settings in wp-config-ddev.php.
$ddev_settings = dirname(__FILE__) . '/wp-config-ddev.php';
if (is_readable($ddev_settings) && !defined('DB_USER')) {
require_once($ddev_settings);
```
There are a number of open issues for WordPress, and this problem is at the …
> WordPress: Fix bug with complaints about config.php not set up, fixes #1736, fixes #1928

- containers/ddev-webserver/files/usr/local/bin/wp
- docs/users/developer-tools.md
- pkg/version/version.go
The command `wp` (`wp-cli`) does not work properly if the `$WP_CORE` environment variable was not set, because the bash script at `/usr/local/bin/wp` appends an empty path option "`--path=`".
You might wonder why the `$WP_CORE` environment variable is not set.
This is a special use case where I am using the default `php` type along with [bedrock](https://roots.io/bedrock/). DDEV's [WordPress setup](https://ddev.readthedocs.io/en/latest/users/cli-usage/#wordpress-quickstart) is not compatible with [bedrock](https://roots.io/bedrock/).
In this case the `$WP_CORE` environment variable is not set automatically. However I still need to run `wp` (bedrock ships a [`.wp-cli.yml` config file](`$WP_CORE` environment variable).
Manually provide the `$WP_CORE` environment variable (see …
> WordPress: Fix wp-cli not working if $WP_CORE is provided

- pkg/ddevapp/config.go
#1947 points out that in certain situations (major config file changes in upstream Debian packages) the `webimage_extra_packages` (or any apt-get install noninteractive) may fail. 
Per https://serverfault.com/a/279446/79810 a DEBIAN_NONINTERACTIVE can be more likely to succeed with `-o Dpkg::Options::="--force-confnew"`
* Set `webimage: drud/ddev-webserver:v1.11.0` to recreate the starting point of #1947
* `webimage_extra_packages: [php-yaml, php7.3-ldap]`
* `ddev restart`
OP #1947
> Make package noninteractive install more likely to succeed, fixes #1947

- docs/users/cli-usage.md
@lopezs points out in https://github.com/drud/ddev/pull/1918#issuecomment-554344217 that the WordPress bedrock instructions need to mention WP_HOME. This docs-only PR does that.
> Add WP_HOME to bedrock instructions [skip ci][ci skip]

- cmd/ddev/cmd/commands.go
- pkg/ddevapp/task.go
- pkg/util/utils.go
#1946 points out that the exec-host task is not interpreted in the context of a shell, which people would expect (and the exec task - in a container - is interpreted in bash context). 
Use "bash -c" to interpret the item
Add a pre-start hook like:
```
hooks:
pre-start:
- exec-host: echo $HOME
```
and then `ddev start`. You should see the interpreted $HOME, not '$HOME'
Also test this on Windows. Requires git-bash.
OP #1946
> Interpret exec-host in bash context, fixes #1946

- winpkg/ddev.nsi
Message boxes are shown during the uninstall.
This patch changes the behavior of the uninstaller to not to show message boxes during the process. The only exception is the message if the install directory could not be removed.
Run the uninstaller with the parameter /S or with chocolatey uninstall
> Change silent uninstaller to not showing messages

- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
xdebug 2.8 (works with php7.4) is now part of deb.sury.org, distribution, try to get it working.
> Use php-xdebug that should work with php7.4 xdebug

- cmd/ddev/cmd/config_pantheon.go
- pkg/ddevapp/pantheon_test.go
- pkg/ddevapp/providerPantheon.go
An app.Init() is done for most operations.. but if it's a pantheon provider, that means it was phoning home to verify the name of the project. Shouldn't do that. #1905.
Stop validating on app.Init()
> Pantheon should not authenticate when just initing app, fixes #1905

- .circleci/config.yml
- .vscode/launch.json
- .vscode/settings.json
- docs/developers/building-contributing.md
- pkg/ddevapp/config_test.go
- pkg/ddevapp/container_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/dockerutil/dockerutils.go
- pkg/globalconfig/values.go
- pkg/output/output_setup.go
- pkg/testcommon/testcommon.go
- pkg/util/utils.go
- pkg/version/version.go
- testing/ddev-perf-test.sh
#1881: MacOS Catalina really slow execution.
This is mostly due to docker-compose problems as described in https://github.com/docker/compose/issues/6956#issuecomment-555623639 and potentially fixed by https://github.com/docker/compose/pull/7010
* Adds more debugging capability than anything else.
* On macOS temporarily skip the docker-compose version check
`ddev list` on macOS should return in a couple of seconds or less. 
#1905 (fixed by #1916) was also a problem here, not just for Catalina, but for everybody that had a Pantheon project active.
> Diagnose/improve execution speed on macOS Catalina, for #1881

- pkg/version/version.go
Time for v1.12.0, bump container versions.
> Bump containers to v1.12.0 in preparation for release

- .circleci/config.yml
- .circleci/macos_circle_vm_setup.sh
It seems CircleCI has changed the macOS image and we can't write
/etc/exports any more. It's not worth chasing this at this moment
because we don't use NFS on macOS currently.
Commenting out the NFS setup.
> [Tests only] Remove macOS nfsd setup as not working on CircleCI

- .circleci/config.yml
This reverts commit 5023ee9384cbe9456ad51ca89c19c36efedce0d7.
CircleCI has fixed their regression and claim that this will work now.
> Revert "[Tests only] Temporarily Use macOS High Sierra for CircleCI testing (#1973)

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
PHP 7.4.0 has been released, and missing modules like redis, memcached, and apcu have been added to the deb.sury.org repo. It's nice to get all those slipped in before v1.12.0 release.
Remove the special handling that removed those (missing) modules from PHP7.4, bump container version to v1.12.1
> Bump web version to v1.12.1 to get latest PHP7.4

- docs/users/extending-commands.md
The issue is that the documentation suggests that it's the best practice to reinstall the site at every `ddev start`, but it's not so efficient, basically it loses all the benefits of database persistence. After stopping a container, using the example, you cannot continue using your existing site.
It makes the installation step conditional.
Apply the config, start it, stop it, start it, let's make sure that the 2nd start is much faster, as no installation is involved, but the site is still usable.
Not applicable, only documentation.
Not applicable, only documentation.
> Better example on drupal7/8 config

- .markdownlintrc
@gilbertsoft pointed out github.com/DavidAnson/markdownlint and https://github.com/igorshubovych/markdownlint-cli - these can be used to specify consistent markdown in our docs. Since readthedocs/mkdocs is particularly susceptible to markdown style, this will be great for fixing up our markdown in the docs.
Markdown will either be updated later bit by bit or with a mass update like https://github.com/drud/ddev/pull/1980, or perhaps that one will be updated to meet the requirements of this markdownlintrc
> Add .markdownlintrc defining markdown, especially for readthedocs

- pkg/ddevapp/drupal.go
The setting for file_scan_ignore_directories is Drupal default settings.php. There is no need to override it in ddev.
> Remove file_scan_ignore_directories

- cmd/ddev/cmd/composer_test.go
- containers/ddev-ssh-agent/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/composer_test.go
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
Debian buster is now the mainline distribution, use it instead of stretch in both ddev-webserver and ddev-ssh-agent
> Debian buster is now the mainline distribution, use it instead of stretch, fixes #2009

- cmd/ddev/cmd/config.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/php/7.4/fpm/php-fpm.conf
- containers/ddev-webserver/test/containertest.sh
- docs/users/extend/config_yaml.md
- docs/users/extend/customization-extendibility.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/templates.go
- pkg/nodeps/values.go
- pkg/version/version.go
PHP7.2 active support ends on Nov 30, 2019 (in 3 days). Time to set PHP7.3 as default version
Use PHP7.3 as default both in container and in ddev and docs.
* Configure a junk site
* Start it up
* php --version should show 7.3
> Use PHP7.3 as default PHP version

- containers/ddev-dbserver/files/etc/my.cnf
- containers/ddev-webserver/files/home/.my.cnf
- pkg/version/version.go
mysql import-db and mysql are affected by client config which lacks utf8mb4 (defaults to latin1). 
Add client config to set connection to utf8mb4
Example is coming from @RobertLang, who ran into trouble with imported dbs because of this.
We need to add a test to the mysql container to make sure that everything works properly, should be easy enough.
> Add utf8mb4 client collation to my.cnf in containers

- .buildkite/testbot_maintenance.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
We noted a test failure in https://buildkite.com/drud/ddev-windows-dockerforwindows/builds/3055#5bd947d3-05be-40e9-83ca-bf2e581dadff where the unzip of the Windows EnvVar plugin hung forever because there was already something in that directory:
```
+ curl -fsSL -o /tmp/EnVar-Plugin.zip https://github.com/GsNSIS/EnVar/releases/latest/download/EnVar-Plugin.zip
+ sudo unzip -d /usr/local/share/nsis /tmp/EnVar-Plugin.zip
Archive:  /tmp/EnVar-Plugin.zip
replace /usr/local/share/nsis/Contrib/EnVar/EnVar.sln? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
Too long with no output (exceeded 10m0s): context deadline exceeded
```
We weren't able to figure out any reason that EnvVar.sln would already be there, unless CircleCI did something really bad, reusing an un-erased VM.
Anyway, it makes sense to use …
> Use unzip -o (mostly in testing)

- containers/ddev-webserver/scripts/start.sh
- pkg/version/version.go
A user had a problem where the ddev-webserver would fail to start on *any* project with this in the logs:
```
cp: cannot open '/home/.ssh-agent/known_hosts' for reading: Permission denied 
```
/home/.ssh-agent is actually mounted from a docker volume, ddev-ssh-agent_socket_dir. And in this case, when we inspected the actual contents, we found that /home/.ssh-agent/known_hosts actually was owned by root, which it shouldn't have been. We have no idea how it got that way.
The problem was resolved by running the webserver container with `docker run -it --rm -u $(id -u) -v ddev-ssh-agent_socket_dir:/home/.ssh-agent  drud/ddev-webserver:v1.11.0-built bash` so that we could inspect things. At that point, we found the known_hosts owned by root and `sudo rm /home/.ssh-agent/known_hosts` solved the …
> Use sudo to copy dotfiles into user dir on start

- containers/ddev-webserver/files/usr/local/bin/disable_xdebug
- containers/ddev-webserver/files/usr/local/bin/enable_xdebug
- containers/ddev-webserver/files/var/www/html/docroot/test/xdebug.php
- containers/ddev-webserver/test/containertest.sh
- pkg/version/version.go
Due to the nature of apache-cgi we need an config reload to make php config changes work. Therefore running `ddev exec enable_xdebug` with `apache-cgi` as webserver turns on Xdebug only for the CLI and not for normal webserver requests.
This adds an apache2 reload to the enable_xdebug and disable_xdebug bash scripts in case the current webserver is apache-cgi.
Use the containertest.sh which now checks if both the CLI and the webserver have Xdebug enabled/disabled after using the commands.
> Fix enable_xdebug / disable_xdebug not fully working for apache-cgi

- cmd/ddev/cmd/composer_test.go
It seems `composer create-project --no-install` fails quite often on Windows NFS environments. I don't know how to sort this out, so removing that particular portion of the test on Windows NFS.
> Skip composer --no-install on Windows NFS (tests only)

- .circleci/config.yml
- .circleci/macos_circle_vm_setup.sh
Apparently homebrew has phased out python2 now in one of the recipes and switched to python3. Anyway, we have to unlink python2.
> Unlink python2 since it can't be used any more

- pkg/ddevapp/drupal.go
Drupal 8.8 changed where the sync directory is defined
(https://www.drupal.org/node/3018145)
Changing the code to use $settings rather than $config_directories.
> New location to define sync directory

- .circleci/macos_circle_vm_setup.sh
We've been occasionally seeing docker not starting up in CircleCI macOS instances. But the loop is infinite, so the test runs until circle stops it. Kill it in a shorter amount of time.
> Add timeout to docker startup in macos circleci

- cmd/ddev/cmd/commands.go
In testing @jonaseberle 's excellent and very fancy dump-db commands (https://github.com/drud/ddev-contrib/pull/30) I noted that the .ddev/commands/web/target subdirectory showed up as a "target" command.
This checks to make sure that items in custom command directories are not directories, removing them in that case.
> Subdirectories in commands dirs should not show up as commands

- docs/users/extending-commands.md
I think this came from a version when the `composer` command was not yet available. Also the `-d` pointed to the default directory.
The example does not use an available ddev command which would make the docs more consistent.
> Simplify TYPO3 composer example

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/settings_test.go
Drupal 8 drush drush.yml has always been placed in <docroot>/sites/all/drush. However, community opinion seems to be that putting drush.yml in <projectroot>/drush. 
Both of these 
* Can break multisite in the same way by overriding the default uri
* Create a new drush.yml file that is annoying to people and they may have to take over. 
But this is a slightly better place, outside Drupal's docroot, etc.
> Move drush.yml into /drush from sites/all/drush

- Makefile
- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
xdebug has been fixed upstream, fixing #1996. This applies the change to the master branch; a patch fix for v1.12.2 is in the 20200106_notarize_v1.12.1 branch.
> Bump web tag for xdebug 2.9.1 fixes #1996

- containers/ddev-dbserver/Dockerfile
- containers/ddev-dbserver/Makefile
- pkg/version/version.go
The mysql builds suddenly started failing because xtradb requires gnupg2 package. 
This adds it.
> Add gnupg2 to container build to fix xtrabackup fail

- cmd/ddev/cmd/restore_snapshot.go
#2031 points out that `restore-snapshot` doesn't happen in bash completions.
It's a result of trying to make the command not show up if omit_containers[db] is set, but it's probably not a good idea.
Bash completions are generated with no context (no project config'd or running) and so this wouldn't show up. In the future, we might consider changing the generation to be done in the context of a configured project. I think that's the basic flaw of this approach.
> Always add restore-snapshot command into list, fixes #2031

- pkg/ddevapp/drupal.go
#1994 switched settings.ddev.php to handle Drupal 8.8+ new method of managing config_sync_directory. However, it was a bit naive, and results in warnings about undefined CONFIG_SYNC_DIRECTORY on newer Drupal versions.
Drive the usage on existence of CONFIG_SYNC_DIRECTORY instead of setting both things.
> Improve settings.ddev.php handling of config_sync_directory

- pkg/version/version.go
New container versions for coming edge v1.13.0-rc1
> Bump containers to v1.13.0-rc1 (and phpmyadmin to 5)

- cmd/ddev/cmd/export-db.go
- cmd/ddev/cmd/export-db_test.go
- cmd/ddev/cmd/testdata/TestCmdExportDB/nondefault.sql
Discovered in testing: Using the "-d" or "--target-db" option with `ddev export-db` didn't actually change the db. It always exported the database named "db".
This fixes it.
It adds tests for this scenario as well.
> Actually select database when --target-db is provided to export-db

- cmd/ddev/cmd/config.go
Testing for v1.13.0 revealed the bogus "Provider.Validate() returned nil" statement on ddev config. I couldn't find any reason that this existed except as printf debugging code.
`ddev config`
When it goes through and does everything you should no longer see the "Provider.Validate() returned nil" warning message.
> Remove debug code about provider.Validate return value

- pkg/ddevapp/drupal.go
In https://github.com/drud/ddev/pull/1856 the environment variable IS_DDEV_PROJECT was introduced and used to wrap things like settings.ddev.php
However, in final testing for v1.13.0 it was noted that there was a TYPO in drushrc.php, which had IS_DRUSH_PROJECT instead of IS_DDEV_PROJECT. As a result, when drush was used on the host on a D7 project the URL wasn't set correctly.
With a Drupal 7 project:
```
ddev config && ddev start
drush uli
```
You should see the URL generated properly.
> Use proper IS_DDEV_PROJECT, not IS_DRUSH_PROJECT

- pkg/ddevapp/ddevapp.go
We've had a few questions like #2049 where people see errors like "Failed to start my-project: failed to load any docker-compose.*y*l files:"
So far it's not been easy to track them down. 
You can start a project, remove .ddev/docker-compose.yaml, then `ddev exec ls` and you'll get it. But most of the time we don't understand.
This PR:
* Tells the directory in which it's looking for docker-compose.yaml.
A future PR will prevent `ddev config` or `ddev start` in directories that have glob patterns in them. That seems too risky for near-release of v1.13.0, and this doesn't happen that often.
The simple change of the output should help us with debugging and learning new instances of this problem.
> Give more info on "Failed to start <project>: failed to load any docker-compose.*y*l files"  for #2049

- cmd/ddev/cmd/commands.go
https://github.com/drud/ddev/pull/2022 attempted to prevent *directories* in the .ddev/commands/* area from showing up as commands. Because they shouldn't. 
It failed. 
This fixes it. 
```
mkdir .ddev/commands/host/junkhost .ddev/commands/web/junkweb .ddev/commands/db/junkdb
ddev | grep junk
```
You shouldn't see anything.
> Subdirectories of .ddev/commands/* should not show up as custom commands

- pkg/version/version.go
Bump container versions to v1.13.0-rc2 for rc2
> Bump container versions to v1.13.0-rc2

- .circleci/generate_artifacts.sh
As far as I know only Quickstart uses the image tarball, but it did not include the phpmyadmin image before this PR.
> generate_artifacts needs to include phpmyadmin image in image tarball [skip ci][ci skip]

- docs/users/cli-usage.md
This is just a re-open of #1993 
* Drupal 8.8 now has its own composer template, drupal/recommended-project, so we no longer need to use the traditional template. See [Drupal.org docs](https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates)
* I updated the bedrock/WordPress and TYPO3 quickstarts to not require switching the project type.
Notes in #1993 point out 
* trouble on Windows with unzipping. This seems to be a Docker problem when WSL2 is enabled.
* Drush is not installed by recommended-project. So we need to mention that and add it to this one.
> Use drupal/recommended-project template now that Drupal 8.8 is here (docs only), fixes #1920

- .circleci/config.yml
- .circleci/generate_artifacts.sh
The part of the script that determins when to build image tarballs
hadn't been tested, and they didn't get built in v1.13.0,
so have to be built manually.
This fix should solve the problem.
> Correctly detect when to build image tarballs [skip ci][ci skip] (Build only)

- pkg/ddevapp/config.go
- pkg/ddevapp/utils.go
This follows on https://github.com/drud/ddev/pull/2052
and attempts to discover the problems shown in #2049 
Essentially, there are times that `ddev start` or other commands (`ddev ssh`?) result in "Failed to start <project>: failed to load any docker-compose.*y*l files". We know one occasion, and it's when there are glob characters in the full path to the project.
There may be other causes.
This PR should *not* be merged into v1.13.0, but go on the back burner to be included in v1.14 or whatever. It may involve some risk that I'd rather not take.
> Improve docker-compose.y*ml parse: Prevent using glob inappropriately

- cmd/ddev/cmd/root.go
#2065 reports that most (all?) of the event description in Segment/Amplitude is missing. It was reported as just being the "type" field, but really everything is missing. 
As  in another bug, #1882, the codebase has a long history of depending on init() for lots of things, and init() is a lousy cheater, with poorly-defined execution order. 
The actual population of the event struct should happen right before the event is to be sent, and that should do the job (assuming the correct analysis of the problem)
> Move event initialization to right before reporting, fixes #2065

- docs/users/cli-usage.md
Installing via https:// does not give problems any more since TYPO3 v9
> Clarify TYPO3 "Trusted host patterns mismatch"

- .circleci/linux_circle_vm_setup.sh
CircleCI did something that broke curl's respect for the system CA path. This adds a .curlrc to fix that and make ddev-router tests work again.
> Fix curl recognition of system CA path (testing only)

- cmd/ddev/cmd/import-db.go
The help text for the `target-db` argument in `import-db.go` was copied from the `extract-path` argument. It needed to be updated.
It updates the help text to mirror the help text used for the `target-db` argument on the `export-db` command.
Run `ddev help import-db` and observe that the help text for `target-db` option is a copy of the different option `extract-path`. After using this MR it is appropriate documentation.
No new tests. Not sure if help text is tested?
n/a from my perspective.
> Fix some copy-pasta for the command help text.

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/php/5.6/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.0/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.1/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.2/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.3/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.4/fpm/php-fpm.conf
- pkg/ddevapp/config_test.go
- pkg/version/version.go
Upstream php-fpm packaging suddenly changed where the php-fpm pid is stored, causing usage of extra packages (or custom Dockerfile) to fail. Reported in #2092 
* Create the new directory
* Change all fpm configs to use the standard directory
* Add a test to make sure that extra_packages works so we catch stuff like this in nightly build in the future.
* Add webimage_extra_packages: [php7.3-ldap]
* `ddev start`
* Should work
> Put php-fpm pidfile in new location for upstream, fixes #2092

- .circleci/config.yml
- .circleci/generate_artifacts.sh
- .circleci/linux_circle_vm_setup.sh
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/php/5.6/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.0/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.1/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.2/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.3/fpm/php-fpm.conf
- containers/ddev-webserver/files/etc/php/7.4/fpm/php-fpm.conf
- pkg/ddevapp/config_test.go
- pkg/version/version.go
A point release v1.13.1 is required because of upstream changes, see #2099 
Essentially upstream PHP packaging changed, #2099 fixes it, but it's on master, and we need to backport it to a v1.13.1
This should be *merged* not *squashed*
> Prepare v1.13.1 point release

- build-tools/makefile_components/base_build_go.mak
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/pause_test.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop_test.go
- pkg/ddevapp/ddevapp_test.go
> Bump to build-tools 2.4.0, golang 1.14

- containers/ddev-webserver/files/etc/php/5.6/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.0/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.1/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.2/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.3/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.4/fpm/php.ini
- pkg/version/version.go
This fixes #2083 when with an `apache-fpm` web server in a Drupal project accessing /update.php/selection returns the following error:
> No input file specified.
`cgi.fix_pathinfo=1` lets CGI interpret the path correctly. See [`PATH_INFO`](https://tools.ietf.org/html/rfc3875#section-4.1.5) in the CGI specs.
Same as in the opening post to #2083  
Should there be tests for this issue?
Probably worth to mention that setting `cgi.fix_pathinfo=1` may come with security implications. But I don't know how relevant these implications are in a local setup.
* [Turned on cgi.fix_pathinfo still “dangerous” in Nginx?](https://security.stackexchange.com/q/177354/150906)
* [Is the PHP option 'cgi.fix_pathinfo' really dangerous with Nginx + PHP-FPM?](https://serverfault.com/q/627903/291405)
I wonder if …
> Set cgi.fix_pathinfo=1 in php-fpm php.ini files, fixes #2083

- scripts/windows_ddev_nfs_setup.sh
The NFS Installer on Windows errored out.
The $HOME variable isn't quoted and when a space is present in the profile it gets expanded into another parameter to the docker command.
This PR quotes the value to prevent unintended consequences.
> NFS Installer on Windows breaks when spaces present

- docs/users/cli-usage.md
Install clean 1.13 ddev. 
Install Magento 2 using the quickstart tutorial.
Accessing https://magento2.ddev.site/ gives an error page with message "There is no back-end webserver at the url you specified".
Use correct url in quickstart
No
> Fix Magento 2 quickstart default url

- pkg/ddevapp/utils.go
When executing commands on a project whose files have gone missing, an error message instructs you to return the files or delete the project. The "delete the project" part of that message has a typo.
This PR fixes the typo.
> Fix typo '--omit-snaphot'

- pkg/ddevapp/backdrop.go
- pkg/ddevapp/drupal.go
`settings.ddev.php` defined a few `ini_set`. Those `ini_set` are not part of the `default.settings.php` that comes with a vanilla Drupal.
The problem of having those `ini_set` is that it can result with `ini_set(): Headers already sent. You cannot change the session module's ini settings at this time` (witnessed for example in PHPunit tests).
One option would be to prefix it with `@` (e.g. `@ini_set('session.gc_probability', 1);`), however as this doesn't appear in the `default.settings.php`, it's likely a better idea to completely drop it.
Removes `ini_set`.
> Remove ini_set() from settings.ddev.php

- pkg/ddevapp/config_test.go
TestTimezoneConfig had a naive assumption about CET vs CEST, and now that CEST has arrived, the test fails. 
Allow the test response to be either CET or CEST.
> Make TestTimezoneConfig more robust for summertime CEST

- pkg/ddevapp/ddevapp_test.go
On Windows you can't just rename/mv/rm a directory that's in use, and TestDdevDescribeMissingDirectory has been haunted by occasional failures due to that. Even though the project is now shut down before the rename, it seems maybe a sleep is in order. This adds a sleep after the stop.
> Minor improvement for reliability of TestDdevDescribeMissingDirectory on Windows (tests only)

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/pause_test.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/testcommon/testcommon.go
* A few timeouts in TestDdevFullSiteSetup
* A few failures on Test*MissingDirectory that weren't fixed in #2139 
Increase timeouts, wait after stopping project
> Improve a few tests to prevent transient failures (tests only)

- containers/ddev-webserver/files/etc/nginx/nginx-site-backdrop.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-default.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal6.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal7.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal8.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-magento.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-magento2.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-typo3.conf
- containers/ddev-webserver/files/etc/nginx/nginx-site-wordpress.conf
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
Docker desktop 2.2.3.0 (both Windows and Mac) can't handle IPV6, see github.com/docker/for-win/issues/6206 and https://github.com/docker/for-mac/issues/4415
An untouched line in our nginx config binds nginx to ::80 and ::443, but it's completely unnecessary as far as I know. 
Remove the ipv6 bind lines.
Try out ddev on windows or mac with docker 2.2.3.0
Note that you can use the image that works with `webimage: drud/ddev-webserver:20200402_remove_ipv6` in your project's config.yaml
> Remove unneeded ipv6 listen from nginx config
