- README.md
This removes `import` and adds `import-db` and `import-files`.
> Updated available commands.

- circle.yml
- pkg/plugins/platform/utils.go
- pkg/util/dockerutils.go
- pkg/util/utils.go
Codecoroner reports some unused code in our project. Let's go ahead and get rid of it. This is built on top of #167.
`make codecoroner` should report clean.
Since we're removing dead code with this branch, I've also enabled codecoroner on all future test runs.
> Remove dead code

- README.md
See additional commentary here (https://github.com/drud/ddev/issues/196#issuecomment-300459091) for Linux support and here (https://github.com/drud/ddev/issues/196#issuecomment-300272958) for Windows support.
#196 
No impact on code.
> Updating w/outcome of drud/ddev/issues/196

- pkg/updatecheck/updatecheck_test.go
I made a typo in https://github.com/drud/ddev/pull/217
Spell gooder 📚
> Fix typo in updatecheck

- cmd/ddev/cmd/remove.go
- cmd/ddev/cmd/remove_test.go
- cmd/ddev/cmd/root_test.go
- docs/users/cli-usage.md
- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
- pkg/dockerutil/dockerutils.go
- pkg/plugins/platform/local.go
- pkg/plugins/platform/local_test.go
- pkg/plugins/platform/types.go
- pkg/util/prompt.go
Reverts drud/ddev#340
This broke our nightly build (https://circleci.com/gh/drud/ddev/1165) and we're not sure why at this point. This reverts the change until we can fix the issue.
> Revert "Use named volumes for MySQL volume"

- docs/users/extend/additional-services.md
- docs/users/extend/customization-extendibility.md
These are some minor fixes to the docs that were uncovered while trying to get docs builds going again.
You can view this version of the docs site here: https://ddev.readthedocs.io/en/docs-fix/
> minor docs fixes

- README.md
OP #378 Improving the proejct readme.md
Changing the verbiage.
> Update Opening for Readme.md DDEV/378

- docs/index.md
OP #378 
Change the intro ddev verbiage to what was listed in the parent issue.
> Updating RTD Index.md Intro ddev/378

- pkg/plugins/platform/local.go
Typo in user-exposed message
Fix typo.
> Fix typo 'have you ran'

- mkdocs.yml
> updates docs ToC

- build.sh
- docs/developers/surf-testmachine-setup.md
Only I know how to set up a test machine with surf.
Document it a little.
> Add docs on test machine setup, minor improvement to build.sh

- pkg/ddevapp/config.go
- pkg/plugins/platform/router.go
Noticed a couple of spelling issues identified by goreportcard.
Corrects spelling issues.
> Minor spelling corrections.

- README.md
- docs/index.md
… and instructions for Windows 10 Pro.
* The README.md is out of date and this question has come up again and again.
* The words "Experimental Support" are removed.
* NA
* NA
* NA
* Text only change
> Removed 'Experimental Support' because we have adequate test coverage and instructions for Win10Pro

- .github/ISSUE_TEMPLATE.md
We decided to add a complexity rating to our issue template. Here's a shot at it.
> Add complexity rating to issue template

- docs/index.md
We committed to support this and we just need some additional documentation outside the issue queues to make this more obvious.
See verbiage in PR.
OP [drud/ddev/issue/352](https://github.com/drud/ddev/issues/352)
> Semantic Versioning in readthedocs, for drud/ddev #352

- README.md
- docs/index.md
ddev README.md is out of date and duplicates a bit of our documentation. This is an attempt to correct and consolidate.
OP https://github.com/drud/ddev/issues/251
> DDEV 251: readme and documentation updates

- README.md
Looks like an awesome project! Some people might see WordPress capitalized incorrectly and pass over the project or something, this fixes it to the correct capitalization.
> chore: Capitalized WordPress

- docs/users/extending-commands.md
While learning about exec-host I happened on a typo, then discovered that the example didn't use exec-host. Needed fixing.
> Fix exec-host docs

- build-tools/makefile_components/base_build_go.mak
- build-tools/makefile_components/base_build_python-docker.mak
Updating everything to golang 1.10. This shouldn't change anything particularly.
> Updated build-tools to 1.5.5 (golang 1.10)

- pkg/ddevapp/typo3.go
Resolves: https://github.com/drud/ddev/issues/632
> Generate AdditionalConfiguration.php compatible with TYPO3 8.7, fixes #632

- README.md
- cmd/ddev/cmd/root.go
- docs/index.md
Fixes https://github.com/drud/ddev/issues/699
> Document how to upgrade ddev, fixes #699

- docs/users/extend/customization-extendibility.md
I don't think the switch-from-utf8mb4-to-utf8 instructions I put in there before were adequate, this seems to totally work.
One line docs fix.
> Trivial Fix utf8 instructions

- README.md
Backdrop has been officially supported and is noted in our docs. This just updates the main README.md to reflect that.
Adds a link to our Backdrop Quickstart.
> Note Backdrop's quick start.

- docs/index.md
Minor docs change - we have been requiring changes on upgrade and the general docs don't currently mention that.
> Add warning about release notes to install docs

- README.md
We need more permanent support, HOWTO, problem-solving. OP #702
Add Stack Overflow to support techniques in docs.
> Add Stack Overflow as support mechanism (docs), fixes #702

- docs/index.md
There's an AUR repo for ddev, so we should mention it in the docs.
Adds docs.
Fixes https://github.com/drud/ddev/issues/818
> Document AUR repository for installing ddev

- README.md
- docs/index.md
- docs/users/troubleshooting.md
OP #872 mentions adding StackOverflow links to docs, this PR adds those references.
> Updates support options, adding StackOverflow, fixes #872

- docs/developers/release-checklist.md
The steps involved in generating a `ddev` release weren't version controlled and relied on institutional knowledge.
Add an authoritative workflow to create a `ddev` release.
> Add release checklist

- docs/users/cli-usage.md
With a composer example for TYPO3 you can setup a fresh installation.
> Add Composer Setup Example for TYPO3

- pkg/version/version.go
Bump container versions from v0.20.0 to v1.0.0.
> Bump container versions to v1.0.0

- pkg/ddevapp/templates.go
Trailing whitespace.
Remove whitespace.
Take a look. :)
> fix whitespace in generated config.yaml

- Makefile
We're hitting timeout on gometalinter quite a lot. Bump it up.
> Increase gometalinter timeout as we're hitting it too often

- docs/developers/buildkite-testmachine-setup.md
I found yet another thing that needs to go in the testbot install docs. This is trivial, it can be pulled after I reinstall the win10home testbot, maybe I'll learn something else.
> Add zip to list of testbot requirements

- docs/users/extending-commands.md
People have struggled with php module installation
Provide an example (including fpm restart).
> Add php module post-start hook example to docs, fixes #1117

- docs/index.md
- docs/users/uninstall.md
#1059 requests uninstall instructions. We owe them! This adds them.
>  Add uninstall instructions, docs only, fixes #1059

- pkg/testcommon/testcommon.go
This PR is for test improvements and may collect a few of them before being pulled.
* Fix panic in TestGetLocalHttpResponse
> Test Improvements: Fix panic in TestGetLocalHttpResponse, etc. for #1270

- docs/developers/building-contributing.md
- docs/developers/buildkite-testmachine-setup.md
Time moves on. Tools change names. Minor updates to developer/buildkite setup docs.
> Minor updates to developer docs [skip ci] [ci skip]

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Meta.md
- .github/ISSUE_TEMPLATE/release-checklist-template.md
this adds a new issue template for our release checklist to Github
> Add release issue template

- pkg/ddevapp/ddevapp_test.go
This is just to collect obvious discovered test cleanups. We'll pull it after a while, probably after v1.5.0 release.
> Test cleanups, no rush

- docs/index.md
> Fix Arch Linux link in docs

- CONTRIBUTING.md
- docs/developers/building-contributing.md
- docs/developers/buildkite-testmachine-setup.md
- docs/users/developer-tools.md
- docs/users/docker_installation.md
Minor documentation updates, mostly for docker toolbox, but also some updates to CONTRIBUTING.md and related.
> Documentation updates including for Docker Toolbox, fixes #1271

- docs/developers/release-checklist.md
- docs/index.md
- docs/users/cli-usage.md
- docs/users/docker_installation.md
- docs/users/uninstall.md
We're supporting Linuxbrew now, put technique in docs.
> Update docs for Linuxbrew

- .circleci/README.md
- .circleci/trigger_build.sh
- docs/developers/building-contributing.md
- docs/index.md
Sorry, I obviously pulled the previous docs PR too soon. This fixes the subtitle about linuxbrew.
> More final v1.5.2 docs

- README.md
Maintenance is being shown as stalled, which seems to be not true.
I updated the year for you, that the correct data is being pulled from shields.io
> Fix Maintenance status in Readme

- docs/developers/buildkite-testmachine-setup.md
Minor improvements to testbot setup docs from recent experience.
> Improve macos buildkite setup instructions [skip ci][ci skip]

- containers/ddev-router/nginx.tmpl
- containers/ddev-webserver/files/etc/nginx/nginx.conf
- containers/ddev-webserver/files/etc/php/5.6/apache2/php.ini
- containers/ddev-webserver/files/etc/php/5.6/cgi/php.ini
- containers/ddev-webserver/files/etc/php/5.6/cli/php.ini
- containers/ddev-webserver/files/etc/php/5.6/fpm/php.ini
- containers/ddev-webserver/files/etc/php/5.6/fpm/pool.d/www.conf
- containers/ddev-webserver/files/etc/php/7.0/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.0/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.0/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.0/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.0/fpm/pool.d/www.conf
- containers/ddev-webserver/files/etc/php/7.1/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.1/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.1/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.1/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.1/fpm/pool.d/www.conf
- containers/ddev-webserver/files/etc/php/7.2/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.2/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.2/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.2/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.2/fpm/pool.d/www.conf
- containers/ddev-webserver/files/etc/php/7.3/apache2/php.ini
- containers/ddev-webserver/files/etc/php/7.3/cgi/php.ini
- containers/ddev-webserver/files/etc/php/7.3/cli/php.ini
- containers/ddev-webserver/files/etc/php/7.3/fpm/php.ini
- containers/ddev-webserver/files/etc/php/7.3/fpm/pool.d/www.conf
- pkg/version/version.go
Various edge-case usages have run into issues in the web container and router container, this makes minor changes for those.
OP #1507: nginx client_max_body_size,
max_input_vars (can't remember who had trouble with it)
OP #1447: Some people hit pm.max_children in php-fpm, it's probably not an actual issue, but easy fix.
> Minor web container and router container config changes, fixes #1507, fixes #1447

- .circleci/README.md
- .circleci/trigger_release.sh
- docs/developers/release-checklist.md
I tried to track a few release docs updates during v1.7.1, this is just docs-only to reflect that.
> Minor release docs improvements

- docs/users/extend/additional-services.md
- pkg/servicetest/testdata/services/docker-compose.solr.yaml
The post-setup instructions for Solr are not completely clear.
Some improvements to the Additional Services page, and the Solr config yml.
rtfm (-:
> Further improved Solr install docs.

- pkg/version/version.go
Time for a new release. Bump containers to v1.8.0
> Bump container versions to v1.8.0

- docs/users/cli-usage.md
There were a couple of minor problems with the wordpress composer quickstart
Docs fix only.
> Improve wordpress quickstart with ddev config [skip ci][ci skip]

- docs/index.md
In testing we discovered some instances where the mkcert installation did not go as easily as planned on Linux. 
Add some more detail to Linux install mkcert.
> Improve mkcert docs for linux [skip ci][ci skip]

- pkg/ddevapp/drupal.go
> Fix coding standards of generated Drupal settings, fixes #1582

- pkg/servicetest/testdata/services/docker-compose.memcached.yaml
The docker-compose.memcache.yaml file's comments needs a little tidying.
This tidies up the file to be easier to follow.
#1549
n/a
> Improvements to the memcache compose file

- docs/users/extend/customizing-images.md
- docs/users/performance.md
- docs/users/uninstall.md
Minor docs issues that people mention.
* Mention how Dockerfile.example gets created on `ddev config`
> Minor docs additions (ongoing PR), fixes #1482 [skip ci][ci skip]

- pkg/ddevapp/config.go
Testing for v1.9.0 release [here](https://github.com/drud/ddev/issues/1595#issuecomment-505458860) found that timezone validation on Windows was failing to validate correct timezones. It turns out that golang on Windows mostly can't do a timezone.LoadLocation() unless golang is installed on the machine and $GOROOT points to it. Neither of which are likely with our users.
If we get the error of type syscall.errno on Windows, assume it's a result of this and don't validate, but emit a message instead.
> Special-case validation of timezone on windows, since golang windows can't do it

- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/share_test.go
- docs/developers/buildkite-testmachine-setup.md
- docs/developers/release-checklist.md
- docs/index.md
- pkg/ddevapp/composer_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/pantheon_test.go
* Make ddev's help give pointers to docs
* Add ddev-edge to install documentation
* Minor test fixes
* Minor updates to developer docs
> Minor fixes to tests and documentation

- docs/users/extend/customization-extendibility.md
Improve verbiage about default containers.
> Improve verbiage about default docker images [skip ci][ci skip] (docs only)

- pkg/version/version.go
It's getting time for a release. Bump image versions to v1.10
> Bump image versions to v1.10

- pkg/ddevapp/instrumentation.go
- pkg/globalconfig/global_config.go
Per #1726 Segment needs to place a few things into Context, and handle instrumentation_user in its own first-class field.
This PR also adds comments with more info to the global_config.yaml
> Move Segment items into Context, better instrumentation_user, fixes #1726

- .circleci/config.yml
- .circleci/generate_artifacts.sh
- .circleci/trigger_release.sh
- Makefile
In v1.10.0 Chocolatey artifacts didn't get uploaded during artifacts build. Fix it.
> Chocolatey artifacts didn't get uploaded during artifacts build

- containers/ddev-ssh-agent/Dockerfile
- containers/ddev-ssh-agent/files/etc/group
- containers/ddev-ssh-agent/files/etc/passwd
- pkg/ddevapp/config.go
- pkg/version/version.go
There seem to be two issues running here:
* Upper-case usernames cause a failure building ddev-ssh-agent (which is an Alpine image). 
* Docker disk space usage results in something like this.
```
Building ddev-ssh-agent 
Service 'ddev-ssh-agent' failed to build: Error processing tar file(exit status 1): write /var/log/tallylog: no space left on device 
Failed to start api-nml: failed to start ddev-ssh-agent: Failed to run docker-compose [-f /Users/mileslemon/.ddev/ssh-auth-compose.yaml -p ddev-ssh-agent up --build --force-recreate -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
v1.10.0: Pulling from drud/ddev-ssh-agent
Digest: sha256:76f98314c9691f74b015da54a2f16469c17385a1cb1bbe1a1595a7b0af5a395b
Status: Downloaded newer image for …
```
> Fix problems with some usernames and uids in v1.10, fixes #1758

- docs/users/extend/additional-services.md
> Documenting Solr version + instructions how to change it

- pkg/ddevapp/ddevapp.go
#1706 
Provides two ways to encourage the user to upgrade DDEV (config).
Downgrade local DDEV, execute on a latest configfile and check the warning message.
Tests would be nice to add later.
#1706 
No changes are needed on the user side.
> Better version suggestion

- .buildkite/sanetestbot.sh
- .buildkite/test.sh
In workjing on quicksprint I noted a bug in the test.sh. Fix it.
> Use ddev --version in opening section of test.sh

- docs/users/extend/custom-commands.md
When creating my first custom command, there were a few subtleties that I didn't follow. 
I moved the bit about scripts needing to be executable to the top, along with a couple other things I discovered that should be helpful.
> Updated custom command docs with a little more detail

- docs/users/extending-commands.md
> [TASK] Hint on post-stop runs for exec-host only

- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
This is another attempt to fix the nightly build. This time I was able to isolate the failure locally and recreate it and I think I have it now.
> Tests: Attempt again to fix cruft that breaks TestDdevFullSiteSetup

- docs/users/troubleshooting.md
> Troubleshoot port issues on Windows [docs only]

- docs/users/extend/additional-services.md
- pkg/servicetest/testdata/services/solr-configupdate.sh
There were some formatting and usability problems in previous PR
> Solr docs followup [skip ci][ci skip]

- docs/users/step-debugging.md
People still stumble on old PHPStorm/xdebug problem. Add it to docs.
> Minor docs update for phpstorm [skip ci][ci skip]

- pkg/ddevapp/drupal.go
> Header in drush.yml is wrong

- docs/users/extend/database_types.md
Slight adjustments to the database types documentation.
> Improve database_types docs

- docs/users/extend/additional-services.md
> Solr docs - fix typo with incorrect script name

- docs/users/cli-usage.md
A few docs improvements were suggested in the v1.13.0 release testing. This does them.
> Improve docs per notes in v1.13.0-rc1 testing [skip ci][ci skip]

- pkg/version/version.go
> Bump containers to v1.13.0 for release

- docs/users/performance.md
Typo in documentation: systme => system
Typo fixed
> Fix small typo

- docs/users/developer-tools.md
Documentation lacks information about new terminus abilities
Adds documentation about new terminus abilities
Proofreading?
None
> Add terminus documentation

- pkg/ddevapp/apptypes.go
@wizonesolutions pointed out typo "Not creating CMA settings files", thanks!
> Fix typo about CMS settings

- docs/developers/release-checklist.md
@cweagans kindly gave appropriate access to AUR repo and documented the process. Thanks! This links to those instructions and updates a few other things.
> Add AUR instructions to release process [skip ci][ci skip]

- docs/index.md
- docs/users/docker_installation.md
- docs/users/extend/customization-extendibility.md
- docs/users/extend/customizing-images.md
- docs/users/performance.md
- docs/users/troubleshooting.md
There are some typos in the documentation.
Er, fix the typos. ;)
- Review the updated files in the GitHub UI.
- Generate the docs using `mkdocs`. This may be overkill.
N/A
N/A
Rebuild the docs as usual.
> Fix some typos

- pkg/nodeps/utils.go
- pkg/nodeps/utils_test.go
#1969 
Stops the DNS lookup if it takes longer then 500ms (the value might need adjustments).
> Add timeout to IsInternetActive(), fixes #1969

- docs/index.md
> Windows: mkcert: add to firefox: add mkcert CA

- docs/users/docker_installation.md
> replace superceded package name docker-for-windows -> docker-desktop

- .circleci/linux_circle_vm_setup.sh
- docs/users/extend/customizing-images.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/nodeps/values.go
See #2205 for the original PR. This is a backport to provide this same thing on a v1.13.2 version.
> v1.13 backport of #2205, fixes #2092 (Use debian existing package conf, not new conf)

- docs/users/cli-usage.md
The Drupal 8 and Drupal 9 quickstarts change with the arrival of Drupal 9.
Minor docs touchups while I was there.
> Update Drupal 8 quickstart (docs only) [skip ci][ci skip]

- docs/developers/buildkite-testmachine-setup.md
- docs/developers/scripts/windows_buildkite_setup.sh
- docs/developers/scripts/windows_buildkite_start.ps1
Improve buildkite-agent setup instructions for Windows (docs only)
> Improve buildkite-agent setup instructions for Windows (docs only)

- .circleci/README.md
- .circleci/aur-checker-Dockerfile
- .circleci/bump_aur.sh
- .circleci/bump_homebrew.sh
- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
- docs/developers/release-checklist.md
Finally automate releases to Homebrew, Chocolatey, and AUR
> Automate releases to Homebrew, Chocolatey, and AUR, fixes #2213

- pkg/ddevapp/providerDdevLive.go
#2348 explains that you have to do a `ddev-live backup files` before you can count on `ddev-live pull files` to work
* Do the ddev-live backup files first
* Also adds debug output when required
Hook up a site and do a `ddev-live pull -y`. 
It would be reasonable to delete the database and files and .ddev/.ddev-live before beginning to confirm the functionality.
> Improve ddev-live integration with initial files backup, fixes #2348

- build-tools/makefile_components/base_build_go.mak
Golang v1.15 is out
Minor changes to build-tools (removing docker toolbox support)
Switch to not using :delegated in the DOCKERMOUNTFLAG
> Update build-tools to v2.5.1

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
Needed for https://github.com/drud/ddev/pull/2454 - creating a separate PR to first upgrade the image and see if everything still works as it should in the current state.
> Update CircleCI version to ubuntu-1604:202007-01

- docs/index.md
- docs/users/extend/custom-commands.md
- docs/users/providers/DDEV-Live.md
This PR is for ongoing docs updates/fixes, and should live at least a couple of weeks. Feel free to suggest docs changes.
* Remove project types from ddev-live doc
> Ongoing long-running docs PR, fixes #2478

- cmd/ddev/cmd/composer-create.go
- containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
I was noticing that some test projects were not cleaned up after the test was completed. This cleans up the ones I found.
> Improve test cleanup (tests only)

- cmd/ddev/cmd/auth-ssh.go
@AronNovak  reported in #2573 that `ddev auth ssh` doesn't return an error when the ddev-ssh-agent is omitted. That's wrong.
> ddev auth ssh shouldn't work if ddev-ssh-agent opted out, fixes #2573

- pkg/ddevapp/task.go
Output of exec-host is not correctly handled see issue.
exec.RunInteractiveCommand() is now used for exec-host tasks which solves the problem.
See also example from the issue.
```yaml
hooks:
post-start:
- exec-host: "echo test exec-host && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done"
- exec: "echo test exec && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done"
```
```bash
Executing post-start hook...
=== Running task: Exec command 'echo test exec-host && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done' on the host (NB-SIMON), output below
test exec-host
1: Sa, 24. Okt 2020 16:29:22
2: Sa, 24. Okt 2020 16:29:23
3: Sa, 24. Okt 2020 16:29:24
4: Sa, 24. Okt 2020 16:29:25
5: Sa, 24. Okt 2020 16:29:27
=== Running task: Exec command 'echo test exec && for …
```
> Fix missing output of exec-host, fixes #2477

- pkg/ddevapp/config.go
There have been oh-so-many test failures due to inability to download from getcomposer.org.
Try it a second time if the first time fails.
> Try twice to get composer; many test failures

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
> Bump to latest images

- docs/users/alternate-uses.md
Minor docs additions aimed at v1.16.0
> Add new details to casual webhosting section [skip ci][ci skip]

- docs/index.md
- docs/users/extend/in-container-configuration.md
* Mention the $HOME/bin directory and how it can be used with homeadditions.
> Ongoing docs for v1.16

- docs/users/extend/additional-services.md
There are various broken links in the page.
URLs updated.
> Fix broken links

- docs/users/extend/custom-compose-files.md
Wrong description in the docs
Corrects the naming of the port setup and how the exposed port is used
> Fix description of HTTPS_EXPOSE

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Bump webimage for v1.16.1 release
> Bump webimage for v1.16.1 release

- docs/index.md
- docs/users/docker_installation.md
- docs/users/extend/customizing-images.md
- docs/users/extending-commands.md
Improve docs as small improvements are discovered.
> Ongoing docs PR [skip ci][ci skip]

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/root.go
- containers/ddev-dbserver/README.md
- pkg/ddevapp/instrumentation.go
- pkg/version/version.go
- pkg/version/version_test.go
#2662: 
* We haven't been getting appropriate segment instrumentation reporting since ddev v1.16.0-alpha4, or at least aren't seeing the "version" attribute
* One user [reported](https://twitter.com/ochorocho/status/1331299788869021704) seeing "Instrumentation is opted in, but SegmentKey is not available" when doing a ddev command, which would imply a build problem.
* The last_started_version attribute was not properly updated
* Remove COMMIT and VERSION attributes, use DdevVersion
* Verify that the version segment attribute gets sent
* Fix logic error that caused last_started_version not to update
Mostly I don't know how to do a useful test for this.
> Fix segment instrumentation reporting, fixes #2662

- docs/users/extend/additional-services.md
> Updating the url for `solr-configupdate.sh`

- docs/users/performance.md
Two minor grammar fixes in the NFS setup for mac os section.
> [docu only] Grammar fixes

- docs/users/faq.md
- docs/users/performance.md
Little docs things get found and added to this PR :)
> Ongoing docs fixes

- README.md
The "maintained" badge on README.md has to be updated every year :)
> [docs] Update maintained badge on README [skip ci][ci skip]

- .circleci/config.yml
- .circleci/generate_artifacts.sh
- .circleci/linux_circle_vm_setup.sh
I noticed due to a CircleCI networking fail that we're not properly caching the testcache on circleci.
This should fix it.
> Testcache was wrong for circleci

- docs/users/extend/additional-hostnames.md
This fixes just a minor formatting issue
> Fix minor formatting issue in Additional Project Hostnames documentation

- docs/users/extend/customizing-images.md
- docs/users/shell-completion.md
Ongoing docs:
* Make more emphatic that you can't access mounted code during image build in custom Dockerfile
> Ongoing docs updates [skip ci][ci skip]

- .github/workflows/docscheck.yml
- Makefile
- docs/developers/buildkite-testmachine-setup.md
It's time for another PR to accept several docs commits.
This also lightens up on markdownlint checking on non-user-facing markdown
> [docs][tests] Ongoing docs work and lighten up on markdownlint

- .circleci/config.yml
There was a little extra unneeded being done in the circleci container tests.
> Minor fix to circleci container test

- .buildkite/test.sh
- pkg/ddevapp/ddevapp_test.go
The output of an empty db in phpmyadmin changed, causing TestDdevFullSiteSetup to fail.
Use the new expected response.
> [tests only] Minor upstream change in phpmyadmin caused test failure

- pkg/ddevapp/drupal.go
[Drupal 7: drushrc.php comment coding standards](https://github.com/drud/ddev/issues/2849)
I made the changes to the code writing the drushrc.php file and its doc comment.
No tests were added. Only changes made were to a string.
[Drupal 7: drushrc.php comment coding standards](https://github.com/drud/ddev/issues/2849)
> Drupal 7: drushrc.php coding standards, fixes #2849

- pkg/ddevapp/ddevapp.go
A new bug in docker-compose v1.28+ has docker-compose exec outputting ERROR: <errnum> when a an exec task has nonzero return, see https://github.com/docker/compose/issues/8169
The snapshot restore feature was depending on the nonzero result of an exec error, but the unwarranted output from docker-compose made it really ugly.
This workaround uses pidof and checks to see if anything is there instead of the previous approach
> Fix snapshot restore progress broken by docker-compose bug

- .buildkite/test.sh
- .buildkite/testbot_maintenance.sh
- .circleci/macos_circle_vm_setup.sh
- .github/workflows/selfhosted-upgrades.sh
- docs/developers/buildkite-testmachine-setup.md
- docs/developers/github-selfhosted-setup.md
- pkg/ddevapp/router_test.go
- scripts/docker-desktop-version.sh
- scripts/test_ddev.sh
This adds scripts/docker-desktop-version.sh, which will allow reporting the docker desktop version
> Add a script to parse docker desktop version

- scripts/macos_ddev_nfs_setup.sh
Thanks to @chellman a significant bug was discovered in the macos_ddev_nfs_setup.sh script - it set up amd64 machines as if they were arm64, which doesn't work. Thanks @chellman.
Fix the logic error - `uname -m` does *not* return "amd64" for amd64 machines. It gives "x86_64"
We don't have tests for this script. Tests that require root access and also (on Big Sur) authorization for full disk access are either difficult or impossible.
> Fix macos_ddev_nfs_setup.sh - was broken on amd64 [skip ci][ci skip]

- docs/users/extend/database_types.md
Snapshot docs mention the database type, but the example describes different database versions.
Adds mention of version constraints, per discussion in https://gitter.im/drud/ddev?at=60510519b5131f4f281d10ac
> Clarify caveat about snapshot compatibility

- docs/users/alternate-uses.md
- docs/users/extend/additional-services.md
- docs/users/faq.md
* Add FAQ about nginx headers when using apache, fixes #2870
> Ongoing docs for completion of ddev v1.17.0

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Fresh images are needed for a new major version
> Bump images to v1.17.0-rc1

- .github/ISSUE_TEMPLATE/Bug_report.md
- scripts/test_ddev.sh
#2905 test_ddev.sh failed if xq wasn't there... but xq wasn't even needed any more.
Improve script
> Make test_ddev.sh not need xq, not quit if not found, fixes #2905

- docs/users/providers/provider-introduction.md
> Fix provider command documentation

- docs/index.md
Firefox tab names and selections have changed slightly
> Update mkcert-in-Firefox docs;  Firefox tab naming changed

- cmd/ddev/cmd/global_dotddev_assets/commands/web/blackfire
> blackfire: Fix example command to set blackfire credentials

- .circleci/bump_homebrew.sh
- .circleci/config.yml
- .circleci/macos_circle_vm_setup.sh
Homebrew changed how the formula is done
Update the generated formula
I have tested this manually, releasing it on rfay/ddev, but it will have to be looked at closely on the next release.
> Update homebrew formula to fix deprecations, fixes #2942, fixes drud/homebrew-ddev#43

- docs/users/providers/platform.md
> Fix docs typo TERMINUS_MACHINE_TOKEN->PLATFORMSH_CLI_TOKEN for Platform

- docs/users/extend/additional-services.md
- pkg/ddevapp/ddevapp_test.go
Minor test fixup of TestDdevRestoreSnapshot
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/2991"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor test fixup of TestDdevRestoreSnapshot

- .github/workflows/master-build.yml
I happened to notice that only one macOS binary was getting notarized. Do both.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3015"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure to notarize both macos binaries

- .gitpod.yml
Details: https://github.com/gitpod-io/gitpod/issues/4205
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3032"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> prebuild is getting deprecated

- cmd/ddev/cmd/root_test.go
- pkg/util/utils.go
TestPoweroffOnNewVersion didn't work at all on Windows. This should fix it to make it work.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3031"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make TestPoweroffOnNewVersion work on Windows, fixes #2979

- .github/ISSUE_TEMPLATE/Bug_report.md
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3064"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixing a typo

- cmd/ddev/cmd/global_dotddev_assets/commands/web/blackfire
- containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/enable_xhprof
I'm working on a screencast and article on the new xhprof feature and the Blackfire.io feature, and will discover some issues and improvements, in commands and in docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3070"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [WIP] Profiling improvements and docs

- docs/users/troubleshooting.md
A recent PR triggered a spellcheck problem.
Reformat and fix it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3127"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix spellcheck problem

- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/debug-compose-config_test.go
- cmd/ddev/cmd/exec_test.go
- cmd/ddev/cmd/share_test.go
- pkg/archive/archive_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/embed.go
- pkg/ddevapp/provider.go
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerLocalfile_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/ddevapp/providerPlatform_test.go
- pkg/ddevapp/providers.go
- pkg/ddevapp/settings_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/fileutil/files.go
- pkg/fileutil/files_test.go
- pkg/globalconfig/global_config.go
- pkg/testcommon/testcommon.go
- pkg/util/capture.go
@bobbygryzynger was working on this in #2911 and I somehow messed it up with a rebase and that one got closed. 
This is still all his work.
See comments there.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix #2886: replaces deprecated ioutils package.

- docs/users/cli-usage.md
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3141"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> D9 Git repo still requires config to be run

- cmd/ddev/cmd/debug-mutagen.go
- docs/users/performance.md
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/version/version.go
* Improve TestDdevExec to be more resilient on Windows
* Docs updates
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Ongoing mutagen updates, test improvements, fixes #3139

- cmd/ddev/cmd/dotddev_assets/mutagen.yml
- docs/users/performance.md
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/provider.go
Docs and other ongoing finish work for mutagen.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3155"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mutagen finish work for alpha5

- pkg/ddevapp/mutagen.go
Mutagen status reporting on startup could be confusing with the lines changing all the time, and dots impeding the other status.
* Output a newline when status changes
* Remove the dots, as the status with changes may be adequate
Enable mutagen and `ddev start` and `ddev mutagen reset` and see if you like it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve mutagen startup status reporting

- pkg/ddevapp/providerAcquia_test.go
TestAcquiaPush has been failing a lot
Simplify and speed it up
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Simplify and speed up TestAcquiaPush

- .buildkite/testbot_maintenance.sh
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/utils.go
- pkg/dockerutil/dockerutils.go
The work done for the docker-compose v2 PR https://github.com/drud/ddev/pull/3083 is getting stale, and some of it has current value, so transplanting it here.
Once this gets in that one can be updated with the things that are left to do there. There will be loads of conflicts.
* #3083  
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3193"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Partial updates (volume naming) from docker-compose v2 PR

- cmd/ddev/cmd/poweroff.go
When the first project in the list was paused (perhaps due to docker restart or computer restart) there was an ugly message on `ddev poweroff` that everybody just ignored, `"Failed removing custom certs: %v"`
Turns out that there's no reason to exec into the container, no need to start it. Just use a `docker run` to clean up the certs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3217"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Simplify custom cert removal to get rid of paused container warning

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/import-db_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/mutagen-cmd_test.go
- cmd/ddev/cmd/mutagen-monitor.go
- cmd/ddev/cmd/mutagen-reset.go
- cmd/ddev/cmd/mutagen-status.go
- cmd/ddev/cmd/mutagen-sync.go
- docs/users/cli-usage.md
- docs/users/extend/config_yaml.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/list.go
- pkg/ddevapp/list_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/utils.go
- pkg/nodeps/utils.go
- pkg/styles/tables.go
- pkg/util/utils.go
* #3210 
* #3215 
* #3218 
* #3207 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix various bugs in ddev list and ddev describe, fixes #3210, fixes #3215, fixes #3218, fixes #3207

- docs/users/troubleshooting.md
Added these changes based on conversation with and support from @rfay in Slack.
I was getting errors during the `ddev start` process that where not covered in the troubleshooting guide. 
This PR provides documentation of how to identify the problem and how to solve it.  
N/A
N/A
N/A 
N/A
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update troubleshooting.md docs about port conflicts

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/describe_test.go
- pkg/globalconfig/styles.go
* #3242
Fixes the items listed there.
Try it out on gitpod or locally.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3243"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve table formatting and presentation, fixes #3242

- .ci-scripts/nsis_setup.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- .github/workflows/linux-build-setup.sh
I had to reinstall nsis today on a regular machine and had to go digging for how to do it, and found it was being done several different ways. 
Move the logic into one place.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3273"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Move nsis setup into a separate script

- docs/users/cli-usage.md
For discussion about this, see https://github.com/drud/ddev/issues/3299
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3363"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] Wordpress Quickstart - Add "Commandline Setup Example using WP-CLI"

- .circleci/config.yml
- cmd/ddev/cmd/xdebug_test.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example
- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
- pkg/ddevapp/dotddev_assets/providers/platform.yaml.example
- pkg/ddevapp/provider.go
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/ddevapp/providerPlatform_test.go
- pkg/version/version.go
* Upstreams from deb.sury.org have been updated
* php8.1-xdebug
* php8.1-xhprof
* Updated usable version of uploadprogress on php8.x
* Updated 8.1.0RC4
* Tests updated to allow testing of php8.1-xdebug and php8.1-xhprof
* #3292 
* #3263 
* This may solve #3333 because the db is now gzipped for transport
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3368"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update upstreams and add php8.1-xdebug php8.1-xhprof, fixes #3263, fixes #3292

- pkg/ddevapp/templates.go
Add missing comma ;-)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3380"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update templates.go with current list of PHP versions [skip ci]

- docs/users/extend/database_types.md
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3426"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use "ddev delete --omit-snapshot" instead of "ddev stop --remove-data"

- .spellcheckwordlist.txt
- cmd/ddev/cmd/share_test.go
- docs/users/step-debugging.md
- docs/users/topics/gitpod.md
- docs/users/topics/phpstorm.md
- mkdocs.yml
Various test and docs details.
* Make TestShareCmd more robust and report errors properly.
* Improve PhpStorm instructions, fixes #3401
* #3406
* Document gitpod usage for #3283
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3434"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Docs and test details for release of v1.18.2, fixes #3401, for #3283, fixes #3406

- pkg/ddevapp/webserver_config_assets/nginx-site-php.conf
The configuration for php project type should be kept as simple as
possible to avoid conflicts with the various needs of the various
applications. It's easy possible to enhance the Nginx configuration
with a custom include in .ddev/nginx afterwards.
The static file configuration is removed.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3454"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove unnecessary rules for static content

- .github/workflows/docscheck.yml
I have recently released 0.20.0 of the spellcheck GitHub action, I can see that you are using 0.8.0, so an update could be useful to you. Let me know if you have any issues with the proposal and I will try to accommodate.
I can recommend [Dependabot](https://github.com/dependabot) for keeping your GitHub actions up to date, if you want a PR proposing a basic configuration, please let me know.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3466"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bumped spellcheck GitHub action to version 0.20.0

- docs/assets/extra.css
- docs/developers/building-contributing.md
- docs/index.md
- docs/users/faq.md
The FAQ has been hard to maintain and has lots of hand-formatting in it.
It's also missing a section on how to install a specific version
* Rework using definition lists, supported by material style.
* Add new question about how to install a specific version.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3478"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Rework FAQ as definition lists dt/dd with some formatting

- docs/users/cli-usage.md
Minor updates to several quickstarts.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3485"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Review and improve various CMS quickstart recipes

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/root.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- pkg/util/utils.go
Attempt to debug macos mutagen TestCustomCommands failures
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3493"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Debug/improve macos mutagen TestCustomCommands failures

- go.mod
- go.sum
- vendor/modules.txt
Dependabot is complaining about another containerd problem, which is pulled in by fsouza/go-dockerclient
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix dependabot alerts about containerd

- docs/users/step-debugging.md
Docs to improve xdebug troubleshooting
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3533"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add minor details to xdebug troubleshooting

- README.md
- docs/index.md
Adding support channel
Added Discord permanent invite.
N/A
N/A
N/A
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3565"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added Discord server

- docs/index.md
- docs/users/cli-usage.md
- docs/users/docker_installation.md
- docs/users/performance.md
- docs/users/step-debugging.md
Minor markdownlint things that got pointed out after a markdownlint upgrade
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3595"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix new things markdownlint wants fixed

- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/laravel.go
Laravel 9, just released, requires PHP 8.0+
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use php8 for Laravel

- pkg/ddevapp/ddevapp.go
After 
* https://github.com/drud/ddev/pull/3668
went in, I noted that some pulls were happening at inconvenient times. It turns out that ddev-ssh-agent was being pulled before that, and also that ddev-webserver was used for some routine utility things, so needed to be there earlier.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3678"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Pull the fundamental images we need earlier in Start()

- docs/users/extend/customization-extendibility.md
Please see https://github.com/drud/ddev-contrib/pull/210#issuecomment-1071916362
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3717"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Document how to add env-file support

- cmd/ddev/cmd/get.go
* https://github.com/drud/ddev-drupal9-solr/issues/1
* https://github.com/drud/ddev-beanstalkd/issues/1
point out that the output can be improved
* Better output of pre-install activities, including explaining where they're happening.
* Call to Action to get them to visit the source page.
* Less green and more black in output
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve output of ddev get

- docs/developers/buildkite-testmachine-setup.md
Minor developer-focused test runner setup docs improvements.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3729"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve buildkite test machine setup [skip ci]

- docs/index.md
Try to make the distinction between "Docker CLI client" that colima needs and Docker Desktop
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3776"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update index.md for Docker CLI distinction

- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
* #3748 
AFAICT this was just some kind of build or process problem.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3753"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Rebuild mariadb/mysql images, add test, fixes #3748

- pkg/version/version.go
compose 2.5.1 has probably fixed https://github.com/docker/compose/issues/9428
Run a set of tests to see if they succeed.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3851"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Try docker-compose 2.5.1 to test functionality

- docs/users/cli-usage.md
- markdown-link-check.json
Added Drupal 10 Quickstart per recommendations from rfay.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3868"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update cli-usage.md to add D10 Quickstart

- pkg/ddevapp/config.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
* TestContainerWait fails quite a lot, seemingly a timeout. Bump the timeout
* Lots of failures downloading nodejs setup_*.sh, seems to be a problem on node server. Try twice.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3888"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [mostly tests] Test fixup and nodejs setup failure fix

- docs/users/cli-usage.md
Clarify the exact setting to use to opt-in/out to stats usage.
Adds instructions. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3911"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add more instructions on how to opt-in/out to stats usage.

- .buildkite/testbot_maintenance.sh
- docs/developers/buildkite-testmachine-setup.md
- docs/developers/scripts/windows_buildkite_setup.sh
- docs/developers/scripts/windows_buildkite_start.ps1
- scripts/macos_ddev_nfs_setup.sh
The buildkite setup docs were out of date
Worked through them with a couple of testbots
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3932"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [mostly docs] Buildkite installation maintenance

- README.md
I noticed the README.md had some out-of-date things in it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3928"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update README for current items

- pkg/ddevapp/nodejs_test.go
Minor test cleanups
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3966"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Improve nodejs tests [skip ci]

- .github/workflows/docscheck.yml
- .readthedocs.yaml
- docs/content/users/quickstart.md
- docs/mkdocs-pip-requirements
- mkdocs.yml
* #3977 
* #3967 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3980"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Readthedocs features update and debug current problems for #3967

- docs/content/users/quickstart.md
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3989"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove --no-interaction from quickstarts

- cmd/ddev/cmd/scripts/test_ddev.sh
for `ddev debug test` and test_ddev.sh:
* Add info about macOS version
* mount type inside container
* Actual results of healthcheck script
* A few other things.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4004"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve test_ddev.sh with a few pieces of info

- README.md
The FAQ link on the [README.md](https://github.com/drud/ddev/blob/master/README.md) page returns a 404 page.
It's a link that works.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4005"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update the FAQ link

- docs/content/users/extend/custom-commands.md
- docs/content/users/install/ddev-installation.md
- docs/content/users/install/docker-installation.md
- docs/content/users/topics/cms_specific_help.md
* Fix linting problem (broken link)
* Reorganize docker and ddev installation sections by OS
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4015"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix linting problem, reorganize docker and ddev installation sections

- .github/workflows/colima-tests.yml
- .github/workflows/docscheck.yml
- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config.go
- pkg/globalconfig/styles.go
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4024"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Colima update to hopefully fix #4022

- README.md
The install link on the [README.md](https://github.com/drud/ddev/blob/master/README.md) page returns a 404 page.
corrected link 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4020"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update the README.md install link

- .github/workflows/docscheck.yml
- docs/content/users/install/ddev-installation.md
Docs: Explain how to switch to the apt install from install_ddev.sh or homebrew.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4025"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Say how to switch to apt install on linux

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
yq was quite old, bump it to current.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4039"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump yq in container to current version

- version-history.md
Release time, version history update time.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4074"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update version history

- docs/content/users/install/docker-installation.md
[docs] Mention home directory requirement for colima
> [docs] Mention home directory requirement for colima

- .spellcheckwordlist.txt
- docs/content/users/basics/troubleshooting.md
Troubleshooting docs improvements
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4085"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add using curl and diagnosing DNS rebinding to troubleshooting

- .github/workflows/colima-tests.yml
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/debug-config-yaml.go
- pkg/ddevapp/assets.go
- pkg/ddevapp/instrumentation_test.go
- pkg/ddevapp/shopware6.go
- pkg/ddevapp/ssh_auth.go
- pkg/dockerutil/dockerutils.go
- pkg/globalconfig/global_config.go
- pkg/nodeps/utils.go
- pkg/nodeps/values.go
- pkg/output/text_formatter.go
- pkg/util/utils.go
- pkg/util/yamltools.go
- pkg/versionconstants/versionconstants.go
Once again, colima tests are mysteriously failing; last time this was fixed with cache version bump. Doing it again.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4094"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Bump colima caches again

- scripts/windows_ddev_nfs_setup.sh
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4103"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix broken windows_ddev_nfs_setup.sh [skip ci]

- docs/content/users/install/docker-installation.md
The 2nd step assumed you had DDEV installed, which isn't necessarily true as setting up Docker is usually the first step.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4102"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] fix colima installation step 2

- cmd/ddev/cmd/scripts/test_ddev.sh
* On colima, if the project directory isn't explicitly mounted by the colima config, the .ddev directory isn't mounted into /mnt/ddev_config and it causes things like docroot config to fail.
* On Mac M1, people can accidentally set $DOCKER_DEFAULT_PLATFORM, which can really mess things up. Report this. See 
* https://github.com/drud/ddev/issues/3971#issuecomment-1212398491
* Some errors have been obscured by `ddev debug test` running in ~/tmp. This changes to run in a sibling directory of hopefully a project.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve test_ddev.sh and ddev debug test by using docroot and adding more docker info [skip ci]

- .ci-scripts/nsis_setup.sh
nsis_setup.sh didn't work on Windows and didn't have clues about how to make it work
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Improve nsis_setup.sh to work on Windows [skip ci]

- docs/content/users/install/performance.md
> [docs] Add info about mutagen windows and settings things executable, fixes #4108

- docs/content/users/extend/customization-extendibility.md
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Give example of nginx snippet and remove statement that it will be removed

- docs/content/users/providers/index.md
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4139"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [DOCS] Add hint to hooks

- .gitpod/images/Dockerfile
- .goreleaser.yml
- docs/content/users/install/ddev-installation.md
- docs/content/users/install/shell-completion.md
- docs/content/users/topics/phpstorm.md
* #4112 
* #4113 
* #4125 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4133"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve apt packages and docs, fixes #4112, fixes #4113, fixes #4125

- docs/content/users/basics/faq.md
- docs/content/users/basics/how-ddev-works.md
- docs/content/users/install/ddev-installation.md
It is really hard to find information on that. Unfortunately I have no idea how else to do it. Maybe someone ™️ could improve this.
It is hard to find information on how to update DDEV
Add some information on it that helped me
Search on google for "update DDEV" or "update DDEV WSL2", etc...
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve DDEV update/upgrade instructions

- docs/content/users/basics/cli-usage.md
- docs/content/users/install/performance.md
The latest PR
* https://github.com/drud/ddev/pull/4153
had some docs changes that didn't stay that way. Fix them
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Mutagen debugging followup

- docs/content/users/quickstart.md
Saw the conversation on Discord and though it would be wise to drop a quick note in the docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add note about checking unused space when importing DBs [skip ci]

- docs/content/users/install/docker-installation.md
[docs] Use more initial colima disk allocation
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4171"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Use more initial colima disk allocation

- .goreleaser.yml
* #4168
No description in the debian package
Add description
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4174"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add description to nfpms, fixes #4168

- pkg/globalconfig/global_config.go
Try docker-compose 2.10.2
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4167"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Try docker-compose 2.10.2 to see if it works

- cmd/ddev/cmd/root.go
Add a missing period at the end of the sentence
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4172"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [output] Fix typo/needs period at end of output string in root.go

- docs/content/users/extend/customization-extendibility.md
[docs] Be clear about MySQL/MariaDB config enhancement
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4177"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Be clear about MySQL/MariaDB config enhancement

- docs/content/developers/building-contributing.md
Improve building/testing docs per experience of @khalwat and @bencroker 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve building/testing section

- .github/workflows/container-tests.yml
- .github/workflows/docscheck.yml
- .github/workflows/docspublish.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/linux-setup.sh
- .github/workflows/master-build.yml
- .github/workflows/tests.yml
* https://github.com/actions/runner-images/issues/6283
Add brew back into the path
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4224"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Add brew to path to fix missing brew

- pkg/ddevapp/config.go
PR for #4182
Before:
After: 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4202"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [output] improve custom config output in config.go

- docs/content/developers/building-contributing.md
Improve gitpod docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4238"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve gitpod PR checking docs to say to delete the sample project

- docs/content/developers/testing-docs.md
The developer docs don't seem to say clearly that you can do a docs PR (and review it) using just web browser.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4237"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Explain how to do docs PR in browser

- cmd/ddev/cmd/scripts/test_ddev.sh
The idea behind `ddev debug test` is it should be run in a directory sibling of a failing project. 
Make sure it is running in a project before switching to sibling directory
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4249"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev debug test should be run in a project directory [skip ci]

- version-history.md
Update version history for v1.21.2
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4270"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update version history [skip ci]

- docs/content/developers/testing-docs.md
[docs] Explain how to review PR using the checks
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Explain how to review PR using the checks

- .ci-scripts/nsis_setup.sh
Simple fix to nsis_setup.sh
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4315"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> nsis_setup.sh was broken, fix it [skip ci]

- docs/content/developers/buildkite-testmachine-setup.md
- pkg/ddevapp/ddevapp_test.go
I noted some followups to 
* https://github.com/drud/ddev/pull/4252
Here they are :)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor tweak followups for xdebug PR [skip ci]

- .spellcheckwordlist.txt
- docs/content/users/install/performance.md
* #4122 
Just warn people.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add docs warning about macOS Ventura and NFS

- docs/content/users/configuration/config_yaml.md
- docs/content/users/extend/database_types.md
- pkg/ddevapp/postgres/15/postgresql.conf
- pkg/nodeps/postgres_values.go
Postgresql 15 was [released on Oct 13, 2022](https://www.postgresql.org/about/news/postgresql-15-released-2526/#:~:text=October%2013%2C%202022%20%2D%20The%20PostgreSQL,most%20advanced%20open%20source%20database.)
So this adds support
Try out `ddev config --database=postgres:15`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4348"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add postgres:15 support

- docs/content/users/install/performance.md
[docs] Remove the mutagen.yml in troubleshooting
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4352"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove the mutagen.yml in troubleshooting

- docs/content/developers/release-management.md
- winpkg/chocolatey/ddev.nuspec
- winpkg/ddev.nsi
* #3962 
Starting to improve the related docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve developer docs discussing secrets and accounts for #3962 [skip ci]

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
#4220 
Instead of eliminating all the spaces, it just eliminates trailing + leading spaces.
See the issue.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Web environment variables - allow spaces, fixes #4220

- .github/workflows/colima-tests.yml
- .github/workflows/master-build.yml
- .github/workflows/tests.yml
Minor github workflow cleanup
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4358"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor github workflow cleanup

- docs/content/users/extend/customization-extendibility.md
[docs] Minor - new linter version insists on _ for emphasis
> [docs] Minor - new linter version insists on _ for emphasis

- cmd/ddev/cmd/scripts/test_ddev.sh
Improve `ddev debug test` by:
* Adding `ddev debug configyaml` in the broken project
> Get config.yaml in ddev debug test

- .spellcheckwordlist.txt
- cmd/ddev/cmd/commands_test.go
- docs/content/users/basics/cli-usage.md
- docs/content/users/basics/commands.md
- pkg/ddevapp/global_dotddev_assets/commands/host/querious
- pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
- pkg/ddevapp/global_dotddev_assets/commands/host/sequelpro
- Make sure you have Querious installed
- Run `ddev querious`
- Run `ddev querious [database]` to test opening a specific database.
Not quite sure how this could be tested in CI
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4429"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add `ddev querious` command

- docs/content/users/quickstart.md
Drupal 10 is nearer release; update docs to reflect that.
> [docs] Improve Drupal 10 quickstart

- .github/workflows/tests.yml
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/ddevapp/providerPlatform_test.go
* https://github.com/drud/ddev/pull/4525
got most things working, but the `Test*Pull` and `Test*Push` tests aren't yet running.
Hopefully get the various secrets in the right place.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make Test*Pull and Test*Push actually work

- docs/content/developers/building-contributing.md
Improve instructions about how to build/use HEAD
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4529"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve instructions about how to build/use HEAD

- pkg/globalconfig/global_config.go
Test to see if docker-compose 2.15.1 works properly
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4565"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change DockerCompose version to 2.15.1 to test

- docs/content/users/usage/troubleshooting.md
* https://github.com/drud/ddev/issues/2642#issuecomment-1400421270
* #4573
Mention getting rid of all docker containers
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4575"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add removing containers to port troubleshooting

- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/get.go
- go.mod
- pkg/ddevapp/compose_yaml.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/provider.go
- pkg/ddevapp/traefik.go
- pkg/globalconfig/global_config.go
- pkg/util/yaml_test.go
- pkg/util/yamltools.go
- vendor/modules.txt
* #4579 
* drud/ddev-platformsh#94
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4581"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix 'n' panic in ddev-platformsh, fixes #4579, fixes drud/ddev-platformsh#94

- .github/workflows/master-build.yml
- .github/workflows/pr-build.yml
- containers/ddev-dbserver/files/docker-entrypoint.sh
- docs/content/developers/building-contributing.md
- docs/content/developers/buildkite-testmachine-setup.md
- docs/content/developers/project-types.md
- docs/content/developers/release-management.md
- docs/content/developers/testing-docs.md
- docs/content/users/extend/customization-extendibility.md
- docs/content/users/quickstart.md
- docs/content/users/topics/hosting.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Checked for typos with LanguageTool.
Fix typos in docs and several scripts.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4603"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix typos, especially in developer docs

- cmd/ddev/cmd/exec.go
https://github.com/drud/ddev/issues/4634
Add hard line break
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4636"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix line break in `ddev exec` help, fixes #4634

- docs/content/users/install/performance.md
I failed to review PR status before pulling https://github.com/drud/ddev/pull/4646 , so these suggestions were lost.
> [docs] Fix docs suggestions from @mattstein

- docs/content/users/install/shell-completion.md
Snippet to add to .bash_profile was incorrect.
Corrected the incorrect snippet.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4638"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve bash-completion instructions

- .github/workflows/linux-build-setup.sh
- .github/workflows/pr-build.yml
pr-build has been failing at least half the time. It's probably an artifact of github actions trouble, or could be from upgrading to ubuntu 22.04 for the builds.
> [tests only] Try to make pr-build not fail all the time - github actions weirdness

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
> Bump all images for v1.21.5

- version-history.md
Release of v1.21.5 - update version-history.md
> [docs] Update version-history.md for release

- docs/content/users/extend/custom-commands.md
The title says it all....
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4735"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add ExecRaw annotation documentation.

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/ssh.go
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/craftcms.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/instrumentation.go
- pkg/ddevapp/list_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/provider.go
- pkg/ddevapp/wordpress.go
- pkg/dockerutil/dockerutils.go
- pkg/output/text_formatter.go
golangci-lint upgraded and apparently "revive" is revived, so there are new linting errors
Fix the linting errors
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4770"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Pacify lint for newly revived revive linter

- docs/content/users/install/docker-installation.md
Colima 0.5.4 has the ability to increase disk size.
Tell people about it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4798"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve colima disk allocation methods to show new increase capability

- .github/workflows/master-build.yml
- .goreleaser.yml
- docs/content/developers/buildkite-testmachine-setup.md
- docs/content/users/install/ddev-installation.md
* #4707
* #4628
Run through the Linux and cloud instructions
* https://github.com/ddev/ddev.com-front-end/pull/42
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4808"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Separate prerelease and stable fury channel, use ddev not drud, fixes #4707, fixes #4628 [skip ci]

- .buildkite/test.sh
The test.sh wasn't showing GOTEST_SHORT value
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4840"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Improve buildkite test.sh [skip ci]

- .buildkite/linux-amd64.yml
- .buildkite/linux-arm64.yml
- .buildkite/macos-m1.yml
- .buildkite/macos_container.yml
- .buildkite/macosdockerformac.yml
- .buildkite/test.sh
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2-docker-desktop.yml
- .buildkite/wsl2-docker-inside.yml
Upgrade docker login plugin for buildkite
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4845"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Upgrade docker login plugin for buildkite

- docs/content/users/extend/customization-extendibility.md
Minor docs improvements to customization-extensibility
> [docs] Minor improvements to customization-extensibility

- cmd/ddev/cmd/config-global.go
wrong example is shown
add correct example
---
a simple fix
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4897"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [TASK] Add correct example for ---web-environment-add

- docs/content/users/usage/commands.md
`ddev version` normally gives more output than people want. Give tip about `ddev --version`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Give tip about ddev --version in ddev version section

- docs/content/users/extend/customization-extendibility.md
Fixes doc:
* https://github.com/ddev/ddev/issues/4965
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4967"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix incorrect path for daemon file

- docs/content/users/extend/additional-hostnames.md
I pulled a PR with a spellcheck failure
Add backticks
> docs: fix spellcheck failure

- .buildkite/test.sh
- .buildkite/testbot_maintenance.sh
- pkg/versionconstants/versionconstants.go
[Mutagen 0.17.2](https://github.com/mutagen-io/mutagen/releases/tag/v0.17.2) has been released
Bump, see how it does.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5049"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump mutagen to 0.17.2

- pkg/ddevapp/ddevapp.go
The stop hooks are even called when the project is already stopped. This can have some negative side effects.
This patch changes the behavior to only call the stop hooks when the project is not stopped.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4877"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: avoid calling stop hooks if app is already stopped

- pkg/ddevapp/providerPantheon_test.go
Fixing a problem with this test I noted just a couple of not-so-big problems, trivial, but decided to commit.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5116"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: minor cleanup for TestPantheonDoMonthlyPush [skip ci]

- pkg/ddevapp/drupal/drupal10/settings.php
* #5121
Copied the content of the default.settings.php from a Drupal 10.1.0 install and updated the settings.php for the Drupal 10 project type. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: update settings.php for the Drupal 10 project type, fixes #5121

- README.md
I was reading about the 1.22.0-beta3 release and the bugfixes.
When I checked the homepage I noticed the heading: "Parital features".
This read as "features not fully developed".
Update title to be more positive: "Highlighted Features".
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: rename feature section in readme.md

- pkg/version/version.go
* #5142
The docker platform is a key piece of telemetry that we'd like to capture.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: make GetDockerPlatform() give more useful information, fixes #5142

- docs/content/users/install/phpstorm.md
Docs in phpunit section deserve Drupal 10 reference.
> docs: update outdated reference to Drupal 9 in phpunit section

- docs/content/users/usage/commands.md
Somehow this wasn't tested in the PR...
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: traefik capitalization incorrect

- docs/content/users/debugging-profiling/step-debugging.md
* #5248.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5249"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: step-debugging: add firewall tip at top, update Debug Configuration to use PHP Web Page, fixes #5248

- .spellcheckwordlist.txt
- docs/content/users/install/docker-installation.md
- docs/content/users/usage/faq.md
* https://github.com/ddev/ddev/issues/4858#issuecomment-1640158592
Add FAQ about how to migrate from one Docker provider to another.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5159"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add FAQ about migrating between Docker providers

- docs/content/developers/building-contributing.md
I can't ever remember how to examine data on amplitude.com
Write it down.
Read this section at https://ddev--5261.org.readthedocs.build/en/5261/developers/building-contributing/#examining-data-on-amplitudecom
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: explain how to examine data on Amplitude

- docs/content/users/quickstart.md
Only a small doc change for the Magento 2 quickstart guide.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5360"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: use a stronger password for Magento 2

- pkg/ddevapp/ddevapp_test.go
TestDdevXhprofEnabled is flaky
Run it a bit less
Stop running it on macOS/darwin
Also run TestDdevXdebugEnabled a bit less
> ci: try to make TestDdevXhprofEnabled flake less often

- cmd/ddev/cmd/config.go
- docs/content/users/configuration/config.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/errors.go
- pkg/ddevapp/schema.json
- pkg/ddevapp/templates.go
Attempts to enforce a specific ddev version using semver constraints
Fixes 
* #4630
> feat: add ddev_version_constraint to config.yaml, fixes #4630

- containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
- pkg/versionconstants/versionconstants.go
As described in #5409, this PR fixes this issue 
See #5409 - steps to reproduce to verify this PR
#5409
> fix: cleanup ddev-webserver bashrc variables, fixes #5409 

- docs/content/users/install/ddev-installation.md
* #5364 
Add the suggested line
> docs: fix missing manual instructions in WSL2 install, fixes #5364

- docs/content/users/extend/database-types.md
- docs/content/users/usage/database-management.md
- pkg/ddevapp/postgres/16/postgresql.conf
- pkg/ddevapp/templates.go
- pkg/nodeps/postgres_values.go
* #5335
Support postgres:16
Adds support
Use it, verify that it's 16 in the container
Make sure existing TestDdevAllDatabases does what it should with this, and ImportDB and ExportDB perhaps.
> feat: support postgres:16, fixes #5335

- pkg/ddevapp/poweroff.go
- pkg/dockerutil/dockerutils.go
- #5305
The change proposed in #5305 has the side effect: when a user downgrades DDEV without `ddev poweroff` (in the new version with #5305), the project cannot be restarted because the external project network cannot be removed automatically https://github.com/ddev/ddev/pull/5305#pullrequestreview-1668407006:
`time="2023-10-10T19:01:03+02:00" level=warning msg="a network with name ddev-junk_default exists but was not created by compose.\nSet external: trueto use an existing network" network ddev-junk_default was found but has incorrect label com.docker.compose.network set to "" Failed to restart junk: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-junk docker-compose -f /Users/rfay/workspace/junk/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 1', …
> feat: assign label to external docker network, for #5305

- docs/content/users/install/ddev-installation.md
> docs: add mkcert tip for Firefox Dev and Flatpak in Linux, fixes #5415

- .ci-scripts/bump_homebrew.sh
- .goreleaser.yml
I thought about this and I think this will work. I am unsure how to test it though.
I did edit the homebrew formulae locally and and tried adding the version and it works ok.
And out of curiosity, what does COMMIT= do as part of the make? 
Fixes #5433
> feat: use the stable release version as part of the HEAD version on homebrew, fixes #5433

- pkg/ddevapp/config_test.go
TestExtraPackages fails intermittently, apparently due to problems with the deb.sury.org CDN.
Don't use packages (php packages) from deb.sury.org, use mainstream packages instead.
There are many examples of this. For example, https://github.com/ddev/ddev/actions/runs/6619373200/job/17979758687?pr=5420, which has 
> [web 3/5] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.1-tidy:
> 4.040 W: GPG error: https://packages.sury.org/php bullseye InRelease: Splitting up /var/lib/apt/lists/packages.sury.org_php_dists_bullseye_InRelease into data and signature failed
> 4.040 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
There are also many …
> ci: improve TestExtraPackages to not use deb.sury.org

- pkg/versionconstants/versionconstants.go
Bump images to v1.22.4 for release.
> build: bump images to v1.22.4 for release

- docs/content/users/usage/troubleshooting.md
Disk space problems need to be mentioned in Troubleshooting section.
> docs: add info about disk space checking on wsl2

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/get.go
- pkg/ddevapp/ddevapp_test.go
> fix: remove unnecessary use of fmt.Sprintf

- pkg/versionconstants/versionconstants.go
Following docker-compose to v2.23.0, upgrading it, testing to make sure it works.
> build: bump docker-compose to v2.23.0

- .github/workflows/tests.yml
Add TestComposerCreateCmd to push-pull-test-platforms so that we can fully test #5499
> feat: add `TestComposerCreateCmd` to `push-pull-test-platforms`, tests #5499

- pkg/ddevapp/templates.go
> docs: Update list of project types in comments for config.yaml, fixes #5544

- .github/workflows/pr-artifacts-comment.yml
> fix: revert "build: bump actions/github-script from 6 to 7"

- docs/content/developers/building-contributing.md
- docs/content/users/usage/cli.md
- docs/content/users/usage/commands.md
Linter on master rejected use of Zip, wants ZIP
> docs: pacify linter on Zip vs ZIP

- pkg/versionconstants/versionconstants.go
Trying out docker-compose v2.23.3.
> build: bump docker-compose to v2.23.3

- docs/content/users/install/docker-installation.md
Noticed an incorrectly formatted markdown list.
> docs: fix indentation for Docker provider list

- docs/content/users/quickstart.md
@rpkoller had suggested this update for 
* https://github.com/ddev/ddev/pull/5489
but I forgot to do it before merging.
> docs: mention problems with shopware6 ddev composer create

- pkg/ddevapp/config.go
> fix: update outdated link for hostname, fixes #5604 [skip ci]

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Bump images to v1.22.6 for release.
> build: bump images to v1.22.6 for release

- .spellcheckwordlist.txt
- docs/content/developers/release-management.md
- docs/content/users/code-of-conduct.md
- docs/content/users/usage/faq.md
- mkdocs.yml
- winpkg/chocolatey/ddev.nuspec
- winpkg/ddev.nsi
* #4848 
@GuySartorelli points out that there are still references to the Localdev Foundation in docs, etc. 
Clean them up.
> docs: fix localdev foundation -> DDEV foundation, for #4848

- docs/content/users/usage/troubleshooting.md
Docs: Recommend using current stable version
> docs: Add using current stable version to troubleshooting section

- docs/content/users/quickstart.md
Reverts ddev/ddev#5716
This should be pulled when we're in final get-ready for v1.22.7
> docs: Revert "docs: temporarily revert docs on not needing --create-docroot"

- .buildkite/testbot_maintenance.sh
- docs/content/developers/buildkite-testmachine-setup.md
More learning about buildkite setup on wsl2. 
* https://github.com/ddev/maintainer-info/issues/1#issuecomment-1950457894
> docs: buildkite wsl2 setup learning

- .buildkite/test.sh
- .buildkite/testbot_maintenance.sh
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2-docker-desktop.yml
- .buildkite/wsl2-docker-inside.yml
We're having a little trouble with buildkite/macos cleanup, especially when it seems like Colima doesn't start right
Try to simplify the startup clean situation
* Make sure everything is stopped, then orbstack or Docker Desktop (or some docker provider) running
* Make sure we are on a context with docker running
> test: make sure buildkite leaves docker in sane setup

- .buildkite/test.sh
Just trying to continue to stabilize the buildkite builds and docker. Here we ran the Windows tests for the first time and it failed because $USER is not defined there.
> test: more buildkite work, windows not working [skip ci]

- docs/content/users/usage/faq.md
* https://github.com/ddev/ddev/pull/5924#pullrequestreview-1914966461
Fixes it
> docs: fix extraneous '#' in FAQ

- docs/content/users/usage/faq.md
The Docker-ce row has capialization inconsistent with other items on the table.
Follows capitalization of other items.
> docs: standardize capitalization of Docker-ce

- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/mods-available/deflate.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/mime.types
- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
- pkg/versionconstants/versionconstants.go
Fixes 
* #5937.
JavaScript files are no longer served with `Content-Encoding: gzip` response headers since DDEV v. 1.22.7 (#5661), due to the `js` extension being mapped to a new MIME type `text/javascript`. This affects both Nginx and Apache.
For Nginx, the `text/javascript` MIME type is added to `gzip_types` in `/etc/nginx/nginx.conf`.
For Apache, the `text/javascript` MIME type is added to `deflate.conf`.
Nginx:
1. `mkdir gzip-nginx-test && cd gzip-nginx-test && ddev config --auto --omit-containers db`
2. Add a file called `test.js` to the project. The file needs to be bigger than 256 bytes.
3. Confirm that the file is served with a `Content-Encoding: gzip` response header:
```shell
ddev exec curl -I --compressed https://gzip-nginx-test.ddev.site/test.js
```
> 
```shell
HTTP/2 200 …
```
> fix: Adds text/javascript MIME type to gzip_types and mod_deflate.conf, fixes #5937

- docs/content/users/usage/database-management.md
Explain how to delete database snapshots
> docs: explain how to delete snapshots

- pkg/ddevapp/ddevapp.go
* #5942 
Remove the old debug code. After the related issue was solved no problem was every reported with this.
> fix: remove debug code, fixes #5942

- docs/content/users/install/docker-installation.md
- docs/content/users/usage/faq.md
* Stop recommending colima because it has had many recent bumps on the road.
* Remove the "can increase disk size" section because it can't with VZ
> docs: stop recommending colima

- docs/content/users/extend/additional-services.md
It is not clear how to update add-ons.
Provide instructions for updating add-ons.
> docs: add instruction how to update add-ons

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/laravel.go
- pkg/ddevapp/magento.go
- pkg/ddevapp/silverstripe.go
We're about to release a major version and we want to make sure that the config overrides match current requirements.
Links are in the code for the changes to Laravel, Silverstripe, Magento1/Openmage
Try out the quickstarts for the changed items.
> fix: Update defaults for config overrides

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
It's time to bump/build images
> build: bump all images to v1.23.0

- docs/content/users/quickstart.md
a few changes based on the latest testing
> docs: Updates to the quickstarts

- docs/content/users/quickstart.md
- #6095
Follow up for quickstarts.
> docs: updates to the quickstarts, for #6095

- .github/devcontainers/src/install-ddev/devcontainer-feature.json
DDEV v1.23.0 is out
Pushes a new `ddev/install-ddev` package.
https://github.com/orgs/ddev/packages/container/package/ddev%2Finstall-ddev
> build: update devcontainer-feature.json for v1.23.0 release [skip ci]

- pkg/ddevapp/config.go
- #6122
Move the permission fix to the end of the generated Dockerfile for web container.
1. `echo 'RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confnew" --no-install-recommends --no-install-suggests php${DDEV_PHP_VERSION}-dev' > .ddev/web-build/Dockerfile`
2. `ddev restart`
3. The project should start without this error:
```
[23-Apr-2024 12:14:53] ERROR: Unable to create the PID file (/run/php/php8.2-fpm.pid).: Permission denied (13)
```
- #5898
> refactor: move php folder permission fix to the end, for #6122

- cmd/ddev/cmd/scripts/test_ddev.sh
- pkg/ddevapp/dotddev_assets/php/php-example.ini.example
Add a bit more detail to `ddev debug test`:
* host.docker.internal ping
* All customizations to current project
* add-ons installed in current project
Run `ddev debug test`
> fix: Add host.docker.internal and customizations to ddev debug test

- pkg/ddevapp/ddevapp.go
* #6249 
The new (formerly illegal) line at the top of some mariadb-dump files has
```
/*!999999\- enable the sandbox mode */
```
This breaks so many things all over the internet. It breaks `ddev import-db` and etc. And it breaks our TestDebugMigrateDatabase test in HEAD now that we are supporting the new versions of MariaDB, via the immediate fix in https://github.com/ddev/ddev/issues/6249
Remove the offending line from the import when importing via app.ImportDB. We already remove a couple of other lines, so might as well remove this one also.
* With a mariadb:10.11 project, `ddev debug migrate-database mysql:8.0`
* With a dump that contains the offending line, `ddev import-db`
The automated tests caught this problem, and they should be good enough with it.
It's worth considering adding …
> fix: ImportDB() and ddev import-db should remove new mariadb-dump line, for #6249

- docs/content/users/usage/faq.md
FAQ https://ddev.readthedocs.io/en/stable/users/usage/faq/#can-different-projects-communicate-with-each-other is a bit hard too read. Everything is in one paragraph
Use paragraphs, trying to improve readability
https://ddev--6238.org.readthedocs.build/en/6238/users/usage/faq/#can-different-projects-communicate-with-each-other
none
> docs: improve FAQ - communication between projects

- docs/content/developers/building-contributing.md
Tried my first steps with go, DDEV and Gitpod and was a bit confused which steps are needed exactly and which directory is correct.
https://ddev.readthedocs.io/en/stable/developers/building-contributing/#open-in-gitpod
- add description of first easy win for devs (change something, compile, success 🎉 )
none
> docs: improve contributing via gitpod

- docs/content/users/usage/commands.md
- markdown-link-check.json
Add details of what `debug migrate-database` does, to provide information and reassurance. The text is close to the prompt that the command returns.
> docs: Update commands.md to add detail for `debug migrate-database`

- docs/content/developers/project-types.md
This fixes the pointer to where a new project type should be added to.
> docs: update first step in project-types.md

- cmd/ddev/cmd/root.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/hooks_test.go
> feat: add `--skip-hooks` global flag to avoid running hooks, fixes #2129, fixes #6185

- docs/content/users/usage/faq.md
People often ask about whether to check in the .ddev directory.
Say yes, add to FAQ
> docs: Add FAQ about checking in .ddev

- .github/workflows/pr-artifacts-comment.yml
PR artifact comment is not created:
- https://github.com/ddev/ddev/actions/runs/9581560892
```
Unhandled error: TypeError: Cannot destructure property 'prNumber' of '(intermediate value)' as it is undefined.
```
I'm not sure what's wrong here.
I refactored the action to at least better understand the error.
> refactor: error handling for PR artifact comment [skip ci]

- docs/content/developers/buildkite-testmachine-setup.md
- docs/content/developers/scripts/windows_buildkite_start.ps1
- pkg/ddevapp/config_test.go
Because of having to rebuild tb-wsldd-05 I wanted to capture some of the things that needed to be updated. 
This PR is created against upstream/ddev so perhaps we'll find out whether the setup was complete.
> docs: revisit WSL Docker Desktop setup instructions

- pkg/versionconstants/versionconstants.go
A couple of Docker-Compose versions have gone by. See if we're still working with 2.28.1
> build: check docker-compose 2.28.1

- .spellcheckwordlist.txt
- docs/content/users/quickstart.md
* #6230
Review the rendered content at https://ddev--6256.org.readthedocs.build/en/6256/users/quickstart/#sulu
> docs: Initial draft for adding a quickstart for Sulu, fixes #6230

- .github/workflows/pr-artifacts-comment.yml
- README.md
- #6399
Changes `https://codespaces.new` to `https://github.com/codespaces/new`
> ci: update Codespaces link, fixes #6399 [skip ci]

- pkg/versionconstants/versionconstants.go
`docker-compose` v2.29.0 - https://github.com/docker/compose/releases/tag/v2.29.0
Try it out and see if it works for us.
> build: try out docker-compose v2.29.0

- docs/content/developers/buildkite-testmachine-setup.md
I did a new WSL2 Docker CE install the other day and wanted to capture more of the process.
> docs: improve WSL2 buildkite install instructions

- pkg/ddevapp/compose_yaml.go
In reviewing 
* #6501
I noted some old code that was built around a docker-compose anomaly from long ago
Remove the old adaptive code
Figure out the original bug and make sure it's properly handled now.
* https://youtrack.jetbrains.com/issue/WI-61976
* https://github.com/docker/compose/issues/8503#issuecomment-930969241
This will cause a conflict with #6501 so can go in after that one with modest work.
> fix: Remove obsolete code that fixed up absolute mountpoints

- pkg/versionconstants/versionconstants.go
New docker-compose release https://github.com/docker/compose/releases/tag/v2.29.3
Try using it.
> build: bump docker-compose to 2.29.3

- cmd/ddev/cmd/config_test.go
- docs/content/users/extend/database-types.md
- docs/content/users/usage/database-management.md
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/postgres/17/postgresql.conf
- pkg/ddevapp/templates.go
- pkg/nodeps/postgres_values.go
- #6566
Support `postgres:17`.
Adds support.
Use it, verify that it's 17 in the `web` and `db` container.
```
ddev config --database=postgres:17
```
Make sure existing TestDdevAllDatabases does what it should with this, and ImportDB and ExportDB perhaps.
> feat: support postgres:17, fixes #6566

- cmd/ddev/cmd/describe.go
- pkg/ddevapp/ddevapp.go
- #6661
Adds check for HTTPS in several places.
1. `mkcert -uninstall`
2. `sudo mv $(which mkcert) $(which mkcert)-backup`
3. remove `mkcert_caroot` from `~/.ddev/global_config.yaml`
4. `ddev start && ddev describe`
Before:
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Project: d11 ~/code/ddev/d11 http://d11.ddev.site                                                                    │
│ Docker platform: linux-docker                                                                                        │
│ Router: traefik                                                                                                      │
├──────────┬──────┬───────────────────────────────────────────────────────────────────── …
```
> fix: improve `ddev describe` output for HTTP only, fixes #6661

- .spellcheckwordlist.txt
- docs/content/users/quickstart.md
Add Quickstart Installation info via Composer for [Contao CMS](https://contao.org/en/) .
Review it here https://ddev--6674.org.readthedocs.build/en/6674/users/quickstart/#contao
> docs: Add Contao recipe to Quickstarts

- pkg/ddevapp/schema.json
add type cakephp to schema.json
> docs: Update schema.json to include cakephp project type

- docs/content/developers/project-types.md
- docs/content/users/configuration/config.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/templates.go
There is no enough information.
Adds it.
Adds missing `cakephp` in couple of places.
> docs: update how to create project types

- docs/content/developers/release-management.md
- docs/content/users/configuration/config.md
- docs/content/users/debugging-profiling/step-debugging.md
- docs/content/users/extend/additional-services.md
- docs/content/users/extend/custom-compose-files.md
- docs/content/users/extend/customizing-images.md
- docs/content/users/install/ddev-installation.md
- docs/content/users/install/ddev-upgrade.md
- docs/content/users/install/phpstorm.md
- docs/content/users/install/shell-completion.md
- docs/content/users/usage/faq.md
This PR is for a few obsolete paragraphs in docs, or other minor tweaks in docs.
> docs: Remove random docs stanzas and tweaks

- pkg/ddevapp/mutagen.go
I happened to notice this old mutagen warning message, so updated it.
> fix: Update old mutagen warning

- version-history.md
Update version-history.md for v1.24.0
> docs: Update version-history.md for v1.24 [skip buildkite]

- .spellcheckwordlist.txt
- docs/content/developers/maintainers.md
- docs/content/users/support.md
- mkdocs.yml
docs: remove twitter, add bluesky
Rendered at https://ddev--6799.org.readthedocs.build/en/6799/
> docs: Remove twitter, add bluesky [skip ci]

- pkg/ddevapp/config.go
It says `web-entrypoint.d` (but it should say `web-build`), and it doesn't show customizations for `db-build`:
```
$ ddev start
Starting d11... 
Using custom web-entrypoint.d configuration: [
/home/stas/code/ddev/d11/.ddev/web-build/Dockerfile.test
/home/stas/code/ddev/d11/.ddev/web-build/pre.Dockerfile
] 
Custom configuration is updated on restart.
If you don't see your custom configuration taking effect, run 'ddev restart'.
```
Fixes it:
```
$ ddev start
Starting d11... 
Using custom web-build configuration: [
/home/stas/code/ddev/d11/.ddev/web-build/Dockerfile.test
/home/stas/code/ddev/d11/.ddev/web-build/pre.Dockerfile
] 
Using custom db-build configuration: [
/home/stas/code/ddev/d11/.ddev/db-build/Dockerfile.xample
/home/stas/code/ddev/d11/.ddev/db-build/pre.Dockerfile.asd
] 
Custom …
```
> fix: show correct warning for Dockerfiles in `web-build` and `db-build`

- docs/content/users/quickstart.md
Initial draft for a draft for drupal cms. as a reminder the stability flag has to be removed after the 15th of january
https://ddev--6829.org.readthedocs.build/en/6829/users/quickstart/#drupal-drupal-cms
> docs: Add a quickstart for drupal cms

- .github/workflows/linux-setup.sh
- .github/workflows/selfhosted-upgrades.sh
- pkg/ddevapp/ddevapp_test.go
There were warnings about mkcert etc in recent PRs, so trying to clean up a bit
We don't need the NFS setup any more
The ngrok setup was out of date.
> test: Minor updates to linux-setup.sh

- README.md
"Maintained" badge on readme is showing unmaintained.
> docs: Update maintained date to 2025 in README [skip ci]

- docs/content/users/extend/custom-commands.md
- #6752
The documentation was not updated.
Updates it.
> docs: replace GOOS and GOARCH for a DDEV_ alternative, for #6752

- docs/content/users/quickstart.md
- docs/tests/common-setup.bash
- docs/tests/drupal.bats
This PR is adding tests for Drupal Core and Drupal CMS, updates the drupal quickstarts layout wise and makes a change to the common setup function. 
Rendered quickstart: https://ddev--6893.org.readthedocs.build/en/6893/users/quickstart/#drupal
about the tests: i've added a fifth test that is currently commented out. it requires a creation of a test repo in the ddev org on github first (https://github.com/ddev/test-drupal.git would be the same naming pattern used for backdrop). the zip based test for drupal cms contains one additional line that renames the directory. problem is the zip file contains a folder called drupal-cms. due to the fact that launc-drupal-cms.sh contains a ddev config command that makes the project name drupal-cms in consequence and that way the teardown same sas the …
> test: Add bats test coverage for Drupal Core and Drupal CMS quickstarts

- docs/content/users/topics/hosting.md
Docs: Missed indentation in Let's Encrypt docs
> docs: Fix formatting for staging server in Let's Encrypt [skip ci]

- docs/content/developers/building-contributing.md
- https://github.com/ddev/ddev/issues/6938#issuecomment-2616045373
@RoelsL was not sure which binary to use for testing a PR on WSL2.
Adds an example for Linux and WSL2.
https://ddev--6942.org.readthedocs.build/en/6942/developers/building-contributing/#testing-a-pr
> docs: add more examples for testing a PR

- .github/workflows/quickstart.yml
- docs/content/developers/quickstart-maintenance.md
- mkdocs.yml
- #6880 
Add to developer docs on what has to be done on a quickstart
https://ddev--6888.org.readthedocs.build/en/6888/developers/quickstart-maintenance/
> docs: Add info on maintaining and testing quickstarts, fixes #6880

- .vscode/launch.json
- cmd/ddev/cmd/config.go
- docs/content/users/extend/customizing-images.md
- pkg/ddevapp/ddevapp_test.go
I noticed some places with incorrect spelling.
Fixes the spelling.
> fix: correct spelling for Xdebug

- pkg/ddevapp/list.go
- pkg/ddevapp/router.go
- pkg/globalconfig/global_config.go
```
❯ ddev list
┌──────────┬─────────┬──────────────────────┬────────────────────────┬─────────┐
│ NAME     │ STATUS  │ LOCATION             │ URL                    │ TYPE    │
├──────────┼─────────┼──────────────────────┼────────────────────────┼─────────┤
│ ddev.com │ stopped │ ~/code/ddev/ddev.com │                        │ php     │
├──────────┼─────────┼──────────────────────┼────────────────────────┼─────────┤
│ Router   │ stopped │ ~/.ddev              │ http://127.0.0.1:10999 │ traefik │
└──────────┴─────────┴──────────────────────┴────────────────────────┴─────────┘
```
We don't need the router URL if it's stopped.
Don't show the URL for the `stopped` status.
```
❯ ddev list
┌──────────┬─────────┬──────────────────────┬─────┬─────────┐
│ NAME     │ STATUS  │ LOCATION …
```
> fix: do not show router URL in `ddev list` if it's stopped

- docs/content/users/usage/troubleshooting.md
They'll probably have to _invent_ an award for my heroism. 😉
> docs: Fix niggling code sample inconsistency in `troubleshooting.md`

- docs/tests/grav.bats
> test: grav quickstart bats tests

- docs/tests/ibexa.bats
> test: quickstart bats test for ibexa

- docs/tests/moodle.bats
> test: quickstart bats test for moodle

- docs/tests/pimcore.bats
> test: bats test for pimcore quickstart

- docs/content/users/quickstart.md
- docs/tests/shopware.bats
> test: shopware quickstart bats test

- docs/tests/joomla.bats
> test: joomla quickstart bats test

- docs/tests/joomla.bats
> test: add more joomla specific tests [skip buildkite]

- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils_test.go
* #472 
It's been a long time. This rarely causes trouble, but I spent a few hours with it today on #7007 so maybe it's time to fix it!
> test: run ClearDockerEnv() before tests, fixes #472

- docs/content/users/quickstart.md
- docs/tests/sulu.bats
locally the tests are not working because they require a mutagen sync but the tests work on github actions already. the not working local tests are being fixed with https://github.com/ddev/ddev/pull/6994 (tested the artifact with the tests that failed before locally and work now with the artifact in PR6994)
> test: bats test for the sulu quickstart

- docs/content/users/quickstart.md
- docs/tests/magento.bats
- docs/tests/magento2.bats
This is a new Quickstart test for Magento2
@rpkoller created it; I tried to fix it so we have the needed composer keys in there
> test: Add quickstart test for magento2 (by @rpkoller) [skip buildkite]

- docs/content/users/quickstart.md
- docs/tests/joomla.bats
> test: use a more robust approach downloading the latest zip file (by @stasadev)

- docs/content/users/quickstart.md
- docs/tests/cakephp.bats
…ment
bats test for the composer quickstart for cakephp. i'Ve omitted the git based for now since there is no actionable git repo to build a bats test around.
> test: Bats test for CakePHP composer quickstart

- docs/tests/silverstripe.bats
stuck to the pattern of adding the run command as a comment. best when all bats tests are in to unify everything at once.
> test: adding silverstripe quickstart bats test

- docs/content/users/quickstart.md
- docs/tests/craftcms.bats
adding a bats test for the composer based quickstart (only remaining question if the approach for setting up the site used on the test should be used on the quickstart as well - asked @mandrasch over in discord)
> test: craftcms bats test

- docs/content/users/quickstart.md
- docs/tests/statamic.bats
> test: bats test for Statamic Composer quickstart [skip buildkite]

- docs/content/users/extend/custom-compose-files.md
Example has a wrong name.
Fixes it.
See https://ddev--7130.org.readthedocs.build/en/7130/users/extend/custom-compose-files/#third-party-services-may-need-to-trust-ddev-webserver
> docs: fix example file name

- docs/content/users/providers/acquia.md
- docs/content/users/providers/pantheon.md
- docs/content/users/providers/platform.md
- docs/content/users/providers/upsun.md
- pkg/ddevapp/dotddev_assets/providers/acquia.yaml
- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
- pkg/ddevapp/dotddev_assets/providers/platform.yaml
- pkg/ddevapp/dotddev_assets/providers/upsun.yaml
- #7177
Adds a tip.
Review:
https://ddev--7183.org.readthedocs.build/en/7183/users/providers/acquia/
https://ddev--7183.org.readthedocs.build/en/7183/users/providers/pantheon/
https://ddev--7183.org.readthedocs.build/en/7183/users/providers/platform/
https://ddev--7183.org.readthedocs.build/en/7183/users/providers/upsun/
> docs: add tip on using per-project API tokens for hosting providers, fixes #7177

- docs/content/users/quickstart.md
- docs/tests/magento2.bats
- #7191
See https://ddev--7192.org.readthedocs.build/en/7192/users/quickstart/#magento-2
> test: fix for magento2 quickstart and bats test, fixes #7191

- docs/content/developers/buildkite-testmachine-setup.md
I was rebuilding tb-wsl-14 and had just a little trouble, fixed here.
> docs: Improve buildkite windows setup script run [skip buildkite]

- pkg/ddevapp/ddevapp_test.go
- #7109 
Need at least a rudimentary test of upload_dirs
Adds TestUploadDirs
> test: Add TestUploadDirs to verify upload_dirs, fixes #7109

- cmd/ddev/cmd/commands.go
Sometimes I copy and paste global commands, edit them slightly, and then I don't understand why they don't work:
```
$ cp ~/.ddev/commands/host/self-upgrade ~/.ddev/commands/host/self-upgrade2
$ ddev self-upgrade2
Error: unknown command "self-upgrade2" for "ddev"
Did you mean this?
self-upgrade
self-upgrade
Run 'ddev --help' for usage.
```
For:
- #6293
- Adds a duplicate warning for `## Usage:`
- Adds a file path to all warnings for a better understanding of where they are coming from.
```
$ cp ~/.ddev/commands/host/self-upgrade ~/.ddev/commands/host/self-upgrade2
$ ddev self-upgrade2
Command 'self-upgrade2' cannot have usage 'self-upgrade' because it is already in use by command 'self-upgrade', skipping /home/stas/.ddev/commands/host/self-upgrade2
Error: unknown command "self-upgrade2" …
```
> fix: add warning about duplicate usage for global commands, for #6293

- containers/ddev-xhgui/var/www/xhgui/config/config.php
- pkg/versionconstants/versionconstants.go
- https://github.com/perftools/xhgui/pull/556
- Updates xhgui config.
- Adds link to upstream config file.
Automated testing should be enough.
> feat: update xhgui config, add link to upstream file

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- #7246 
Fix up `GetWebContainerDirectHTTPPort` and `GetWebContainerHTTPSPublicPort` to preferably use `app.GetPublishedPortForPrivatePort("web", 80)` and `app.GetPublishedPortForPrivatePort("web", 443)`, and fall back only for generic type projects.
Have ngrok set up and authenticated as per https://ngrok.com/docs/getting-started/
```
mkdir share_test
cd share_test
ddev config --project-type=php --omit-containers=db
```
Add `web_extra_exposed_ports` to `.ddev/config.yaml`:
```
web_extra_exposed_ports:
- name: vite
container_port: 5173
http_port: 5172
https_port: 5173
```
```
ddev start
ddev share
```
Verify that `ddev share` maps to the expected port, instead of the web_extra_exposed_ports it did before.
Additionally, test the same with …
> fix: replace broken http and https port lookup, fixes #7246

- README.md
@rfay shared this AI managed resource https://deepwiki.com/ddev/ddev
And we can enable weekly auto refresh for it by adding a badge to our README.md
Adds more badges.
https://github.com/stasadev/ddev/blob/20250513_stasadev_deepwiki_badge/README.md
> docs: add ddev.com, addon registry, last commit, DeepWiki badges to README.md

- docs/content/users/quickstart.md
- #7231
I searched for `composer create` and found another place that wasn't updated.
> docs: use `composer create-project` in Magento 2 quickstart, for #7231

- docs/content/users/quickstart.md
Fixes indentation.
https://ddev--7314.org.readthedocs.build/en/7314/users/quickstart/#processwire
> docs: fix indentation for code block

- pkg/ddevapp/templates.go
The ngrok Agent Configuration link, https://ngrok.com/docs/ngrok-agent/config, currently displays a "Page not found" error.
This PR updates the link to Agent Configuration for version 3 (current). 
1. Link should display in `config.yaml`.
2. Link should navigate to Agent Configuration page.
> docs: update ngrok link

- docs/content/users/debugging-profiling/xhprof-profiling.md
The original instructions were not extensive enough. Copied more detailed instructions from https://ddev.com/blog/xhgui-feature/
- #7376
https://ddev--7377.org.readthedocs.build/en/7377/users/debugging-profiling/xhprof-profiling/#simplest-xhprof-usage-with-xhgui
> docs: improve xhgui documention, fixes #7376

- docs/content/users/providers/pantheon.md
- docs/content/users/usage/developer-tools.md
- #7352 
Adds links to https://ddev.com/blog/ddev-bundled-tools-using-custom-versions/
- https://ddev--7353.org.readthedocs.build/en/7353/users/providers/pantheon/#pantheon-quickstart
- https://ddev--7353.org.readthedocs.build/en/7353/users/usage/developer-tools/#ddev-and-terminus
> docs: add Terminus downgrade tips, fixes #7352

- go.mod
- go.sum
- vendor/github.com/spf13/cobra/.golangci.yml
- vendor/github.com/spf13/cobra/README.md
- vendor/github.com/spf13/cobra/SECURITY.md
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/completions.go
- vendor/modules.txt
- #7361
Uses latest commit with fix.
Before:
```
$ ddev -h
...
Additional help topcis:
...
```
After:
```
$ ddev -h
...
Additional help topics:
...
```
> build: bump github.com/spf13/cobra to latest commit, fixes #7361

- .github/workflows/pr-check.yml
- #7513
Unable to start message with uppercase or quote.
Unable to have `, fixes ddev/ddev-mongo#24`
Allow at the PR message start:
- uppercase letter
- `'` single quote
- `"` double quote
- ` backtick
It’s practically impossible to specify all allowed characters, so I added `.*` in the middle. This made `(?:, (?:fixes|for) #\d+)*` effectively useless, but I kept it as a hint that the message can end with these.
```
^(build|chore|ci|docs|feat|fix|perf|refactor|style|test)(\([a-z][a-z0-9-]*\))?!?:\s(?!.* )[A-Za-z''"`].*[A-Za-z0-9\]\)''"`](?:, (?:fixes|for) #\d+)*$
```
https://regex101.com/r/9HTbYi/7
```
ci(pr): testing pr-checker.yml
feat: Add something [skip ci]
feat: add something (extra)
fix: correct the bug
docs(readme): update installation guide
feat: add new_feature to enhance …
```
> ci(pr-check): loosen start and middle rules for message [skip ci], for #7513

- pkg/ddevapp/ddevapp_test.go
TestDdevExportDB started failing today on HEAD.
It did an export of the database, and then checked to see that "ump complete" was in the last "line", which it turned out was assumed to be 80 characters. I don't know what the \unrestrict might mean.
But as of today, that dump seemed to have exceeded 80 characters:
```
ALTER TABLE ONLY public.users
ADD CONSTRAINT users__user_field__uuid__value__key UNIQUE (uuid);
--
-- PostgreSQL database dump complete
--
\unrestrict 9xW0ONzgZT8GfP5CfMcEmH3BHvMExf5nWzLJEY2XQaFT2mTpzYbYbJ665LBa4aF
```
* the `readLastLine()` was silly in its wrong naming (didn't get last line) and in the fact that it didn't take an arg for how much to look at. (This function is only used here)
* The TestDdevExportDB now looks at 120 characters using the updated function.
* …
> fix(testddevexportdb): postgres:14 output dump statement was suddenly more than 80 characters from end

- .gitignore
- CLAUDE.md
- https://github.com/ddev/ddev/pull/7586#issuecomment-3254154937 (Number 10)
Copilot correctly pointed out that CLAUDE.md and gitignore changes don't belong in 
* https://github.com/ddev/ddev/pull/7586
Do those here.
> build: gitignore/CLAUDE.md nitpicks [skip ci]

- cmd/ddev/cmd/scripts/test_ddev.sh
We don't expect an alternate global ddev dir sometimes, and it can confuse us if that is changed.
* Point out XDG_CONFIG_HOME
* Explicitly state global dir
* Update one place that naively used `~/.ddev`
* Try `ddev debug test` with and without XDG_CONFIG_HOME
> feat: update ddev debug test to emphasize global ddev dir [skip ci]

- AGENTS.md
- cmd/ddev/cmd/debug-dockercheck.go
- cmd/ddev/cmd/scripts/test_ddev.sh
- cmd/ddev/cmd/utility-dockercheck.go
- cmd/ddev/cmd/utility-dockercheck_test.go
- pkg/dockerutil/requirements.go
- pkg/dockerutil/requirements_test.go
- #7672 
Some people had trouble with v1.24.8 because of misconfigured buildx or authentication plugins
* Add check for buildx (and use it)
* Add authentication plugin check
* Add new tests
* `ddev debug test` minor update to use this
Run `ddev debug dockercheck` with a variety of problems
Assisted by Claude Code
> feat(dockercheck): improve ddev ut dockercheck, fixes #7672
