- docs/index.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/config.yaml
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/linkedconfigs/config.----.yaml
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/linkedconfigs/config.0.yaml
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/linkedconfigs/config.0.yml
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/linkedconfigs/config.1.yaml
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/linkedconfigs/config.a.yaml
- pkg/ddevapp/testdata/TestConfigLoadingOrder/.ddev/linkedconfigs/config.b.yaml
- pkg/ddevapp/testdata/TestWriteConfig/.ddev/config.extra.yaml
- pkg/ddevapp/testdata/TestWriteConfig/.ddev/config.yaml
- pkg/globalconfig/global_config.go
We have never, ever used the APIVersion in config.yaml or global_config.yaml
The version check annoys people and doesn't help in any way.
Remove the APIVersion and related version check from config.yaml and global_config.yaml
> Remove APIVersion from global config and project config, fixes #2116, fixes #1713

- docs/users/extend/customizing-images.md
- pkg/ddevapp/config.go
The inclusion of `ARG BASE_IMAGE=...` was confusing to people. ddev always provides the BASE_IMAGE arg, so it does not need a default (and the default does not need to be maintained)
> Stop providing default to BASE_IMAGE arg in Dockerfile.example, fixes #2155

- pkg/ddevapp/templates.go
The description in the default configuration file does not refelect the description in the current documentation. See: https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/
Updated the description.
Don't think it is required. Only adjusted text.
Don't think it is required. Only adjusted text.
// 
//
> Updated omit_containers description

- .circleci/generate_artifacts.sh
Quicksprint needs MariaDB 10.3 for Drupal 9. It should be added to the images tarball.
After CircleCI build, ssh into build and run the generate_artifacts.sh script with BUILD_IMAGE_TARBALLS=true. (Otherwise, this won't be run that way until full release)
Verify that the 10.3 docker image is bundled in the tarball.
> Add mariadb 10.3 image to docker tarball, fixes #2118

- cmd/ddev/cmd/delete-images.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
As per #2134, we need to make sure that -built images (<imagebase>-<projectname>-built) get deleted on ddev stop --remove-data and elsewhere
Delete them. 
`ddev delete` a project make make sure it's -built image is gone. `docker images | grep built` will show remaining -built images.
Tests are improved to check this.
> Remove -built image when deleting project, fixes #2134

- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer_test.go
- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config-global_test.go
- cmd/ddev/cmd/sequelpro.go
- docs/users/extend/config_yaml.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/globalconfig/global_config.go
People want to set nfs_mount_enabled globally, not per project. Most people like it that way.
* Enabled nfs_mount_enabled in global_config.yaml
* This also fixes a longstanding problem with global value of omit_containers leaking into per-project config.yaml, #1456
> Allow nfs_mount_enabled globally, fixes #1985, fixes #1456

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- docs/users/extend/config_yaml.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
It is extremely difficult to experiment with new methods of getting files into the web container. docker-compose doesn't allow _removing_ things in the base docker-compose file, so any attempt to override the mount point, whether or not a volume is mounted at all, etc doesn't actually lead to success.
I added a new option to config.yml that lets people just opt out of the web mount in question. Since this is realistically the only mount people are going to care about getting rid of for testing new file sync methods, I didn't take it further than that.
Add `no_project_mount: true` to a project config.yaml, then start the project. Inside the web container, you should see /var/www/phpstatus.php, /var/www/html/index.html, and /var/www/html/docroot/ which should contain the default php files …
> Add no_project_mount option to omit the web mount for app code (experiment with mutagen)

- pkg/ddevapp/config.go
In an earlier architecture/code we couldn't handle a project directory which had glob characters in its path. That problem no longer exists, so this removes the error about it. 
docker-compose.*.yaml with wildcard characters: Verify that the described failure case is resolved. (Create dir named ~/tmp/[Local]/j2 and try ddev config)
See https://github.com/drud/ddev/issues/2049#issuecomment-579255858
> Remove the forced error if glob characters in project path

- README.md
- cmd/ddev/cmd/composer-create.go
- docs/users/cli-usage.md
This is inspired by and replaces @alesrebec's #2175 - Thanks for stimulating the thinking @alesrebec!
An eccentricity of `ddev composer create` has been the need to run an extra `ddev start` after it finishes. This is because the create-project has just created an entirely new code structure, and ddev hasn't had the chance to create settings files. (ddev creates settings files on start and config)
* Run app.Start() at the end of the `ddev composer create` process to get the settings files created.
* Change the docs to have just one start (it's actually unnecessary but instructional)
* Other minor docs changes. 
* Run through the Drupal 8 and Drupal 9 Quickstarts and verify.
> Do app.Start() after `ddev composer create`

- cmd/ddev/cmd/restart_test.go
- pkg/ddevapp/ddevapp.go
- pkg/nodeps/utils.go
Testing in https://github.com/drud/ddev/issues/2174 showed that although IsInternetActive() is working correctly with flaky internet, hostnames might not be added to /etc/hosts in that situation, and we'd think they'd want to be.
If !IsInternetActive(), we'll go ahead and add the hostnames.
I tested this by setting a network conditioner on Parallels Windows 10 instance with a 1000ms delay on incoming. With the delay, it now adds hostnames rather than relying on net.Lookup.
> Don't check host lookup if not IsInternetActive()

- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
#2180 points out that the generated .ddev/.gitignore has the wrong files gitignored in .ddev (.ddev-docker-compose-*)
Make it right.
Follow pattern in https://github.com/drud/ddev/pull/2182#issuecomment-614796590 and make sure it works right.
Adds TestConfigGitignore, which discovered another problem here.
> Fix incorrect .gitignore contents, fixes #2180

- cmd/ddev/cmd/delete.go
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
In testing v1.14 I noticed that the volume deletion of persistent third-party volumes is done, but there's no info to the user about this.
Add the info to the user
Improves some other output at delete time.
1. Create a project with some docker-compose stuff (use solr)
2. start it
3. Stop it. View output. You should see explicit info about volumes being deleted
> Improve output from ddev delete to show volume deletion, etc.

- .circleci/linux_circle_vm_setup.sh
- pkg/version/version.go
Bump containers to v1.14.0 in preparation for v1.14.0 release
> Bump containers to v1.14.0

- pkg/ddevapp/instrumentation.go
It would be nice to detect unique project IDs in segment. This adds a hashed project ID (server ID + project name) to the reporting
Do an action. Watch segment for the event. Look at the ProjectID hash.
> Add ProjectHash to segment reporting, fixes #2193

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/php.go
#2200 points out that with a  project of type 'php', the .ddev/.gitignore does not get created/managed on `ddev start`. It ought to update.
Add post-start hook for 'php' project type to update.
1. Create a project of type 'php'
2. Edit the .ddev/.gitignore
3. `ddev start`
Your edits should be gone.
> Add creation of .ddev/.gitignore to post-start actions on php project, fixes #2200

- docs/users/cli-usage.md
- docs/users/extending-commands.md
A couple of late entries for 1.14 docs:
* Add quotes around `ddev composer create` examples that use "^", since that's a reserved character on cmd in Windows
* Improve yaml presentation by using ` ```yaml` as the yaml type on a few problematic stanzas, fixing #2203
> Minor docs fixes, fixes #2203 [skip ci][ci skip]

- docs/users/extend/customizing-images.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/nodeps/values.go
#2092 points out that once again, upstream configuration changes broke use of `webimage_extra_packages`. In this case it was PHP 7.4.5 that did it, and it shipped with a new configuration.
The basic problem though was that ddev was automatically accepting new config, when it should be using existing config.
Use configold not confignew
Create a php7.4 project
Add `webimage_extra_packages: [php7.4-ldap]` to the config.yaml
ddev start
If it succeeds, it's working
OP #2092
This has to be backported to v1.13.1 as well.
> Use debian existing package conf, not new conf, fixes #2092

- docs/users/cli-usage.md
This patch also tries to solve issue #2203 for the bash commands in this area.
Today we released a new LTS version of the TYPO3 CMS.
The version constraint is updated to the new LTS.
> [DOCS] Update TYPO3 quick start to new LTS

- pkg/version/version.go
This just updates the build of the web container to get the latest packages. Right before v1.14.0 was released, and right after the docker images were prepared, there was a set of PHP updates. Those make it really slow to add extra packages.
> Bump ddev-webserver to v1.14.1, updating to latest PHP versions

- pkg/ddevapp/templates.go
fixes a small typo
there is an extra { on the port for "phpmyadmin_https_port" in the config.yaml
remove the the extra "{"
> remove { on phpmyadmin_https_port

- cmd/ddev/cmd/a.go
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/start.go
- pkg/ddevapp/instrumentation.go
- pkg/globalconfig/global_config.go
At least one recreation scenario for #2065  is described in https://github.com/drud/ddev/issues/2065#issuecomment-624437369 - the opt-in request was made *after* the app data was collected, so at the time of collection, the opt-in flag was false. 
In addition, SetInstrumentationAppTags() was not setting the tags if InstrumentationOptIn was false, which was unnecessary.
* Collect the app/tag information regardless of the setting (of course we don't send it if it's turned off)
* Do the opt-in earlier than the app creation
* This also moves a failsafe to prevent superuser execution to an earlier and more appropriate spot. 
* Delete the `instrumentation_opt_in` and `last_started_version` lines in ~/.ddev/global_config.yaml
* `ddev start`
* Accept the opt-in
* Review what's sent to segment. It …
> Fix segment events without app data, fixes #2065 (again)

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/instrumentation.go
- pkg/ddevapp/instrumentation_test.go
A one-character typo caused the phpmyadmin_https_url to be included in segment data, and that shouldn't be included. Thanks to @unn for noticing this.
* Fix it, don't send phpmyadmin_https_url
* Any app.Describe() tag with "url" in it doesn't get sent
* Add TestSetInstrumentationAppTags to ensure these things happen right
Watching segment debug data, do something. Look at results. There should be no phpmyadmin_https_url (or any other URLs)
* Added TestSetInstrumentationAppTags and make sure that no URLs are included. Make sure that ignoredProperties is handled as expected. 
This is a candidate for v1.14.2 point release
> Fix typo phpmyadmin_http_url -> phpmyadmin_https_url

- containers/ddev-webserver/files/etc/nginx/nginx-site-drupal9.conf
- containers/ddev-webserver/files/etc/nginx/nginx_drupal9.conf
- containers/ddev-webserver/test/containertest.sh
- pkg/version/version.go
The drupal9 configuration in ddev-webserver was left out in v1.14; as a result, the default configuration was in use. It seemed to work for everything, but it needs its own configuration. 
The explicit test in the container was also left out, and that's how this was discovered, when working on https://github.com/drud/ddev-images/pull/3
Add the Drupal9 explicit nginx config (just a copy of drupal8)
This probably requires a release v1.14.2
> Provide explicit Drupal9 nginx configuration

- .buildkite/testbot_maintenance.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
This simply updates the test runner scripts to use new versions of bats-core and ddev, etc.
It only affects test runners.
> Update various packages on testbots and circleci (tests only)

- pkg/ddevapp/ddevapp.go
#2217 pointed out that v1.14.0 (deliberately) disallowed docker-compose add-ons of the format docker-compose.*.yml. This seems unnecessary. 
Put it back to allow docker-compose.*.yml
* Test add-on 3rd party services with `docker-compose.*.yml` as well as `docker-compose.*.yaml`
* Verify that a mixture of yaml and yml files works out OK.
* Verify that no additional files are picked up with this glob pattern
* Review the code to make sure it does what's expected
* What happens when there is a docker-compose.override.yaml and also a docker-compose.override.yml ?
> Allow docker-compose.*.yml as well as docker-compose.*.yaml, fixes #2217

- pkg/dockerutil/dockerutils.go
For Docker Toolbox we had a path massaging function that changed C:\Users\rfay\workspace to //c/Users/rfay/workspace. This // really helped toolbox work.
But now in Docker 2.3.0.1 (edge) and 2.3.0.2 (released today as stable) it doesn't work any more on Docker Desktop for Windows.
Only add the extra slash on the front when running Docker Toolbox.
`ddev auth ssh` with Docker Desktop for Windows 2.3.0.2
> Only use //c on Docker Toolbox, not Docker Desktop for Windows

- pkg/version/version.go
It's time for a point release, and ddev-webserver needs to be bumped to v1.14.2. The docker image has already been pused.
> Bump ddev-webserver to v1.14.2 in preparation for release

- containers/ddev-dbserver/test/basic_database.bats
- containers/ddev-dbserver/test/custom_config.bats
- containers/ddev-router/test/containertest.sh
- containers/ddev-webserver/test/containertest.sh
Docker Desktop for Windows 2.3.0.1+ stopped accepting the classic path workaround //c/...
This meant that git-bash and all its friends would rewrite /c to C:\Program...
Which meant that nothing worked. 
Work around all this mess in a new way.
> Fix up ddev-dbserver tests to work with docker 2.3.0.1+ - tests only

- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/pause_test.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop_test.go
- pkg/ddevapp/ddevapp_test.go
Due to apparent problems with cache flushing on Docker Desktop For Windows, we have some tests are intermittently fail there.
The Docker for Windows issue is https://github.com/docker/for-win/issues/6512 (probably). 
Basically, even though a container with a bind mount gets shut down, it does not give up control of the host-side directory, causing these tests to fail. Probably a longer sleep would make it work, but it's hard to tell how much longer.  
Skip these tests on Windows. There's nothing particularly valuable in executing these on Windows I don't think.
> Skip tests that are too difficult for Windows Docker (tests only)

- .circleci/config.yml
Reorganization of CircleCI contexts for security reasons requires changing the circle test setup.
This affects only tests; 
* Use new context with only ddev-local stuff in it
* Configure CircleCI to not pass secrets to forked builds.
> Change the context we're using since it's now specific to ddev-local (tests only)

- Makefile
The Windows installer was providing version 1.3 of mkcert; this shouldn't really cause trouble, but 1.4.1 is current, and it has the --version command, which helps in so many ways.
Bump the version.
> Update version of mkcert, specified in Makefile

- .githooks/pre-push.allchecks
- Makefile
- build-tools/build_update.sh
- build-tools/makefile_components/base_build_go.mak
#2253 points out that `make staticrequired` requires lots of workstation-installed software, and it shouldn't be like that. 
* Update golang via build-tools and golang-build-container
* mkdocs and markdownlint-cli are now in the golang-build-container
* Change the githooks and `make staticrequired` to just use `make staticrequired` 
`make staticrequired` - no local installs required beyond go and docker.
> `make staticrequired` shouldn't require all kinds of local installs, fixes #2253

- cmd/ddev/cmd/root.go
#2222 points out that life would be a lot easier for new users if `ddev config` checked for docker before doing things. 
Don't skip the docker check for `ddev config`
Try `ddev config` without docker running.
> Check for docker on ddev config, fixes #2222

- build-tools/README.md
- build-tools/makefile_components/README.md
- docs/developers/building-contributing.md
There haven't been adequate instructions in the developer docs for new devs. 
* Improve the docs
* Also fixes minor formatting problems in build-tools
> Improve developer build instructions [skip ci][ci skip]

- pkg/ddevapp/providerPantheon.go
#2241 points out the common problem that if people haven't done a `ddev auth pantheon` then they get a cryptic message on `ddev config pantheon` and `ddev pull` that doesn't say "hey, do a `ddev auth pantheon`"
Improves that message to "unable to get Pantheon environments for project %s - Have you authenticated with `ddev auth pantheon`? Does the ddev project name match the pantheon project name?"
Start a pantheon project without doing a `ddev auth pantheon`. If you need to kill off the existing authentication, `ddev exec rm -r /mnt/ddev-global-cache/terminus/cache/*`
`ddev config pantheon` and see the error message.
`ddev auth pantheon` and then try `ddev config pantheon` again to see it work.
> Improve error message when ddev auth pantheon has not been run, fixes #2241

- docs/index.md
The link to Docker in the intro to the DDEV-Local docs no longer linked users to the appropriate tool
Updated the link to point to Docker desktop.
Click the link for Docker at the top of system requirements. Should result in the Docker Desktop download side.
Nope, just docs.
> Update link to Docker Desktop

- docs/users/cli-usage.md
- pkg/ddevapp/templates.go
Javierv pointed out in [TYPO3 slack](https://typo3.slack.com/archives/C8TRNQ601/p1589667761211100) that the upload size of a database in PHPMyAdmin was limited to 2MB, mighty small. 
Increase the max upload to 1024MB. With PHPMyAdmin a database this large will *time* out, but the other limits won't prevent success. 
Upload a large database using PHPMyAdmin
> Increase the upload limit for PHPMyAdmin

- pkg/ddevapp/ddevapp.go
It is possible to use a numeric value for HTTP_EXPOSE or HTTPS_EXPOSE environment variables in a 3rd-party service. 
The code assumes that it will be a string, and crashes with 
```
panic: interface conversion: interface {} is int, not string
goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Describe(0xc00013adc0, 0xc0001c86c0, 0x8, 0x8)
/workdir/pkg/ddevapp/ddevapp.go:270 +0x31a4
github.com/drud/ddev/cmd/ddev/cmd.glob..func25(0x219d1c0, 0x21d7d90, 0x0, 0x0)
/workdir/cmd/ddev/cmd/list.go:41 +0x268
github.com/spf13/cobra.(*Command).execute(0x219d1c0, 0x21d7d90, 0x0, 0x0, 0x219d1c0, 0x21d7d90)
/workdir/vendor/github.com/spf13/cobra/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x219e340, 0x0, 0x0, 0x0)
/workdir/vendor/github.com/spf13/cobra/command.go:914 …
```
> Panic: Handle numeric 3rd party service use of HTTP_EXPOSE or HTTPS_EXPOSE, fixes #2266

- containers/ddev-dbserver/files/etc/my.cnf
- pkg/version/version.go
In [TYPO3 slack](https://typo3.slack.com/archives/C8TRNQ601/p1587817297004700) we studied extensively why a few collation variables weren't the utf8mb4_general_ci variables we expected. 
* change `collation-server`, which also results in the default database creation with the correct collation.
* add `init_connect='SET collation_connection = utf8mb4_unicode_ci'`, which auto-changes the client connection.
* Delete your existing database or create a new project. `mkdir testcoll && cd testcol && ddev config --project-type=php && ddev start`
* `echo "SHOW VARIABLES LIKE 'coll%';" | ddev mysql`
You should see all collation variables being utf8mb4_general_ci
```
$ echo "SHOW VARIABLES LIKE 'coll%';" | ddev mysql
mysql: [Warning] Using a password on the command line interface can be insecure. …
```
> Change default mysql collation to utf8mb4_general_ci

- pkg/ddevapp/config.go
#2243 pointed out that if a project is already configured with "default" provider, you can't do a `ddev config pantheon`.
Set the provider after reading the config.
In a pantheon project, `ddev config` (to get default provider)
Then try `ddev config pantheon`. It should work
> Set provider in app after config read, fixes #2243

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.10.5
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.imagespec.10.5
- containers/ddev-dbserver/Makefile
- containers/ddev-dbserver/test/basic_database.bats
- containers/ddev-dbserver/test/test_dbserver.sh
- docs/users/extend/config_yaml.md
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/dbimage-10.5/.ddev/config.yaml
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/mariadb-version-10.5/.ddev/config.yaml
- pkg/nodeps/values.go
- pkg/version/version.go
Add MariaDB 10.5 support
Configure for 10.5. Do something with the project.
All tests executed up through 10.4 are also executed against 10.5
> Add mariadb 10.5 support, fixes #2229

- cmd/ddev/cmd/auth-pantheon.go
- cmd/ddev/cmd/auth-ssh.go
- cmd/ddev/cmd/auth.go
- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer.go
- cmd/ddev/cmd/delete.go
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/hostname.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/import-files.go
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/sequelpro.go
- cmd/ddev/cmd/snapshot.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
- docs/users/extend/customizing-images.md
Some older commands had no examples at all. Some help text was a bit out of date.
Add examples to most commands.
> Improve examples and help in several commands

- Makefile
- pkg/ddevapp/templates.go
#2120 reports that on a slower machine (2011 MBP) and probably a larger project, `ddev start` can report a timeout... but `ddev list` immediately shows it being OK. 
We've also seen this in a few situations with ddev-webserver
Loosen the timeout for ddev-router and ddev-webserver
Currently I don't have a way to test this, but will ask @rpkoller to test. 
I think existing tests will test for regressions just fine. Many, many ddev starts are done. 
OP #2120
> Increase timeout on ddev-router and ddev-webserver for slower machines, fixes #2120

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/files/etc/bash.nointeractive.bashrc
- containers/ddev-webserver/files/etc/bashrc/composer-bin-dir-in-path.bashrc
- containers/ddev-webserver/files/etc/skel/.bashrc
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
Most ddev projects probably use composer and many will have tools installed with composer. Sadly right now in order to execute them you have to do something like this:
```bash
$ ddev exec ./vendor/bin/tool --parameter
```
By adding the vendor/bin directory to the container PATH you can access the script directly
```bash
$ ddev exec tool --parameter
```
Steps to test if this works (assuming you're using a built of ddev/containers from my PR)
```bash
$ mkdir test-this-change
$ cd test-this-change
$ composer req typo3/minimal helhum/typo3-console
$ ddev config
$ ddev start
$ ddev exec typo3cms cache:flush
Flushed all file caches.
```
I couldn't think of a better example :).
This won't affect non composer projects at all, because directories that don't exist don't cause any issues when inside …
> Add composer bin directory to PATH in ddev-webserver

- containers/ddev-webserver/files/etc/nginx/nginx_drupal7.conf
- pkg/version/version.go
The `location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {` entry is duplicated in the drupal7 nginx config.
> fix(nginx): Remove duplicated image location

- README.md
- containers/ddev-webserver/files/etc/nginx/nginx-site-laravel.conf
- containers/ddev-webserver/files/etc/nginx/nginx_laravel.conf
- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/laravel.go
- pkg/nodeps/values.go
- pkg/version/version.go
There is currently no official Laravel support in form of a project-type.
https://github.com/drud/ddev-contrib/tree/master/recipes/laravel suggests to use the generic `php` project type, but it's Nginx config is more Drupal inspired than generic (for example the `try_files $uri $uri/ /index.php?q=$uri&$args;`)
This PR does add the `laravel` project type and official Laravel config for Nginx.
Additionally, in the `postStartAction`, it does check if the the ddev db container is configured in the .env and prints some helpful instructions how to do it with a one-liner.
How I tested:
1. Create a new Laravel app same as I described in the quickstart docs:
```
mkdir my-laravel-app
cd my-laravel-app
ddev config --project-type=laravel --docroot=public --create-docroot
ddev start
ddev composer …
```
> Add Laravel support

- cmd/ddev/cmd/dotddev_assets/commands/web/live
Now that the ddev-live tool is in the web container we should ship a default custom command for `live`
* introduces `live` command resulting in commands `ddev live`
> Adds ddev-live as a default custom command

- pkg/ddevapp/ddevapp.go
@edysmp pointed out in https://github.com/drud/ddev/issues/2278#issuecomment-636215134 that `ddev import-db` was failing in the tested Mutagen edge version of Docker, but reporting success. 
The reason this was happening was that in app.Exec bash was being invoked without the `pipefail` option, so a failure in the pipe wasn't caught, and the ddev import-db uses a pipe with pv. 
Make sure that `set -o pipefail` is set
This change needs to be mentioned in release notes, as some people might be counting on failures not being reported.
> Make sure that Exec() runs commands with bash error checking, especially pipefail

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/Makefile
- docs/users/docker_installation.md
- docs/users/extend/config_yaml.md
- docs/users/extend/custom-commands.md
- docs/users/extend/customization-extendibility.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
* Minor ddev-webserver image maintenance
* Add deprecation warnings for docker toolbox and apache-cgi
#2284: Deprecate docker-toolbox
#2286: Deprecate apache-cgi
* Normal testing
> Image maintenance and deprecation warnings, for #2284 and #2286

- docs/users/cli-usage.md
Docs related
Use current state of information about Magento 1 and OpenMage
Read the text
Klick on the links
Do all steps on your system
https://github.com/drud/ddev/issues/2283
Update Docs section about Magento1 /OpenMage quickstart
> Update Magento 1 Quickstart section to use OpenMage (docs only), fixes #2283

- .circleci/bump_homebrew.sh
- .circleci/generate_artifacts.sh
#2317: Zsh and fish completions were not being placed properly in the homebrew bottle.
Put them in the correct place.
* `brew uninstall ddev`
* Verify that the zsh completions are gone
* `brew install ddev`
* Verify that zsh and fish completions have been properly added to /usr/local/share/zsh/site-functions and that they work
It should say
```
zsh functions have been installed to:
/usr/local/share/zsh/site-functions
```
OP #2317 
This needs to be tested after next alpha release
> Put zsh completions in correct place in homebrew bottle, fixes #2317

- containers/ddev-dbserver/files/create_base_db.sh
- pkg/version/version.go
There have been intermittent timeouts only on the Windows container build; this increases the timeout.
> Increase timeout on create_base_db to avoid transient windows test failures (tests only)

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
In reorganzing how we build ddev-webserver, a couple of key environment variables got lost, most importantly COMPOSER_CACHE_DIR
Add them back in.
> Add environment variables to web container that got lost in reorg

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/utils.go
- pkg/globalconfig/global_config.go
#1933 points out that a lot of nasty things happen when people change the name of a project in a directory.
This attempts to mitigate most of those. 
* When `ddev start` or `ddev config`, look to see if the global_config.yaml already has a project in that directory. If so, error out. 
* Improve error messages in this case
* Improve the error message where the directory has been deleted.
Manual testing is so important on this one.
Change the name in a project when it's already started. Use `ddev config` or edit the config.yaml. Verify that you get fails when needed.
Change the name in a project when it's *not* running. Same checks.
> Improve handling of duplicate project in same directory, closes #1933

- cmd/ddev/cmd/config.go
- pkg/ddevapp/composer.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/task.go
- pkg/util/capture.go
- pkg/util/utils_test.go
#2214: Hook output has been saved up and then output at completion, but users want to see it as it happens, especially on long-running items.
Output directly as things happen.
Add a post-start hook like this:
```
hooks:
post-start:
- exec: echo hi there && sleep 1 && date && sleep 1 && date
```
and then `ddev start`
You should see the output as it happens.
Existing hook tests were updated.
> Hook output streamed as it occurs, fixes #2214

- cmd/ddev/cmd/export-db.go
- pkg/ddevapp/config_test.go
- pkg/output/output_setup.go
- pkg/util/utils.go
`ddev export-db >something.sql` could output an error message to something.sql
All error messages were going to stdout
* Improve export-db in general by starting if not started
* Improve all calls to util.Failed and friends to go to stderr
* `ddev stop`
* `ddev export-db >junk.sql.gz`
It should now start and succeed.
But create an error with 
`ddev start somethingthatdoesntexist >/tmp/junk.out`
and you should see the error on the screen
> Improve util.Failed() handling and export-db, fixes #2281

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
In the testing phase we should have the newest images possible. This bumps them and they're all built fresh so have latest PHP etc.
> Bump all images built with no cache to v1.15-rc1

- docs/index.md
Closes #2320 to add WSL2 installation instructions.
Quick first version of DDEV installation docs for WSL2. Tried keeping it as short as possible (as the blog post already gives some more background info: https://ddev.com/ddev-local/ddev-wsl2-getting-started/). Probably needs some fine-tuning.
> Add WSL2 installation docs, fixes #2320

- .buildkite/testbot_maintenance.sh
- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/root.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/instrumentation.go
- pkg/globalconfig/global_config.go
- pkg/globalconfig/global_config_test.go
- pkg/nodeps/utils.go
- pkg/nodeps/utils_test.go
- pkg/nodeps/values.go
#2302 points out that there are times when ddev's internet check times out faster than people would prefer, resulting in `ddev start` trying to add a hostname to /etc/hosts.
There are also cases where "internet not detected" shows on the screen when it's unnecessary.
* Increase the default timeout from 500ms to 750ms
* Make the timeout configurable in ~/.ddev/global_config.yaml by changing `internet_detection_timeout_ms`
In a VM, slow down internet
Verify that the global config can make it work even with slowed internet.
> Make internet connection timeout configurable, fixes #2302

- cmd/ddev/cmd/a.go
- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/root.go
- cmd/ddev/main.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
#2349 points out that we should never be writing files in the rare case where we're running as root (`ddev hostname` only). 
Try to prevent that situation.
* `sudo rm -rf .ddev/{commands,homeadditions,.global_commands} ~/.ddev/{commands,homeadditions}`
* Try `sudo ddev start` - it should balk
* Try `sudo ddev hostname junker42.ddev.site` - it should add the hostname without creating any files in the above directories
* `find ~/.ddev . -user root` in project directory; nothing should be found.
* Add an `additional_fqdns` entry to config.yaml, it needs to be something that is not already in /etc/hosts
* `ddev start` - You should see the hostname get added
* `find ~/.ddev . -user root` in project directory; nothing should be found.
* Test basic functionality of custom commands and built-in …
> Don't use root privileges when writing files #2349

- pkg/ddevapp/templates.go
Extra spaces in `templates.go`
Removing extra spaces :)
> removing extra spaces in template.go that end up in .ddev/config.yaml

- cmd/ddev/cmd/export-db.go
Testing of v1.15-rc2 showed that `ddev export-db >file.sql.gz` would not work correctly if the project was stopped at the time, because all the output from docker-compose made it into the file.
It will be nice to get that docker-compose output going to stderr maybe, but not right before a release.
Instead, this just does what the original #2281 asked for, which was not having this exact situation fail. So now `ddev export-db` does not auto-start a stopped project.
> Don't try to start export-db or docker-compose output will end up in output

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Preparing for v1.15.0 release - bumping image tags to v1.15.0
> Bump image versions for v1.15.0 release

- pkg/ddevapp/config.go
- pkg/ddevapp/instrumentation.go
- pkg/ddevapp/providerDdevLive.go
- pkg/nodeps/utils.go
There's a flaw in docker on WSL2 where running a container right after another one gets the wrong mount permissions.
A sleep seems to fix it. 
This only affects `ddev pull` with ddev-live provider type.
> Work around WSL2 docker flaw with incorrect mount ownership - affects ddev-live pull

- docs/users/extend/custom-commands.md
Typo in documentation
Fixed typo
> Fix typo in custom-commands documentation

- docs/users/shell-completion.md
Added backticks to shell completions docs.
N/A
The word `<TAB>` was missing the backticks and therefore was not displaying on the page. This fixes the issue and not the word is visible.
N/A
N/A
https://github.com/drud/ddev/blob/master/docs/users/shell-completion.md
No ramifications.
> Fixed small typo

- containers/ddev-router/test/containertest.sh
- containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
- containers/ddev-webserver/tests/ddev-webserver/custom_config.bats
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/ddev-webserver/tests/ddev-webserver/project_type.bats
- pkg/version/version.go
It turns out if people have a proxy set up in docker
and they haven't excluded "localhost", then the
healthcheck script will fail accessing http://localhost
There was a change in the web image healthcheck script in v1.15.0 to use "localhost" instead of "127.0.0.1" and this broke somebody with a proxy and 127.0.0.1 (only) excluded from the proxy.
> Use 127.0.0.1 in healthcheck instead of localhost - avoid docker corp proxy

- cmd/ddev/cmd/commands_test.go
TestCustomCommands has a fragile test that can be simpler with Contains instead of Equals.
> Minor test improvment, contains instead of equal

- .circleci/bump_homebrew.sh
- .circleci/generate_artifacts.sh
- .github/ISSUE_TEMPLATE/Bug_report.md
- docs/developers/buildkite-testmachine-setup.md
- docs/developers/release-checklist.md
- docs/index.md
Docker Desktop for Mac minimum requirement has changed to High Sierra. 
Switch to High Sierra
> Bump minimum macOS requirement to High Sierra because Docker Desktop already has

- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
#2374 describes the issue when something is added to ~/.ddev/homeadditions and then you do a `ddev start`. 
The resulting homeadditions item gets copied into the project at .ddev/.homeadditions and then it is not properly gitignored. 
Add .homeadditions to the gitignore.
* Start with a project that is clean in git. (`git status` is clean)
* Add something to ~/.ddev/homeadditions.
* `ddev start` 
* `git status` should still be clean.
Added this scenario to TestConfigGitIgnore() and also added global commands the same way.
#2374
> Gitignore the .homeadditions completely, fixes #2374

- pkg/ddevapp/drupal.go
#2389 points out that "files/sync" is being created in "web/files/sync" instead of in "web/sites/default/files/sync"
Create the right path. 
in docroot:
rm -rf sites/default/files/sync files/sync
`ddev start`
Check the status page to make sure it doesn't have a complaint about the sync dir.
> Fix wrong dir creation of sync dir, fixes #2389

- pkg/ddevapp/providerDdevLive.go
DDEV-Live introduced quota on backups. But `ddev pull` with ddev-live integration creates a new backup on each pull. So quota is quickly depleted.
Delete the pulled database after it's pulled.
```
export DDEV_DEBUG=true
ddev pull
```
Note the deletion. You can also probe it using `ddev live describe backup <backupname>`
> Delete db backup after pulling to not use quota

- docs/index.md
A set of docs improvements, will be batched for a while
* Use PowerShell command to setx, lose git-bash references (thanks to @vacilando and @gilbertsoft ) #2397
> Docs improvements; Use PowerShell command to setx, fixes #2397

- pkg/globalconfig/global_config.go
#2373 points out that `DdevGlobalConfig.MkcertCARoot` never gets updated of $CAROOT changes, which means that especially in WSL2, if any mistake is made in $CAROOT, it never gets corrected.
If $CAROOT isn't the same as `DdevGlobalConfig.MkcertCARoot` then re-read the correct value.
Test in WSL2. 
* Mess up the setx command so that WSLENV contains a semicolon instead of colon.
* You should now have a broken CAROOT on WSL side
* `ddev start` and see that the bad CAROOT gets into ~/.ddev/global_config.yaml
* Now fix CAROOT via a proper setx. 
* `ddev start` and see that it get fixed in global_config.
* Verify that chrome trusts a site.
> Reset global mkcert var if  has changed, fixes #2373

- pkg/ddevapp/webserver_config_packr_assets/README.apache.txt-site-php.conf
- pkg/ddevapp/webserver_config_packr_assets/apache-site-php.conf
- pkg/ddevapp/webserver_config_packr_assets/apache_second_docroot_example-site-php.conf
The 1.15 Apache config files were linking to Nginx manual section. 
Fixed the link. Also added a sentence in README file on where this config files end up to help understanding.
> v1.15: Improved/Fixed documentation for Apache config override files

- docs/index.md
People have had trouble with ";" in the WSLENV environment variable. The result is not being able to get a trusted connection in chrome.
Make sure that the WSLENV variable gets set to a usable value, even if it was previously set wrong.
> Docs: More failsafe on WSLENV having colon [skip ci][ci skip]

- .buildkite/windows10dockertoolbox.yml
- .circleci/config.yml
In v1.16 we'll no longer be supporting apache-cgi or docker-toolbox. So we should stop wasting testing time on those.
Stop the explicit tests for those.
#2286: Deprecating apache-cgi
#2284: Deprecating docker-toolbox
#2288: Reallocate windows test-runners.
> Stop testing for apache-cgi and docker toolbox for #2286, for #2284, for #2288

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/testdata/TestDdevExec/docker-compose.busybox.yaml
drud/ddev-contrib#80 points out that custom commands (and all execs) on non-ddev-provided containers will fail because the "sh" shell is used by default, and it doesn't provide the "pipefail" error check.
Only use -o pipefail if bash is the shell.
* Consider dropping pipefail out completely to simplify the code.
* Test drud/ddev-contrib#80
* Test other ordinary `ddev exec` with ddev and non-ddev containers.
> Don't use pipefail with non-bash exec/custom commands, fixes drud/ddev-contrib#80

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Rebuilding docker images for v1.15.1
> Bump image tags to v1.15.1

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
- containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/php_ide.bashrc
- containers/ddev-webserver/ddev-webserver-base-files/etc/skel/.bashrc
- docs/users/extend/custom-commands.md
- docs/users/extend/custom-compose-files.md
- pkg/ddevapp/templates.go
- pkg/version/version.go
This fixes a regression in v1.15.0 - 
DDEV-Local v1.15 adds automatic settings of PHP_IDE_CONFIG to help people who are doing command-line debugging and want to use xdebug. Otherwise they'd have to set it themselves. 
However, setting this throughout the web container (in php-fpm's context) results in PHPStorm not popping up the normal server/mapping creation dialog box. It's possible to work around it, but we've always been proud of how ddev makes PHPStorm so easy... and suddenly it's not.
Only set PHP_IDE_CONFIG in the `ddev ssh` or `ddev exec` context
Set up PHPStorm
Remove all servers
`ddev xdebug on`
Set a breakpoint in index.php
Visit the site
It should pop up a mapping dialog.
> PHP_IDE_CONFIG must not be set for php-fpm

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Preparing new updated images for v1.15.2
> Bump ddev-webserver version to v1.15.2 for release v1.15.2

- pkg/ddevapp/providerDdevLive.go
* DDEV-Live recently implemented quotas, including quotas on backups of db and files
* ddev-live-client was updated to v0.6.0 in v1.15.2+, and its syntax for deleting database backups has changed.
* The test user that runs tests (and perhaps people who use backups) could easily run out of quota on backups because `ddev pull` doesn't clean them up.
* Make sure both files and db backups are deleted after we pull them.
* Adjust code to the new `ddev-live delete backup` syntax
Just review `ddev-live list backups` or `ddev live list backups` after tests have run. There should be nothing there.
> DDEV-Live needs to delete its backups after pulling to avoid quota trouble

- containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
- containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
- containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/php_ide.bashrc
- pkg/version/version.go
Unfortunately version v1.15.2 made Xdebug with PHPStorm work fine for people using it for web debugging, but broke it for command-line debugging.  See https://github.com/drud/ddev/pull/2424
This revision works with both command-line and web debugging. 
Make sure that PHP_IDE_CONFIG does *not* get loaded by php-fpm (which breaks web debugging) but *does* get loaded by `ddev ssh` (using /etc/bash.bashrc)
Try debugging with PHPStorm both with a web setup and a command-line setup.
> Make PHP_IDE_CONFIG work for both command-line and web debugging

- pkg/ddevapp/templates.go
During the addition of the new xdebug custom command the docs were changed but the description in the config.yaml still talks about the old commands.
This patch changes the description in the related template.
> Change xdebug description in config.yaml to new custom command

- pkg/ddevapp/config.go
Developers sometimes use "webroot" or "html" for the docroot in their projects. Auto-recognize those.
> Add 'webroot' and 'html' to the places we look for default docroot

- docs/users/extend/in-container-configuration.md
In response to https://stackoverflow.com/questions/63084369/in-ddev-how-to-automatically-use-custom-shell-config-inside-docker-container I tried to make the shell configuration more explicit... particularly including the exact words "shell config" and "dotfiles" so the readthedocs search can find them.
In regards to "If you want to use a shell other than bash, add it as a package to [customize the Docker image](https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/).".... I presume that's correct for adding a shell like zsh but I'm not sure..?
> [docs] Improve wording of "In-container home directory configuration"

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/version/version.go
Remove drupal console from ddev-webserver #2388 
By removing the curl command which installs the drupal console into the ddev-webserver.
1. Edited `containers/ddev-webserver/Makefile` with my docker hub info.
2. Followed the instruction from the file [README.md](https://github.com/drud/ddev/blob/master/containers/ddev-webserver/README.md)
3. Docker hub repo link: [abhisekmazumdar/ddev-webserver](https://hub.docker.com/r/abhisekmazumdar/ddev-webserver)
> Remove drupal console from ddev-webserver, fixes #2388

- containers/ddev-webserver/ddev-webserver-base-files/etc/ImageMagick-6/policy.xml
- pkg/version/version.go
TYPO3 is able to convert PDF files to images for a preview with the help of ImageMagick / GraphicsMagick but ImageMagick blocks PDF files by default on Debian.
The policy.xml file distributed by the APT package on Debian is added to the web server container image and the related line is commented out to have PDF conversion enabled by default in DDEV.
Go to the TYPO3 Backend and under environment in the admin / install tool run the image test. There should not be an error and the PDF should be shown as image in the related test.
**The important test:**
**In case something is broken it looks like this:**
> Allow processing of PDF files with ImageMagick

- Makefile
Minor change to Makefile - use :cached in DOCKERMOUNTFLAG
> Use :cached in DOCKERMOUNTFLAG for performance

- .buildkite/testbot_maintenance.sh
Failed tests have left some random projects still listed on buildkite-agents. Delete them at startup.
> Delete any existing ddev projects at buildkite startup

- docs/users/developer-tools.md
Running `composer global require x/y` in web container creates a bunch of files in in-container user's home directory. That directory seems to get wipeout on container restart. This leads to really obscure errors and possibly non-reproducible state (if module resolution changed since last install).
There is no easy solution, but at least a note to point out this side-effect would be useful. I added cross-link to homeaddition , but I don't think there is an easy way to sync, it has to be done manually.
> Add note about composer global issues

- .circleci/config.yml
- pkg/testcommon/testcommon.go
TestComposeCmd is failing under NFS on CircleCI, for no reason I understand. It seems to fail only on NFS, and only since we updated to new CircleCI image in https://github.com/drud/ddev/commit/fa8fb704f32fcc24e81f3ebdc650c50a647c1a0d
This appears to be a result of a umask setting (022) in the new image, along with NFS being unwilling to grant access to *some* directories if the perm is 700.
> Fix umask problem with tests on NFS on CircleCI

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/ddev-webserver/tests/ddev-webserver/test.sh
- pkg/version/version.go
* #2245 requests that xdebug be on by default for usage of the image in other contexts (PHPStorm)
* Terminus switch from composer install to download-and-install, much faster.
> Web image maintenance: Simpler terminus install, xdebug on by default

- containers/ddev-dbserver/Dockerfile
Currently, [CircleCI fails](https://app.circleci.com/pipelines/github/drud/ddev/2673/workflows/6c5de43d-da23-49fc-9d60-a035179b3b1e/jobs/27226) because of these errors:
```
--2020-08-29 03:09:07--  https://repo.percona.com/apt/percona-release_latest.stretch_all.deb
Resolving repo.percona.com (repo.percona.com)... 167.71.118.3, 157.245.119.64, 167.99.233.229
Connecting to repo.percona.com (repo.percona.com)|167.71.118.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11150 (11K) [application/octet-stream]
Saving to: 'percona-release_latest.stretch_all.deb'
0K ..........                                            100%  113M=0s
2020-08-29 03:09:08 (113 MB/s) - 'percona-release_latest.stretch_all.deb' saved [11150/11150]
Selecting previously unselected package …
```
> Fix percona installation by installing curl

- pkg/ddevapp/webserver_config_packr_assets/nginx-site-backdrop.conf
- pkg/ddevapp/webserver_config_packr_assets/nginx-site-drupal6.conf
- pkg/ddevapp/webserver_config_packr_assets/nginx-site-drupal7.conf
- pkg/ddevapp/webserver_config_packr_assets/nginx-site-drupal8.conf
- pkg/ddevapp/webserver_config_packr_assets/nginx-site-drupal9.conf
- pkg/ddevapp/webserver_config_packr_assets/nginx-site-magento2.conf
- pkg/ddevapp/webserver_config_packr_assets/nginx-site-wordpress.conf
Front-end developers really want changes to css and js to come through right away, and ddev is a developers' tool. 
#2404 explains how the Expires setting in nginx makes it so devs can't see their CSS changes.
I ran into this exact problem exploring #2410 , so figure it will probably affect others. 
Turn off the expires header for css and js.
Must test for every changed CMS project type.
* Start the project
* Visit pages
* Use Chrome debugger or whatever to see the expires situation for css
> nginx shouldn't have long expires on css/js, fixes #2404

- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/monitoring.conf
- pkg/version/version.go
Since `/ping` is not checked we should remove it so that the path is available for hosted applications.
I would like to host an application that uses the `/ping` path as part of it's own healthcheck.  In [this PR](https://github.com/drud/ddev/commit/3976b9431b9b87101ba2416268f6f3cbfe317ffd#diff-d8376a050ab0946a67f42cd13bfff9e3) you replace the line:
```
The `location ~ ^/(phpstatus|ping)$ {` block is required for the webserver container healthcheck to work.
```
with
```
The alias `Alias "/phpstatus" "/var/www/phpstatus.php"` is required for the healthcheck script to work.
```
This PR removes the `ping` reference in `monitoring.conf` which is redundant and therefore will make it available for hosted applications to use.
> Stop using the /ping URL in webserver since it is not checked anyway

- pkg/ddevapp/utils.go
In the case of a corrupted ~/.ddev/global_config.yaml, we were failing loading an app, but then trying to use it. #2483 
Thanks so much to @mtelgkamp for the careful reporting on this one!
Don't use the failed app load. 
Run `ddev list` with the corrupted global_config.yaml as in #2483
> Don't try to assign to nil app.Name in GetProjects(), fixes #2483

- docs/users/extend/custom-commands.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/testdata/TestEnvironmentVariables/showhostenvvar
#2486: Although a number of environment variables were created and were intended to be added into the web container, some of them were not exported via the .ddev-docker-compose*.yaml, so did not end up inside the container.
Make sure they get exported. 
Verify that $DDEV_DOCROOT and all other named environment variables in the container section of https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#environment-variables-provided are properly set inside the container.
Added TestEnvironmentVariables to verify values in container and on host
I used these custom commands (global) for testing: https://gist.github.com/rfay/8773faca379cc22c9c4b5cc61e75f6e6
> Export documented environment variables into web container, fixes #2486

- docs/users/faq.md
> **Do I need to install PHP or Composer or Nginx or DDEV on my computer?**
> Absolutely *not*. All of these tools live inside DDEV's docker containers, so you need only Docker and DDEV. This is especially handy for Windows users where there's a bit more friction installing those tools.
The question lists among other DDEV. Yet the answer says in the first sentence "no, not necessary" but in the second it is listed in the two required tools (Docker and DDEV).
It removes the tool DDEV from the question which makes the answer valid.
No testing needed as there are no code changes involed.
> Fix faq entry about required tools like PHP

- cmd/ddev/cmd/root.go
- pkg/ddevapp/instrumentation.go
#1968: Ad-blockers like pi-hole seem to often define api.segment.io as unwanted, which is fine, but they just resolve its DNS as 127.0.0.1, which doesn't have anything listening and doesn't have a valid cert. So users get ugly error messages.
Add a no-op logger for the segment operations.
This also adds the architecture (like 'amd64' or 'arm64' to Segment logging.
Nothing added
> Prevent segment from writing to console (especially for pi-hole), fixes #1968, fixes #1767, fixes #1967

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/commands_test.go
The global prefix in the command suffix of global commands is missing.
This patch fixes the condition and adds tests to avoid regressions in this place.
run `ddev` and check if the global prefix is added to global commands suffixes e.g.
`Run TYPO3 CLI (typo3) command inside the web container (global shell web container command)`
The new tests are checking the correct behavior of global host and web commands. Also a new test is provided to ensure global host commands gets properly overwritten by the project ones.
> Fix missing global prefix of command suffix

- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
#2443 points out that people who are doing Drupal multisite don't want DRUSH_OPTIONS_URI set, because it confuses everything. And since that recipe usually has `disable_settings_management: true` it's pretty reasonable to not include $DRUSH_OPTIONS_URI in the web container when set.
Don't set DRUSH_OPTIONS_URI if `disable_settings_management: true`
On a D8+ site, 
- [ [ Now set `disable_settings_management: true` and `ddev start`. `ddev exec "set | grep DRUSH"` should NOT show DRUSH_OPTIONS_URI.
None added. Seems to obscure to bother.
> Don't set DRUSH_OPTIONS_URI if disable_settings_management, fixes #2443

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/testdata/TestCustomCommands/project_commands/host/testhostcmd
- docs/users/extend/custom-commands.md
Currently the examples section of a custom command does only support a one line description which ends in confusing examples. Examples in multiple line is highly desirable.
This patch introduces the possibility of using `\n` in the examples to force a line break.
Change the examples comment and use `\n` to force a new line and run `ddev [command] -h` to see the new output.
The line breaks and fromatting are tested in a new test to avoid regressions.
> Allow multiline examples for custom commands

- docs/users/snippets/atom_config_cson_snippet.txt
- docs/users/step-debugging.md
The `php-debug` package requires `atom-ide-ui`, but `atom-ide-ui` has it’s own debugger system which isn’t compatible with `php-debug`. So you essentially have to disable the debugger that comes with `atom-ide-ui` to use the `php-debug` debugger. After doing that everything works.
It updates the XDebug + Atom documentation to provide instructions on doing this
Step through setup instructions on Atom and ensure Xdebug works
Documentation change only, so no tests.
https://github.com/gwomacks/php-debug/issues/310#issuecomment-419751273
The `atom-ide-ui` dependency adds a few features to Atom, so it might slightly change the user experience, but overall it should be pretty seamless.
> Update Atom XDebug Instructions

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router.go
- pkg/ddevapp/ssh_auth.go
@chellman points out in #2512 that if port 80 is occupied, ddev refuses to start, even if the project is configured to not use port 80.
There was code in determineRouterPorts() that always added port 80 to the ports list. I am not sure if this was debugging code or if I'm about to find out what it was there for. 
`brew install nmap` and then run it with `ncat -l -k -p 80`
Set project to start with router_http_port: 8080
`ddev start`
It should work
> Don't always require port 80 in determineRouterPorts(), fixes #2512

- docs/developers/buildkite-testmachine-setup.md
- pkg/testcommon/testcommon.go
- pkg/testcommon/testcommon_test.go
macOS Big Sur, preview 7, doesn't seem to share subdirectories of something exported in /private/var/folders, so a single line static export doesn't work
Move the tmpdir created for tests into ~/tmp/ddevtest instead. That way we don't ever have to have that extra share in the /etc/exports anyway.
#2501: Prep Big Sur
> Big Sur: Change tmpdir to ~/tmp/ddevtest for tests: NFS problems (tests only)

- containers/ddev-dbserver/files/docker-entrypoint.sh
- pkg/version/version.go
In #2454 @dennisameling encountered a difficult issue where the mysql 5.6 (ONLY) somehow created /var/lib/mysql/mysql (the database folder for the main db) when it never has before. But the start script used the existence of that directory to signal that the database was already set up, so skipped setting it up.
Switch to using the /var/lib/mysql/db_mariadb_version.txt file as a signal that the database has been set up, as that gets created whenever the database has actually been copied/initialized the first time.
I think this should be fine with automated tests... but just using `ddev config --mariadb-version="" --mysql-version=5.6 && ddev start` will fail if `docker buildx build` was used to build the 5.6 image. 
This only shows up in `docker buildx build`, so although it should pass …
> db container start script needs different test to copy prepped db

- scripts/install_ddev.sh
* #1587 script needs to be able to install a named version
* #2416: run mkcert if possible
* Handle post v1.16.0-alpha4 architecture in the download filename
* Use the script to install latest stable version (no args)
* Use the script to install a named version post v1.16.0-alpha4
* Use the script to install a named version pre-v1.16.0-alpha4
* We haven't ever tested this script... it's possible we should.
> Improve install_ddev.sh to take a version and handle architectures, fixes #1587, fixes #2416

- .circleci/bump_aur.sh
- .circleci/config.yml
Because we now have both amd64 and arm64 tarballs for download, the naming has changed.
The homebrew and AUR scripts need to point to the right (amd64) ones.
> Fix release scripts for new naming of tarballs

- cmd/ddev/cmd/auth-ssh.go
Docker Desktop 2.4.0.0 for Windows (in Hyper-V mode only) changed the ownership of mounted files from root to the actual user, but still does not provide any way to change permissions.
As a result, `ssh-add` fails in the process of `ddev auth ssh` because the (windows) permissions are too loose for ssh purposes.
```
$ ddev auth ssh
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0755 for '/home/anja.leichsenring/.ssh/id_ecdsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Docker command 'docker [run -it --rm --volumes-from=ddev-ssh-agent --user=1000 …
```
> Fix Docker Desktop 2.4.0.0 Windows Hyper-V "WARNING: UNPROTECTED PRIVATE KEY FILE"

- cmd/ddev/cmd/delete.go
- cmd/ddev/cmd/pause.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/snapshot.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
#2537 describes a bug resulting in a panic when one uses `ddev <command> --all`, but there are no projects.
Don't assume there are projects
`ddev stop --unlist --all`
`ddev stop --all` should not result in a panic
Make sure all affected commands still work fine. start, stop, restart, pause
> Don't assume that project list populated, fixes #2537

- pkg/ddevapp/config.go
1. Start a project
2. `rm .ddev/config.yaml`
3. `ddev config`
You get error:
`could not create new config: /Users/rfay/workspace/d9/.ddev/config.yaml exists but cannot be read. It may be invalid due to a syntax error.: unable to load config file /Users/rfay/workspace/d9/.ddev/config.yaml: could not find an active ddev configuration at /Users/rfay/workspace/d9/.ddev/config.yaml have you run 'ddev config'? open /Users/rfay/workspace/d9/.ddev/config.yaml: no such file or directory`
The error is incorrect (the config.yaml does not exist)
The config.yaml should not have been loaded if it didn't exist in the first place.
Only load config.yaml if it exists
Follow the recreation instructions above.
> Don't try to load config.yaml if it doesn't exist

- pkg/ddevapp/ddevapp.go
Images for omitted containers are pulled from registry
Prevents pulling of images for omitted containers
#2262
> Images of omitted containers should not be pulled, fixes #2262

- .buildkite/testbot_maintenance.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- Makefile
Use official golang container instead of golang-build-container
This frees us to move forward with building/testing on arm64, see https://github.com/drud/ddev/issues/2543
> Use official golang container instead of golang-build-container

- .buildkite/test.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
See #2544: docker login with a team-member user is required, especially on CircleCI.
> Use docker login with team member user, fixes #2544

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
This is to aid with future compatibility for Drupal 9.
Drupal 8 sites that upgrade to Drupal 9 will be stuck with databases that won't work anymore, because ddev uses mariadb 10.2 by default whereas D9 requires 10.3.
This changes the configuration to use mariadb 10.3 when building an instance for Drupal 8.
Build an instance for D8.
TBD.
#2232
TBD.
> Use MariaDB 10.3 with Drupal 8, fixes #2369

- Makefile
`make` was creating spurious empty directories like "TARGET=darwin_amd64; GOOS=darwin GOARCH=amd64"
Remove those and quiet down the output.
> Fix spurious creation of dirs like 'TARGET=darwin_amd64; GOOS=darwin GOARCH=amd64'

- Makefile
> Bump golang to 1.15.3 for build

- docs/users/cli-usage.md
- pkg/ddevapp/drupal.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
Maybe this was just me, but I thought it was fine to modify the settings.ddev.php file in a Drupal project after the initial config.  I know it does technically work, but I've found out it's not recommended.  I think the comment template, and docs, should be updated to make this a smidge clearer.
Added a line to the docs, and modified the comment templates for Drupal, Typo3, and WordPress settings files (the only ones I saw that seemed applicable).
Only comments changed, so as long as the build succeeds, all should be well.
> Discourage users more strongly from modifying DDEV's settings.ddev.php

- cmd/ddev/cmd/cmd_version_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/nodeps/values.go
- pkg/version/version.go
- pkg/version/version_test.go
In v1.15, mariadb_version started being omitted from the config.yaml if it was the same as default.
Unfortunately, this made it impossible to change the default without surprising people with odd behavior.
mariadb_version will now be included in config.yaml on `ddev config`, but it can still be empty and result in default
TestConfigMariadbVersion and TestConfigMysqlVersion were updated, but should have the same strength.
> mariadb_version should not be omitted, fixes #2555

- containers/ddev-dbserver/Makefile
- pkg/version/version.go
Mysql 8.0 has been pinned at 8.0.19 for some time due to an incompatibility with xtrabackup. Hopefully that's fixed now and we can move on to standard.
> Unpin mysql 8.0, fixes #2546

- cmd/ddev/cmd/config.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/cli/php.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/fpm/php-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/fpm/php.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/fpm/pool.d/www.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/mods-available/xdebug.ini
- containers/ddev-webserver/tests/ddev-webserver/test.sh
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/dockerutil/testdata/TestComposeWithStreams/test-compose-with-streams.yaml
- pkg/nodeps/values.go
- pkg/version/version.go
Add PHP8.0 support
I haven't found that either TYPO3 v10 or Drupal9 is able to run under php8, so just an index.php with phpinfo(); in it is the best I've done.
There is no testing yet.
> Experimental PHP8.0 support, fixes #2553

- pkg/ddevapp/templates.go
drush-launcher (/usr/local/bin/drush in web container) disables xdebug by default, see https://github.com/drush-ops/drush-launcher#xdebug-compatibility
But people will want it if they're using drush in the container and have `ddev xdebug on`
Per https://github.com/drush-ops/drush-launcher#xdebug-compatibility, set `DRUSH_ALLOW_XDEBUG=1` by default
`ddev start`
`ddev exec 'echo $DRUSH_ALLOW_XDEBUG'`
Value should be 1
> Provide DRUSH_ALLOW_XDEBUG=1 to allow drush launcher xdebug usage

- containers/ddev-dbserver/Makefile
Unfortunately, there's once again an incompatibilty between
xtrabackup (based on 8.0.21) and mysql 8.0.22
Mysql 8.0.22 became available and the builds suddenly started breaking, see https://app.circleci.com/pipelines/github/drud/ddev/2972/workflows/6a6762db-b33f-4cf3-be22-761663c6191a/jobs/28469
I'm guessing the bug is https://jira.percona.com/browse/PXB-2301
> Pin mysql 8 to 8.0.21

- pkg/ddevapp/drupal.go
Drupal 8.9.6 website, that is using a custom deprecated (but still supported) setup for configuration sync directory, gets overridden by ddev default setup.
```
CONFIG_SYNC_DIRECTORY = 'sync'
$config_directories[CONFIG_SYNC_DIRECTORY] = `/var/www/html/config/sync`
```
Rearranging the conditions that check if a configuration sync directory already exist.
I am thinking testing for this, would require 6 scenarios, installing Drupal Umami + Drush 10, and then run `drush cex -y`.
(no custom config directory)
Drupal 8.7 Umami
Drupal 8.8 Umami
Drupal 9.0 Umami
(with custom config directory)
Drupal 8.7 Umami
Drupal 8.8 Umami
Drupal 9.0 Umami
Some of these tests should fail with the conditions set in ddev `master`, but pass with the new set of conditions (in this patch)
> Fix config sync directory for Drupal 8 websites that are using a custom sync directory

- pkg/version/version.go
When I changed the mysql containers to pin mysql 8.0.21, I didn't add new bump in version.go
> Bump db version to pinned 8.0.21

- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/testdata/TestMariaMysqlConflicts/config.yaml.mariawithemptymysql
- cmd/ddev/cmd/testdata/TestMariaMysqlConflicts/config.yaml.mysql8only
- cmd/ddev/cmd/testdata/TestMariaMysqlConflicts/config.yaml.mysqlwithemptymaria
- cmd/ddev/cmd/testdata/TestMariaMysqlConflicts/config.yaml.nodbspecified
- pkg/ddevapp/config.go
#2571 reports a problem with projects that have mysql_version set but where mariadb_version is not yet in the config.yaml (it should be empty in there)
If mysql_version is already set, set mariadb_version to ""
In a working project, set `mysql_version: 8.0` but don't set mariadb_version (it shouldn't be in the config at all)
`ddev start` should work without errors.
Adds TestMariaMysqlConflicts and improves TestConfigMysqlVersion.
OP #2571
Release notes should explain how mariadb_version and mysql_version interact, and why, (because we want to change mariadb_version default in the future)
> mysql_version should override mariadb_version if it is set, fixes #2571

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Bump upstream of ddev-webserver docker image to v0.5.7 to get php5.6 on arm64
It also gets the upstream with composer v1 by default.
> Bump upstream to v0.5.8 to get php5.6 on arm64 (and composer v1 by default)

- .travis.yml
- .travis/linux_travis_arm64_setup.sh
- Makefile
- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- containers/containers_shared.mak
- containers/ddev-dbserver/Makefile
- containers/ddev-dbserver/database-versions
- containers/ddev-dbserver/test/test_dbserver.sh
- containers/ddev-webserver/Makefile
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/get_arch.sh
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/nodeps/mariadb_values.go
- pkg/nodeps/mariadb_values_linux_arm64.go
- pkg/nodeps/mysql_values.go
- pkg/nodeps/mysql_values_linux_arm64.go
- pkg/nodeps/php_values.go
- pkg/nodeps/php_values_linux_arm64.go
- pkg/nodeps/values.go
As discussed in https://github.com/drud/ddev/issues/2543#issuecomment-706209596, this PR tries to add a TravisCI config for running tests on arm64 Linux. It's using the brand-new [arm64-graviton2 processor](https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availaibility) which should result in good performance 🚀 
First test run: https://travis-ci.com/github/dennisameling/ddev/builds/191266714
Small note: Linuxbrew is not supported on arm64 ([no binary packages](https://docs.brew.sh/Homebrew-on-Linux#arm)), and mkcert is not available for arm64 as well. I therefore used our custom mkcert version: https://github.com/drud/mkcert/releases/download/v1.4.6/mkcert-v1.4.6-linux-arm64. 
The config likely needs some tweaks so that it will support more tests. I'll try to take …
> Add Travis config for arm64 tests, fixes #2543

- docs/users/cli-usage.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
* Sometimes restore-snapshot seems to have timed out on large databases
* Currently huge restores show completed restore when it's still ongoing
* Occasional support requests for timeouts on ddev-webserver
This is a bit of a niche problem, but add docs and better message showing what's going on.
* Increase timeout numbers for ddev-webserver
* Increase timeout numbers for ddev-router
No changes.
> Add docs and longer timeout for restore-snapshot and start, fixes #1477, fixes #2542

- cmd/ddev/cmd/auth-ssh.go
- pkg/ddevapp/ssh_auth.go
- pkg/ddevapp/ssh_auth_test.go
#2597 reported that `ddev poweroff && ddev auth ssh` failed. This was a regression from v1.15
#2608 reports that only default keys are added by `ddev auth ssh` in recent alphas, although this seems to be the expected behavior, see https://www.ssh.com/ssh/add. It certainly isn't what we have had before. 
Make sure that the ddev-ssh-agent is started with appropriate environment variables.
* Added turning off the testsite to TestSSHAuth
> Make sure env vars are added to ssh-agent start and all keys are loaded, fixes #2597, fixes #2608

- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/magento.go
- The Magento2 DevDoc links are outdated (version 2.3 instead of 2.4)
- The Magento 2 Quickstart doesn't work with latest Magento 2.4.1 version because of missing elasticsearch.
- Added Magento 2 base-url to the install command instead of running it manually afterwards and having to flush the cache.
- The magento2 project type doesn't work with latest Magento 2.4.1 because it runs with php7.2 which is not supported
I added missing elasticsearch from ddev-contrib to the doc
https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/elasticsearch
I removed `magento2ConfigOverrideAction` from the magento2 project type to use standard php7.3 which is minimum requirement for Magento 2.4.1
Just folow the Magento 2 Quickstart.
It would be awesome to cover all quickstarts with …
> Magento2 Quickstart improvements, fixes #2600, fixes #2602

- .buildkite/testbot_maintenance.sh
- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/delete-images.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router_test.go
- pkg/nodeps/utils.go
* #2387 requests a --yes/-h flag for `ddev composer create`
* buildkite testbot maintenance wants a --yes flag for `ddev delete images`
* buildkite testbot maintenance needs nodejs to install markdownlint-cli
Add flags. Update buildkite config.
> Add --yes -y flags to composer create and delete images, fixes #2387

- scripts/install_ddev.sh
install_ddev.sh is broken when trying to download ddev v1.16.0-rc1.
Improve the version_compare (see [gist](https://gist.github.com/Ariel-Rodriguez/9e3c2163f4644d7a389759b224bfe7f3#gistcomment-35184970) so it does the right thing.
Output useful information when a curl fails
It would be great to figure out a good way to test this script.
> Make install_ddev.sh work with v1.16.0-rc1 and hopefully future versions

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/typo3.go
Both TYPO3 and Drupal7 had configOverrideActions that set the PHP version to 7.2, and neither requires it.
In a recent TYPO3 test (with ddev v1.16.0-rc1), with latest deb.sury.org build PHP 7.2.34-8+0~20201103.52+debian10~1.gbpafa084 failed, even though 7.2.34-4 had worked fine. 
> An exception occurred while executing 'DELETE tags2, cache1 FROM cf_cache_pages_tags AS tags1 JOIN cf_cache_pages_tags AS tags2 ON tags1.identifier = tags2.identifier JOIN cf_cache_pages AS cache1 ON tags1.identifier = cache1.identifier WHERE tags1.tag = 'redirects'': Malformed communication packet
* Remove the php7.2 setting for Drupal7 and TYPO3. Both should work fine with the default php7.3. This seems to make more sense than chasing an obscure "malformed communication packet" issue in an obsolete PHP …
> Remove php7.2 config override for typo3 and drupal7

- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/config.go
- pkg/version/version.go
`composer self-update` couldn't work because the /usr/local/bin/composer was root-owned
Make it writable by all users. 
* Make composer, ddev-live, and terminus all world-writeable
`ddev exec composer self-update`
> Make composer updateable/writeable by user in ddev-webserver, fixes #2614

- .github/workflows/activate.yml
Simple PR to activate GitHub Actions on the `master` branch (both for commits to that branch and all PRs that target that branch), so that we can continue working on https://github.com/drud/ddev/pull/2615 more easily
> Activate GitHub Actions

- containers/ddev-dbserver/database-versions
- pkg/version/version.go
The recently released versions of MariaDB have a regression that affects all PHP versions < 7.3. https://jira.mariadb.org/browse/MDEV-24121
Pin MariaDB versions to the previous minor release. 
Try installing TYPO3 v10 using php7.2. I think it will succeed, whereas it would have failed with php7.2 and ddev v1.16.0-rc2
Some kind of manual test that's more authoritative would be better
I'd love to have a test that clearly demonstrates this, so we could know when to unpin these releases.
> Pin mariadb versions to previous release because of regression that affects php7.2

- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
A new version of ddev-live client is out, and it could break ddev-live tests. See what happens.
> Bump webtag for latest ddev-live

- pkg/version/version.go
Tagging built images for v1.16.0
> Bump images to v1.16.0

- pkg/ddevapp/providerDdevLive.go
- pkg/ddevapp/providerDdevLive_test.go
Recently we've been seeing Intermittent Failures of TestDdevLivePull
Improve ddev-live provider to make TestDdevLivePull work better and use current commands.
> Improve ddev-live provider to make TestDdevLivePull work better

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
drush launcher v0.8.0 has some problems, at least for CI, see https://github.com/drush-ops/drush-launcher/issues/82
Upstream image has rolled back to 0.7.4, and this picks that up.
> Use version 0.7.4 of drush launcher from upstream

- cmd/ddev/cmd/flags.go
An empty defValue for string flags leads to panic.
This patch implements the missing case for the string type.
Create a custom command with a string type flag and without providing a DefValue.
#2631
#2493
> Fix validation error for string flag, fixes #2631

- cmd/ddev/cmd/commands.go
In case of missing usage annotation no command name is shown anymore. This was accidentally removed with https://github.com/drud/ddev/commit/c34907d7d6cd836e0571ad0b0effcaa1d48a7b83.
This patch reintroduces the default value again.
Create a custom command without the `usage` annotation and check the command name is shown properly on the help screen.
#2633
#2452
> Add default usage of custom commands again, fixes #2633

- containers/ddev-dbserver/README.md
- containers/ddev-router/etc/nginx/conf.d/default.conf
- containers/ddev-router/gen-cert-and-nginx-config.sh.tmpl
- containers/ddev-router/healthcheck.sh
- containers/ddev-router/nginx.tmpl
- containers/ddev-router/testtools/testgen.sh
- pkg/version/version.go
#2648 : In ddev v1.16.0 and v1.16.1, a `ddev start` might result in a site that was unreachable; the newly started site would get "503: No ddev back-end site available."
It turns out that this was timing related, but more importantly, 
* the listener (`-watch`) docker-gen process creates a script which is then run to create the nginx configuration
* However, the script is not recreated if docker-gen does not see that it changed
* However, the generated script had hostnames in it (container names) but it did *not* include the ports from HTTP_EXPOSE or HTTPS_EXPOSE. So if those came through in separate events, docker-gen would read the later events but decide that because the generated script did not change, it did not need to be recreated (and the script didn't get run... so the nginx …
> Solve problem with unreachable sites due to ddev-router config fail, fixes #2648

- docs/users/cli-usage.md
I wasn't 100% clear on whether I could/should delete snapshots on my own, or use a ddev command.
Updates the docs to explain that yes, you can just delete them however you want.
> Docs: Add a little extra info on snapshot deletion [skip ci][ci skip]

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
PHP 8.0.0 has been released; some other things may have changed in upstream deb.sury.org. Pick up new upstream versions from ddev-images.
> Bump webserver to pick up php8.0.0

- .github/workflows/multiplesites.sh
- .github/workflows/nginx-tmpl.yml
The github actions added recently to test nginx.tmpl are a bit onerous and run too many permutations. Slim it down. 
These will be removed completely in #2615
> [tests only] Less github actions test on nginx.tmpl

- pkg/version/version.go
In preparation for release, bumping ddev-router and ddev-webserver versions to v1.16.2
> Bump image versions to v1.16.2 for release

- pkg/ddevapp/templates.go
It makes sense for PHPMyAdmin (dba) to use the root user instead of the 'db' user.
> Use root user for PHPMyAdmin

- docs/users/extend/database_types.md
Just a propopal to give DDEV users a clear hint for mysql 5.7 support (which still runs on many  webspace hosting providers, therefore having the same version on DDEV is very helpful). 
Best regards.& thanks for providing DDEV!
> Update database_types.md for mysql 5.7

- cmd/ddev/cmd/xdebug_test.go
- pkg/ddevapp/config.go
In ddev v1.16.3, a bug was discovered where `ddev xdebug on` failed if `composer_version` was set to 1 or 2 in the project .ddev/config.yaml.
Previously, xdebug was disabled in the Dockerfile build by `disable_xdebug`; unfortunately, running that as root (as is done in the build). This left key files owned by root, so they couldn't be manipulated by enable_xdebug and disable_xdebug.
Now, it just uses XDEBUG_MODE=off to accomplish the same thing.
This is effective only for PHP7.2+, but that should cover all the bases we need to cover. 
```
ddev config --composer-version=2 --php-version=7.4
ddev start
ddev xdebug on
ddev exec php --version
```
Should show xdebug
Then test to see that xdebug actually works.
In TestCmdXdebug I changed to set `composer_version: 2` before starting
In the future …
> Use XDEBUG_MODE to disable xdebug in Dockerfile, not disable_xdebug

- docs/users/cli-usage.md
With the release of TYPO3 11 this version should be used for new installations.
> Use TYPO3 11 for new installations by default

- cmd/ddev/cmd/auth-ssh.go
The docs for `ddev auth ssh` were still referencing `--keydir` as the long name of the `-d` switch.
Corrected the long description to display `--ssh-key-path` instead.
`ddev auth ssh --help` and see the glory of the correct switch. 😄
> Update auth ssh doc to correct --ssh-key-path switch name

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
- Makefile
Previously, CircleCI only supported Ubuntu 16.04 as builder, nothing newer. But suddenly they have 20.04
* Use the Ubuntu 20.04 builder
* Bump the CircleCI build cache to v15 to refresh it
* Homebrew seems not to have a bottle for makensis for Linux any more, see https://github.com/Homebrew/homebrew-core/issues/67825 - Instead use --build-from-source to see if it can work
> [tests only, circleci] Use Ubuntu 20.04 for builds, bump cache

- docs/users/extend/additional-services.md
Updating the SOLR "Installation" steps to be a 3 step process with clearly marked steps. The previous list implied there were more than 3 steps, and was confusing as to which was required, and which was optional. Numbering the steps clears the ambiguity and implies simplicity.
> Improve 3rd-party Apache SOLR setup in additional-services.md

- docs/users/cli-usage.md
Minor change in the .env file for wp-bedrock installation
The `.env` file for Bedrock example is not complete. It miss 2 important variables that are important:
* `WP_SITEURL` (because bedrock put the `wp` install behind the `wp` directory!)
* `WP_ENV` (by default it consider the environment as production which is not the case generally when you use this magic tool ddev ! )
It fix a reasonable good values for the 2 environment variables
Install `ddev` on a bedrock-wp site, and check: 
* if WP_SITEURL is missing then you will have broken link in bedrock
* if WP_ENV then bedrock will not show you the plugin to update (as a classic bedrock dev environment is doing)
I don't know how to automate this kind of tests, sorry!
No linked issues.
It's a documentation modification.
*By the way thanks …
> Update cli-usage.md for bedrock

- pkg/ddevapp/drupal.go
`public/sites/default/drushrc.php` being written when settings disabled.
Skips writing the file when settings are disabled.
On a D7 site
```
ddev config \
--docroot=public \
--disable-settings-management
```
> Ignore drushrc.php writing when settings disabled

- pkg/servicetest/servicetest_test.go
TestServices has been failing randomly but more frequently. It looks like the solr process isn't fully "up" when the container is ready.
Wait a couple of seconds before checking solr in TestSolr
> [tests only] TestServices has been failing a lot, give solr a little time to come up

- cmd/ddev/cmd/testdata/TestMariaMysqlConflicts/config.yaml.mariawithemptymysql
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/shopware6.go
- pkg/nodeps/mariadb_values.go
- pkg/nodeps/mariadb_values_linux_arm64.go
MariaDB 10.3 is required by several CMSs now, we're leaving 10.2 behind. #2232 
Change the default to 10.3. 10.2 is still fully supported, and any project that has it configured will still use it.
> Bump default mariadb version to 10.3, fixes #2232

- cmd/ddev/cmd/snapshot.go
- cmd/ddev/cmd/snapshot_test.go
- docs/users/cli-usage.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
I want be able to list and delete existing db-snapshots. A command or option is missing.
Add a `--list` option to snapshot command.
Add a `--cleanup` option to snapshot command.
Code should not affect any existing project.
Related snapshot and restore-snapshot issues are at https://github.com/drud/ddev/issues?q=is%3Aissue+is%3Aopen+snapshot
> Add --list and --cleanup options to snapshot command, for #1163

- docs/users/developer-tools.md
`ddev composer` does not work in every scenario (e.g. `ddev composer --version`). This PR adds examples and workarounds to the docu based on #2547 and Slack exchange from 2020-21-30.
> [docs only] Add "Limitations using ddev composer"

- mkdocs.yml
The menu entries "Shell completion" and "Bach and Zsh Completion" did the same thing. Removed the latter.
WARNING:
My local copy behaves differently than the live page: it shows only the first h3 submenu level instead of all h2 and h3. Not sure why...
> Remove duplicate menu entry for shell autocompletion in docs

- pkg/testcommon/testcommon_test.go
On Windows, TestGetLocalHTTPResponse gets an enormous number of failures due to a WIndows docker bug, https://github.com/docker/for-win/issues/10008
As a result, skip this one on Windows. The Docker failure happens elsewhere also, but this one pops up again and again.
> Skip TestGetLocalHTTPResponse on Windows

- docs/users/extend/config_yaml.md
PHP 8.0 is missing in the supported versions in the config section
/
no testing needed
no testing needed
#2553
> [Docs] Add PHP 8.0 to the supported php versions

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
#2515 points out that if you reuse an existing snapshot name it makes a mess
Check first
`ddev snapshot --name=something && ddev snapshot --name=something` should give an intelligible error
Added this situation to the main test
> Give an error on duplicate snapshot anme, fixes #2515

- pkg/ddevapp/apptypes.go
#2534: In Drupal 8/9 there isn't a reason any more to go to the docroot on `ddev ssh` or `ddev exec`, since drush works in the project root.
In D8/D9, `ddev exec pwd` and it should be /var/www/html
People may need to know about this for some exec actions. Add to release notes.
> Stop setting working_dir to docroot in Drupal8+, fixes #2534

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
#2725  - hardened webimage needs to allow relinking of drush
Open up /usr/local/bin permissions so that non-privileged user can link drush in there on startup if it's needed.
> Hardened webserver needs to allow /usr/local/bin update, fixes #2725

- containers/ddev-webserver/Dockerfile
- docs/users/step-debugging.md
Drush launcher is no longer used, remove references to it.
> Remove drush launcher config from web image [skip ci][ci skip]

- pkg/nodeps/mariadb_values_darwin_arm64.go
I discovered working on an M1 machine that although the mariadb default was changed to 10.3 on amd64 and linux_arm64, it got lost on darwin_arm64.
Bump it.
> MariaDB default didn't get changed to 10.3 for M1 [skip ci][ci skip]

- pkg/dockerutil/dockerutils_test.go
TestComposeWithStreams was fragile expecting exact input, which is broken in upcoming Docker release. 
Use assert.Contains() instead of assert.Equal()
> Improve fragile test TestComposeWithStreams

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
* PHP8.0 did not previously have redis and memcached extensions, but they're now available upstream.
* Drush launcher is completely removed (upstream)
> Bring in php8 extensions from upstream

- pkg/ddevapp/ddevapp.go
In upcoming docker-compose in Docker Desktop, they have
buldkit builds turned on, using native docker build. It makes
a big mess visually and isn't very useful for our small web/db build.
COMPOSE_DOCKER_CLI_BUILD="0"
`ddev start` on Windows with new Docker. It should look like it has in the past. See https://github.com/docker/for-win/issues/10008#issuecomment-766654081
> Turn off buildkit build in ddev start

- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
Container config validation errors can be a little confusing as, while a previous version may have (at one point) been "valid", the current version of ddev may no longer actually support it. Note: this came up when a project which worked on previous Macs (using MariaDB 10.0) would show this error because of the new Apple Silicon arm64 architecture; of which MariaDB does not include packages for this version.
Changes the verbiage of "invalid" to "unsupported" and as specifies that it is ddev (and current architecture) that does not support the requested version.
Specify a version that isn't supported and check that the message matches the PR.
Not sure if this is tested anywhere?
Doesn't affect anything, just a better error message.
> Improve DDEV configuration validation errors (php_version, mysql_version, etc.)

- .circleci/config.yml
- pkg/servicetest/servicetest_test.go
We've moved a lot of tests to GitHub actions, so we can build less stuff in CircleCI. 
Stop some CircleCI tests
Thanks to @dennisameling !
The next step, could be taken in this PR, is to test only the things that require secrets in CircleCI (pantheon, ddev-live, etc.).
> Remove several circleci jobs as github actions is doing them

- Makefile
Use go 1.16-rc1 to build M1 builds
> Use go 1.16-rc1 to build M1 builds

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/version/version.go
Since the beginning of magento/magento2 support we've installed magerun and magerun2 in /usr/local/bin, but all instructions and expectations say to use bin/magento, the composer-installed binary.
Remove magerun, magerun2.
> Remove magerun from web container as people use composer-installed version

- cmd/ddev/cmd/share_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
A couple of unreliable tests; one turned off for Windows, the other using a longer timeout.
> Minor test improvements (tests only)

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/dockerutil/dockerutils_test.go
- pkg/version/version.go
#2772: The yarn key expired again this year as it seems to on Feb 1 every year. 
But there's a new installation technique, so this uses the new technique. It gets a new minor version of yarn, but otherwise no change.
> Update yarn install to fix replaced yarnpkg key, fixes #2772

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/version/version.go
#2772 points out that any `apt-get update` inside the web container is now broken due to expiration of yarn key.
#2773 fixes this for ddev v1.16 and will be released as v1.16.6 today
However, we need this fixed in the master version, to go into ddev v1.17.0-alpha4, which should also get released today.
> Use updated upstream for yarn fix, fixes #2772

- docs/index.md
One link to brew.sh was linked relatively to the docs of ddev itself which caused to create a https://ddev.readthedocs.io/en/stable/brew.sh instead of https://brew.sh.
Wrong link as stated above.
Updated it properly with a HTTPS scheme protocol.
Click on the brew.sh link. :)
It's a simple link anyone can test by clicking on it. Guess it's self-explaining enough.
https://ddev.readthedocs.io/en/stable/
Nothing
> Update index.md - link to brew.sh was not correct

- docs/users/cli-usage.md
Adding `drush site:install` and `drush uli` to the the Drupal 8 and [Drupal 9 Quickstart instructions](https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-quickstart) could help on-ramp new DDEV users faster, see #2769.
Adds Drush commands `site:install` and `uli` to D8 and D9 quickstart guide.
> Adds Drush site:install and uli to D8 and D9 quickstart

- containers/ddev-dbserver/files/docker-entrypoint.sh
- containers/ddev-dbserver/files/healthcheck.sh
- containers/ddev-dbserver/test/basic_database.bats
- containers/get_arch.sh
- docs/users/cli-usage.md
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
The db container shows healthy during a snapshot restore, meaning the project can come up and look healthy, but in reality it's still restoring.
* Make sure that db container shows unhealthy while restoring.
> Large snapshot restore shouldn't return until it's done

- cmd/ddev/cmd/config-global.go
- pkg/dockerutil/dockerutils.go
- pkg/globalconfig/global_config.go
The latest upcoming version of the Mac M1 preview for docker won't require special handling for host.docker.internal.
Remove the special handling.
> Remove special host.docker.internal handling for mac M1

- docs/users/performance.md
The setup.sh script previously seemed like a step under the `macOS Catalina (and above) warning:` heading. Once I looked at the markdown I realized that wasn't a heading, but instead just bold text. However it caused me a lot of confusion since I wasn't running the `setup.sh` script and everything was failing.
I re-ordered the text so it is clear that the general section is not a sub-section to the Catalina specific heading. Even if my change isn't what is desired, some structure change to indicate the correct associations would be great!
N/A
N/A
N/A
> Update OSX install step order for clarity.

- .github/workflows/container-tests.yml
- containers/ddev-dbserver/Dockerfile
- containers/ddev-dbserver/Makefile
- containers/ddev-dbserver/build_image.sh
- containers/ddev-dbserver/database-versions
- containers/ddev-dbserver/test/test_dbserver.sh
- containers/ddev-webserver/Makefile
- containers/get_arch.sh
- pkg/version/version.go
ddev-dbserver builds have been awkward to test; there weren't targets for each version, so you had to wait forever, etc.
* Provide a separate target for each build. For example `make mariadb_10.3_both`
* Provide a target to build all, `make build` or just `make`
* Provide a target to test each one, like `make mariadb_10.3_test`
* Provide `make test` for the do-all build and test
> Refactor ddev-dbserver builds

- containers/ddev-dbserver/files/docker-entrypoint.sh
- pkg/version/version.go
#2765 : `ddev snapshot restore` can fail when there is already a .DS_Store file in the snapshot directory and when the snapshot also contains a .DS_Store
Remove .DS_Store before restoring
> Remove .DS_Store files before restoring snapshot, fixes #2765

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
It's an oddball issue but in #2799 a user added extra apache packages and those packages created /var/lock/apache too early, so they got root privs and weren't writeable.
Might as well create the directory and set permissions earlier to prevent this in the future.
> Process /var/lock/apache2 in ddev-webserver Dockerfile, fixes #2799

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Upstream from php-base has been rebuilt with latest, including php8.0.2
> Bump upstream for ddev-webserver, includes php8.0.2

- Makefile
Before go 1.16 was released we used a hodgepodge of go1.15 for non-M1 and go1.16-beta for M1 builds. 
Now consolidated since go 1.16 is out.
> Use only go 1.16 now that it's released

- .buildkite/testbot_maintenance.sh
- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- .github/workflows/linux-setup.sh
- .github/workflows/selfhosted-upgrades.sh
- docs/developers/scripts/windows_buildkite_setup.sh
- docs/developers/scripts/windows_github_agent_setup.sh
We've seen the error from bats a couple of times recently and already fixed it in the travis build. 
```
/home/circleci/ddev/containers/ddev-dbserver/test/functions.sh.bash does not exist
/usr/local/libexec/bats-exec-suite: line 20: let: count+=: syntax error: operand expected (error token is "+=")
bats tests failed for DB_TYPE mariadb DB_VERSION=5.5 TAG=v1.17.0-alpha6
```
This fixed with this approach in the travis build. But there it was npm-installed and a new version. Here it's homebrew and apparently not new. 
Anyway, here's hoping. This only affects the nightly build, because that's the only place we're doing container build (which uses bats) on circleci.
This also removes bats-core from lots of places since we only use it on Linux these days.
> [tests only] git install bats-core since it doesn't seem to be working from package

- containers/ddev-ssh-agent/files/entry.sh
- pkg/version/version.go
The removal of sudo from ddev-ssh-agent missed one thing - a chown that can't work or is unnecessary.
> Experiment with removing chown from ddev-ssh-agent startup script

- pkg/dockerutil/dockerutils.go
#2815 reports that OpenSUSE Tumbleweed is building docker with the version "20.10.3_ce", and so we don't consider it valid when checking docker version.
Strip the suffix "_ce" from docker version before processing. This is a bit fragile, but it fixes the issue with opensuse. 
Tested with `ddev start` on OpenSUSE.
> Strip _ce from docker version if added by some linux distros, fixes #2815

- .buildkite/linux-amd64.yml
- .buildkite/linux-arm64.yml
- .buildkite/macos_container.yml
- .buildkite/test.sh
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2.yml
Experimenting with linux-arm64 and linux-amd64 on buildkite. It might save us some money on travis-ci.
> Add linux types for buildkite-agent

- .gitpod.Dockerfile
- .gitpod.yml
- CONTRIBUTING.md
- README.md
- docs/developers/building-contributing.md
Gitpod is pretty cool. Add gitpod support so that people can use build and test ddev.
* Add gitpod.yml for golang setup
> Add gitpod support to ddev [skip ci][ci skip]

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/version/version.go
magerun and magerun2 were mistakenly removed from the web image in #2768 
Bring it back in. Turns out it wasn't exactly completely removed, and this should be a better installation anyway
`ddev exec magerun2`
> Reintroduce magerun and magerun2

- .buildkite/test.sh
- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
#2832: deb.sury.org's key is going to expire, which will wreak havoc on people who use `webimage_extra_packages` after 2021-03-17. 
Get the new key into ddev-webserver image.
`docker run --rm drud/ddev-webserver:v1.16.7 apt-key list` and check the expiration of deb.sury.org key (last one)
> Update to new deb.sury.org key, fixes #2832

- .gitpod.yml
Gitpod requires `sudo docker-up` to run docker commands.
That process run indefinitely.
The other terminal that run `make` command and can show progress and becomes available for additional commands of the user is "hidden" as a second terminal.
Switch between the terminal order, so `sudo docker-up` is on secondary terminal, and `make` commands runs in main terminal.
> move Gitpod's docker-up to a "secondary" terminal

- .circleci/config.yml
- .circleci/linux_circle_vm_setup.sh
- .travis/linux_travis_arm64_setup.sh
- pkg/ddevapp/providerDdevLive_test.go
CircleCI now has arm64 testing, and it probably will be more convenient and certainly more scalable for us than Travis.
Add CircleCI arm64 build.
> Add circleci-based arm64 testing

- containers/ddev-webserver/ddev-webserver-base-files/etc/php/5.6/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.0/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.1/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/version/version.go
Since ddev is a development toolkit item, it would make sense to enable zend assertions by default. It was disabled.
This enables zend assertions.
From the php manual:
```
// Make an assertion that should fail
assert('2 < 1');
assert('2 < 1', 'Two is less than one');
```
I don't think testing is needed. We're just enabling something built-in to PHP.
PHP asserts are now enabled by default. If this is not desired, see how to override PHP directives in https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-php-configuration-phpini and set `zend.assertions` to `0` or `-1` as desired.
> Enable zend assertions by default

- .circleci/linux_circle_vm_setup.sh
This patch bumps NSIS to the last stable release 3.06.1 with Linux builds. This ensures we get the same result on MacOS and Linux but does not influence the production release cycle.
> Bump NSIS to 3.06.1 for Linux builds

- cmd/ddev/cmd/ssh.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
On occasion, app.Exec() will try to access a container that isn't running. This can happen especially when a container has died, especially a 3rd party service container.
Check to see if the container exists and is running.
> Don't let app.Exec() run against non-running container, fixes #1858

- pkg/ddevapp/templates.go
The TYPO3 internal file `AdditionalConfiguration.php` was sometimes mistakenly referred as `AdditionalSettings.php`.
Rename all occurrences of AdditionalSettings.php to AdditionalConfiguration.php.
It is only about documentation in comments and test data.
It is only about documentation in comments and test data. No tests required.
None.
No.
> [DOCS] Rename AdditionalSettings.php to AdditionalConfiguration.php

- docs/users/providers/pantheon.md
Documentation is different than the instructions in `.ddev/providers/pantheon.yaml.example`
I confirmed this syntax is working.
> Use the correct variable name for Pantheon token

- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils_test.go
In TestContainerWait, on old mac running Catalina, the timeout happened to fast I think. 
Give it more seconds to complete.
> [tests only] Wait a little longer on healthcheck startup

- pkg/util/utils.go
#2860: GetContainerUIDGid() can cause a panic.
Check to make sure user.Current() returns successfully.
unset USER
ddev start
> Make sure missing USER env doesn't cause panic, fixes #2860

- .buildkite/test.sh
- .circleci/config.yml
- .github/workflows/build-and-test.yml
- .spellcheckwordlist.txt
- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/root_test.go
- docs/users/troubleshooting.md
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router_test.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon.go
- pkg/util/prompt.go
- pkg/util/utils_test.go
#2533: In the current state of WSL2, there's quite a lot of confusion in the computer about how to look up hostnames. However, ddev already has warnings to users, and it rarely matters to users who use *.ddev.site.
* Improved docs, minor addition to code that warns WSL2 users
* Rename DRUD_INTERACTIVE  environment variable to DDEV_INTERACTIVE
> Touch up Windows WSL2 hosts file support and docs, rename DRUD_INTERACTIVE, fixes #2533

- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/debug-nfsmount_test.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/homeadditions_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/pause_test.go
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/start_test.go
- cmd/ddev/cmd/stop_test.go
- cmd/ddev/cmd/xdebug_test.go
- pkg/ddevapp/router_test.go
On new ddev version, we really want people to do a poweroff, so the ddev binary isn't interacting with older/odd versions of containers. 
* Ask permission to poweroff if version has changed.
* `ddev start -y` to skip this, or `yes | ddev start` to automatically accept
* Edit last_started_version in ~/.ddev/global_config.yaml
* `ddev start`
Try the same with `ddev start -y`
Added TestPoweroffOnNewVersion
> Poweroff if new ddev version, fixes #1786

- Makefile
It turns out that https://github.com/gerardog/gsudo is maintained robustly, and the downloadable binary is signed. 
Switch from using mattn/sudo to https://github.com/gerardog/gsudo
> Use gerardog/gsudo instead of mattn/sudo on Windows sudo.exe

- pkg/ddevapp/instrumentation.go
wsl2 is essentially an OS environment of its own. It's separately supported, etc. We need to be able to see it separately in Amplitude.
Report wsl2 as OS alongside Windows.
In WSL2, do something and see how it's reported to Segment.
> Report WSL2 to segment as separate operating system

- cmd/ddev/cmd/dotddev_assets/commands/web/xdebug
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.2/mods-available/xdebug.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.3/mods-available/xdebug.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/7.4/mods-available/xdebug.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.0/mods-available/xdebug.ini
- pkg/ddevapp/ddevapp_test.go
- pkg/version/version.go
After running `ddev xdebug on`, the error are not "pretty" stack traces like I was expecting. 
They looked like this: 
What I was expecting was an output more like this: 
Xdebug.ini config changes to enable stack trace outputs. 
- Turn on xdebug. 
- Cause an error.
I don't think this affects anything else.
> Enabling develop mode in xdebug so we get the pretty stack trace outputs

- .github/ISSUE_TEMPLATE/Bug_report.md
- scripts/test_ddev.sh
I noticed that test_ddev.sh was depending on the docker desktop version script... but it will most often
> test_ddev.sh should not depend on other scripts [skip ci][ci skip]

- mkdocs.yml
#2885: Broken left sidebar reference to provider integration intro.
> Fix broken docs sidebar, fixes #2885 [ci skip][skip ci]

- docs/index.md
- docs/users/shell-completion.md
- scripts/install_ddev.sh
Tried to update ddev with `ddev poweroff && brew upgrade ddev`to latest version and got the following error:
``` 
Formulae found in multiple taps: 
* drud/ddev/ddev
* drud/ddev-edge/ddev
```
Updated the existing upgrade command with `ddev poweroff && brew upgrade drud/ddev/ddev` to match correct package/tap.
> Update brew upgrade command

- .circleci/config.yml
Since all the push tests have (significant) side-effects, we should only be doing them in one place. With this change we'll do them only in CircleCI's arm64 test.
> Test push only on one test system

- docs/users/extend/additional-services.md
- docs/users/faq.md
#2744: It's possible to use ambiguous service names in client configuration. This changes the docs to suggest using names like `ddev-<projectname>-solr` instead of the default (and sometimes ambiguous) `solr`
@tgaertner I'd definitely appreciate your review of this, and would appreciate if you could re-test. I think this will fix the problem you described so clearly.
> [docs only] Use fully-qualified name for service when configuring in client, fixes #2744 [skip ci][ci skip]

- .buildkite/test.sh
For some time the buildkite script has killed and restarted docker... but that doesn't work on latest docker desktop 3.3.0 for mac M1. So removing that stanza.
> Killing and restarting docker doesn't work on latest docker for mac

- scripts/macos_ddev_nfs_setup.sh
The latest Docker for Mac M1 tech preview has changed its networking again... to an easier model that doesn't require special handling for mac M1. 
Revert the special architecture-based handling.
> Revert macos_ddev_nfs_setup script because docker mac m1 has gone back to old networking

- .circleci/config.yml
- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
ddev-live binary is now available for arm64 from the canonical source. Use it.
> Use the real ddev-live latest binary

- .gitpod.Dockerfile
This reverts commit 9e5228aae47443e87b803c19338598f336a9ba11, #2897 
It turns out that while 20.04 works for building images... you can use ddev or anything else useful.
> Revert "Latest docker (version 20) (#2897) [skip ci][ci skip]"

- mkdocs.yml
There's no reason for the "developer docs" to be in ddev.readthedocs.io
Remove them from the index.
> Remove developer docs from index [skip ci][ci skip]

- cmd/ddev/cmd/dotddev_assets/providers/ddev-live.yaml.example
The latest version of ddev-live client seems to not always download to a predictable filename, so this makes sure we know the actual filename and use it. Updates the ddev-live provider example only.
> Fix ddev-live provider example to use actual filename downloaded as db

- containers/ddev-router/nginx.tmpl
- pkg/version/version.go
This experimental PR might solve #2805, where some (mostly WSl2?) IP addresses get resolved wrong. Maybe.
Use the name of the container, instead of using its IP address.
Manual testing is not likely to recreate the bug, but general testing should be extensive, but it should at least be tested on WSL2.
> Use upstream hostname instead of IP for upstream in ddev-router, resolves #2805

- cmd/ddev/cmd/dotddev_assets/providers/acquia.yaml.example
- cmd/ddev/cmd/dotddev_assets/providers/ddev-live.yaml.example
- cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example
- cmd/ddev/cmd/dotddev_assets/providers/rsync.yaml.example
- pkg/ddevapp/providerDdevLive_test.go
* The `ddev-live push ddev-live` (and as a result TestPushDdevLive) were creating a backup every time, because that's what ddev-live does.
* As a result we hit the backup quota and everything broke
* Change the example to delete its backup after pushing 
* Change the test to use a configurable db backup (environment variable)
> Change testdata for db backup to env var for ddev-live

- cmd/ddev/cmd/dotddev_assets/providers/acquia.yaml.example
I noted on testing `ddev push acquia` that there was a problem with drush rsync; apparently the aliases weren't fully populated.
This adds the drush core:init command to make sure those get loaded.
> Make sure drush knows about acquia aliases

- docs/index.md
We've opted out of GitHub Sponsors. Remove doc pointing to it.
> Remove github sponsors from docs/index.md [skip ci][ci skip]

- cmd/ddev/cmd/dotddev_assets/providers/platform.yaml.example
This just removes a spurious commented-out line in the platform.yaml.example
> Remove commented line in platform example [skip ci][ci skip]

- cmd/ddev/cmd/dotddev_assets/providers/acquia.yaml.example
- pkg/ddevapp/providerAcquia_test.go
Another round of getting stable Acquia. 
It turns out that `acli remote:aliases:download` puts drush aliases into ~/.drush, but drush by default doesn't load from there. acli gives a message saying you need to `drush core:init` to get it to find them, but that doesn't have anything to do with it AFAICT. What's needed is to use an `alias-path` somewhere. This PR changes to use it in the actual drush command.
> Specify remote alias locations for acquia integration

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
In preparation for v1.17.0 release, build new images.
Bump to new upstream php image from ddev-images
> Bump images to v1.17.0

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/ddev-webserver/tests/ddev-webserver/test.sh
- pkg/version/version.go
* v1.17.0 didn't have php7.*-imagick enabled or installed, see #2934 
* uploadprogress was also missing I think
* Adds php8.0-xmlrpc
Add those from upstream
php -i and look for the missing items
Added a new container test to look for key php extensions.
> Pick up new php-imagick build from upstream, fixes #2934

- cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example
The instructions in the pantheon.yaml.example file say to:
In your project's .ddev/providers directory, copy pantheon.yaml.example to pantheon.yaml and edit the `project_id` and `environment_name`.
There is no `project_id`or `environment_name` in the file. Instead, `yourproject.dev` must be defined.
Updates the instructions to match the yaml.
Review the PR and test locally.
As an example, updating `yourproject` to the name of a Pantheon site and changing `dev` to `live` works for me.
N/A
N/A
N/A
> Update Pantheon provider instructions to match yaml.

- docs/users/extend/customization-extendibility.md
The documentation should reflect the [support of PHP 8.0](https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/)
> Fix docs to show available PHP versions including 8.0

- cmd/ddev/cmd/dotddev_assets/providers/acquia.yaml.example
- docs/users/providers/acquia.md
Add additional comments for Acquia provider feature
n/a
n/a
n/a
> Expand on Acquia provider documention

- .gitpod.Dockerfile
- .gitpod.yml
The gitpod check is likely not running because there is no init.
With the latest gitpod as of yesterday, there's no need to delay the make and ddev start
Add an init that does basic make and setup.
See also #2935
> gitpod: Move make into init in .gitpod.yml

- pkg/ddevapp/ddevapp.go
Docker-compose in 1.29.0 started saying this when building:
```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```
It's really annoying. DOCKER_SCAN_SUGGEST=false gets rid of it.
See https://github.com/docker/compose-cli/issues/1517
This is partially fixed in https://github.com/docker/compose-cli/pull/1532
But we don't ever need this advertising.
set environment DOCKER_SCAN_SUGGEST=false
`ddev start` with docker-compose v1.29.0. You should not see the annoying message.
> Turn off DOCKER_SCAN_SUGGEST to get rid of synk advertising

- containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
- docs/users/extend/in-container-configuration.md
- pkg/version/version.go
A number of people have their composer bin directory in /bin instead of /vendor/bin - this is fairly nonstandard, but there's no reason not to add that to the default path. 
Add /var/www/html/bin to path
Also adds ~/bin to front of $PATH, allows people to solve problems like this by just putting whatever they need in global homeadditions.
`ddev exec 'echo $PATH'`
> Add ~/bin and /var/www/html/bin to PATH in web container

- pkg/version/version.go
It's time to release v1.17.1, and nice to have a simple tag for ddev-webserver
> Bump web image tag for v1.17.1

- .github/workflows/linux-setup.sh
- cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example
- docs/users/providers/pantheon.md
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
The previous (drush rsync) technique for pulling a backup from Pantheon was just way too tedious, and could even fail due to connection timeouts
Use `terminus backup:get`. command and require that a backup already exists.
Use the "pull" sections of the new strategy with your site and see if it works.
> Change pantheon pull to use terminus backup:get

- cmd/ddev/cmd/describe.go
Several people chimed in on #2195 asking for `ddev status` as an alias for `ddev describe`.
Adds `ddev status`, `ddev st`, `ddev desc`. Otherwise functionality is unchanged.
* Try `ddev status` and `ddev status <projectname>`
You can test this PR at https://gitpod.io/#https://github.com/drud/ddev/pull/2955 - You can get to the base project with `cd /workspace/simpleproj` and then use `ddev describe` and `ddev status` to your heart's delight.
> Add ddev status as alias of ddev describe for #2195

- .gitpod.Dockerfile
- .gitpod.yml
- docs/developers/building-contributing.md
Routine gitpod maintenance. Since gitpod does not have docker 20.10, we need to install the buildx extension
When gitpod supports 20.10, this should be removable.
> gitpod: Install docker buildx so we can build images

- .github/workflows/container-tests.yml
- containers/ddev-dbserver/test/image_general.bats
- containers/ddev-router/test/containertest.sh
- containers/ddev-ssh-agent/Makefile
- containers/ddev-ssh-agent/test/functions.sh
- containers/ddev-ssh-agent/test/image_general.bats
- containers/ddev-ssh-agent/test/test.sh
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
We've periodically had problems with expiring apt keys inside the container, especially the web container
Check during build to see that keys are no closer than 90 days from expiration.
Tests only. 
This adds tests for each image to make sure that we're no closer than 90 days to expiration.
> Add tests to check for expiring apt keys in images

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
In preparation for release v1.17.2, update upstream and make sure all tests work.
> Bump upstream version for v1.17.2

- .gitpod.Dockerfile
- .gitpod.yml
Gitpod runs docker daemon by default.
`sudo docker-up` is no longer needed to run docker commands in Gitpod.
This PR removes all related commands from `.gitpod.yml`
Open this PR in gitpod, confirm that ddev runs as usual.
https://github.com/shaal/ddev-gitpod/pull/36
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/2984"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> `sudo docker-up` is no longer needed in Gitpod

- pkg/ddevapp/config.go
This adds the autogenerated ddev command "live" to the autogenerated .ddev/.gitignore
After updating to v1.17.2, ddev-using repositories would show `.ddev/commands/web/live` as newly added file.
Add file to .gitignore
1. `ddev start` in a clean git repository
2. Check if `git status` reports `.ddev/commands/web/live` as new file
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/2982"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Gitignore .ddev/commands/web/live

- pkg/ddevapp/router.go
#2981 - a docker restart or system reboot could leave the ddev-router in "stopped" state, where it seems lots of things can go wrong.
Related upstream problem on macOS amd64 and arm64: https://github.com/docker/for-mac/issues/5649
If `ddev start` finds the router in a state other than "running", it kills it off and thus restarts it.
Follow the recreation instructions in #2981
No new tests
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/2985"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Kill off ddev-router if it's not running, fixes #2981

- cmd/ddev/cmd/global_dotddev_assets/commands/web/blackfire
- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
DDEV-Local implements Blackfire agent V1 which is now deprecated and will be soon unsupported. This PR bootstrap the [upgrade to Blackfire agent V2](https://blackfire.io/docs/up-and-running/agent-upgrade#documentation).
I haven't been able to test this code and look forward to some procedures to do so.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/2970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Upgrade to Blackfire agent v2 in web container

- .buildkite/test.sh
- Makefile
- docs/developers/scripts/windows_buildkite_setup.sh
- docs/developers/scripts/windows_postinstall.sh
- docs/users/extend/additional-services.md
Ironically, we can't `make windows_install` on Windows :) This makes it harder to move signing to a windows machine. Working on it. 
Currently the result of `make windows_install` is 
```
λ make windows_install
building .gotmp/bin/windows_amd64/ddev.exe from ./cmd/... ./pkg/...
Signing windows ddev.exe...
Succeeded
Command line defined: "VERSION=v1.17.2-6-ge7e3ae63"
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
Processing script file: "winpkg/ddev.nsi" (ACP)
Plugin directories:
C:\Program Files (x86)\NSIS\Plugins\x86-unicode
Plugin not found, cannot call INetC::get
Error in script "winpkg/ddev.nsi" on line 415 -- aborting creation process
make: *** [Makefile:224: .gotmp/bin/windows_amd64/ddev_windows_installer.v1.17.2-6-ge7e3ae63.exe] Error 1
```
The contents of C:\Program …
> Make windows_install build on Windows

- containers/ddev-dbserver/test/image_general.bats
See #3004 - The upcoming key expirations on mysql 5.5 container are breaking nightly build, and there is no longer support for mysql 5.5. 
As a near-term workaround, stop testing the 90-day expiration for mysql 5.5
We'll see what happens with the next step, and when Jessie has a new apt key.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3006"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Temporarily skip apt key expiration test on mysql 5.5, for #3004

- .circleci/config.yml
Trying to reduce cost of CircleCI and decrease redundancy with github workflow. 
Use less in the normal build and also in the nightly.
The fundamental value of CircleCI at this point is
1. Testing on arm64
2. Testing forked PRs with (throwaway) secrets. Github can't do that.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3010"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Reduce how much circleci gets used

- .github/workflows/master-build.yml
- Makefile
The new github builds try to build chocolatey on interim revisions, and it blows sky-hi because choco can't accept something like 1.17.2-12-g7a20a436
Don't try to build chocolatey in that situation.
After this goes in we can re-add CHOCOLATEY_API_KEY to the repository
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3012"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't try to build chocolatey on interim revisions

- pkg/ddevapp/instrumentation.go
Segment costs > $100/month, and we have no funding, so it makes no sense to spend that money. We have switched to the free plan, which allows a far smaller number of packets.
Only report `ddev start` to segment.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3020"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Stop reporting anything but start to segment

- .buildkite/test.sh
On Windows buildkite we often see test runs fail just because the windows machine (or docker?) fail to successfully look up a (usually github-related) DNS address.
Attempt to prime the pump with a ping.
This may need to be done inside a docker container.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3016"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Windows often has first-time trouble with DNS lookups

- .github/ISSUE_TEMPLATE/Feature_request.md
Update GitHub's issue templates to hide helper text from issue display, and keep it visible only to the issue author.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3029"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Keep helper text visible only to the issue author

- pkg/ddevapp/drupal.go
Very minor nit, but no need to check whether the file is readable if it's not a DDEV environment.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3017"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Check ENV variable first before doing a FS stat in settings.ddev.php

- containers/ddev-dbserver/Dockerfile
- containers/ddev-dbserver/test/image_general.bats
See #3004 and #3006 - Old keys were preventing us from being able to test for expiring keys. 
Remove the ancient Jessie keys that are expiring/expired. They were apparently only needed for upgrades to Stretch in the first place.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove Jessie keys so we can properly test for expiring keys, fixes #3004

- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/sites-enabled/apache-site.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
- pkg/ddevapp/testdata/TestConfigOverrideDetection/.ddev/apache/apache-site.conf
- pkg/version/version.go
Some users have run into trouble with huge cookie payloads, both in nginx and apache. This doubles the relevant [nginx default value](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) is "large_client_header_buffers 4 8k;". This raises the size of the nginx buffers to "large_client_header_buffers 4 16k;"
Apache LimitRequestFieldSize  is doubled to 16380.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3034"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Increase ddev-webserver apache/nginx limit request field size for large cookie payloads

- containers/ddev-router/etc/nginx/nginx.conf
- pkg/version/version.go
Some users have had trouble with huge cookie payloads and ddev-router's (nginx default) large_client_header_buffers value.
The [default value](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) is "large_client_header_buffers 4 8k;". This raises the size of the buffers to "large_client_header_buffers 4 16k;"
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3033"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Increase ddev-router nginx large_client_header_buffers value for larger cookie payload

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
The docker images need to be refreshed and re-tagged. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3035"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update docker images for upcoming ddev v1.17.3

- .github/workflows/master-build.yml
We failed to get homebrew (edge) or AUR pushes in v1.17.3
AUR was partly a result of not having the right ssh key configured in secrets.
homebrew edge was due to a logic error. 
I'm manually pushed homebrew edge, and still have to do AUR manually.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3036"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix homebrew and AUR release push failures [skip ci][ci skip]

- .github/workflows/master-build.yml
We've had various build problems where SegmentKey wasn't included in the build. Might as well test for it in the build process. 
This adds an explicit test.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3037"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a test to make sure SegmentKey is working on release build

- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/router_test.go
- pkg/version/version.go
* composer 2.1.1 was released; it may solve some problems with 2.1.0
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3038"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump upstream Dockerfile again to get composer 2.1.1

- Makefile
In #3039 we stopped downloading winnfsd.exe and nssm.exe because they caused false virus checker warnings.
But we can't sign them then. Stop signing them.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3042"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't attempt to sign windows binaries we don't have

- .buildkite/test.sh
- cmd/ddev/cmd/root_test.go
Multiple attempts to solve #2979 on Windows. There seems to be some time difference in docker (or an error in behavior that I don't understand on Windows). 
If this doesn't solve it, maybe will just disable the test on traditional Windows. 
But if that is required, careful manual testing will be required first.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3043"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> TestPoweroffOnNewVersion : Try to get a reasonable behavior for start time, fixes #2979

- .buildkite/linux-amd64.yml
- .buildkite/linux-arm64.yml
- .buildkite/macos-m1.yml
- .buildkite/macos_container.yml
- .buildkite/macosdockerformac.yml
- .buildkite/test.sh
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2.yml
While working on my PR https://github.com/drud/ddev/pull/3039 there was a login issue with Docker so I was looking for a solution and found the docker-login plugin.
So far this looks to perform nice and no login issue occured.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use buildkite docker-login plugin instead of scripting `docker login`

- scripts/docker-desktop-version.sh
docker-desktop-version.sh mistakenly insisted on installation of xq
Affects only macOS buildkite builds.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3045"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docker-desktop-version.sh mistakenly insisted on installation of xq

- containers/ddev-webserver/Makefile
- pkg/version/version.go
I discovered that when doing a local `make` in ddev-webserver, the ddev-webserver-prod ended up overwriting the ddev-webserver build. It was very confusing.
Make it build with the right target. This only affects local builds, not push. also, `make VERSION=xxx DEFAULT_IMAGES=ddev-webserver` now will build just ddev-webserver, saving some dev time.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3049"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix bug in webserver Makefile where prod image can overwrite dev image

- containers/ddev-router/etc/nginx/nginx.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
- pkg/ddevapp/webserver_config_assets/apache-site-php.conf
- pkg/version/version.go
I noticed this error in the ddev-webserver log:
> the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:133
So somewhere in our doubling of the http2_max_header_size journey we did/did not switch to the new format. 
This switches to the new format in ddev-webserver and ddev-router.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3053"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use large_client_header_buffers instead of http2_max_header_size for nginx config

- pkg/ddevapp/templates.go
- pkg/globalconfig/global_config.go
Two tiny nitpicks found while doing a git-diff with white space highlighted :)
[skip ci][ci skip]
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3056"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove trailing whitespace in config templates

- containers/ddev-router/Dockerfile
- pkg/version/version.go
I happened to notice when looking at headers that ddev-router was using an older version of nginx (v1.18) rather than current stable (v1.20)
Update
`curl -I <projecturl>` and see headers.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3059"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use stable nginx as upstream image for ddev-router

- docs/developers/scripts/windows_buildkite_start.ps1
I was having trouble with the docker-login buildkite extension on a few Windows test runners. Found that the problem was that the Windows bash.exe was earlier in the PATH than the git-bash that we need to be running those scripts.
Add to PATH as we install
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3058"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure windows path is set with git-bash first [skip ci][ci skip]

- pkg/ddevapp/ddevapp_test.go
I noticed that the firewall was triggering on one of the tests on the M1 test runner. 
https://apple.stackexchange.com/questions/3271/how-to-get-rid-of-firewall-accept-incoming-connections-dialog pointed out that this can happen when you try to listen on something other than localhost.
So adding. I didn't find any other places that were likely to have this problem.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3061"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] only listen on localhost for xdebug test

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Time for a v1.17.6 release. Tag new images for it, use latest upstream images.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3062"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images to v1.17.6 for pending release

- Makefile
Bump golang build to v1.16.5
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3063"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump golang build to v1.16.5

- pkg/ddevapp/templates.go
- pkg/dockerutil/testdata/TestComposeWithStreams/test-compose-with-streams.yaml
- pkg/dockerutil/testdata/docker-compose.yml
The syntax for using a pre-existing network has changed, and docker compose v2 complains a lot about the old syntax. 
This just updates to the new syntax. 
See https://github.com/docker/compose-cli/issues/1856#:~:text=commented-,20%20minutes%20ago,-I%20am%20the
`ddev start` and see if you see the complaints in #3069 "network.external.name is deprecated"
No change.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3076"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use newer syntax for default network, fixes #3069

- pkg/ddevapp/templates.go
`ddev auth ssh` didn't work with docker-compose v2, see #3075 
The problem turns out to be that docker-compose v2 uses a different default name for the volume
Normal testing for `ddev auth ssh`
* `ddev auth ssh` and add some keys
* `ddev exec ssh-add -l` should show your keys
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3077"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make ssh-auth volume name explicit on creation, fixes #3075

- Makefile
- winpkg/ddev.nsi
Like before with WinNFSd and NSSM, now virus tools are recognizing gsudo as malicious software and so it gets not longer bundled to the installer but downloaded on demand during the installation to avoid issues.
gsudo is now downloaded on demand, so only local virus scanners can complain.
Remove the previous DDEV installation or in minimum remove the sudo.exe to see if it's correctly downloaded and installed with the new installer.
#2973
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3066"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Download gsudo on demand for Windows installer

- winpkg/chocolatey/ddev.nuspec
In attempting to get out of virus detection hell on Chocolatey, declare gsudo as a dependency, so it won't be scaneed.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3080"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Declare gsudo as dependency in chocolatey

- docs/index.md
- pkg/dockerutil/dockerutils.go
- pkg/version/version.go
Currently there are so many bugs on docker-compose v2 beta that it's unusable for most ddev purposes.
This PR checks for compose v2 and refuses to use it, and gives instruction. 
For a current list of incompatibilities and problems, see https://github.com/drud/ddev/pull/3083#issuecomment-873060929
Improve the version constraint to disallow v2
Add an extra error message explaining about v2
With compose v2 enabled, `ddev start`. It should fail, explaining why.
Then `docker-compose disable-v2` and `ddev start`. It should work. 
Hopefully we can revert this when compose v2 is fully functional and compatible.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3086"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't allow docker-compose v2 to be used

- containers/containers_shared.mak
- pkg/ddevapp/ddevapp.go
- winpkg/ddev.nsi
- winpkg/include/docker.nsh
I happened to notice that there were some remnants of Docker Toolbox support in the Windows Installer
Remove them
Use the installer and verify that it behaves.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3079"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove remnants of Docker Toolbox support from Windows Installer

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
* Bump new image names
* All tests on macOS amd64 will use docker-compose v2 to make sure that's all sorted out
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3081"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images to 1.17.7 in preparation for release

- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.10.6
- cmd/ddev/cmd/testdata/TestConfigMariaDBVersion/config.yaml.imagespec.10.6
- containers/ddev-dbserver/Dockerfile
- containers/ddev-dbserver/Makefile
- containers/ddev-dbserver/test/custom_config.bats
- containers/ddev-dbserver/test/testdata/mysql/collation.cnf
- containers/ddev-dbserver/test/testdata/mysql/utf.cnf
- pkg/ddevapp/config_test.go
- pkg/ddevapp/testdata/TestConfigOverrideDetection/.ddev/mysql/collation.cnf
- pkg/ddevapp/testdata/TestConfigOverrideDetection/.ddev/mysql/utf.cnf
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/dbimage-10.6/.ddev/config.yaml
- pkg/ddevapp/testdata/TestPkgConfigMariaDBVersion/mariadb-version-10.6/.ddev/config.yaml
- pkg/nodeps/mariadb_values.go
- pkg/nodeps/mariadb_values_darwin_arm64.go
- pkg/nodeps/mariadb_values_linux_arm64.go
- pkg/version/version.go
MariaDB 10.6 has been released to GA, see #3093
Unfortunately, in doing it they removed all the unsupported versions from their apt repositories, so we now can't build MariaDB 5.5, 10.0, or 10.1 :( so those are removed.
I opened https://jira.mariadb.org/browse/MDEV-26122 with MariaDB about the disappeared repositories. 
This PR does an end-run by removing the /etc/apt/sources.list.d/mariadb.list file, so `apt-get update` doesn't find it and freak out.
Build a project with MariaDB 10.6
The tests are driven by the ValidMariaDBVersions, so should be extended properly
This deserves a notice, but it shouldn't affect much else.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3096"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add MariaDB 10.6, solve problems with unsupported 5.5-10.1 versions, fixes #3093

- cmd/ddev/cmd/dotddev_assets/providers/acquia.yaml.example
- cmd/ddev/cmd/dotddev_assets/providers/platform.yaml.example
- docs/users/providers/acquia.md
- docs/users/providers/platform.md
- pkg/ddevapp/providerAcquia_test.go
The TestAcquiaPull test started failing. Debugging led to minor change in the suggested acquia config.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3100"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use 'drush -r docroot' in acquia provider as acquia seems to require it now

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/global_dotddev_assets/commands/host/heidisql
https://github.com/drud/ddev/issues/3051
In 2ff4f0b17, triming was added for readability of file paths but the code
does not actually depend on quotes around paths. It only cares for
commas to differentiate multiple paths in a given directive.
This partially reverts:
```
commit 2ff4f0b178734f602a4f26013fb48fb528ac0f30
Author: Andreas Hager <3351175+andreashager@users.noreply.github.com>
Date:   Tue Dec 29 05:47:40 2020 +0100
Create new HeidiSQL command for Windows and WSL2 (#2679)
```
Call `ddev drush --help` or any command help in `cmd/ddev/cmd/global_dotddev_assets/commands/web/`
NA
https://github.com/drud/ddev/issues/3051
I can't test on Windows, which was the focus of the original commit
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3057"><img …
> Do not trim quotes in findDirectivesInScriptCommand (#3051)

- docs/index.md
Fixes broken link in https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2 (step 17)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix link to brew.sh in docs

- .gitpod.yml
There's already a Gitpod badge in the PR description, the badge in comments is redundant and confusing.
Remove the badge from PR comments (but keep it in PR description)
Confirm that there's only 1 Gitpod badge in this PR, and no badge in this PR's comments 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3122"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove Gitpod badge from PR comments

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Platformsh/platform SEGV, Acquia ACLI SEGV, curl to certain hosts. Affects only Mac M1 users
* platformsh/platformsh-cli#1063
* #3116 
On macOS M1 architectures, the use of `curl` on some websites causes a SEGV in the web container, see [docker desktop 3.4.0 release notes](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-340)
> On Apple Silicon in native arm64 containers, older versions of libssl in debian:buster, ubuntu:20.04 and centos:8 will segfault when connected to some TLS servers, for example curl https://dl.yarnpkg.com. The bug is fixed in newer versions of libssl in debian:bullseye, ubuntu:21.04 and fedora:35
* Upgrades base image to debian:bullseye-slim
* DOWNGRADES nginx to 1.18 from 1.20 because nginx packages for bullseye are not available. ([Request …
> Use debian bullseye as base image for ddev-webimage, downgrades nginx to 1.18.0, fixes #3116

- docs/users/cli-usage.md
Just a minor file name correction in the laravel doc.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3123"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix typo on laravel quickstart [skip ci][ci skip]

- docs/users/cli-usage.md
Recently, my network was offline and I was unable to access the internet. No problems, I though, I develop locally in WSL. Unfortunately, I was getting DNS errors when attempting to access my site from Windows. I looked in the DDEV documents but couldn't see an obvious reference to my problem.
Once I found a solution, I did a search of the docs for `hosts`, but didn't see anything. 
- adds specific instructions for Windows browsers, to a WSL DDEV website when Windows is offline.
NA
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Windows WSL2 offline usage (windows-side hosts file) [skip ci][ci skip]

- docs/users/troubleshooting.md
credit to RFay, who included this approach elsewhere for creating index.php; seems useful to add here
without index.php, the ddev instance will throw errors
adds index.php with content
NA
NA
NA
NA
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] add index.php to command for "simplest possible" [ci skip][skip ci]

- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
- pkg/nodeps/values.go
On macOS, there's a specifically limited disk allocation in Docker Desktop, and when you run out very bad things happen.
* #863 
On Start and Import-db, check to see if we're in trouble on disk (defined as over 85% usage) and gives a warning.
This is hard to test without compiling. I changed the value in nodeps and ran it to test. 
No automated testing; not sure it's possible
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Check for adequate disk space in docker, fixes #863

- cmd/ddev/cmd/dotddev_assets/mutagen.yml
- cmd/ddev/cmd/global_dotddev_assets/.gitignore
- cmd/ddev/cmd/root.go
- docs/users/performance.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/mutagen_test.go
- pkg/globalconfig/global_config.go
- scripts/diagnose_mutagen.sh
- scripts/test_ddev.sh
As expected, there's some cleanup + new experiences to clean up with mutagen
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3125"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mutagen followup from v1.18.0-alpha1, fixes #3124

- pkg/dockerutil/dockerutils.go
In https://github.com/drud/ddev/pull/3110 I added checking for available docker (or other) disk space. 
I reversed the logic, so it showed the warning when you have LOTS of disk space.
This turns it back.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Reverse broken backwards minimum disk space warning

- cmd/ddev/cmd/exec.go
- cmd/ddev/cmd/exec_test.go
#3131 points out that there's a spare newline after `ddev exec <anything>`. 
Remove it. Improve test.
`ddev exec echo hi` and see if there's an extra newline.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3133"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix extraneous newline in ddev exec, fixes #3131

- cmd/ddev/cmd/describe.go
- docs/users/cli-usage.md
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/magento.go
- pkg/ddevapp/magento_assets/env.php
- pkg/ddevapp/magento_assets/local.xml
- pkg/ddevapp/shopware6.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
The hostname "db" is potentially ambiguous, see previous issues
TODO:
Everywhere that we used to use "db" for inside-docker hostname, use `ddev-<project>-db`, which is explicit.
`ddev start` on each project type and inspect the additional settings (like settings.ddev.php). You should see the explicit database hostname.
Regular TestDdevFullSiteSetup (on CircleCI) should check all this.
This should be added to the release notes, but as the old usage should work forever, it's not a big deal.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3111"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use explicit db hostname, fixes #3065

- containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof_prepend.php
- pkg/version/version.go
When enabling xhprof, the output in the UI does not contain information about memory consumption.
Enable profiling of memory consumption alongside CPU profiling by adding the XHPROF_FLAGS_MEMORY when xhprof_enable is called.
This can be tested using gitpod: https://gitpod.io/#https://github.com/drud/ddev/pull/3154
Enable xhprof (ddev xhprof on).
Visit at least one page on your site.
Visit /xhprof and view the profiling output, it should contain information on memory consumption.
Not sure if (or how) this can be included in automated testing. Happy to add testing to this PR if someones points me in the right direction.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Include memory consumption by default in xhprof output.

- pkg/ddevapp/ddevapp_test.go
Tests only: I don't know why, but TestNFSMount fails to create symlinks inside the container. But if you wait and do an ls, it works.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> TestNFSMount can fail on Windows because of NFS failure, make it more resilient

- pkg/ddevapp/ddevapp.go
We were checking for available docker space very early in `ddev start`, potentially before the images had been downloaded... and it uses the webimage. This could lead to a long silent pause depending on internet speed, and especially after an upgrade where we need a new image.
Check available space later.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Check available space AFTER we've already downloaded webimage

- cmd/ddev/cmd/root.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/globalconfig/values.go
`export DDEV_ALLOW_COMPOSE_V2=true`
in the environment will allow running with docker-compose v2. This is for testing.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow use with compose v2 when DDEV_ALLOW_COMPOSE_V2 is true

- docs/users/extend/custom-compose-files.md
- pkg/ddevapp/templates.go
- pkg/servicetest/testdata/TestServices/docker-compose.beanstalkd.yaml
- pkg/servicetest/testdata/TestServices/docker-compose.memcached.yaml
- pkg/servicetest/testdata/TestServices/docker-compose.solr.yaml
There were places in the docs where `ports` was used and it's not a very good habit, as things can collide. Encourage use of `expose` instead, which just works inside the docker network.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Encourage use of expose instead of ports in docker-compose.*.yaml

- containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/php-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- pkg/ddevapp/templates.go
- pkg/version/version.go
* For PhpStorm zero-configuration debugging to work, PHP_IDE_CONFIG must not exist (for php-fpm)
* For command-line debugging, PHP_IDE_CONFIG must be set
After discovering this problem, the attempt was to *add* PHP_IDE_CONFIG only for login sessions, but people didn't like that for a variety of reasons (doesn't work then for `ddev exec` or `ddev drush`)
Instead of trying to ADD PHP_IDE_CONFIG for the command-line, instead add it everywhere (via docker-compose.yaml) and *hide* it from php-fpm by unsetting it before php-fpm or even supervisord is started
Thanks to @cspitzlay for pushing me to try another time!
This testing is critical:
* `docker pull  drud/ddev-webserver:20210808_PHP_IDE_CONFIG` to make sure you have the latest
* Start a project with this ddev (you can use gitpod per the …
> Remove PHP_IDE_CONFIG in php-fpm instead of trying to add it elsewhere, replaces #3143, fixes #2998, fixes #3106

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- scripts/test_ddev.sh
* #3161 
1. Use container ID instead of name for the Beta in mutagen sync session
2. Unconditionally stop a mutagen session of the appropriate name even if mutagen is not currently enabled.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3162"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use container ID for beta in sync session, fixes #3161

- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
- pkg/util/utils.go
* Blackfire.io's Debian repositories are currently refusing `apt-get update`, see https://twitter.com/randyfay/status/1426535913094467584
* Image removal is not currently forced. I think it will do no harm to force removal
* Embargo the TestExtraPackages test until 20 AUG 21 10:00 MDT, meaning we won't test it until then, but tests will resume then.
* Change dockerutil.RemoveImage() to force removal. This fixes a random test failure that was identified at the same time as the Blackfire problem.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Blackfire packages are currently broken, embargo TestExtraPackages, force image removal

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
* #3158 
#3158 points out that we could more efficiently do working_dir with the docker-compose yaml instead of only passing it on the docker-compose command line. 
Put working_dir in the generated `.ddev/.ddev-docker-compose-*.yaml`
I'm hoping the existing tests are adequate.
The behavior shouldn't change.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3160"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use working_dir in generated compose instead of always overriding, fixes #3158

- cmd/ddev/cmd/mutagen-cmd_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/mutagen_test.go
A bug was described by a @TXChetG:
-  Project running nfs, never had mutagen before
-  Configure mutagen while running
- ddev start, downloads mutagen
- Long pause before download (because restarting daemon?)
- Then comes up and it's actually mutagen-syncing to nfs
On Start, make sure that the mutagen volume is mounted. If it is not, insist on a `ddev restart`
1. Start a project with NFS only
2. While project is running, `ddev config --mutagen-enabled`
3. `ddev start`
4. It should insist on a `ddev restart`
@TXChetG I'd love it if you could review this (especially manually testing)
This is an odd edge case; it might deserve a test. Not sure.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3167"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Force restart if mutagen volume did not get mounted

- pkg/ddevapp/config_test.go
In 65b8151aebadeea8c716aad2389b2ea644652570 I had to embargo TestExtraPackages because the Blackfire.io packages were broken. 
This reverts that, but keeps the helper utility.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove embargo on TestExtraPackages

- pkg/nodeps/utils.go
- pkg/testcommon/testcommon_test.go
TestGetLocalHTTPResponse is one of the (many) tests that fail perpetually on mac M1, only occasionally succeed. And this one prevents the next set of tests from running, and doesn't have anything special for M1.
Skip it. Let the later tests fail on M1. 
See https://github.com/docker/for-mac/issues/5407
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3177"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Skip TestGetLocalHTTPResponse on mac m1 - fails always

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
* #3128
Prerelease version of ddev v1.18.0 were using the Debian 11 Bullseye default nginx (1.18) because the official nginx debian packages were not available. Now Bullseye is officially released, and nginx has built official images, so we can go back to nginx 1.20.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3178"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Debian 11 Bullseye released, nginx packages available, go back to nginx 1.20, fixes #3128

- cmd/ddev/cmd/mutagen-reset.go
- docs/users/performance.md
- pkg/ddevapp/mutagen.go
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mutagen followup tweaks and docs

- pkg/ddevapp/config.go
When people do a `ddev config` on a project, it writes version-specific information into the config.yaml
They then check it in
When a new `ddev config` is done, it always causes a git difference which is not necessary.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't write version info into config.yaml

- cmd/ddev/cmd/logs_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router_test.go
Some odd problem with Docker Desktop on Mac M1 leads to lots of "connection reset by peer" errors. 
* https://github.com/docker/for-mac/issues/5407
Rather than investigating these all the time on M1, skip them. These tests get run on amd64 mac, windows, wsl2, linux. Enough places.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Mute some tests on mac M1 to avoid random EOF/connection reset by peer problems

- pkg/ddevapp/composer_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/dockerutil/dockerutils.go
* Minor test failure on mutagen on Windows. Spiff up TestDdevStartUnmanagedSettings as a result
* Fix SEGV bug if container not found in IsMutagenVolumeMounted
* Skip TestDddevStartMultipleHostnames on mac M1
* Skiip TestDdevStartUnmanagedSettings with mutagen
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Spiff up TestDdevStartUnmanagedSettings, etc, fix SEGV panic

- docs/users/step-debugging.md
Could be helpful to link to vscode launch help
Docs
Doc help
Read through and click link
n/a
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add vscode help link for launch.json

- cmd/ddev/cmd/xdebug_test.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/conf-available/php8.1-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/mods-available/php8.1.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/cli/php.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/php-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/php.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/pool.d/www.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/mods-available/assert.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/mods-available/blackfire.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/mods-available/xdebug.ini
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/mods-available/xhprof.ini
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/ddev-webserver/tests/ddev-webserver/test.sh
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen_test.go
- pkg/nodeps/php_values.go
- pkg/version/version.go
Time to refresh from upstream.
This adds php8.0-uploadprogress, shouldn't change much. Using Debian 11 bullseye.
We also have php8.1beta3
Just made this draft, as it needs to go in late in the release process. Also, deb.sury.org has started at least preliminary support for PHP8.1, which may make it into this PR or a later one. https://github.com/oerdnj/deb.sury.org/issues/1439#issuecomment-905581670
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3198"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump to latest upstream (ddev-images) php image. Adds PHP 8.1 and php8.0-uploadprogress

- cmd/ddev/cmd/logs.go
The logs command doesn't support `project-name` passed as an argument.
Tries to add support for `[project-name]` passed to the logs command.
https://github.com/drud/ddev/issues/3203
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add project-name arg to ddev logs, fixes #3203

- pkg/ddevapp/ddevapp_test.go
This was begun as an attempt to debug TestDdevXdebugEnable, but it turned out the test failures were a result of me changing the DNS settings in Docker Desktop to solve other problems. I had to go back and reset all the Docker Desktop settings and remove the DNS settings.
But since I was studying the test, finally figured out why it was so slow (curl timeout at 15s). So made it time out at 1s since we don't care about the result, we're just trying to trigger xdebug.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Test Improvements - TestDdevXdebugEnable

- .buildkite/test.sh
- pkg/ddevapp/composer_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/mutagen_test.go
- pkg/dockerutil/dockerutils_test.go
- pkg/version/version.go
There is a path where mutagen can hang forever... if you try to flush it and the container is already stopped or inaccessible (like after `ddev pause` or after docker restart.
* Check to see if mutagen session is connected before trying to flush it. If it's not connected, just terminate it.
* Prevent downloading mutagen multiple times in tests. This seems to have been an issue only on Windows?
* `composer install` in tests with `--no-progress`
* Don't show mutagen download progress bar in tests
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3220"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Terminate mutagen if container not running or sync not working

- pkg/ddevapp/mutagen.go
- pkg/nodeps/values.go
- pkg/version/version.go
Mutagen version v0.12.0-beta12 is out, with special accommodations for ddev (Not trying to sync if it's impossible)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3224"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump required mutagen version to v0.12.0-beta12 and move RequiredMutagenVersion to version.go

- cmd/ddev/cmd/commands.go
- pkg/ddevapp/ddevapp_test.go
* #3074
The error message is really misleading because it calls out project-level .ddev/.global-...
Improves the error message to say that project-level command is overriding the other one.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3227"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve the command-overriding-global-command warning, fixes #3074

- pkg/version/version.go
Mutagen v0.12.0-beta7 was released, which mostly affects performance on arm64.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3228"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump mutagen to 0.12.0-beta7

- docs/users/topics/cms_specific_help.md
- docs/users/topics/webserver.md
- mkdocs.yml
Some questions show up regulary so these should be covered by the docs.
This patch adds an example on how to add a Base Variant to TYPO3 for the local ldevelopment with DDEV which is often asked for.
Because of the proxy setup used with DDEV normal redirect examples from plain HTTP to TLS won't work so and extended example is provided.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3211"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Provide TYPO3 and Webserver specific help

- requirements.txt
Fixes #3232
Fixes breaking readthedocs builds due to removal of Python 2 support in setuptools 58.
PR: https://github.com/tikitu/jsmin/pull/34
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> pin jsmin to PR #34

- pkg/ddevapp/mutagen_config_assets/mutagen.yml
.DS_Store is a macOS-only side file that should never be synced into the container.
Exclude it in mutagen.yml.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3236"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Exclude .DS_Store from mutagen syncing

- pkg/util/utils.go
* #3233
It seems that the upstream coloring for Output.UserOut got lost, but it had been added back for util.Success. This adds it for util.Fail() and util.Error() and util.Warn
Not entirely sure why the upstream technique doesn't work any more. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Colors for warning and error and fail were lost, fixes #3233

- .circleci/config.yml
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example
- pkg/ddevapp/dotddev_assets/providers/localfile.yaml.example
- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
- pkg/ddevapp/dotddev_assets/providers/platform.yaml.example
- pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example
- pkg/ddevapp/provider.go
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/ddevapp/providerPlatform_test.go
* #3237
* Make sure mutagen gets synced after db is downloaded
* Make sure there's test coverage (CircleCI) for pull with mutagen
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3238"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix `ddev pull` with mutagen enabled, fixes #3237

- docs/index.md
Good news: Windows users can now simply run `wsl --install` to install WSL2. This removes 3 steps from the installation process in the docs 🎉 
Some notes:
- The `wsl --install` command was backported to Windows 2004 and higher. This drastically simplifies installation of WSL2. https://devblogs.microsoft.com/commandline/install-wsl-with-a-single-command-now-available-in-windows-10-version-2004-and-higher/
- Windows 10 1903 and 1909 are out of support at the moment of writing (https://docs.microsoft.com/en-us/windows/release-health/release-information), and also don't support the `wsl --install` command. Therefore we don't mention them anymore in the installation guide.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3246"><img …
> Simplify WSL2 installation steps

- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/monitoring.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/apache.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/conf.d/supervisor.conf
- containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/kill_supervisor.py
- containers/ddev-webserver/ddev-webserver-prod-files/etc/supervisor/apache.conf
- containers/ddev-webserver/ddev-webserver-prod-files/etc/supervisor/conf.d/supervisor.conf
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/ddev-webserver/tests/ddev-webserver/testdata/apache/auth.conf
- containers/ddev-webserver/tests/ddev-webserver/testdata/nginx/auth.conf
- containers/ddev-webserver/tests/ddev-webserver/testdata/nginx/junkpass
- pkg/version/version.go
With Nginx if basic authentication is enabled the monitoring endpoints are not longer accessible and this cannot be changed in a custom configuration because the locations are already defined.
For Apache this is not an issue because an alias is used for `/phpstatus`.
In addition, this need uncovered problems in how apache is run via supervisord, and those had to be fixed. This was originally https://github.com/drud/ddev/pull/3249 but for practicality had to be rolled in here. 
* To avoid this problem this patch sets `auth_basic` always to `off` for phpstatus
* Fix a bug from #3249 where `child_exit_monitor entered FATAL state, too many start retries too quickly` showed up in the logs at startup in v1.18 (using nonexistent python (python2) in /usr/local/bin/kill_supervisor.py)
* Fix a bug …
> Ensure monitoring is accessible also with basic authentication

- containers/ddev-dbserver/Makefile
- containers/ddev-dbserver/files/etc/my.cnf
- pkg/version/version.go
It's time to update images for upcoming release. This gets mysql 8.0.26 and latest of everything else
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update ddev-dbserver images for v1.18 release

- cmd/ddev/cmd/composer-create.go
- docs/users/developer-tools.md
- docs/users/extend/custom-commands.md
- pkg/ddevapp/composer.go
In #3226 the support for Windows symlink scanning and conversion was removed. This is currently unnecessary for current Docker Desktop running WSL2, but it may still be necessary for some Windows systems using the old Hyper-V Docker Desktop setting.
Roll back symlink setup and docs for this feature
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3255"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Restore windows symlink scanning and recreation, fixes #3254

- cmd/ddev/cmd/describe.go
- pkg/ddevapp/ddevapp.go
In testing for v1.18, it was discovered that neither docroot nor project type was reported in `ddev describe`
Add them in.
With a variety of projects, `ddev describe` and make sure project type and docroot are obvious.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3258"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add project type and docroot to describe

- docs/users/extend/additional-services.md
Different systems use Solr API v1 and others use v2.
Noted that the "Solr path" setting must be set to "/solr" when using Solr API v1 and just "/" when using Solr API v2.
https://drupal.slack.com/archives/C5TQRQZRR/p1632433128297900
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Clarify usage of the "solr path" setting in implementation details

- cmd/ddev/cmd/mutagen-monitor.go
- cmd/ddev/cmd/mutagen-reset.go
- cmd/ddev/cmd/mutagen-status.go
- cmd/ddev/cmd/mutagen-sync.go
- pkg/ddevapp/global_dotddev_assets/commands/host/yarn
There's no reason for an actual failure return on `ddev mutagen sync` and related commands if mutagen is not enabled.
* Return a warning and zero exit
* Make `ddev yarn` not show the output anyway.
No additions.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3260"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mutagen commands should not hard-fail when not enabled, fixes #3269

- pkg/ddevapp/providerAcquia_test.go
TestAcquiaPush seems to regularly destroy the test site. Turn it off for now. It seems to work fine when `ddev push acquia` is done.
What we really need is for TestAcquiaPush to push to a different environment so it can't break everything if something goes wrong.
Don't run TestAcquiaPush unless DDEV_ALLOW_ACQUIA_PUSH=="true". This allows turning it on with env var.
https://github.com/drud/ddev/issues/3263 has been created and scheduled for v1.19 to turn this back on and reimplement it so it's not so dangerous.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Stop TestAcquiaPush temporarily as it seems to fail and break upstream

- mkdocs.yml
- requirements.txt
Previously jsmin stopped working when python2 was removed. See https://github.com/drud/ddev/pull/3235 and https://github.com/drud/ddev/issues/3232
Thanks so much @mootari !
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3267"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> readthedocs: Go back to using published jsmin [skip ci]

- pkg/ddevapp/mutagen.go
A project name beginning with numeric chars can't work, even though it's a valid hostname. 
Related problems (dots) had already been dealt with in MutagenSyncName() but not this one. 
Try to create a mutagen-enabled project named 123project.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure mutagen sync name begins with letter, fixes #3265

- .spellcheckwordlist.txt
- containers/ddev-webserver/Dockerfile
- docs/users/xhprof-profiling.md
- pkg/version/version.go
v1.18.0 images are ready in preparation for v1.18.0 release. Also use latest upstream ddev-images
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3270"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images for v1.18.0

- containers/ddev-dbserver/Dockerfile
- pkg/version/version.go
This is about building the MariaDB 5.5 image only.
The upstream image (mariadb:5.5) is based on Ubuntu 14.04 Trusty, which seems not
to be allowed to connect to the Percona repos any more.
However, I did open https://jira.percona.com/browse/DISTMYSQL-125
about this issue, as we'd certainly rather use https.
http is only for mariadb 5.5 at this time.
Edit /etc/apt/sources.list.d/percona.list so it uses http instead of https when the upstream image is Ubuntu and older than 16.04
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3285"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use http for xtrabackup/percona for mariadb 5.5

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
LDAP+SSL aka `ldaps://` doesn't work without the OS CA cert being set. In version 1.17.0, libldap-common was a dependency of libldap-2.4-2, and in 1.18.0 it moved it to "recommends" and doesn't install it.
```
DDEV 1.17 
Package: libldap-2.4-2
Version: 2.4.47+dfsg-3+deb10u6
Depends: libc6 (>= 2.28), libgnutls30 (>= 3.6.6), libsasl2-2 (>= 2.1.27+dfsg), libldap-common
DDEV 1.18
Package: libldap-2.4-2
Version: 2.4.57+dfsg-3
Depends: libc6 (>= 2.28), libgnutls30 (>= 3.7.0), libsasl2-2 (>= 2.1.27+dfsg)
Recommends: libldap-common
```
The file needed is:
`/etc/ldap/ldap.conf` which has `TLS_CACERT /etc/ssl/certs/ca-certificates.crt` pointing to the OS CA's path which is needed for client SSL connections.
Explicitly adds the package back.
`apt install ldap-utils` and use ldapsearch with ldaps:// …
> LDAP missing TLS_CACERT path from libldap-common

- .ci-scripts/generate_artifacts.sh
Quicksprint needs to support mac M1, see https://github.com/drud/quicksprint/pull/203
* Separately package up amd64 and arm64 images
Note that using the script here I manually created the ddev_docker_images*.tar.xz that are needed and added them to the v1.18.0 release. That allows Quicksprint to move forward
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support both amd64 and  arm64 image tarballs for quicksprint usage

- docs/users/topics/phpstorm.md
Currently the Step debugging link on the PHPStorm integration docs page is not working (see https://ddev.readthedocs.io/en/stable/users/topics/phpstorm/)
Uses the correct markdown file name for the step debugging page (was: `step_debugging.md`, has to be: `step-debugging.md`)
Check that step debugging link works in changed PHPStorm integration docs page
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix step debugging link in PHPStorm integration docs

- docs/users/topics/phpstorm.md
If you have a `.` in your ddev project name, it can lead to problems when following the [PHPStorm integration guide](https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/) - Example:
* **ddev project name:** `my.project`
* **Does not work:** `COMPOSE_PROJECT_NAME=ddev-my.project`
* **Works:** `COMPOSE_PROJECT_NAME=ddev-myproject`  (while still using `my.project` as actual ddev project name)
I also posted my findings to these PHPStorm issues:
* https://youtrack.jetbrains.com/issue/WI-63293
* https://youtrack.jetbrains.com/issue/WI-62914
Adds some information about this issue to the PHPStorm integration documentation where `COMPOSE_PROJECT_NAME` is set (see Steps 3.7)
Create a ddev project with a dot in its name and try to follow the PHPStorm integration guide. Preserving the dot …
> Add notice about dots in project names for PHPStorm integration docs

- .gitpod.yml
- .gitpod/images/gitpod-setup-ddev.sh
- .gitpod/images/push.sh
- pkg/dockerutil/dockerutils.go
- pkg/nodeps/utils.go
* Our technique for determining host.docker.internal didn't work on Gitpod, and may have occasionally failed elsewhere
* There is a "correct" way to get it on linux (`docker network inspect bridge`), see https://docs.docker.com/engine/tutorials/networkingcontainers/
* We can use the docker api to get it as well, as done here.
* Thanks to @shaal for the inspiration for the better detection technique!
* This would have fixed #2904 - On docker 20.10+ we use host-gateway. But it doesn't work out, because we need host.docker.internal for NFS usage as well, and we don't get that then. So giving up on #2904
The existing xdebug tests should exercise this just fine.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3346"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use docker interface to determine host.docker.internal, fixes #2904

- docs/users/developer-tools.md
The documents [Email Capture and Review](https://ddev.readthedocs.io/en/stable/users/developer-tools/#email-capture-and-review) documents seem misleading for Laravel projects.
They state that mailhog "will not intercept emails if your application is configured to use SMTP ...", although later it talks about configuration.
This PR adds specific Laravel `.env` settings to configure Mailhog email interception.
- Create a Laravel project
- Config DDEV with default settings
- Update the `.env` file with the settings
- Attempt to send mail
A [demo project](https://github.com/tyler36/ddev-smpt-mailhog) was created for testing purposes.
- I debated about updating the quickstart guide or adding the config here. 
- I'm not sure if other frameworks have a similar "simple steps" that could help …
> add Mailhog note for Laravel users

- cmd/ddev/cmd/composer_test.go
- pkg/ddevapp/composer_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/templates.go
- pkg/nodeps/php_values.go
`composer_version` defaulted to "" during the transition from composer v1 to v2. But now people are on composer v2, and ddev has long since made `composer_version: ""` mean `composer_version: 2`. But there's a subtle difference - `composer_version: ""` does not update to latest composer during image build, and `composer_version: 2` does. 
This changes the default for `composer_version` to "2" so that people starting a new project get latest composer version
I think the existing tests will cover this.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3351"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make '2' the default composer_version so people get latest composer

- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
Adding debugging/verbose code that Randy walked me through when experiencing trying to do a ddev pull pantheon -y with a bad machine token. It wasn't clear that the token was bad, and it was returning a "Pull failed: exit status 1 " status that wasn't at all verbose/clear what was going on. The issue was a bad character in the machine token.
The PR displays the error message of where the pull is failing if it's caused by a bad machine token
Insert a bad machine token into the global_config.yaml file, and you'll see the error messages. (Although, it's not exiting the pull as Randy had expected)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3324"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix pantheon.yaml.example auth section so it checks for successful login

- containers/ddev-router/Dockerfile
- pkg/version/version.go
* the upstream source for arm64 forego builds went away
* nginx:stable moved to Debian bullseye, so the package name for certbot
had to change - instead, stay with previous nginx 1.20.1
See https://github.com/drud/ddev/issues/2980#issuecomment-972227437
* Use explicit upstream nginx image, 1.20.1, instead of "stable", which moved to 1.20.2
* Put the forego binaries (amd64 and arm64) in the drud/forego release instead of getting it from other places
* Go ahead and start using python3-certbot-nginx instead of python-certbot-nginx (python-certbot-nginx is no longer available in debian bullseye.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3378"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make ddev-router build despite upstream changes, for #2980

- pkg/ddevapp/config.go
* https://github.com/oerdnj/deb.sury.org/issues/1682
An update to the upstream deb.sury.org repositories doesn't work with ddev's Dockerfile generation because of a needed `apt-get dist-upgrade`. This adds it.
TestExtraPackages was breaking, and it would break lots of ddev installations already in the wild.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3385"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add apt-get dist-upgrade -y to webimage_extra_packages

- .github/workflows/container-tests.yml
- containers/ddev-dbserver/test/basic_database.bats
- containers/ddev-dbserver/test/custom_config.bats
- containers/ddev-dbserver/test/image_general.bats
- containers/ddev-router/test/containertest.sh
- containers/ddev-ssh-agent/test/image_general.bats
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/version/version.go
This is for 
* https://github.com/drud/ddev/issues/3369
It only affected use of mysql client directly in ddev-webserver.
During start.sh, update ~/.my.cnf to use explicit hostname `ddev-<project>-db`
No changes required
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3376"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use an explicit hostname `ddev-<project>-db` in ddev-webserver .my.cnf, for #3369

- .ci-scripts/bump_aur.sh
It works fine with 644, no executable permissions required.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3389"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set correct permission for bash completion in AUR

- .buildkite/testbot_maintenance.sh
Reverted deleted `fi` from this [commit](https://github.com/drud/ddev/commit/f478f52097f1c3182bc93ee4c2325d678f306b9d#diff-451042c4fa59c23de7087124c09570fdd5b4e97fefdea93266859950c56c03be).
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3390"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Buildkite script - added closure for if statement

- .ci-scripts/bump_aur.sh
I did not notice at first, but after reading the docs, I discovered that there are completions for all shells.
Tested in `zsh` and `fish`, everything works as expected.
It will be useful to have this functionality for all users of AUR out of the box.
Adds completions to standard `zsh` and `fish` folders.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3392"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> AUR: Add zsh and fish completions

- docs/users/providers/provider-introduction.md
- pkg/ddevapp/dotddev_assets/providers/git.yaml.example
- pkg/ddevapp/providerGit_test.go
A  (private) git repository is a perfectly fine place to store user-files and db dump for doing a pull, and most of us have access to great free storage on github/gitlab/etc.
Add git provider.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3372"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a git provider for ddev pull git

- docs/users/extend/additional-services.md
- pkg/servicetest/servicetest_test.go
- pkg/servicetest/testdata/TestServices/docker-compose.solr.yaml
https to access the solr UI has never worked right; somehow the solr interface always redirects to the wrong thing.
Stop using HTTPS_EXPOSE. `ddev describe` will then show the http URL.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3394"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove HTTPS_EXPOSE from solr recipe

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
* Upstream deb.sury.org/ddev-images has updated many things
* php8.1.0 is now there
Update to these.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump upstream web container to get php8.1.0

- cmd/ddev/cmd/export-db_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/utils.go
When using `ddev export-db` if the output file already exists and is larger than the new output file, the file will be the same size as before. This causes `ddev import-db` to fail again, `gunzip` to consider that the file has garbage at the end, etc.
Closes #3402
The file is truncated at opening.
Copy a very large file to db.sql.gz.
Run `ddev export-db -f db.sql.gz` on a site with a small database.
The file should be smaller than before, and `gunzip` should not complain about it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3407"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Truncate existing file when `ddev export-db --file=`, fixes #3402

- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
- docs/users/extend/in-container-configuration.md
- pkg/version/version.go
Allows users to easily add to the .bashrc by adding files (via homeadditions) to ~/.bashrc.d, and the files will then be executed on bash start. (This does not work with `ddev exec`.)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3397"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add .bashrc.d option when starting shell

- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
- pkg/version/version.go
In https://github.com/drud/ddev/pull/3397 I added the capability of adding files to homeadditions .bashrc.d - but there was a flaw in it that resulted in an error when `ddev ssh`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3420"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix error in home .bashrc.d in .profile 

- .gitpod.yml
- docs/users/docker_installation.md
- pkg/dockerutil/dockerutils.go
- pkg/nodeps/utils.go
`host.docker.internal` does not currently work on WSL2 with native docker install (as opposed to Docker Desktop).  This is because of name resolution changes for Gitpod, which should probably be reverted. These went into ddev v1.18.1 in https://github.com/drud/ddev/pull/3346
* https://github.com/gitpod-io/gitpod/issues/6446 claims that `experimentalNetwork: true` in .gipod.yml can make it behave as expected with regard to the bridge network.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix WSL2 docker-native host.docker.internal, use experimentalNetwork in .gitpod.yml

- pkg/ddevapp/config.go
This exact dist-upgrade is now breaking dbimage_extra_packages.
It's probably due to an error in mariadb packages,
but it seems that apt-get dist-upgrade is not a risk-free
action.
Also, this whole problem seems to have been solved upstream in
the deb.sury.org package.
See https://github.com/drud/ddev/pull/3385 and
https://github.com/oerdnj/deb.sury.org/issues/1682
This reverts commit d385ef98feb6ddb98013cd484c55ab49e9094b3f.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3425"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert "Add apt-get dist-upgrade -y to webimage_extra_packages (#3385)"

- pkg/util/utils.go
* #3421 
A username can't have parens in it.
Remove them.
* Created account "Some Body (SSG)"
* Started a project with that user
* `ddev ssh` and `id` showed the username as "somebodyssg"
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3423"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove parens from usernames, fixes #3421

- .gitpod.yml
- .gitpod/images/Dockerfile
- .gitpod/images/push.sh
- .vscode/launch.json
- cmd/ddev/cmd/auth-ssh.go
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/start.go
- docs/developers/building-contributing.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router.go
- pkg/nodeps/utils.go
* #3283
DDEV has long had easy gitpod.io integration to test DDEV, but now it will have a way to 
1. Launch a gitpod instance for any project (on github or gitlab) with a special URL
2. Add gitpod configuration to any project 
Allows starting any project in gitpod (without prior configuration) using a URL like https://gitpod.io/#DDEV_REPO=https%3A%2F%2Fgithub.com%2Fdrud%2Fd9simple,DDEV_BRANCH=main,DDEV_ARTIFACTS=https%3A%2F%2Fgithub.com%2Frfay%2Fjunk-demo-shaal-artifacts,/https://github.com/rfay/ddev/tree/20211101_gitpod_experiments
where
* DDEV_REPO: git Repository with the code
* DDEV_BRANCH: Branch of repository to check out
* DDEV_ARTIFACTS: git repository with `db.sql.gz` and `files.tgz` available when you check it out on default branch
Both DDEV_REPO and DDEV_ARTIFACTS should be …
> Gitpod integration for website projects, for #3283

- docs/users/extending-commands.md
It's easy to miss the target file to update on a quick scan of the docs. 
This update make it "pop" a bit more.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3437"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> highlight the target file

- docs/developers/release-checklist.md
- docs/users/step-debugging.md
- pkg/dockerutil/dockerutils.go
- pkg/nodeps/utils.go
In the v1.18.2 release, to make xdebug work for both docker-installed-in-wsl2 and docker-desktop-wsl2 environments, a technique for detecting Docker Desktop was introduced. It looked for the docker client symlink. But that was fragile, because
* People might have docker-ce installed but not be using it
* The /usr/bin/docker symlink might not be exactly the one we were looking for (if people have manipulated wsl.conf, etc)
Use the api equivalent of `docker info` to detect "Docker Desktop" as the "Operating System"
Try xdebug on:
* There are no tests for the (so far unsupported) docker-install-inside-wsl2
* Other than that hopefully most things can catch this.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3443"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use more robust technique to detect Docker Desktop (WSL2), fixes #3441

- .github/workflows/linux-setup.sh
Fix apt install of mysql-client so github actions ubuntu can work.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3446"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove apt install of mysql-client as it seems to break Ubuntu test runner in Github Actions

- cmd/ddev/cmd/commands_test.go
- pkg/ddevapp/assets.go
* #3449 
It turns out .gitattributes (that helps Windows people not to check out files with CRLF in them) got lost in embedding when embed changed.
Bring the file back.
* TestCustomCommands got coverage added for this.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3450"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure .gitattributes gets into commands directory, fixes #3449

- docs/users/developer-tools.md
sequelpro.com is no longer functioning, and the project is abandoned anyway.
Remove the link. Update other random out-of-date things in that section.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3455"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove sequelpro URL and update database management stuff [skip ci]

- pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
Additional WebP support and the minimal CSP headers for fileadmin are
added with this patch.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3453"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Optimize Nginx configuration for TYPO3

- .buildkite/macos-m1.yml
- .buildkite/macosdockerformac.yml
- .buildkite/wsl2.yml
- cmd/ddev/cmd/share_test.go
Avoid the complaint
Your account is limited to 1 simultaneous ngrok client session.\nActive ngrok client sessions in region 'us'
Cut down on how many test runners can use it. Now just macOS (both kinds) and WSL2
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3457"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Tests only] Limit how many places TestShareCmd can run

- Makefile
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/version/version.go
The nice new way to specify a docker endpoint instead of complicated `$DOCKER_HOST` is `docker context`.
Unfortunately neither the fsouza/go-dockerclient (that we currently use) nor the docker https://github.com/moby/moby has direct support for this, it's all written into the docker cli AFAICT.
Use `docker context inspect` to find out the current context's endpoint, then use that for DOCKER_HOST (if DOCKER_HOST is not set).
Try it out with colima or another remote context
This changes the docker constraint to 19.03.9 (oldest version I could find that supported contexts).
As a result, it needs to wait for ddev v1.19.0
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3452"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add support for docker context, changes required docker constraint

- cmd/ddev/cmd/config_test.go
TestConfigMariaDBVersion and TestConfigMySQLVersion don't do a lot and they take forever.
Make them test less versions.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3462"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Simplify TestConfigMariaDBVersion and TestConfigMySQLVersion

- .github/workflows/linux-setup.sh
- Makefile
Back in the day, go builds were heavily dependent on the existing environment.
But modules came along, and things are better, with no known problems.
Although I sure spent a lot of time maintaining the golang-build-container and the full platform-independent build process all this time, it's time to let it go.
This build just using go itself.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Build using golang itself instead of using docker image

- .buildkite/test.sh
- .buildkite/testbot_maintenance.sh
- cmd/ddev/cmd/commands_test.go
- pkg/ddevapp/mutagen_test.go
- pkg/ddevapp/providerGit_test.go
* #2619
There are flaws in a number of tests and test setup where storage on the buildkite runners builds up over time.
* Fix a couple of tests
* `rm -r ~/tmp/ddevtest` at beginning of test
Details on usage and where it comes from are at https://gist.github.com/rfay/baa24ff932d6f9ae6d4b59b2b4ac0731
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3474"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Clean up several test directories that grow over time, for #2619

- .github/workflows/colima-tests.yml
- .github/workflows/macos-colima-setup.sh
- .github/workflows/tests.yml
- .vscode/launch.json
- Makefile
- cmd/ddev/cmd/a.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/composer_test.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/debug-nfsmount_test.go
- cmd/ddev/cmd/describe.go
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router_test.go
- pkg/ddevapp/utils.go
- pkg/dockerutil/dockerutils.go
- pkg/globalconfig/global_config.go
- pkg/servicetest/servicetest_test.go
- pkg/testcommon/testcommon_test.go
* #3208 
* #3444 
* Full support for Colima
* Fix 60-second blocking in TestDdevXdebugEnabled, for https://github.com/drud/ddev/issues/2619
To test this PR, go to [checks](https://github.com/drud/ddev/pull/3470/checks) and choose "PR Build" and all the downloads will be there.  You can also test general functionality on [gitpod](https://gitpod.io/#https://github.com/drud/ddev/pull/3470)
Install colima and work with ddev.
`brew install colima --HEAD` and `colima start`
Consider `colima start --cpu 4 --memory 4`
* Full macOS tests run with colima on Github Actions
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3470"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support and test Colima as docker environment for ddev, fixes #3208

- .ci-scripts/bump_homebrew.sh
It's always been complicated for people to get the latest version of ddev for testing, but with this, `head` is added to the homebrew formula, so `brew unlink ddev && brew install --head ddev` will do the job.
It's already live, this PR makes it so it will be in future updates.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3476"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add brew install --head capability to homebrew on release

- Makefile
- pkg/ddevapp/assets.go
- pkg/ddevapp/wordpress.go
- pkg/ddevapp/wordpress/.editorconfig
- pkg/ddevapp/wordpress/phpcs.xml.dist
- pkg/ddevapp/wordpress/wp-config-ddev.php
- pkg/ddevapp/wordpress/wp-config.php
Currently, the generated `wp-config-ddev.php` defines the following WordPress configuration constants without checking if they are already defined:
* `DB_NAME`
* `DB_USER`
* `DB_PASSWORD`
* `DB_HOST`
* `WP_HOME`
* `WP_SITEURL`
* `WP_DEBUG`
Additionally, the `$table_prefix` global variable is set such that it will override any changes if the DDev configuration is included first which can prevent operability with configurations that have intentionally changed the WordPress table prefix. This setup become problematic with heavily customized WordPress setups and those that use, for example, the dotenv package to manage the WordPress configuration depending on the running environment.
* Changes `wp-config-ddev.php` output to allow overriding when included in an existing WordPress project …
> Fixes DDev WordPress Config Files for Override & Coding Standards, fixes #2795

- pkg/ddevapp/network_test.go
- pkg/ddevapp/testdata/TestNetworkAmbiguity/docker-compose.test.yaml
* #3403
#3403 will fix our network ambiguity problem, but we have to have a baseline to measure it against.
This test will work with current HEAD, but then will fail when #3403 goes in, because network ambiguity problem will be solved. It will be adapted to the new setup.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3479"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add TestNetworkAmbiguity in preparation for #3403

- containers/ddev-dbserver/Makefile
* #3482
#3482 pointed out that mariadb 10.1 was not working on mac M1 (arm64). 
There was an error in the build list and mariadb 10.1 was only being pushed for arm64, even though the upstream mariadb 10.1 image is pushed for arm64 as well.
Start a project with `mariadb_version: 10.1`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Push mariadb-10.1 to arm64 and amd64

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
blackfire extension is enabled by default on Casual Webhosting setup, and it shouldn't be
`docker run --rm --name=blackfire drud/ddev-webserver-prod:20211230_blackfire_on_prod`
`ddev exec -it blackfire php --version` should not show blackfire
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3486"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix blackfire-php being enabled by default on hardened/prod ddev-webserver

- .circleci/config.yml
- .github/workflows/container-tests.yml
- .github/workflows/tests.yml
Moving nightly builds to github (free) instead of circleci.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3490"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Do nightly build on github instead of circleci, fixes #3013

- .circleci/config.yml
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/ddevapp_test.go
Testing was using an ancient version of WordPress
Use a current version.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3488"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Tests should use updated wordpress 5.6 code

- pkg/ddevapp/ddevapp_test.go
The ongoing battle with TestDdevXdebugEnabled timing out and such.
* Use an even simpler project
* Use app.Restart() instead of app.Start()
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Tests only] Simplify TestDdevXdebugEnabled and TestDdevXhprofEnabled with simpler project

- docs/users/extend/customizing-images.md
Docs say "Debian 10 Buster" and should say "Debian 11 Bullseye".
String updated from "Debian 10 Buster" to "Debian 11 Bullseye".
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3497"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update Debian verbiage in Docs, omit mentioning specific version

- docs/users/docker_installation.md
There appears to be a missing `sudo` in the install commands for docker in WSL2 — I got "Could not open lock file /var/lib/dpkg/lock-frontend" before adding the `sudo` shown here.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Added missing sudo to wsl2 docker install instructions

- cmd/ddev/cmd/debug-download-images.go
- pkg/ddevapp/ddevapp.go
docker-compose and mutagen are images that are currently loaded upon request.
Updating `ddev debug download-images` command, to include the missing images.
1. Run `ddev debug download-images` and confirm it includes `mutagen` and `docker-compose`.
1. Run `ddev start`, and confirm that no extra images are downloaded.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3472"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Debug download images with mutagen and docker compose

- pkg/ddevapp/config.go
In certain network situations, including when no internet is available, the `composer self-update` in generated .ddev/.web-image-build/Dockerfile can fail.
Try twice, but allow failure.
Try starting a fresh project with no internet. (All images need to have been previously downloaded of course)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3508"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't fail if composer self-update fails in web image build (like with no internet)

- .spellcheckwordlist.txt
- docs/users/performance.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/mutagen_config_assets/mutagen.yml
* #3505
* #3400 
* #3384 
* #3357 
* When mutagen is enabled (and --no-bind-mounts=false so bind-mounts are possible) then mount .git and upload_dir into the container via traditional bind-mount and exclude them from mutagen. That way they're available inside the container, but have no mutagen-setup time.
* Rework the docs a bit
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3507"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mount .git and upload_dir with bind-mount when using mutagen, fixes #3505, fixes #3400, fixes #3384, fixes #3357

- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerPantheon_test.go
The pantheon and acquia push tests were failing, apparently due to drush 11 coming out and causing extra composer hell. 
Use `composer require drush/drush:*` instead of just `composer require drush/drush`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3512"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] composer drush is failing, fix up

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/mutagen.go
On mutagen, since 
* #3507 
the /var/www directory can be a mix of native filesystem and bind-mounted stuff. So the .git directory and upload_dir are typically bind-mounted. But then the chown of /var/www takes forever. Very painful.
This mounts the project_mutagen volume a separate place (/tmp/project_mutagen) so it can be chowned there and the chown command will only find native-filesystem files.
`export DDEV_DEBUG=true` and `ddev start` and see the difference. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make more efficient chown of mutagen volume, speed up start

- .github/workflows/pr-build.yml
- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/poweroff.go
- docs/users/extend/additional-services.md
- docs/users/extend/custom-compose-files.md
- docs/users/faq.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router_compose_template.yaml
- pkg/ddevapp/ssh_auth_compose_template.yaml
- pkg/ddevapp/testdata/TestDdevExec/docker-compose.busybox.yaml
- pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.z2.yaml
- pkg/ddevapp/testdata/TestNetworkAmbiguity/docker-compose.test.yaml
- pkg/ddevapp/testdata/TestSSHAuth/.ddev/docker-compose.sshserver.yaml
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/testdata/TestComposeWithStreams/test-compose-with-streams.yaml
- pkg/servicetest/servicetest_test.go
- pkg/servicetest/testdata/TestServices/docker-compose.beanstalkd.yaml
- pkg/servicetest/testdata/TestServices/docker-compose.memcached.yaml
- pkg/servicetest/testdata/TestServices/docker-compose.solr.yaml
* People on versions below v1.19 are referred to the HEAD version of docker-compose.solr.yaml, which does not work until v1.19.x
* People upgrading to v1.19 with solr and other 3rd party services have to *add* the `networks:` line to make their project work.
* The failure mode if people are missing the networks line is awful - ddev-router has a fatal that's hard to understand and says nothing about solr.
* Nothing added at this point. It's possible we should add a test for the network-checking behavior
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> v1.19.x vs v1.18.x compatibility with 3rd party services, especially solr

- .github/workflows/colima-tests.yml
- .github/workflows/container-tests.yml
- .github/workflows/docscheck.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/macos-colima-setup.sh
- .github/workflows/pr-build.yml
- .github/workflows/tests.yml
- .spellcheckwordlist.txt
- cmd/ddev/cmd/composer-create.go
- docs/users/docker_installation.md
Previously colima installation with `--HEAD` was required, but the needed things have made it into regular release.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3519"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use regular colima release instead of HEAD, change composer create-project approach

- .github/workflows/docscheck.yml
- markdown-link-check.json
A couple of sites are now blocked by captchas that curl can't deal with.
And `nssm.cc` regularly fails. Ignore them
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3525"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Ignore a couple of misbehaving spellcheck items

- .github/workflows/pr-artifacts-comment.yml
It's hard to get build artifacts from github.
Use nightly.link to get them.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3529"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add build artifacts to PRs with nightly.link [skip ci]

- pkg/ddevapp/ddevapp.go
It's possible to have a race condition between mutagen doing things and the chown of the mutagen volume, see https://github.com/drud/ddev/runs/4843625816?check_suite_focus=true
Terminate an existing mutagen session before chowning the volume; it then gets created right away.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Terminate mutagen before chowning volume to avoid conflicts

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- pkg/version/version.go
An obscure bug was discovered in https://github.com/docker/compose/pull/9033 - 
* If ddev-global-cache volume does not exist
* And if mkcert does not exist
Then ddev-webserver crashes on startup, and `ddev logs` shows a permission error accessing /mnt/ddev-global-cache/mkcert/rootCA-key.pem:
```
Failed to start d9: container failed to become healthy: err=container 'web' exited, please use 'ddev logs -s web' to find out why it failed 
```
`ddev logs` shows:
```
+ mkcert -install
ERROR: failed to save CA key: open /mnt/ddev-global-cache/mkcert/rootCA-key.pem: permission denied
```
Make sure the ddev-global-cache/mkcert directory is readable/writeable by current user even if it just got created. 
```
mkcert -uninstall
rm -rf "$(mkcert -CAROOT)"
brew unlink mkcert
ddev poweroff
docker volume …
```
> Make sure that rootca is writeable in ddev-global-cache

- pkg/ddevapp/global_dotddev_assets/commands/web/artisan
People sometimes have artisan checked out without it being executable,  so they get this when they run `ddev artisan`:
```
/mnt/ddev_config/.global_commands/web/artisan: line 9: ./artisan: Permission denied
Failed to run artisan : exit status 126
```
Use `php` to run the artisan command.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Artisan command sometimes isn't executable. Use php to run it.

- cmd/ddev/cmd/share_test.go
Regular test failures on TestShareCmd. Apparently ngrok stays alive somewhere and prevents other connections.
Try a killall during cleanup.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Try again to make sure ngrok dies

- pkg/ddevapp/drupal.go
* #3522 
Use mysqli on drupal6
Start project with drupal6 and look at settings.ddev.php, should have `mysql` for driver
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3542"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Drupal6 should use mysqli for driver, fixes #3522

- docs/users/extend/custom-compose-files.md
- pkg/ddevapp/ddevapp.go
* #3537
The method for deleting docker volumes owned by 3rd party services on `ddev delete` was pretty rigid and just name-based. As a result, it was hard to have multiple volumes, and a mistake in naming could have consequences.
Look up what we actually have for volumes and use that information to delete.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3543"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Introspect to determine service volumes to delete, fixes #3537

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/magento.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/php.go
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerGit_test.go
- pkg/ddevapp/providerLocalfile_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/ddevapp/providerPlatform_test.go
- pkg/ddevapp/shopware6.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/wordpress.go
I stumbled on a bug where app.GetUploadDir() was returning the docroot when the UploadDir was "". 
This happened always with php projects that didn't have an UploadDir. 
The way I hit it was I had mutagen enabled globally and started a php project and found that the docroot wasn't mounted!
Use a new function to return the full upload dir instead of repeating it everywhere.
Start a mutagen-enabled PHP project that has a docroot and no upload_dir.
`ddev ssh` and make sure the docroot exists!
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix bug where upload_dir is docroot if no upload_dir

- cmd/ddev/cmd/service-enable.go
- cmd/ddev/cmd/testdata/TestCmdGet/example-repo/README.md
- cmd/ddev/cmd/testdata/TestCmdGet/example-repo/tests/test.bats
- docs/users/extend/additional-services.md
* #3545
Some instances of `ddev service get` appeared in docs etc after it was changed to `ddev get`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3546"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove incorrect usages of `ddev service get`, fixes #3545

- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/root.go
- pkg/ddevapp/instrumentation.go
- pkg/version/version.go
- pkg/version/version_test.go
* #3520
Some changes for gitpod broke the regular describe for normal users
Go back to looking up port for each service
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3544"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change renderAppDescribe to use different URLs for each service, fixes #3520

- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
#3549
Check if `$settings['config_sync_directory']` is empty before setting it.
1. Have a Drupal 9 project. Define a config sync directory in the default `settings.php` file, e.g. `$settings['config_sync_directory'] = $app_root . '/../config/sync';`.
2. Export config.
3. Config should be exported to `config/sync` directory outside the webroot instead of `sites/default/files/sync`.
Fixes #3549 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Prevent unconditional overriding config sync directory

- Makefile
- docs/developers/testing-docs.md
@tyler36 pioneered all of this while trying to test docs as they would really look in https://github.com/drud/ddev/pull/3495 - so this is all credited to him. 
`make mkdocs-serve` will run either local mkdocs or run a docker command to serve it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3541"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add make mkdocs-serve

- pkg/ddevapp/ddevapp.go
The `.ddev/.gitingore` is created very late in the start process and until the creation git status shows many untracked files.
The `.ddev` folder preparation and `.ddev/.gitingore` creation is now done before any other files are created.
#3239
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3551"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Prepare ddev directory earlier, fixes #3239

- cmd/ddev/cmd/root.go
The warning about the missing SegmentKey generates a second obejct on output which causes it to be invalid for parsers.
In json output mode the warning is no longer triggert.
Execute ddev describe -j on a self build ddev binary. The following warning must not appear:
```json
{
"level": "warning",
"msg": "Instrumentation is opted in, but SegmentKey is not available.",
"time": "2022-02-05T16:52:26+01:00"
}
```
N/A
N/A
N/A
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3574"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove warning about missing SegmentKey in json mode

- docs/users/snippets/launch.json
VS Code has deprecated the workspace variable `${workspaceRoot}` in favor of `${workspaceFolder}`.
[Source](https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3580"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] update vscode docs to use ${workspaceFolder} instead of ${workspaceRoot}

- docs/users/docker_installation.md
According to [official Docker CLI documentation](https://docs.docker.com/engine/reference/commandline/context/), `docker context show` command does not exist. 
Replacing it with `docker context ls`.
To replicate run `docker context show` on latest docker CLI. 
Note: apparently the command works on "some" docker CLI installation. Still the command is not documented in the official docs.
This doesn't affect anything. It's just a documentation update, and not related to any setting changes but just how to check the docker active context.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3589"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Command `docker context show` not available on all docker client versions

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- pkg/version/version.go
Problems cleaning up php gc() were reported in https://gitter.im/drud/ddev?at=619b5d2fcd3f06175dcbff24
`Uncaught PHP Exception ErrorException: "Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13)` when PHP tries to clear / delete old sessions
Make sure that /var/lib/php is owned by the php-fpm user.
Not sure how to recreate this.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3391"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set writable perms on /var/lib/php in ddev-webserver start.sh

- .vscode/launch.json
- pkg/dockerutil/dockerutils.go
Xdebug wasn't working any more on gitpod because they changed the networking situation. Now the networking is normal Linux, so we don't need the previous technique (which now doesn't work).
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3597"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove special handling for gitpod getting host.docker.internal

- pkg/dockerutil/dockerutils.go
* #3548 
This has only been seen on WSL2 when the docker client disappears, due to Docker Desktop problems with integrating with WSL2 distro.
If we can't use `docker context inspect` for whatever reason, just bail.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3605"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't let ddev continue processing if docker context inspect doesn't work, fixes #3548

- docs/users/docker_installation.md
* #3560 
Docs: It turns out you can just launch colima with `colima start --port-interface 127.0.0.1` to work around this problem.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3608"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Use --port-interface when starting colima, fixes #3560

- docs/index.md
Proposed changes to simplify the install instructions.  Motivation: The current instructions are confusing for Linux and WSL2 users.  Removed all Linuxbrew references.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3579"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve installation instructions, especially for WSL2/Linux

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/list_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/settings_test.go
* #3582 
TestDdevAllDatabases has been hanging on all Windows platforms
Skip the part on TestDdevAllDatabases that tries to capture stdout.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3616"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix TestDdevAllDatabases on Windows, fixes #3582

- containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/healthcheck.sh
- pkg/version/version.go
I noticed in a support issue that there were some things in the
healthcheck.sh that I don't know how they could work.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve web container healthcheck script

- cmd/ddev/cmd/debug-download-images.go
- cmd/ddev/cmd/debug-download-images_test.go
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
* #3556 
ddev (really docker-compose) makes way too much noise when downloading images. 
Limit what it says. 
Now pulling solr, for example, it says
```
rfay@rfay-tag1-m1:~/workspace/d9$ ddev start
Starting d9...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
solr Pulling
solr Pulled
Network ddev-d9_default  Created
```
`ddev get drud/ddev-drupal9-solr && ddev start`
No tests added.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3614"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev shouldn't output so much stuff when pulling 3rd party images, fixes #3556

- cmd/ddev/cmd/testdata/TestCmdGet/example-repo/docker-compose.example.yaml
- docs/users/extend/custom-compose-files.md
- docs/users/faq.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/compose_yaml.go
- pkg/ddevapp/config.go
- pkg/ddevapp/testdata/TestDdevExec/docker-compose.busybox.yaml
- pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.z2.yaml
- pkg/ddevapp/testdata/TestNetworkAmbiguity/docker-compose.test.yaml
- pkg/ddevapp/testdata/TestSSHAuth/.ddev/docker-compose.sshserver.yaml
- pkg/dockerutil/testdata/TestComposeWithStreams/test-compose-with-streams.yaml
- pkg/dockerutil/testdata/docker-compose.yml
* #3587
Because the requirement of the `networks` stanza in ddev v1.19 is pretty intrusive, requiring existing `docker-compose.*.yaml` all to be edited, this PR unmarshalls in the fully normalized yaml text into a golang map, replaces the `networks` array, and then marshalls the yaml back out to .ddev/.ddev-docker-compose-full.yaml.
I'm just hoping that all existing pass. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change docker-compose yaml to insert networks stanza, fixes #3587

- pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
The classic database browsers like sequelace don't work with postgres, but tableplus does. make the `ddev tableplus` command support postgres.
Use a postgres dburl when using postgres. 
Install Tableplus and
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3623"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support tableplus for postgres projects

- pkg/ddevapp/ddevapp.go
* #3621 
In projects with a hyphen in the project name, ddev didn't find the images to pull correctly, using a naive approach.
This PR uses a smarter approach to finding out the image to pull based on the full -built image name. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3622"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix findAllImages() where project name has hyphen, fixes #3621

- containers/ddev-dbserver/files/home/.my.cnf
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/assets.go
- pkg/ddevapp/config.go
- pkg/ddevapp/healthcheck/postgres_healthcheck.sh
- pkg/fileutil/files.go
- pkg/version/version.go
* #3617 
* Add healthcheck with backoff to postgres container
* Improve maria/mysql healthcheck so it doesn't show irrelevant output
* Improve PrepDdevDirectory() so it lists named files that can be grepped for #ddev-generated properly
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve healthcheck for db container including postgres, fixes #3617

- cmd/ddev/cmd/delete-images.go
This adds a flag --all to delete all ddev Docker images.
More work will be needed for database images (postgres etc).
I also wrapped the remove image code into a function because it
was repeated many times.
* #2968 
The existing delete images command leaves the default ddev images and people want to be able to delete *all* ddev-pulled images when cleaning up.
This additional flag will allow the delete images command to delete all ddev images.
Start a ddev project and then run this command
`ddev delete images --all`
Verify all your project images and the default ddev images are removed.
There is no test file for the delete command.
#2968 
None
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Adds delete all images command flag, fixes #2968

- cmd/ddev/cmd/snapshot.go
- cmd/ddev/cmd/snapshot_restore.go
Snapshots don't work with postgres:9. Nobody has really stepped up to study it, and postgres:9 is probably a very limited case anyway, so just don't let people use snapshots there.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3630"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't allow snapshots for postgres:9, fixes #3583

- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/drupal.go
It was announced that Drupal 10 will require php8.1, so we'll use it by default
Create a drupal10 project. It should automatically have php8.1 as the PHP version.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3633"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Drupal 10 will require php8.1, use it by default

- cmd/ddev/cmd/xdebug_test.go
- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
GraphicsMagick is often used with TYPO3 instead of ImageMagick.
This patch adds the graphicsmagick package to the ddev-php-base image.
Resolves #3569
This change has no impact or side effects.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3629"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Install GraphicsMagick by default, fixes #3569

- containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
- docs/users/extend/customization-extendibility.md
- pkg/version/version.go
People sometimes want to change the in-container PATH for various reasons, and it hasn't been that easy.
* #3022 
Allow both `ddev ssh` and `ddev exec` to pick up files from ~/.bashrc.d (from homeadditions). This allows just overriding/adding to the PATH there.
I didn't add test, which may be questionable.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3634"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use .bashrc.d to add to $PATH, fixes #3022

- pkg/ddevapp/provider.go
I noted looking through CirclCI logs that a failed TestPantheonPush actually exited the whole test. It's not supposed to do that. 
Don't use util.Failed() (which immediately exits) in api methods.
Make sure `ddev push` works fine in example.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3635"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> We shouldn't use util.Failed in api method, it exits everything

- .github/workflows/golangci-lint.yml
A dependabot auto-PR tried to do this in https://github.com/drud/ddev/pull/3638 but it completely failed
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3640"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix up golangci-lint for v3 after update

- docs/users/topics/phpstorm.md
The documentation currently contains information about a bug in PHPStorm that does not allow the use of Docker Compose V2 and provides a workaround by downgrading DDEV to use V1. This is no longer necessary as PHPStorm can use Compose V2 if it is available on the system, alternatively the bundled Docker Compose binary can be used.
The documentation section has been updated to recommend using your system's Docker Compose binary in V2 mode or using the bundled binary.
None
None
https://youtrack.jetbrains.com/issue/WI-61205
None
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3631"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update the docs on the use of DDEV with Compose V2 support in PHPStorm

- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/get_test.go
- docs/users/extend/additional-services.md
- pkg/ddevapp/provider.go
- pkg/globalconfig/values.go
* #3552
* #3553
`ddev get` is great, but it doesn't help people discover the add-ons that may be available.
With this PR you can `ddev get --list` or `ddev get --list --all` (--all picks up unofficial add-ons)
* Added just a bit to TestCmdGet
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3641"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add ddev get --list so people can discover add-ons, fixes #3552, fixes #3553

- pkg/version/version.go
Bump image versions for v1.19.0-rc1
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3642"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump image versions for v1.19.0-rc1

- pkg/dockerutil/dockerutils.go
- pkg/nodeps/values.go
I noticed in a casual test on Colima that the value provided for absolute disk space was calculated wrong.
Try to get it right
Try testing with various values and make sure it works
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3646"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> The absolute available space value was wrong for checking docker disk space

- pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
- pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
- pkg/ddevapp/global_dotddev_assets/commands/web/drush
I noted in testing v1.19.0-rc3 that `ddev drush` didn't work on drush10. It should.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3655"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev drush should be available for drupal10

- .vscode/launch.json
- cmd/ddev/cmd/delete-images.go
- cmd/ddev/cmd/poweroff.go
- cmd/ddev/cmd/root.go
- pkg/ddevapp/compose_test.go
- pkg/ddevapp/compose_yaml.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/poweroff.go
* #3649 
* The new ddev v1.19 was using `docker-compose convert`, which was listed as an *alias* of `docker-compose config`, but in reality, `docker-compose convert` is not valid in docker-compose v1.
* I also noted that docker-compose v1 doesn't create a "name" for a volume, so volumes wouldn't be deleted if they don't have an explicit name. Rather than trying to work around that I just added a name in ddev-drupal9-solr, https://github.com/drud/ddev-drupal9-solr/commit/d00c4acaeea187238e6e9ec3871f6e954d093be6
* Start a project with docker-compose v1 enabled globally
Added TestComposeV1
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Compatibility with docker-compose v1, fixes #3649

- pkg/ddevapp/providerAcquia_test.go
Now that we have an acquia account to test against, we can turn on Acquia again.
* #3656 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3662"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make Acquia work again, fixes #3656

- .gitpod/images/Dockerfile
Current gitpod doesn't work quite right with older ddev, so this puts ddev v1.19.0-rc1 inside the ddev-gitpod-base image
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3661"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use recent ddev version for gitpod [skip ci]

- containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
- containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- pkg/version/version.go
* nvm-selected default node version wasn't shown in `ddev exec node --version`
* Startup with no internet caused failure
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3664"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve `ddev nvm` persistence and availability, starting with no internet

- .github/workflows/colima-tests.yml
- .github/workflows/pr-artifacts-comment.yml
- .github/workflows/pr-build.yml
- .github/workflows/tests.yml
Access to secrets is denied by default for PRs from foreign repositories and all tests using these will fail therefor.
The solution is to use the `pull_request_target` event instead of the simple `pull_request` event. This changes the behavior of the workflows for security reasons, the workflow is not loaded from the PR but always the base of it. This makes sure nobody can get access to the token and abuse it.
Merge this PR and create a new PR from a foreign repository to verifiy if the tests are working as expected now.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3671"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make tests working from foreign repositories

- pkg/ddevapp/ddevapp_test.go
Some tests (TestDdevStartMultipleHostnames and TestInternalAndExternalAccessToURL) just don't run predictably on M1 or Colima. Just exclude them, as they get covered elsewhere.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3674"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Exclude a couple of commonly failing tests (TestDdevStartMultipleHostnames and TestInternalAndExternalAccessToURL) [skip ci]

- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
Time for official ddev-webserver:v1.19.0
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3672"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump webserver to v1.19.0

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/poweroff.go
In the case of changing additional services, etc, ddev could pull the wrong set of images. It needs to wait until after the .ddev-docker-compose-full.yaml is written to find out what images it's looking for.
* Move the pull until after the creation of yaml
* Also uses busybox for ddev poweroff instead of surprising people with a pull there. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3668"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Must pull image after calculating them, fixes #3648

- pkg/ddevapp/ddevapp.go
- pkg/output/output_setup.go
Hooks output is too chatty, low signal-to-noise ratio
Only output extra hook output if DDEV_DEBUG=true
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3667"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Quiet down hook output

- cmd/ddev/cmd/describe.go
- pkg/ddevapp/list.go
See 
* https://github.com/jedib0t/go-pretty/issues/191
`ddev list` and `ddev describe` sometimes inappropriately wrap URLs
Remove the max width for those URL columns.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update ddev list and ddev describe to try to not break URLs

- .gitpod/images/Dockerfile
- docs/users/docker_installation.md
- docs/users/topics/version-history.md
* Minor docs updates for v1.19.0 release
* Change the ddev-gitpod-base image to use install_ddev.sh without an argument
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3675"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> v1.19.0 docs updates, version history, etc.

- .gitpod.yml
- pkg/ddevapp/ddevapp.go
- pkg/version/version.go
We noticed in v1.19.0-rc2 and earlier versions that on gitpod every startup left a pile of dead containers. 
It seems this is a result of 
* https://github.com/docker/compose/pull/9012
which was fixed between docker-compose v2.2.2 and v2.2.3.
* This changes docker-compose version from v2.2.2 to v2.2.3
* Make sure that `ddev ssh` and related don't try to use docker-compose without -T arg if there's no tty
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3677"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix piles of dead containers from the docker build process

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/healthcheck.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- pkg/ddevapp/compose_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/hardened_test.go
- pkg/ddevapp/mutagen.go
- pkg/version/version.go
With v1.19.0-rc2, manual testing proved that hardened images didn't work.
* Fix up the reasons
* Make clear not compatible (currently) with mutagen
* Add a simple test for the hardened images situation
`ddev config global --use-hardened-images && ddev poweroff && ddev start`
Added TestHardenedImages
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3680"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make hardened images work and provide test

- .github/workflows/master-build.yml
- docs/users/cli-usage.md
- docs/users/docker_installation.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/drupal.go
* On uploading artifacts, drop into tmate on failure. Unfortunately GitHub fails quite often uploading artifacts, and it may be easier to solve by going into the build.
* Minor docs updates to installing docker inside WSL2
* Make PHP 8.0 the default version for Drupal9, since it insists on that.
* Minor fixup to Quickstart docs to use `--no-install` with `ddev composer create`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3684"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> v1.19.0 release prep final steps

- .ci-scripts/generate_artifacts.sh
We don't need to take a really long time to build image tarballs since the consumer was drud/quicksprint.
Remove it
> Remove building image tarballs [skip ci]

- docs/users/cli-usage.md
When the user clones a lean repository but has not yet run the
`composer install` command, then using `ddev config --auto` will not
work because the files that the detection needs are not yet present.
Updates the documentation that users were following and not having luck with.
Clone a lean repository for a Drupal 9 site (say, from a Pantheon site using Integrated Composer). Run `ddev config --auto` before doing a `composer install`. Note that the generated config.yaml will not be Drupal 9.
Documentation update only.
Issue not filed. Discussed in Drupal Slack: https://drupal.slack.com/archives/C5TQRQZRR/p1646971651968869
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3690"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> More accurately reflect necessary setup for D9.

- pkg/ddevapp/global_dotddev_assets/commands/web/magento
* #3699
Currently the command looks for a script/binary "magento"
in the $PATH which is not available in a general Magento installation.
Change the script to use the shipped bin/magento.
If Magento is not installed via "composer install", the "bin/magento"
script is not available. So the check if ok with the right path.
Fix the path to magento script.
Start a Magento project with a Magento installation in a sub-directory and set working_dir.
Automatic test requires a Magento installation or a dummy script. Let's see if we can add that in the future.
Issue was introduced in ddev v1.19.0.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3700"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use bin/magento in magento command, fixes #3699

- .github/workflows/docscheck.yml
- markdown-link-check.json
* https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/127
Roll it back to 1.0.13 to see if it sorts things out.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3706"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Roll back github-action-markdown-link-check to 1.0.13

- cmd/ddev/cmd/exec_test.go
- cmd/ddev/cmd/stop_test.go
- cmd/ddev/cmd/xdebug_test.go
- docs/users/troubleshooting.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/composer_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/nodejs_test.go
- pkg/exec/exec.go
- pkg/testcommon/testcommon_test.go
- pkg/version/version.go
In v1.19.0 it is impossible to capture stdout from `ddev exec`. For example `ddev exec ls -lR >/dev/null` will display the output. This seems to be a regression in docker-compose v2.2.3, which was used in ddev v1.19.0
Pointed out in:
* https://github.com/drud/ddev-contrib/issues/206
Bump to docker-compose v2.3.3, seems to solve it.
`ddev exec ls -l >/tmp/out.txt` should show nothing. And you should find the output in /tmp/out.txt
* I added to TestCmdExec a section that deliberately redirects output to a file. However, I wasn't able to recreate the actual behavior that we all saw even when I ran the test against v1.19.0 (and docker-compose v2.2.3). The test succeeded. I assume this must have something to do with pty detection by docker-compose.
<a …
> Bump docker-compose to 2.3.3 to solve problems with ddev exec stdout capture, fixes #3698

- docs/users/docker_installation.md
- pkg/dockerutil/dockerutils.go
* #3703 
* Use a more robust way to access the output of `df /`
* Update/remove some obsolete docs instructions about fedora
`ddev start` on fedora, look for the complaint about not being able to check.
No testing is in place for fedora, and won't be.
\
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3704"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make docker disk check work on fedora, fixes #3703

- .github/workflows/colima-tests.yml
- pkg/dockerutil/docker_compose_version_test.go
- pkg/version/version.go
docker-compose 2.3.3 uses a version without the 'v' on the front. TestDockerComposeDownload didn't recognize that. Not sure how tests passed before. 
Handle version with or without v.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3716"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests] Fix TestDockerComposeDownload to handle version with or without v

- docs/users/cli-usage.md
- docs/users/extend/additional-services.md
Elasticsearch has moved to https://github.com/drud/ddev-elasticsearch
Update docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3715"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add elasticsearch in list of official services

- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer_test.go
On traditional Windows, it's not possible to change permissions on a mounted file, so the `rsync -a` in `ddev composer create` fails:
* #3712 
Don't try to set permissions on Windows, use lesser rsync command
This has always been excluded on Windows, but I attempted to simplify the test section to see if maybe it can be tested on Windows and we'd have caught and error like this. It may not work
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3720"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use altered rsync for composer create on Windows, fixes #3712

- .vscode/launch.json
- cmd/ddev/cmd/clean.go
- cmd/ddev/cmd/delete-images.go
Provide a new clean command
This creates a new command
Run `ddev clean projectname` and verify the snapshots have been removed
No tests have been created. I would like to create the tests.
#2332 
No
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3683"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
>  Add `ddev clean` command, fixes #2332

- pkg/ddevapp/typo3.go
See https://stackoverflow.com/questions/71509163/php-warning-in-typo3databasebackend-line-158-after-updating-ddev-to-1-19
A default TYPO3 v11 install shows this warning on the BE pages:  
> Core: Error handler (BE): PHP Warning: gzuncompress(): need dictionary in /var/www/html/public/typo3/sysext/core/Classes/Cache/Backend/Typo3DatabaseBackend.php line 157
The TYPO3-generated LocalConfiguration.php uses driver mysqli, not pdo_mysql. Use the one TYPO3 uses.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change default TYPO3 mysql/mariadb driver to mysqli

- cmd/ddev/cmd/get.go
There's a piece of code I ran into when using ddev on a flight with no wifi... it gives a SEGFAULT. 
This fixes it. Tested on the plane
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3736"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't use invalid resp.Rate when nil - ddev get when no inteernet

- pkg/ddevapp/composer_test.go
In Composer 2.3.x upstream changed the output of composer --version
and it broke TestComposerVersion
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3742"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] TestComposerVersion fixup for composer 2.3.x

- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
Container timeout due to healthcheck didn't give enough information
Figure out what container(s) aren't healthy and give info about that.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve message when an add-on times out due to healthcheck

- containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/enable_xhprof
`ddev xhprof on` states that it generates a profile for web requests.
It makes a precision that it works for CLI processes too.
`ddev xhprof on` should have a more precise output now.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3752"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> More precise output for xhprof enable

- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/utils.go
For custom commands and when Docker Desktop isn't running ddev tells me "Error: unknown command 'drush' for 'ddev'  Run 'ddev --help' for usage."
(This is a Cobra error message)
This check that Docker is running in root init for commands.
Turn Docker off and try running a command and a custom command.
No test provided. I can provide tests with assistance.
#3336 
No
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3746"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Determine if the command requires Docker running, fixes #3336

- docs/users/cli-usage.md
The example missed the `ddev config` step.
This removes a sentence that was not really necessary. It add `ddev config` and finally a `ddev launch` to be in line with the other examples.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3779"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix TYPO3 Git clone example

- .github/workflows/colima-tests.yml
- .github/workflows/macos-colima-setup.sh
Colima install has been failing consistently apparently since go 1.18 release. Try to fix with fresh cache.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Try to fix colima install - homebrew with cache flush

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- pkg/version/version.go
* #3765 points out that drush8 isn't linked for use in Backdrop. This fixes that.
* Configure a backdrop project
* Start it
* `ddev drush --version`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Link drush8 for backdrop, fixes #3765

- CONTRIBUTING.md
- docs/developers/building-contributing.md
- markdown-link-check.json
There have been several new docs link-check failures recently, see
* https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/136
This just ignores the docs.github.com and guides.github.com links.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3787"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Try to fix markdown link failures

- pkg/ddevapp/providerAcquia_test.go
TestAcquiaPull has been failing all the time.
Drush now doesn't seem to explicitly require symfony/http-kernel so we just need to do that in the installation
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3789"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix TestAcquiaPull as drush has new dependency

- docs/users/cli-usage.md
That page is too convoluted already. Information that is not specific to a framework should not be unnecessarily repeated there.
This removes information unspecific to TYPO3 from that section.
As a drive-by change it beautifies the big bold block for legacy TYPO3
installation.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3780"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove unnecessary information from TYPO3 quickstart

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config-global_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- docs/users/extend/customization-extendibility.md
* #3691
Allows a user to append environment variables to a web container rather than overwriting them all. See #3691
Adds a `--web-environment-add` option to `ddev config`
```
$ composer create-project drupal/recommended-project ddev-test
$ cd ddev-test
$ ddev config
$ ddev config --web-environment="FOO=bar"
$ cat .ddev/config.yaml 
.
web_environment:
- FOO=bar
.
$ ddev config --web-environment="BAR=baz"
$ cat .ddev/config.yaml
.
web_environment:
- BAR=baz
- FOO=bar
.
```
Test added to `cmd/ddev/cmd/config.go`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3697"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a config --web-environment-add command which appends environment variables to the web container configuration

- cmd/ddev/cmd/share_test.go
ngrok 3.0.2 changed the args from single hyphen to double, so TestShareCmd has to change
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3790"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Fix TestShareCmd - args for ngrok changed in 3.x

- cmd/ddev/cmd/clean.go
See companion PR at #3770 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3771"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Clarify that only images from drud/ddev are deleted

- cmd/ddev/cmd/delete-images.go
Our additional service uses an image called `massgov/mysql-sanitized`. We had hoped it would be deleted with a `ddev delete images` since it is known to ddev via a compose file. But it isn't.
We solved our need with `~/.ddev/bin/docker-compose -f .ddev/.ddev-docker-compose-full.yaml down --rmi all`
Improve docs
N/A
N/A
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3770"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Clarify that `delete images` wont operate on 3rd party images

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
* #3766 
requests an altered MTU in gitpod context. Normally this is not something ddev would have to be involved with.
Conditionally set the MTU.
@shaal please include testing instructions.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3773"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set MTU for gitpod, fixes #3766

- cmd/ddev/cmd/snapshot.go
`ddev snapshot --help` command says ddev snapshot --all should only snapshot running projects.
It still tries to snapshot a stopped project and then fails.
`ddev snapshot --all` will now start any stopped or paused apps and create a snapshot and then place the app back to its original state of stopped or paused.
- Have three or more projects
- Stop one project and pause another and start the others
- Execute ddev snapshot --all
- Will create a snapshot of all projects
- Project stopped or paused will be set back to stopped or paused after snapshots
Run existing tests
#3707
No deployment changes
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3749"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev snapshot -a should snapshot all apps and not fail just because one isn't running, fixes #3707

- .github/workflows/codeql.yml
This adds codeql coverage per https://github.blog/2022-04-22-5-simple-things-every-developer-can-do-to-ship-more-secure-code/
I don't know if it will be useful or not.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3793"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add codeql coverage [skip ci]

- pkg/dockerutil/dockerutils.go
* #3794 
When docker (client) is not in $PATH, `ddev --version` fails, and `ddev --version` is used as the test in `brew install`. And in the context of `brew install` docker is not in the $PATH.
Just look and see if we're trying to do `ddev --version`, `ddev version`, `ddev help` before trying to use docker. 
This replaces the alternate approach in 
* #3796
I think that github.com/drud/homebrew-ddev should have basic tests... make sure that a homebrew install can be done.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3798"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't try to use docker client for ddev --version, fixes #3794

- docs/users/providers/platform.md
Stray backtick in the yaml example.
Removes it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3802"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove extra backtick in platform.sh instructions

- .github/workflows/colima-tests.yml
- .github/workflows/macos-colima-setup.sh
- .github/workflows/pr-build.yml
- .github/workflows/tests.yml
- cmd/ddev/cmd/root.go
It turns out that yesterday's adjustment to allowing `ddev --version`, 
* #3798
didn't work for colima, which has to have the docker context set in most cases
Related still: 
* #3794 
This also changes the event everywhere to `pull_request` from `pull_request_target`, which I'm pretty sure it should be. With `pull_request_target` it's actually testing the upstream/master, which is not what we want.
Remove the version check for the same set of ddev commands
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3803"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't always check for ddev version, stop using pull_request_target for #3794

- cmd/ddev/cmd/root.go
- pkg/dockerutil/dockerutils.go
`ddev version` isn't working properly
Don't exclude `ddev version` from the docker setup initializations.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't skip docker setup for ddev version

- docs/developers/building-contributing.md
When I tried to use ddev artifacts from a PR first, I wasn't sure which DDEV version was used and if the replacement worked on my laptop.
Also the link step should be at the end of all steps (in my humble opionion).
Add info about `ddev -v` which will give you an exact info whether it worked (or not ;-))
No, just docs
No, just docs
No, just docs
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3807"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] Improve docs for PR testing, add step for checking

- docs/users/cli-usage.md
Since I did use this [quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#command-line-setup-example-using-wp-cli) many times, I experienced that installing WordPress in the browser window (user, password) is way more comfortable.  For new users the optional step described might be confusing. 
Moves the 'ddev launch' command above the (possibly confusing) optional step. 
No tests, just docs.
See previous discussion https://github.com/drud/ddev/issues/3299
No
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3806"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] Move 'ddev launch' above optional step (WP CLI quickstart)

- .github/workflows/pr-artifacts-comment.yml
* https://github.com/oprypin/nightly.link/issues/37
Use the older version that works.
This was also not working here for(ever) because we were using pull_request_target in the "PR Build", so it didn't match the code needed here. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3810"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Use working version of artifact commenter

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/version/version.go
v1.19.2 is about ready. 
Bump webserver and dbserver images to v1.19.2.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3804"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump image versions to v1.19.2

- cmd/ddev/cmd/debug-refresh.go
- cmd/ddev/cmd/debug-refresh_test.go
Docker cache can be pretty confusing, and it turns out that Dockerfile RUN commands like `composer self-update` can be cached *across all projects*, which means that composer isn't even updated on a new project.
This adds a `ddev debug refresh` command that does a `docker-compose build --no-cache`, hopefully allowing a reset of this situation.
```dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN shuf -i 0-99999 -n1 > /random.txt
```
Added TestDebugRefreshCmd
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3808"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add ddev debug refresh command to solve composer issues

- .gitpod/images/Dockerfile
`ddev config` no longer works without docker available.
And the Dockerfile for the gitpod image used it.
Instead of using `ddev config global` just output a starter global_config.yaml
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3816"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix ddev-gitpod image build: Don't try to use ddev config in gitpod image

- docs/users/performance.md
The recommended way is to enable mutagen per-project 
if you don't want it enabled in each DDEV project.
Fixes: #3821
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3822"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [DOCS] Add info about mutagen global enable option, fixes #3821

- .github/workflows/pr-artifacts-comment.yml
This reverts commit 2aa08b47c6180c9d5a2be6e3d95757a64470de17.
pr-artifacts-comment was working until dependabot upgraded things.
Revert.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3835"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert "Bump actions/github-script from 3 to 6 (#3826)"

- .github/workflows/colima-tests.yml
- .github/workflows/container-tests.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/master-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/push-tagged-image.yml
- .github/workflows/tests.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3763"><img …
> Set permissions for GitHub actions

- docs/users/performance.md
- pkg/ddevapp/config.go
- pkg/ddevapp/global_dotddev_assets/commands/web/yarn
https://github.com/drud/ddev/issues/3741
Executes the command right inside the web container so no further CLI parameter tweaking is necessary.
`yarn gulp <someTaskName>`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3836"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Move yarn command from host to web (#3741)

- docs/users/performance.md
- pkg/version/version.go
Mutagen v0.14.0 has been released, with lots of logging and instrumentation improvements.
Try it on tests.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3786"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump mutagen to v0.14.0

- .github/workflows/colima-tests.yml
Colima has a new version v0.4.* that requires starting from scratch, so we need to get rid of the existing cache.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Refresh colima/homebrew caches to get new

- pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
Sometime you use multiple databases in a project (e.g. for migration). 
Currently, using ddev sequelace opens directly the default database "db" so the user has to switch manually to the database she/he would like to use.
This adds an option to ```ddev sequelace``` to specify a database name different from "db" so the command directly opens the database.
* create a simple project with DDEV
* add another database to the project
* run ```ddev sequelace <database name>```
* https://github.com/drud/ddev/issues/3847
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3848"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow choosing a different database when opening sequelace, fixes #3847

- docs/developers/building-contributing.md
- docs/developers/project-types.md
* A couple of new project types (django and craftcms) are slotted for this release cycle, and a couple of people are interested in working on those. So adding a set of docs about how to do it.
* It's not simple to figure out how to push a multi-arch image and use it in ddev. Improve those docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3857"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add how to add project type, improve docker push info

- docs/users/cli-usage.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/magento.go
* #3852 
* Magento 2 quickstart doc broken
* Magento 2 now requires php 8.1
* Fix the quickstart docs (thanks @cmuench !)
* Set the default PHP version for magento2 to php8.1
Walk through the quickstart and verify it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3853"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix magento 2 quickstart and set php default to 8.1, fixes #3852

- cmd/ddev/cmd/ssh_test.go
- pkg/ddevapp/ddevapp.go
With docker-compose 2.5.1...
* https://github.com/drud/ddev/pull/3851#issuecomment-1132745998 (discussion)
* https://github.com/docker/compose/issues/8881
* https://github.com/compose-spec/compose-go/pull/197
Bottom line is that `ddev ssh` and `ddev exec` (possibly other things) don't work if COMPOSE_PROJECT_NAME has a dot in it. You get:
```
$ ddev ssh
service "web" is not running container #1
Failed to ddev ssh web: exit status 1
```
I imagine since ddev was using COMPOSE_PROJECT_NAME initially with `docker-compose config`, which inserts `name` into the .ddev-docker-compose-full.yaml (without dots) and then uses that .ddev-docker-compose-full again with COMPOSE_PROJECT_NAME set (and with a dot in it), that it triggers an obscure edge case.  It's easier to remove the dot here than to …
> Dont' use compose project name with dots, add dot test

- pkg/util/network.go
@nico-loeber and @jonaseberle  discovered that when docker-compose is getting updated non-json output is output as a progress bar for the download. 
* https://github.com/php-perfect/ddev-intellij-plugin/issues/56
In json mode ddev can show non-json output if downloading a file, especially docker-compose or mutagen. 
`rm -f ~/.ddev/bin/docker-compose && ddev start -j` will show non-json output as described in the issue:
```
$ ddev version --json-output
{
"level": "info",
"msg": "Downloading https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-linux-x86_64 ...",
"time": "2022-05-22T12:42:34+02:00"
}
docker-compose 25.30 MiB / 25.30 MiB [=======================================================================================================] 100.00% 5s
{
"level": "info", …
```
> Don't show download progress bar when in json mode

- containers/ddev-router/nginx.tmpl
- pkg/versionconstants/versionconstants.go
@deviantintegral pointed out in Discord that ddev-router is creating two upstream hosts for every port, resulting in inappropriate round-robin behavior of the reverse-proxy nginx inside ddev-router. https://discord.com/channels/664580571770388500/976181828341866526
More discussion in the PR that probably introduced this behavior inadvertently:
* https://github.com/drud/ddev/pull/3403#issuecomment-1132892462
Upstreams in ddev router (shown by `ddev debug router-nginx-config`) show both of the IP addresses (for the two networks that the container belongs to), resulting in inappropriate round-robin behavior, as if there were actually two different containers out there:
```
upstream d7.ddev.site-80 {
keepalive 100;
server ddev-d7-web:80;
server ddev-d7-web:80;
}
```
Instead, with this PR, the …
> ddev-router should only output one upstream per container port

- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/ssh_test.go
- pkg/ddevapp/hardened_test.go
Some tests commonly fail on mac M1 (Docker Desktop) due to failure to connect, per
* https://github.com/docker/for-mac/issues/5407
Turn off a few tests.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3866"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Tests only] Turn off some tests that commonly fail on mac M1

- cmd/ddev/cmd/hostname.go
- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_test.go
- cmd/ddev/main.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
Warnings and errors are not written to stderr consistently.
Apart from a general unpredictability, warnings can disturb automatically evaluated output.
To make the output more predictable all warnings and errors, I was able to find, are now written to stderr.
Executing any ddev commands on the command line should still show exactly the same result.
To test if warnings are written to stderr you can run the command outputting the error / warning to show stdout only by adding `2>/dev/null`. 
For example `ddev describe 2>/dev/null` should now show a clean output. 
N/A
This will help to improve stability when using the [DDEV Integration plugin](https://github.com/php-perfect/ddev-intellij-plugin).
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3863"><img …
> Make sure that errors and warnings are written to stderr

- cmd/ddev/cmd/composer_test.go
- pkg/ddevapp/app_compose_template.yaml
* #3702 
Web container should depend on db container readiness unless omit_containers
This adds a `depends_on` for the web container if no `omit db`
Start a ddev in a new project, look in the `.ddev-docker-compose-full.yaml `file
No tests added
#3702 
N/A
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3858"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Web container depends on db container, fixes #3702

- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
- pkg/ddevapp/utils.go
- pkg/ddevapp/utils_test.go
As a user I want to start a project by name. If the current working dir is not the project root, then I need to know the project name. Then I have to use `ddev list` to find the right name. Developers are lazy. So they have to copy the name to the clipboard.
Provide an interactive selection of the project by adding a parameter `-s` to the `start` and `stop` command.
Run `ddev start -s` or `ddev stop -s`
There are two new function in ddevapp.
- `ddevapp.ExtractProjectNames`
- `ddevapp.GetInactiveProjects`
There is a new file util_test.go which covers both new functions.
For the interactive command is currently no test available, because I do not know how we can test it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3760"><img …
> Add interactive project selection to start and stop command

- pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example
Acquia Cloud may default to outdated drush versions. Additionally, Drush/Ddev integration has a known problem of including error output in sql-dump (see https://github.com/drud/ddev/issues/2839). Therefore if there happens to be a missmatch of the drush version, the gzipped database file may contain error text like this:
```
Deprecated: Required parameter $args follows optional parameter $command in /usr/local/drush9/vendor/drush/drush/includes/batch.inc on line 115
Deprecated: Required parameter $options follows optional parameter $command in /usr/local/drush9/vendor/drush/drush/includes/batch.inc on line 115
```
Resulting in an error running the pull command:
```
Pull failed: failed to extract provided archive: gzip: invalid header
```
1. Replace `drush sql-dump` with `acli pull:db`. …
> Use acli to sync database from Acquia

- docs/users/extend/customizing-images.md
- docs/users/troubleshooting.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
* Automatically add the `ARG BASE_IMAGE` and `FROM $BASE_IMAGE` so the user doesn't have to remember those 
* Remove the need to add BASE_IMAGE to the Dockerfile and make sure that this won't create issues for already created Dockerfiles
* Add the capablity to have `Dockerfile.*`, like `Dockerfile.cron` and `Dockerfile.elasticsearch`, all of which will get built into the .ddev/webimageBuild/Dockerfile
Discord reference: https://discord.com/channels/664580571770388500/689166305315520541/979760093602123796
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Docs change: https://github.com/hanoii/ddev/blob/2022_hanoii_custom_dockerfile_last/docs/users/extend/customizing-images.md
> Remove need for `ARG BASE_IMAGE` etc and allow multiple Dockerfiles

- pkg/ddevapp/config.go
- pkg/versionconstants/versionconstants.go
It's time for DDEV v1.19.3
Bump web and db images with fresh content
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3880"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump web, db, router images for v1.19.3

- cmd/ddev/cmd/debug-capabilities.go
- cmd/ddev/cmd/debug-capabilities_test.go
DDEV add-ons need a way to check to see if the ddev version running is up to the task. For example, several add-ons will soon need the multiple Dockerfiles feature that just went in. 
This could be checked with a version check, but the version checking capability in bash is awful, and it's hard to understand where else to put it in most add-ons.
Add `ddev debug capabilities` to be able to test for a capability, like `multiple-dockerfiles`.
`ddev debug capabilities`
`ddev debug capabilities -`
Added TestDebugCapabilitiesCmd
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3879"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> `ddev debug capabilities` provides an easy way to test capabilities without version compare

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
* https://github.com/drush-ops/drush/issues/4979 - The latest drush8 versions have odd output and some problems. Previous 8.4.8 seemed to work right for a long time. This is typically only used with Drupal 7 and lower PHP versions. It should be fine. 
* https://github.com/drud/ddev/issues/3867 - After previous image build platformsh-cli should fix #3867 
Downgrade drush8, rebuild
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3882"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Downgrade drush8 to 8.4.8, refresh to get latest platform cli tool

- .github/workflows/cancel-previous-workflow.yml
- .github/workflows/codeql.yml
- .github/workflows/tests.yml
The default way GitHub Actions works is that a new push just creates a new set of test runs, which very quickly uses up all the available runners (20 total concurrent jobs, 5 macOS), https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
* Change to cancel previous workflow when a new push comes in on forked PR or master.
* Limit the size of tests run in the main tests.yml matrix. They were too big.
* Limit scope of codeql.yml to just golang
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3884"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Cancel workflow on PR or master when another push comes

- .github/workflows/cancel-previous-workflow.yml
- .github/workflows/push-tagged-dbimage.yml
- .github/workflows/push-tagged-image.yml
- containers/ddev-dbserver/Makefile
- docs/developers/building-contributing.md
* The dbimage build takes forever, doing each build sequentially (currently 13 images)
* To restart after a weird failure you have to restart the whole thing.
* Build them in parallel, and you can restart failed jobs as needed.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3885"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Split the dbimage build into a matrix for performance and restart capability

- .github/workflows/codeql.yml
- .github/workflows/colima-tests.yml
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/nodejs_test.go
A number of tests are really flaky and we have no control. 
* Docker for Mac M1 has constant networking problems, 
* https://github.com/docker/for-mac/issues/5407
* Colima has constant port conflict problems
* https://github.com/abiosoft/colima/issues/189
* Fail fast on Colima, because it's always a waste after the first failure
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3896"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Minor test cleanups and exclusions

- pkg/testcommon/testcommon_test.go
In cleaning up repositories I deleted the old drud/wordpress repo. I shouldn't have.
This changes it to use the same WP download as the other tests use
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3900"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Tests only] Fix TestValidTestSite

- docs/users/snippets/atom_config_cson_snippet.txt
- docs/users/step-debugging.md
GitHub has dropped support for Atom, and I've never heard of anybody using it for debugging, so removing it from the docs. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3902"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove atom debug instructions as github has dropped atom

- cmd/ddev/cmd/clean.go
- cmd/ddev/cmd/utils.go
* #3892 
The OP in #3892 was surprised by the `ddev poweroff` happening before the y/n prompt and thought all their projects were being deleted. 
Check for valid project and do poweroff *after* the y/n prompt.
`ddev clean .` - or some other permutations.
I think existing is ok.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3901"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev clean: Do poweroff later so it's not scary. Check for projects first, fixes #3892

- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
I noticed in studying some "-built" containers that everything I'd ever done was ending up in then. It turns out that in the recent addition of `Dockerfile.*` we didn't clear out the .ddev/.webimageBuild or .ddev/.dbimageBuild before starting over with them, so we end up with lots of crap in there. Lots in my case. 
Clear those directories before using them.
I think this does need a test.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3906"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> .webimageBuild and .dbimageBuild must be empty before using

- pkg/ddevapp/config.go
- pkg/ddevapp/dotddev_assets/providers/README.txt
The #ddev-generated marker was missing from Dockerfile.example, causing `ddev get` to balk at overwriting the .ddev/web-build directory.
Add it in
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3916"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev-generated was missing from Dockerfile.example, breaking some ddev get

- cmd/ddev/cmd/commands_test.go
- pkg/ddevapp/global_dotddev_assets/commands/web/npm
npm is a common development tool and it can be exhausting having to type ddev exec npm ... each time.
Enabling a global command to pass this into the web container makes it a much smoother task.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3886"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add `ddev npm` command

- pkg/ddevapp/global_dotddev_assets/commands/web/wp
The wp command didn't have #ddev-generated in it. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3918"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> wp command needs #ddev-generated [skip ci]

- cmd/ddev/cmd/get.go
- docs/users/extend/additional-services.md
- pkg/util/yamltools.go
Environment variable replacement in install.yaml actions made it impossible to use environment variables. 
Stop doing that.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3922"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> No environment replacement in install.yaml actions

- .github/workflows/selfhosted-upgrades.sh
- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config-global_test.go
- pkg/globalconfig/global_config_test.go
- pkg/nodeps/values.go
I often find that the internet detection timeout is incorrect and it wants to add a hostname to /etc/hosts
Use longer timeout. It usually won't matter
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump the internet detection timeout to 3000=3s

- docs/developers/building-contributing.md
The container WebImg and WebTag variables have been moved to pkg/versionconstants/versionconstants.go
This PR updates the paths in the documentation.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3925"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update documentation: Docker image development

- pkg/ddevapp/app_compose_template.yaml
I noted that some newer env vars (DDEV_DATABASE, GOOS, GOARCH) didn't make it into the container, while they were available on the host.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3927"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure newer env vars get into containers

- docs/users/topics/database_management.md
The “Managing Databases” page in the docs was referencing a `ddev restore-snapshot` command that doesn’t exist anymore.
Replaces the reference with `ddev snapshot restore`.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3929"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> restore-snapshot → snapshot restore

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
https://github.com/drud/ddev/issues/3920
This PR adds the PHPStorm required directory `/opt/phpstorm-coverage`  to the web-container with read/write premissions for the cli user.
As discussed in #3920, a Docker volume would allow persistence of the coverage reports, but I don't think this is necessary. Therefore, adding the directory was the easiest solution.
PHPStorm does allow loading coverage data from previous runs, but it does not load it automatically at startup. This is a pretty hidden feature and I don't think anyone would use it.
The directory `/opt/phpstorm-coverage` should exist right after `ddev start`. 
Your default user (not root) should be able to read / write files in this directory.
I don't think tests for this are needed.
* https://github.com/drud/ddev/issues/3920
Please …
> Add `/opt/phpstorm-coverage` directory to web-container

- docs/users/cli-usage.md
https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-10-quickstart has missing code block ending, breaks D6/7 quickstart
Adds missing ticks
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3934"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] missing close to code block on d10 quick start

- pkg/dockerutil/dockerutils.go
IsColima() detects whether we're on colima; among other things this lets us generate host.docker.internal
But it may not just be "colima", it may be "colima-9p", more generally "colima-<profile>". 
Change to look at the docker name profile.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3935"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Colima name may only be a prefix - fix IsColima()

- .github/workflows/cancel-previous-workflow.yml
The latest version of the cancel-workflow github action allows workflow_id: all
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3943"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests] Use new workflow_id in cancel-previous-workflow [skip ci]

- cmd/ddev/cmd/logs.go
I had a web container crash and ddev wouldn't give me the logs with `ddev logs`. 
Try to get the logs even if the project is unhealthy.
Kill a container and do `ddev logs` against it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3942"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Try to get logs even if site unhealthy

- containers/ddev-ssh-agent/Dockerfile
- pkg/versionconstants/versionconstants.go
To update to bullseye-slim
Changes the version for ddev-ssh-agent container
Poweroff ddev and removed ssh agent images
Start a ddev project and should see pulling the new image
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3931"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use bullseye-slim for ssh agent container, fixes #3250

- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/testcommon/testcommon.go
* The composer full restriction on no plugins went into effect, breaking TestAcquiaPush and TestPantheonPush
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3950"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Acquia/Pantheon fixes post-composer-no-plugins

- .ci-scripts/generate_artifacts.sh
- .github/workflows/master-build.yml
- .goreleaser.yml
- .spellcheckwordlist.txt
- Makefile
- cmd/ddev_gen_autocomplete/ddev_gen_autocomplete.go
- docs/developers/release-management.md
- docs/index.md
- docs/users/docker_installation.md
- scripts/install_ddev.sh
- winpkg/ddev.nsi
* https://github.com/drud/ddev/issues/3723
* https://github.com/drud/ddev/issues/1678
Uses goreleaser for almost all of the post-build release process
There are a thousand things to test once we make a release using this.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3939"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use goreleaser for most release actions, add apt and yum repositories, fixes #3723, fixes #1678

- pkg/ddevapp/composer_test.go
- pkg/ddevapp/mutagen_test.go
The composer plugin requirement broke TestComposer
Allow plugins.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3964"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Tests only] Fix TestComposer for new composer requirement

- .github/workflows/master-build.yml
- docs/content/developers/release-management.md
I noted some release flow obsoletes and tried to remove/reorg.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3970"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor release workflow cleanup [skip ci]

- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_test.go
Brand new users get asked if we can do a `ddev poweroff`, but it doesn't make sense.
Don't ask them if they're brand new (last_used_version == v0.0)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3965"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't ask people to ddev poweroff if first use of ddev

- docs/content/users/install/ddev-installation.md
- docs/content/users/install/docker-installation.md
- docs/content/users/install/performance.md
- docs/content/users/install/shell-completion.md
- docs/content/users/quickstart.md
I took a closer look at the Start tab in the new documentation https://ddev.readthedocs.io/en/latest/ and changed a few things:
* fixed several small typos
* corrected the position for `!!!warning`, `!!!note`, `!!!tip` (they must be separated by a new line from everything above)
* removed extra spaces
* fixed code style for bash inserts
* removed/changed links from the old docs
* "macOS Full Disk Access for Special Directories" was in Windows tab
* "macOS-specific NFS debugging" was in the wrong place (not in the macOS tab, but under it, and with broken formatting)
* added formatting for file paths (e.g. settings.php became `settings.php`)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3979"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improvements for Start tab [skip ci]

- .spellcheck.yml
- docs/content/users/install/performance.md
* #3981 
Indented blocks were considered code by superfences, so were not inspected. 
I tested this without the spellcheck fixes from https://github.com/drud/ddev/pull/3979 (listed in #3981) and it now catches them.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3982"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix spellcheck configuration to inspect indented blocks, fixes #3981

- cmd/ddev/cmd/commands.go
- pkg/ddevapp/commands.go
* #3955 
Ugly output in a project that hasn't gotten its .global_commands directory created yet
Make sure it's created
```
mkdir junk && cd junk
ddev get drud/ddev-cron
```
You shouldn't see any ugly output, but all shell-based commands should work as well.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3987"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure that the temp global commands dir is created, fixes #3955

- docs/content/users/quickstart.md
`APP_URL` should be set correctly in Laravels `.env`, this was missing in the [quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#laravel-quickstart).
I added and tested the following on OSX 11.6.5 and ddev version v1.19.1.
```bash
ddev exec 'sed -i "/APP_URL=/c APP_URL=$DDEV_PRIMARY_URL" .env'
```
A more readable version (as described [here](https://programarivm.medium.com/how-to-set-a-web-env-variable-from-the-command-line-on-linux-unix-a06016bb9b89)) would be the following. 
```bash
sed -i "s/APP_URL=.*/APP_URL=${DDEV_PRIMARY_URL}/g" .env
```
But I couldn't get it to work with quote escaping. 🤔
No tests needed, just docs improvement
- https://github.com/drud/ddev/issues/3636
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3949"><img …
> [Docs] Laravel Quickstart: Add command to automatically replace APP_URL with $DDEV_PRIMARY_URL

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp.go
* #3688 
* Don't create upload_dir except when using mutagen
* Warn if there's a problem, instead of failing
No new tests
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3952"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't create upload_dir if not in mutagen, warn instead of failing, fixes #3688

- containers/ddev-webserver/Dockerfile
- docs/content/users/providers/acquia.md
- pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example
- pkg/ddevapp/providerAcquia_test.go
- pkg/versionconstants/versionconstants.go
* #3511 : Use current versions of acli (Acquia cli tool)
* #3333: Use an existing backup on Acquia instead of dumping it ourselves
* Minor changes to TestAcquiaPull to accomodate.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3951"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use current acquia acli, fixes #3511 and use existing backup in integration, fixes #3333

- .circleci/config.yml
CircleCI keeps trying to test the gh-pages branch
Turn that off
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3993"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> CircleCI should ignore gh-pages

- docs/content/users/extend/customizing-images.md
- pkg/ddevapp/config.go
* #3988 
* #3960 
In DDEV v1.19.3, multiple user Dockerfiles were supported, and they were all added *after* the initial portions of generated Dockerfile content. This meant that things like HTTP_PROXY/HTTPS_PROXY could not be added before the `apt-get` things or related things. And it also meant that things like custom-cert installation couldn't be done before the other things happened. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3990"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Insert user Dockerfiles earlier, fixes #3988, fixes #3960

- .github/workflows/master-build.yml
* #3996 
Put the stanzas in that used to do that on master build
On next master pull, (or when this one gets pulled) see if the binaries show up on the workflow page.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3998"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Publish binaries on master workflow, fixes #3996

- .gitpod.yml
- .gitpod/images/push.sh
* https://github.com/drud/ddev-gitpod-launcher/issues/22
Push a new image. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4002"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Gitpod image needs explicit tag, and it needs to be bumped, fixes ddev-gitpod-launcher#22 [skip ci]

- .github/workflows/master-build.yml
- cmd/ddev/cmd/debug-capabilities.go
- docs/content/users/extend/customizing-images.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
Partially reverts 
* #3990 
with a `pre.Dockerfile.*` approach and keeping regular `Dockerfile*` at the end of the insertions.
From Discord: https://discord.com/channels/664580571770388500/997163304822771842
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3999"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support for pre.Dockerfile.*

- .github/workflows/master-build.yml
- .gitignore
Latest release tests resulted in a failure because the /artifacts directory gets created, so showed git dirty.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4007"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> gitignore /artifacts and do goreleaser before artifacts

- docs/content/users/install/ddev-installation.md
* #3997
Debian apt packages are now signed, fix doc to show that approach.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4008"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Show how to use signed debian packages, for #3997

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Time for new release. Bump to new images.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4010"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump docker images for v1.19.4

- pkg/versionconstants/versionconstants.go
Bump images to v1.19.5
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4011"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images to v1.19.5

- .gitpod.yml
- .gitpod/images/Dockerfile
DDEV v1.19.5 is out, need to bump gitpod image
Bumps it.
Also switches to using apt-get to install ddev instead of using install_ddev.sh
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4018"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump gitpod usage of ddev to use apt and apt-get upgrade it [skip ci]

- pkg/ddevapp/ddevapp.go
It's a great thing to get information on failing patches immediately.
Uses https://github.com/cweagans/composer-patches/blob/1.x/src/Patches.php#L285
Apply a broken patch on the codebase and see the exit code of `ddev composer install`
-
As it might be a breaking change for some, we might need to wire it into the config and make it adjustable.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/3795"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Composer should fail if patches fail

- .buildkite/test.sh
- .circleci/config.yml
- .github/workflows/tests.yml
- containers/ddev-dbserver/Makefile
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/laravel.go
- pkg/ddevapp/magento.go
- pkg/nodeps/mariadb_values.go
- pkg/nodeps/mariadb_values_darwin_arm64.go
- pkg/nodeps/mariadb_values_linux_arm64.go
- pkg/nodeps/php_values.go
- pkg/versionconstants/versionconstants.go
Bump default PHP/MariaDB versions, add Maria 10.8
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4012"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump default php to 8.0, MariaDB to 10.4, add Maria 10.8

- pkg/nodeps/mariadb_values_darwin_arm64.go
* https://github.com/drud/ddev/pull/4012 introduced a bug/typo, for arm64 macOS only, that didn't use mariadb 10.8, but instead 18.0. This didn't get caught because on arm64 we don't have a complete set of GOTEST_SHORT tests.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4031"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix typo in mariadb values for 10.8 arm64

- pkg/ddevapp/config.go
While importing a database a temporary folder is created. This folder is not part of the DDEV's .gitignore and may lead of crashing git tools on very big imports.
The temporary folder is now added to the .gitignore and should avoid any issues during the import.
- start a project
- check if `/.importdb*` is added to the `.ddev/.gitignore` file
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Properly ignore temporary .importdb* folder

- .github/workflows/master-build.yml
- .goreleaser.yml
- docs/content/developers/release-management.md
- `.gotmp` was accidentially added to the tarballs
- arm64 is not applicable for Windows
- Fury account is hardcoded
- completion scripts are missing in the release
- conflict with `mkcert` package on Debian 12 and Ubuntu 22 - #4021 
This patch addresses the above mentioned issues and solves them properly.
The replace of mkcert is a temporary solution and should be removed and replaced by a conflict once the mkcert package is available in stable releases.
A test release can be found at https://github.com/gilbertsoft/ddev/releases/tag/v1.19.6-alpha.2.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4027"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve release with goreleaser cleanups, fixes #4021

- pkg/ddevapp/ddevapp.go
* @joelpittet discovered in https://discord.com/channels/664580571770388500/999439336267333743 that `composer_root` was ending up relative to the `working_dir` instead of relative to the project root, as described in the docs.
* Only Drupal6 and Drupal7 have a default `working_dir` that is not the project root, so this hadn't seemed to affect anybody, and composer is not commonly used on Drupal7.
* The work to add composer_root was done in https://github.com/drud/ddev/pull/3654
Make the composer_root relative to project root, not to working_dir
No changes
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4038"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> GetComposerRoot uses relative path to working_dir, should be approot

- docs/content/developers/building-contributing.md
- docs/content/users/basics/faq.md
- docs/content/users/install/ddev-installation.md
The current instructions on how to use the installer script all relay on downloading the script which can make troubles in case of changes in the master which then are ignored locally.
The new instruction directly passes the script to bash via pipe and avoids issues with deprecated and incompatible locally saved scripts.
Follow the instructions changed by this PR to check if it works.
None
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4023"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Directly run installer script

- pkg/ddevapp/global_dotddev_assets/commands/web/craft
Running Craft CMS commands requires one of the following syntaxes, which is fine but somewhat verbose.
```shell
ddev exec php craft
ddev exec ./craft
```
This PR adds a new `craft` convenience command so that running the command is less verbose.
```shell
ddev craft
```
Running `ddev craft` should show the help text for `craft`.
This is a small step in getting better support for Craft CMS in DDEV. I have added it for the `php` project type, which may be too broad. It is my hope that @pixelandtonic team will consider submitting (or perhaps are already working on) a complete Craft CMS project type for DDEV in due course.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4040"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Custom command for Craft CMS "craft" utility

- pkg/ddevapp/global_dotddev_assets/commands/web/magento
People sometimes have the magento command not executable and then they get an error from `ddev magento`
Prompt them about this possibility
See discord conversation, https://discord.com/channels/664580571770388500/1001062475065724989
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Give more error info on bin/magento failure

- cmd/ddev/cmd/composer-create.go
If `ddev composer create-project` is called with an option the message about the usage of `ddev composer create` instead is not shown but an error about an unknown option.
The issue poped up in this DDEV Discord thread https://discord.com/channels/664580571770388500/999382823033118801.
This PR enforces to skip the option validation and shows the correct message in any case.
Run e.g. `ddev composer create-project -s centarro/commerce-kickstart-project kickstart` which will show the correct message about the correct usage with `ddev composer create` now.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4033"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Skip option validation for composer create-project

- docs/content/developers/styleguide.md
Update the link to https://github.com/drud/ddev/tree/master/docs/content/developers/logos
N/A
Fixes #4034 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4048"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Updating the link to the logos, fixes #4034

- docs/content/users/extend/additional-services.md
Replaces the relative link with a direct link to https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
Check the link works in the ["Additional Service Configurations and Add-ons for ddev"](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/) page,
Section ["Template action replacements (advanced)"](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#template-action-replacements-advanced),
the link to "advanced test example".
fixes #4044 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4050"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix broken link, fixes #4044

- pkg/ddevapp/app_compose_template.yaml
* #4032
Add the suggested env var inside container
```js
const getScript = (url) => {
return new Promise((resolve, reject) => {
const http      = require('http'),
https     = require('https');
let client = http;
if (url.toString().indexOf("https") === 0) {
client = https;
}
client.get(url, (resp) => {
let data = '';
// A chunk of data has been recieved.
resp.on('data', (chunk) => {
data += chunk;
});
// The whole response has been received. Print out the result.
resp.on('end', () => {
resolve(data);
});
}).on("error", (err) => {
reject(err);
});
});
};
(async (url) => {
console.log(await getScript(url));
})('https://d9.ddev.site/');
```
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4049"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add NODE_EXTRA_CA_CERTS to web container, fixes #4032

- pkg/globalconfig/global_config.go
Current version of docker-compose is 2.7.0
Bump it and see if it works.
If it passes automated tests it's probably fine.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4052"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump docker-compose to 2.7.0

- cmd/ddev/cmd/get.go
If you use `ddev get <something>` with a stopped project, it can confuse mutagen by making changes when it's not running, and then reconciliation can do strange things when you start.
Start the project before getting/changing files.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4054"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev get <item> should run with project running, to avoid mutagen problems

- cmd/ddev/cmd/debug-capabilities.go
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/nodejs_test.go
- pkg/versionconstants/versionconstants.go
* Although we've been caching composer forever, yarn and npm caches were not persisted.
* $USER environment variable wasn't in containers
* #3666 ddev delete needs to clean up ddev-global-config when it runs
Do those things
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4051"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Persist yarn and npm caches, clean up ddev-global-config on delete, add $USER  to web env, fixes #3666

- pkg/globalconfig/global_config.go
Bump docker-compose again to 2.9.0 since they released that (#4056)
Use automated tests to verify. They say they introduced a breaking change in 2.8.0.
https://github.com/docker/compose/releases/tag/v2.9.0
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4062"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump docker-compose again to 2.9.0 since they released that (#4056)

- docs/content/users/install/performance.md
- pkg/ddevapp/templates.go
Using mutagen with TYPO3 and secured-web results in an issue where composer cannot create a symlink for fileadmin under public/
Setting the ddev "upload_dir" to `../private/fileadmin` prevent the creation of a docker volume (type: bind), see: .ddev-docker-compose-full.yaml.
The right directory here is the one under "private/"
https://github.com/mutagen-io/mutagen/issues/359
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4061"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Mention use of upload_dir for TYPO3 projects with nonstandard fileadmin

- .spellcheckwordlist.txt
- cmd/ddev/cmd/debug-capabilities.go
- cmd/ddev/cmd/describe.go
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/conf.d/supervisor.conf
- containers/ddev-webserver/ddev-webserver-prod-files/etc/supervisor/conf.d/supervisor.conf
- docs/content/users/extend/additional-services.md
- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/extra_expose_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/router.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/utils.go
- pkg/versionconstants/versionconstants.go
* #3456 
* Fix difficulty of using docker-compose.*.yaml to start daemons
* Explicit proxying
Try out all the things in the doc
Added TestExtraPortExpose
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4057"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow proxying arbitrary ports and starting daemons, more explicit nodejs support, fixes #3456

- docs/content/users/install/docker-installation.md
Removing trailing quote in the documentation - matching the other headings in this file
Originally viewed at https://ddev.readthedocs.io/en/latest/users/install/docker-installation/
Cosmetic issue with a trailing quote character
This removes the trailing character
Not aware of any testing process
No automated testing for documentation typos?
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4064"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix typo in docker-installation.md

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
v1.20.0 is in preparation.
Bump the images for it. They have been pushed.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4067"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images for v1.20.0

- pkg/ddevapp/router.go
HTTP_EXPOSE with a single value is legitimate, and is used in ddev-redis-commander.
Regression was introduced in https://github.com/drud/ddev/pull/4057 where that situation was not properly handled and thus an empty string was added into the array of ports to expose.
As a result, HEAD was failing on the ddev-redis-commander tests
* Handle the single-value properly
* Check for empty and otherwise non-numeric values in HTTP*_EXPOSE
Try ddev-redis with ddev-redis-commander
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4065"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Regresssion: Handle single port in HTTP_EXPOSE or HTTPS_EXPOSE in determineRouterPorts()

- .github/workflows/master-build.yml
- .goreleaser.yml
- docs/content/developers/release-management.md
- pkg/dockerutil/dockerutils_test.go
* It's really hard to safely test release generation.
* TestContainerWait fails all the time on colima. Why bother.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4070"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [releases only] Make testing releases on a fork easier

- pkg/ddevapp/templates.go
The config.yaml docs for web_extra_daemons got left out.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4072"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add config.yaml comments for web_extra_daemons

- docs/content/assets/temp-fix-header-links-in-tabs.js
- mkdocs.yml
This PR fixes part of [this issue](https://github.com/drud/ddev/issues/4059) by triggering the `fixTabs` function on page load and on hash change.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4069"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Use [this link](https://ddev--4069.org.readthedocs.build/en/latest/users/install/ddev-installation/#linux) to test, you'll notice the page automatically opening the Linux tab.
> Fix issue where the script doesn't fire on page load or search.

- .spellcheckwordlist.txt
- docs/content/users/install/docker-installation.md
- docs/content/users/providers/pantheon.md
- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
[Unable to pull db from pantheon after switching to colima](https://github.com/drud/ddev/issues/4035)
Add steps to docs regarding setting a DNS Nameserver IP address in Colima configuration
No tests included, only docs have been updated.
[Unable to pull db from pantheon after switching to colima](https://github.com/drud/ddev/issues/4035)
No anticipated deployment steps.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4076"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update Pantheon and Colima docs - Add step to set DNS Nameserver IP address 

- pkg/nodeps/values.go
Remove from nodejs_versions "12" and "17" as both are out of support.
Both can still be used via `ddev nvm`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4073"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove nodejs 12 and 17 from allowed values as out of support

- docs/content/users/quickstart.md
Tab indentation was wrong.
Please click [here](https://ddev--4084.org.readthedocs.build/en/4084/users/quickstart/#drupal)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4084"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [DOCS] Fix tabs for drupal section on the quickstart page

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
As a developer I want to execute scripts in the container. Sometimes it's good to know which ddev version is currently used to have a different logic or to warn that some features require an ddev update.
Register a new DDEV_VERSION variable in the container.
Start a new project and run `echo $DDEV_VERSION`. It should print the currently used ddev version as string.
For stable versions it's a tag like `v1.20.0`.
Test was added to `pkg/ddevapp/ddevapp_test.go`.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4080"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Provide DDEV_VERSION env variable in container

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
* https://github.com/docker/compose/issues/9732
If the db container exits, for example because the db type has been changed and the existing database is incompatible with the new one, the `docker-compose up` hangs forever without any information. Unfortunately we can't let docker-compose do the work for us as we had anticipated in #3858.
* Remove the docker-compose depends_on
* Add inline code to check db container
Note that DDEV v1.20 web_extra_daemons already waits for these things (now), so the original problem described in #3702 should be resolved *if* it uses web_extra_daemons, which would be great.
* https://github.com/drud/ddev/issues/3702
* https://github.com/drud/ddev/pull/3858
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4095"><img …
> Don't use docker-compose to wait for db container to become healthy
