ddev/ddev

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- pkg/versionconstants/versionconstants.go
* #4088 
Try both yarn cachedir setting techniques; just give up if they don't work
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4090"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make yarn cachedir setting dependent on version, fixes #4088

- .github/workflows/golangci-lint.yml
Trying to fix crashes of golangci-lint, https://github.com/drud/ddev/runs/7755098131?check_suite_focus=true
It seems to be the fault of gocritic, 
A variety of issues including 
* https://github.com/golangci/golangci-lint-action/issues/545
May be affected by using go 1.19, so that's probably the fix, lock to 1.18
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4101"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Try to fix golangci-lint crash with update

- docs/content/users/install/performance.md
There was a typo in the code highlighting on the performance page within the docs
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4097"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix code highlighting in docs performance page

- .github/workflows/macos-colima-setup.sh
- pkg/dockerutil/dockerutils_test.go
Colima tests fail oh-so-often on github actions test runner, macOS.
* Make sure jq is in the test runner
* Give better output if containerwait fails
* Wait 60 seconds instead of 30.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4111"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Try to sort out colima test failures in startup

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/debug-capabilities.go
- cmd/ddev/cmd/debug-check-db-match.go
- cmd/ddev/cmd/debug-get-volume-db-version.go
- cmd/ddev/cmd/debug-migrate-database.go
- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/root.go
- docs/content/users/extend/database_types.md
- pkg/ddevapp/config.go
- pkg/ddevapp/db.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
* #4089 
* #3923 
It's not a common occurrence, but people are really frustrated when they configure a database and then can't start it. 
* Check on start to see if the existing database matches the configuration
* Check on DB config change to see if the existing database matches the configuration
* `ddev debug check-db-match` checks to see if they match
* `ddev debug get-volume-db-version` gets the existing in-container in-volume value
* `ddev debug migrate-database` will attempt a database migration
* TestDdevAllDatabases has additional coverage.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Check database type, allow migration, fixes #4089, fixes #3923

- docs/content/users/providers/platform.md
- Split one time config (cli_token) from per project config
- Improve formating (using double spaces) so that both mkdocs and github print new bullets on a new line
https://ddev.readthedocs.io/en/latest/users/providers/platform/ is a bit hard to follow because of poorly rendered markdown list and the fact that global configuration is mixed with per-project config
This MR separates one time config and improves lists
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4106"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update platform integration documentation

- cmd/ddev/cmd/homeadditions_test.go
TestHomeadditions is failing on Windows NFS, see https://buildkite.com/drud/ddev-windows-dockerforwindows-nfs/builds/5765#018287cd-8a45-4bf9-a816-ef4b0aa0eb47
Try to get more information about why it's failing. I haven't been able to recreate on local Windows machine.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4104"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Attempt to chase Windows NFS homeadditions failure

- pkg/versionconstants/versionconstants.go
Mutagen has 0.15.1
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4121"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump mutagen to 0.15.1

- docs/content/assets/extra.css
- mkdocs.yml
The readability within the new docs should be improved;
1. The light-blue theme has a very low contrast ratio which results in poor accessibility
2. The line length within the docs is too long, which makes text harder to read and understand.
3. Heading margin feels off, the content related to the heading is too far away.
4. Heading styling should stand out more, this in terms helps with navigation throughout the page.
5. Blockquotes should stand out more, they usually contain important information the user has to read. Currently it can easily be overlooked,
1. The light-blue theme has been replaced with indigo, as the contrast between backgrounds and text is better.
2. The max width for `div.md-content` has been reduced by almost 300px.
3. All heading margins have been reduced and are now …
> [docs] Improve doc readability by changing the theme and style

- pkg/ddevapp/global_dotddev_assets/commands/web/blackfire
Blindly using and running that command deleted my platform.sh CLI token and I had to generate a new one.
Add the env variables instead of replacing everything
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4130"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use --web-environment-add instead of --web-environment in blackfire error

- cmd/ddev/cmd/root.go
- pkg/globalconfig/global_config.go
* #4131
* https://github.com/php-perfect/ddev-intellij-plugin/issues/83#issuecomment-1218700136
* Only do IsInternetActive on start/restart
* Only test `test.ddev.site` (and always use that instead of a random url)
export DDEV_DEBUG=true
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4134"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Do IsInternetActive() less often, and do it more efficiently, fixes #4131

- cmd/ddev/cmd/scripts/test_ddev.sh
The message `Success accessing database... db via TCP/IP ddev is working. You will want to delete this project with 'ddev delete -Oy tryddevproject-15988` misses a single `'`.
The quote is added
Use `ddev debug test` and see response
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4140"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [TASK] Add missing quote in test_ddev.sh

- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
- pkg/ddevapp/list.go
- pkg/ddevapp/list_test.go
- pkg/ddevapp/utils.go
If I run `ddev list` in most of the cases the text is wrapped.
That's because the text of the path and the URL in the table is to long for my terminal window.
In most of the cases a user want to get an overview about the existing projects and the current status of
them.
Example screenshot:
The size of the *type* column was increased to prevent a wrap of longer project types than "drupal7". The project types "wordpress" and "magento2" are not wrapped anymore with this PR.
I moved the *status* column from the end of the table right after the name.
If the terminal width is not enough the text will now be truncated.
Screenshot:
For users who want to have the previous behavior the flag `-W` was added to force the old text wrapping.
Run `ddev list` and change terminal window size.
It's a …
> ddev list: Truncate app list table text to avoid wrapping

- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/debug-download-images_test.go
- cmd/ddev/cmd/homeadditions_test.go
- cmd/ddev/cmd/list_test.go
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/hooks_test.go
- pkg/ddevapp/router_test.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/dockerutil/docker_compose_version_test.go
- pkg/dockerutil/dockerutils_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
Reference: https://pkg.go.dev/testing#T.Setenv
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4126"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> test: use `T.Setenv` to set env vars in tests

- pkg/ddevapp/config.go
In the past a file named .ddev/providers/platform.yaml.example was provided, but it's no longer needed, as edits to the file are no longer required.
Remove the old example file.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4141"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> On upgrade ,remove old provider/platform.yaml.example [skip ci]

- pkg/ddevapp/config.go
After platform.yaml.example has been removed, it still was warning about not finding it.
Don't bother.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4145"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't show warning when removing platform.yaml.example [skip ci]

- .circleci/config.yml
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/docker_compose_version_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
* #4135 
As of v1.21.1, docker-compose v1 is not allowed, but the docker-compose version constraint was not updated
Update the version constraint, check it on start, and explain what to do about it.
See explanatory error message. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4142"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set version constraint for docker-compose to current, fixes #4135

- pkg/globalconfig/global_config.go
docker-compose v2.10.1 has been released. See if it passes tests.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4143"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump required docker-compose to 2.10.1

- containers/ddev-webserver/Dockerfile
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/versionconstants/versionconstants.go
Random ContainerWait() fails on colima expecially
* Increase timeout in one place
* Improve wording of output message
* Distinguish between two similar failures
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4144"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [ tests only] Solve colima ContainerWait failure

- containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/versionconstants/versionconstants.go
* #4060 
When people have their composer_root set to non-default, the $PATH in the web container doesn't point to their vendor/bin
Add <composer_root>/vendor/bin to $PATH
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4147"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure vendor/bin is in PATH even if composer_root is different, fixes #4060

- .spellcheckwordlist.txt
- cmd/ddev/cmd/a.go
- cmd/ddev/cmd/clean.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/debug-fixcommands.go
- cmd/ddev/cmd/debug-mutagen.go
- cmd/ddev/cmd/debug-nfsmount.go
- cmd/ddev/cmd/debug.go
- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/mutagen-reset.go
- cmd/ddev/cmd/mutagen-status.go
- cmd/ddev/cmd/root_test.go
- docs/content/users/basics/cli-usage.md
- docs/content/users/install/ddev-installation.md
- docs/content/users/install/performance.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/mutagen_config_assets/mutagen.yml
- pkg/ddevapp/mutagen_test.go
- pkg/ddevapp/poweroff.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/globalconfig/global_config.go
- scripts/diagnose_mutagen.sh
@xenoscopic, maintainer of mutagen, suggests that we can have a more successful mutagen lifecycle by using the container name for beta identifier instead of using the container id. This is a first test of that. I originally did it that way, but switched to ID for some reason. 
When the container name is used, we can *pause* the mutagen session instead of terminating it, and it will do better with a number of things. That's not here yet, but if things work out in automated tests it has potential.
* Use new json output of `mutagen` commands, especially `mutagen sync list`
* Use labels on sync sessions and docker volumes and verify that they match
* Use pause and resume instead of creating sync sessions from scratch
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4109"><img …
> Mutagen rework to use volume label and session label

- cmd/ddev/cmd/debug-compose-config_test.go
- cmd/ddev/cmd/testdata/TestCmdGet/example-repo/docker-compose.example.yaml
- docs/content/users/basics/faq.md
- docs/content/users/extend/custom-compose-files.md
- docs/content/users/install/performance.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/router.go
- pkg/ddevapp/router_compose_template.yaml
- pkg/ddevapp/ssh_auth.go
- pkg/ddevapp/ssh_auth_compose_template.yaml
- pkg/ddevapp/testdata/TestDdevExec/docker-compose.busybox.yaml
- pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.override.yaml
- pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.z1.yaml
- pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.z2.yaml
- pkg/ddevapp/testdata/TestNetworkAmbiguity/docker-compose.test.yaml
- pkg/ddevapp/testdata/TestRouterConfigOverride/router-compose.override.yaml
- pkg/ddevapp/testdata/TestSSHAuth/.ddev/docker-compose.sshserver.yaml
- pkg/ddevapp/testdata/TestSshAuthConfigOverride/ssh-auth-compose.override.yaml
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/testdata/TestComposeWithStreams/test-compose-with-streams.yaml
- pkg/dockerutil/testdata/docker-compose.override.yml
- pkg/dockerutil/testdata/docker-compose.yml
* #3214 
docker-compose no longer requires `version: 3.6` (or anything like it)
DDEV now maintains its own private docker-compose, so we have a working verison.
Remove usages of `version: 3.6`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4151"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove requirement of docker-compose version 3.6 in docker-compose.*.yaml, for #3214

- cmd/ddev/cmd/clean.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/poweroff.go
* Need to terminate session if we find a non-matching sync
* Need to stop mutagen daemon on poweroff
* Remove one util.Warning() that doesn't need to be there.
Use 
`MUTAGEN_DATA_DIRECTORY=~/.ddev_mutagen_data_directory ~/.ddev/bin/mutagen sync list -l` 
to see what's running after you've done lots of things.
You can also
```
export MUTAGEN_DATA_DIRECTORY=~/.ddev_mutagen_data_directory
export PATH=$PATH:~/.ddev/bin
mutagen sync list -l
```
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4153"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Mutagen followup: Make sure mutagen sync sessions are terminated

- docs/content/users/install/docker-installation.md
[docs] Make sure to disable Docker Desktop integration before installing wsl2 docker-ce
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4155"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Make sure to disable Docker Desktop integration before installing wsl2 docker-ce

- docs/content/users/topics/phpstorm.md
For full PhpStorm integration, people need a recent docker-compose v2, preferably the private one provided by DDEV.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Mention need to configure docker-compose for PhpStorm

- cmd/ddev/cmd/debug-dockercheck.go
- cmd/ddev/cmd/scripts/test_ddev.sh
* test_ddev.sh had a syntax error from previous editing
* Clean up mutagen as it can be simpler now, and doesn't have to warn about other mutagen instances
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4164"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix up test_ddev.sh [skip ci]

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/root.go
- pkg/ddevapp/mutagen.go
* #4162 
* #4163 
Fix things.
Also changes the wording when creating an unrecognized project
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4165"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't flush mutagen if project not running, fixes #4162, fixes #4163

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
When people have mutagen turned on, it's really far better to have upload_dir. Some folks who use the 'php' project type especially don't have that set, and it causes slower startup time and disk duplication.
Warn on `ddev start` in this situation.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4173"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Ask people about upload_dir when mutagen is set

- .ci-scripts/bump_homebrew.sh
ZSH completion doesn't work if DDEV was installed by Homebrew. It happens because a completion file has a wrong name: `ddev` instead of `_ddev`.
The file was renamed to `_ddev`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4179"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Homebrew] Fix zsh completion file name

- docs/content/users/install/ddev-installation.md
Extra back-tick in installation doc show up on copy/paste.
Removes the back-tick from snippets.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Docs] Remove extra back-tick from snippets (and trailing whitespace).

- .spellcheckwordlist.txt
- CODE_OF_CONDUCT.md
- docs/content/users/code-of-conduct.md
- mkdocs.yml
ddev does not have a documented code of conduct.
This adds the Contributor Covenant, as discussed in #4159.
Here's a screenshot from the PR. I made a first guess as to where to put this in the navigation:
None added or needed.
https://github.com/drud/ddev/issues/4159
Docs only update!
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4186"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add an initial code of conduct #4159

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Made some pedantic edits to improve brevity and add links to common jumping-off points:
- Curly punctuation (`'` → `’`) because it’s okay to have nice things.
- Link for “search existing issues” to make it more convenient and actionable.
- Reduced verbosity of diagnostic step instruction. ~~(Would be good to link to a “troubleshooting your project” guide here so there isn’t a dead end if the diagnostic is healthy—not sure if such a document exists.)~~
- Swapped order of bug report’s actual and expected result, assuming that helps better frame problems.
- Made several minor edits for brevity.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve issue templates

- docs/content/users/quickstart.md
Linked sample data is for older Magento 1 versions. Better use latest version.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4196"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Updated link to Magento 1/OpenMage sample data

- pkg/ddevapp/mutagen_config_assets/mutagen.yml
Fixes 
* #4193
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4194"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow .ddev/.downloads in web container for pull providers, fixes #4193

- pkg/ddevapp/providerPantheon_test.go
Every 3 months the pantheon repo gets frozen due to lack of commits.
So commit on the 9th of the month when TestPantheonPull gets run.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4201"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Make TestPantheonPull do commits monthly

- pkg/ddevapp/global_dotddev_assets/commands/web/craft
Once https://github.com/drud/ddev/pull/4176 is merged, existing Craft projects that have the project type set to `php` will no longer have the `craft` command available to them and will output an error.
This PR maintains the `craft` command in the `php` project type, but prompts users to switch to the `craftcms` project type in order to use it, easing the transition for existing users who update DDEV without reading the release notes.
This is primarily to aid in transitioning and the `craft` command could be dropped for`php` project types in the next minor version, if desirable.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add `craft` command transition

- .buildkite/test.cmd
- .buildkite/test.sh
- cmd/ddev/cmd/debug-mutagen.go
- cmd/ddev/cmd/stop.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- pkg/versionconstants/versionconstants.go
* non-utf8 filenames aren't handled well in lots of places, but Mutagen in this version can at least detect and report the problem.
* On traditional Windows, mutagen doesn't know what permissions to use with directories and files, so with this version of mutagen that can be forced to 777 as Docker Desktop also does.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump mutagen (v0.16.0-beta1) and set it to use windows 777 permissions

- .github/workflows/container-tests.yml
- .github/workflows/linux-setup.sh
- cmd/ddev/cmd/xdebug_test.go
- containers/ddev-php-base/Dockerfile
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/apache2/php.ini
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/cli/php.ini
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/php-fpm.conf
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/php.ini
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/pool.d/www.conf
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/mods-available/xdebug.ini
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/conf-available/php8.2-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/mods-available/php8.2.conf
- containers/ddev-webserver/tests/ddev-webserver/custom_config.bats
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- containers/ddev-webserver/tests/ddev-webserver/test.sh
- pkg/ddevapp/ddevapp_test.go
- pkg/nodeps/php_values.go
- pkg/versionconstants/versionconstants.go
PHP 8.2 is near release
* Add PHP 8.2 as an option.
* Set PHP 8.0 as the default PHP version when this is run without DDEV context.
* These extensions are not available in the repo yet: "apcu imagick memcached redis uploadprogress xdebug xhprof xmlrpc" so xdebug is not available.
`ddev config --php-version=8.2`
I think the tests that need to will pick this up.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support PHP 8.2 in DDEV

- cmd/ddev/cmd/root.go
I wasn't quite happy with the state of the messaging on starting up with a new version.
Redo it a bit:
```
$ ddev start
You seem to have a new DDEV version.
During an upgrade it's important to `ddev poweroff`.
May I do `ddev poweroff` before continuing?
This does no harm and loses no data. [Y/n] (yes):
```
Do a `ddev start` with new version. Or fiddle with the version in global config.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4232"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Clean up messaging on new ddev version

- cmd/ddev/cmd/mutagen-logs.go
- pkg/ddevapp/mutagen.go
@rpkoller points out that `ddev mutagen logs` in the context of a stopped app can cause some confusion. And we don't need an app running for this. 
Just do a mutagen daemon start at the end, not start a sync.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev mutagen logs should just restart daemon, not sync

- cmd/ddev/cmd/scripts/test_ddev.sh
If test_ddev.sh fails to create its project dir, it can continue out and alter the original project.
Don't do that.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4239"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix test_ddev.sh so it doesn't continue if unable to create test dir [skip ci]

- cmd/ddev/cmd/start.go
I noted on some types of start failure, the project was being stopped, which means you can't then examine any of the logs, etc.
This change was made recently in
* #4156
Instead of stopping the project in this situation, let it be, and just make sure the mutagen session is stopped, which I think must have been the intent in #4156 
```yaml
hooks:
post-start:
- exec: ls kdkdd
```
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't stop project on start failure

- .spellcheckwordlist.txt
- docs/content/users/quickstart.md
These changes can be found under the Laravel section in the quickstart for CMSes page.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4236"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Expanded the Laravel quickstart with instructions on how to run Vite

- pkg/ddevapp/db.go
- pkg/ddevapp/db_test.go
* #4229 
Properly handle existing postgres "9.x" as `postgres:9`
`ddev start` and empty postgres:9 and then `ddev restart`
Added the 9.6 expectation to tests.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix postgres:9 detection of existing project, fixes #4229

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- pkg/ddevapp/app_compose_template.yaml
- pkg/versionconstants/versionconstants.go
* #4215 
This is also related to the previous yarn v3 fix, 
* #4090 
* #4088 
More subtle approach to cache for yarn:
* For yarn v1, the global config is set by running yarn config outside the project directory
* For yarn v2/3+ the global config is there if wanted, but not used by default.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Rework yarn and npm cache dirs, fixes #4215

- docs/content/developers/release-management.md
On my local markdownlint, this fragment seems to be wrong somehow, just fixing here. It doesn't seem to be caught by the markdownlint in the docs checker on github actions.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4260"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix linter fragment complaint

- docs/content/users/extend/additional-services.md
After #4200 and subsequent updates to some GitHub repository descriptions, the `ddev get --list` example is stale.
This fixes that situation, in a refreshingly small PR. Also cheats by fixing an “addon” that should be “add-on”, and capitalizing Memcached which, against all odds, [appears to be](https://www.memcached.org) a proper noun for the product.
https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-your-changes
Only Markdown; no new tests needed.
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4263"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update example service list

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Bump images, see what happens.
Check carefully:
* https://github.com/drud/ddev/issues/3748
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images to v1.21.2 for upcoming release

- docs/content/developers/testing-docs.md
The enthusiastic writer may not be aware of the spell checker, which would be ideal for the [Working on the Docs](https://ddev.readthedocs.io/en/latest/developers/testing-docs/) page.
This adds a “Check for Spelling Errors” section to that page:
Terminal commands are grabbed directly [from the Makefile](https://github.com/drud/ddev/blob/master/Makefile), and the `→  ` is used to indicate user CLI input since that style is used elsewhere in the docs.
https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-your-changes
Only Markdown; no new tests needed.
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add spell check instructions

- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/templates.go
Post-start hook is wrongly stated on two places, fixed that.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4265"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use proper post-start hook label everywhere

- docs/content/users/install/ddev-installation.md
[docs] Fix incorrect statement about where homebrew can be used
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix incorrect statement about where homebrew can be used

- docs/content/users/install/docker-installation.md
When trying to copy all the commands and paste them in terminal of Ubuntu so they all run at once, the `-y` is missing.
Adding `-y` to auto-confirm installing Ubuntu packages.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4275"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] auto-install recommended packages

- .spellcheckwordlist.txt
- docs/content/users/basics/developer-tools.md
- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
```
mkdir my-drupal9-site
cd my-drupal9-site
ddev config --project-type=drupal9 --docroot=web --create-docroot
ddev start
ddev composer create "drupal/recommended-project" --no-install
ddev composer require drush/drush --no-install
ddev composer require drupal/symfony_mailer --no-install
ddev composer install
ddev drush site:install -y
ddev drush pm:install symfony_mailer
ddev drush user:login "admin/config/system/mailer/test"
```
Use the login link to go to the page send a test mail.
Verify mailhog recieves the test mail.
#2706 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4214"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add Symfony Mailer config for Mailhog in Drupal 9 settings #2706

- .spellcheckwordlist.txt
- docs/content/developers/brand-guide.md
- docs/content/developers/testing-docs.md
- docs/content/developers/writing-style-guide.md
- docs/content/users/extend/additional-services.md
- mkdocs.yml
While there are tools in place for linting and spell-checking the documentation, there aren’t any higher-level guidelines that clarify how it should be written. Without a clear standard, the organization and flow of the documentation is limited to the efforts and perspectives of individual contributors.
This PR renames the “Styleguide” page to “Brand Guide”—which should be a more specific and appropriate description of that content—and adds a “Writing Style Guide” to comprehensively detail objectives from #4200 with some additional considerations for the broader effort of #4188 and a reference to the related aims of the [Code of Conduct](https://ddev.readthedocs.io/en/latest/users/code-of-conduct/).
It adds some initial examples that could probably be improved or grown to clearly …
> [docs] Add writing style guide

- docs/content/users/install/docker-installation.md
The current command listed in ddev docs results in error.
Tested on Windows 11 Pro - this PR uses the new command
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] fix command for installing Ubuntu 20.04 on WSL2

- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
The problem where a docker volume can't be removed may be caused by the web container still being running and preventing deletion, so the simplest fix in that case is `ddev restart`. 
Add that to the output.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Offer ddev restart option for failure to remove volume

- docs/content/users/quickstart.md
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/typo3.go
The new TYPO3 v12 major version has some breaking changes regarding the settings files.
This patch introduces an automatic detection of the TYPO3 version 12 or higher and properly adapts the setting file paths and names.
To avoid the creation of the .gitignore in the wrong location, it is not written anymore before TYPO3 is installed or the version could be properly detected.
Follow the quick start guide to test this change. To test it for a previous version just add a version to the composer create command e.g.:
```
ddev composer create --no-install "typo3/cms-base-distribution:^11"
```
https://github.com/TYPO3/get.typo3.org/issues/386
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4268"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add support for TYPO3 v12

- pkg/versionconstants/versionconstants.go
Mutagen 0.16.0-rc1 has been released; 0.16.0 should come shortly
Use and run full tests on it. @xenoscopic doesn't foresee any impact from the beta1 we were using.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4277"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump mutagen to 0.16.0-rc1

- .buildkite/test.sh
- cmd/ddev/cmd/snapshot_restore_test.go
- pkg/ddevapp/mutagen.go
- pkg/dockerutil/dockerutils.go
* #4285 
Shorten the label used by removing the homedir and changing the time label
Try it out, `docker volume inspect <project>_project_mutagen` should show the shorter label. In my case it's 33 characters.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4289"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Shorten the descriptor used for docker/mutagen label, fixes #4285

- docs/content/users/extend/custom-compose-files.md
Just a typo at the docs.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4295"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix simple typo

- .spellcheckwordlist.txt
- docs/content/developers/github-selfhosted-setup.md
- docs/content/index.md
- docs/content/users/support.md
- docs/content/users/topics/cms_specific_help.md
- docs/content/users/topics/webserver.md
- docs/content/users/topics/whats_in_ddev_dir.md
- mkdocs.yml
As demonstrated by the changes in #4293, the combined section and on-page sidebar navigation can get _in the way_ of browsing a section or page—which is its sole purpose:
The problem isn’t just limited to suggested FAQ page revisions, though. The same imbalance is demonstrated on the [Extending and Customizing Environments](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/) page:
This PR makes a few changes to the theme configuration to balance things out and make the navigation more useful for browsing:
1. Separates the on-page table of contents from section navigation by disabling [`navigation.integrate`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=instant#navigation-integration). This makes it easier to focus on the flow of …
> [docs] Refine navigation setup

- docs/content/users/basics/faq.md
- docs/content/users/basics/how-ddev-works.md
The [current FAQ](https://ddev.readthedocs.io/en/stable/users/basics/faq/) is a bit sprawling, and it contains important information that can’t be linked to directly.
This shapes up the FAQ to be more readable and linkable in a few ways:
- Re-titles excessively-explanatory “Frequently-Asked Questions (FAQ)” simply to “FAQ”, while repurposing the phrase “frequently-asked questions” in introductory framing for the one person who searches that term or has never seen an FAQ.
- Gives a proper heading to each Q&A item, further organized categorically for easier browsing and more orderly maintenance.
- Pares down headings wherever possible for brevity and readability, with sense breaks added to text.
- Swaps in the word “workstation” in a few places, since we’re trying to use that more …
> [docs] Improve FAQ

- .spellcheckwordlist.txt
- cmd/ddev/cmd/get.go
- docs/content/users/extend/additional-services.md
1. `ddev get --list` returns its results in no particular order, requiring the user to read the whole list in search of something specific.
2. The bulleted list on the [Additional Service Configurations & Add-ons](https://ddev.readthedocs.io/en/stable/users/extend/additional-services/) page is incomplete and also randomly organized.
This PR updates the page in the docs and changes the existing sort (favoring `drud` only), so that results are alphabetized by project name.
This happens to group `drud/*` projects at the top, even though their accompanying asterisk `*` already identifies first-party add-ons regardless of where they appear in the table. (So arguably not a problem if `acme/ddev-foo` comes along.)
```
❯ ddev get --list
┌───────────────────────────┬──────────────────────────────── …
```
> Alphabetize `ddev get` services list

- docs/content/users/quickstart.md
This PR makes the following improvements to the Craft CMS instructions in the [CMS Quickstarts](https://ddev.readthedocs.io/en/stable/users/quickstart/) page:
- Swaps `composer install` for `composer update`, since the `craftcms/craft` project doesn't have a `composer.lock` file. (Avoids a Composer warning about the missing .lock file.)
- Swaps `ddev craft setup/welcome` for `ddev craft install`, taking advantage of a simplified install process with Craft CMS 4.2.7 + DDEV 1.21.2.
- Removes the `composer install` step from the “Manual download” instructions, since `latest-v4.zip` already has a fully-loaded `vendor/` folder.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4284"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve Craft CMS installation instructions

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Time for a release. Bump images.
This also bumps mutagen to 0.16.0, but there is no difference between the previous 0.16.0-rc1 and 0.16.0
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump images to v1.21.3 and mutagen to 0.16.0

- .gitpod.yml
- .gitpod/images/Dockerfile
New version means bumping .gitpod.yml
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4311"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump .gitpod.yml to new image [skip ci]

- docs/content/developers/release-management.md
docs fix removing broken chocolatey deploy instructions.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4316"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove inappropriate link from chocolatey deploy

- docs/content/developers/release-management.md
The Chocolatey manual push instructions left off the need to set GITHUB_REPOSITORY_OWNER=drud 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4321"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] fix manual chocolatey push instructions

- cmd/ddev/cmd/scripts/test_ddev.sh
A user showed an unusual `ddev debug test` that had apache output, but no header to show where the info was coming from.
We need to show `curl -I` and also `curl` output (from outside container).
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4333"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve test_ddev.sh curl to show what it's doing [skip ci]

- pkg/ddevapp/app_compose_template.yaml
On GITPOD, ddev in combination with posgress DB was not working correct. 
`ddev import-db --src=sql/db.sql.gz` or `ddev export-db` 
throws an:
`  psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  no pg_hba.conf entry for host "::1", user "db", database "postgres", no encryption`
error.
We set the  PGHOST=localhost env in app_compose_template.yaml to PGHOST=127.0.0.1
- Create a ddev Container from scratch with:   `ddev config --project-type=drupal9 --docroot=web --database=postgres:14 --create-docroot`
- try to export the db with `ddev export-db`
https://discord.com/channels/664580571770388500/1034154179192696996
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix ddev import-db with postgres on gitpod by changing PGHOST=127.0.0.1

- pkg/ddevapp/typo3.go
If the `typo3` folder is a symlink to a non existing target the detection fails currently.
If the first check fails, an additional check for an existing symlink is introduced.
- Set up a TYPO3 according the [legacy installation](https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/LegacyInstallation.html)
- Rename the source folder extracted from the package
- Remove `AddintionalConfiguration.php`
The `AddintionalConfiguration.php` is not longer created during `ddev start` or `ddev restart`.
#4326 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix TYPO3 project detection to work with non existent symlinks, fixes #4326

- .gitpod/images/Dockerfile
- docs/content/users/install/ddev-installation.md
- docs/content/users/topics/phpstorm.md
To allow adding the key without a warning in recent Ubuntu versions, the variant using a key within /etc/apt/trusted.gpg.d/ is provided since `apt-key` is deprecated.
Usage of `apt-key` is deprecated
The suggestion of adding the keyring to the local trusted.gpg.d directory is explained
On an Ubuntu machine use the new instruction commands
* https://github.com/drud/ddev/issues/3997
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4324"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update process of adding the gpg key

- pkg/ddevapp/mutagen.go
Currently, `ddev poweroff` tries to stop an existing mutagen daemon running against the traditional/normal ~/.mutagen, which we don't use any more. 
This is probably a bit too intrusive, as that daemon may have reasonable non-DDEV versions for running. 
It also results in creation of ~/.mutagen, as discovered by @rpkoller (thanks!)
Just don't try. 
Remove ~/.mutagen, then `ddev start && ddev poweroff`, no mutagen daemons should be running, and ~/.mutagen should not exist.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4291"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't try to stop default mutagen daemon on `ddev poweroff`

- docs/content/users/quickstart.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/craftcms.go
- pkg/ddevapp/ddevapp_test.go
- pkg/testcommon/testcommon.go
* #4302 
* Related attempt and conversation in #4303
* Remove the wired upload_dir
* Remove the wired docroot (seems inappropriate? DDEV will autodetect, and people should be able to override?)
* Support specifying upload_dir in tests
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4317"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> upload_dir support in Craft CMS, fixes #4302

- .gitignore
One might easily and accidentally commit those annoying macOS `.DS_Store` files to their commit, adding cruft to the project.
This uses the `.gitignore` file to prevent those from being noticed or committed by Git.
🤔 Stage this change, then purposefully try to commit a file named `.DS_Store`. It’ll be trickier, at least.
n/a
Faintly related to #4188; came up during #4336.
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4337"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Gitignore `.DS_Store` and similar files

- pkg/ddevapp/drupal.go
On [Stack Overflow](https://stackoverflow.com/questions/74190777/error-when-creating-drupal-project-with-ddev-existing-settings-php-file-includ) a user thought that the general startup output from Drupal was error output. It would be better as debug output (when DDEV_DEBUG=true). Changing those to util.Debug().
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make ddev settings management less chatty for Drupal

- docs/content/users/quickstart.md
The original documentation related to changing where the `craft` executable is located in CraftCMS projects was slightly misleading as it implied you could make this change via an `.env` file.
This PR updates the docs to show how to provide this variable via DDEV's documented methods for providing environment variables to containers.
Set up a CraftCMS project where the Craft application lives in a subdirectory. Follow the docs to set the location of the `craft` executable. Restart your project and test that `ddev craft` works.
https://github.com/drud/ddev/issues/4309
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4314"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve Craft CMS Quickstart - how to add environment variables

- cmd/ddev/cmd/composer-create.go
- docs/content/users/quickstart.md
`composer create-project` executes a `git clone` which is possible only into empty directories. Therefor the `ddev composer create` command was introduced to automatically bypass this problem and make the initialization easier for the user. This is achieved by running the `composer create-project` command automatically providing the directory argument and rsync the the files and folders from this directory afterwards to the project root directory. This can be very slow depending on the number of files and folders which must be synchronized and therefor using the `--no-install` option is suggested in many places to avoid issues and make the process faster but requires the user to run `ddev composer install` afterwards, once the `ddev composer create` command has finished. This workflow can …
> Optimize composer create to also work without --no-install

- docs/content/users/quickstart.md
I must have made a mistake with a merge conflict, and `--no-install` remained in the Craft CMS quickstart
Remove it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4340"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Craft CMS quickstart should  not have --no-install, fixes #4338

- pkg/ddevapp/global_dotddev_assets/commands/host/launch
xd-open fails on gitpod environments. 
Check if we have a env with GITPOD_INSTANCE_ID and open the "gp previev" with FULLURL
Please consider that there is a other Issue in GITPOD with gp preview ( https://github.com/gitpod-io/gitpod/issues/7825 )
- Open a GITPOD, `ddev start` and test `ddev launch`  (in Vscode Browser edition be sure that popups are enabled :) )
- Test `ddev launch` with phpstorm EAP
- Test `ddev launch` on a linux environment **NOT** running gitpod to verify that xd-open still works
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4342"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make `ddev launch` work right on gitpod

- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
This resolves the issue of #4281 which requires MySQL tranaction isolation level setting.
Add the required line to 'mysql' driver configurations. 
- Note: I added it on a Drupal 10 Postgres system too which appeared to load correctly, but am unaware of any side affects under "normal" usage.
Comment out line in a Drupal 10 install and a warning appears on `/admin/reports/status`
Fixes #4281
[Setting the MySQL transaction isolation level](https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level)
[Suggestion for: (3285800) Setting the MySQL transaction isolation level](https://www.drupal.org/project/documentation/issues/3308909)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4339"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Setting the MySQL transaction isolation level (Fixes #4281)

- pkg/globalconfig/global_config.go
See if docker-compose v2.12.2 works with ddev
If it does, since docker-compose with 2.12.2 seems to handle proxies correctly, https://github.com/docker/compose/issues/9034 then we may be able to no longer use [drud/ddev-proxy-support](https://github.com/drud/ddev-proxy-support) as things may work with no intervention.
Use new version.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4350"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> See if docker-compose v2.12.2 works with ddev

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/drupal.go
* #4341 
* #3584 
* #3653 
Add the pg_trgm extension for Drupal9/10 if it's not already enabled. It only acts on the "db" database.
Install on Drupal 9/10, with database postgres, look for warnings.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4347"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add pg_trgm extension on postgres for Drupal9+, fixes #4341, fixes #3584, fixes #3653

- docs/content/users/topics/cms_specific_help.md
- pkg/ddevapp/drupal.go
- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
* #4281
* Previous totally-valid solution: https://github.com/drud/ddev/pull/4339
This is an alternate technique for setting Drupal transaction isolation level. I apologize for re-doing it @tyler36. 
Install and/or Bring up a variety of Drupal 9.4, 9.5, 10 sites and view admin/reports/status looking for the warning.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4351"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Round 2 for Drupal transaction isolation, fixes #4281

- docs/content/users/quickstart.md
Update QuickStart in the Laravel section
Adding example explain how to make Git Clone
```
git clone https://github.com/ibrah3m/laravel.git my-laravel-app
cd my-laravel-app
ddev config --project-type=laravel --docroot=public --create-docroot
ddev start
ddev composer install 
ddev exec "cat .env.example | sed  -E 's/DB_(HOST|DATABASE|USERNAME|PASSWORD)=(.*)/DB_\1=db/g' > .env"
ddev exec 'sed -i "s#APP_URL=.*#APP_URL=${DDEV_PRIMARY_URL}#g" .env'
ddev exec "php artisan key:generate"
ddev launch
```
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4320"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] QuickStart Laravel Git Clone 

- containers/ddev-dbserver/Dockerfile
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- docs/content/developers/buildkite-testmachine-setup.md
- pkg/ddevapp/config.go
- pkg/versionconstants/versionconstants.go
* #4313 
* #4243 
* DDEV wsl2 test runner wouldn't work right when buildkite-agent was running as uid 999
The blackfire user takes over uid 999 inside the web container, and the mysql user takes over uid 999 in the db container. There could be other conflicts, but this seems to be the main one. This affects any time the host-side user is uid 999, which includes a variety of things, including buildkite-agent. Mostly I don't see likely other conflicts. This also affects Ubuntu Live, where the default user is 999 (#4243)
* Use `username` for setup instead of a host-side expected username
* Put nvm setup directly into .bashrc in container instead of waiting for nvm to do it.
* Create a user with uid 999 and use ddev with it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4346">< …
> Fix UID collision with host-side uid 999 and make docker-compose username override work again, fixes #4243, fixes #4313

- containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/healthcheck.sh
- pkg/versionconstants/versionconstants.go
@weitzman noticed that something he added to .bashrc.d in homeadditions was being executed by the healthcheck every minute.
The healthcheck should not be loading any profile or bashrc scripts.
Run the healthcheck without bashrc or profile
TODO:
```bash
echo "junk.sh got run"
```
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4356"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't run /etc/bash_profile  ~/.bash_profile or .bashrc in ddev-webserver healthcheck

- cmd/ddev/cmd/debug-nfsmount.go
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/dockerutil/wsl.go
* #4122 
Sets `wsize`/`rsize` to 32768
See 
* #4122 
@rfay unsure how you'd like to test. I've been using a 100MB zip file and running md5sum on it from inside a container, but I bet you don't want a 100MB object in the git repo 🙃
* #4122
* docker/for-mac#6544
Existing NFS volumes would need to be deleted/recreated to pick up the new options.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4359"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set NFS wsize/rsize options for Ventura (Fixes #4122)

- docs/content/users/install/docker-installation.md
The docker installation with the command mentioned in the docs [https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#docker-ce-inside-windows-wsl2](https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#docker-ce-inside-windows-wsl2) does not work:
```
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update && sudo apt-get install ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/    linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > …
```
> [docs] correct url in the docker install command

- docs/content/users/install/ddev-installation.md
- scripts/install_ddev_wsl2.ps1
- scripts/install_ddev_wsl2_docker_desktop.ps1
The existing installation instructions include a long, long list of activities, most of which can be scripted.
Try to script them. `wsl --install` and Docker Desktop installation are prerequisites.
Try running it. It shouldn't harm existing installations.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4150"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve WSL2 Installation experience with a PowerShell script [skip ci]

- docs/content/users/topics/phpstorm.md
Updated documentation to indicate needing to use the full path.
Following the docs at https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/ was not working because a path with `~` didn't work.
I got this error from PhpStorm:
```
Error while parsing <projectroot>.ddev/.ddev-docker-compose-full.yaml
Cannot run program "~/.ddev/bin/docker-compose" in directory ...
No such file or directory
```
Related:
* https://github.com/php-perfect/ddev-intellij-plugin/issues/123
Updates the documentation to indicate that the full path is necessary.
Review text changes.
NA
NA
NA
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4368"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Don't use inappropriate ~ for path in PhpStorm location for docker-compose

- .github/workflows/master-build.yml
We're getting errors in the master build (macOS) saying that xq isn't installed.
It seems that xq is now available via brew, so add it there. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4369"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests] Add xq and yq to brew install in master-build [skip ci]

- .circleci/linux_circle_vm_setup.sh
- .circleci/macos_circle_vm_setup.sh
- .github/workflows/master-build.yml
- .spellcheckwordlist.txt
- README.md
xq and yq are not needed in the build any more.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4370"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] xq and yq are no longer needed

- docs/content/users/configuration/config_yaml.md
- docs/content/users/extend/customization-extendibility.md
Realized working on #4354 that the `web_extra_daemons` and `web_extra_exposed_ports` settings aren’t referenced on the refreshed config settings page.
This adds those settings and links back to them where their usage is described in more detail.
You can test manually by checking out this branch and following [these steps](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes), or examine the [automatic preview build](https://ddev--4373.org.readthedocs.build/en/4373/users/configuration/config_yaml/#web_extra_daemons).
n/a
- #4354
- #4188
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4373"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add `web_extra_daemons` and `web_extra_exposed_ports` to settings page

- docs/content/users/basics/database-management.md
Incorrect directories in MySQL workbench example cp command
Adds missing / after ~
Run said command(s) on machine
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4381"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix mysqlworkbench custom command instructions

- pkg/ddevapp/ddevapp_test.go
TestDdevStart was dependent on DDEV_DEBUG=true
Remove the check for that text.
> [tests only] TestDdevStart should not rely on DDEV_DEBUG

- pkg/dockerutil/dockerutils.go
* People on Linux keep finding trouble with Docker Desktop for Linux. 
* This is mentioned in the docs
Warn them so they maybe they won't use it.
Try to `ddev start` with Docker Desktop for Linux
> Warn about usage of Docker Desktop for Linux

- docs/content/developers/building-contributing.md
The content https://guides.github.com/activities/contributing-to-open-source/ is gone from github. 
Remove the reference
> [docs] Contributing to open source URL no longer at github

- docs/content/users/install/performance.md
Looks like I missed some minor stylistic edits on the Performance page!
This fixes a few stylistic issues to adhere to the writing guide, capitalizing “Mutagen”, making sure to “run” commands, using backticks consistently, and making tiny edits for brevity.
[Preview locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or by visiting the [automatic build preview](https://ddev--4386.org.readthedocs.build/en/4386/users/install/performance/#troubleshooting-mutagen-sync-issues).
n/a
#4188
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4386"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Stylistic cleanup

- cmd/ddev/cmd/root_test.go
- pkg/dockerutil/dockerutils.go
We're warning about Docker Desktop on WSL2, shouldn't be
> Don't warn about Docker Desktop for Linux on WSL2

- cmd/ddev/cmd/share.go
ngrok no longer accepts `-subdomain` as an arg, now `--subdomain`, 
* #4390
(Note: You don't need this PR to solve the problem, but instead can just use the technique in the docs, https://ddev.readthedocs.io/en/latest/users/topics/sharing/#setting-up-a-stable-ngrok-subdomain - put the ngrok args in config.yaml)
Use --subdomain
With paid ngrok account, `ddev share --subdomain=xxxsomething`
> ddev share --subdomain should use ngrok --subdomain, fixes #4390

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
* #4391 
* https://github.com/docker-library/postgres/issues/1012
Work around by using archive versions of debian repositories.
`ddev config --database=postgres:9 && ddev start` (and the postgres:10 and postgres:11`
Then `ddev psql`
We did miss this in the automated tests because these older versions were excluded in TestDdevAllDatabases. I added postgres:10 and postgres:11 to that test.
> Fix postgres 9-11 build broken, fixes #4391

- .goreleaser.yml
After moving to GoReleaser, dependencies for AUR were lost.
Brings back missing `depends` and `optdepends`.
I moved `docker-compose` to `optdepends` because it is not required now.
Check `PKGBUILD` for the options above in [ddev-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddev-bin) and [ddev-edge-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddev-edge-bin) after release.
https://github.com/drud/ddev/issues/3723
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4396"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> AUR: bring dependencies back to PKGBUILD recipe

- docs/content/users/install/ddev-installation.md
The WSL2 docker desktop download script was a 404
Fix it
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4400"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix 404 on wsl2 docker desktop download

- docs/content/users/install/ddev-installation.md
WSL2 install scripts don't work right in PS7
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4401"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] WSL2 instructions should specify PowerShell 5

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/hostname_mgt.go
* #4404 - hosts file removal didn't work on non-WSL2 any more, it always tried to remove all hosts entries.
Was broken by 
* #4377
Check the hosts file to see if we actually need to remove
* Preferred setup is latest version of DDEV installed on Windows side, with gsudo. (Only difference in latest version is it doesn't require docker on Windows side)
* `gsudo cache on` (on Windows side) can make things easier for WSL2 users who have additional_hostnames. `gsudo config CacheMode auto` even easier.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4408"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Restore proper hosts file removal, fixes #4404

- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/push.go
- pkg/ddevapp/provider.go
- pkg/ddevapp/providerPlatform_test.go
* #4180 
* https://github.com/platformsh/ddev-platformsh/issues/63
Add `--environment` to `ddev pull`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4399"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow setting environment in ddev pull on command line, fixes #4180, fixes platformsh/ddev-platformsh#63

- docs/content/users/extend/custom-compose-files.md
The code sample at https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/#docker-composeyaml-examples has an indentation problem in the `labels` section.
Reformats the whole section to use 2-spaces like the other examples on this page.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4412"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fixing indentation in multiple exposed ports example YAML.

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/composer-create.go
- cmd/ddev/cmd/composer.go
- docs/content/users/extend/custom-commands.md
- pkg/ddevapp/global_dotddev_assets/commands/host/launch
- pkg/ddevapp/global_dotddev_assets/commands/web/blackfire
- pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
- pkg/ddevapp/global_dotddev_assets/commands/web/xhprof
Disables flag parsing for custom commands and some internal ones.
Attempts to solve #4225.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4283"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Disable flags from custom commands when the annotation is not present, fixes #4225

- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/get_test.go
- docs/content/users/extend/additional-services.md
- pkg/nodeps/utils.go
`ddev get` can be pretty intimidating on a large add-on
Provide simpler and colored output:
Try `ddev get platformsh/ddev-platformsh`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4414"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make `ddev get` output friendlier

- pkg/globalconfig/global_config.go
In preparation for DDEV v1.21.4, bump docker-compose to current release 2.13.0
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4422"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump docker-compose to v2.13.0

- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
* #4309 
Import environment variables from project .ddev/.env file if it exists. 
Create a .ddev/.env file, `ddev restart`, verify that your env vars appear in the web container.
Added TestEnvFile
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4418"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add support for .ddev/.env file, fixes #4309

- docs/content/users/basics/commands.md
- docs/content/users/basics/faq.md
- pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
* #2680 
DDEV users sometimes don't know how to upgrade
Add `ddev self-upgrade` command to give clues
Test it on
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4419"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> `ddev self-upgrade` command, fixes #2680

- pkg/globalconfig/global_config.go
docker-compose 2.14.0 was released. Test it.
> Bump docker-compose to 2.14.0

- docs/content/users/extend/customization-extendibility.md
The docs added in #4418 could use some pedantic nitpicking.
This jumps right in with pedantic nitpicking:
- Fixes a backtick formatting issue.
- Introduces environment-variable-setting methods so it seems less like an unfinished sentence.
- Reorders methods from what we know/expect to what’s new/different.
- Rewords slightly and works in “setting” and “command” phrases to gently reiterate how DDEV works.
- Clarifies that we’re using the `ddev config` command in the example, and links to its reference to again subtly reiterate how DDEV works.
- Reformats `ddev config` command for (hopefully) easier readability.
- Moves sensitive value warning into warning callout and further suggests common `.env.example` convention while we’re covering basic secret hygiene—and gives the callout a heading …
> [docs] Improvements on addition of .ddev/.env file (for #4418)

- cmd/ddev/cmd/get.go
* #4423 
* Improve output when a pre-install or post-install action fails
* Fix error in output from global files
Try it out with `platformsh/ddev-platformsh`, `drud/ddev-redis` etc
> Improve output from ddev get, fixes #4423

- .ci-scripts/generate_artifacts.sh
- .ci-scripts/linux_arm64_setup.sh
- Makefile
- containers/ddev-php-base/Dockerfile
- containers/ddev-router/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
* Bump mkcert and yq versions
* Use real mkcert repo instead of our fork
> Web image maintenance: Bump mkcert, yq versions, use real mkcert repo

- docs/content/users/quickstart.md
Our team has decided to stop advertising bare downloads as a means of installing Craft, in favor of using `composer create-project`.
Removes instructions that use `curl` and a CDN URL to download a barebones Craft project folder.
_None_
_None_
_None_
This is a documentation-only PR. No functionality provided by the Craft project type is affected.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4428"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Craft CMS: Remove manual download instructions

- pkg/ddevapp/ddevapp.go
It references an old option to skip creating a snapshot.
From `ddev delete --remove-data --yes`
To `ddev delete --omit-snapshot --yes`
When you try deleting a project with `ddev delete`, you get the following output:
```
...
your db container in project drupalcms is not running. 
Please start the project if you want to snapshot it. 
If deleting project, you can delete without a snapshot using 
'ddev delete --remove-data --yes', 
which will destroy your database
```
The above is incorrect because `--remove-data` does not exist.
It replaces `--remove-data` by `--omit-snapshot`.
This is a documentation change so there is no need to test anything manually.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4438"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix help message when deleting a project

- pkg/ddevapp/craftcms.go
- pkg/ddevapp/envfile.go
- pkg/ddevapp/envfile_test.go
- pkg/ddevapp/laravel.go
- pkg/ddevapp/shopware6.go
- pkg/ddevapp/testdata/TestWriteProjectEnvFile/env-ambiguousvar.txt
- pkg/ddevapp/testdata/TestWriteProjectEnvFile/env-commentsnewlines.txt
- pkg/ddevapp/testdata/TestWriteProjectEnvFile/env-normalthings.txt
See bug reported in 
* https://github.com/drud/ddev/pull/4197#issuecomment-1340843620 Thanks @stasadev
The application .env file replacement (for laravel, shopware, etc.) was matching partials on the key, so 
> For example, I have DYNAMODB_CONNECTION in my .env (from [this](https://github.com/baopham/laravel-dynamodb/blob/963811691313124e7562a02aefdcc31fdbd75e78/config/dynamodb.php#L14) package) and ddev thinks it is the same as DB_CONNECTION, and replaced my config with DYNAMODB_CONNECTION="mysql".
* Use a more sophisticated pattern for replacement
* Add TestWriteProjectEnvFile that covers (hopefully) all the things
Try the env file suggested by @stasadev 
Added significant test in TestWriteProjectEnvFile
* https://github.com/drud/ddev/pull/4197#issuecomment-1340843620 
* #3636 
* #3590
> Fix over-eager project env replacement, for #4197

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- pkg/ddevapp/ddevapp_test.go
deb.sury.org fixed a number of missing php 8.2 extensions, so they should all be here now.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update php 8.2 extensions (xdebug, memcached, redis now there)

- cmd/ddev/cmd/pull.go
- cmd/ddev/cmd/push.go
- docs/content/users/providers/platform.md
- pkg/ddevapp/dotddev_assets/providers/platform.yaml
- pkg/ddevapp/provider.go
- pkg/ddevapp/providerPlatform_test.go
* #4415 
* https://github.com/platformsh/ddev-platformsh/issues/59
* https://github.com/drud/ddev/pull/4417
* DDEV was focused on downloading a single database
* Use relationships to download all the upstream databases
* If one should be primary, set it with PLATFORM_PRIMARY_RELATIONSHIP and it will go into the database named 'db'
This also fixes a bug in handling blank `--environment` in `ddev pull`
Try it out on a multisite or whatever, `ddev config --web-environment-add=PLATFORM_PRIMARY_RELATIONSHIP=maindb` or `ddev pull platform --environment=PLATFORM_PRIMARY_RELATIONSHIP=maindb` 
Multiple databases are not yet covered in TestPlatformPull. 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4426"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Platform integration: Download all databases, Allow a primary relationship for the main 'db', fixes #4415, fixes platformsh/ddev-platformsh#59

- cmd/ddev/cmd/get.go
- docs/content/users/basics/commands.md
When `ddev get` fails it can emit a lot of ugliness that is hard to parse
By default, don't show all the extra info. Just show the item that failed and prompt them to use `ddev get -v` to figure it out.
Break an addon locally, make sure it has #ddev-description in it, `ddev get` it. Use --verbose to get more info.
> Improve output of ddev get in failure cases and add --verbose flag

- docs/content/users/basics/database-management.md
- docs/content/users/quickstart.md
* #4197 edited the quickstart but didn't do it right.
See discussion about laravel problems in 
* https://github.com/drud/ddev/pull/4273#issuecomment-1335649935
> [docs] Laravel quickstart had duplicated `ddev composer create`

- .github/workflows/colima-tests.yml
Colima tests are failing, and the homebrew cache there is old
See if starting a new cache will fix colima tests.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4458"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [Tests only] Refresh homebrew/lima caches since colima/lima upgraded

- docs/content/users/providers/platform.md
A typo in docs
Fixes the typo
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4457"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix typo on primary relationship command

- docs/content/users/extend/customization-extendibility.md
- docs/content/users/install/docker-installation.md
- docs/content/users/providers/platform.md
- docs/content/users/quickstart.md
- docs/content/users/topics/phpstorm.md
- pkg/ddevapp/config.go
- pkg/ddevapp/dotddev_assets/providers/platform.yaml
- version-history.md
* See https://github.com/drud/ddev/issues/4452 - there were duplicate handling of WSL2 docker installation in the docker and DDEV installation sections.
* PhpStorm WSL2 instructions update
* Drupal 10 and Drupal 9 quickstart updates with release of Drupal 10
* version_history.md update for release of v.1.21.4
* #4411
* Much shorter Docker installation sections for WSL2, with links
https://ddev--4456.org.readthedocs.build/en/4456/users/install/docker-installation/#windows
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4456"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Multiple release prep docs changes, fixes #4411

- docs/content/users/install/ddev-installation.md
addresses #4461
Installing ddev on Arch.
Fixes AUR package name.
Run `yay -S ddev-bin` on Arch.
#4461
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4462"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fixes Arch yay install/update; to match package name, fixes #4461

- docs/content/users/extend/customizing-images.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
It was always awkward to build a PHP extension in a Dockerfile because you had to do the very fragile setting of PHP version inside the Dockefile
* Provide DDEV_PHP_VERSION at Dockerfile build time
* Provide docs example on how to build an extension
Try out the doc.
Added test of this in TestCustomBuildDockerfiles
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4463"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add DDEV_PHP_VERSION to image build time, docs for building extension

- .spellcheckwordlist.txt
- docs/content/users/install/ddev-installation.md
Following on after https://github.com/drud/ddev/pull/4462 to remove unnecessary backticks and add some commas.
Some commas were needed and some backticks were not.
Fixing some (mostly existing) stylistic issues.
[Preview locally](https://ddev.readthedocs.io/en/latest/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--4464.org.readthedocs.build/en/4464/users/install/ddev-installation/#linux).
n/a
- #4462
- #4188
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Update Arch Linux section in ddev-installation.md

- cmd/ddev/cmd/get.go
- docs/content/users/extend/additional-services.md
- docs/content/users/providers/platform.md
- pkg/ddevapp/dotddev_assets/providers/platform.yaml
drud/ddev-platformsh is now officially supported
Fix references to platformsh/ddev-platformsh and update the official add-ons list
* https://ddev--4460.org.readthedocs.build/en/4460/users/providers/platform/
* https://ddev--4460.org.readthedocs.build/en/4460/users/extend/additional-services/
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4460"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add ddev-platformsh as officially supported

- docs/content/users/basics/commands.md
- docs/content/users/configuration/config.md
- docs/content/users/extend/customization-extendibility.md
- docs/content/users/install/docker-installation.md
Need to catch up!
This adds more minor edits to some of the remaining documentation updates in #4456. Mainly fixing up some wording and again emphasizing and improving reference materials.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the automatic build:
- [Commands → config](https://ddev--4470.org.readthedocs.build/en/4470/users/basics/commands/#config)
- [Config Options → `webserver_type`](https://ddev--4470.org.readthedocs.build/en/4470/users/configuration/config/#webserver_type)
- [Extending and Customizing Environments](https://ddev--4470.org.readthedocs.build/en/4470/users/extend/customization-extendibility/)
- [Changing Web Server Type](https://ddev--4470.org.readthedocs.build/en/4470/users/extend/customization- …
> [docs] nginx/snippet/restart cleanup for #4456

- docs/content/users/basics/commands.md
- docs/content/users/providers/platform.md
Documentation guy is too slow right now and trying to catch up.
This makes some minor edits for consistency and hopefully clearer phrasing about how databases are handled in the Platform.sh integration.
I brought this up to date with the `master` branch and had to fix a conflict in `docs/content/users/providers/platform.md`, which I think looks good and doesn’t omit any improvements. But you may want to double-check.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the automatic build:
- [Commands → `get`](https://ddev--4469.org.readthedocs.build/en/4469/users/basics/commands/#get)
- [Platforms → Platform.sh → Designating a Primary Database](https://ddev--4469.org.readthedocs.build/en/4469/users/providers/platform/#designa …
> [docs] Minor tidying for `ddev pull platform` PRs #4441 and #4426

- .github/devcontainers/src/install-ddev/README.md
- .github/devcontainers/src/install-ddev/devcontainer-feature.json
- .github/devcontainers/src/install-ddev/install.sh
- .github/workflows/devcontainer-feature-release.yaml
The preferred technique to use DDEV in GitHub codespaces is to use a feature.
This builds the feature for codespaces.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add package build for install-ddev (for github codespaces) [skip ci]

- docs/content/users/quickstart.md
This fixes a typo in the docs when suggesting switching to the `craftcms` project type: `craft → craftcms`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix typo in project type

- docs/content/developers/building-contributing.md
The “Testing a PR” instructions could be slightly more clear and easy to follow.
- Moves steps into full fenced blocks for easier copying. (Since people will very likely copy these verbatim.)
- Keeps `unzip` on its own line since it’ll be unnecessary if the binary was downloaded with a browser that automatically extracts it, like Safari.
- Moves macOS binary note to a headlined tip so it’s easier to skip for a non-macOS user.
- Maintains `/usr/local/bin/ddev` path (instead of `/path/to/ddev`) for consistency and mindless following.
- Adjusts language to “run” commands or pitch to a full code block.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect [the automatic build](https://ddev--4490.org.readthedocs.build/en/4490/develo …
> [docs] Update “Testing a PR”

- docs/content/users/basics/commands.md
This is just a documentation fix.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix example "debug dockercheck" on Commands page

- docs/content/users/extend/additional-hostnames.md
This is just a documentation fix.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4487"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix additional_hostnames example

- docs/content/users/install/docker-installation.md
Recent releases of Colima mean lots of permutations for vm type and mount type. Specify the current safest and fastest, based on https://ddev.com/ddev-local/ddev-docker-desktop-and-colima-benchmarking-updated-dec-2022/
Followup on 
* #4466
> [docs] Change colima recommendation for installation

- docs/content/users/extend/customizing-images.md
#4497 - DDEV_PHP_VERSION is not yet available in build in released ddev v1.21.4
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Add disclaimer about DDEV_PHP_VERSION in image build, fixes #4497 [skip ci]

- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
Confusing error message with typo.
Improves the readability.
N/A
This doesn't change how anything works.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4488"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve custom configuration information message

- mkdocs.yml
The navigation includes a section called “Developers”, which has two problems:
1. It breaks the naming convention that roughly describes actions (_Usage_, _Configuration_, _Extending_, _Debugging & Profiling_, _Hosting & Deployment_).
2. The section doesn’t actually describe DDEV’s _developers_, but processes and conventions for DDEV _development_.
This renames the section to _Development_.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the automatic build.
n/a
- #4188 
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] “Developers” → “Development”

- docs/content/users/install/phpstorm.md
Added a little note on finding the DDEV docker-compose file
I searched and searched after installing DDEV. I thought I should be prepared well and already install the plugin and appointing the right docker-compose file. This was before I did a `ddev start`.
It might not solve, but maybe give someone like me a hint :-)
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4513"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Private docker-compose not available until a project has been started

- docs/content/users/install/ddev-installation.md
* #4523 
In this PR I updated the link of the instructions for how to upgrade DDEV on WSL2 LINE#211 
Old:
To upgrade DDEV in WSL2 Ubuntu, use `apt upgrade ddev` as described in the [Linux installation section](#apt-packages-for-Debian-based-systems).
New:
To upgrade DDEV in WSL2 Ubuntu, use `apt upgrade ddev` as described in the [Linux installation section](#linux).
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix link in WSL2 upgrade section, fixes #4523

- docs/content/users/install/phpstorm.md
- mkdocs.yml
The documentation guy has been whining about smart punctuation ever since he started digging around here, and we’ve generally agreed that modern typography is lovely but it shouldn’t be a burden to the Markdown-writer.
[SmartyPants](https://daringfireball.net/projects/smartypants/) was created so long ago it’s old enough to drive and vote and almost buy cigarettes. To my embarrassment, it was trivially easy to enable and it now handles quotes and apostrophes automatically.
Take [this Markdown excerpt](https://github.com/drud/ddev/blob/master/docs/content/users/install/phpstorm.md?plain=1#L103-L106), for example:
```markdown
1. Open your WSL2 project using *File* → *Remote Development* → *WSL* and choose the distro, then the project.
2. For Xdebug you'll want to use `ddev config global …
```
> [docs] Enable SmartyPants

- docs/content/users/usage/developer-tools.md
Since [v1.21.4](https://github.com/drud/ddev/releases/tag/v1.21.4) command flags for wrapper commands work as expected, `ddev composer --help` works out of the box.
The [docs](https://ddev.readthedocs.io/en/latest/users/usage/developer-tools/#limitations-of-ddev-composer) mention limitions when using composer through ddev. This is not true since latest release v1.21.4.
It removes the composer limitations part in the docs.
Maybe it is too early to remove this notes for users with older ddev version stumpling upon this limitation. I don't know how you handle this..
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove notes about composer limitations

- docs/content/users/quickstart.md
The git clone example do a new directory named my-drupal-site but the cd go to example-site. Modify for consistency.
Change `cd` directory
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4534"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] typo: small typo error in drupal git clone section

- docs/content/users/quickstart.md
There is a mention to bedrock that is a composer-based installation where is a wording issue
I only correct a wording issue
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Correct a mistake in Bedrock description wording

- docs/overrides/partials/integrations/analytics/plausible.html
- mkdocs.yml
We needed to add a snippet.
This adds a snippet, though I guess it will only be live on the “latest” docs and take a while to get to “stable”.
I tested this locally to be sure the snippet’s included in `<head>`, which indeed it is. ~~Will verify that individual page views are tracked.~~
Used the preview build to confirm that individual pageviews are tracked as a visitor moves around the site, so all good!
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the automatic build.
n/a
#4367
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add Plausible analytics snippet

- pkg/ddevapp/craftcms.go
- pkg/ddevapp/envfile.go
- pkg/ddevapp/envfile_test.go
- pkg/ddevapp/laravel.go
- pkg/ddevapp/shopware6.go
There were some abstractions in #4197 that led to the addition of two methods for reading and writing out `.env` files for project types where settings management is enabled: `ReadProjectEnvFile` and `WriteProjectEnvFile` respectively. These methods each presumed that the `.env` file was located at `app.AppRoot`. However, there are cases where the `.env` file might need to live somewhere else, for example, if something like Craft CMS is installed in a subdirectory. In a case like, that, the post start action would keep attempting to write out an `.env` file in the incorrect location.
This PR makes the `envFilePath` a parameter in both `ReadProjectEnvFile` and `WriteProjectEnvFile`, which allows a given application type like Craft CMS or Laravel to be in charge of determining where it …
> Updates write path for `.env` files to respect app-specific locations.

- docs/content/users/usage/database-management.md
The [Database Management](https://ddev.readthedocs.io/en/stable/users/basics/database-management/) page uses a heading called “Discussion” that consists not of a discussion, but a massive bulleted list.
This liberates the useful nuggets of information from their list and groups them into more useful headings, with linking and minor language nitpicks we must expect from me at this point.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--4559.org.readthedocs.build/en/4559/users/usage/database-management/).
n/a
n/a
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4559"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] “Database Management” touch-up

- docs/content/users/project.md
- docs/content/users/quickstart.md
- mkdocs.yml
Randy [suggested in Discord](https://discord.com/channels/664580571770388500/1062097685143879801/1062097685143879801) that people get discouraged when their CMS type isn’t explicitly supported, and I suggested that we adjust the “Getting Started” framing to put less emphasis on CMS options and hopefully create a bit more clarity.
This adds a “Starting a Project” page as the first step under “Getting Started”, now leading into (and followed in the nav by) “CMS Quickstarts”. It also pushes “Performance” out of that first slot, because why did that ever make sense?
I tried to strip everything out of those first steps that didn’t _have_ to be there, and follow with support and jumping-off points below. The mention of generic `php` projects got a callout specifically because that’s the thing …
> [docs] Gentler “Getting Started” with less CMS emphasis

- pkg/ddevapp/hostname_mgt.go
In 
* #4553 at the last minute I introduced a regression where network lookup is no longer used when deciding whether to add a hostname to /etc/hosts, so it happens every time.
But the old code back in for *add* but not for *remove*.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4563"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix regression where it always adds *.ddev.site to hosts

- docs/content/users/usage/commands.md
Resolves #4541, where the 404 was the result of an incorrect path after some shuffling around.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4564"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix link on “Commands” page, fixes #4541

- docs/content/users/install/ddev-installation.md
The [Windows installation instructions](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#windows) include an unnecessary backtick.
This removes said backtick, along with an unnecessary space as a bonus.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the automatic build.
n/a
n/a
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4567"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Remove space and backtick from Windows installation instructions.

- README.md
While exciting, the new “Open in GitHub Codespaces” button visually dominates the row of badges and looks like a mistake:
The “DDEV” heading is also redundant with the logo just beneath it.
1. Introduces some uncomfortable HTML to fix the visual issue by limiting that badge’s height to 20px.
2. Replaces the DDEV heading with the DDEV logo (maintaining alt text!), where it can proudly lead the page instead of being informationally redundant.
It’s still not ideal because the badge’s text is significantly smaller than its peers. While GitHub [calls the thing a “badge”](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/adding-a-codespaces-badge) it looks like it’s intended to be used more like a button. Similar examples:
- [Deploy on …
> Improve visual balance of README.md.

- scripts/install_ddev_wsl2_docker_desktop.ps1
- scripts/install_ddev_wsl2_docker_inside.ps1
It turned out people with existing versions of ddev, mkcert, gsudo didn't get upgraded.
Use `choco upgrade` instead of `choco install`. It installs if not already installed.
Run the script
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4571"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [wsl install scripts] Use choco upgrade instead of choco install [skip ci]

- README.md
The readme’s “Open in GitHub Codespaces” badge opens the `rfay/ddev` repo fork when it should open `drud/ddev`.
This fixes the ID which, for future reference, I got here: https://api.github.com/repos/drud/ddev
Click the link and observe that it opens the correct repository.
n/a
https://discord.com/channels/664580571770388500/1066146245514633326
n/a
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4572"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix GitHub Codespaces badge repository ID [skip ci]

- .buildkite/test.sh
* https://github.com/docker/for-win/issues/13180 breaks tests on Windows and wsl2/Docker Desktop
Delete the ~/.docker/contexts on starting tests if it's broken
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Fix broken docker context list problem, for docker/for-win/#13180

- containers/ddev-php-base/ddev-php-files/etc/php/8.1/fpm/php-fpm.conf
- containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/php-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.1/fpm/php-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/php/8.2/fpm/php-fpm.conf
* #4587
* #4588
* #4590
* #4589
The php-fpm.conf files were including from the wrong directories in php 8.1 and 8.2. Thanks to @skleiber.
This won't take effect until the next set of images is built, which won't be too long.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4591"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix include dirs for php-fpm, fixes #4590, fixes #4589, fixes #4588, fixes #4587

- markdown-link-check.json
deb.sury.org is down, see 
* https://github.com/oerdnj/deb.sury.org/issues/1919
So it breaks our docs link checker. Just exclude it.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4592"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs/tests] Exclude deb.sury.org from link check

- docs/content/users/extend/customization-extendibility.md
Currently the docs states that you can easily edit the custom nginx configuration (on the host system) and run `ddev exec nginx -s reload` to take the changes into effect.
That's currently not possible, because the configuration is copied during restart. (Reference https://discord.com/channels/664580571770388500/1067833800597446698/1067834259815010365)
I edited the wording to reflect the current possibility to edit and reload the configuration within the container.
Read the docs and try to follow the steps: see if it really works 😄 
I don't think that it's possible to have automated testing for the documentation. Else I really need to know how!
https://discord.com/channels/664580571770388500/1067833800597446698/1067834259815010365
No actions needed since it's only plain text in the …
> [docs] update custom nginx configuration docs

- cmd/ddev/cmd/ssh.go
Attempt to check if values were piped in before deciding to return additional error output from ssh.go.  Issue 
* #3738.
`ddev ssh` returns output when not needed.  It should only do so when a command was piped in.
Lots of confusion on this... 
*  #1697 was in 2019... but that code isn't there any more. 
The change reversion happened in 
* https://github.com/drud/ddev/pull/2830
Which was fixing 
* #1858
It doesn't.  It's a direction that needs work.  Reading the stdin/piped-in values removes them from evaluation later down the chain.
Should NOT produce additional output and should exit with code 0:
```
ddev ssh
ls /non-existent
exit
echo $?
```
SHOULD produce error output from the piped in command:
`echo "ls /non-existent" | ddev ssh`
No automated tests at this time.
#3738 
In addition to …
> Make `ddev ssh` exit more predictable, not outputting useless info, fixes #3738

- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/tests/ddev-webserver/general.bats
- pkg/versionconstants/versionconstants.go
It doesn't make sense for Xdebug to be enabled by default in ddev-webserver any more:
* #4597 
It was enabled for very different workflows back in the day, see 
* https://github.com/drud/ddev/issues/2245
* https://github.com/drud/ddev/pull/2460
I don't think those workflows are valid any more, but will ping those folks.
Turn off xdebug after it's installed.
As @deviantintegral did in #4597, `docker run -it --rm drud/ddev-webserver:20230128_xdebug_build_time
php --version` and see if xdebug is shown there.
It may be worth trying to fix `ddev composer`,  so they doesn't try to use xdebug as well.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4599"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't enable xdebug by default in ddev-webserver, fixes #4597

- cmd/ddev/cmd/ssh.go
There is no "sb" service in ddev by default. It was probably just a mistype of the "s" next to the "d" on the keyboard. Just adjust that.
Run `ddev ssh --help`
Only info/help/documentation text output
--
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4602"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update service name typo in ddev ssh example

- pkg/ddevapp/testdata/TestTraefikVirtualHost/docker-compose.extra.yaml
- pkg/ddevapp/traefik.go
- pkg/ddevapp/traefik_config_template.yaml
- pkg/ddevapp/traefik_test.go
* #4537 
It was mistakenly using all hostnames for all services, now actually walking the routingTable
Added TestTraefikVirtualHost
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4582"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Traefik needs to properly handle $VIRTUAL_HOST, fixes #4537

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
In
* #4582
I noticed that manually edited traefik config was not being handled correctly; it should have been left out of the .ddev/.gitconfig, and instead the whole directory was gitignored.
* Gitignore the specific files
* Fix mutagen config, which had the same problem
* Fix mutagen/.start-synced, which did not contain #ddev-generated
* Check in your project
* Manually edit .ddev/traefik/<project>.conf, remove the #ddev-generated from top
* `ddev start`
* You should see .ddev/traefik/<project>project.conf as changed in `git status`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4604"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure that traefik items get properly managed in .gitconfig

- cmd/ddev/cmd/get_test.go
- pkg/globalconfig/values.go
* #4608
We moved all the official add-ons to github.com/ddev, and now none are found.
* change org to ddev
* Fix test to use correct URLs
`ddev get --list` should show all 14 official add-ons
Existing test already covered this and would be failing without this.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4609"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use 'ddev' for official add-ons, fix test, fixes #4608

- pkg/ddevapp/config.go
npm behavior with regard to `--unsafe-perm` seems to have changed, and now the various versions don't `npm install` in the same way; some need --unsafe-perm, and others need `npm config unsafe-perm`
Try both ways.
`ddev config --nodejs-version= <all>` and `ddev start` and `ddev exec gulp`
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4610"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make nodejs installation work, changed npm --unsafe-perm behavior

- cmd/ddev/cmd/composer-create.go
* #4475 
* Create the directory in advance
* Do the composer create-project into the named composer_root
See #4475 
* Did not add test
* 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4611"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make 'ddev composer create' respect composer_root, fixes #4475

- cmd/ddev/cmd/root_test.go
- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
- pkg/ddevapp/config.go
- pkg/ddevapp/nodejs_test.go
- pkg/versionconstants/versionconstants.go
* #4499 
NVM regression in DDEV v1.21.4 was caused mostly by dropping the NVM_DIR environment variable in the container.
* Restore the NVM_DIR globally
* Improve the .bashrc (from /etc/skel) by using `source` instead of `.`
* Add better nvm coverage to TestNodeJSVersions
```
ddev nvm install 10.16.0 && ddev nvm use 10.16.0 && ddev nvm alias default 10.16.0
ddev exec node --version
```
should show 10.16.0
Manually test the things #4346 was aimed at:
#4346 was trying to fix the issues in 
Improved TestNodeJSVersions to get coverage for this case.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4620"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make ddev nvm work right again, fixes #4499

- .spellcheckwordlist.txt
- docs/content/users/quickstart.md
Recently [Discord issue](https://discord.com/channels/664580571770388500/1072827039415021628/1072827039415021628) highlighted the need for current setup instructions.
There is older article, [Setup Statamic via DDEV](https://dev.to/mandrasch/setup-statamic-via-ddev-39bi) which is outdated and has issues as discussed in Discord thread.
Statamic is built on top of Laravel, so the instructions are almost identical.
Work through setup instructions.
There is currently an "unoffical" addon [ddev-addon-statamic-please](https://github.com/mandrasch/ddev-addon-statamic-please). 
This does _not_ include the `ddev-get` topic and is therefore not disoverable by DDEV. An [issue](https://github.com/mandrasch/ddev-addon-statamic-please/issues/1) was created to address this. However, the addon is stale …
> [docs] add Statamic setup guide

- .ci-scripts/linux_arm64_setup.sh
- .github/workflows/colima-tests.yml
- .github/workflows/container-tests.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/master-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/tests.yml
- .gitpod/images/Dockerfile
- Makefile
- go.mod
- pkg/archive/archive.go
- pkg/fileutil/files.go
- pkg/util/utils.go
Go v1.210 is out
This should fix 
* #4443
Several testing environments depend on homebrew to install go 1.20, and it is not yet available, see 
* https://github.com/Homebrew/homebrew-core/pull/122082
golangci-lint (at least the homebrew version) does not yet work with go 1.20
Download the appropriate binary from https://github.com/drud/ddev/pull/4639#issuecomment-1426199485. But it's not signed/notarized, so see "macOS and unsigned binaries" in https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-latest-commits-on-head, `xattr -r -d com.apple.quarantine /path/to/ddev`
See if the networking issue is resolved.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4639"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump golang to v1.20, fixes #4443

- pkg/ddevapp/ddevapp.go
I noticed that a new check about /mnt/ddev_config being mounted resulted in a failure, but it only needs to be a warning.
This class of failure happens when:
* Colima: Project directory is outside the home dir.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4642"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> If /mnt/ddev_config is not mounted, don't fail, just warn

- pkg/globalconfig/global_config.go
docker-compose 2.16.0 is out
It's built with go 1.20, so may impact DNS issues reported in 
* #4443 
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4641"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump docker-compose to 2.16.0, which is built with go 1.20, fixing DNS issues on macOS

- docs/content/users/install/performance.md
- pkg/ddevapp/mutagen_config_assets/mutagen.yml
Big tarballs, or unmanaged files in .ddev/.downloads can cause extraordinary starup pain with mutagen enabled. 
* Add .ddev/.downloads to mutagen exclusion
* Add docs about figuring what's wrong in this situation (infinite startup time when mutagen enabled)
> Add .ddev/.downloads to mutagen exclusions, fixes #4645

- .github/workflows/master-build.yml
There's a long term problem with actions/cache when caching on Windows and then restoring on linux.
Apparently there is new trouble in this area.
But we were using the old actions/cache 3.0.11 on Windows, and that suddenly seems to have stopped working.
They have struggled and struggled with this.
> [tests only] Attempt to get actions/cache working again [skip ci]

- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
At least in my experience you can't run `ddev composer require drush/drush` before having a project configured. You need to run `ddev config` first, then run `ddev...` commands.
> [docs] pantheon.yaml.example comments: changed sequence of items #6 and #7

- Makefile
- pkg/dockerutil/dockerutils.go
* #4655
Change regex that controls output to adjust to latest docker-compose output.
`ddev start` should only show a few lines of output, like
```
$ ddev start
Starting d9...
Container ddev-d9-dba  Running
Container ddev-d9-db  Recreate
Container ddev-d9-web  Running
Container ddev-d9-db  Recreated
Container ddev-d9-db  Started
Starting mutagen sync process... This can take some time.
Mutagen sync flush completed in 1s.
For details on sync status 'ddev mutagen st d9 -l'
Container ddev-router  Running
```
> Fix chatty docker-compose output, fixes #4655

- docs/content/users/configuration/config.md
- docs/content/users/usage/developer-tools.md
The webserver_type description here:
https://ddev.readthedocs.io/en/stable/users/configuration/config/#webserver_type
Was the same as xdebug_enabled here:
https://ddev.readthedocs.io/en/stable/users/configuration/config/#xdebug_enabled
This PR fixes that.
> [docs] Fix copy pasta on webserver_type description

- .vscode/launch.json
- containers/ddev-dbserver/Dockerfile
- containers/ddev-dbserver/Makefile
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/versionconstants/versionconstants.go
* #4619 
* #4504
It's been a really long time since we've been able to bump mysql, because we depend on xtrabackup for `ddev snapshot`, and xtrabackup always lags mysql 8.0, to the point that you can't get the Ubuntu packages for mysql 8.0 by the time the related/matching xtrabackup is released. 
This time we captured/downloaded the relevant mysql-8.0 packages as debs ahead of the xtrabackup release, so were able to adapt the build to use those instead of using current mysql.
* Configure project with mysql 8.0 and verify that it's running 8.0.31 (`ddev exec -s db mysql --version`). Install, use. 
* Create snapshot
* Restore snapshot and verify behavior
No new tests, but there's a full set of tests to run through these.
* https://github.com/drud/ddev/pull/4026
* …
> Bump mysql to 8.0.31 and 5.7.41, fixes #4619, fixes #4504

- .github/workflows/master-build.yml
Windows artifacts weren't being properly cached, weren't being restored, etc.
* https://github.com/actions/cache/issues/1114 and related
Caching of windows binary was failing in release and upload process
Use newer inputs:
```
enableCrossOsArchive: true
fail-on-cache-miss: true
```
> [tests/release] Fix upload artifacts/cross-os caching failure

- docs/content/users/extend/customization-extendibility.md
https://github.com/drud/ddev/issues/4648
Prepends the missing `.ddev/web-build/` to the `daemonname.conf` example.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the automatic build.
n/a
https://github.com/drud/ddev/issues/4648
n/a
> [docs] Prepend project-relative path and capitalize Supervisor

- docs/content/users/install/ddev-installation.md
Typo in documentation:
> DDEV is a single executable, so installation on any OS is a matter of copying the **a** `ddev` binary for your architecture into the appropriate system path on your machine.
Fixes typo:
> DDEV is a single executable, so installation on any OS is a matter of copying the `ddev` binary for your architecture into the appropriate system path on your machine.
Does not apply
Does not apply
\-
None, it's only about docs.
> [docs] Fix typo in manual installation doc

- cmd/ddev/cmd/import-files.go
- pkg/ddevapp/ddevapp.go
In the two queries for a full path, "pull" is used instead of "full".
"pull" is replaced by "full".
Run the two commands `import-db` and `import-files` to see if the query for the path is fine.
> Fix `ddev import-db` and `ddev import-files` queries for path to artifacts

- mkdocs.yml
Upgrading to mkdocs-material 9 lost edit and copy icons that are so useful.
* https://github.com/squidfunk/mkdocs-material/issues/5092#issuecomment-1443927417
Enable them explicitly
See https://ddev--4675.org.readthedocs.build/en/4675/ to review this.
> [docs] Re-enable copy and edit icons

- cmd/ddev/cmd/config-global_test.go
- docs/content/users/configuration/config.md
- docs/content/users/topics/hosting.md
- pkg/globalconfig/global_config.go
* #4632 
Don't allow this configuration; however, it can be configured with custom traefik config
Try to configure let's encrypt with traefik. Should fail. Read docs.
> Don't allow Let's Encrypt with Traefik router, fixes #4632

- mkdocs.yml
Icon for editing docs was obscure.
* https://github.com/squidfunk/mkdocs-material/issues/5092#issuecomment-1445152593
Change the icon.
> [docs] Change edit button to pencil again

- docs/content/users/usage/cms-settings.md
The _Managing CMS Specifics_ page includes an oddly-formatted [TYPO3 Specifics](https://ddev.readthedocs.io/en/latest/users/usage/cms-settings/#typo3-specifics) section, which starts with a single-item bulleted list and continues with a level 4 subheading.
This swaps the rogue bullet with a level 4 subheading, and adds the word “file” to complete the sentence.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--4687.org.readthedocs.build/en/4687/users/usage/cms-settings/#typo3-specifics).
n/a
n/a
n/a
> [docs] Fix “TYPO3 Specifics” formatting

- docs/content/users/quickstart.md
The CMS Quickstarts page includes [WordPress Git Clone instructions](https://ddev.readthedocs.io/en/latest/users/quickstart/#git-clone_2) that are a bit of a formatting mess and needlessly verbose.
This fixes the formatting, improves brevity, and better adheres to the [writing guide](https://ddev.readthedocs.io/en/stable/developers/writing-style-guide/). It will also pair nicely with #4685 to improve PHP highlighting.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--4686.org.readthedocs.build/en/4686/users/quickstart/#git-clone_2).
n/a
n/a
n/a
> [docs] Fix Wordpress Git Clone

- mkdocs.yml
The few PHP fenced code blocks we’ve got (` ```php `) [don’t appear to be highlighted](https://ddev.readthedocs.io/en/latest/users/usage/cms-settings/#cms-specific-help-and-techniques) like you’d expect:
While it’s possible to fix this with a leading `<?php`, that also seems impractical and even distracting in some cases. So this PR uses the `extend_pygments_lang` options to override the `php` highlighter’s default behavior and allow inline highlighting—which means highlighting clumps of PHP that don’t start with an opening `<?php`.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect [the automatic build](https://ddev--4685.org.readthedocs.build/en/4685/users/usage/cms-settings/#cms-specific-help-and-techniques).
n/a
n/a
n/a
> [docs] Fix PHP code block highlighting

- cmd/ddev/cmd/debug-dockercheck.go
- cmd/ddev/cmd/debug-nfsmount.go
- pkg/ddevapp/db.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/poweroff.go
- pkg/dockerutil/dockerutils.go
* #4676
* https://github.com/drud/ddev/pull/4635
* GetExistingDBType() used heavyweight image to do its work, use busybox instead; this should also make disruption in `ddev config` on first pull be nicer.
* app.PullContainerImages() moved to earlier in Start() so that it behaves more predictably.
No new tests are added
> Make sure all containers get cleaned up on stop and poweroff, fixes #4676

- .github/devcontainers/src/install-ddev/devcontainer-feature.json
- .github/devcontainers/src/install-ddev/install.sh
When v1.21.5 comes out, codespaces/devcontainer can use regular apt install
Prepare to just use apt install
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4612"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Switch devcontainer/github codespaces to use apt install

- docs/content/index.md
- docs/content/users/install/ddev-installation.md
- docs/content/users/install/docker-installation.md
* One person reported confusion about the wording of Docker Desktop vs Colima, thinking that Colima was only for older versions of macOS
* Many people don't understand that Mutagen is the normal standard on macOS (and will be default on v1.22)
* VirtioFS is still problematic on filesystem permissions on Docker Desktop.
> [docs] Update guidance about Colima/Docker Desktop requirements and Mutagen

- docs/content/users/usage/cms-settings.md
Changes are from Discord DDEV multisite [forum question posed by KristofferRom](https://discord.com/channels/664580571770388500/1037263797674594334).  File examples are from Jon McLaughlin and tested by myself  with an existing codebase deployed on Acquia Cloud Site Factory.
**Original Question**
Anyone here with experience in converting separate sites to one multisite using ddev as local environment? I'm aware of https://github.com/drud/ddev-contrib/tree/master/recipes/drupal8-multisite but I was thinking to use an existing site as the code base so installing with --disable-settings-management isn't an option. Is there a workaround or should I create a new installation for the code base?
**Additional Requirements**
We run a Drupal Multisite setup where the default DB manages the bulk of …
> [docs] Add Drupal Multisite recommendations

- .github/workflows/docscheck.yml
To avoid hassle with minor upgrades of Github Actions it is better to not to look a specific version and use a canonical version instead.
This patch replaces the current versions with a canonical one like suggested by the authors of the two actions. See https://github.com/marketplace/actions/markdown-link-check and https://github.com/marketplace/actions/github-spellcheck-action for more information.
> [tests only] Use major versions for actions on some tests

- docs/content/developers/release-management.md
I had completely forgotten (and not documented) that updated devcontainer feature for Github Codespaces had to be pushed/published.
Document how publishing happens in the release section.
Note that this should actually be done automatically with a github action like https://github.com/marketplace/actions/dev-container-publish
> [docs] Explain how to push devcontainer feature for GitHub Codespaces

- .editorconfig
Some essential settings are missing and the editor defaults are used instead which could lead to differences with the various editors.
This patch introduces important default settings to avoid differences with the various editors.
> Improve .editorconfig [skip ci]

- docs/content/users/extend/customizing-images.md
- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
* #4727
Revert the feature that allowed using entire project for context
Use `ADD <somefile> /var/tmp` in a custom .ddev/web-build/Dockerfile. It should get added.
Use `ADD .ddev/web-build/<somefile /var/tmp` - it should fail.
The customizations to tests that were added to that feature were removed.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4728"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert full-project Dockerfile context, fixes #4727

- docs/content/users/install/performance.md
- pkg/ddevapp/config.go
- pkg/ddevapp/mutagen_config_assets/mutagen.yml
* #4721 
`ddev pull platform` and probably other things are broken with mutagen enabled on DDEV v1.21.5.
Bind-mount the .downloads directory.
Note that this isn't working quite right on linux.
I haven't sorted out how to do this better. It would be better if we added a mutagen-based TestPullPlatform, etc.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4723"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure the .ddev/.downloads directory is available, even on mutagen, fixes #4721

- pkg/globalconfig/global_config.go
* #4727 
@mkalkbrenner reports that his project is super slow to start (the docker build phase takes forever) in a particular project with mounted files, and it only happens with docker-compose versions after 2.15.1.
Go to docker-compose 2.15.1 for now.
We need to find out why docker-compose 2.16.0 is a problem, so we'll have to have a reproduction scenario, and we'll have to `git bisect` the docker-compose build to do a reasonable bug report for them.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4734"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change docker-compose to v2.15.1 for problems in #4727

- .github/workflows/tests.yml
- pkg/ddevapp/providerPantheon_test.go
TestPantheonPull and related Pantheon tests are failing, apparently due to bad SSH key
* Remove stray quote
* Give more information at failure time in test.
> [tests only] TestPantheonPull: Remove stray quote, give more info

- docs/content/index.md
- docs/content/users/usage/faq.md
A few minor things about this page amount to cruft:
1. The “Gitpod and GitHub Codespaces” tab requires horizontal paging when it doesn’t need to.
2. The macOS requirements instruct the reader to enable Mutagen, which is neither a requirement nor anything they have to install. (I brought that up [here](https://github.com/ddev/ddev/pull/4694#discussion_r1125190704) but I think that got lost.)
3. The macOS version requirement applies to both Colima and Docker Desktop, so calling them both out is redundant.
1. Whittles the tab name down to “Gitpod & Codespaces”, which fits great and is more consistent with the [DDEV Installation](https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/) page.
2. Removes the Mutagen comment/instruction from requirements. It’s an explicit step in …
> [docs] Requirements: reduce tab width, eliminate redundancy

- docs/content/users/install/performance.md
This is a late followup review of #4723, to “run” commands and make sure the summarize+explain list formatting is consistent.
It also adds `<br>` elements, since the deliberate two-space line breaks (`  `) are stripped out after #4712—which is still an improvement since so many docs PRs get snagged on whitespace issues. I’m positive I have more deliberate line breaks scattered around that will get removed, but nobody will be injured.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--4739.org.readthedocs.build/en/4739/users/install/performance/).
n/a
- #4723
- #4712
n/a
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4739"><img …
> [docs] Fix formatting and phrasing

- docs/content/users/install/ddev-installation.md
- docs/content/users/usage/commands.md
- docs/content/users/usage/faq.md
I realized looking at #4722 that a shorter install script URL would be easier to read. It’s long enough that it gets cut off and adding line breaks doesn’t solve the problem; the second example can’t illustrate usage until you’ve scrolled horizontally:
This shortens it to rely on a 302 redirect from ddev.com, which functions exactly the same:
This _only_ changes examples using `curl -fsSL`, because I haven’t tested others in the docs (PowerShell) and don’t want to break anything.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--4738.org.readthedocs.build/en/4738/users/install/ddev-installation/).
n/a
Not an issue, but supported by [this …
> [docs] Shorten install script URL

- .gitpod.yml
Standard post-release maintenance - bump gitpod.yml
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4737"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump .gitpod.yml to 20230310 [skip ci]

- .spellcheckwordlist.txt
- docs/content/users/extend/customization-extendibility.md
It wasn't clear to me that a services file could _only_ modify the web service, without declaring an additional container to run. When I first started trying to figure this out, I looked on this page so it's where I've added the new docs.
A new section on exposing non-HTTP ports.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4736"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Document exposing additional non-HTTP ports on web

- cmd/ddev/cmd/scripts/test_ddev.sh
- docs/content/users/extend/custom-commands.md
@JurriaanK found that `ddev debug test` had unpredictable and incorrect results when run in a subdirectory of a project.
Don't allow it to run unless in root of project.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4743"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> `ddev debug test` should not try to work in subdir of project [skip ci]

- docs/content/users/extend/custom-commands.md
ExecRaw started causing spellcheck trouble. I probably pulled something when tests hadn't finished.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix up ExecRaw spellcheck trouble

- .spellcheckwordlist.txt
- docs/content/users/extend/custom-commands.md
* https://github.com/ddev/ddev/pull/4744#discussion_r1133308470
ExecRaw was done differently than everything else on the section.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4746"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Use standard notation for ExecRaw

- docs/content/users/extend/additional-services.md
Noticed a tip callout that was visually broken:
The git blame identifies _me_ as the culprit, so it’s unrelated to the more recent whitespace issues.
This indents the text so the tip appears like it’s supposed to:
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect [the automatic build](https://ddev--4751.org.readthedocs.build/en/4751/users/extend/additional-services/).
n/a
n/a
n/a
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4751"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix empty tip in additional services/add-ons

- docs/content/users/usage/cli.md
Changes `without touching to your code` -> `without touching your code`
Simple grammatical typo
Removes unnecessary word "to"
n/a
n/a
Documentation only
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4756"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix typo "without touching to your code" -> "without touching your code"

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
* #4189 
* #1999
* https://github.com/drush-ops/drush/issues/4979
We've been unable to use latest drush8 for quite some time due to that issue.
Drush 8.4.12 hopes to solve the issue.
Use drush in a Drupal 7 project. Review the previous issues.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4754"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump drush8 to 8.4.12, fixes #4189

- docs/content/users/extend/customization-extendibility.md
This example says both services would be exposed on port 4000
Correct small typo
n/a
n/a
n/a
n/a
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4761"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Typo in port numbers in example

- docs/content/users/usage/faq.md
* It wasn't really clear where to put the `docker-compose.communicate.yaml` file directly
* Fixed the syntax of the example, it had wrong indentation
* Added a bit more context
* Fixed the indentation
- None, as this is for the docs
- None, as this is for the docs
- None, I fixed this as I saw it
- None, as this is for the docs
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4757"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Adjusted the FAQ 'communication between projects faq'

- .editorconfig
- .github/workflows/docscheck.yml
- docs/content/developers/building-contributing.md
- docs/content/developers/buildkite-testmachine-setup.md
- docs/content/developers/release-management.md
- docs/content/developers/writing-style-guide.md
- docs/content/users/configuration/hooks.md
- docs/content/users/debugging-profiling/blackfire-profiling.md
- docs/content/users/debugging-profiling/step-debugging.md
- docs/content/users/extend/in-container-configuration.md
- docs/content/users/install/ddev-installation.md
- docs/content/users/install/docker-installation.md
- docs/content/users/install/performance.md
- docs/content/users/install/shell-completion.md
- docs/content/users/project.md
- docs/content/users/providers/platform.md
- docs/content/users/quickstart.md
- docs/content/users/topics/hosting.md
- docs/content/users/usage/architecture.md
- docs/content/users/usage/cms-settings.md
- docs/content/users/usage/database-management.md
- docs/content/users/usage/developer-tools.md
- docs/content/users/usage/troubleshooting.md
In 
* #4712 
@gilbertsoft made some very reasonable improvements to the .editorconfig, but they've been causing some trouble in a number of places.
* Embedded yaml in codeblocks in yaml gets 4-space (and ugly) indentation
* Lots of failures are getting shown with existing stuff that gets edited and the editor magically removes trailing spaces.
* Don't force the 4-space indentation (remove indent_size)
* Clean up trailing spaces in our Markdown files so the current restriction about trailing spaces doesn't trigger on Markdown at least. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4745"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert indentation specifier from editorconfig settings

- docs/content/users/install/ddev-installation.md
- scripts/install_ddev.sh
* #4747
1. If /usr/local/bin doesn't exist, the install_ddev.sh fails. In M1 macs, that directory doesn't necessarily exist, although it has always existed almost everywhere else.
2. The docs may not make clear that the script installation is an *alternate* 
* Add creation of /usr/local/bin to the script
* Minor tweak to install doc
1. Temporarily remove /usr/local/bin, `sudo mv /usr/local/bin /usr/local/bin.bak`
2. Run the updated script from this PR, 
`curl -fsSL https://raw.githubusercontent.com/rfay/ddev/90f9d72e02591df1fd1fcc75fa5401bad6aa4113/scripts/install_ddev.sh
| bash `
3. Put your system back together, `sudo mv /usr/local/bin /usr/local/bin.test && sudo mv /usr/local/bin.bak /usr/local/bin`
No testing is done on this.
<a …
> Improve install_ddev.sh by making it create /usr/local/bin, replaces #4747 [skip ci]

- pkg/ddevapp/router_Dockerfile_template
* #4758 
When adding Traefik plugins to the static configuration, Traefik will automatically download the files of the plugin in the working directory. 
Switching the `WORKDIR` of the router Docker image will prevent adding unwanted YAML files to the dynamic configuration directory, which would be loaded automatically by Traefik.
See https://github.com/ddev/ddev/issues/4758. 
It changes the `WORKDIR` of the Traefik based router image. 
1. Add a plugin to Traefik in its static configuration `~/.ddev/traefik/static_config.yaml`:
```yaml
experimental:
plugins:
htransformation:
moduleName: "github.com/tomMoulard/htransformation"
version: "v0.2.7"
```
2. Restart the ddev-router container
3. Traefik **does not** try to load YAML files from the plugin as dynamic configuration
4. Traefik works …
> Fix Traefik trying to load Traefik plugin files as dynamic configurations, fixes #4758

- pkg/exec/exec.go
Tangentially resolves #4717.
As discussed on https://discord.com/channels/664580571770388500/1082435430479306803/1082435430479306803 instead of having an add on define dependencies, the add-on can already install those from post-install actions.
This PR only adds an environment variable so that the running ddev binary can be used in any ddev host Command  (also pre/post install actions) through an env var.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4724"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Append DDEV_EXECUTABLE to the Host commands environment

- pkg/ddevapp/provider.go
Environment variables are exported inline with no delimiter between one value and the next variable.
Encloses variable values with quotes to note beginning and end of values.
- Create a custom provider configuration
```
environment_variables:
test: "variable with spaces"
auth_command:
command: |
set -eu -o pipefail
db_pull_command:
command: |
set -eu -o pipefail
echo ${test}
files_pull_command:
command: |
set -eu -o pipefail
echo ${test}
service: web
```
- Add a variable (as above) which contains a space in the value
- Echo the variable in a command (as above)
- Run with `ddev pull test -y --skip-import`
The complete string should be available in the bash commands
```
Authenticating... 
Obtaining database... 
variable with spaces
Skipping database import. 
Obtaining files... 
variable …
```
> Enclose exported environment variable values with quotes, fixes #3499

- .spellcheckwordlist.txt
- docs/content/users/quickstart.md
Add a quickstart for [ExpressionEngine](https://expressionengine.com/)
Shows zipfile and git checkout approaches.
Try it out
* We need to find a better way to add more quickstarts. Django4 is soon to come, and the tab approach just doesn't scale.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4777"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Quickstart for ExpressionEngine

- docs/content/users/quickstart.md
- Add elasticsearch engine to options
- Define elasticsearch port
- Disable depending new Magento_AdminAdobeImsTwoFactorAuth module
See issue: #4762 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4767"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix Magento 2 quickstart for Magento 2.4.6, fixes #4762

- docs/content/users/debugging-profiling/step-debugging.md
Code block missing closing "`".
Added missing closing "`".
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4801"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix code block (missing closing mark)

- docs/content/users/debugging-profiling/blackfire-profiling.md
Here's how steps numbers section looks a bit broken:
Well, it looks now as initended.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4806"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix markdown in profiling doc page

- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal7/settings.ddev.php
- pkg/ddevapp/drupal/drupal8/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
This change updates the settings to have the system logging error level set to verbose to ensure errors are a bit more clear.
By default, Drupal set up through DDEV will not provide clear messages when an error occurs.
This changes the error_level to be verbose so Drupal reports something a bit more clear.
Install Drupal with DDEV. Run it.
No automated testing needed here.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4689"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Drupal: Enable verbose error logging

- pkg/fileutil/embed.go
Users have occasionally reported having empty shell commands like `launch` on their system (~/.ddev/commands/host/launch). It's unknown how this happens, perhaps no space available.
https://stackoverflow.com/questions/75801233/problems-with-ddev-after-upgrade-to-1-21-6-launch-file-empty
On empty file, overwrite it. This doesn't solve the original problem, but will fix on `ddev restart` if there's available disk space
`rm ~/.ddev/commands/host/launch && touch ~/.ddev/commands/host/launch && ddev start` - `ddev launch` should work again.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4775"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Overwrite copies of embedded files if they're empty on target filesystem

- docs/content/users/install/docker-installation.md
When switching from Docker Desktop and installing colima and docker via homebrew, following this documentation here, I ran into the following issue when running `ddev start` on my project.
```
', stderr='failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: docker-credential-desktop resolves to executable in current directory (./docker-credential-desktop), out: ``' 
```
DDev was still looking for a docker desktop file, despite it being fully uninstalled.
This PR updates documentation to provide a configuration tip when migrating from Docker Desktop to Colima. 
The `.docker/config.json` should to be updated to:
```
{
"auths": {},
"credsStore": …
```
> [docs] Update credsStore to Colima to avoid DDEV start errors

- .spellcheckwordlist.txt
- cmd/ddev/cmd/share.go
- docs/content/users/configuration/config.md
- docs/content/users/topics/sharing.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/templates.go
The documentation includes an [example](https://ddev.readthedocs.io/en/stable/users/usage/commands/#share) for ngrok:
```bash
ddev share --basic-auth username:pass1234
```
The same example is provided by the `ddev help` command:
```bash
$ ddev help share
Use "ddev share" or add on extra ngrok commands, like "ddev share --basic-auth username:pass1234". Although a few ngrok commands are supported directly, any ngrok flag can be added in the ngrok_args section of .ddev/config.yaml. Requires a free or paid account on ngrok.com; use the "ngrok authtoken" command to set up ngrok.
Usage:
ddev share [project] [flags]
Examples:
ddev share
ddev share --basic-auth username:pass1234
ddev share myproject
Flags:
-h, --help               help for share
--subdomain string   ngrok --subdomain argument, as …
```
> Add basic-auth flag to ngrok

- docs/content/users/install/ddev-installation.md
- scripts/install_ddev_wsl2_docker_desktop.ps1
- scripts/install_ddev_wsl2_docker_inside.ps1
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4731"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> WSL2 installation: Escaped asterisks while echoing ddev and docker sources as it list directory contents without it [skip ci]

- pkg/ddevapp/backdrop.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/drupal/backdrop/settings.ddev.php
- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal7/settings.ddev.php
- pkg/ddevapp/drupal/drupal8/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
In Drupal settings.ddev.php we set the database prefix to ''. This overrides what might be set in the settings.php, and there's no need for it.
Stop setting the database prefix at all.
Set database prefix in settings.php before the include of settings.ddev.php. See if things work with a project that has a prefix in the db.
No changes.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4781"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't override database prefix in settings.ddev.php

- docs/content/users/quickstart.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/laravel.go
Laravel 10 requires PHP 8.1:
* #4651 
* Change default version in code
* For now, change docs to show explicit --php-version
* Test with laravel
* Test quickstart
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4653"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set laravel PHP default to 8.1, fixes #4651

- .circleci/config.yml
CircleCI arm64 test has been failing on TestDdevExec
See if Ubuntu 22.04 fixes it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4810"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Fix broken TestDdevExec on CircleCI arm64

- cmd/ddev/cmd/list.go
- cmd/ddev/cmd/list_test.go
- docs/content/users/usage/commands.md
- pkg/ddevapp/list.go
- pkg/ddevapp/list_test.go
- pkg/ddevapp/project.go
As a user of many different local installed ddev projects I want to filter the `ddev list` output. Currently we have the `only-active` flag available.
Additionally we could filter by project type.
The PR restructures the parameters of the list command into a struct. This prepares the command to get additional filters in the future like tags.
Run the `ddev list` command with new filter option `-t` or `--type` and set a project type
Example: `ddev list -t php` or `ddev list -t magento2`.
The filter can be combined with active only filter. 
`ddev list -A -t php`
I added a simple test which filters by a not existing type. Currently I am looking for a good way to test also the project type filter by an existing type.
<a href="https://gitpod.io/#https://github.com/drud/ddev/pull/4613"><img …
> project type filter for `ddev list` command (`ddev list --type=`)

- .goreleaser.yml
Working on the new goreleaser stuff in 
* https://github.com/ddev/ddev/pull/4808
I seem to have ended up with a space in the middle of the filename in the homebrew stuff. This fixes that.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4815"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [release] Fix broken tarball filename [skip ci]

- cmd/ddev/cmd/debug-migrate-database_test.go
- cmd/ddev/cmd/testdata/TestDebugMigrateDatabase/users.sql
- pkg/ddevapp/config.go
* #4800
Don't delete the .ddev/.downloads directory on start
Just use `ddev debug migrate-database`
Added TestDebugMigrateDatabase
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4818"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix broken ddev debug migrate-database, fixes #4800

- docs/content/users/extend/in-container-configuration.md
Fixing a missing dot in `ln -s ~/.ssh ~/.ddev/homeadditions/ssh` (should be `.ssh`).
-mike
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4823"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixed minor bug in symlink creation code.

- docs/content/developers/release-management.md
Our setup for apt/yum package management wasn't adequately explained.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4825"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Minor docs for apt/yum package management

- .buildkite/macos-m1.yml
- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/get_test.go
* #4795 
Make it properly handle pages... and start with a larger number
`ddev get --list --all`
* Changed to only run ddev TestCmdGet tests on mac M1, since Github always breaks tests when we run multiple places
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4819"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ddev get --list --all should return all repos, fixes #4795

- README.md
This adds a [Repobeats](https://repobeats.axiom.co) overview to DDEV’s readme to transparently demonstrate the project activity that I think is one of its strengths. It keeps itself up to date and acknowledges contributors.
I deliberately placed it in the _Contributing_ section because it’s relevant there, and I don’t think it should live at the top and distract from a description of what DDEV is that’s for everyone.
> [docs] Add Axiom Repobeats contributor overview

- pkg/ddevapp/laravel.go
Laravel requires additional configuration to work with DDEV's Mailhog.
With current setup, sending an email results in the following exception:
```php
Symfony\Component\Mailer\Exception\TransportException  Connection could not be established with host "mailpit:1025": stream_socket_client(): php_network_getaddresses: getaddrinfo for mailpit failed: Temporary failure in name resolution.
```
This PR add `MAIL_HOST=127.0.0.1` to the project's `.env`.
1. Follow quickstart guide for a Laravel project. You should see the Laravel "Welcome page"
1. Launch Mailhog to watch for email:
```shell
ddev launch -m
```
1. Enter "tinker mode" by typing the following command:
```shell
ddev artisan tinker
```
1. Copy and past (or type) the following command into "tinker mode". This will attempt to send an …
> Automate Laravel MailHog capture configuration

- winpkg/ddev.nsi
The windows installer had some awkward language in it.
Fix it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4839"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix bad verbiage in windows installer [skip ci]

- pkg/testcommon/testcommon_test.go
Experimental skip of TestGetLocalHTTPResponse on Windows
TestGetLocalHTTPResponse is failing always on Windows NFS, starting Apr 2023. If that's the only one that fails, just skip it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Experimental skip of TestGetLocalHTTPResponse on Windows

- containers/ddev-dbserver/Dockerfile
- pkg/ddevapp/config.go
- pkg/versionconstants/versionconstants.go
Debian stretch (9) is even more obsolete now that they've turned off all the repos. But we have old DB images (mysql, mariadb, postgres) that are based on stretch.
Update the /etc/apt/sources.list to be 
`deb http://archive.debian.org/debian/ stretch main contrib non-free`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4846"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Avoid using old stretch apt repos because it breaks all builds

- README.md
Related to [#44](https://github.com/ddev/ddev.com-front-end/issues/44) and [#46](https://github.com/ddev/ddev.com-front-end/issues/46), sponsors could be promoted with more care in several places.
This replaces individual sponsor logos in the readme with a programmatically precomposed SVG, so all logos are pulled from the ddev.com front end and hopefully easier to maintain.
GitHub doesn’t facilitate linking from embedded SVGs, but clicking on it will directly open the asset where the links do work.
While the dark mode presentation isn’t exactly stunning, it’s at least more uniform as a result:
Examine the readme [over here](https://github.com/mattstein/ddev/tree/docs/readme-sponsors-svg#wonderful-sponsors), I guess.
n/a
- https://github.com/ddev/ddev.com-front-end/issues/44
- …
> [docs] Add precomposed sponsor logos to readme [skip ci]

- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/debug-nfsmount.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/mutagen_test.go
- pkg/ddevapp/poweroff.go
- pkg/ddevapp/router.go
- pkg/ddevapp/snapshot.go
- pkg/ddevapp/ssh_auth.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/ddevapp/testdata/TestMutagenConfigChange/mutagen.yml
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/fileutil/file_hash.go
- pkg/fileutil/file_hash_test.go
- pkg/testcommon/testcommon.go
* #4753 
A sync session can outlive the mutagen.yml file, as it's not checked again after creation
* Add a label to the mutagen sync session with the SHA1 hash of the existing mutagen.yml
* On start, check to see if the hash remains the same
* If not, recreate the sync session (and volume)
Added TestMutagenConfigChange and TestFileHash
* It may be wise for people to `ddev mutagen reset` on the new release. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4837"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Recreate mutagen sync session when mutagen.yml changes, fixes #4753

- docs/content/users/debugging-profiling/step-debugging.md
- pkg/dockerutil/dockerutils.go
* #4803 
* https://github.com/ddev/ddev/issues/3772#issuecomment-1505090962
Capture information on how host.docker.internal is generated; To see where it comes from, `export DDEV_DEBUG=true` and then `ddev start`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4813"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add debugging output to GetHostDockerInternalIP() for #4803

- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/conf.d/supervisor.conf
- pkg/ddevapp/ddevapp_test.go
- pkg/versionconstants/versionconstants.go
In 
* https://github.com/ddev/ddev/pull/4830
PHP_IDE_CONFIG got set to an empty value for php-fpm, breaking PhpStorm, which seems not to treat that the same as a nonexistent value. PhpStorm complains about not being able to parse it.
Make sure that PHP_IDE_CONFIG is unset for php-fpm, as it always has been
Just use xdebug!
Improve TestDdevXdebugEnabled()
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4851"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> PHP_IDE_CONFIG was set to empty instead of unset, breaking PhpStorm

- .spellcheckwordlist.txt
- docs/content/users/extend/custom-compose-files.md
It's obscure, but some 3rd party services need to trust the mkcert CA/Certificate
Add docs on how to do it.
Read it and weep.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4853"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Provide instructions for 3rd party services to trust mkcert

- pkg/ddevapp/drupal/backdrop/settings.php
- pkg/ddevapp/drupal/drupal10/settings.php
- pkg/ddevapp/drupal/drupal6/settings.php
- pkg/ddevapp/drupal/drupal7/settings.php
- pkg/ddevapp/drupal/drupal8/settings.php
- pkg/ddevapp/drupal/drupal9/settings.php
- pkg/ddevapp/wordpress/wp-config.php
This solves https://github.com/ddev/ddev/issues/4838
It inverts the logic, thus on non-ddev environments, it will not read the disk unneeded.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4843"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> settings.php - Invert logic to reduce disk reads if non-ddev environment

- pkg/ddevapp/typo3.go
If composer_root is set for TYPO3 v11 or lower the settings path is wrong calculated. TYPO3 v12 or higher is not affected.
The correct path calculated from the docroot is now used and composer_root is ignored for TYPO3 v11 or lower.
Setup a TYPO3 v11 or lower and set the composer_root. See linked issue for more information.
Fixes 
* #4545
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4835"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix wrong TYPO3 settings path if composer_root is used, fixes #4545

- cmd/ddev/cmd/start_test.go
- containers/ddev-webserver/Dockerfile
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/apache.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/gunicorn.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/php-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-fpm.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-gunicorn.conf
- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
- pkg/ddevapp/ddevapp_test.go
- pkg/versionconstants/versionconstants.go
We had intermittent failures in automated testing on TestCmdStart.
This seems to have been a result of the unusual behavior in that test: Pause all, then start all.
With the new start.sh setup, this could mean that the container wasn't being started from scratch, so supervisord was possibly already running.
The actual problem we saw was only with webserver_type=apache-fpm; apache2 not starting successfully, perhaps because it hasn't stopped properly.
* `supervisorctl shutdown` at beginning of start.sh
* Use proper graceful termination signal for apache2
Try `ddev start` with apache-fpm, and then `ddev start`.
Try `ddev pause` and `ddev start`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4856"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Shut down supervisord on start in case it's running

- .github/workflows/push-tagged-image.yml
- cmd/ddev/cmd/config.go
- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- docs/content/users/configuration/config.md
- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/config_test.go
- pkg/ddevapp/templates.go
- pkg/nodeps/php_values.go
- pkg/testcommon/testcommon.go
- pkg/versionconstants/versionconstants.go
* #4652 
Changes defaults to use PHP 8.1 for new sites or sites that do not have configuration set for `php_version`.
Fixes https://github.com/ddev/ddev/issues/4652
* https://github.com/ddev/ddev/pull/4653
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4834"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use PHP 8.1 by default, fixes #4652

- docs/content/users/debugging-profiling/blackfire-profiling.md
blackfire.io links were failing regularly in docs links checks.
Seems they have redirected a couple of them.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4869"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix 302 on blackfire.io links

- containers/ddev-webserver/README.md
- docs/content/users/debugging-profiling/blackfire-profiling.md
Links failure in blackfire references in docs
Move more to canonical versions so no redirect happens
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4874"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Try to fix canonical blackfire links

- markdown-link-check.json
In the links check for docs, *blackfire.io* is quite inconsistent, returning a variety of failure or redirect results.
Stop checking those links.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4876"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs][tests] Stop checking blackfire.io since it's inconsistent

- pkg/ddevapp/templates.go
The description in the comments in the config.yaml file misses a notice that `https_port` is mandatory to fill.
Adds this notice to the description.
Fixes https://github.com/ddev/ddev/issues/4864
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> config.yaml comments: Explanation about mandatory https_port field, fixes #4864

- .goreleaser.yml
* #4884 
[`mkcert`](https://archlinux.org/packages/community/x86_64/mkcert/) dependency is missing in the aur package.
This PR adds `mkcert` as a dependency.
This PR does not affect any code
Fixes #4884 
This should not affect anything else
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4887"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> add mkcert to arch dependencies, fixes #4884

- .goreleaser.yml
Follow-up PR for `ddev-edge-bin`
Thanks to @Data5tream for noticing the missing dependency.
Related PR:
- https://github.com/ddev/ddev/pull/4887
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4890"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [aur] Add mkcert dependency to ddev-edge-bin

- docs/content/users/providers/pantheon.md
- pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
- pkg/ddevapp/providerPantheon_test.go
* #4882
It seems that most Pantheon operations don't require ssh, at least the pull ones.
Try it without, get it to pass tests
Try
* `ddev pantheon pull`
* `ddev pantheon push`
Minor changes to TestPantheonPush
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4883"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> See if Pantheon integration can be partially without ssh, fixes #4882

- pkg/ddevapp/traefik.go
See https://discord.com/channels/664580571770388500/1105126065556422737
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4888"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> check for empty HTTP_EXPOSE and HTTPS_EXPOSE env variables (traefik only)

- pkg/ddevapp/config.go
* #4872 
On some unusual umask settings, the /etc/supervisor/conf.d files may have inadequate permissions for the user (same as local user id) running supervisord
chmod 644 the files
`ddev start` with a `web_extra_daemons` setup; `ddev exec ls -l /etc/supervisor/conf.d/*` to verify they're all 644.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4878"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure perms on webextradaemons supervisor conf are correct, fixes #4872

- markdown-link-check.json
The links check for twitter.com/search always fails.
Stop doing it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4892"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Exclude twitter.com/search from link check

- docs/content/developers/writing-style-guide.md
This adds an excellent link to the “avoid just and it’s easy” section of the writing style guide that further describes the problem and potential solutions with that sort of language.
Here’s a direct link to it in the preview build: https://ddev--4903.org.readthedocs.build/en/4903/developers/writing-style-guide/#avoid-just-and-easy
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4903"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add “just simply” link to the writing style guide

- .gitpod.yml
- .gitpod/images/Dockerfile
The base image for use with gitpod got out of date; especially ours didn't have `docker buildx`, whereas the upstream has added it. 
Push new image, use new image.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4906"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update gitpod base to get docker buildx [skip ci]

- containers/ddev-dbserver/Makefile
- docs/content/users/configuration/config.md
- docs/content/users/extend/database-types.md
- pkg/ddevapp/db.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/nodeps/mariadb_values.go
- pkg/nodeps/mariadb_values_darwin_arm64.go
- pkg/nodeps/mariadb_values_linux_arm64.go
- pkg/versionconstants/versionconstants.go
Currently, the latest supported MariaDB Version to 10.8. The newest (LTS) version of MariaDB is 10.11.
Note: In #4894 are comments about only supporting MariaDB LTS Releases, that's why 10.9 and 10.10 are not added.
- Add MariaDB 10.11 to `containers/ddev-dbserver/Makefile`
- Add MariaDB 10.11 to allowed config options
I'm not sure whether there are automated tests for changes like this. If so, I'd of course look into that and adapt them accordingly.
Fixes #4894 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4902"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: add support for MariaDB 10.11 LTS

- pkg/ddevapp/ddevapp_test.go
Since Docker Desktop 4.19.0 we're unable to get successful testing of TestDdevXdebugEnabled on Docker Desktop/WSL2. 
Seems to be related to
* https://github.com/docker/for-win/issues/13463
Disable the test on DD/WSL2 for now.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4910"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Stop testing TestDdevXdebugenabled on Docker Desktop until it works [skip ci]

- cmd/ddev/cmd/mutagen-monitor.go
`ddev mutagen monitor` had some copy pasta in the help.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4909"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix copy pasta in ddev mutagen monitor [skip ci]

- docs/content/users/quickstart.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/craftcms.go
The Craft team is gradually shifting its priority to MySQL support over MariaDB, and would prefer this as the default.
This PR also changes the default PHP version to 8.1. New projects/config can still choose their database driver and PHP version via the `--database` and `--php-version` flags, if the user desires.
MariaDB has slowly drifted away from being a drop-in replacement for MySQL, and this has resulted in some frustration from our community, as well as an increased support burden.
We implemented a new `craftCmsConfigOverrideAction` function that sets the `PHPVersion` and `Database` properties for the current `DdevApp`, using predefined constants. This function is assigned to the project type’s `configOverrideAction` so it runs during setup.
The current recommended `config` …
> Update `craftcms` project type defaults

- pkg/ddevapp/providerPlatform_test.go
The Platform.sh project that we were previously using for `TestPullPlatform` and `TestPushPlatform` is on a region (EU-3) 
that is not considered stable (it's a testing platform) and it's more expensive and higher CO2 than the CA-1  region
I moved the test project to CA-1, and gave the user that has access to the old one access to the new project.
This changes the project used by the test.
> [tests only] Use new platform.sh target site for testing

- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/get_test.go
- docs/content/users/extend/additional-services.md
- docs/content/users/usage/architecture.md
- docs/content/users/usage/cli.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/list_test.go
* #3555 
* #3919 
Adds versioning, get by version, and removal
Adds TestCmdGetInstalled()
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4891"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Introduce versioned addons and add-on removal, fixes #3555, fixes #3919

- pkg/dockerutil/dockerutils_test.go
In a recent update the logic was changed in the testMain of dockerutils_test; it may or may not have to clean up the test container, but it should use the correct test container. 
I was seeing this output sometimes in tests:
`[580](https://github.com/ddev/ddev/actions/runs/4990360031/jobs/8935458261?pr=4866#step:9:581)time="2023-05-16T09:50:34Z" level=error msg="-- FAIL: dockerutils_test failed to remove test container: No such container: 3578dd127b77350566d800ec43c2ac63485d8ebedcbccb5bfa4f3ce390e15bb6"`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4916"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] dockerutils_test TestMain should only delete existing test container

- docs/content/users/install/ddev-installation.md
Solves #4912.
The mkcert command is placed at the bottom, under the Arch Linux section, but it is a requirement for all Linux installations. 
It moves the mkcert info to the beginning of the Linux section, since it is a requirement for all Linux installations. Repeating it under each Linux distro would break with the DRY principle.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4914"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Move mkcert to the top for Linux [skip ci]

- pkg/ddevapp/ddevapp.go
Per https://docs.docker.com/compose/environment-variables/envvars/#unsupported-in-compose-v2 COMPOSE_DOCKER_CLI_BUILD is not supported in compose v2
Remove it
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4921"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove obsolete docker compose COMPOSE_* env vars

- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/root.go
- cmd/ddev/main.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/container_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/hardened_test.go
- pkg/ddevapp/hooks_test.go
- pkg/ddevapp/instrumentation.go
- pkg/ddevapp/instrumentation_test.go
- pkg/ddevapp/list.go
- pkg/ddevapp/mutagen_test.go
- pkg/ddevapp/nodejs_test.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/snapshot_test.go
- pkg/ddevapp/ssh_auth_test.go
- pkg/dockerutil/dockerutils.go
- pkg/util/debug.go
- pkg/util/utils.go
The util.TimeTrack() function has currently a parameter start which was always set to time.Now() and can therefor set directly in the function instead which will reduce the impact a bit and simplify the usage. Also in many cases the name parameter was manually set to the calling function name which is also error prone.
With this patch, the TimeTrack functionallity was moved to a dedicated file in the same package and two functions are now available, one without parameters where the calling function name is retrieved with the help of the runtime package and a second with a name parameter to individually set a name e.g. used for tests. Source documentation was extended to also show a simpler one line usage which is apropriate in most cases. Also some minor optimization are done like …
> Simplify and optimize util.TimeTrack

- .buildkite/wsl2-docker-desktop.yml
WSL2 Docker Desktop crashes so often that it doesn't make sense to run it for every PR/commit. Let's just run it against master. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4930"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Only run wsl2-docker-desktop on master

- docs/content/users/configuration/config.md
- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/config.go
* #4893 
Most teams want `config.*.yaml` committed, and add-ons reinforce this.
Start gitignoring *only* `config.local.yaml`
`ddev config` and `ddev start` a project. Get an add-on. `git status` should show `config.*.yaml`.
This needs release note about the change.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4923"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Stop gitignoring most config.*.yaml, fixes #4893

- pkg/ddevapp/ddevapp.go
- pkg/globalconfig/global_config.go
Time to catch up to current docker-compose version
Bump to composer 2.18.1
See also
* https://github.com/ddev/ddev/issues/4727
Use it. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4917"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump docker-compose to v2.18.1

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
Perhaps docker 24.0.0/24.0.1 has a bit different behavior wrt exiting containers; this may be timing related also.
TestDdevExec was failing on wsl2-docker-inside, perhaps because of new behavior of Docker 24.0.0
Automated testing should do the job.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4935"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [mostly tests only] TestDdevExec was failing on WSL2-docker-inside

- docs/content/users/quickstart.md
* https://github.com/ddev/ddev/issues/4650
docs: Folks on Craft CMS 3 haven't really benefited from the explicit project type `craftcms`. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4925"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Mention that `craftcms` is best with Craft CMS 4+

- docs/content/users/install/docker-installation.md
The `--vm-type` arg doesn't work on Colima on OSs before Ventura. 
Say so.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4937"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Mention not to use --vm-type with Colima on pre-Ventura

- containers/ddev-dbserver/files/healthcheck.sh
- pkg/ddevapp/drupal.go
- pkg/versionconstants/versionconstants.go
* #4933
* https://github.com/ddev/ddev/issues/3748 (Note that I used the github actions builder to push the db image; it will be interesting to see if perhaps this problem is resolved; there is an automated test to catch it, but we should look.)
It seems that mysql:5.7 takes a little longer to get the server started, and this may result in different results on different platforms. 
* The db container's healthcheck should have been saying "not ready" during snapshot restore, instead it was returning 0 implying healthy. 
* We weren't capturing the stderr properly, and having it helps a lot. 
* On mysql you have to have root privs to do the required `SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;`
* Using a Drupal9+ project, with mysql:5.7 and mysql:8.0 databases, `ddev snapshot && …
> mysql:5.7 snapshot restore can take longer, fixes #4933

- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/get_test.go
- cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/extra/has-ddev-generated.txt
- cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/extra/no-ddev-generated.txt
- cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
- docs/content/users/extend/additional-services.md
- pkg/fileutil/files.go
* #4253 
* Expand directories found in both ProjectFiles and GlobalFiles before using them, so we process only files
* Improve testing to cover this
Use a sample add-on that has a directory in it; make sure #ddev-generated is respected in files in that directory.
TestCmdGetComplex is updated to handle this situation.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4932"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Expand files before processing so we can check #ddev-generated, fixes #4253

- .buildkite/test.sh
- pkg/versionconstants/versionconstants.go
Mutagen has moved along since last we bumped it. Let's see how it does with 0.17.1
 
<br class="Apple-interchange-newline">
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4939"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump mutagen to 0.17.1

- cmd/ddev/cmd/debug-refresh.go
- docs/content/users/extend/customizing-images.md
- docs/content/users/usage/troubleshooting.md
- pkg/ddevapp/ddevapp.go
- pkg/util/utils.go
People sometimes struggle with debugging .web-build/Dockerfile.* items because it doesn't give good output unless there's an error. 
* With `export DDEV_VERBOSE=true` `ddev start` shows the output of the build stage and also the full output of the "up" stage, including start.sh, etc.
* `ddev debug refresh` always shows the output of the build stage. 
* Added `DDEV_VERBOSE=true` to the troubleshooting.md page. 
* Added unconditional timestamp to util.Debug() output
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4919"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Separate "build" from "up" stages in DDEV Start()

- .buildkite/test.sh
In test.sh (buildkite) we need to make sure the mutagen daemon has been stopped. 
Allow `|| true` after trying to stop it. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4943"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Make sure to kill mutagen daemon

- .github/workflows/colima-tests.yml
- .github/workflows/macos-colima-setup.sh
* Colima should be running on macOS 13
* Colima needs upgrade to 0.5.5 and cache clean
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4951"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Use macOS 13 for colima, update colima

- docs/content/users/extend/customizing-images.md
- docs/content/users/usage/troubleshooting.md
I didn’t get a chance to review 
* #4919 before it merged and there are a few opportunities to improve the docs that came with it:
- It’s best to reiterate in every case, provided it doesn’t interrupt the reading flow, that commands are meant to be run. This is especially true when someone’s troubleshooting and we want them to be successful without knowing [their technical comfort level](https://ddev.readthedocs.io/en/stable/developers/writing-style-guide/#beginner-friendly-expert-compatible) with what’s going on.
- A callout was added with a heading that [didn’t summarize the contents](https://ddev.readthedocs.io/en/stable/developers/writing-style-guide/#use-tips) as much as label them, and it gave excessive emphasis to something that...
- a) From its own language, is less useful to …
> [docs] Debug environment variable suggestions

- docs/content/users/usage/commands.md
When `ddev pull --environment=` was added, it didn't get into docs
Add to docs
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4945"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Improve `ddev pull` flags description with `--environment`

- pkg/versionconstants/versionconstants.go
Traefik is now at 2.10, so we might as well use it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4946"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump traefik to 2.10

- cmd/ddev/cmd/get.go
- cmd/ddev/cmd/get_test.go
- cmd/ddev/cmd/testdata/TestCmdGetDependencies/dependency_recipe/install.yaml
- cmd/ddev/cmd/testdata/TestCmdGetDependencies/depender_recipe/install.yaml
- docs/content/users/extend/additional-services.md
* #4717 
* Add `dependencies` key to install.yaml
* On `ddev get`, if the target add-on requires a dependency, check before allowing get (and ask for dependency to be installed if not)
* On `ddev get --remove` explain to people that the dependency *might* need to be removed.
Try out these steps. You'll likely want a manually checked out add-on to add `dependencies` to.
Added TestCmdGetDependencies
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4941"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow add-ons to declare dependencies, fixes #4717

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- pkg/ddevapp/ddevapp.go
- pkg/versionconstants/versionconstants.go
Related to
* #4942
* .ddev/mutagen/mutagen.yml needs to be created earlier to avoid a spurious warning in some cases. 
I tried to fix the double-chown in start.sh here but it failed mysteriously, but only on github-linux-non-traefik. So that's pretty interesting. But I reverted the change and left the double-chown in there. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4944"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix problems with mutagen.yml being generated too late

- pkg/ddevapp/config_test.go
- pkg/ddevapp/traefik_test.go
* #4875 
Trying to make tests work on Windows Mutagen again.
* It seems that for Windows, the app.Start() didn't cause a mutagen flush in some situations. Adding the flush seems to make TestPHPOverrides work OK.
* Turned off macos-nfs for PRs, which will save some testing resources. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4968"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Fix TestPHPOverrides for Windows Mutagen, fixes #4875

- docs/content/users/extend/customizing-images.md
Although `$username` is provided and documented, it's not shown the many ways we can use it. Add an example.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4969"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Dockerfile Tutorial on installing into ~/.cache

- .goreleaser.yml
I was trying to understand why the fish completions were not working and this was the reason, it needs to be suffixed with .fish.
https://fishshell.com/docs/current/completions.html#where-to-put-completions
Duplicate of from https://github.com/ddev/homebrew-ddev/pull/48.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4973"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Proper fish completion file extension

- docs/content/developers/release-management.md
I couldn't figure out where the (expired) package management PAT was used. But it was already documented.
Give more context about it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4971"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Show details about GitHub PAT for package management

- .circleci/config.yml
We don't really need to run full linux/arm64 build on CircleCI for every PR. We can save some money by not doing that.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4984"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Only run circleci on master branch updates, not PRs

- pkg/ddevapp/ddevapp_test.go
There maybe additional debug output which currently will break the test. This change makes the test more stable by only verifying the expected string is printed somewhere in the output and does not longer expect to be found at a predefined position.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4987"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Make TestHostDBPort more stable

- docs/content/users/usage/cms-settings.md
Rendering of main branch was not working yesterday so we had to switch to latest version. Because it is working again we finally can switch to main branch like discussed in #4988.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4992"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Change link to TYPO3 docs to point to main

- docs/content/users/extend/custom-commands.md
spf13/cobra moved their docs around in https://github.com/spf13/cobra/commit/dcb405a9399ed307eaa0e50f5cb1c290c8979dd4
This broke our link checking. 
Fix it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5004"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [docs] Fix moved link in spf13/cobra

- pkg/ddevapp/ddevapp_test.go
@gilbertsoft debugged the routine failures in TestDdevFullSiteSetup and found 
* https://github.com/ddev/test-flask-sayhello/pull/1
* This moves to https://github.com/ddev/test-flask-sayhello/releases/tag/v1.0.1, which includes that change.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5008"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [tests only] Fix TestDdevFullSiteSetup flask test

- cmd/ddev/cmd/a.go
- cmd/ddev/cmd/config-global_test.go
- cmd/ddev/cmd/describe_test.go
- cmd/ddev/cmd/root_test.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/dockerutil/docker_compose_version_test.go
- pkg/dockerutil/dockerutils_test.go
- pkg/globalconfig/global_config.go
- pkg/globalconfig/global_config_test.go
- pkg/globalconfig/values.go
- pkg/testcommon/testcommon_test.go
@gilbertsoft pointed out elsewhere that globalconfig.DdevGlobalConfig initialization should be encapsulated in a New() function. 
Do it and work it all out. 
This one ends up being a pre-requisite for some other PRs, especially 
* https://github.com/ddev/ddev/pull/4983
* https://github.com/ddev/ddev/pull/5006
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5007"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Implement DdevGlobalConfig initialization in one place

- docs/content/users/configuration/config.md
- pkg/globalconfig/global_config.go
In 
* https://github.com/ddev/ddev/pull/5007
the logic that forces a reasonable value for InternetDetectionTimeout was lost. And many of the test runners had that value set to 0, so we got lots of failures, for example TestEnvironmentVariables in https://buildkite.com/ddev/ddev-macos-amd64-mutagen/builds/4489#0188ef4b-872a-4bc7-a6b0-cbddbc269697
* Add the logic back in there
* Fix docs in global config comments and also the docs themselves, which were inaccurate.
* Look around for global_config.yaml that has `internet_detection_timeout_ms: 0` - if that is happening somewhere we have another bug.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5017"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make sure InternetDetectiontimeout is a reasonable value

- cmd/ddev/cmd/debug-instrumentation-flush.go
- pkg/amplitude/amplitude.go
- pkg/amplitude/loggers/ddev_logger.go
- pkg/amplitude/loggers/ddev_logger_test.go
- pkg/amplitude/storages/delayed_transmission_event_storage.go
- pkg/amplitude/storages/delayed_transmission_event_storage_test.go
#5023
Because the flush method of Amplitide has no return value we do not know if events are subitted or not. Only way around is to let the Amplitude logger print some messages.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5025"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Optimize output of debug instrumentation flush, fixes #5023

- cmd/ddev/cmd/start.go
- cmd/ddev/main.go
#5022
Initialization of remote-config is moved to start command.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5024"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Move init of remote-config to start, fixes #5022

- .gitignore
- cmd/ddev/cmd/export-db.go
- cmd/ddev/cmd/import-db.go
- docs/content/users/usage/commands.md
- go.mod
- go.sum
- pkg/ddevapp/ddevapp.go
- pkg/heredoc/heredoc.go
- pkg/heredoc/heredoc_test.go
- vendor/github.com/MakeNowJust/heredoc/v2/LICENSE
- vendor/github.com/MakeNowJust/heredoc/v2/README.md
- vendor/github.com/MakeNowJust/heredoc/v2/heredoc.go
- vendor/modules.txt
- #4593
This PR streamlines the flags and descriptions of the import-db and export-db commands. It introduces a new package which makes it possible to write cleaner command definitions regarding indentation. Commands are created with a factory function.
Old flags are still here and marked as deprecated to avoid BC issues.
Thanks to @miromichalicka for the initial work done in #4647.
The impact is minimal and everything should be covered by automated testing.
- import-db command works including deprecated flags
- export-db command works including deprecated flags
Closes:
* #4593
Replaces:
* #4647
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5013"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use `--file` for import-db and rework import-db and export-db, fixes #4593

- cmd/ddev/cmd/delete-images.go
* #4974
Attempt to make the code less fragile
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/4975"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix ddev delete images panic, fixes #4974

- Makefile
Our Windows+Mutagen tests often take more than the standard limit of 4 hours. This test only happens on master when a PR is pulled.
Increase the timeout on Windows
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5036"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Increase test timeout for Windows tests [skip ci]

- cmd/ddev/cmd/describe_test.go
- pkg/ddevapp/global_dotddev_assets/router-build/traefik_healthcheck.sh
- pkg/ddevapp/router_Dockerfile_template
- pkg/ddevapp/router_compose_template.yaml
- pkg/ddevapp/traefik_static_config_template.yaml
We saw some test failures, TestDdevFullSiteSetup is failing on both [linux](https://github.com/ddev/ddev/actions/runs/5384364660/jobs/9772197856?pr=5028) and [colima](https://github.com/ddev/ddev/actions/runs/5392269854/jobs/9790378473?pr=4904). seems to fail on checking port 8025. Fails on WordPress in each case.  But it may be because that’s the first test? (Traefik has no healthcheck)
Add healthcheck to ddev-router when Traefik
Ordinary testing. See how our tests go.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5034"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add healthcheck to router so we wait for it to be started

- pkg/ddevapp/ddevapp_test.go
Traditional Windows and Colima testing are very slow and TestDdevFullSiteSetup is particularly problematic with both.
We don't need TestDdevFullSiteSetup on Windows/Colima. Stop testing it
Future:
For ddevapp package, we could easily change the TestMain to skip certain tests automatically based on some general criteria instead of doing one-off changes like this.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5041"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> test: stop testing TestDdevFullSiteSetup on Windows/Colima [skip ci]

- .buildkite/testbot_maintenance.sh
- .github/workflows/colima-tests.yml
- .github/workflows/golangci-lint.yml
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router.go
- pkg/ddevapp/settings_test.go
- pkg/ddevapp/ssh_auth.go
- pkg/ddevapp/utils.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/testcommon/testcommon_test.go
I'm seeing [failures in colima](https://github.com/ddev/ddev/actions/runs/5405137627/jobs/9820257249?pr=5042) of the Traefik router healthcheck coming up; in other environments this has meant the build cache is messy, or that's the best I've been able to figure out.
* New cache for homebrew and colima/lima.
* Clean docker build cache and `-built` images at start of test
* Destroy any existing containers before starting test
* Add healthcheck history to the output of many tests for debugging
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5043"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> test: refresh colima/lima/homebrew github caches, docker build cache

- cmd/ddev/cmd/mutagen-cmd_test.go
- #5053
Config overridden by env vars is now taken into account.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5054"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> test: fix broken Mutagen test, fixes #5053

- .github/pr-labeler.yml
- .github/workflows/pr-check.yml
- docs/content/developers/building-contributing.md
* #5037 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5038"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: enforce commit message convention, fixes #5037 [skip ci]

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
To avoid surprises, rebuild all the images and start using them. We'll do this again at full release or if problems.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5057"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump to new images for v1.22.0-beta1

- .devcontainer/devcontainer.json
- .devcontainer/setup_test_project.sh
- according to https://containers.dev/features latest version of docker-in-docker is 2.2.0, ddev repo uses v1
- bump to v2
- setup ddev in codespaces, check test project
Beware: `setup_test_project.sh` currently fails with
```bash
2023-07-02 09:41:48.611Z: + ddev delete -Oy tmp
2023-07-02 09:41:49.204Z: Failed to get project(s): could not find requested project 'tmp', you may need to use "ddev start" to add it to the project catalog
2023-07-02 09:41:49.297Z: postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```
I did full rebuilds, it failed on docker-in-docker v1 as well as v2.
- no automated tests for codespaces so far iirc
- https://github.com/ddev/ddev/issues/5033#issuecomment-1615076600
- update docs, prs are add: …
> build: gh codespaces - bump docker-in-docker to v2

- docs/content/users/install/ddev-installation.md
- according to https://containers.dev/features latest version of docker-in-docker is `2.2.0`, ddev docs still refer to v1
- bump version to v2
- maybe changes / tests for https://github.com/ddev/ddev/blob/master/.devcontainer/devcontainer.json needed?
- maybe changes / tests for https://github.com/ddev/ddev/blob/master/.devcontainer/devcontainer.json needed?
- https://github.com/ddev/ddev/issues/5033#issuecomment-1615076600
- could not find any release notes for `docker-in-docker`, therefore I assume there were no breaking changes (https://github.com/devcontainers/features)
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5060"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: gh codespaces install docs - update docker-in-docker to v2

- .github/pr-labeler.yml
- cmd/ddev/cmd/cmd_version_test.go
- cmd/ddev/cmd/debug-dockercheck.go
- cmd/ddev/cmd/debug-download-images.go
- cmd/ddev/cmd/debug-download-images_test.go
- cmd/ddev/cmd/debug-nfsmount.go
- cmd/ddev/cmd/delete-images.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router.go
- pkg/docker/images.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
- pkg/globalconfig/global_config.go
- pkg/globalconfig/values.go
- pkg/version/version.go
- pkg/versionconstants/versionconstants.go
We like to detect dependency changes in the CI to properly label PRs changing dependencies. The required Docker Compose version is currently located in the global config and is not taken into account
This PR moves the Docker Compose version to the version constants. To avoid import cycles the functions from version constants are moved to a new package docker/images.
Changes in the version constants are now properly label with `dependencies`.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5072"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: detect more dependency changes

- docs/content/users/extend/additional-hostnames.md
Removed confusing string quotes that doesn't work in the config and example of console command that adds the hostnames for you.
Quotes around the hostnames didn't work for me.
Removes the quotes from the text and suggests a console command
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5045"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: improve additional-hostnames.md

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/network_test.go
- pkg/nodeps/values.go
* #4403
* https://github.com/ddev/ddev/issues/1919
If an app type was set already before running `ddev config` it won't longer be overwritten by the detected app type but a warning is shown to let the user know about. The only way to change the type config is to provide a new value using `--projecttype` flag.
Not implemented so far but could be an option to allow the type `auto` to enforce the value from the detection. But to me this currently looks superfluous.
Use `ddev config --projecttype=...` with an other type than already specified in the project. This should set the new value and not using the auto detected type.
No new tests are introduced.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5011"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: avoid `type: php` to detected project type but instead show a warning, fixes #4403, fixes #1919

- cmd/ddev/cmd/root.go
- #5065
Avoids instrumentation of the project if none is available.
Run `ddev --version` in a folder without DDEV config.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5066"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: avoid instrumentation of project if none is loaded, fixes #5065

- cmd/ddev/cmd/config.go
The type of the `upload-dir` flag was accidentially changed to string slice.
This PR reverts the accidental change back to type string which will make `--upload-dir` working again like expected.
`ddev config --project-type=craftcms --docroot=web --create-docroot --upload-dir=cpresources` should properly add the `cpresources` to the `upload_dirs` config.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5087"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: revert accidental change of upload-dir type, fixes #5076

- pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
When launching HeidiSQL via `ddev heidisql` there is an additional double quote at the end of each database connection name. If you remove the double quotes from the arguments the host parameter must be written in double quotes as the documentation suggests it (Docu: https://www.heidisql.com/help.php#commandline).
This PR removes the double quotes at the end of the string and adds them to the host parameter.
Run`ddev heidisql` to start HeidiSQL from WSL2 with correct name.
> fix: quote host parameter for HeidiSQL and prevent argument double quoting

- cmd/ddev/cmd/a.go
- pkg/dockerutil/dockerutils.go
* #5077 
Turn off cli hints with environment variable DOCKER_CLI_HINTS=false
`ddev poweroff && docker rmi -f $(docker images -q) && ddev start`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5085"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: disable docker CLI hints, fixes #5077

- .github/workflows/colima-tests.yml
- .github/workflows/tests.yml
The previous tests confirmed the problem with the missing assets in the cache was related to tests not downloading all assets. The ddev-test-cache is only stored on pull-push tests where all assets are downloaded, other tests only read this cache. Therefor the cache storing interval is increased again to one week.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5091"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: increase cache update interval to one week

- cmd/ddev/cmd/root.go
- pkg/ddevapp/mutagen.go
* #5040
When DDEV upgrade is detected, after poweroff, destroy mutagen sessions. These should already have been flushed when they were stopped.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5096"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: terminate mutagen sessions on DDEV upgrade, fixes #5040

- docs/content/users/topics/remote-docker.md
https://github.com/jonaseberle/github-action-setup-ddev has been migrated to https://github.com/ddev/github-action-setup-ddev.
I suggest to use the Github marketplace URL as a landing page in the docs.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: point to new location of DDEV GitHub Action

- .github/workflows/colima-tests.yml
- .github/workflows/tests.yml
Cleanup may fail on upstream problems see https://github.com/ddev/ddev/actions/runs/5482145525/jobs/9987195573?pr=5094
Make clean up optional and don't fail anymore.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5097"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: prevent job from failing if cleanup fails

- containers/ddev-webserver/ddev-webserver-base-scripts/pre-start.sh
- pkg/versionconstants/versionconstants.go
* https://github.com/ddev/ddev/issues/5089#issuecomment-1626124810
During debugging we saw:
```
2023-07-07 20:47:42,159 INFO stopped: child_exit_monitor (terminated by SIGTERM)
+ trap - SIGTERM
+ kill -- --1
/pre-start.sh: line 1: kill: --1: arguments must be process or job IDs
```
Apparently in the situation of a failing web_extra_daemon things weren't handled correctly. 
Use the correct syntax, `kill -- -1` (`-1` rather than `--1`)
The previous error was created by making an error happen with something like this:
```yaml
web_extra_daemons:
- name: "failit"
command: "./failit.sh"
directory: /var/www/html
```
and after ddev start, `ddev logs` showed the error. 
This shouldn't happen now.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5107"><img …
> fix: ddev-webserver process kill function was incorrect

- go.mod
- go.sum
- pkg/amplitude/doc.go
- vendor/github.com/amplitude/analytics-go/amplitude/constants/constants.go
- vendor/modules.txt
Reviewing the project, I noticed that we are using a fork for the explicit purpose of including a patch. This patch has now been incorporated into the upstream, so we can move back to using that upstream project and shed the fork.
Related:
* https://github.com/ddev/ddev/issues/5048
* #5101 
I'm a new contributor and author of Go code, but I believe this replaces the fork with the upstream. Happy to make any adjustments or take on further work, if needed - let me know.
Nothing specific, to my knowledge. The usual things I guess?
https://github.com/amplitude/analytics-go/pull/56 is the PR that was needed to be incorporated into the upstream project.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5103"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: revert to upstream Amplitude, fixes #5101

- cmd/ddev/cmd/restart.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/mutagen.go
- pkg/dockerutil/dockerutils.go
* #5089 
* Fix bug where if container was not yet healthy mutagen sync didn't happen.
* Add request to poweroff on `ddev restart`
* Check inside container to make sure mutagen flush is complete (look at /var/www/html/composer.json)
* `ddev restart` with version change
* `export DDEV_DEBUG=true && ddev mutagen reset && ddev start -y` on mutagen-enabled system. It should check composer.json (and succeed)..
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5106"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: solve mutagen failure, restart should check for new version, check composer.json in container, fixes #5089

- .github/workflows/golangci-lint.yml
go.mod file is not up to date from time to time because running `go mod tidy` is often forgotten after changing dependencies.
This PR introduces a check for the validation of the current installed dependencies and also if go.mod and go.sum are up to date.
Tested here in CI see commits.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5115"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: ensure go modules have a clean state

- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/root.go
- pkg/ddevapp/assets.go
User-defined custom commands are exposed to instrumentation which is not what we want regarding data protection.
User-defined custom commands are now anonymized with the name `custom-command`. So we still are able to record statistics about the usage of custom commands but have not longer critical data stored in Amplitude.
Run user-defined custom commands and check on Amplitude if they are properly anonymized. This is best done with the user lookup debug technique where all commands are visible.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: anonymize user-defined custom commands

- pkg/ddevapp/providerPantheon_test.go
TestPantheonDoMonthlyPush fails most months on the 10th and this isn't the right place to do it anyway.
We'll have to figure out a better way to keep our Pantheon account from going stale.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5124"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: remove TestPantheonDoMonthlyPush [skip ci]

- docs/content/users/extend/additional-hostnames.md
I made some suggestions for #5045 I couldn’t get into fenced text blocks, so they’re back here with a vengeance:
1. Have the intro summarize the page from the start, linking away to the relevant config and command docs to reiterate the core concepts.
2. Apply syntax highlighting to the YAML examples, because syntax highlighting is good for your health.
It makes the suggestions much easier to follow.
[Preview changes locally](https://ddev.readthedocs.io/en/stable/developers/testing-docs/#preview-changes) or inspect the [automatic build](https://ddev--5120.org.readthedocs.build/en/5120/users/extend/additional-hostnames/).
n/a
- #5045
n/a
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5120"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: improve “Additional Project Hostnames” intro and add YAML syntax highlighting

- pkg/globalconfig/global_config.go
- pkg/globalconfig/styles.go
Many v1.21.6 projects had `table_style: ""`
v1.22.0 requires `table_style: default`
Disallow "" as value, then the global config reader substitutes "default"
Set `table_style: ""` in global_config.yaml, then `ddev start`
You should now see `table_style: default` in global_config.yaml
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5117"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: empty global table style should revert to "default"

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config.go
- pkg/ddevapp/config.go
- pkg/globalconfig/global_config.go
- #5095
Removed flags are reintroduced and marked deprecated.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5109"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: reintroduce removed flags and remove dba from `omit_containers`, fixes ddev#5095

- .github/workflows/tests.yml
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/php.go
- pkg/ddevapp/upload_dirs.go
* #5126
* #5127 
* Fix the panic
* Add test coverage for upload_dirs=false and several other situations
* Refactor the type conversion management
* Fix `ddev import-files` for Laravel
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5128"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: fix panic when upload_dirs=false, improve upload_dirs tests, fixes #5126, fixes #5127

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- docs/content/users/configuration/config.md
- docs/content/users/usage/cli.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/backdrop.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/drupal.go
- pkg/ddevapp/magento.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/shopware6.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/typo3.go
- pkg/ddevapp/upload_dirs.go
- pkg/ddevapp/wordpress.go
- pkg/testcommon/testcommon.go
We tried to support a multi-type upload_dirs but it added a lot of complexity to the code. 
Unfortunately, I've decided to revert that and go back to a simpler approach.
An additional PR will be required to add a new config that turns off warnings about upload_dirs
Also accidentally fixes
* #5131 
by going back to a simple array for the declaration.
Many things have to be re-tested:
* #5131 - empty `config.*.yaml` was resulting in upload_dirs being emptied
* #5031 (after #5132 goes in) - Specific upload_dirs with Craft CMS
* #5127 - import-files needs to work on Laravel and Craft if import-dirs specified
* #5126 - panic with upload-dirs
* #4796 - Of course we need a way to do that.
I think the tests cover the things that matter
<a …
> refactor: revert `upload_dirs=false`, fixes #5131

- cmd/ddev/cmd/auth-ssh_test.go
- cmd/ddev/cmd/logs_test.go
- cmd/ddev/cmd/ssh_test.go
- cmd/ddev/cmd/xdebug_test.go
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/hardened_test.go
- pkg/ddevapp/router_test.go
- pkg/nodeps/utils.go
There are references to Mac M1 in the code, but with Apple's release of M2, it is probably wise to change those references to a more general "Apple Silicon", when checking architectures.
This simply updates the function name and all of the references to it.
Start up a DDEV project on a device using Apple Silicon, particularly one using Docker Desktop, as this code is required due to compat quirks with that.
This change should included updated tests where necessary.
https://github.com/ddev/ddev/issues/5125
This should be fairly self-contained and not affect other code to a large degree.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5129"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: change code refs of Mac M1 to Apple Silicon

- winpkg/ddev.nsi
The language strings were accidentially removed with https://github.com/ddev/ddev/pull/4553 and some other parts were not properly removed.
Also fixes 
* #1945 
The missing language strings are added again and left overs are removed properly.
Check build if there are no warnings. When running the installer, on the component page the descriptions should be shown properly for all components now.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5098"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: clean up Windows installer, fixes #1945

- cmd/ddev/cmd/composer-create.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/upload_dirs.go
* #5031
Because we delete most things in the project directory, we're removing the host-side directories that bind-mounts depend on, invalidating them. When using mutagen, there are (by default) bind-mounts to the upload_dirs, and so those get invalidated.
The way to fix this is to recreate the bind mount directories (upload_dirs) after we've deleted them unknowingly, and then Restart()
Use the recipe in #5031 
Existing tests should be adequate
Previous attempts:
* #5042 (Two separate attempts there)
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: composer create project must restart to fix broken bind mounts, fixes #5031

- cmd/ddev/cmd/root.go
Code said we were supposed to start reporting other commands to Amplitude by now
Remove the exclusions
Look at Amplitude data coming in.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: start reporting all commands to amplitude

- containers/ddev-dbserver/Makefile
- pkg/versionconstants/versionconstants.go
mysql 8.0.33 and 5.7.42 are out
* #5114 
upgrade to them
Start a mysql 8 project and check version, `mysql --version`
See also 
* https://github.com/ddev/mysql-arm64-images/pull/6
* https://github.com/ddev/xtrabackup-build/releases/tag/8.0.33-27 (actually worked this time)
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5140"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump mysql to 8.0.33 and 5.7.42, fixes #5114

- pkg/ddevapp/craftcms.go
- pkg/ddevapp/ddevapp.go
- #4650
`CRAFT_WEB_URL` and `CRAFT_WEB_ROOT` are added to the `.env` file. `PRIMARY_SITE_URL` is still left untouched to not break existing installations at the moment. Additionally a version check is implemented and warns the user if using project type `craftcms` for version before 4.
Follow the quick start to setup a new Craft CMS site which should not work out-of-the-box without any additional configuration.
Setup a Craft CMS v3 or earlier with project type `craftcms` and check if a warning is properly shown.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5108"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: detect Craft CMS version and warn user on type mismatch and introduce new env vars, fixes #4650

- pkg/ddevapp/config.go
* #5146
* It kept repeating on invalid type
* The second through nth times it used `print` instead of the correct `printf`, so showed an invalid message
* Replace print with printf
* If invalid project type, use detected project type
Set an invalid type in .ddev/config.yaml and then try to do interactive config.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5148"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: ddev config should not stumble on invalid app type, fixes #5146

- pkg/ddevapp/mutagen.go
- pkg/util/utils.go
* #5143 
Move many of these from "DDEV_DEBUG" to DDEV_VERBOSE.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5147"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: make many mutagen debug outputs only verbose, fixes #5143

- pkg/ddevapp/router.go
- pkg/globalconfig/global_config.go
1. We use DDEV_ROUTER_HTTP_EXPOSE and DDEV_ROUTER_HTTPS_EXPOSE in generating the .ddev/.ddev-docker-compose-full.yaml. 
2. Those are derived from the global or project router_http_port or similar
3. They can be wrong (mostly empty) (which this fixes)
4. But then they get used in HTTP_EXPOSE and HTTPS_EXPOSE
5. So other projects inherit them by inspecting the web container, and then they can end up with an HTTP_EXPOSE like ":80:443:443", which isn't valid (now ignored with this fix)
This was showing up in TestProcessHooks and probably other places on Traditional Windows/Mutagen tests. AFAICT, that is a result of the Windows machines having `router_http_port: ""` in their global config. Fixing that to `router_http_port: "80"` actually fixed it. 
I think if tests work this is OK. 
<a …
> fix: repair broken received HTTP*EXPOSE that breaks ports statement

- pkg/ddevapp/ddevapp_test.go
When running locally TestDdevNoProjectMount would fail just because it was set up wrong.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5149"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: minor improvement to TestDdevNoProjectMount [skip ci]

- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- docs/content/users/configuration/config.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
- pkg/ddevapp/templates.go
- pkg/ddevapp/upload_dirs.go
Earlier we had the option of `upload_dirs: false` to turn off the pester about `upload_dirs` not being set and mutagen being enabled. This ended up being a very complex bit of code and was rolled back.
Now we need another way to do it.
Add `disable_upload_dirs_warning`
On a `php` project without `upload_dirs`, `ddev start` should show the warning.
After `ddev config --disable-upload-dirs-warning` it should not show the warning.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5139"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: add new disable-upload-dirs-warning configuration

- pkg/ddevapp/ddevapp.go
- https://github.com/ddev/ddev/issues/5135
Project files in `ddev-global-cache` are now always deleted, not only when the project is running.
Start a project, confirm that there is a folder for this project (ending with `-web`) into `nvm_dir`:
```
docker run --rm -i -v=ddev-global-cache:/mnt/ddev-global-cache busybox:stable ls /mnt/ddev-global-cache/nvm_dir
```
Run `ddev delete --omit-snapshot --yes` on the started and stopped project.
Make sure the folder for this project (ending in `-web`) in `nvm_dir` is deleted:
```
docker run --rm -i -v=ddev-global-cache:/mnt/ddev-global-cache busybox:stable ls /mnt/ddev-global-cache/nvm_dir
```
To be safe, make sure that the cache for other projects is not deleted.
No.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5137"><img …
> fix: always clean up ddev-global-cache, fixes #5135

- docs/content/users/configuration/config.md
- pkg/globalconfig/global_config.go
`messages` configuration was omitted from the config docs
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5156"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add messages configuration to config.md

- version-history.md
For v1.22.0 we need to update version-history.md
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5155"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add v1.22 to version-history [skip ci]

- .github/workflows/colima-tests.yml
- .github/workflows/macos-colima-setup.sh
Random homebrew installation failures were breaking all of colima tests
On review, the huge caches and cache restores were taking longer than it would take to start colima from scratch
Try giving up cache.
Some homebrew cleanup
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5157"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: stop caching colima and homebrew on colima

- pkg/ddevapp/app_compose_template.yaml
* #5133
Actually use the timeout in the docker-compose setup
```
ddev config --default-container-timeout=600
ddev start
ddev snapshot restore huge
```
Assuming `huge` snapshot can be imported in 10m, it shouldn't time out or give the timeout message
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5154"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: default_container_timeout should actually work, fixes #5133

- cmd/ddev/cmd/root.go
Reverts ddev/ddev#5136
This code was actually only supposed to be removed when we end up removing the Segment reporting. Right now we're keeping the segment reporting in parallel with Amplitude.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: revert "refactor: start reporting all commands to amplitude"

- docs/content/users/extend/custom-compose-files.md
Docker moved a link. Remove the link to pacify links linter.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5166"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix broken link on docker

- cmd/ddev/cmd/root.go
`ddev start` on first usage was outputting invalid link for info on instrumentation.
```
$ ddev start
Network ddev_default created
It looks like you have a new ddev release.
May we send anonymous ddev usage statistics and errors?
To know what we will see please take a look at
https://ddev.readthedocs.io/en/stable/users/details/opting-in
Permission to beam up? [Y/n] (yes):
```
Fix link
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5170"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: bad link was output when asking permission on instrumentation

- cmd/ddev/cmd/root.go
People who use the PhpStorm extension for DDEV have `ddev describe -j` happening every minute or so in the background. This causes loads of useless traffic.
Don't report commands when using `--json-ouput`
`for ((i=0; i<100; i++)); do ddev describe -j; done >/tmp/out 2>&1 && ddev debug instrumentation flush` should *not* result in new data in amplitude
`for ((i=0; i<100; i++)); do ddev describe; done >/tmp/out 2>&1 && ddev debug instrumentation flush` SHOULD result in new data in amplitude
https://app.amplitude.com/analytics/ddev/chart/vqe8wcsj can be used to study this; the filtering will have to be adjusted for your use.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5169"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: don't report json-formatted commands to Amplitude

- pkg/ddevapp/apptypes.go
* #5168 
This seems like the lightest touch possible here, just check to see if project is running before trying to sync it. The only reason for the sync is to get the new settings into the container right away, and since it's just one file normally, mutagen has probably already synced it without even a flush. However, if the project is stopped, it will be synced on start.
I first experimented with changing MutagenSyncFlush itself, and it can be done there, but it would have effects on all callers, and I'm risk-averse at this point in the release cycle.
Use #5168 instructions
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5175"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: don't run MutagenSyncFlush on non-running project during config, fixes #5168

- cmd/ddev/cmd/describe.go
`ddev describe` was showing docker version, which isn't that useful. Docker Platform is better.
New:
```
Project: n ~/workspace/n https://n.ddev.site                                
Docker platform: orbstack                                                    
Router: traefik
```
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5176"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: show docker platform in ddev describe

- pkg/config/remoteconfig/messages.go
* #5177
The notification and ticker interval are not set if 0, so conditions are fixed to reflect this correctly and return the first set config.
Set `notification_interval` and `ticker_interval` to `-1` and check if notifications and ticker messages are not longer shown on `ddev start`.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5178"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: correctly return notification and ticker interval, fixes #5177

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Time for v1.22.0: Push new images
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5179"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump docker image tags for v1.22.0

- pkg/config/remoteconfig/messages.go
* #5180
On short living instances e.g. Gitpod the first ticker message is always show.
In case no message was shown so far, a random message is picked.
Remove the state file `~/.ddev/.state.yaml` and check if a random message is shown on `ddev start`.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5181"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: start with random ticker message, fixes #5180

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/router.go
Some environments may have a hang after the router is started but before it's healthy
Try to gather some information
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: output debug messages during router startup

- pkg/ddevapp/router_compose_template.yaml
There is no difference in `router_bind_all_interfaces` for Traefik:
```
ddev config global --router-bind-all-interfaces=true
ddev start
cat ~/.ddev/.router-compose.yaml | grep 9999
- 9999:9999
ddev config global --router-bind-all-interfaces=false
ddev start
cat ~/.ddev/.router-compose.yaml | grep 9999
- 9999:9999
```
Traefik must consider the `router_bind_all_interfaces` config.
```
ddev config global --router-bind-all-interfaces=false
ddev start
cat ~/.ddev/.router-compose.yaml | grep 9999
- "127.0.0.1:9999:9999"
ddev config global --router-bind-all-interfaces=true
ddev start
cat ~/.ddev/.router-compose.yaml | grep 9999
- "9999:9999"
```
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: traefik dashboard should not bind all interfaces by default

- docs/content/developers/building-contributing.md
As described by Randy on 
[2023-07-18 | Maintaining and Improving the Docs](https://www.dropbox.com/scl/fi/2d5qryxzgwa5zat9xz056/20230718_contributor_traiing_docs.mp4?dl=0&rlkey=senzp6l6j8zq52vd4y74uhqfy)
This line could be better at reflecting what has been changed.
`docs: improve additional-hostnames.md` 
It replaces `docs: improve additional-hostnames.md` for this one `docs: change code refs of Mac M1 to Apple Silicon`.
Both are merged PR's
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5183"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: improve docs example on building-contributing.md

- cmd/ddev/cmd/debug-dockercheck.go
@rpkoller pointed out that there was a typo in `ddev debug dockercheck`
Further study showed that there was also a problem because it should have failed with that typo.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: ddev debug dockercheck logic error and typo

- pkg/ddevapp/magento.go
* #5197 
The default upload_dirs is incorrect for magento2 in v1.22.0
Use the correct value
Create magento2 project using the quickstart
`ddev start && ddev exec 'echo $DDEV_UPLOAD_DIRS'` - it should show pub/media, not pub/pub/media
> fix: default upload_dirs incorrect for magento2, fixes #5197

- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/hardened_test.go
- pkg/versionconstants/versionconstants.go
* #5191
* Fix the build (/usr/local/bin was being overwritten with unwriteable perms)
* Push new image
* Fix TestHardenedImages to prefer drupal7
In drupal7 project:
```
ddev config global --use-hardened-images
ddev restart
```
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: chmod ugo+rwx /usr/local/bin *after* dirs have been added, fixes #5191

- cmd/ddev/cmd/debug-testcleanup.go
- cmd/ddev/cmd/debug-testcleanup_test.go
- cmd/ddev/cmd/scripts/test_ddev.sh
- docs/content/users/usage/commands.md
The output for `ddev debug test` contains:
```
If you're brave and you have jq you can delete all tryddevproject instances with this one-liner:
ddev delete -Oy $(ddev list -j |jq -r .raw[].name | grep tryddevproject)
In the future ddev debug test will also provide this option.
```
It is dangerous to run this one-liner twice in a row, because the second run will be the same as `ddev delete -Oy` without any arguments, and it will delete the DDEV project with its volumes.
Add `ddev debug testcleanup` command that will clean up all projects with `tryddevproject` prefix. No `jq` required.
Run `ddev debug test` several times, then `ddev debug testcleanup`
- https://github.com/ddev/ddev/issues/5210
Use `xargs`:
```
ddev list -j | jq -r '.raw[].name' | grep tryddevproject | xargs -L 1 -r ddev …
```
> feat: add `ddev debug testcleanup`, fixes #5210

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/dockerutil/dockerutils.go
* #5222
There are two code problems;
* In the app_compose_template.yaml there are two "if" statements but it needs an else if instead to avoid duplicating in case of odd situations like this
* In config.go, UseHostDockerInternalExtraHosts should not be set if we're using Colima, when we use a static host.docker.internal.
Fix the two problems above.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5223"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: correct xdebug port detection for colima on linux, fixes #5222

- cmd/ddev/cmd/config-global.go
- cmd/ddev/cmd/config-global_test.go
- docs/content/users/configuration/config.md
- docs/content/users/extend/traefik-router.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/healthcheck/router/traefik/traefik_healthcheck.sh
- pkg/ddevapp/router.go
- pkg/ddevapp/router_compose_template.yaml
- pkg/ddevapp/traefik.go
- pkg/ddevapp/traefik_static_config_template.yaml
- pkg/globalconfig/global_config.go
- pkg/nodeps/values.go
* #5196
In DDEV v1.22.0, the traefik monitoring port was fixed at 9999. This conflicted with lots of existing usage, and also conflicted with many suggested configurations in the docs.
* Change the default port to 10999
* Make it configurable with global config: `traefik_monitor_port`
* `ddev describe` should show it running now on port 10999 by default
* Change it using `traefik_monitor_port` in the global_config.yaml
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: make traefik monitoring port configurable, not just 9999, fixes #5196

- .readthedocs.yaml
- docs/mkdocs-pip-requirements
readthedocs sent out an email:
```
You are receving this email because your Read the Docs project is impacted by an upcoming deprecation.
Read the Docs used to pre-install common scientific Python packages like scipy, numpy, pandas, matplotlib and others at system level to speed up the build process. However, with all the work done in the Python ecosystem and the introduction of "wheels", these packages are a lot easier to install via pip install and these pre-installed packages are not required anymore. If you have Apt package dependencies, they can be installed with [build.apt_packages](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages).
With the introduction of our new "Ubuntu 20.04" and "Ubuntu 22.04" Docker images, we stopped pre-installing these extra …
```
> build: update readthedocs config per their email

- pkg/ddevapp/config.go
* #5246
Described in [issue #5646](https://github.com/ddev/ddev/issues/5246): Removes unneeded notice about removed "dba" container
Removes the string output; keeps configuration strip code in place.
1. Use this patched version
2. Choose any project
3. Edit that project's `.ddev/config.yam` file and add `omit_containers: [dba]` at the end
4. Run the project via `ddev start`
5. You should NOT GET this warning output now: "PhpMyAdmin (`dba`) is no longer part of DDEV core, please edit your `omit_containers` configuration to remove it"
6. Rest of functionality untouched, so the 'dba' container will not try to be referenced.
N/A
https://github.com/ddev/ddev/issues/5246
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5247"><img …
> docs: remove information about obsolete omit-containers=dba config, fixes #5246

- docs/content/users/quickstart.md
[Stack Overflow Question](https://stackoverflow.com/questions/76872710/ddev-moodle-docker/76880321#76880321) points out that Moodle requires MariaDB 10.6, which wasn't in our quickstart.
> docs: update moodle quickstart to use MariaDB 10.6

- pkg/version/version.go
* #5250 
Both `docker version` and Amplitude were reporting some thing incorrectly for docker-platform.
Reorganize the tests.
Use `ddev version` to validate the docker platform on several OSes:
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5258"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: make GetDockerPlatform() more accurate, fixes #5250

- .github/workflows/macos-colima-setup.sh
Colima tests are all failing. I'm pretty sure we don't need libpq any more.
```
====== Running brew link ======
+ brew link --force libpq mysql-client
Linking /usr/local/Cellar/libpq/15.4... 
Error: Could not symlink bin/clusterdb
Target /usr/local/bin/clusterdb
is a symlink belonging to postgresql@14. You can unlink it:
brew unlink postgresql@14
To force the link and overwrite all conflicting files:
brew link --overwrite libpq
To list all files that would be deleted:
brew link --overwrite --dry-run libpq
```
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: don't install libpq on macOS any more, postgresql is installed

- docs/content/users/usage/commands.md
The yarn folks seem to have updated their site and the link has changed. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5265"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix yarn commands link

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
* #1812 
Actually figure out what the port is for DDEV_HOST_WEBSERVER_PORT and DDEV_HOST_HTTPS_PORT and provide it.
Corrected the coverage in TestEnvironmentVariables
* https://github.com/ddev/ddev/pull/5173
After this is done custom commands can implement things like localhost.run, etc.
* https://github.com/ddev/ddev/pull/5173
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5263"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: properly support DDEV_HOST_WEBSERVER_PORT, fixes #1812

- pkg/ddevapp/ddevapp.go
DdevApp had unused items:
* DBImage was no longer used by anything
* DBAImage no longer exists because dba was removed
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: remove cruft from DdevApp

- pkg/versionconstants/versionconstants.go
docker-compose 2.20.3 is out. Try it out.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5276"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump docker-compose to 2.20.3

- .github/workflows/push-tagged-image.yml
The `choice` option for the push-tagged-image is a lot easier to use. 
Try building an image
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5283"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: use explicit choices for image name to push [skip ci]

- docs/content/users/extend/custom-tls-certificates.md
The default router is now the traefik router, and that makes the verbiage in custom certs section incorrect.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5287"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix custom cert issues - default router has changed

- cmd/ddev/cmd/debug-nfsmount.go
- docs/content/users/install/performance.md
* URL in error message is incorrect
* Warning about NFS on Ventura is incorrect
Update them
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5284"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix URL in error message, remove warning in NFS docs

- .devcontainer/devcontainer.json
- docs/content/users/install/ddev-installation.md
- it was explained here, that the universal image already installs `docker-in-docker` https://github.com/devcontainers/features/issues/634#issuecomment-1681303196
- `docker-in-docker` feature had no effect and lead to irritating output, since the outputted version info in codespaces creation log had no real effect (since docker was already installed) 
- updated my demo repo https://github.com/mandrasch/ddev-craftcms-vite/blob/main/.devcontainer/devcontainer.json#L4, first tests worked
- We might discuss whether ddev itself should be tested with universal image as well?  https://github.com/ddev/ddev/blob/56afe4bee4170688435510c79135d32d63b7d824/.devcontainer/devcontainer.json#L2-L14 (don't know about ramifications, just a quick idea)
- updating the docs, removing docker-in-docker from code …
> codespaces - remove docker-in-docker since it's installed via universal image

- pkg/ddevapp/ddevapp.go
Codespaces changed their port forwarding domain from `preview.app.github.dev` to `app.github.dev`
> To prepare for this change, replace any hardcoded references to preview.app.github.dev in your code with the GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN environment variable by July 31 to avoid any disruptions. The environment variable value will be updated from preview.app.github.dev to app.github.dev when the migration completes. Learn more about environments variables [here](https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace).
https://github.blog/changelog/2023-07-14-codespaces-port-forwarding-domain-name-updates/
- `ddev launch` did not work anymore
- replacing `preview.app.github.dev` with `app.github.dev`
- test `ddev launch` …
> fix: change codespaces forwarding domain name to app.github.dev 

- .github/devcontainers/src/install-ddev/devcontainer-feature.json
- .github/workflows/macos-colima-setup.sh
* A few devcontainer-related changes went in and we want to pick them up
* Colima tests have been failing due to broken macOS running in Github. Update lima to get current
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5289"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: update devcontainer package since we have new devcontainer stuff

- pkg/ddevapp/apptypes.go
`ddev import-files` should work for all project types, including `silverstripe`.
`importFilesAction` can be easily forgotten for newly created project types.
Let's use `genericImportFilesAction` if no specific `importFilesAction` is defined.
```
mkdir silverstripe && cd silverstripe && mkdir source && touch source/file
ddev config --project-type=silverstripe
```
Before:
```
ddev import-files --source=source --target=target 
Error: failed to import files for silverstripe: this project type (silverstripe) does not support import-files
```
After:
```
ddev import-files --source=source --target=target 
Successfully imported files for silverstripe
```
- https://github.com/ddev/ddev/pull/5119
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5234"><img …
> fix: import-files should work with any project type

- pkg/ddevapp/schema.json
- pkg/globalconfig/schema.json
Having IDEs automatically validate the global_config.yaml or config.yaml is useful to help guide valid changes within a specification. This also allows DDEV plugins to leverage a schema file that is maintained in the project, allowing for updates across versions.
This scenario was born from the fact the JetBrains Intellij plugin for DDEV written by @nico-loeber was implementing it's own JSON Schema but it was based on 1.19 and had become outdated. By doing this, we allow other plugins to use a single source of truth to prevent issues with out date options or missing options e.g. project types. Any changes required can be directly submitted to the ddev repository, maintaining a single source of truth,
This PR provides two JSON schema files which have been validated against test files for …
> feat: initial JSON schemas for global config and project/app config, fixes #4511

- docs/content/index.md
- mkdocs.yml
Thought about some UX improvements for the docs start page:
1. new users will often begin their "user journey" on https://ddev.readthedocs.io/en/latest/
1. "System Requirements" section contain external links to Docker Desktop, Colima, etc <br> --> users might exit the process of following next steps ("bounce rate")
1. no call to actions at the end of the start page <br> --> users might exit the process of following next steps ("bounce rate")
Especially the gitpod & codespaces section provides no further link, I completely missed the sub-section https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#github-codespaces when I explored codespaces.
First I thought about a "next / prev" nav (screenshot example of [vitepress](https://my-ddev-lab.mandrasch.eu/):
But Windows and …
> docs: add next steps to improve guiding new users, enable footer links

- pkg/ddevapp/dotddev_assets/providers/README.txt
The GitHub links in the provider README.txt point to the wrong (old?) location.
The URLs have been updated.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5297"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix broken links to provider directory on GitHub

- docs/content/users/install/docker-installation.md
- docs/content/users/usage/faq.md
* #5014
Even though not all Docker Providers have automated tests, people may have good experiences anyway. Try to document them in FAQ.
Add item to FAQ
This replaces #5014 but @jmarkel gets commit credit on this one.
https://ddev--5293.org.readthedocs.build/en/5293/users/usage/faq/#are-there-alternate-docker-providers-i-can-use
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5293"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: mention alternate docker providers in faq, fixes #5014

- .github/workflows/macos-colima-setup.sh
Colima has been broken several ways in recent weeks due to qemu homebrew build.
Try another workaround.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5308"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: try another technique to get colima running again

- docs/content/developers/release-management.md
Chocolatey has made maintainers of package private; remove it as a link so it doesn't get tested
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5311"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix broken chocolatey link

- docs/content/users/debugging-profiling/step-debugging.md
Xdebug troubleshooting doc update for xdebug_ide_location.
-mike
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: mention xdebug_ide_location setting in xdebug troubleshooting section

- docs/content/users/quickstart.md
Fix Silverstripe “Git Clone” tab
An indent error was making it seen as raw text instead of tab title.
Buggy space is removed
On https://ddev.readthedocs.io/en/latest/users/quickstart/#silverstripe "Composer" tab is lonely and followed by a raw `=== “Git Clone”`
With this PR, there should now be two tabs, side by side, titled "Composer" and "Git Clone".
N/A
It seems that there is no automated test to check tab syntax in Markdown.
N/A
N/A. Affect nothing else.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5302"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: fix a tab in "CMS Quickstarts"

- .spellcheckwordlist.txt
- docs/content/users/quickstart.md
How to quickly install Ibexa DXP OSS
N/A
N/A
Run the proposed command lines.
It could need the addition of `ddev config --http-port=8080 --https-port=8443` on some platform where ports 443 and/or 80 are already reserved.
"CMS Quickstarts" scripts do'nt seem to have automated tests. Did I miss something?
No side effect.
N/A
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5301"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add Ibexa DXP to "CMS Quickstarts"

- .github/workflows/colima-tests.yml
Yet more pain on the colima run; brew install mysql-client is failing with an obscure dependency.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5312"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ci: more work to get homebrew sorted out on colima

- cmd/ddev/cmd/auth-ssh_test.go
- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.ssh/config
- docs/content/users/extend/in-container-configuration.md
- pkg/ddevapp/ssh_auth_test.go
- pkg/versionconstants/versionconstants.go
SSH power users and security folks expect `ssh` to check host keys.
The option `StrictHostKeyChecking=accept-new` has been introduced in OpenSSH 7.6. It provides the protection against IP-spoofing without the previously necessary user interaction (in case of `=yes/true`) to accept unknown keys on first connect.
In case a host key has actually changed, OpenSSH gives a helpful warning including the exact command that is necessary to remove the old host key from known_hosts.
Using `ssh` from within containers works as before. If a host key actually changed, the connection is rejected and OpenSSH shows an error message.
Tests have been adapted to use the web container's default SSH config.
(Discussion topic) https://github.com/orgs/ddev/discussions/5029
Would be great to see this for 1.22.
<a …
> refactor: use StrictHostKeyChecking=accept-new

- .ci-scripts/nsis_setup.sh
- .github/workflows/linux-setup.sh
- .github/workflows/pr-build.yml
- winpkg/ddev.nsi
* #4701
We want to use gsudo.exe directly from the upstream gerardog/gsudo repository, instead of using our forked one with an implanted old release
Use the upstream zipball and extract it.
* Remove any sudo.exe from the installer directory C:\Program Files\DDEV
Download the installer from this PR (https://github.com/ddev/ddev/pull/5314#issuecomment-1701925943) and run the installer. 
* Verify that sudo.exe has been installed and can be used
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5314"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: use gsudo.exe directly from gerardog/gsudo, for #4701

- .ci-scripts/nsis_setup.sh
- .github/workflows/docscheck.yml
- docs/content/users/usage/managing-projects.md
* Minor fixups to pacify linter, which only seemed to complain on master.
* nsis_setup.sh failed on win11-06 because of missing double quote. 
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5323"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: textlint is complaining about Zip usage - use ZIP

- docs/content/users/configuration/config.md
name in the config yaml needs to be project-name when used with `ddev config`
Explains that.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5315"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: note that the CLI flag `--project-name` is what sets `name` in config.yaml

- docs/content/users/install/performance.md
- mkdocs.yml
* #5299
When using npm / 
This adds a note to the Mutagen section of the performance page about node_modules and the recommendation to exclude it on website projects that doesn't need it at runtime.
Review at https://ddev--5303.org.readthedocs.build/en/5303/users/install/performance/#mutagen
*shrug*
* #5299
N/a
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5303"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add info about mutagen sync slow due to node_modules

- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
In Drupal7 and maybe early Drupal 8 it was common for people to run Drupal's drush (8) on the host side and so there was capability in the settings.ddev.php to allow this. 
However, that's long since obsolete and just causes confusion now. 
Remove the stanza from settings.ddev.php that set this up.
Use DDEV with D9/D10. You should see a settings.ddev.php that doesn't have the stanza any more.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: drupal9 and drupal10 shouldn't be used with host-side drush so remove facility

- docs/content/users/usage/commands.md
I noticed that project-tld was left out of global config commands.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5330"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: add --project-tld to global config

- docs/content/users/configuration/config.md
* #5280
the `bind_all_interfaces` option is not shown in config.md
Review at https://ddev--5334.org.readthedocs.build/en/5334/users/configuration/config/#bind_all_interfaces
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: document bind_all_interfaces project config, fixes #5280

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
* #5310
Time to bump images. This brings us to v1.22.2
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5333"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump images to v1.22.2, fixes #5310

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config_test.go
- pkg/ddevapp/ddevapp.go
* #5341 
* There didn't seem to be any test coverage for this regression
* Make it work on `ddev restart`
* Add a test
Added TestConfigFunctionality
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5353"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: make host_webserver_port and host_https_port config work again, fixes #5341

- docs/content/users/configuration/config.md
> docs: typos in config.md in names of elements simple-formatting etc

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Bump images to v1.22.3 for release.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5357"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> build: bump images to v1.22.3 for release

- pkg/ddevapp/dotddev_assets/providers/platform.yaml
The platform.yaml still said it was an "example", whereas you don't have to do anything to use it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5369"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: platform.yaml shouldn't say it is an example

- .spellcheckwordlist.txt
- cmd/ddev/cmd/share.go
- docs/content/users/configuration/config.md
- docs/content/users/topics/sharing.md
- docs/content/users/usage/commands.md
From [Discord](https://discord.com/channels/664580571770388500/1068592266752573440/1150669419123589211): documentation needs to be updated because ngrok introduced [static domains for all ngrok users](https://ngrok.com/blog-post/free-static-domains-ngrok-users).
Also, from [new ngrok domains now available](https://ngrok.com/blog-post/new-ngrok-domains):
> Deprecated `--subdomain` and `--hostname` flags in favor of `--domain` flag which accepts a fully qualified domain.
1. Updates the documentation with the latest changes from ngrok.
2. Removes `--basic-auth` and `--subdomain` from `ddev share`.
3. Adds `--ngrok-args` to `ddev share`.
If I want to run something custom, I need to use `ngrok_args` from `.ddev/config.yaml`. But I never want to commit `ngrok_args`, I can use …
> feat: replace ngrok flags in `ddev share` with `--ngrok-args`

- pkg/ddevapp/ddevapp_test.go
In working on #5340 `TestDdevXdebugEnabled` was failing were not passing with random (but frequent) failure of `TestDdevXdebugEnabled` with
```
ddevapp_test.go:989: 
Error Trace:	/home/runner/work/ddev/ddev/pkg/ddevapp/ddevapp_test.go:989
Error:      	Received unexpected error:
listen tcp :9003: bind: address already in use
Test:       	TestDdevXdebugEnabled
```
i.e. https://github.com/ddev/ddev/actions/runs/6273418171/job/17036856628#step:17:3502
These commits were previously on that issue and since then this test hasn't failed again.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5372"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> test: close xdebug listening port after opening to avoid "listen tcp :9003: bind: address already in use" errors

- pkg/ddevapp/ddevapp_test.go
- pkg/testcommon/testcommon.go
TestDdevPause often fails. Apparently `docker-compose stop` is a gentle stop, and may not immediately result in the expected `exited` state for containers. 
Remove the unuseful and flaky TestDdevPause
Minor simplification to ContainerCheck(), used only in a couple of tests.
> ci: remove TestDdevPause because it's flaky and unuseful

- cmd/ddev/cmd/debug-refresh.go
- pkg/ddevapp/compose_yaml.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/router.go
- pkg/ddevapp/router_test.go
- pkg/ddevapp/ssh_auth.go
- pkg/ddevapp/utils.go
- pkg/dockerutil/dockerutils.go
- pkg/dockerutil/dockerutils_test.go
Fixes 
* #5339.
To test simply restart any project with it.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5340"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: output that the container images are being built, fixes #5339

- pkg/ddevapp/ddevapp.go
People don't know what is going on during `ddev start` and so can't understand when it pauses for some time.
It can be waiting for containers to become ready, etc.
Output when key sections start (and in some cases, when they end)
Use `ddev restart`
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5370"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: provide more user info on ddev start

- pkg/ddevapp/drupal.go
@weitzman pointed out in https://discord.com/channels/664580571770388500/1156252315750256721/1156252315750256721 that `omit_containers: [db]` doesn't work with drupal9+ 
Don't try to configure the Mariadb/Mysql/Postgres things that are required for Drupal9+ if the db container is omitted.
Use `omit_containers: [db]` and try a `ddev start`. Your project won't work, but it should come up successfully.
> fix: drupal9+ shouldn't try to configure db if db container omitted

- docs/content/developers/building-contributing.md
A minor typo in the docs where the suggested date format has a hard coded year.
Fixes the date format.
> docs: fix suggested PR branch name format

- cmd/ddev/cmd/debug-refresh_test.go
On Windows [TestDebugRefreshCmd](https://buildkite.com/ddev/ddev-windows-mutagen/builds/4247#018ae11f-41f6-4caa-9624-64a8eaa1fa23) may fail due to some file being held open:
`
Received unexpected error:
--
  | remove C:\Users\testbot\tmp\ddevtest\TestDebugRefreshCmd1061869345\.ddev\traefik\config\TestDebugRefreshCmd1061869345.yaml: The process cannot access the file because it is being used by another process.`
Just don't check the error, don't fail. It doesn't matter.
> ci: don't check error in test because windows can't clean up

- pkg/ddevapp/dotddev_assets/providers/platform.yaml
Platform.sh now pauses environments if they're not "production". This breaks TestPlatformPull periodically, etc. 
This actually fixes it for regular users.
Do a `platform environment:resume` before doing anything else.
`ddev pull platform` on a paused project and on a running project.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5390"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: make sure Platform.sh environment is not paused before pull/push

- .github/workflows/pr-artifacts-comment.yml
- https://github.com/ddev/ddev/issues/5386
From what I can see, there are no problems with `nightly.link` itself, the failures for PR artifact comments are from GitHub Actions.
The current implementation of upstream [pr-comment.yml](https://github.com/oprypin/nightly.link/blob/5a34469cc7939d3c6a79ad5badbc62971145fa57/.github/workflows/pr-comment.yml) uses different technique to insert/update a bot comment (it looks for `` in the comments), but it doesn't work with forked PRs.
Also, DDEV is currently using the deprecated action `actions/github-script@v3`.
I combined two different workflows (see the changes) and used `actions/github-script@v6`.
I tested the new technique on this repo https://github.com/stasadev/ddev-pr-artifacts-comment
The change affects the current open PRs, a second bot …
> ci: change technique for PR artifact comment, fixes #5386

- docs/content/users/usage/troubleshooting.md
When we added global config for router_http*_port, we didn't update the troubleshooting instructions. It's much easier now.
Explain how to use the global router-http*-port to change basic port.
> docs: improve troubleshooting instructions for changing ports

- cmd/ddev/cmd/config_test.go
- docs/content/users/configuration/config.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/schema.json
- pkg/ddevapp/templates.go
- pkg/nodeps/values.go
Node 14 went end of life in April 2023. New versions of the Node installer do not support version 14.
NodeJS version 14 is [end of life](https://endoflife.date/nodejs).
This pull request removes support for version 14.
Users using Node 14 will need to upgrade.
> refactor: remove support for nodejs version 14

- .gitpod/images/Dockerfile
- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/config.go
- pkg/versionconstants/versionconstants.go
* https://github.com/ddev/ddev/issues/5363
The old method (using setup_X script) is deprecated.
Use the new method outlined in [https://github.com/nodesource/distributions](https://github.com/nodesource/distributions)
* https://github.com/ddev/ddev/issues/5363
> fix: update node install method, fixes #5363

- docs/content/users/install/docker-installation.md
docs: Some users of Docker Desktop for mac have gotten errors indicating that ports 80 and 443 (privileged ports) are not accessible, and implicating vmnetd.
This usually means checking the "allow privileged ports" checkbox in Docker Desktop.
<a href="https://gitpod.io/#https://github.com/ddev/ddev/pull/5388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> docs: docker desktop for mac may need extra setting

- pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
Fixes #5394. The domain name is sent to SequelAce instead of 127.0.0.1, which means that it shows in the SequelAce window title.
See #5397 however -- this was the only env var I could see which was suitable, but the docs for it are suspicious. An array here would clearly be wrong.
Do `ddev sequelace`. The new SequelAce window should show the domain, allowing the project to be identified.
> fix: pass domain/project name to `ddev sequelace`, fixes #5394

- cmd/ddev/cmd/get.go
- https://github.com/ddev/ddev/issues/5342
Changes the `$PWD` to `.ddev` config folder while the command is running.
See the issue.
> fix: command `ddev get --remove` should be run in `.ddev` config folder, for #5342

- .github/workflows/pr-artifacts-comment.yml
- #5386
`This workflow doesn't match any pull requests!` in [Add download link to PR](https://github.com/ddev/ddev/blob/7ab3e70b487aa70712b3e62290d3f38aabbe0fc6/.github/workflows/pr-artifacts-comment.yml)
After changing to a new technique for making PR artifact comments (#5396) everything looked fine until a force-pushed commit was made and no bot comment was updated.
After some debugging, I discovered that the workflow cannot find the PR after doing the force push if the PR author is another user. At first I thought it might be something with a different SHA, but it turned out to be a different user ID.
I believe the user ID check was added usptream just to make it extra unique, but I think only SHA can be used for comparison.
I run tests on my …
> ci: use only SHA to find PR number, for #5386 [skip ci]

- docs/content/users/configuration/config.md
- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/templates.go
In
* https://github.com/ddev/ddev/pull/5405 and 
* https://github.com/ddev/ddev/pull/5400
we invalidated `nodejs_version: 14` because the upstream package manager does not support it any more.
However, we don't want to break people who happen to have that in their config. 
* Allow incorrect config but warn about it
* Empty `nodejs_version` if it's the default, to try to prevent this in the future. This means people will only configure it if they want something other than DDEV's default. This is slightly intrusive, but not too much.
Here's what happens. It's not as pretty as it should be but it gets the job done:
Set `nodejs_version: 14` and `ddev start`. Use `ddev config --auto` to fix.
No new tests - the other 2 PRs handled everything.
* Release requires announcement of the v14 removal
> fix: warn about obsolete nodejs_version instead of failing

- docs/content/users/usage/troubleshooting.md
macOS Sonoma Content filtering adds new port conflict problems that can't be solved with the traditional techniques. 
* Explain how to turn off content filtering in Sonoma
* Explain use of netstat as another technique
> docs: improve port conflict troubleshooting

- pkg/ddevapp/dotddev_assets/providers/platform.yaml
Reverts ddev/ddev#5390
* #5390 did not accomplish the objective, so it doesn't make sense to leave it in there. The request has been made to just stop pausing the target environments.
> fix: revert "fix: make sure Platform.sh environment is not paused before pull/push"

- docs/content/users/install/ddev-installation.md
* #5327  
The docs suggestion does `sudo` in a place where it can eat important info. Do it early and rely on the cached status.
> docs: make sure sudo is done early in linux installation, fixes #5327

- winpkg/chocolatey/ddev.nuspec
* #5336 
The Windows installer installs nssm, and it's rarely used any more. Remove the Chocolatey dependency
> build: remove nssm as choco dependency, fixes #5336

- pkg/ddevapp/config.go
- pkg/ddevapp/ddevapp.go
- pkg/globalconfig/global_config.go
- pkg/nodeps/values.go
* #5404 
The global global config was supposed to be router_mailpit_http_port, not router_mailpit_port
Change it.
Make sure it gets set correctly with the `ddev config global` and that the old version (`router_mailpit_port`) doesn't cause trouble (will be ignored)
> fix: correct global router_mailpit_http_port, fixes #5404

- pkg/amplitude/amplitude.go
- pkg/config/remoteconfig/messages.go
- pkg/config/remoteconfig/remote_config.go
- pkg/ddevapp/amplitude_project.go
- pkg/ddevapp/instrumentation.go
* #5338 
Amplitude has so many util.TimeTrack() you can't see anything else
Remove most
DDEV_VERBOSE=true ddev list
> fix: remove many of the perf trackers from amplitude, fixes #5338

- cmd/ddev/cmd/describe.go
* #5291 
`ddev describe` shows the router as traefik even if `omit_containers[ddev-router]`
Change it
Test with router disabled
> fix: ddev describe shouldn't show router when disabled, fixes #5291

- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
With the new version constraint #5379, it was reported on both the PR as well as on https://github.com/ddev/ddev/issues/4630#issuecomment-1761998687 that it's not clear or is confusing why a built version like `v1.22.3-24-g3d90d5eeb` is not accepted with a constraint of `>= v1.22`. This is because of https://github.com/Masterminds/semver#checking-version-constraints.
This assumes that pre-releases are always included. While this invalidates any means of "excluding" pre-releases with the constraint, for general usage this will lead to less support issues and matches other less strict constraints comparisons.
`ddev config --ddev-version-constraint=">= 1.22"` should work.
> fix: always include pre-releases on version constraint checking, fixes feedback on #4630

- pkg/ddevapp/config_test.go
- pkg/ddevapp/extra_expose_test.go
- pkg/ddevapp/providerAcquia_test.go
- pkg/ddevapp/providerGit_test.go
- pkg/ddevapp/providerLagoon_test.go
- pkg/ddevapp/providerLocalfile_test.go
- pkg/ddevapp/providerPantheon_test.go
- pkg/ddevapp/providerPlatform_test.go
- pkg/ddevapp/settings_test.go
- pkg/dockerutil/dockerutils_test.go
- pkg/util/utils.go
```
$ make golangci-lint
golangci-lint: 
pkg/ddevapp/providerLocalfile_test.go:14:2: dot-imports: should not use dot imports (revive)
. "github.com/ddev/ddev/pkg/ddevapp"
^
pkg/ddevapp/providerGit_test.go:12:2: dot-imports: should not use dot imports (revive)
. "github.com/ddev/ddev/pkg/ddevapp"
^
pkg/ddevapp/providerPlatform_test.go:15:2: dot-imports: should not use dot imports (revive)
. "github.com/ddev/ddev/pkg/ddevapp"
^
pkg/util/utils.go:132:9: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
} else {
output.UserOut.Println("Please type yes or no and then press enter:")
return AskForConfirmation()
}
make: *** [Makefile:265: golangci-lint] Error 1
```
Removes dot-imports and fixes indent-error-flow.
Tests should pass as …
> ci: apply new rules from golangci-lint v1.55.0

- pkg/dockerutil/dockerutils.go
When you start a project, you always see `Network ddev_default created`.
But when you run `ddev poweroff`, there is no indication at all that `ddev_default` is removed.
With docker-compose you can see the output for the project's network when it was removed, but when #5305 comes in, there's no output for that sort of thing at all.
Outputs the message `Network ddev_default removed` (and for any other removed external DDEV created network).
1. `ddev start`
2. `ddev poweroff` - see `Network ddev_default removed`
- https://github.com/ddev/ddev/pull/5305
> feat: add output for removed network, for #5305

- cmd/ddev_gen_autocomplete/ddev_gen_autocomplete.go
- #2961
- #3085
I updated bash autocomplete and now it works OOTB (even with custom user-defined commands).
Before:
In `$HOME` and in a project autocomplete is the same:
```
$ echo $SHELL
/bin/bash
$ ddev <TAB><TAB>
auth          delete        hostname      mutagen       snapshot
clean         describe      import-db     poweroff      ssh
composer      exec          import-files  restart       start
config        export-db     list          service       stop
debug         get           logs          share         version
```
After:
In `$HOME`:
```
$ echo $SHELL
/bin/bash
$ ddev <TAB><TAB>
auth          delete        hostname      poweroff      start
clean         describe      import-db     restart       stop
completion    exec          import-files  service       version
composer …
```
> feat: update Bash and PowerShell autocomplete, fixes #2961, fixes #3085

- pkg/ddevapp/ddevapp.go
At Drupalcon Lille, @davereid was trying to do some tricky automatic database updates, and was stopped because in app.Start() the check for db mismatch was earlier than the execution of the pre-start hooks. I don't see harm in doing the pre-start hooks earlier than the test. 
Move pre-start to earlier
```
hooks:
pre-start:
- exec-host: if ! ddev debug check-db-match; then docker run --rm -v $DDEV_PROJECT-mariadb:/var/tmp/mysql busybox:stable sh -c "echo mariadb_10.4 >/var/tmp/mysql/db_mariadb_version.txt"; fi
```
or some variant of it. It worked for me. This uses the `ddev debug check-db-match` to see if the configured database is the same as the actual database, if not, it forces. Of course, there is no warranty expressed or implied here because the hook is overwriting an internal …
> feat: process pre-start hooks earlier so exec-host hooks can do more

- docs/content/users/configuration/config.md
- pkg/ddevapp/ddevapp.go
- https://github.com/ddev/ddev/issues/5292
Do not pull omitted images on `ddev start`.
1. `ddev poweroff`
2. `docker rmi $(docker images ddev/ddev-traefik-router -a -q)`
3. `ddev config global --omit-containers ddev-router`
4. `ddev start && ddev stop` should not pull `ddev-router`
5. `docker images ddev/ddev-traefik-router -a` should return an empty result
> fix: don't pull omitted images, fixes #5292

- pkg/ddevapp/wordpress/wp-config.php
* #3940 
In a Wordpress install using ddev, WP-CLI `wp config set` and `ddev wp config set` commands fail with
```
Error: Could not process the 'wp-config.php' transformation.
Reason: Unable to locate placement anchor.
```
As discussed in https://github.com/ddev/ddev/issues/3940, wordpress cli seems to look for `/* That's all, stop editing! Happy publishing. */` in order to find a "placement anchor" for config changes added via `wp config set`.
In a standard Wordpress install, `wp-config.php` includes that comment and one preceding it, like this:
```
/* Add any custom values between this line and the "stop editing" line. */
/* That's all, stop editing! Happy publishing. */
```
The addition of the second comment is the only required fix, but this PR adds the standard pair of comments to …
> fix: add comment required by wordpress for `wp config set` to work, fixes #3940

- cmd/ddev/cmd/describe.go
- docs/content/users/configuration/config.md
- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/instrumentation_test.go
- pkg/ddevapp/schema.json
- pkg/ddevapp/templates.go
- pkg/ddevapp/testdata/TestConfigMerge/fulloverridetest/components/.ddev/config.override.yaml
- pkg/ddevapp/testdata/TestConfigMerge/fulloverridetest/components/.ddev/config.yaml
- pkg/ddevapp/testdata/TestConfigMerge/fulloverridetest/expected/.ddev/config.yaml
- pkg/ddevapp/testdata/TestConfigMerge/overridetest/components/.ddev/config.last.yaml
- pkg/ddevapp/testdata/TestConfigMerge/overridetest/components/.ddev/config.yaml
- pkg/ddevapp/testdata/TestConfigMerge/overridetest/expected/.ddev/config.yaml
During a BOF you mentioned this was a bit outdated, so I updated it with what you said it needed to be 😄 
* Updated the docs!
* Updated other usages in tests which shouldn't have been relying on that. 
I don't think we have to do anything.
I think the minor modifications to tests are OK.
> fix: replace outdated nfs_mount_enabled comments with use_dns_when_possible

- pkg/util/yamltools.go
* #5385
Invalid config, especially in .ddev/config.yaml (but could happen in global_config.yaml, and might happen in customer-provided yaml) was resulting in an incomprehensible message "Unable to YamlToDict: yamlToDict: type string not handled (post-start)"
Be more generous and just ignore and warn about the invalid yaml
There are examples of config that causes the problem in https://github.com/ddev/ddev/issues/5385
```
hooks:
post-start:
- host-exec: ddev auth ssh
```
and 
```
hooks:
post-start:
```
Use these in .ddev/config.yaml and see the results.
Also we can expect that a well-formed config.yaml doesn't cause trouble.
No changes
> fix: make yamlToDict give useful information instead of error in invalid config, fixes #5385

- cmd/ddev/cmd/root.go
* #5419 
The PersistentPostRun function for the root command handles instrumentation. It was using NewApp(), which will create a new ddevapp right there in the current dir. I'm pretty sure it should be using GetActiveApp() and that will solve this.
The actual problem can also be solved by turning off instrumentation, because that's where the app is being created.
Use the techniques from
* #5419 
Also try it with and without instrumentation.
It may deserve a test. I'm not sure a test is easy.
> fix: resolve inappropriate creation of .ddev/addon-metadata, fixes #5419

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Upstream deb.sury.org has reached php8.3.0-rc3, so we should include that in our upcoming DDEV v1.22.4
* Build new ddev-php-base (because upstream has changed)
* Build new ddev-webserver (because it's what we actually use and it derives from ddev-php-base
Use it, make sure that we have rc3 of php8.3
> ci: bump ddev-php-base and ddev-webserver for php8.3.0rc3

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/config.go
- pkg/ddevapp/snapshot.go
* #5343 
* I have been confused over and over again by the docker healthcheck configurations, and they were incorrect still. 
* #5133 
* #5154 (where this wasn't done right still)
* The `start_period` is the actual time that we want to wait for things to more-or-less be ready
* The `timeout` is actually how long we'll put up with the healthcheck taking (which is normally just over a minute, based on the web container healthcheck.sh)
* On Windows we'd just rather bump this up anyway, because the mutagen sync can take some time
* When doing a snapshot restore of a large snapshot, also bump it up quite a bit
> fix: the web container startup time should be more generous, fixes #5343

- .gitpod.yml
DDEV v1.22.4 is out.
* Push new gitpod image
* `ddev debug download-images` no longer downloads `ddev-traefik-router`
> build: update .gitpod.yml for v1.22.4 release [skip ci]

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
* #5193 
Sometimes when you start a project, multiple project networks are created (e.g. `ddev-npg_default`) which prevents the project from starting.
```
Error response from daemon: network ddev-npg_default is ambiguous (16 matches found on name)
```
It doesn't happen all the time, but it's really annoying.
The idea is that if the project's docker network is created before doing the usual stuff, it can prevent the problem from occurring.
Let's make the project's docker network external (just like the `ddev_default` global network).
This PR must *not* break existing features to be considered something valuable to merge.
There is no reliable way to test this, because the issue is related to `docker-compose` (not DDEV itself), and it occurs randomly.
- …
> fix: make project network external, fixes #5193

- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/start.go
- cmd/ddev/main.go
When ddev has been compiled without AmplitudeAPIKey (as with `brew install --HEAD ddev` it shows a message warning about the situation.
However, it has been going overboard in recent versions, showing it on every command. Change it to warn only on `ddev start`. 
The message is:
> Instrumentation is opted in, but AmplitudeAPIKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.
```
unset AmplitudeAPIKey
make
ddev config global --instrumentation-opt-in=true
cd <someproject>
ddev start 
ddev exec ls 
```
The message should show at the end of ddev start but not on ddev exec.
No changes.
> fix: we shouldn't show the amplitude warning on every ddev command

- .gitpod.yml
- .gitpod/images/Dockerfile
It is easy to forget to update some packages in [Dockerfile](https://github.com/ddev/ddev/blob/34d7fd76bb9068ac1d8d304c1f928624ff0ded22/.gitpod/images/Dockerfile#L17-L19) for Gitpod after release.
Try to use the latest version all the time.
Found the solution for `go` [here](https://stackoverflow.com/a/77085404).
And it was super easy for `golangci-lint` - I just removed the hard-coded version.
```
$ docker buildx build -t ddev/ddev-gitpod-base --platform=linux/amd64 .gitpod/images
$ docker run --rm -it ddev/ddev-gitpod-base go version
go version go1.21.3 linux/amd64
$ docker run --rm -it ddev/ddev-gitpod-base golangci-lint version
golangci-lint has version 1.55.1 built with go1.21.3 from 9b20d49d on 2023-10-25T10:03:43Z
```
> build: always use the latest go and golangci-lint for gitpod [skip ci]

- pkg/ddevapp/config.go
TestExtraPackages often fails due to 
* https://github.com/oerdnj/deb.sury.org/issues/2046
Experiment with gathering more information about the problem. This is explored in
* https://askubuntu.com/a/990019/18314
* https://askubuntu.com/a/841968/18314
The suggestions have to do with disk space (this happens at docker build time) and with removing /var/lib/apt/lists
> ci: gather debugging information about possible TestExtraPackages failure

- .github/workflows/tests.yml
* We have been using significant Github workflow resources testing no-bind-mounts, but nobody uses this and it turns out not to be an important effort.
* Drupal9 is obsolete, long live Drupal10. Or at least for a year or so.
> ci: stop testing no-bind-mounts and use drupal10 by default

- docs/content/users/install/ddev-upgrade.md
The brew tap at https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/ is not specific enough and results in an error when attempting to upgrade.
This PR specifies the tap `ddev/ddev/ddev`, bringing it in line with the installation instructions at https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/
> docs: specify ddev tap in upgrading instructions for macOS with brew

- docs/content/developers/brand-guide.md
- docs/content/developers/building-contributing.md
- docs/content/developers/buildkite-testmachine-setup.md
- docs/content/developers/github-selfhosted-setup.md
- docs/content/developers/index.md
- docs/content/developers/project-types.md
- docs/content/developers/release-management.md
- docs/content/developers/remote-config.md
- docs/content/developers/testing-docs.md
- docs/content/developers/writing-style-guide.md
- docs/content/users/configuration/config.md
- docs/content/users/extend/additional-services.md
- docs/content/users/extend/customization-extendibility.md
- docs/content/users/usage/database-management.md
- docs/content/users/usage/developer-tools.md
- mkdocs.yml
- version-history.md
In ddev.readthedocs.io docs search, sometimes the links we want people to find first aren't the ones they find
Based on https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+boost#search-boosting we are supposed to be able to affect this. This is a first attempt.
Visit the docs built for this PR and see if the search boosting implemented here works at all.
https://ddev--5500.org.readthedocs.build/en/5500/
> docs: implement search priority setting using mkdocs-material

- README.md
Modifies  README.md to add the missing logos
However, it requires this PR to get merged first https://github.com/ddev/ddev.com/pull/134
Otherwise, the sponsors will break on GitHub's dark theme. Due to the asset not being there.
Fixes #5492 
Check that the README sponsors load well on a light GitHub theme and a dark theme.
No
> docs: adds a dark theme compatible svgs, fixes #5492

- README.md
relates to #5501 #5492
The #gh-dark-mode-only and #gh-light-mode-only tags don't seem to be working so we are switching to the picture tag which is better since it would read correctly outside of github.
It switches from GitHub specific markdown language to the picture tag.
> docs: adds a dark theme compatible svgs, fixes #5492 #5501

- pkg/ddevapp/dotddev_assets/providers/platform.yaml
When testing Upsun, I copied the `platform.yaml` and checked its settings.
When I wanted to customize it, I removed the `#ddev-generated` line and ran `ddev restart`, but the file was reset.
That's because there is a second `#ddev-generated` in this file.
Removes `#` from the extra `#ddev-generated`.
Removes an extra line at the end of the file.
Adds a space between `#set -x` - to make it look like others `# set -x` in this file.
1. Use a regular DDEV binary (no need to generate a new binary for this PR)
2. Run `ddev start`
3. Edit `.ddev/providers/platform.yaml` - remove the `#ddev-generated` from the top.
4. Run `ddev stop` - see that file is reset.
5. Edit `.ddev/providers/platform.yaml` - remove the `#ddev-generated` from the top and edit the second entry of `#ddev-generated` on the …
> fix: allow editing for platform.yaml

- .github/workflows/pr-check.yml
Allows the PR title to hold an uppercase.
relates #5502
It changes the regular expression to allow uppercase letters.
> docs: allow uppercase letters on pr titles.

- .github/workflows/contributors.yml
Add monthly contributor report, see https://github.com/github/contributors/blob/main/README.md
> build: add monthly contributor report

- .github/workflows/tests.yml
On #5516 we added the test, but it didn't run because testcmd was not part of the make target.
> fix: allow testcmd to run as make tarket on `pull-push-test-platforms`, follow up to #5516

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
Mailpit is outdated.
Bumps the mailpit version to the recent release.
`ddev launch -m` -> About -> v1.9.10
This project (https://github.com/pushpak1300/cypress-mailpit) cannot be used at the moment because it uses recent API features which aren't available in v1.8.1.
Bumps the mailpit version to v1.9.10.
> build: use latest version of mailpit at image build time

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/poweroff.go
- pkg/dockerutil/dockerutils.go
- https://github.com/docker/compose/issues/6532#issuecomment-769263484
- #5193
Sometimes when you start a project, multiple project networks are created (e.g. `ddev-your-project_default`) which prevents the project from starting.
```
Error response from daemon: network ddev-your-project_default is ambiguous (16 matches found on name)
```
The project network is *internal* (created from `docker-compose.yaml`) in v1.22.4, and we cannot manipulate its state.
But we can make it *external* (created programmatically from DDEV) in v1.22.5 and control it however we want.
This set of PRs are intended to fix the need for user to do manually `docker network rm`, because the project cannot be started when there are duplicate networks.
An attempt has been made to fix this on the Docker side (but it …
> fix: ensure no duplicates for docker networks, fixes #5193

- docs/content/developers/building-contributing.md
When I first starting working with tests I got used to doing make testpkg TESTARGS="-run Test.." and I didn't know why this hand't worked with commands. Because we are providing the test as argument I gured we can include all tests in the make command so that this is less prone to happen.
> docs: use make test instead of make testpkg

- docs/content/users/usage/developer-tools.md
In
* https://github.com/ddev/ddev/pull/5328
the ability to use drush on the host on a Drupal project was removed, but the docs weren't removed. This removes them.
> docs: remove the docs about obsolete drush-on-host feature

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/poweroff.go
- pkg/dockerutil/dockerutils.go
- pkg/testcommon/testcommon.go
- #5305
- #5508
- #5193
After switch to external project networks in #5305, there were issues with compatibility between different DDEV version, which made downgrade not smooth.
The last issue with downgrade from HEAD to v1.22.4:
```
$ ddev start
...
Building project images... 
Project images built in 3s. 
time="2023-11-07T08:29:14-07:00" level=warning msg="a network with name ddev-d10_default exists but was not created by compose.\nSet `external: true` to use an existing network" 
network ddev-d10_default was found but has incorrect label com.docker.compose.network set to "" 
Failed to start d10: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-d10 docker-compose -f /Users/rfay/workspace/d10/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 1', stdout='', …
```
> fix: internal project network with duplicate check, revert for #5305

- docs/content/users/install/docker-installation.md
with the release of colima 0.6.0 it is possible to add colima to the macos login items by using `brew services`. just a small update to the docker-installation.md file. i am just not sure if it makes sense to add `brew services list` for educational services as well so people are able to validate what the command actually did, where things where copied, and verify everything was done as expected.
> docs: add instructions how to add colima to the macos login items

- .github/workflows/colima-tests.yml
Colima tests have been failing even with 0.6.2, apparently due to 
* https://github.com/abiosoft/colima/issues/856
* Update to run on macos-13 instead of 12 (which was "latest")
* Remove the previous fix to reinstall qemu
* Revert colima to 0.5.6
* Test with vz/virtiofs
> ci: revert colima to 0.5.6, use macos-13

- cmd/ddev/cmd/networks_test.go
- #5508
Docker networks can be created programmatically with the same name (this is no longer possible with Docker >=25.x.x):
- https://github.com/moby/moby/pull/46251
This test creates two networks with the same name, removes duplicates, and checks that everything is OK.
See `TestNetworkDuplicates`
> test: check for duplicate networks, for #5508

- pkg/ddevapp/router_compose_template.yaml
- #5542
Adds a label, does a little reformatting of the router template.
1. `ddev start`
2. `docker inspect $(docker ps -f name=router -q) | jq '.[0].Config.Labels'` check for `com.ddev.site-name`
3. `ddev poweroff`
> fix: add label for ddev-router, fixes #5542

- docs/content/users/configuration/config.md
- docs/content/users/extend/customization-extendibility.md
- pkg/ddevapp/config.go
- pkg/ddevapp/nodejs_test.go
- pkg/ddevapp/templates.go
- pkg/nodeps/values.go
I figured this one was quick to do if you want to give it a try.
> feat: replace deb.nodesource.com with n, fixes #5509

- .github/workflows/colima-tests.yml
With 
* https://github.com/abiosoft/colima/pull/884
the problem with Colima v0.6.* may be solved:
* https://github.com/abiosoft/colima/issues/856
This changes the Colima test to use latest release, which may be working.
> ci: try Colima latest to fix serious docker failures

- docs/content/users/install/ddev-installation.md
I just did a WSL2 install and it's no longer necessary to get the MS store version.
> docs: Remove WSL2 step of installing from store

- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/utils.go
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
- https://github.com/ddev/ddev/issues/5445
Runs validation check for every projects that you pass to any DDEV command that uses args, so fixes more than just `ddev start`.
See the issue.
> fix: add project config validation when using args, fixes #5445

- .github/workflows/pr-artifacts-comment.yml
- https://github.com/ddev/ddev/pull/5551
It failed here https://github.com/ddev/ddev/actions/runs/6935350964/job/18865324443#step:2:460
I don't know what exactly is wrong here, it tried to get this broken URL (contains javascript `object` inside):
```
https://api.github.com/repos/ddev/ddev/pulls?status=200&data=%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D%2C%5Bobject%20Object%5D
```
I looked into GitHub docs https://octokit.github.io/rest.js/v20 for examples and modified our workflow for  `paginate.iterator()`
Create a new PR after merging this one, a bot comment with …
> build: bump actions/github-script from 6 to 7

- .githooks/README.md
- .github/RELEASE_NOTES_TEMPLATE.md
- CONTRIBUTING.md
- containers/ddev-ssh-agent/README.md
- docs/content/developers/maintainers.md
- docs/content/users/install/performance.md
- docs/content/users/install/shell-completion.md
- docs/content/users/quickstart.md
- pkg/ddevapp/testdata/TestApptypeDetection/magento/README.md
It seems to only happen on master, but textlint is stumbling on some usages of 'just'
Remove them.
> docs: remove 'just' from several places to avoid triggering textlint

- docs/content/developers/building-contributing.md
It is documented how to [test a PR in macOS with Homebrew](https://ddev.readthedocs.io/en/latest/developers/building-contributing/#testing-a-pr), but not by installing a downloaded binary in the $PATH.
Documents how to test a PR by installing a downloaded binary in the $PATH, to be used for example in Linux and MacOS.
> docs: add instructions for testing a PR by installing a downloaded binary in the $PATH

- .spellcheckwordlist.txt
- cmd/ddev/cmd/import-files.go
- docs/content/users/usage/cli.md
- docs/content/users/usage/commands.md
* #5474 
The user there did not understand that the tarball should not contain the top-level directory. I imagine this wasn't the first time.
Update docs and help.
> docs: improve discussion of tarball to be imported by ddev import-files, fixes #5474

- pkg/version/version.go
In `ddev version` and related things (including Amplitude) the docker platform is shown as the hostname, which isn't very useful
Make it report `linux-docker`
On linux, `ddev version`
> fix: Add linux-docker platform for non-wsl2 docker-ce

- cmd/ddev/cmd/utils.go
- https://github.com/ddev/ddev/pull/5452#pullrequestreview-1742421480
> `ddev start -a` doesn't validate config
Adds validation when you pass `--all` flag for a DDEV command.
1. Break some config value in the project's `.ddev/config.yaml` (e.g. `php_version: "test"`)
2. Run `ddev start -a` and immediately see the error.
> fix: add config validation for --all flag, for #5452

- .buildkite/testbot_maintenance.sh
- docs/content/developers/buildkite-testmachine-setup.md
Setup buildkite agent for macOS remote machines.
Simplify or make certain steps clearer.
> docs: improve steps for macos buildkite agent

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
- #5529
```
ddev exec sudo apt update | grep upsun
Get:7 https://dl.cloudsmith.io/public/platformsh/upsun-cli/deb/debian bullseye InRelease [5079 B]
```
I think we don't really want the Upsun repo to be pulled up on `sudo apt update`.
1. It's not needed here, because not everyone uses it.
2. This can lead to unpredictable behavior if someone has a post-start hook for `sudo apt update && sudo apt upgrade`, a new untested version of Upsun can be installed, and then who knows how `ddev pull upsun` will behave.
Installs only `upsun` binary, without any extras.
```
ddev exec upsun version
ddev pull upsun -y --environment UPSUN_PROJECT=xxx,UPSUN_ENVIRONMENT=yyy --skip-files
```
> build: install only binary from Upsun, for #5529

- pkg/ddevapp/drupal/drupal10/settings.ddev.php
- pkg/ddevapp/drupal/drupal8/settings.ddev.php
- pkg/ddevapp/drupal/drupal9/settings.ddev.php
It is not a big problem, but the order of host, port, driver is switched, causing a slight "hmm" when you scan the values.
```
$host = "db";
$port = 3306;
$driver = "mysql";
$databases['default']['default']['database'] = "db";
$databases['default']['default']['username'] = "db";
$databases['default']['default']['password'] = "db";
$databases['default']['default']['host'] = $host;
$databases['default']['default']['driver'] = $driver;
$databases['default']['default']['port'] = $port;
```
Makes the order identical to the one in the default settings.php file:
```
* $databases['default']['default'] = [
*   'database' => 'databasename',
*   'username' => 'sqlusername',
*   'password' => 'sqlpassword',
*   'host' => 'localhost',
*   'port' => '3306',
*   'driver' => 'mysql',
[...]
``` …
> refactor: order host, port, driver the same both places in Drupal 10 settings file

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/versionconstants/versionconstants.go
deb.sury.org has built latest packages and now we can do php 8.3.0. In addition, now only 3 packages are missing from php8.3, memcached, redis, and xdebug
* Pushes ddev-php-base, ddev-webserver with new packages
* Updates TestDdevXhprof to test on 8.3
Use it, make sure php8.3 is 8.3.0
Previously TestDdevXhprofEnabled was disabled for 8.3, it should work now.
* https://github.com/oerdnj/deb.sury.org/issues/2034
* Announce 8.3.0 and related extensions
> build: update images to get get php8.3.0 and related new packages

- .gitpod.yml
DDEV v1.22.5 is out.
Push new gitpod image.
> build: update .gitpod.yml for v1.22.5 release [skip ci]

- .buildkite/macos-rancher-desktop.yml
- .buildkite/test.sh
Multiple failures of rancher-desktop tests (see https://github.com/ddev/maintainer-info/issues/1#issuecomment-1828804959) have resulted in the docker context being left as "default" but the default context isn't wired to any provider. Orbstack and Docker Desktop both claim "default", but Rancher Desktop doesn't.
* Don't set context to default
* Leave the provider running that was running at the end of test
We'll see if this works.
**This temporarily allows rancher to run on this PR, but that should be removed before pulling**
> ci: don't set default context to default - fix rancher desktop failures

- docs/content/users/extend/custom-commands.md
> docs: add note about needing to restart for global commands to be picked up

- mkdocs.yml
The mkdocs-material "search.highlight" and "search.share" features weren't very useful, and the "search.highlight" just messed up URLs when you were trying to share with somebody.
Use the docs at https://ddev--5588.org.readthedocs.build/en/5588/ and do searches. It should work fine without the highlighting.
> docs: remove search suggestions and share

- pkg/ddevapp/mailpit_test.go
- pkg/ddevapp/router_test.go
* #5578
TestMailpit fails intermittently on Rancher Desktop
This may be due to the mailpit API coming up after our healthcheck says it should be ready, because we're not polling the API.
Wait in the test a few seconds if necessary
It's possible this could also be fixed by adding more extensive healthcheck.sh to check the mailpit API, but that seems like overkill for something that is not used a huge amount.
> ci: make TestMailpit and TestProjectPortOverride more forgiving of Rancher Desktop, fixes #5578

- pkg/version/version.go
`ddev version` with Rancher Desktop was showing `linux-docker` instead of `rancher-desktop`
`ddev version` with Rancher Desktop running to see what it says for docker platform.
> fix: rancher desktop docker-platform should not report linux-docker

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/os_warnings.go
- pkg/ddevapp/os_warnings_darwin.go
- pkg/globalconfig/performance_mode.go
* https://github.com/ddev/ddev/issues/5590
* If `--no-bind-mounts` is set it forces mutagen behavior. Normally people don't want it, it's a mistake to set it.
* Running DDEV under rosetta by accident causes lots of pain. Prevent it.
* Detect rosetta and error out
* Warn if --no-bind-mounts. 
* Try doing `ddev start` on macOS arm64 with the amd64 version in this PR
* Try start on your normal architecture with `ddev config global --no-bind-mounts`
* Verify that `ddev describe` shows actual performance-mode.
> fix: don't let people run ddev under rosetta, report no-bind-mounts behavior, fixes #5590

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/ddevapp/ddevapp_test.go
- pkg/versionconstants/versionconstants.go
At release of DDEV v1.22.5, php8.3-xdebug, redis, and memcached were not yet available. Now they are
Build them and test them.
Just try using xdebug with php 8.3
> fix: php8.3-xdebug and redis, memcached now available

- cmd/ddev/cmd/commands.go
- pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
- pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
- pkg/ddevapp/global_dotddev_assets/commands/host/launch
- pkg/ddevapp/global_dotddev_assets/commands/host/mysqlworkbench.example
- pkg/ddevapp/global_dotddev_assets/commands/host/querious
- pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
- pkg/ddevapp/global_dotddev_assets/commands/host/sequelpro
- pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
* #2688 
Host shell commands don't always need to start project
* No auto-start for host commands
* Host commands that need project running can start it
Try out `ddev launch` and the various database launcher commands
Try out `ddev self-upgrade` and it should not auto start, or try another custom host command.
* We probably need to visit some add-ons that provide custom commands and update them if needed.
> fix: dont auto start host custom commands, fixes #2688

- .github/workflows/colima-tests.yml
- https://github.com/actions/setup-python/issues/577
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.12
Target /usr/local/bin/2to3-3.12
already exists. You may want to remove it:
rm '/usr/local/bin/2to3-3.12'
To force the link and overwrite all conflicting files:
brew link --overwrite python@3.12
To list all files that would be deleted:
brew link --overwrite --dry-run python@3.12
Possible conflicting files are:
/usr/local/bin/2to3-3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3-3.12
/usr/local/bin/idle3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/idle3.12
/usr/local/bin/pydoc3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/pydoc3.12 …
```
> ci: fix Python conflicts in Colima tests

- docs/content/users/usage/database-management.md
Fix command documentation for `pg_dump`.
The command is `pg_dump`, not `pgdump`.
> docs: fix invalid command reference, `pgdump`

- cmd/ddev/cmd/networks_test.go
- pkg/ddevapp/app_compose_template.yaml
- pkg/dockerutil/dockerutils.go
- #5611
This is a regression.
The project's network is created programmatically and the MTU value is not set, since it is declared only in the `docker-compose.yaml` file and there is no way to modify the network after it is created.
This PR returns the MTU value with a small refactoring.
I don't know if this PR can be checked directly in Gitpod, so my way to check is:
1. Checkout this PR locally
2. Modify the source code to reverse the check for Gitpod, look at this change:
```go
if nodeps.IsGitpod() {
netOptions.Options = map[string]any{
"com.docker.network.driver.mtu": "1440",
}
}
```
Add `!` to `nodeps.IsGitpod()`:
```go
if !nodeps.IsGitpod() {
netOptions.Options = map[string]any{
"com.docker.network.driver.mtu": "1440",
}
}
```
3. `make build`
4. `ddev start`
5. `docker inspect …
> fix: return MTU 1440 for Gitpod, fixes #5611

- cmd/ddev/cmd/root.go
- cmd/ddev/cmd/root_help_json.go
- #5567
Replaces the default help function with one that outputs a JSON-formatted representation of a command when the `--json-output` flag is used.
Run any version of the help command or `-h` flag in conjunction with the `--json-output` (or `-j`) flag, e.g:
- `ddev help -j`
- `ddev auth -hj`
- `ddev auth ssh -hj`
I haven't added tests yet, because I want to make sure the approach is correct and acceptable before I do so. I wouldn't want to write tests only for them to be entirely invalidated by sweeping changes required in the implementation.
Once a maintainer has told me that the approach for the implementation is good, I'll add some tests.
#5567 
N/A
This is my first time contributing here and my first time writing anything in go - so it's likely I've done things in a completely …
> fix: ensure help information respects `--json-output` flag, fixes #5567

- pkg/ddevapp/config.go
- #5620
We must not allow `apt-get update` to fail if some repository is down, because it can stop the webserver from starting.
Allows `apt-get install` to continue after a fail for `apt-get update`.
> fix: do not fail on `apt-get update` for extra packages, for #5620

- containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
- #5238
Enables all ddev-webserver tests for PHP 8.3 after its release.
> ci: enable all ddev-webserver tests for PHP 8.3, for #5238

- cmd/ddev/cmd/snapshot.go
When you run `ddev snapshot`, it doesn't tell you how to restore the DB. It's easy to assume you use import-db command, which leads to #5621.
Add to the message output after a snapshot is created to tell the user how to restore snapshots.
> feat: add detail about restore command to snapshot command output, fixes #5621

- cmd/ddev/cmd/xdebug_test.go
- docs/content/users/configuration/config.md
- docs/content/users/debugging-profiling/step-debugging.md
- docs/content/users/debugging-profiling/xdebug-profiling.md
- docs/content/users/usage/cli.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
- #3593 
Adds new "toggle" argument to the `xdebug` command
1. Run `ddev xdebug toggle` - see it enable xdebug
1. Run `ddev xdebug toggle` - see it disable xdebug
Optionally run `ddev xdebug status` inbetween to see that the status has _actually_ changed.
Added tests to validate that `ddev xdebug toggle` outputs the correct text to indicate the new status, and that running `ddev xdebug status` afterwards reports that the status was in fact toggled.
I'm not sure how to run tests locally so just wrote them blind and hoping they pass - but they're based on existing tests and it seems pretty straight forward so should be fine.
#3593 
I don't think this has any other ramifications.
I wanted to also change the default for `ddev xdebug` to be a shortcut for `ddev xdebug toggle` (it's currently a …
> feat: add toggle arg to xdebug command, fixes #3593

- .gitpod.yml
DDEV v1.22.6 is out.
Push new gitpod image.
> build: update .gitpod.yml for v1.22.6 release [skip ci]

- .buildkite/macos-rancher-desktop.yml
We forgot to disable rancher-desktop except on master again after getting it stabilized.
> ci: rancher desktop test only on master [skip ci]

- .github/ISSUE_TEMPLATE/config.yml
- docs/content/developers/maintainers.md
- docs/content/users/support.md
- docs/content/users/usage/faq.md
- mkdocs.yml
- pkg/ddevapp/testdata/TestApptypeDetection/magento/README.md
I happened to notice that our published discord link was landing people in an obsolete channel, quite confusing. This one has no expiration date and lands in #welcome - It's possible we should just land people in #support, but later.
> docs: update discord link [skip ci]

- README.md
https://github.com/vuejs/vue
https://github.com/withastro/astro
https://github.com/laravel/laravel
https://github.com/lando/lando
https://github.com/tailwindlabs/tailwindcss
https://github.com/vercel/next.js/
After looking at some popular open-source repos it seems like we could switch some items around. 
This PR switches the order of certain items.
> docs: update and reorganize readme.md

- README.md
- docs/content/users/configuration/experimental.md
Added links to the Quickstarts from the experiment page
As I stated in issue
* #5171, I overlooked the quickstarts the first time, so I put helpful links
It adds links
None
No tests needed for docs
As I stated in issue#5171, I overlooked the quickstarts the first time, so I put helpful links
None
> docs: link to experimental CMS quickstarts

- pkg/ddevapp/config.go
```
$ ddev config --project-tld=""
failed to validate config: the test-project project has an invalid hostname: test-project.. See https://en.wikipedia.org/wiki/Hostname#Syntax for valid hostname requirements
```
It is not clear what hostname is in the error, whether it is `test-project.` or `test-project..`
Adds quotes:
```
$ ddev config --project-tld=""
failed to validate config: the test-project project has an invalid hostname: 'test-project.', see https://en.wikipedia.org/wiki/Hostname#Syntax for valid hostname requirements
```
> refactor: add quotes for the hostname error for better visibility

- README.md
- #5513
https://github.com/ddev/ddev/actions/runs/7250457772/job/19750683700?pr=5648#step:10:9
```
README.md:13 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## Documentation"]
README.md:16 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## Questions"]
README.md:17:120 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
```
Fixes `markdown-lint` errors.
> docs: add missing blank lines to readme.md, for #5513

- docs/content/users/install/ddev-installation.md
I was trying to follow the guide and something has probably changed in codespaces since then. I found postAttachCommand works though
> docs: GitHub Codespaces: Adjust examples to make sure docker is running 

- docs/content/users/topics/sharing.md
The following section contains a typo [Sharing - WordPress: Change the URL](https://ddev.readthedocs.io/en/stable/users/topics/sharing/#wordpress-change-the-url-with-wp-search-replace) the `snapshot` command in the second bullet point has a typo.
Changed `shapshot` to `snapshot`
Review the file change
> docs: fix typo in sharing.md

- .buildkite/testbot_maintenance.sh
Noticed a wrong formula in tests:
```
Error: No available formula with the name "postgresql-client". Did you mean postgrest?
```
https://buildkite.com/ddev/wsl2-docker-inside/builds/3039#018c9045-77f3-48e4-879b-01dae0cfaf66/99-116
Uses the same formula from macOS setup.
> ci: fix PostgreSQL client for testbot on WSL2

- pkg/ddevapp/traefik_config_template.yaml
- #5346
Disables autodetect for Content-Type in Traefik project yaml config.
Note that this fix needs to be reverted when Traefik 3 is out.
From https://github.com/ddev/ddev/issues/5346#issuecomment-1860409926
I could reproduce it when just created a fresh TYPO3 Install (Apache Webserver) and then in the Backend (Install Tool) under "Environment" and "Environment Status" I get the messages mentioned in my first post. After the changes I mentioned there there are no more unexpected server responses listed.
This fix is not needed in the upcoming Traefik 3:
- https://github.com/traefik/traefik/pull/9546
> fix: disable Content-Type auto-detection for Traefik 2, fixes #5346

- cmd/ddev/cmd/config-global_test.go
- pkg/ddevapp/config.go
- pkg/globalconfig/global_config.go
* #4290
@rpkoller pointed out that the global_config.yaml would be more useful if it just *specified* ddev.site as the project_tld.
Make it explicit in the config.
> fix: global project_tld should default to 'ddev.site', not empty, fixes #4290

- pkg/globalconfig/schema.json
While editing the global config file, VScode reported 3 invalid keys.
Strangely, after a couple of minutes, the warning disappeared. However, the same 3 keys reported invalid again after a system restart.
The apostrophes also displayed a warning in VSCode:
"The character U+2019 "’" could be confused with the ASCII character U+0060 "`", which is more common in source code."
This PR 
- fixes a single typo.
- adds the missing keys to the the global schema file.
- replaces apostrophes with single quote
I understand apostrophes vs. single quotes is a personal preference. 
My intention is to remove warnings displayed when using the following setting: 
`"editor.unicodeHighlight.ambiguousCharacters": true,`.  We can revert that commit, as required.
> fix: update global schema

- .github/workflows/colima-tests.yml
- cmd/ddev/cmd/composer-create_test.go
- cmd/ddev/cmd/config.go
- cmd/ddev/cmd/config_test.go
- cmd/ddev/cmd/testdata/TestCmdGet/example-repo/tests/test.bats
- docs/content/users/quickstart.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/config.go
- pkg/ddevapp/config_test.go
* #5498
We've been pestering people about the project type not matching (empty) codebase, and about creating the docroot for a long time, and it doesn't help anybody. They want to create the empty project, and they want us to create the docroot.
* Don't warn about empty codebase when `ddev config --project-type=xxx`
* Warn about mismatched codebase (different base detected) but do what they say to do
* Always create docroot if it doesn't exist.
* Deprecate `--create-docroot` flag
Try a lot of things with empty projects, etc.
Minor updates to existing tests
> fix: stop warning about empty app type or docroot creation, fixes #5498

- cmd/ddev/cmd/describe.go
- docs/content/users/usage/commands.md
- docs/content/users/usage/developer-tools.md
- pkg/ddevapp/global_dotddev_assets/commands/host/mailpit
- https://github.com/ddev/ddev/issues/5627
Adds a new `ddev mailpit` host command.
A lot of the code is copied directly from `launch`, which is the same way [adminer](https://github.com/ddev/ddev-adminer/blob/main/commands/host/adminer) and [phpmyadmin](https://github.com/ddev/ddev-phpmyadmin/blob/main/commands/host/phpmyadmin) work.
Run `ddev mailpit` - it should perform the same as `ddev launch -m`
Added a new test right next to the `TestLaunchCommand` test, with a lot of the same code since it's effectively testing the same thing.
https://github.com/ddev/ddev/issues/5627
No deployment ramifications that I'm aware of.
Once https://github.com/ddev/ddev/pull/5525 is merged, this command (and the adminer/phpmyadmin commands) can be vastly simplified.
> feat: add mailpit command (alias of launch -m), fixes #5627

- .github/workflows/master-build.yml
- .github/workflows/pr-build.yml
- #5648
Go to https://github.com/ddev/ddev/actions/runs/7340705862?pr=5661 and click on the artifact and see:
```
Failed to generate URL to download artifact.
```
There is no update guide at the moment, go back to `actions/upload-artifact@v3` for now.
See 
- https://github.com/actions/upload-artifact/issues/472
> build: revert bump actions/upload-artifact from 3 to 4, for #5648

- docs/content/users/install/ddev-installation.md
- scripts/install_ddev_wsl2_docker_desktop.ps1
- scripts/install_ddev_wsl2_docker_inside.ps1
* #5667
Prevent people from accidentally using WSL v1
* Add more to docs about WSL v2
* Make the automated scripts check for WSL_INTEROPE
This requires careful manual checking on a Windows machine, using both WSL v1 and v2.
I may be able to do that but this certainly can't go in without manual testing, so leaving it draft until tested.
> fix: make sure wsl v2 is used, not wsl v1, fixes #5667 [skip ci]

- docs/content/users/quickstart.md
People have been stumbling over the fact that `--create-docroot` is no longer in the quickstarts.. because it's removed in latest dev versions. But it's required in latest stable.
Temporarily revert the changes to the quickstarts and re-add `-- create-docroot`
This PR should be reverted before the next release.
> docs: temporarily revert docs on not needing --create-docroot

- docs/content/developers/building-contributing.md
Per https://github.com/ddev/ddev/pull/5702#issuecomment-1902081714 we had a typo in the URL link for a PR, this fixes it
> docs: fix gitpod PR link

- containers/ddev-webserver/ddev-webserver-base-files/etc/apache2/mods-available/mime.conf
- containers/ddev-webserver/ddev-webserver-base-files/etc/nginx/nginx.conf
- pkg/versionconstants/versionconstants.go
This add the correct MIME type for the Javascript file extension for Modules `.mjs` and for CommonJS `.cjs`
CJS, MJS, and .JS are file extensions used to denote different types of JavaScript files. Here's the difference between them:
The `.js` extension is the most common file extension for JavaScript files. It is used to indicate that a file contains JavaScript code. `.js` files can be executed in different JavaScript environments, such as web browsers, servers, and other JavaScript runtime environments.
CommonJS is a module system for JavaScript used in server-side environments like Node.js. The CJS module format allows you to define modules using the `require` and `module.exports` syntax. In CommonJS, each file is treated as a separate module, and you can import/export functionality …
> fix: Add correct mime types for Javascript

- pkg/ddevapp/craftcms.go
The `CRAFT_WEB_URL` env variable is not necessary for a Craft project, and prevents multi-site features from working.
Does not manage `CRAFT_WEB_URL`.
It also removes the comment about backward compatibility, as it isn't quite true. While `PRIMARY_SITE_URL` isn't an "official" var that Craft uses, it is a de-facto standard, as [Craft's installer script](https://github.com/craftcms/cms/blob/c905cc975a57ee3e41a317adf8cd7e303353a35b/src/console/controllers/InstallController.php#L189) will attempt to set it, and it is helpful to have the primary site set to reference in your config.
Start a craftcms ddev project:
```
ddev config --project-type=craftcms --docroot=web --create-docroot
touch .env
ddev start
```
Ensure `CRAFT_WEB_URL` was not written to `.env` (command should have no output):
``` …
```
> fix: remove CRAFT_WEB_URL, fixes #5665

- cmd/ddev/cmd/logs.go
`ddev logs` doesn't support JSON formatted output, and there's no clear way to add that functionality given the way the logs are currently fetched and outputted.
This is discussed in #962 
We don't display the flag when running `ddev help logs` or `ddev logs -h`.
This is the same way this is handled for the composer command (see [composer.go](https://github.com/ddev/ddev/blob/9b30cac3f0c7201da56611b5ed4cde6fead56de8/cmd/ddev/cmd/composer.go#L51-L56)) and custom commands (see [commands.go](https://github.com/ddev/ddev/blob/9b30cac3f0c7201da56611b5ed4cde6fead56de8/cmd/ddev/cmd/commands.go#L232-L238))
Run `ddev help logs` and `ddev logs -h` - the `--json-output` flag shouldn't be shown as an option.
No automated tests added - I couldn't find associated tests for composer or for custom …
> fix: remove --json-output flag from `logs` command, fixes #962

- docs/content/users/install/shell-completion.md
The 'Shell Completion & Autocomplete' documentation page is difficult to follow and comprehend due to duplication and, in parts, convoluted logic. In particular, there is repetition of the instructions for obtaining the tar archive of completion scripts, and such instructions vary. DDEV version numbers also vary and are outdated in various places.
Overhaul of much of the page for clarification, conciseness, updating of version numbers, and to avoid duplication. In particular, provide instructions for obtaining the tar archive of completion scripts in **just one place**, and link to it from the individual instructions for specific scripts.
See https://ddev--5701.org.readthedocs.build/en/5701/users/install/shell-completion/
No tests needed. Just documentation.
> docs: Overhaul Shell Completion & Autocomplete documentation

- .spellcheckwordlist.txt
- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/testdata/TestCustomCommands/global_commands/host/testhostglobal-noproject
- docs/content/users/extend/custom-commands.md
- pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Custom global host commands currently only be run inside a project directory - even if they don't need a project in order to do their stuff.
A great example of this is `ddev self-upgrade` which should be able to run from anywhere - but currently it has to be run from inside a project directory.
This PR adds a new `CanRunGlobally` annotation. If custom global host commands set this annotation to `true`, they will be added to the cobra command set, and can be run from anywhere, even outside project directories.
1. Run `ddev help` - you should see the `self-upgrade` command there.
1. Run `ddev self-upgrade` - it should work from anywhere, even outside a project directory.
1. Add `## CanRunGlobally: true` to a custom global host command, then perform the first two steps again, but with your …
> feat: allow global host commands to be run from anywhere, for #4416

- pkg/ddevapp/router_compose_template.yaml
- #5705
> API error (500): Could not kill running container d8079abded3b448b54fc3d22bc0abfe10ffbeb69cd7066027655bbf5598992d5, cannot remove - container d8079abded3b PID 1968501 is zombie and can not be killed. Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes
The error suggests to use `init`, it doesn't harm to try it for `ddev-router`:
> Use the --init option when creating containers to run an init inside the container that forwards signals and reaps processes
I cannot reproduce this error, at least it should not break the tests. See the issue.
- https://stackoverflow.com/questions/49162358/docker-init-zombies-why-does-it-matter
> fix: use init option to prevent zombie ddev-router, for #5705

- pkg/ddevapp/dotddev_assets/providers/acquia.yaml
* #5697
The acli output for downloaded database has changed.
Parse the new output
> fix: acli output has changed, capture the output file correctly, fixes #5697

- docs/content/users/extend/customizing-images.md
Several recent discussions in Discord have shown people floundering with adding extra PHP extensions. This adds more detail about how to add both deb.sury.org-supported extensions and pecl extensions.
* https://discordapp.com/channels/664580571770388500/1195343397238616124
* https://discordapp.com/channels/664580571770388500/1197477136215330827
Review new content at https://ddev--5715.org.readthedocs.build/en/5715/users/extend/customizing-images/#adding-php-extensions (and a bit above there)
> docs: expand docs on PHP extension installation, including pecl

- containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof/xhprof_prepend.php
- docs/content/users/debugging-profiling/xhprof-profiling.md
- pkg/ddevapp/dotddev_assets/xhprof/xhprof_prepend.php
xhprof_prepend.php uses:
```
xhprof_enable(XHPROF_FLAGS_CPU + XHPROF_FLAGS_MEMORY);
```
This makes xhprof unnecessary slow. (~ 50% more overhead on function calls)
It uses just:
```
xhprof_enable(XHPROF_FLAGS_MEMORY);
```
Ensure that xhprof output does no longer show the CPU columns and generally has less function call overhead.
Tests should not be affected, because they only test the existence of a run and not the run itself.
#5712 
None
> fix: make xhprof faster, fixes #5712

- docs/content/users/providers/platform.md
- pkg/ddevapp/dotddev_assets/providers/platform.yaml
…an one app under your env.
Today there is no option to choose an app when pulling data from platform.sh using ddev pull platform
Adding new env variable support PLATFORM_APP, when this variable exists we are adding --app flag 
https://github.com/ddev/ddev/issues/5727
> feat: Platform.sh specific app pull, fixes #5727

- docs/content/users/debugging-profiling/xhprof-profiling.md
- docs/content/users/quickstart.md
`ddev drush uli` generates a one-time link to the page for editing the uid1 (admin) account details. If the site is opened with that, there is no need to also run `ddev launch`, so that is confusing.
Add instructions on how to open the link generated by `ddev drush uli`. Remove `ddev launch` from the initial instructions but refer to its use for further site visits.
An alternative would be to drop the `ddev drush uli` line, but then the user would not be logged in when `ddev launch` is run.
> docs: Update Drupal 9 & 10 CMS Quickstarts

- pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Add WSL2 support to the ddev tableplus command
Looks like TablePlus have put out a release since the blocking issue was encountered here - https://github.com/ddev/ddev/pull/2679#issuecomment-740371838
Adds a case that launches the Windows version of TablePlus, taking advantage of the WSL2 OS identifier
> feat: add WSL2 support to tableplus command

- pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
Running `ddev tableplus` opens the database tagged as production and without any description of the site being worked on
It adds `Environment` and `Name` query parameters to the URI, which [TablePlus interprets](https://joshbutts.com/posts/tableplus-shortcuts/)
- Run `ddev tableplus` on a project
- Check out the toolbar, which should now show a green "loc" box and should show the site name
I don't think this requires any extra testing beyond any pre-existing tests for `ddev tableplus`
- no known issue
- should not impact anything else
> feat: add environment and name to TablePlus command

- docs/content/developers/maintainers.md
Not receiving email notifications on Stack Overflow after adding the `ddev` tag to watched:
> Stack Overflow. You can subscribe to the [ddev tag on Stack Overflow](https://stackoverflow.com/questions/tagged/ddev) and answer or comment on questions there.
Add a link to information on how to create a new email filter to receive notifications by tag.
> docs: use Stack Overflow email filter for maintainers

- pkg/ddevapp/schema.json
- #5400
After changes in `nodejs_version`, we should accept any possible value.
Removes enum restrictions for `nodejs_version`.
Removes all unicode characters as in
- #5653
> fix: update project schema nodejs_version, for #5400

- docs/content/users/configuration/hooks.md
- pkg/ddevapp/apptypes.go
- pkg/ddevapp/drupal.go
It would be nice to encourage database sanitizing when importing a database to a local environment. 
Updated examples to include sql:sanitize to post-import-db hooks for Drupal 10 installations.
Changed example heading from Drupal 8 to Drupal 10 to demonstrate this is the current Drupal version.
Also updated commands to use their full name instead of the alias, for better visibility.
> docs: added sql:sanitize to Drupal hook examples.

- docs/content/developers/writing-style-guide.md
- docs/content/users/configuration/config.md
- docs/content/users/usage/troubleshooting.md
Markdownlint has new rule [MD056](https://github.com/DavidAnson/markdownlint/commit/30d62f19acf237c3ec017e660960389881cbd06b).
And our docs fail with:
```
MD055/table-pipe-style Table pipe style [Expected: leading_only; Actual: leading_and_trailing; Unexpected trailing pipe]
MD056/table-column-count Table column count [Expected: 3; Actual: 2; Too few cells, row will be missing data]
```
Uses zero width non joiner `&zwnj;` https://en.wikipedia.org/wiki/Zero-width_non-joiner.
I also found and replaced unicode `&nbsp;` with a regular space.
> docs: use zero width non joiner for markdownlint

- .buildkite/macos-docker-desktop-amd64.yml
- .buildkite/macos-docker-desktop-arm64.yml
- .buildkite/macos-orbstack.yml
- .buildkite/macos-rancher-desktop.yml
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2-docker-desktop.yml
- .buildkite/wsl2-docker-inside.yml
Buildkite's docker-login plugin has been upgraded, use it.
> test: bump docker-login buildkite plugin to 3.0.0

- .buildkite/macos-docker-desktop-amd64.yml
- .buildkite/macos-docker-desktop-arm64.yml
- .buildkite/macos-orbstack.yml
- .buildkite/macos-rancher-desktop.yml
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2-docker-desktop.yml
- .buildkite/wsl2-docker-inside.yml
Reverts 
* ddev/ddev#5769
#5769 broke the use of `docker context`, so our setup for orbstack and rancher desktop couldn't work.
> test: Revert "test: bump docker-login buildkite plugin to 3.0.0"

- cmd/ddev/cmd/autocompletion_test.go
- cmd/ddev/cmd/clean.go
- cmd/ddev/cmd/debug-compose-config.go
- cmd/ddev/cmd/debug-config-yaml.go
- cmd/ddev/cmd/debug-refresh.go
- cmd/ddev/cmd/delete.go
- cmd/ddev/cmd/describe.go
- cmd/ddev/cmd/import-db.go
- cmd/ddev/cmd/logs.go
- cmd/ddev/cmd/mutagen-monitor.go
- cmd/ddev/cmd/mutagen-reset.go
- cmd/ddev/cmd/mutagen-status.go
- cmd/ddev/cmd/mutagen-sync.go
- cmd/ddev/cmd/restart.go
- cmd/ddev/cmd/share.go
- cmd/ddev/cmd/snapshot.go
- cmd/ddev/cmd/ssh.go
- cmd/ddev/cmd/start.go
- cmd/ddev/cmd/stop.go
- docs/content/users/usage/commands.md
- pkg/ddevapp/utils.go
Lots of the go commands take a project name as an argument, but don't provide autocompletion for those arguments.
Adds autocompletion for commands that take a project name as an argument.
- If only one argument is allowed, it doesn't give completion for more.
- If multiple arguments are allowed, it gives completion for all of them.
- For `start` and `stop` specifically, if only gives names of the relevant (inactive and active respectively) projects - for all other commands, all names are given.
**NOTE** This makes the `--select` flag for `ddev start` and `ddev stop` redundant. I've marked the flag as hidden and deprecated for both of those commands - it can be removed in some future release.
I've also removed the docs about that flag - but if you want me to add it back with a note that …
> feat: add autocomplete for project name arguments, fixes #4880

- .buildkite/macos-docker-desktop-amd64.yml
macOS AMD64 testing is becoming less and less relevant as people upgrade. We don't need to test it on every PR/push. 
It also really doesn't show any differences these days from arm64. And it's quite a bit slower.
Only test it on master.
> test: only test macos amd64 on master

- .ci-scripts/linux_arm64_setup.sh
- .circleci/config.yml
* #5732 introduced the slices package which appeared in go v1.21, and CircleCI was set up for v1.20
Update CircleCI config
I'm not 100% sure that we need to keep testing Linux arm64. It's very lightly used, just by people with Raspberry Pi or MS Surface Pro. And the actual testing is probably adequate on macOS. We *could* make a mistake with images, etc.
> test: CircleCI upgrade to go v1.21

- containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
- pkg/versionconstants/versionconstants.go
* #4942 
This at least removes the redundant chown in container start.sh
> fix: remove redundant chown in ddev-webserver start.sh, for #4942

- pkg/ddevapp/apptypes.go
- pkg/ddevapp/php.go
* #5675 
Projects with no settings may fail when starting outside homedir. They shouldn't even be chmodding in that case
* Remove the chmod action if no settings files are configured (as with php project type)
* Completely remove phpPostStartAction as it contained nothing useful. PHP projects never have settings.
Run `ddev start <somephpproject>` in the root directory of a linux machine. It should work fine.
Run `ddev start <somedrupalproject>` in the root directory on linux, it should work and unwriteable settings files should be  chmodded properly.
> fix: when settings files not set, don't chmod, fixes #5675

- docs/content/users/extend/customization-extendibility.md
- docs/content/users/usage/cli.md
- docs/content/users/usage/commands.md
- pkg/ddevapp/config.go
Benny pointed out in [Discord](https://discord.com/channels/664580571770388500/1203395133580640327/1203395133580640327) that while `ddev exec node --version` works correctly, `ddev exec nodejs --version` gets the apt-install nodejs version instead.
* https://github.com/ddev/ddev/pull/5521#issuecomment-1925414133
* Add a symlink for /usr/local/bin/nodejs
* Add to docs discouraging use of `ddev nvm`
`ddev exec nodejs --version` should show the version of `nodejs_version` configured.
No changes
> fix: nodejs in web container should be link to /usr/local/bin/node

- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
* #5788 
The new key is out there now, but we have to rebuild the ddev-php-base and ddev-webserver images to get it
`ddev start` and `ddev exec gpg --list-options show-sig-expire /usr/share/keyrings/deb.sury.org-php.gpg` - check expiration date
> build: Use new tag to get new deb.sury.org key (and updated php versions), fixes #5788

- pkg/versionconstants/versionconstants.go
It's release time for v1.22.7, push new images
This should fix 
* #5633 
as it updated xdebug to 3.3.1
> build: bump images to v1.22.7 for release, fixes #5633

- pkg/ddevapp/global_dotddev_assets/commands/host/tableplus
TablePlus is not only available via download from the vendor website but is  also part of the [SetApp subscription model](https://setapp.com/en/apps/tableplus). In that case, the application is installed in a different directory and thus  the `ddev tableplus` command doesn't work.
This PR checks of tableplus is located in the setapp directory. If not, the default path is used.
Default path is `/Applications/TablePlus.app`
SetApp path is `/Applications/Setapp/TablePlus.app`
`ddev tableplus` works for both, normal users and SetApp users.
> feat: support TablePlus application located in setapp directory (#5815)

- .goreleaser.yml
* https://github.com/ddev/ddev/pull/4179 prepended an underscore to the zsh completion script following the zsh naming convention. The PR changed that only on the bump_homebrew.sh file. on .goreleaser.yaml which is used meanwhile that convention wasn't followed.
> fix: follow the zsh naming conventions for completion scripts

- docs/content/users/quickstart.md
The current Backdrop quickstart fails:
```shell
git clone https://github.com/example/example-site
Cloning into 'example-site'...
remote: Repository not found.
fatal: repository 'https://github.com/example/example-site/' not found
```
This PR fixes 2 issues with the current documenation:
- Corrects clone target
- Sets DDEV config to "backdrop"
As I don't use Backdrop, I'm not sure if this "best practises". However, these steps did result in the "site setup" screen displaying.
> docs: show initial and project-checkout Backdrop installation

- cmd/ddev/cmd/autocompletion_test.go
- cmd/ddev/cmd/commands.go
- cmd/ddev/cmd/commands_test.go
- cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/global_commands/host/global-host-cmd
- cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/global_commands/web/global-web-cmd
- cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/project_commands/host/project-host-cmd
- cmd/ddev/cmd/testdata/TestAutocompleteTermsForCustomCmds/project_commands/web/project-web-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/host/autocomplete/global-host-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/host/global-host-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/web/autocomplete/global-web-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/global_commands/web/global-web-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/host/autocomplete/project-host-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/host/project-host-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/web/autocomplete/project-web-cmd
- cmd/ddev/cmd/testdata/TestAutocompletionForCustomCmds/project_commands/web/project-web-cmd
- containers/ddev-webserver/ddev-webserver-etc-skel/etc/skel/.bashrc
- docs/content/users/extend/custom-commands.md
- pkg/ddevapp/global_dotddev_assets/commands/web/autocomplete/npm
- pkg/ddevapp/global_dotddev_assets/commands/web/autocomplete/nvm
- pkg/ddevapp/global_dotddev_assets/commands/web/blackfire
- pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
- pkg/ddevapp/global_dotddev_assets/commands/web/xhprof
- #5783
For static completions, a new annotation is introduced which provides an array of valid argument values. They aren't validated against, they're only used for completions.
For dynamic completions, if there's a script in the `autocompletions` subdirectory with the same name as a command in that service command directory, it'll be called and the current cli args will be passed in. That script can then use those args to generate a string of line-break-separated values which are valid (see edit to docs)
All CLI args (including the name of the command, since this seems to be standard with bash autocompletion) are passed to the script as arguments. This includes an empty argument if `tab` is pressed after a space.
The return value from scripts should be a space-separated string of value …
> feat: enable autocompletion for custom commands, fixes #5783

- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- pkg/versionconstants/versionconstants.go
This replaces #5278 - At the time that was done the build didn't succeed, but now it may. 
Resurrect #5278 
Try it out.
> build: bump ddev-php-base and ddev-webserver to base on Debian 12 bookworm, replaces #5278

- .github/workflows/master-build.yml
- .goreleaser.yml
- docs/content/developers/building-contributing.md
* #5830
Implementation of a new "head" release in https://github.com/ddev/ddev/pull/5824 caused all hell to break loose.
* Packages were inappropriately pushed to our apt/yum repositories
* `ddev start` notified about a new release inappropriately (it was a prerelease anyway)
* People got repeated email notifications about the head release as it cycled back and forth.
Revert the implementation of the "head" release.
> build: revert implementation of 'head' release, fixes #5830

- docs/content/users/usage/commands.md
- docs/content/users/usage/faq.md
- docs/content/users/usage/troubleshooting.md
- docs/content/users/usage/uninstall.md
- pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
Multiple `ddev` can be in `PATH`.
And the older `ddev` may have a higher priority, so users wonder why their `ddev` is not "updating".
Adds the `which -a ddev` technique in several places in the documentation. My priority is that when you type `old ddev` in the search, it will be shown.
Uses `which -a ddev` in `ddev self-upgrade`.
Run `ddev debug fix-commands`.
Run `ddev self-upgrade` with one `ddev` in `PATH`, repeat with multiple `ddev` in `PATH`.
> docs: find all DDEV binaries using `which -a ddev`

- .gitpod/images/Dockerfile
- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- docs/content/users/usage/commands.md
- pkg/ddevapp/templates.go
- pkg/nodeps/values.go
- pkg/versionconstants/versionconstants.go
Today, Node.js v20 has its active LTS start. As explained in the documentation: The default for the config option `nodejs_version` is the current LTS version.
This PR raises the default used Node.js version from 18 to 20
> refactor: update to Node.js v20 LTS as current default

- docs/content/developers/buildkite-testmachine-setup.md
Docs: I had to deploy a new wsl2-inside test runner, learned some things.
> docs: improve buildkite setup for WSL2

- docs/content/users/quickstart.md
The current stable requires PHP 8.2+ (making the current snippet fail) and v11+ supports PHP 8.3 so it seems like a good default.
PHP 8.1 is not supported by the latest stable TYPO3 version (v13.0.1) which gets installed by default
Follow the steps from the paragraph.
none
none
none
> docs: use PHP 8.3 for the TYPO3 Quickstart

- cmd/ddev/cmd/xdebug_test.go
- containers/ddev-php-base/Dockerfile
- containers/ddev-webserver/Dockerfile
- docs/content/developers/project-types.md
- docs/content/users/configuration/config.md
- docs/content/users/extend/customization-extendibility.md
- docs/content/users/extend/customizing-images.md
- pkg/ddevapp/apptypes_test.go
- pkg/ddevapp/ddevapp_test.go
- pkg/ddevapp/templates.go
- pkg/nodeps/php_values.go
- pkg/versionconstants/versionconstants.go
* #5767 
Change the default everywhere
Try it out. `ddev config --auto` in an empty directory should get a default of 8.2
Start it up. `ddev php --version` should have 8.2
**this won't be testable until I push new images. I'll wait to push new images until**
* https://github.com/ddev/ddev/pull/5453
is in
> feat: change php default version to 8.2, fixes #5767

- docs/content/developers/remote-config.md
I had to debug new remote config for 
* https://github.com/ddev/remote-config/pull/24
I learned/relearned a few things, so adding this info.
> docs: add maintainer docs about remote-config testing

- .buildkite/test.sh
I happened to notice a buildkite build with a bunch of docker scout stuff being output. Annoying. trying to stop it.
> test: silence docker scout nonsense in buildkite [skip ci]

- markdown-link-check.json
There are a couple of external URLs that often fail the docs markdown links test, we just can't test them. We have no control over them and they should be stable anyway.
> docs: don't link check a couple of unstable external urls [skip ci]

- pkg/ddevapp/assets.go
If no ~/.ddev exists, and `ddev --version` is executed in a directory that is not a project, the global commands directory doesn't get created. You end up getting an error like this:
```
$ mv ~/.ddev ~/.ddev.bak
rfay@ub-2204:~/workspace/ddev$ ddev --version
Adding custom/shell commands failed: open /home/rfay/.ddev/commands/host: no such file or directory
ddev version v1.22.7-23-gefa8cea57
```
Create the global directory structure before existing the test for "am I in a project"
```
mkdir -p ~/tmp/junk && cd ~/tmp/junk
mv ~/.ddev ~/.ddev.bak
ddev --version
```
You shouldn't get an error message. Don't forget to copy your ~/.ddev back into place if you care about it.
> fix: make `ddev --version` work even if not in project and ~/.ddev/commands not yet created

- markdown-link-check.json
Stack Overflow is giving us 403 for all URL link checks, so stop trying.
> docs: stop checking all stack overflow links

- docs/content/users/configuration/config.md
- docs/content/users/debugging-profiling/step-debugging.md
A user in Discord set xdebug_ide_location to `container` and didn't know why it didn't work
Try to get people not to use it except in the obscure situations it's needed for.
> docs: mostly warn people off of using xdebug_ide_location

- docs/content/assets/extra.css
- mkdocs.yml
I want to try auto light / dark mode for the docs.
Uses https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=dark+mode#automatic-light-dark-mode
Try out https://ddev--5853.org.readthedocs.build/en/5853/
> docs: add auto light / dark mode

- markdown-link-check.json
docs linkcheck shouldn't be trying for community.chocolatey.org, which requires login I think
> docs: stop checking link to community.chocolatey.org

- pkg/ddevapp/app_compose_template.yaml
- pkg/ddevapp/ddevapp.go
- pkg/dockerutil/dockerutils.go
- #5810
This PR may return this error during `ddev start`, see #5508:
```
Error response from daemon: network ddev-your-project_default is ambiguous (16 matches found on name)
```
But I really doubt it, because we have a test for this behavior, and after the migration from `fsouza/go-dockerclient` to `docker/docker/client` in #5787, I had to rewrite the `networks_test.go`, because neither Docker 24.0.7 nor Docker 25.0.3 could create a duplicate network.
https://github.com/ddev/ddev/blob/cbb96e3a666d33ce7fb7053cfdc7f2e31c1ad0a0/cmd/ddev/cmd/networks_test.go#L44-L53
It only uses a check for network duplicates (which doesn't hurt at all), given that in Docker v25+ you can no longer have duplicates.
This allows users to create additional configurations for project networks in custom …
> fix: do not create project network programmatically on `ddev start`, fixes #5810

- pkg/ddevapp/composer_test.go
This is a very minor improvement to TestComposerVersion that I needed when working on 
* https://github.com/ddev/ddev/issues/5861
so that I could restart the test even if I aborted in the middle of it.
> test: Minor improvement to TestComposerVersion

- pkg/ddevapp/providerPantheon_test.go
TestPantheonPush has been failing.
Studying the problem showed that it was the move to PHP8.2 as default that broke it; drush couldn't be installed on Drupal9.
* Use Drupal10
* Use PHP8.2 
None needed.
> test: Fix TestPantheonPush, broken due to php8.2 default

- pkg/ddevapp/ddevapp.go
* https://github.com/ddev/ddev/issues/5861#issuecomment-1953304513
This is secondary to the actual problem we're chasing there, but there is no reason to do a panic in this situation.
* Replace util.CheckErr() with a warning
* Remove a second util.CheckErr() which was checking the same `err`
> fix: don't panic in app.Describe() if container not found

- pkg/ddevapp/ddevapp.go
On a number of [rancher desktop tests](https://buildkite.com/ddev/macos-rancher-desktop/builds/586#018dc0d5-43b7-4b9d-87ee-30c8d521908b) we're seeing docker having failed, and DDEV having detected startup failure, but continuing on in processing app.Start(), eventually seeing the misleading "Something is wrong with Docker or Colima and /mnt/ddev_config is not mounted from the project .ddev folder. This can cause all kinds of problems."
 
We also saw this misleading output on 
* https://github.com/ddev/ddev-sqlsrv/issues/20
If the web and db containers can't come up, stop the app.Start() and error out.
> fix: ddev start should not continue if web/db containers aren't healthy

- docs/content/users/debugging-profiling/step-debugging.md
PhpStorm moved a page around, so link check fails. Fix.
> docs: fix 404 link in phpstorm docs

- docs/content/users/usage/index.md
While upgrading and installing DDEV are functionally similar, they take place at different times during a user's engagement with DDEV. A new DDEV user may not remember or have ever been informed to check 'Start!' for instructions on upgrading. They should not have to rely on the site search to locate it. For example, the [Drupal's documentation](https://www.drupal.org/docs) takes this approach and provides separate sections for 'Getting started' and 'Updating Drupal'.
It simply adds a link to the 'Upgrading DDEV' from within the 'Usage' > 'Common Tasks' documentation section.
> docs: Link to 'Upgrading DDEV' in 'Usage' section

- pkg/ddevapp/ddevapp.go
I've been noticing in tests and in manual testing of `ddev import-db` the message "Error converting '' to int":
```
% ddev import-db --file=.tarballs/db.sql.gz
13.9MiB 0:00:01 [7.00MiB/s] [================================>] 100%
Error converting '' to int
Successfully imported database 'db' for d10
```
Allow empty and don't try to convert it to a zero. I'm not sure this is a change in go's behavior.
I was unable to find a replacement technique for this stanza. The original idea was to watch the rows come in until they stopped coming in. I don't see how to do that now. But I did my traditional huge database import-db and it seemed to work fine.
> fix: error message 'Error converting to int' on `ddev import-db`

- pkg/ddevapp/config_test.go
- pkg/ddevapp/hooks_test.go
Colima is always difficult to get through a run. Lately we're seeing TestPHPOverrides fail a lot, and it seems no reason to work any harder on it.
Don't test it on Colima.
HOWEVER: Run local tests with colima on TestPHPOverrides and see if it can be reproduced.
> test: exclude TestPHPOverrides on Colima

- pkg/ddevapp/ddevapp.go
- pkg/ddevapp/mutagen.go
In testing a completely unrelated issue on Linux/WSL2, I happened to notice that `mutagen daemon run` was running (`ps -ef |grep mutagen`) even though nothing in the system had `performance_mode: mutagen`. 
It turned out that SyncAndPauseMutagenSession() and TerminateMutagenSession() were not protected by app.IsMutagenEnabled(), and even though their activities didn't cause trouble, there was the side-effect of starting the mutagen daemon, which is not needed.
Properly protect against use of those functions in non-mutagen setup.
With mutagen disabled
* Check to make sure `mutagen daemon run` isn't running
* `ddev start`, `ddev stop`, `ddev poweroff`, `ddev delete` - none of these should result in the mutagen daemon running
> fix: don't start 'mutagen daemon run' during ddev stop/delete

- .buildkite/macos-colima.yml
- .buildkite/macos-colima_vz.yml
- .buildkite/macos-docker-desktop-amd64.yml
- .buildkite/macos-docker-desktop-arm64.yml
- .buildkite/macos-lima.yml
- .buildkite/macos-orbstack.yml
- .buildkite/macos-rancher-desktop.yml
- .buildkite/nfstest.sh
- .buildkite/sanetestbot.sh
- .buildkite/test.sh
- .buildkite/windows10_container.yml
- .buildkite/windows10dockerforwindows.yml
- .buildkite/wsl2-docker-desktop.yml
- .buildkite/wsl2-docker-inside.yml
- .github/workflows/colima-tests.yml
- docs/content/developers/buildkite-testmachine-setup.md
- pkg/ddevapp/extra_expose_test.go
* #5598 
We have never been able to get predictable results from colima tests on Github Actions. Maybe the VMs are too small
Also, we were never able to do normal https tests, so there are a bunch of things that require http, we might be able to remove those.
Run the builds on our larger buildkite test machines.
Testing by running TestExtraPortExpose with:
`GOTEST_SHORT=true make testpkg TESTARGS="-run TestExtraPortExpose -count=1"`
It seems to work after a `colima start` and then a `colima restart`. And then it stays working. So weird.
> test: Run colima tests native instead of github, fixes #5598
