ddev/ddev

docs/content/developers/building-contributing.md

NA
* Point to latest version of file, not a specific commit (which is already outdated)
Go to equivalent https://ddev.readthedocs.io/en/stable/developers/building-contributing/#testing and examine the `TestSites array` link
NA
NA
NA

docs: point to HEAD version of TestSites array

---

pkg/ddevapp/config.go
pkg/ddevapp/config_test.go

- #5898
Although this seems to be a problem with php packaging, we can solve it on our side to prevent this in the future with `chmod 777 /run/php`.
```
mkdir php-gmp && cd php-gmp
ddev config --auto --php-version 8.2 --webimage-extra-packages php8.2-gmp --omit-containers db
ddev start
```
The project should be started normally.

fix: set permissions on /run/php so php-fpm can run

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md

There were no quickstart guide for Grav CMS
It is adding instructions for a composer based install and a git clone based on to the quickstart.md

docs: add instructions for Grav CMS to quickstart.md

---

docs/content/users/topics/hosting.md

During shutdown of a Linux host, the `ddev poweroff` triggered in the `ExecStop=` directive of the provided sample systemd unit file left containers dangling around. This may result in file permission conflict, if a custom mySQL config file is provided.
Changes the `After=` from network.target to multi-user.target, which is fired later on startup and thus ExecStop= will be fired earlier on shutdown, leaving ddev poweroff more time to properly clean up.
Compare the traces from the `systemd-analyze critical-chain ddev.service` for the alternate settings:
```
ddev.service +21.635s
└─basic.target @5.090s
└─sockets.target @5.090s
└─docker.socket @5.083s +5ms
└─sysinit.target @5.056s
└─cloud-init.service @4.063s +987ms
└─systemd-networkd-wait-online.service @2.301s +1.757s …
```

docs: fix systemd unit example for casual hosting

---

cmd/ddev/cmd/config.go
cmd/ddev/cmd/root.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/mutagen_config_assets/mutagen.yml
pkg/ddevapp/router.go
pkg/ddevapp/templates.go
pkg/fileutil/files.go
pkg/globalconfig/global_config.go

We should point go code to the stable docs after
- #5855
Updates the links.

refactor: point go code to the stable docs

---

cmd/ddev/cmd/config.go
cmd/ddev/cmd/config_test.go

- #5882
The bug introduced in
- #5631
The expected behavior for `ddev config` in the various situations:
* `config.yaml` specifies a set of configs but there's no code to match it (the bug here). (This can be more than just project type I think, docroot as well).
Running `ddev config` on existing code should not change existing config options that are not specified.
For example, when you run `ddev config --web-environment-add FOO=bar` on a project with the latest config (updating the outdated configuration is mentioned later), it should only change the `web_environment` option, and nothing else. This is covered in this PR in `TestConfigSetValues` - this test checks a lot of configuration options, so I think we are safe here.
* `config.yaml` specifies a set of configs but the code found by …

fix: ddev config should not change unspecified options, fixes #5882

---

docs/content/index.md

Noticed that OrbStack and Rancher Desktop are not mentioned on the index page.
Updates the docs.
https://ddev--5914.org.readthedocs.build/en/5914/#system-requirements

docs: mention more Docker providers for macOS

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md

* #5843 requests Pimcore support
We'll want more input from the Pimcore community, but this adds a basic quickstart.
Docs example at https://ddev--5909.org.readthedocs.build/en/5909/users/quickstart/#pimcore

docs: Add Pimcore quickstart, fixes #5843

---

.spellcheckwordlist.txt
docs/content/users/extend/custom-commands.md

Most annotations are references using quotes, except the newest one where I was told to use backticks.
They should all use backticks - it looks silly with one being rendered differently.
Use backticks when referencing annotations for custom commands in the docs.
Remove annotations from the spelling words list, since anything in backticks is ignored for spelling checks.
Take a look at [custom commands page](https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/) in the docs.
N/A
- https://github.com/ddev/ddev/issues/5820
N/A

docs: Use backticks when referencing custom command annotations, fixes #5820

---

.spellcheckwordlist.txt
Makefile
docs/content/users/providers/index.md
docs/content/users/topics/index.md
docs/content/users/usage/faq.md
mkdocs.yml

Noticed FAQs that people ask... about code and DDEV, about where the databases live.
* Minor change to `make mkdocs-serve` - delete the container on exit
* Fix menus on hosting provider integration. They've been messed up forever
* Add new FAQs
Built docs at https://ddev--5924.org.readthedocs.build/en/5924/users/usage/faq/
* Review "hosting provider integration" and related menus at 
* Review FAQ
For the mkdocs-not-installed case `make mkdocs-serve` provides a docker-based mkdocs setup thanks to @tyler36 
The [polinux/mkdocs](https://registry.hub.docker.com/r/polinux/mkdocs)  docker image has moved along, and now has arm64 version (not pushed properly), but the current image does not seem to work right on either arm64 or amd64.
I experimented with this, though, to handle arm64, but …

docs: update faq with new questions, fix menus

---

docs/content/users/quickstart.md
pkg/ddevapp/magento.go

* #5919
@stasadev discovered that Magento2 refuses to run with updated MariaDB 10.11 (now default).
Use config override action to use MariaDB 10.6 per https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html
Run through the quickstart using this version.
It should not even require the use of `--database=mariadb:10.6` - that should happen by default, but it's reasonable to make it explicit in the quickstart.
Nothing new.

fix: magento2 requires mariadb 10.6, for #5919

---

mkdocs.yml

I noticed that 404 links always point to the latest docs.
Uses stable URL.
I was concerned about `# todo: Make sure to set this to the correct one; otherwise it breaks 404 page` for the `site_url`, so I tested this on my own fork before making this change.
**Current stable**: https://ddev.readthedocs.io/en/stable/404 and click any link, see the **latest** docs.
**Current latest**: https://ddev.readthedocs.io/en/latest/404 and click any link, see the **latest** docs.
**Latest after merge**: https://ddev.readthedocs.io/en/latest/404 (Hard reload the page) and click any link, see the **stable** docs.
**Stable after merge**: remains the same.
This change will not fix 404 for stable until the next stable release is out.

docs: use stable URL for 404 [skip ci]

---

pkg/ddevapp/webserver_config_assets/nginx-site-backdrop.conf
pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal6.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal7.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal8.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf
pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
pkg/ddevapp/webserver_config_assets/nginx-site-magento.conf
pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf
pkg/ddevapp/webserver_config_assets/nginx-site-php.conf
pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
pkg/ddevapp/webserver_config_assets/nginx-site-wordpress.conf
pkg/ddevapp/webserver_config_assets/nginx_second_docroot_example-site-php.conf

Added webp support for images in hidden directories.
Webp images are not supported for magento 2 projects if the image is in a hidden directory. A request to a webp image will result in a HTTP 403 Error.
Changed nginx config to allow webp files as images in hidden directories.
Add an image in webp format in a hidden directory i.e. https://test.ddev.site/media/.renditions/test.webp and request that image. Before the changes there is an error "403 Forbidden". After the changes the image is shown in the browser.

fix: add nginx support for webp images in hidden directory, sync nginx conf

---

cmd/ddev/cmd/config.go

@ajibarra points out in 
* https://github.com/ddev/ddev/pull/5888#issuecomment-1972943332 
that the PostConfigAction is being called twice. It's being called twice because when `ddev config` is called with args, the WriteConfig() happens both inside handleMainConfigArgs() and also in the parent handleConfigRun. It should only be called once. 
* When `ddev config` is called without args, we do the WriteConfig() in its context
* When called *with* args, let handleMainConfigArgs() do the write
I think it requires debugger or adding a print statement, but just add a print statement to a PostConfigAction or to WriteConfig.

fix: don't call app.WriteConfig twice

---

pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/magento.go

* If you run `ddev config --auto` on the latest Magento 2 version, the project type `magento2` is not detected and `php` is used.
* Magento2 test tarballs are unmaintainable and out-of-date
* The check is for a string `https://hackerone.com/magento` in the root SECURITY.md.
(This is odd because that file is often deleted.)
However, the string has been changed to `https://hackerone.com/adobe` since version 2.4.5 as you can review here: https://github.com/magento/magento2/commit/3cb720f9ed01f3d53ba123fba9c048eb3b73f2b7
* Use new ddev/test-magento2 repository for tests.
Install Magento 2 version 2.4.5 or following via CMS Quickstart.
Run `ddev config --auto`.
See that the project type is still `magento2`.
The test for `isMagento2App` already exists.
I don't think so.

fix: isMagento2App() should detect version 2.4.5+, update test URLs

---

cmd/ddev/cmd/restart.go
cmd/ddev/cmd/start.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/extra_expose_test.go
pkg/ddevapp/utils.go

When the command determines a primary URL, it creates a `http` URL even if you're using custom certs.
The URL will now have a `https` schema if you have custom certs.
Use a custom cert in the config. You can test using my [public wildcard cert](https://github.com/tbmatuka/php-apache-nodejs-development/tree/master/dev/.docker-config/ssl) and `project_tld: loc-dev.com`
The function is used in a lot of places, so if I broke something, tests should fail.
None?

fix: make the primary URL https if the custom cert exists

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

* #5929 
We weren't using the right key location for the blackfire repo in building ddev-webserver, so we got warnings building.
Fix it up per https://installer.blackfire.io/installer.sh
(We can't use the installer because it assumes systemd)

build: use correct key pattern for blackfire, fixes #5929

---

docs/content/users/quickstart.md

* The Magento2 install forgets the composer auth for the private repo
* People always forget what to do if the directory name is different
* Backdrop tabs are broken by messed-up indentation
Make it a bit more resilient, and capture the auth.json where it will persist.
Review at https://ddev--5932.org.readthedocs.build/en/5932/users/quickstart/
Try it out

docs: Improve magento2 quickstart and remember composer auth

---

.buildkite/macos-lima.yml
.buildkite/test.sh
cmd/ddev/cmd/autocompletion_test.go
cmd/ddev/cmd/debug-nfsmount_test.go
docs/content/users/install/docker-installation.md
pkg/config/remoteconfig/messages.go
pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/mailpit_test.go
pkg/dockerutil/dockerutils.go
pkg/testcommon/testcommon_test.go
pkg/version/version.go

Colima has gotten quite unstable for lots of people, but it's just a wrapper on Lima, and so we should be able to use Lima directly as another open-source alternative.
It's worth considering whether we should do this at all, as adding more options doesn't necessarily help people or our support environment.
Use the docs to start a lima instance, then do a simple quickstart test.

feat: Add native lima Docker provider support

---

docs/content/users/install/ddev-installation.md

The WSL2 install docs don't make clear that docker-ce is considered best.
Improve the wording.

docs: Improve suggestions about WSL2 docker options

---

docs/content/users/install/docker-installation.md

* VZ is the most performant and best behaved setup for Colima at this point
* We should only be testing VZ on PRs and then test both QEMU and VZ on master
* Change docs
* Manually changed config on colima in buildkite to run on master and not on PRs.
Run through the install. Have done it many times and currently using it.

docs: change recommendation for colima to vz

---

pkg/ddevapp/ddevapp.go

* #5755 
Sometimes orphaned containers are left around, probably due to removed `docker-compose.*.yaml`, etc.
However, docker-compose provides environment variables to ignore and remove.
Add them.
* Try to create an orphan on a project
* See if we get a complaint

fix: just delete compose orphans, fixes #5755

---

cmd/ddev/cmd/scripts/test_ddev.sh
docs/content/users/usage/troubleshooting.md

* #3679
* `ddev debug test` should say if project is not in home directory
* Gather version numbers of colima/lima/orbstack/rancher
* Remove some mutagen output

fix: ddev debug test should check to make sure project is in homedir, for #3679

---

docs/content/users/install/ddev-installation.md

The WSL2 docs weren't specific saying people need to put projects in homedir.

docs: be more explicit about where projects go in home dir

---

pkg/ddevapp/ddevapp.go

- #5950
`docker-compose up` didn't respect `COMPOSE_REMOVE_ORPHANS` until v2.24.7:
- https://github.com/docker/compose/pull/11462
But now it does, and we cannot use two env variables at the same time.
`COMPOSE_IGNORE_ORPHANS` and `COMPOSE_REMOVE_ORPHANS` are mutually exclusive:
https://github.com/docker/compose/blob/4efb89709ccb9f11ce0b6571a1c4674be37a42b7/cmd/compose/up.go#L92-L95
This did not appear in the tests because we use v2.24.5.
```
$ ddev config global --required-docker-compose-version=v2.24.7
$ ddev start
Starting d10... 
cannot combine COMPOSE_IGNORE_ORPHANS and --remove-orphans
Failed to start d10: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-d10 docker-compose -f /home/stas/code/ddev/d10/.ddev/.ddev-docker-compose-full.yaml up -d', action='[]', err='exit status 1', …
```

fix: remove mutually exclusive COMPOSE_IGNORE_ORPHANS variable, for #5950

---

docs/content/users/quickstart.md

Even if mariadb works, there are times that specific joins can be much slower than in mysql. 
ExpressionEngine documentation (and team) recommends using mysql instead of the default mariadb.

docs: Use mysql:8.0 instead of mariadb for ExpressionEngine quickstart

---

cmd/ddev/cmd/get.go
docs/content/users/extend/additional-services.md
docs/content/users/usage/commands.md
pkg/archive/archive_test.go

* https://github.com/ddev/ddev-drupal-solr/issues/36
* `ddev-drupal9-solr` renamed to `ddev-solr`
* Update output of `ddev get --list`
* Use newer tarball examples and in test

docs: update ddev-drupal9-solr to ddev-drupal-solr

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md
pkg/ddevapp/apptypes_test.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/envfile.go
pkg/ddevapp/laravel.go

- #5962
The PHP version is set to 8.1 for Laravel in DDEV HEAD, so it cannot pull Laravel 11, and it pulls Laravel 10.
Laravel 11 introduced new skeleton, and now it has a new [`mariadb`](https://github.com/laravel/laravel/blob/6ea57d766ffc7948adbf02b6ac63670d43580316/config/database.php#L62-L80) database driver.
- Uses `mariadb` driver by default.
- Sets PHP version to 8.2, including docs.
- Fix Mailpit (Laravel 11 sends emails to log file by default)
- Laravel 11 adds [commented](https://github.com/laravel/laravel/blob/6ea57d766ffc7948adbf02b6ac63670d43580316/.env.example#L22-L27) variables for database, like this:
```dotenv
DB_CONNECTION=sqlite
```
And DDEV doesn't replace the commented lines with new values (it adds `DB_` variables at the end of `.env`), I fixed it.
Use the quickstart …

feat: Laravel 11 support, fixes #5962

---

cmd/ddev/cmd/debug-refresh.go
pkg/ddevapp/ddevapp.go
pkg/dockerutil/dockerutils.go
pkg/util/utils.go

* #5913 
* #5893
* #5470 
* Only use goroutine when we need it, which is just for outputting dots during build.
`ddev debug refresh` builds only the web image, making the output less confusing.

fix: Rewrite ComposeCmd() with just dots goroutine, fixes #5913

---

pkg/ddevapp/config_test.go
pkg/ddevapp/extra_expose_test.go

Lima and Colima often fail TestPHPConfig because they're just not ready to answer I guess. We get this stuff tested plenty elsewhere, just disable here.

test: disable TestPHPConfig on Lima/Colima

---

pkg/ddevapp/traefik.go
pkg/versionconstants/versionconstants.go

docker-compose v2.25.0 was released. Run tests on it.

build: bump docker-compose to v2.25.0

---

cmd/ddev/cmd/logs_test.go
cmd/ddev/cmd/mutagen-cmd_test.go
cmd/ddev/cmd/snapshot_restore_test.go
cmd/ddev/cmd/snapshot_test.go
cmd/ddev/cmd/ssh_test.go
cmd/ddev/cmd/start_test.go
cmd/ddev/main.go
pkg/ddevapp/config.go
pkg/globalconfig/values.go
pkg/nodeps/values.go
pkg/testcommon/testcommon.go
pkg/util/debug.go

* #5920 
We want to know if goroutines get out of control as they did in https://github.com/ddev/ddev/pull/5878
Test on several of the TestCmd tests to make sure we have a reasonable number of goroutines at stop.
You can also use any other command, not just `ddev start`

test: Check goroutine count on several tests at completion, fixes #5920

---

cmd/ddev/cmd/commands_test.go
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/host/launch

- #5685
Opens user-defined full URLs, so users are not limited to using `$DDEV_PRIMARY_URL` all the time.
```
DDEV_DEBUG=true ddev launch https://www.google.com
DDEV_DEBUG=true ddev launch https://www.google.com:1234
DDEV_DEBUG=true ddev launch http://example.com
DDEV_DEBUG=true ddev launch $DDEV_PRIMARY_URL/test
```

feat: accept full URLs in `ddev launch`, fixes #5685

---

cmd/ddev/cmd/commands_test.go

- https://github.com/ddev/ddev/pull/5986#issuecomment-2010306973
Fixes a test, changes the path in the test cases to make it clear which one failed.

fix: make `ddev launch` test work on Windows, for #5986

---

.github/workflows/pr-artifacts-comment.yml
.github/workflows/pr-build.yml

Gitpod long ago stopped showing its badge in a comment on a PR, but we should be able to do it ourselves. 
Try to add the comment.

build: show gitpod testing link in PR comment

---

docs/content/users/debugging-profiling/step-debugging.md
pkg/dockerutil/dockerutils.go

* #5537
Lima has long since been providing `host.docker.internal` as needed, and colima picks that up, so we don't need to add an override of host.docker.internal any more.
* Remove the Colima host.docker.internal override (and the override for nfs, which should be irrelevant)
* Update docs so they don't show that as an example

fix: Revert setting 192.168.5.2 for host.docker.internal on colima, fixes #5537

---

Makefile

For the -race detection tests, I had turned on verbose output of the build in Makefile, but it's not necessary any more
Turn it off

build: turn off verbose output of make build [skip ci]

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

* #4668
Previous attempt last summer was https://github.com/ddev/ddev/pull/5044
New ddev-webserver image with the go-based platform binary
* Try `ddev pull platform`

build: use new go-based platform.sh CLI, fixes #4668

---

docs/content/users/extend/customizing-images.md

When I copied the original code into my config, the project did not start and I recieved the following error:
```shell
ddev restart 
Failed to get project(s): /home/user13/code/drupal/modules/iq_ldap/.ddev/config.yaml exists but cannot be read. It may be invalid due to a syntax error: unable to load config file /home/user13/code/drupal/modules/iq_ldap/.ddev/config.yaml: invalid configuration in /home/user13/code/drupal/modules/iq_ldap/.ddev/config.yaml: yaml: line 14: did not find expected ',' or ']'
```
This PR updates the doc to resolve this.

docs: Fix "webimage_extra_packages" code example

---

.buildkite/testbot_maintenance.sh

I noticed in https://github.com/ddev/maintainer-info/issues/1#issuecomment-2015447823 that brew stuff wasn't getting generally updated
* do `brew upgrade` on macOS instead of just doing a few packages
* In WSL2 we don't need mkcert because it's installed as dependency by ddev
The possible downside is that when buildkite-agent gets upgraded it may have the popups that prevent execution asking permissions.

test: minor updates to buildkite testbot_maintenance.sh [skip ci]

---

.github/workflows/pr-artifacts-comment.yml

We now provide a link on PRs to test in gitpod.. Why not codespaces also?

feat: add PR build link to test on Codespaces [skip ci]

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

We can use the recommended official way to install the `upsun` cli.
Changes the installation script
```
ddev exec upsun version
ddev exec sudo apt update | grep upsun
```

build: use the official script to install Upsun

---

docs/content/users/extend/custom-commands.md
pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver
pkg/ddevapp/global_dotddev_assets/commands/host/heidisql
pkg/ddevapp/global_dotddev_assets/commands/host/launch
pkg/ddevapp/global_dotddev_assets/commands/host/mysqlworkbench.example
pkg/ddevapp/global_dotddev_assets/commands/host/querious
pkg/ddevapp/global_dotddev_assets/commands/host/sequelace
pkg/ddevapp/global_dotddev_assets/commands/host/sequelpro
pkg/ddevapp/global_dotddev_assets/commands/host/tableplus

- #5949
The simplest way I found, is to restart the database command again after the project is running and all nessesary env variables are available.
I also added the same thing to `ddev launch`.
TODO: add the same thing to official add-ons:
https://github.com/ddev/ddev-phpmyadmin/pull/10
https://github.com/ddev/ddev-adminer/pull/20
```
ddev stop
ddev debug fix-commands
ddev dbeaver
```

fix: add restart for database commands after ddev start, fixes #5949

---

.spellcheckwordlist.txt
cmd/ddev/cmd/commands_test.go
docs/content/users/quickstart.md
docs/content/users/usage/architecture.md
docs/content/users/usage/cli.md
docs/content/users/usage/commands.md
pkg/ddevapp/apptypes.go
pkg/ddevapp/apptypes_test.go
pkg/ddevapp/cakephp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/global_dotddev_assets/commands/web/cake
pkg/nodeps/values.go

CakePHP projects must use  generic `php` type which does not allow automatic configuration of settings, access to cake shell through command, etc
This PR adds cakephp project type to DDEV
```bash
mkdir my-cakephp-app
cd my-cakephp-app
ddev config --project-type=cakephp --docroot=webroot --create-docroot --php-version=8.3
ddev composer create--prefer-dist cakephp/app:~5.0
ddev composer install
ddev cake
ddev launch
```
* Added `cakephp` app type to `pkg/ddevapp/ddevapp_test.go`
* Added `cake` command to `cmd/ddev/cmd/commands_test.go`
#5713 
* CakePHP test app: https://github.com/ddev/test-cakephp

feat: add cakephp project type, fixes #5713

---

pkg/versionconstants/versionconstants.go

https://github.com/docker/compose/releases/tag/v2.26.0
Updates docker-compose to v2.26.0

build: bump docker-compose to v2.26.0

---

cmd/ddev/cmd/config.go
containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
docs/content/users/configuration/config.md
docs/content/users/usage/commands.md
pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/nodejs_test.go
pkg/ddevapp/templates.go
pkg/versionconstants/versionconstants.go

* #5987
* Replaces #5988
* New `corepack_enable` config for .ddev/config.yaml
* New `ddev config --corepack-enable`
* docs
* TestCorepackEnable
* Use `ddev config --corepack-enable=true` and false (restart after)
* Review docs
* TestCorepackEnable

feat: provide corepack_enable config, fixes #5987, replaces #5988

---

cmd/ddev/cmd/debug-test_test.go

A recent PR had a test that didn't pass on traditional Windows through no fault of its own.
* https://github.com/ddev/ddev/pull/6002
Don't do the thing that causes the failure.

fix: make TestCmdDebugTest work on trad Windows

---

Makefile
docs/content/developers/testing-docs.md

* It got harder to install mkdocs on homebrew, fix it up
* Improve Makefile and docs to run arm64 docker images

docs: update dev docs to run mkdocs locally [skip buildkite]

---

cmd/ddev/cmd/config-global.go
pkg/ddevapp/ddevapp.go
pkg/globalconfig/global_config.go

* #5046 
Mostly all the work was done in 
* https://github.com/ddev/ddev/pull/6002
This still reorganizes the actual global_config.yaml.
This should just be cosmetic. I find it nearly impossible to parse `ddev config global` right now, this alphabetizes it.
In DdevApp, the Approot is moved up so I can see it in the debugger without breaking my eyes. Should have no effect on user.

fix: alphabetize global config storage and output, fixes #5046

---

mkdocs.yml

Fixes #4982.
We should keep an eye out for possibly slowed down automated builds, after this change.
Bundles the fonts with the generated documents, as opposed to getting them from a third-party.
- **Now:**
Open https://ddev--6027.org.readthedocs.build/en/6027/ in Firefox with uBlock Origin, and see that currently fonts are requested from fonts.googleapis.com
- **After adding the privacy plugin:**
See that fonts are included and served from https://ddev--6027.org.readthedocs.build/en/6027/ 
Alternative method to verify that no third-parties are contacted:
1. Open developer tools in your browser with F12
1. Open "Network"
1. Reload the page, and see that no third-party resources are contacted, in this case Google and Plausible.

docs: add privacy plugins to not use external fonts, fixes #4982 

---

docs/content/users/quickstart.md

CakePHP docs were incomplete for 3.x and missing a link to CakePHP site
Improved CakePHP docs adding instructions for 3.x and the missing link.

docs: update CakePHP docs to include a link and instructions for 3.x

---

pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example

* https://discord.com/channels/664580571770388500/1220763081211121674/1220763081211121674
It was pointed out that if the rsync provider brings down a file as a name other than db.sql.gz, the database gets created with the filename.
This is by design, https://github.com/ddev/ddev/blob/834a772de230c042c4d2d596482c699d0b83ba24/pkg/ddevapp/provider.go#L364-L374
But not useful when the rsync example doesn't explicitly control it.
Change the rsync example to explicitly name the dump file as db.sql.gz
I checked the other examples and integrations and don't find any other example of this ambiguity.
Try out this `.ddev/providers/rsync.yaml`:
```yaml
environment_variables:
dburl: rfay@jumphost.thefays.us:~/tmp/xyz.sql.gz
auth_command:
command: |
set -eu -o pipefail
ssh-add -l >/dev/null || ( echo …
```

fix: rsync example should create db.sql.gz [skip ci]

---

.buildkite/sanetestbot.sh
cmd/ddev/cmd/debug-nfsmount_test.go
pkg/ddevapp/ddevapp_test.go
pkg/dockerutil/dockerutils.go

We're having a bit of trouble with NFS in colima/lima tb-macos-arm64-5/6/7, I'm not sure why. But we don't need to be testing NFS on macOS anyway, certainly not on orbstack/lima/colima.
* https://github.com/ddev/ddev/pull/5994
Lima provides 192.168.5.2 as host.docker.internal, but colima does not seem to have it any more. I assume colima lost it in a recent Lima upgrade.
This probably means that Xdebug is not working on colima since #5994 , but I don't know why it wouldn't have been caught by automated tests.
Revert #5994 to put explicit host.docker.internal back in there again
`ddev debug nfsmount` using colima

fix: revert removal of Colima host.docker.internal setting

---

.ci-scripts/linux_arm64_setup.sh
.circleci/config.yml

* Minor maintenance
* The CircleCI arm64 build has been failing waiting for interactive services restart:
Use DEBIAN_FRONTEND=noninteractive

test: make circleci setup noninteractive so doesn't hang [skip buildkite]

---

cmd/ddev/cmd/describe_test.go
cmd/ddev/cmd/start_test.go
cmd/ddev/cmd/stop_test.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/utils.go

* #5322
People periodically delete a project's filesystem without doing a `ddev delete` first
When the filesystem is gone, remove the project from the project list
```
mkdir junk && cd junk && ddev config --auto
cd .. && rm -r junk
ddev list
```
You should see the project mentioned while it's being removed from registry,  but it won't error and won't show up on the next `ddev list`.
Added TestGetProjectsMissingApp

fix: clean up missing project if it's gone, fixes #5322

---

cmd/ddev/cmd/root.go
docs/content/users/configuration/config.md
docs/content/users/usage/troubleshooting.md
go.mod
pkg/ddevapp/config.go
pkg/ddevapp/hostname_mgt.go

* #4881 
There are a few problems with creating hostnames in /etc/hosts when name lookup fails. 
Tell when we can't do it and don't try doing it.
```
ddev config --use-dns-when-possible=false
ddev config --additional-hostnames="*.junk"
ddev start
```
You should get a warning that `*.junk.ddev.site`  can't be added to hosts file... because hosts file doesn't do wildcards.

fix: handle wildcard hostnames when name resolution not available, fixes #4881

---

.buildkite/macos-colima_vz.yml
.buildkite/macos-docker-desktop-amd64.yml
.buildkite/macos-rancher-desktop.yml
.buildkite/wsl2-docker-desktop.yml
pkg/ddevapp/ddevapp_test.go

After TestGetProjectsMissingApp went in, we had failures with both Rancher Desktop and Colima/basic (which is sshfs mount type).
For example, https://buildkite.com/ddev/macos-colima/builds/228#018e9a1f-6d07-429f-8d7c-1902a74ff956
This is just an attempt to get the directories all created and built, especially .ddev/xhprof, which seems to be the one that was failing. 
I was able to make this fail locally at first, and then it stopped failing for me. 
I think since xhprof would be the last to be created...

test: try to fix sshfs-based failures on TestGetProjectsMissingApp

---

pkg/ddevapp/config.go
pkg/util/utils.go
pkg/util/utils_test.go

E.g. nginx snippets are printed as 
```
Using nginx snippets: [/Users/diego/some-project/.ddev/nginx/some.conf /Users/diego/some-project/.ddev/nginx/some-other.conf]
```
which some users said wasn't very readable.
This provides a new formatting of 
```
Using nginx snippets: [
/Users/diego/some-project/.ddev/nginx/some.conf,
/Users/diego/some-project/.ddev/nginx/some-other.conf
]
```
Added new util function `func FilesToReadableOutput(slice []string) (response string, err error)` and uses that when warning about nginx snippets, mysql conf, php conf and entrypoint scripts.
Create a new project or use an existing one.
Create a couple of snippets:
```
mkdir -p .ddev/nginx/
touch .ddev/nginx/redirect.conf
touch .ddev/nginx/another-redirect.conf
```
Run `ddev start` and you should see those …

feat: more readable formatting of lists of files, fixes #5985

---

cmd/ddev/cmd/debug-config-yaml.go
pkg/ddevapp/config.go

* #6036 
`ddev debug configyaml` was showing this (double-report):
```
upload_dirs: [.ddev/tmp .ddev/tmp]
```
when a `.ddev/config.junk.yaml` had:
```
upload_dirs:
- .ddev/tmp
```
Load a clean, fresh "app" before loading additional configs
Affects only `ddev debug configyaml`
Use the config above and `ddev debug configyaml`, should report only one upload_dirs

fix: ddev debug configyaml shouldn't double-report upload_dirs, fixes #6036

---

.circleci/README.arch-aur-builder.md
.github/workflows/master-build.yml
.gitpod/images/README.md
.goreleaser.yml
containers/ddev-dbserver/README.md
containers/ddev-nginx-proxy-router/README.md
containers/ddev-php-base/README.md
containers/ddev-ssh-agent/README.md
containers/ddev-traefik-router/README.md
containers/ddev-webserver/README.md
containers/image_readme_template.md
containers/test-ssh-server/README.md

feat: Keep hub.docker.com repositories updated, fixes #5847 [skip ci]

---

cmd/ddev/cmd/config_test.go
docs/content/users/usage/architecture.md
pkg/ddevapp/ddevapp.go
pkg/globalconfig/global_config.go
pkg/globalconfig/schema.json

Users have been confused by having two copies of the project list, and haven't known which to update if they need to manually update the list.
1. If there's no `project_list.yaml` file and the `global_config.yaml` file contains a project list (i.e. if someone is upgrading from an older version of DDEV), copy the list into `project_list.yaml`
- This is a departure from the previous behaviour which would copy the list from `global_config.yaml` if there was any difference between the two lists
1. Remove `ProjectList` from the `GlobalConfig` type
- This means the next time `global_config.yaml` is written, the project list will be removed from that file.
Note that I have done this in two commits to show why some of the changes are necessary. I'll add PR comments to help clarify this.
1. Ensure …

refactor: Use project_list.yaml as source of truth, fixes #5918

---

containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/apache.conf
containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/gunicorn.conf
containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/php-fpm.conf
containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-fpm.conf
containers/ddev-webserver/ddev-webserver-base-files/etc/supervisor/supervisord-nginx-gunicorn.conf
containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
containers/ddev-webserver/ddev-webserver-dev-base-files/etc/supervisor/conf.d/mailhog.conf
docs/content/users/extend/customization-extendibility.md
pkg/versionconstants/versionconstants.go

- #5993
I checked https://docs.docker.com/reference/dockerfile/#healthcheck before doing any change and when we use `start_period`, no matter what we do during this period, the container cannot become `unhealthy`.
> start period provides initialization time for containers that need time to bootstrap. Probe failure during that period will not be counted towards the maximum number of retries.
I also searched for a fast fail when starting the container, but that's all I found:
https://forums.docker.com/t/healthcheck-fail-fast-feature-during-container-start-up/121201
So, in the end, I decided to do the same thing as suggested in:
- #5906
but in a simpler way.
Also I decreased `startretries=10` to `startretries=3` in supervisor, there is no reason to try more and wait longer, if the process …

fix: shutdown supervisor in healthcheck.sh on fatal error, fixes #5993

---

docs/content/users/quickstart.md
pkg/ddevapp/apptypes_test.go
pkg/ddevapp/craftcms.go

We have just tagged Craft 5.0.0-beta.1, and with that, are requiring PHP 8.2. The `craftcms` project type currently uses PHP 8.1, which will not satisfy the requirements.
Our upgrade guide covers switching PHP versions using the `config` command (`ddev config --php-version=8.2`), but we would like for all projects moving forward to use the most recent/default DDEV PHP version (8.2)—with which Craft 4 is also fully compatible.
The current database version (MySQL 8.0) is still our recommended engine, so no changes have been made to that configuration.
The `craftCmsConfigOverrideAction()` function no longer overrides the PHP version used when creating new projects.
Create a new DDEV project:
```bash
mkdir craft-five
cd craft-five
ddev config --project-type=craftcms --docroot=web
ddev …
```

fix: Remove Craft CMS PHP version override

---

.github/workflows/master-build.yml
.github/workflows/tests.yml
Makefile
pkg/version/version.go
pkg/versionconstants/cgo_false.go
pkg/versionconstants/cgo_true.go

* #6046 
In DDEV v1.23.0-alpha1, the released binaries were released with CGO_ENABLED=1, which means they can't run everywhere they're intended to run. This includes Ubuntu 20.04
* Make sure we build it right
* Add cgo_enabled to `ddev version` so we can check it
* Update Makefile and github builds to test and make sure we have it right.
You can already test the artifacts built this way from the experimental release https://github.com/ddev-test/ddev/releases/tag/v1.22.10-aaa3 (Do not use this for anything but testing this issue). 
* `ddev version` should show cgo_enabled=0
We now check in the build pipeline to make sure the CGO_ENABLED version is correct.

fix: make sure CGO_ENABLED is normally off, fixes #6046

---

pkg/dockerutil/dockerutils.go

- #6042
Container errors messages contain commands to know more for debugging the issue embedded in the error message itself, which makes it harder to visually parse.
Shows the commands that can provide more information in separate lines.
Message will look like:
```
Failed waiting for web/db containers to become ready: web container failed: log=, err=health check timed out after 2m0s: labels map[com.ddev.site-name:project-name com.docker.compose.service:web] timed out without becoming healthy, status=, detail= ddev-project-name-web:starting - more info with [
ddev logs -s web
docker logs ddev-project-name-web
docker inspect --format "{{ json .State.Health }}" ddev-project-name-web
]
```
Try breaking project containers on ddev start and see what happens.
I don't really know how to break …

feat: Improve container errors messages format, fixes #6042

---

pkg/ddevapp/cakephp.go

DEBUG_KIT_SAFE_TLD was spelled like DEBUGKIT_SAFE_TLD
Change env variable name to DEBUG_KIT_SAFE_TLD
1. Run ddev config in a `cakephp` project
2. Check .env in config folder. Variable must be spelled correctly.
No change in tests

fix: Fix spelling for DEBUG_KIT_SAFE_TLD env variable

---

docs/overrides/partials/header.html

- https://github.com/ddev/ddev/pull/6048#issuecomment-2040194194
Links with anchors open in the wrong position:
Stable:
https://ddev.readthedocs.io/en/stable/users/quickstart/#drupal
Latest:
https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal
The code that calculates this:
https://github.com/squidfunk/mkdocs-material/blob/68126abb567ed9f9c5940af5ba31c6005c499596/src/templates/assets/stylesheets/main/extensions/markdown/_toc.scss#L61-L71
Ideally we would need to add another `+ 48px` here for a warning banner:
```scss
--md-scroll-margin: #{px2rem(48px + 24px)};
```
Uses a fixed value of `6rem` for the margin. This is not ideal, as it may not work for all `font-size`, but at least it should satisfy most users.
Open on different devices …

docs: fix the scroll margin for links with anchors, for #6048

---

docs/content/developers/release-management.md
docs/content/users/configuration/config.md
docs/content/users/extend/custom-commands.md
docs/content/users/install/docker-installation.md

* Mention `disable_upload_dirs_warning` in the `upload_dirs` section
* Improve search likelihood on "custom commands"
* Remove "Alternate docker providers" as it's a basic FAQ section
* Add DOCKERHUB_USERNAME/TOKEN to list of required secrets

docs: several maintenance items

---

docs/content/users/extend/custom-compose-files.md

We made the mistake, of naming the container differently from the service, and thus not being able to access the service. We somehow overlooked the part about the container name. Also we wanted to have a different hostname and did not know if we have to set `VIRTUAL_HOST=$DDEV_HOSTNAME` or if this has side effects. If everything is configured correctly we can expose a completely different service on an arbitrary hostname.
I've clarified the wording. I mention traefik in the hostname conventions to explain why this is needed for smooth operations.
I've added an example in the VIRTUAL_HOST part to show what would be possible there. (hostname taken from a [ddev test](https://github.com/ddev/ddev/blob/v1.22.7/pkg/ddevapp/testdata/TestTraefikVirtualHost/docker-compose.extra.yaml#L12))
Maybe it …

docs: clarify additional compose service configuration

---

cmd/ddev/cmd/commands_test.go
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/host/launch

- #5525
I added an example in #5986 to run `ddev launch` with a specific port:
```
ddev launch $DDEV_PRIMARY_URL:3000
```
But this never actually worked:
```
DDEV_DEBUG=true ddev launch $DDEV_PRIMARY_URL:3000
FULLURL https://d10.ddev.site/:3900
```
`$DDEV_PRIMARY_URL` is not expanded because it is not available on the host side and `$DDEV_PRIMARY_URL:3000` and `:3000` are the same thing.
`ddev launch $DDEV_PRIMARY_URL:3000` only works if it is run in another DDEV custom script.
Adds actual support to launch ports.
```
ddev debug fix-commands
```
```
$ DDEV_DEBUG=true ddev launch :3000
FULLURL https://d10.ddev.site:3000
```
```
$ DDEV_DEBUG=true ddev launch :3000/test
FULLURL https://d10.ddev.site:3000/test
```
See a tip for HTTP to HTTPS redirect at …

feat: accept port in `ddev launch`, for #5525

---

cmd/ddev/cmd/commands_test.go
pkg/ddevapp/global_dotddev_assets/commands/web/pint

Laravel includes its own linter, pint, which is installed by default with 11.x
Adds the pint shortcut command.
I've tested this on Gitpod:
* Clean the Drupal test data first:
```
ddev delete -Oy d10simple
rm d10simple/ -rf
```
* Create a laravel project:
```
mkdir laravel
cd laravel/
ddev config --project-type=laravel --docroot=public --php-version=8.2
ddev start
``` 
* As you didn't install laravel yet,  `pint` should fail with instructions to install:
```
ddev pint
```
* Install laravel:
```
ddev composer create --prefer-dist laravel/laravel:^11
```
* Now `ddev pint` should succeed:
```
ddev pint
```
* And you will see
```
PASS   26 files  
```
Added a test verifying the command is added to Laravel projects.
Run the individual test with `go test -v -run TestCustomCommands …

feat: add pint command to laravel projects

---

pkg/ddevapp/dotddev_assets/php/README.txt
pkg/ddevapp/dotddev_assets/php/php-example.ini.example

* #6052 
Add .php directory with example and readme
* `ddev start`
* Review the provided files in .ddev/php
* Verify that nothing is added to the git index (`git status`) should not show anything.

fix: provide example .ddev/php folder and README, fixes #6052

---

docs/content/users/configuration/config.md

The config docs for `ddev_version_constraint` seemed weak
Add an example.

docs: Improve ddev_version_constraint

---

pkg/version/version.go
pkg/version/version_test.go

Noticed that we can show Docker API version.
Adds API version output.
Look for `docker-api`:
```
$ ddev version
ITEM             VALUE                                    
DDEV version     v1.23.0-beta1-10-g5cb608f31              
architecture     amd64                                    
cgo_enabled      0                                        
db               ddev/ddev-dbserver-mariadb-10.11:v1.23.0 
ddev-ssh-agent   ddev/ddev-ssh-agent:v1.23.0              
docker           25.0.3                                   
docker-api       1.44                                     
docker-compose   v2.26.0                                  
docker-platform  linux-docker                             
mutagen          0.17.2                                   
os               linux …
```

feat: add Docker API version to `ddev version`

---

pkg/versionconstants/versionconstants.go

docker-compose v2.26.1 contains a few bugfixes that may not be important, but are still worth a try.
https://github.com/docker/compose/releases/tag/v2.26.1

build: bump docker-compose to v2.26.1

---

.buildkite/macos-colima.yml
.buildkite/macos-colima_vz.yml
.buildkite/macos-docker-desktop-amd64.yml
.buildkite/macos-docker-desktop-arm64.yml
.buildkite/macos-lima.yml
.buildkite/macos-orbstack.yml
.buildkite/macos-rancher-desktop.yml
.buildkite/windows10_container.yml
.buildkite/windows10dockerforwindows.yml
.buildkite/wsl2-docker-desktop.yml
.buildkite/wsl2-docker-inside.yml
docs/content/developers/buildkite-testmachine-setup.md

We have perpetual problems with the `docker login` on Docker Desktop for windows, 
`:docker: Logging into docker registry
Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded`
This can be demonstrated on the command line.
https://buildkite.com/ddev/wsl2-docker-desktop/builds/5372#018ec23f-52ae-4ba9-beb3-826af374d24c
The whole business of logging on buildkite tests was to prevent rate-limiting by Dockerhub. But in the years since it was introduced, they put us on the DSOS program, where rate-limiting isn't a problem any more.
Remove the docker login from buildkite tests.

test: Remove docker login from buildkite tests

---

pkg/ddevapp/config_test.go

The recent introduction of pre-creating the project `.ddev/php` directory caused TestPHPOverrides to fail on traditional Windows:
https://buildkite.com/ddev/ddev-windows-mutagen/builds/4537#018ec0a3-1a37-4afa-9718-9930e764a04d
TestPHPOverrides was using fileutil.CopyDir(), which requires the target directory not to exist. 
Use the better tool, github.com/otiai10/copy, for copying

test: Fix TestPHPOverrides on Windows

---

.goreleaser.yml

* #6049 
Use the new syntax
Do a release. Probably v1.23.0-rc1

build: fix deprecated goreleaser configs, fixes #6049 [skip ci]

---

docs/content/users/install/docker-installation.md

* #6068 
Limactl create seems to have changed from using "default" as the default name and started using "docker"
Use `limactl create --name=default` to force the name to be default.

docs: limactl create needs --name=default, fixes #6068

---

docs/content/users/usage/commands.md

- #6013
Adds more examples of how to check and switch Node.js versions with `nvm`, creates a tip about `nodejs_version`, warns about `nvm use`.
https://ddev--6067.org.readthedocs.build/en/6067/users/usage/commands/#nvm

docs: add more examples how to use `ddev nvm`, fixes #6013

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md

* Add drupal9/11 tabs to quickstarts
* Add symfony
Rendered versions at:
* https://ddev--6060.org.readthedocs.build/en/6060/users/quickstart/#drupal
* https://ddev--6060.org.readthedocs.build/en/6060/users/quickstart/#symfony

docs: Add drupal9/11 tabs and symfony to quickstart

---

.spellcheckwordlist.txt
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/tests/ddev-webserver/general.bats
docs/content/users/quickstart.md
docs/content/users/usage/cli.md
pkg/versionconstants/versionconstants.go

In
* https://github.com/ddev/ddev/pull/6060
we added the symfony quickstart. But we had the awkward duty of adding it with a Dockerfile.
If we're going to push another ddev-webserver:v1.23.0-1... why not get this in?

feat: Add symfony cli

---

docs/content/users/usage/faq.md

"Flag --target-db has been deprecated, please use --database instead" when following instructions for multiple dbs on the FAQ page
Replaces --target-db flag by --database

docs: Replaced --target-db by --database

---

containers/ddev-webserver/ddev-webserver-base-files/etc/apt/preferences.d/blackfire
pkg/versionconstants/versionconstants.go

* #6078 
* Pin blackfire to the working version to make sure it doesn't try to update
Use blackfire. But that's impossible for anyone without an expensive subscription.
Anyway, `ddev ssh` and `sudo apt update && sudo apt upgrade` and nothing bad should happen.

build: pin blackfire to working package, fixes #6078

---

cmd/ddev/cmd/debug-capabilities.go
version-history.md

* #6051 
Update capabilities, version-history.md
* `ddev debug capabilities` review output
* Read version-history.md

feat: add ddev debug capabilities with corepack, version-history.md, fixes #6051

---

pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
pkg/ddevapp/webserver_config_assets/nginx-site-php.conf

* #6087 
This seems to have been a result of adding image file cache expirations to the nginx php setup in 
* https://github.com/ddev/ddev/pull/5580
Remove the image cache expiration that was added to the base 'php' type and `craftcms`.
Start a Kirby project using the quickstart, https://ddev.readthedocs.io/en/latest/users/quickstart/#kirby-cms
The images presented should load and show.

fix: revert additions to php/craftcms expires in nginx-site.conf, fixes #6087

---

cmd/ddev/cmd/debug-dockercheck.go
cmd/ddev/cmd/debug-nfsmount.go
pkg/ddevapp/commands.go
pkg/ddevapp/db.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/poweroff.go
pkg/dockerutil/dockerutils.go
pkg/dockerutil/dockerutils_test.go
pkg/fileutil/file_hash_test.go

* #6085 
* RunSimpleContainer() should use no healthcheck
* Don't attach full label to these containers, so they're not detected in waiting for container start
See #6085

fix: don't label transient containers and run without healthcheck, fixes #6085

---

pkg/ddevapp/poweroff.go
pkg/dockerutil/dockerutils.go

- #6088
The Docker filter used the old syntax from `fsouza/go-dockerclient`, and as a result, it was looking for `label=label=com.ddev.site-name` instead of `label=com.ddev.site-name`.
I also finally figured out the syntax for filtering by label only.
See #6088.
- #5787

fix: add Docker filter by label without value, fixes #6088

---

pkg/versionconstants/versionconstants.go

* #6086 
We didn't get 100% of the PHP upgrades done upstream because the build process is hugely slow, but we have most now, and certainly almost all the ones that matter. 
Point to new build with more up-to-date PHP packages.
`ddev ssh` and example PHP versions. Should have 
```
$ ddev php --version
PHP 8.3.6 (cli) (built: Apr 11 2024 22:03:32) (NTS)
Zend Engine v4.3.6, Copyright (c) Zend Technologies
with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
```

build: Update to latest ddev-webserver prior to v1.23.0 release, fixes #6086

---

.gitpod.yml

DDEV v1.23.0 is out.
Pushes a new Gitpod image.

build: update .gitpod.yml for v1.23.0 release [skip ci]

---

docs/content/users/install/ddev-installation.md

There's a trailing comma in the provided devcontainer.json, and codespaces won't have it.

docs: remove errant comma in codespaces devcontainer.json

---

cmd/ddev/cmd/scripts/test_ddev.sh
pkg/exec/exec.go

* #6111 
* Adding build-time connectivity test
* Catch signal and clean up on exit
* Check docker build-time connectivity to internet

fix: clean up test project on signal, fixes #6111

---

.gitpod.yml
.gitpod/images/Dockerfile

It's awkward to use ddev-ssh-agent on gitpod
Put it in there again.
(this has already been pushed)

build: keep ddev-ssh-agent on gitpod, fixes #6132 [skip ci]

---

pkg/versionconstants/versionconstants.go

docker-compose 2.27.0 is out. See if it works.

build: bump docker-compose to 2.27.0

---

pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/drupal.go
pkg/versionconstants/versionconstants.go

* #6110 
Drupal 11 added an arbitrary sqlite3 version constraint that is hard to meet with Debian Bookworm
Install it using debs from Debian 13 Trixie
* Install drupal 11 site
* `ddev exec sqlite3 --version` should show 3.45.1
It's a sad location, but I added a test in TestDdevFullSiteSetup for drupal 11 that is specific to this case. I'm open to better suggestions. It could have its own test, but that seemed even worse.
* #6110 
* https://www.drupal.org/project/drupal/issues/3346338#comment-15572139
* https://github.com/justafish/ddev-drupal-core-dev/pull/23#discussion_r1581724491

fix: provide sqlite 3.45 for drupal11, fixes #6110

---

.github/workflows/pr-artifacts-comment.yml

- https://github.com/gitpod-io/gitpod/issues/19519
I tried https://pullrequestbadge.com/ from https://github.com/gitpod-io/gitpod/issues/19519#issuecomment-2093438752, but decided to do something else.
Found these:
- https://gist.github.com/tianhaoz95/5bf47c416b4b641d83a2022f977a0ec0
- https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/facilitating-quick-creation-and-resumption-of-codespaces#creating-an-open-in-github-codespaces-badge
I did not find the light/dark variants for the images:
Light background:
Dark background:

build: show badges for Gitpod and GitHub Codespaces in PRs

---

docs/content/users/install/ddev-installation.md
scripts/install_ddev_wsl2_docker_desktop.ps1

- #5915
Ubuntu 24.04 doesn't have `curl` by default.
Installs `curl` before running it.

docs: install curl for Debian/Ubuntu and WSL2, fixes #5915

---

.github/ISSUE_TEMPLATE/bug_report.yml
cmd/ddev/cmd/scripts/test_ddev.sh
docs/content/users/usage/troubleshooting.md
markdown-link-check.json

People are often asking about issues that have been fixed in current stable.
* Encourage them to upgrade before filing an issue.
* Minor improvements to checkboxes and suggestions to start with.
* Minor improvements to `ddev debug test`, including curl of google.com to test internet access
* Minor improvements to troubleshooting suggestions
Here's what it looks like:

docs: encourage people to use latest stable version

---

cmd/ddev/cmd/debug-refresh.go

From Drupal DDEV Slack:
https://drupal.slack.com/archives/C5TQRQZRR/p1715061420332539
```
ddev debug refresh
...
Failed to execute docker-compose -f exit status 17 build web --no-cache: %!v(MISSING) 
```
Adds missing variables to the output.

fix: show error in `ddev debug refresh`

---

pkg/ddevapp/traefik.go

Global traefik file not closed after creation
close global traefik file after creation

fix: close global traefik file after creation

---

pkg/ddevapp/provider.go

From https://discord.com/channels/664580571770388500/1232668554550186024/1232668554550186024
The .ddev/.downloads/files directory may exist somehow when trying to just get databases. 
Currently in HEAD `ddev pull` ignores failure to delete and recreate the .downloads directory.
Check the error.

fix: getDatabaseBackups() should check error on .downloads deletion

---

cmd/ddev/cmd/config.go
cmd/ddev/cmd/debug-migrate-database.go
docs/content/users/extend/database-types.md
pkg/nodeps/values.go

```
$ ddev debug migrate-database mariadb:12345
Is it OK to attempt conversion from mariadb:10.11 to mariadb:12345?
This will export your database, create a snapshot,
then destroy your current database and import into the new database type.
It only migrates the 'db' database [Y/n] (yes):
```
Fixed the condition for valid db versions. I came across it and couldn't understand how it worked before. During debugging, I saw that instead of the version, for example, `8.0`, the whole string `mysql:8.0` was passed inside.

fix: check for valid db version in `ddev debug migrate-database`

---

containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
pkg/versionconstants/versionconstants.go

From Discord https://discord.com/channels/664580571770388500/1238432307526897725/1238432307526897725
```
$ ddev start
...
Failed waiting for web/db containers to become ready: web container failed: log=, err=health check timed out after 2m0s: labels map[com.ddev.site-name:tryddevproject-12211 com.docker.compose.service:web] timed out without becoming healthy, status=, detail= ddev-tryddevproject-12211-web:starting - more info with [
ddev logs -s web
docker logs ddev-tryddevproject-12211-web
docker inspect --format "{{ json .State.Health }}" ddev-tryddevproject-12211-web | docker run -i --rm ddev/ddev-utilities jq -r
] 
```
```
$ ddev logs -s web
...
+ install_nvm.sh
=> nvm is already installed in /home/mcdruid/.nvm, trying to update using git
(the log ends here)
```
```
$ docker run --rm …
```

fix: add timeout for install_nvm.sh

---

docs/content/users/extend/customization-extendibility.md

https://stackoverflow.com/questions/78460055/enabling-server-status-mod-status-in-ddev-project
The user there apparently didn't know about the magic of #ddev-generated
Mention #ddev-generated in the apache section.

docs: Add info about #ddev-generated for apache-fpm users

---

pkg/ddevapp/config.go

Suddenly we're not able to support sqlite/libsqlite 3.45.1 because it's gone from the repo we were pulling it from, so Drupal 11 startup fails.
Pull from snapshot.debian.org
I do wonder if we should only grab the 3.45 sqlite if they have omit_containers[db].
I don't understand why we didn't catch this in latest test on master (https://github.com/ddev/ddev/actions/runs/9035899711/job/24831603173) unless they just removed the package between the time that started and when I was testing. (Search for "DdevFullSiteSetup for TestPkgDrupal11").  Code is in https://github.com/ddev/ddev/blob/a96ab265933cc9c94c7533740fd40d78add0ccc5/pkg/ddevapp/ddevapp_test.go#L2221-L2232
I did manually test TestDdevFullSiteSetup with drupal11 on master and it failed there and succeeds here.
Start a d11 project

fix: retrieve Drupal 11 sqlite3 packages from snapshot.debian.org

---

containers/ddev-webserver/ddev-webserver-base-scripts/healthcheck.sh
containers/ddev-webserver/ddev-webserver-prod-scripts/healthcheck.sh

- #6033
I noticed that I forgot to update `healthcheck.sh` for production.
1. Copies the supervisorctl changes from #6033
2. Small reformatting (remove extra spaces, use `printf` output for variables)

build: update hardened/prod healthcheck.sh, for #6033

---

pkg/versionconstants/versionconstants.go

It's release time for v1.23.1, push new images.

build: bump images to v1.23.1 for release

---

cmd/ddev/cmd/commands.go
cmd/ddev/cmd/commands_test.go
cmd/ddev/cmd/testdata/TestCustomCommands/global_commands/.hiddendir/not-a-command

DDEV thinks hidden directories in `~/.ddev/commands/` hold commands for services with names that start with a `.`
This can result in commands like this showing up:
Note that the `composer.lock`, `composer.json`, and `config.yml` files all live in a hidden directory.
(For reference, `.php-utils/` here contains code and dependencies that my global host commands share - see https://github.com/GuySartorelli/my-ddev-commands if you're curious)
Skips hidden directories, so that files in those directories are not treated like commands.
Add a hidden directory in `~/.ddev/commands/` with some files in it and run `ddev` - before the PR they will show up in the commands list, but afterwards they shouldn't.
Tests that a command in a hidden directory doesn't show in the commands list
N/A
In the very …

fix: Skip hidden directories when creating commands

---

pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
pkg/ddevapp/global_dotddev_assets/commands/web/xhprof

The `xdebug` command has a toggle option, but `xhprof` doesn't. They're both really similar in their operation so it makes sense to add a `ddev xhprof toggle` option.
Adds the option.
Also some unrelated-but-adjacent refactoring of xdebug, which was pretty convoluted.
- Try `ddev xhprof toggle` and validate the status with `ddev xhprof status`
- Check that hitting `tab` after typing `ddev xhprof ` gives you `toggle` amongst the other options.
- Try `ddev xdebug toggle` and `ddev xdebug status` as a sanity check for the refactor
Existing tests should cover the xdebug refactoring.
There's no tests at all for xhprof that I could find, so adding them seems out of scope. Happy to add if maintainers disagree with that assessment though.
- #5782 
N/A

feat: Add toggle option for xhprof command, rework xdebug, fixes #5782

---

cmd/ddev/cmd/push.go
pkg/util/prompt.go
pkg/util/utils_test.go

Sensitive operations such as `ddev provider push` recommend being careful but default to a 'yes' value if left blank.
We add a utility, `ConfirmTo(prompt, default)` which takes the logic of `Confirm(prompt)` and allows passing a default value (of true or false).
We then use `ConfirmTo` in the push command and default to `false`.
Lastly, `Confirm` is updated to be a wrapper of `ConfirmTo`, thus maintaining current behavior without repeating code.
1. Config a project with a provider (any)
2. Attempt to push to the provider
3. You should see the prompt message ending in `(y/N)` and if blank is submitted it will cancel the operation
Replaces `TestConfirm` with `TestConfirmTo`. Since `Confirm` is just a wrapper, its possible values have already been accounted for in `TestConfirmTo`.
#6103

feat: Add support for negative default in confirm prompt, fixes #6103

---

pkg/ddevapp/utils.go

- #5684
The refactored code had an incorrect condition for Gitpod and Codespaces.
- https://github.com/ddev/ddev/issues/6102#issuecomment-2106255867
The primary URL should point to the Gitpod or Codespaces URL.
```
$ ddev describe -j
...
"httpURLs": [
"http://127.0.0.1:8080"
],
"httpsURLs": null,
```
I tried to add Gitpod and Codespaces generated URLs to httpURLs, it worked, but the result was confusing:
```
$ ddev describe -j
"httpURLs": [
"https://d10-8080.app.github.dev",
"http://127.0.0.1:8080"
],
"httpsURLs": null,
```
So I reverted the check for HTTP, and now it works as it should:
```
$ ddev describe -j
...
"httpURLs": [
"http://127.0.0.1:8080"
],
"httpsURLs": [
"https://d10-8080.app.github.dev"
],
```
Also `ddev describe` did not show `All URLs` with disabled router, so I moved …

fix: Gitpod and Codespaces can use HTTPS

---

docs/content/developers/release-management.md
docs/content/developers/testing-docs.md

Two Markdown link fragments were broken, and markdownlint was catching it, at least locally.

docs: Fix a couple of broken link fragments

---

docs/content/developers/release-management.md
docs/content/developers/testing-docs.md

This reverts commit 41f38c70098d6ba3613cc890e0334c88d2f4ad6a.
See discussion in #6197 
I had to do a --no-verify to push this because I have pre-push checks enabled

docs: Fix markdownlint problems by using different headers instead of different links

---

.github/workflows/pr-artifacts-comment.yml
README.md

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/ddev/ddev/pull/6196)
The link above ⬆️ opens the wrong repo, and the branch is not selected:
Fixes the link.
I also removes autostart from Gitpod link, because it should really have confirmation before creating a new workspace.
The link below works ⬇️
[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/?ref=20240516_stasadev_fix_codespaces_link&repo=669738338)

build: fix Codespaces link

---

.devcontainer/devcontainer.json
.devcontainer/setup_test_project.sh

- #6187
Sets directory permissions for `/workspaces/d10simple`
Removes hard-coded path for `/workspaces/ddev` (because users can clone the repo to a different directory).
```
git clone https://github.com/ddev/ddev.git my-ddev-copy
code my-ddev-copy
ls -l /workspaces
total 8
drwxr-xr-x  7 codespace codespace 4096 May 16 12:40 d10simple
drwxr-xr-x 25 codespace codespace 4096 May 16 11:46 my-ddev-copy
```
[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://github.com/codespaces/new?ref=20240516_stasadev_devcontainers&repo=669738338)

build: fix devcontainers postCreateCommand permissions, fixes #6187

---

cmd/ddev/cmd/root.go

- #6189
Adds a check for the `__complete` command before sending it to Amplitude.

fix: do not send autocomplete commands to Amplitude, fixes #6189

---

.gitpod.yml

DDEV v1.23.1 is out.
Pushes a new Gitpod image.

build: update .gitpod.yml for v1.23.1 release

---

.github/workflows/pr-check.yml

Since we introduced the concurrency check, we've been getting useless emails about the pr-check concurrency.
Remove it.

build: Remove concurrency/cancellation check on pr-build as it's useless [skip ci]

---

pkg/ddevapp/ddevapp_test.go

Drupal 11 has been moving along pretty fast, now at beta1. 
I updated ddev/test-drupal11 repo to 11.0.0-beta1 with a new release
Use the new release of 11.0.0-beta1

test: Update drupal11 test to 11.0.0-beta1

---

docs/content/users/quickstart.md

[Quickstart docs for TYPO3](https://ddev.readthedocs.io/en/latest/users/quickstart/#typo3) do not mention the official guide made by the TYPO3 organisation.
Add link to https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/Installation/TutorialDdev.html
None, only docs change
None, only docs change

docs: add link to TYPO3 ddev guides

---

docs/content/users/install/performance.md

At Drupalcon Portland 2024 someone was explaining how much they liked mutagen on their macOS amd64 machine, but their project could take 30 minutes to do the syncing.
I wasn't able to figure out working with them what the problem was. I eventually determined that we used to show the files syncing as they happened, but now we've replace it with dots, which makes debugging much harder.
Provide a technique for debugging.
Follow the instructions. To create a dummy file if you need one, use `dd if=/dev/zero of=dummyfile bs=1M count=5000`

docs: Add Debugging long mutagen startup time

---

cmd/ddev/cmd/config.go
pkg/ddevapp/config.go

`app.CheckExistingAppInApproot()` does not work properly if you run `ddev config` several times and change the project name:
```
$ ddev config --project-name=d10
Creating a new DDEV project config in the current directory (/home/stas/code/ddev/d10) 
Once completed, your configuration will be written to /home/stas/code/ddev/d10/.ddev/config.yaml
Configuring a 'php' project with docroot '' at /home/stas/code/ddev/d10 
Configuration complete. You may now run 'ddev start'. 
$ ddev config --project-name=d10-rename
You are reconfiguring the project at /home/stas/code/ddev/d10.
The existing configuration will be updated and replaced.
Configuring a 'php' project with docroot '' at /home/stas/code/ddev/d10
Configuration complete. You may now run 'ddev start'.
$ ddev config …
```

fix: add more checks for existing approot

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md

Saw a reddit post, which stated that it was not clear how to use Vite within DDEV, at least in the past https://www.reddit.com/r/laravel/comments/1cuietp/dockers_is_ddev_worth_the_hassle/
Add the most basic Vite usage information for Laravel + DDEV
Optional:
- a link to https://ddev.com/blog/working-with-vite-in-ddev/ would also be possible
- additionally we could say that more ways of exposing the port / exposing Vite are possible (like https://www.lullabot.com/articles/nodejs-development-ddev), but I think that would be too much for the quickstart docs.
- Check instructions after fresh install, I already did a fresh install of v11 and used the instructions in https://github.com/mandrasch/ddev-laravel-vite
- docs change
- https://github.com/ddev/ddev.com/pull/204

docs: add Vite infobox for Laravel quickstart

---

docs/content/users/usage/faq.md

Typo in the [current docs](https://ddev.readthedocs.io/en/stable/users/usage/faq/#how-can-i-change-a-projects-name). 
Change "thew" to "the"

docs: typo in faq "thew"

---

docs/content/users/configuration/config.md

Use of `nvm` and cached version of `node` can occur if updating config file to use `nodejs_version` after previously using `nvm` in `post-start` hooks.
Adds a note to the `nodejs_version` documentation with instructions on how to clear the cache.
No tests necessary.
Fixes #6204 
No special deployment actions needed. Documentation change only.

docs: Explain how to switch from  nvm to `nodejs_version`, fixes #6204

---

cmd/ddev/cmd/config.go
cmd/ddev/cmd/config_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go

In testing @stasadev 's improvements in
* https://github.com/ddev/ddev/pull/6208
it seemed to me that the instructional output of `ddev config` could be improved
New output, including project name and quoted dir:
```
rfay@rfay-xps13:~/workspace/j2$ ddev config --project-type=laravel --docroot=public --project-name=xxx
You are reconfiguring the project at /home/rfay/workspace/j2.
The existing configuration will be updated and replaced.
Created docroot directory at /home/rfay/workspace/j2/public
Configuring a 'laravel' project named 'xxx' with docroot 'public' at '/home/rfay/workspace/j2/public'.
For full details use 'ddev describe'.
Configuration complete. You may now run 'ddev start'.
```
Use `ddev config`

fix: Improve instructional output on 'ddev config'

---

pkg/ddevapp/backdrop.go
pkg/ddevapp/craftcms.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/drupal.go
pkg/ddevapp/magento.go
pkg/ddevapp/shopware6.go
pkg/ddevapp/typo3.go
pkg/ddevapp/upload_dirs.go
pkg/ddevapp/wordpress.go

* #6188 
It turns out that with mutagen enabled, all of our import-files and `ddev pull` actions will fail because the host-side target files directory gets removed during the import process.
When mutagen is enabled, then each of the `upload_dirs` are bind-mounted from the host. In this situation, the existing code removes the host-side directory, breaking the bind-mount because the host source dir has been removed.
`ddev restart` fixes everything, but that's just a workaround.
* Purge the source directory instead of removing it
* Use otiai10/copy to do the copying instead of fileutil.CopyDir (which requires the target directory not to exist)
With a Drupal (and all other CMS) directory, and with mutagen enabled, `ddev import-files --src=<tarball>` and verify that the files get loaded into …

fix: do not remove mounted files directory, fixes #6188

---

cmd/ddev/cmd/clean.go
cmd/ddev/cmd/config_test.go
cmd/ddev/cmd/delete.go
cmd/ddev/cmd/stop.go
cmd/ddev/cmd/utils.go
pkg/ddevapp/config.go

While testing #6208 I noticed a regression in:
- #5452
- #5555
```
ddev config --project-name=d10
ddev config --project-name=d10-rename
ddev config --project-name=d10-rename2
this project root /home/stas/code/ddev/d10 already contains a project named d10. You may want to remove the existing project with "ddev stop --unlist d10"
ddev stop --unlist d10
Project 'd10-rename' was found in configured directory /home/stas/code/ddev/d10 and it is already used by project 'd10'. If you have changed the name of the project, please "ddev stop --unlist d10" 
Failed to get project(s): the d10 project has an invalid hostname: 'd10.', see https://en.wikipedia.org/wiki/Hostname#Syntax for valid hostname requirements
```
And you are stuck with `ddev stop --unlist d10` until you manually clean …

fix: do not validate config in ddev clean, delete -O, stop -U

---

docs/content/users/usage/developer-tools.md

textlint just started complaining about the phrase "command line tool"
Pacify it.

docs: make textlint stop complaining about command line tool

---

cmd/ddev/cmd/describe.go
pkg/ddevapp/ddevapp.go

Right now, `ddev describe` outputs most of the information one needs to access the various services in a DDEV project. There are cases however where it neglects to output custom `VIRTUAL_HOST` values from `environment` sections of a Docker Compose service. These values can allow for vanity domains of a service. This could/would be common with add-on services like Solr, NodeJS applications or similar.
This PR modifies describe.go to try and pull in the information of the `environment` section of a service.
- Build binary of this PR.
- Have a test DDEV project that has a service and set its VIRTUAL_HOST environment variable to "`VIRTUAL_HOST=site1.$DDEV_HOSTNAME`"
- Start the project with the test binary.
- Run the `describe` command.
- The output should contain your custom virtual host …

feat: output the VIRTUAL_HOST if specified in environment variables of a service

---

.buildkite/test.sh
.spellcheckwordlist.txt
cmd/ddev/cmd/autocompletion_test.go
cmd/ddev/cmd/commands_test.go
cmd/ddev/cmd/config_test.go
cmd/ddev/cmd/homeadditions_test.go
cmd/ddev/cmd/mutagen-version.go
cmd/ddev/cmd/root.go
cmd/ddev/cmd/root_test.go
docs/content/users/configuration/config.md
docs/content/users/install/performance.md
docs/content/users/usage/architecture.md
docs/content/users/usage/commands.md
docs/content/users/usage/uninstall.md
pkg/ddevapp/config.go
pkg/ddevapp/mutagen.go
pkg/ddevapp/mutagen_test.go
pkg/dockerutil/docker_compose_version_test.go
pkg/globalconfig/global_config.go
pkg/globalconfig/schema.json
pkg/testcommon/testcommon.go
pkg/version/version.go
scripts/diagnose_mutagen.sh

- #5807 
This is my first time touching Go so please "go" easy on me! 😄 Thanks for having great documentation, good code, and an easy build process that made it a pretty easy learning process.
1. Allows to move the global `~/.ddev` directory to `$XDG_CONFIG_HOME/ddev` or predefined OS specific location:
* `~/.config/ddev` on Linux and WSL2 only
**Important: if `$XDG_CONFIG_HOME` is set, DDEV will automatically create `$XDG_CONFIG_HOME/ddev` dir, if it doesn't exist.**
2. If there are multiple DDEV global configurations, they are checked with the following priority:
1. `$XDG_CONFIG_HOME/ddev`
2. `~/.config/ddev` on Linux and WSL2 only
3. `~/.ddev`
The current location of the configuration directory can be checked using `ddev version | grep global-ddev-dir`
3. Switches from …

feat: generalize HOMEDIR management and respect XDG_CONFIG_HOME, fixes #5807

---

pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/providerLagoon_test.go

* #6249
We've already done a lot to mitigate this. 
* Pushed updated ddev-dbserver images for v1.23.1 that have the new client binaries so folks on v1.23.1 can at least get by
* https://github.com/ddev/ddev/pull/6253 fixed import-db so it wouldn't stumble on the new line
But we still had trouble of course *pushing* to remote. So TestPantheonPush failed for all the same reasons.
Rather than adding workarounds to our push tests, I figured I should just make ExportDB() and `ddev export-db` also remove the offending line, which should fix all of our Push  tests. 
ExportDB also removes the new mariadb line
Use `ddev export-db` with a new-style mariadb (10.11) and verify that the dump file does not have the offending directive.
I think all the tests stand on their own. I had to run many of them …

fix: Make export-db also remove new mariadb directive in dumpfile , fixes #6249

---

cmd/ddev/cmd/homeadditions_test.go
cmd/ddev/cmd/import-db_test.go
cmd/ddev/cmd/root_test.go
pkg/ddevapp/hooks_test.go

We've had some master test failures since https://github.com/ddev/ddev/commit/5b0e640a8dca6d0ee327de75495290a25efab3dc in Rancher desktop, older Colima, and traditional Windows
* Rancher and Colima seem to be a result of the docker provider not syncing bind-mounted directories fast enough. Fix with a `app.Restart()` at the top of offending test instead of `app.Start()`
* Windows failure looks like it's a result of previous test (TestPoweroffOnNewVersion) not cleaning up its tmp project correctly, and then TestCmdStart() fails to start that broken project.
Review, look for problems, look at test.

test: Fix test failures on master of Rancher, Colima, Windows

---

pkg/ddevapp/ddevapp.go

TestDdevAllDatabases was failing since we added the fix to use a `tail +2` on ExportDB to mitigate the mariadb-dump change of format. 
It turned out this was failing on mariadb:5.5 and mariadb:10.0, neither of which are available on arm64, and neither of which are tested routinely (only on full github test)
Use `tail --lines=+2` which seems to work on all versions of tail.
Use `ddev export-db` with mariadb:5.5 and 10.0
The tests caught this. That should be good enough :)

fix: tail for mariadb export-db doesn't work on older mariadb

---

cmd/ddev/cmd/autocompletion_test.go

On upstream/master tests, TestAutocompletionForCustomCmds fails intermittently on Colima.
There's no need to test this everywhere, and the problem appears to be colima, especially without virtiofs. 
Disable the test on Colima.

test: Skip TestAutocompletionForCustomCmds because of slow mount responses

---

.ci-scripts/generate_artifacts.sh

In generate_artifacts.sh (which builds the tarball versions for the release page) the curl download `curl --fail -JL -s -o mkcert "https://dl.filippo.io/mkcert/latest?for=windows/amd64"` was hanging, timing out, and causing build failure. 
Download from the github release instead of downloading from dl.filippo.io.

build: download mkcert from github

---

.ci-scripts/generate_artifacts.sh
.github/workflows/master-build.yml
.github/workflows/pr-build.yml

* upload-artifact is deprecated and needs to bump to v4
* mkcert.exe in tarball/zipball is wrong.

build: bump upload-artifact to v4 and fix mkcert.exe in tarball/zipball [skip ci]

---

docs/content/developers/buildkite-testmachine-setup.md

We can no longer use the `mysql` that comes with mariadb for our TestConfigFunctionality test
Use the one that comes with `mysql-client`

docs: install mysql-client instead of mariadb on macOS

---

.buildkite/windows10dockerforwindows.yml
cmd/ddev/cmd/root_test.go
cmd/ddev/cmd/start_test.go
pkg/testcommon/testcommon.go

Debugging Windows TestPoweroffOnNewVersion (and fallout from its failure)
One windows, give NTFS a few seconds to finish cleanup after `ddev delete`

test: Try to fix windows problems with TestPoweroffOnNewVersion

---

pkg/ddevapp/config_test.go

Failures from packages.sury.org have broken our tests for a day or so, and this has happened before. 
TestExtraPackages doesn't really need to test a PHP package, so at least for now it would be nice to move forward, so using a non-deb.sury.org package there.
* https://github.com/oerdnj/deb.sury.org/issues/2046#issuecomment-2143131325
Use a non-deb.sury.org package for TestExtraPackages.

test: Don't use php package in TestExtraPackages

---

pkg/version/version.go

- #6259
```
docker info | grep rancher
Context:    rancher-desktop
Name: lima-rancher-desktop
```
The name has `lima` prefix (it was added at some point?), and `lima` is checked earlier.
Moves up the condition for Rancher Desktop detection.
1. Use Rancher Desktop
2. `ddev version`
3. See `docker-platform  rancher-desktop`

fix: detect Rancher Desktop, fixes #6259

---

docs/content/developers/building-contributing.md

https://ddev.com/blog/contributor-training/ not yet mentioned on https://ddev.readthedocs.io/en/stable/developers/building-contributing/
- link to https://ddev.com/blog/contributor-training/
none
none

docs: add link to contributor trainings

---

docs/content/users/extend/custom-compose-files.md

Docs update related to https://github.com/ddev/ddev/pull/6136
Makes a slight update that shows a subdomain approach for VIRTUAL_HOST, which will be output with `ddev describe` due to the linked PR.
n/a
n/a
https://github.com/ddev/ddev/pull/6136

docs: Add a small update noting either a subdomain or arbitrary domain.

---

docs/content/users/install/phpstorm.md

The PHPStorm instructions are pretty clear, but setting the `COMPOSE_PROJECT_NAME` was missing from the instructions, making it impossible to set up PHPStorm. The screenshot already included this variable.
It adds a step in the instructions that explains that you need to set it and what the value should be.
- Set up a new project.
- Open it in PHPStorm.
- Follow the instructions.
You can't automate this afaik.
N/A
N/A

docs: Update PHPStorm instructions to include COMPOSE_PROJECT_NAME in manual instructions

---

.github/devcontainers/src/install-ddev/install.sh
cmd/ddev/cmd/scripts/test_ddev.sh
containers/ddev-ssh-agent/Dockerfile
containers/ddev-webserver/Dockerfile
docs/content/developers/building-contributing.md
docs/content/developers/buildkite-testmachine-setup.md
docs/content/users/extend/customizing-images.md
docs/content/users/install/ddev-installation.md
docs/content/users/install/ddev-upgrade.md
docs/content/users/install/shell-completion.md
docs/content/users/usage/faq.md
docs/content/users/usage/uninstall.md
pkg/ddevapp/config.go
pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade
pkg/versionconstants/versionconstants.go
scripts/install_ddev_wsl2_docker_desktop.ps1
scripts/install_ddev_wsl2_docker_inside.ps1

- #6235
`apt-get update` can fail in the user's custom Dockerfiles.
I thought we could search for `apt-get update` using a regex and automatically replace it in the resulting Dockerfile, but that seems like overkill because people can write it with different variations, like:
- `apt-get update`
- `apt-get update -y`
- `apt-get update -qq`
- `apt-get update -qq >/dev/null`
And the same with `apt`, so it's probably impossible to write a good regex to cover all cases and not break anything.
Replaces `apt-get update` with `(apt-get update || true)` in the docs.
Uses `apt-get` instead of `apt` everywhere.
Removes `/etc/apt/sources.list.d/blackfire.list` as we pin the blackfire package to a specific version and don't need it in `apt-get update`:
- #6078
1. `ddev start`
2. `ddev ssh`
3. `sudo …

build: standardize apt-get usage, remove blackfire from apt sources, for #6235, for #6078

---

pkg/dockerutil/dockerutils_test.go

TestCopyIntoVolume left a volume undeleted, named for the test
Clean it up at completion.

test: TestCopyIntoVolume should clean up after itself [skip ci]

---

pkg/ddevapp/ddevapp.go

On a test project, I disabled the database using:
```yml
omit_containers: 
- "db"
```
When I started the project, I saw:
```
$ ddev start
...
Waiting for web/db containers to become ready: [web] 
```
This (nitpic) PR makes the output more generic:
```diff
- Waiting for web/db containers to become ready: [web] 
+ Waiting for containers to become ready: [web] 
```
The line continues to show container names ('web') at the end.

refactor: make "waiting for" message more generic

---

Makefile

Several add-on tests were failing on HEAD last night apparently because dl.filippo.io was broken.
Makefile should use the github repo as source for `mkcert`.
The reality is that the homebrew formula already installs mkcert as a dependency, so at least in the add-on tests, this is pretty much irrelevant.

build: Use github instead of dl.filippo.io to get mkcert binary

---

.buildkite/test.sh
cmd/ddev/cmd/a.go
cmd/ddev/cmd/mutagen-cmd_test.go
cmd/ddev/cmd/mutagen-logs.go
cmd/ddev/cmd/restart.go
cmd/ddev/cmd/root.go
cmd/ddev/cmd/root_test.go
cmd/ddev/cmd/start.go
docs/content/users/install/performance.md
docs/content/users/usage/architecture.md
docs/content/users/usage/uninstall.md
pkg/archive/archive.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/hooks_test.go
pkg/ddevapp/mutagen.go
pkg/ddevapp/mutagen_test.go
pkg/ddevapp/poweroff.go
pkg/dockerutil/dockerutils.go
pkg/exec/exec.go
pkg/fileutil/file_hash.go
pkg/fileutil/file_hash_test.go
pkg/globalconfig/global_config.go
pkg/testcommon/testcommon.go

* #6234 
With our new ability to change the global configuration directory from `~/.ddev` to other places come new risks for mutagen. 
(Removed): Mutagen now keeps its directory in `<globaldir>/.mdd` instead of `<home>/.ddev_mutagen_data_directory`. 
There's a risk in changing that mutagen could continue using an obsolete mutagen session or accidentally use a docker volume that did not match.
* When computing the mutagen hash for uniqueness, include not only the `mutagen.yml` contents but also the location of the `mutagen.yml` and the global configuration location.
* Revert to using ~/.ddev_mutagen_data_directory to resolve risks of upgrades and environment variable changes (XDG_CONFIG_HOME)
Still working on explicit instructions that can demonstrate the underlying problem.
I think the …

fix: prevent various Mutagen conflicts between daemons when changing versions or global directory, fixes #6234

---

.github/workflows/master-build.yml
.goreleaser.yml

https://goreleaser.com/blog/goreleaser-v2/#upgrading
Bumps it.
I ran `goreleaser check` - all good.
I created a test release here https://github.com/ddev-test/ddev/releases/tag/v1.22.11-goreleaser

build: bump goreleaser to v2, update its action to v6

---

docs/content/users/install/performance.md

The example command is missing `ddev` at the start, `jq` may not be available.
Fixes it.

docs: fix mutagen example command

---

cmd/ddev/cmd/describe.go

Remove backticks from `` `ddev mailpit` `` and use `Launch: ddev mailpit` instead.
- #6276
Removes the backticks from `` `ddev mailpit` `` in `ddev describe`  to use `Launch: ddev mailpit` instead.

refactor: remove backticks from ddev mailpit in ddev describe info text, fixes #6276

---

go.mod
go.sum
vendor/github.com/amplitude/analytics-go/amplitude/constants/constants.go
vendor/github.com/amplitude/analytics-go/amplitude/plugins/destination/internal/amplitude_http_client.go
vendor/modules.txt

Amplitude did a [new 1.0.2 release](https://github.com/amplitude/analytics-go/releases/tag/v1.0.2) of their analytics-go, which we use.
It appeared to be a minor bug fix only, but this package gets very little maintenance, so I wanted to make sure we explicitly updated and tested it instead of getting it by accident someday in the future.
Use the new version
Manual testing is the key here. 
Use https://ddev.readthedocs.io/en/stable/developers/building-contributing/#examining-data-on-amplitudecom
Verify that expected events are arriving.

refactor: Update to new amplitude/analytics-go

---

cmd/ddev/cmd/auth-ssh.go
cmd/ddev/cmd/debug-test.go
cmd/ddev/cmd/exec_test.go
pkg/ddevapp/providerLocalfile_test.go
pkg/ddevapp/ssh_auth_test.go
pkg/dockerutil/dockerutils.go
pkg/fileutil/file_hash.go
pkg/fileutil/file_hash_test.go
pkg/nodeps/utils.go
pkg/util/utils.go

- #6284
`TestFileHash` is broken on Windows due to different slashes in the filepath.
Uses `filepath.ToSlash()` to normalize behavior for different OSs.

test: fix TestFileHash on Windows, fixes #6284

---

pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade

- #6274
The issue is caused by the fact that for loop items in bash were split by spaces.
Adds split by newlines only.
Can be tested without Windows:
```
mkdir -p "$HOME/folder space"
cp $(which ddev) "$HOME/folder space"
export PATH="$HOME/folder space":$PATH
ddev self-upgrade
```

fix: make self-upgrade command respect spaces, fixes #6274

---

cmd/ddev/cmd/auth-ssh_test.go
cmd/ddev/cmd/commands.go
cmd/ddev/cmd/debug-test.go
pkg/archive/archive.go
pkg/ddevapp/addons.go
pkg/ddevapp/apptypes.go
pkg/ddevapp/assets.go
pkg/ddevapp/backdrop.go
pkg/ddevapp/config.go
pkg/ddevapp/craftcms.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/django.go
pkg/ddevapp/drupal.go
pkg/ddevapp/magento.go
pkg/ddevapp/mutagen.go
pkg/ddevapp/shopware6.go
pkg/ddevapp/ssh_auth_test.go
pkg/ddevapp/typo3.go
pkg/ddevapp/wordpress.go
pkg/dockerutil/dockerutils.go
pkg/fileutil/embed.go
pkg/fileutil/files.go
pkg/fileutil/files_test.go
pkg/testcommon/testcommon.go
pkg/util/utils.go

Add-ons can't properly manage built-in DDEV resources because when you remove `#ddev-generated` the file is no longer "installed" with the add-on. When you remove the add-on the file without the `#ddev-generated` is not removed. But when you leave out `#ddev-generated`, the file is replaced with DDEV:
- #6173
Built-in DDEV assets are copied every time:
- #6190
Do not override bundled assets in the project directory if they are listed in add-on manifest in `project_files` and have `#ddev-generated`.
This will allow to override files generated by DDEV in `.ddev` directory, by moving control over them to the add-on.
And do not copy the embedded assets if their content is the same.
```
mkdir test-pr && cd test-pr
mkdir -p test-addon/xhprof && printf "name: …
```

feat: don't override ddev-generated built-in project files created by add-on, fixes #6173, fixes #6190

---

pkg/ddevapp/compose_yaml.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/utils.go

- https://github.com/phenaproxima/starshot-prototype/issues/94
- #6158
If there is a config in `.ddev/config.yaml`:
```yaml
working_dir:
web: /var/www/html/something
```
And the `something` directory doesn't exist on the host side, it will be created by Docker as root.
We can create the directory beforehand and it is only needed if it is in the approot.
1. Use Linux/WSL2.
2. `ddev config global --performance-mode=none`
3. `ddev config --web-working-dir=/var/www/html/something`
4. `ddev start`
5. check file permissions `ls -l something`
- https://github.com/moby/moby/issues/2259

fix: create `working_dir` for `web` if it doesn't exist, fixes #6158

---

containers/ddev-dbserver/Makefile
pkg/versionconstants/versionconstants.go

- #6250
- https://github.com/ddev/mysql-arm64-images/pull/8
- https://github.com/ddev/mysql-arm64-images/pull/9
- https://github.com/ddev/xtrabackup-build/releases/tag/8.0.35-30
- https://perconadev.atlassian.net/browse/PXB-3304
It looks like we can bump to mysql 8.0.36 now, with xtrabackup 8.0.35. 
Update
Note that this updates the mysql:8.0 image to Ubuntu 22.04
Use mysql:8.0 and do snapshots and snapshot restores. 
Existing tests may be adequate.

build: Bump mysql to 8.0.36, fixes #6250

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #6083
mysql and mysqldump in the `ddev-webserver` don't handle mysql's new sandbox directive. 
This installs the 10.11.8-MariaDB of the mariadb client (mysql) and the related mysqldump in the ddev-webserver
We already have matching versions in the ddev-dbserver, but some tools like drush and craft cms's backup tools use local tools in the ddev-webserver.
Try creating database dumps on ddev-webserver and importing them various places
You'll note `ddev exec 'mysqldump db >/tmp/db.sql'` will create a db.sql that has the dreaded `/*!999999\- enable the sandbox mode */`
`ddev import-db` and `ddev export-db` now strip this, but if processing is done by application-level things like drush, your mileage may vary. The sql dump that you create may not be import-able by a different version of …

fix: Use mariadb repositories for mariadb-client, for #6083

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

yq yaml parser has a new version with multiple improvements 
bump version to the latests stable release (v4.44.1)
install ddev with this PR and launch yq --version inside web container. Version should be v4.44.1.
None 
None

build: bump yq to v4.44.1

---

cmd/ddev/cmd/commands.go
pkg/ddevapp/global_dotddev_assets/commands/web/drush
pkg/ddevapp/global_dotddev_assets/commands/web/xdebug

- #5523
- #6275
DDEV users may run some legitimate bash commands built into DDEV and see errors like this:
```
$ ddev drush
Error: unknown command "drush" for "ddev"
Did you mean this?
push
Run 'ddev --help' for usage.
```
For our users, this is confusing, they don't know what to do and how to fix it. I myself have been hit by an "unknown command" several times.
We need to provide better output to indicate why the specified command does not work.
Adds a warning before "unknown command" error for custom bash commands, explaining why they don't work.
```
$ cd ~ && ddev mailpit
Command 'mailpit' cannot be used outside the project directory.
$ cd ~/workspace && mkdir command-warnings && cd command-warnings && ddev config --auto --database="postgres:16"
$ ddev drush
Command 'drush' is not …
```

feat: add warnings for global commands when they are "unknown", for #5523, for #6275

---

cmd/ddev/cmd/composer-create.go

- https://github.com/ddev/ddev/pull/6256#discussion_r1627427307
`.env.local` is not created in the Sulu project quickstart, but it should.
`ddev composer create` doesn't run `post-root-package-install` composer script because Mutagen doesn't perform a sync.
Adds additional `app.MutagenSyncFlush()` right before checking for `composer.json`
```
ddev config global --performance-mode=mutagen
mkdir my-sulu-site && cd my-sulu-site
ddev config --project-type=php --docroot=public --upload-dirs=uploads
ddev composer create sulu/skeleton
Executing composer command: [composer run-script post-root-package-install]
ls .env.local
```

fix: Composer post-root-package-install didn't work with Mutagen enabled

---

containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
pkg/ddevapp/providerAcquia_test.go
pkg/ddevapp/providerLagoon_test.go
pkg/versionconstants/versionconstants.go

* #6295
* TestLagoonPush broke for the same reason
* We want to put a `neutral` mysql/mysqldump in there for people in this situation, so it's now in /usr/local/mariadb-old/bin
Acquia uses MySQL 5.7. We were using the default MariaDB:10.11 for the TestAcquiaPush test, and of course it has the mariadb-client 10.11.8, which has the broken directive in it.
This changes the tests to use MySQL 5.7, which now gets the MySQL 5.7 client in it, which should work OK.

test: Fix TestAcquiaPush and TestLagoonPush, add mariadb-old clients, fixes #6295

---

cmd/ddev/cmd/root.go

This has apparently been an issue for quite some time, but if you change DDEV versions (upgrade, test a new one, whatever - or just change the `last_started_version` in ~/.ddev/global_config.yaml, it prompts you to poweroff. I guess I always did this... until recently. I didn't want to wait for it.
But then I would see that all of my other projects (the ones I didn't want to impact with a poweroff) were broken because their mutagen session was gone.
If people do not agree to a poweroff, do not delete their mutagen sessions.
Change the last_started_version in global config and `ddev start` a project.  Do not accept poweroff.The other projects should not be broken.

fix: Don't terminate mutagen sessions on upgrade/version change

---

docs/content/users/install/ddev-upgrade.md
docs/content/users/usage/faq.md
docs/content/users/usage/troubleshooting.md

From Discord:
ddev version different when trying to upgrade
https://discord.com/channels/664580571770388500/1250826678096236554/1250826678096236554
Updates instructions to include more use cases.
Adds a tip to the "Upgrading DDEV" page.
Rendered version is at https://ddev--6310.org.readthedocs.build/en/6310/users/install/ddev-upgrade/

docs: update instructions for cleaning up old `ddev` binaries

---

containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
pkg/ddevapp/config.go
pkg/versionconstants/versionconstants.go

* https://github.com/ddev/ddev/issues/6083#issuecomment-2165714455
It seems that people still do use MySQL 5.6 and maybe somebody out there still uses 5.5
We can't build the clients for those long-obsolete versions for Debian 12 Bookworm, but they should work fine with the MySQL 5.7 client. 
If MySQL 5.5 or 5.6, use the mysql 5.7 client in the ddev-webserver.
Try using mysql 5.6. `ddev exec mysql --version` should show the 5.7 client.
I tested this on Gitpod with mysql 5.5 and 5.6 and it seems to be fine.

fix: Support MySQL 5.5 and 5.6 on ddev-webserver by using MySQL 5.7 clients

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time to release v1.23.2, building and tagging all the new images.

build: prepare images for v1.23.2

---

.gitpod.yml
.gitpod/images/Dockerfile

- #6228
Sets `XDG_CONFIG_HOME=/workspace/.config` inside the Gitpod container.
DDEV global configuration will be stored in a non-volatile location: `${XDG_CONFIG_HOME}/ddev`
I added a symlink from `~/.ddev` to `${XDG_CONFIG_HOME}/ddev`, so it won't break a custom user script (e.g. in hooks) that uses the `~/.ddev` location.
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/ddev/ddev/pull/6315)
Click Open in Gitpod, change some global config setting, e.g.:
```
ddev config global --internet-detection-timeout-ms 4000
```
Stop the workspace in https://gitpod.io/workspaces, open it again, and confirm that setting is the same:
```
ddev config global | grep internet-detection-timeout-ms
internet-detection-timeout-ms=4000
```
Check that …

build: use $XDG_CONFIG_HOME in Gitpod for v1.23.2 release, for #6228 [skip ci]

---

docs/content/users/configuration/hooks.md

This removes a stray recommendation about adding php packages that somehow lived in the hooks page.

docs: Remove stray info about packages from hooks docs

---

docs/content/users/install/ddev-installation.md
docs/content/users/install/ddev-upgrade.md
pkg/ddevapp/global_dotddev_assets/commands/host/self-upgrade

* A fairly common question is "I upgraded DDEV but `ddev --version` still shows the old version.
* `mkcert` is installed as a dependency most places, so a separate mention of the download etc is not needed.
Update docs

docs: suggestion ddev --version, move mkcert -install to later

---

pkg/ddevapp/config.go
pkg/ddevapp/utils.go

In studying 
* #6317
I found that the project .ddev/.gitignore was not being created correctly at all. Mostly it was failing.
It's intended to look for named files, check them for #ddev-generated, and add them to the .gitignore if that's found *or* if there's an error in opening the file.
However, due to a bug in the logic, it wasn't successfully opening *any* file, and as a result was not adding files to the .gitignore that should be added (like if they had the #ddev-generated removed).
This PR:
* Removes a number of obsolete items from the CreateGitignore() call. I didn't recognize several of them, and didn't find them in a search.
* Fixes so we actually grep the right file before adding it to the .gitignore
Remove the "#ddev-generated" from an important file, like in providers dir, or …

fix: generated gitignore is not working correctly

---

containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
pkg/ddevapp/app_compose_template.yaml
pkg/versionconstants/versionconstants.go

- #6332
Yarn should not ask to download classic yarn with `corepack enable`.
Adds `COREPACK_ENABLE_DOWNLOAD_PROMPT=0` to disable download prompt for Yarn.
In addition, I found that `yarn set config cache-folder` was never called because of an incorrect condition.
1. `docker run --rm -it -v ddev-global-cache:/mnt/ddev-global-cache busybox sh -c "rm -rf /mnt/ddev-global-cache/corepack"` to remove cached yarn downloads
2. `ddev config --corepack-enable && ddev start && ddev yarn -v` should not ask for download
3. `ddev yarn config get cache-folder` should show `/mnt/ddev-global-cache/yarn/classic` (this command works only for yarn v1)

fix: autodownload yarn from corepack, and set cache-folder, fixes #6332

---

docs/content/developers/buildkite-testmachine-setup.md

Minor docs update for Buildkite setup for wsl-dd. The ngrok install was wrong; you can't use snap ngrok outside /home.

docs: windows-wsl2-dd needs apt install for ngrok

---

cmd/ddev/cmd/config-global.go
pkg/ddevapp/list.go
pkg/fileutil/files.go

- #6328
Introduces a new function to replace `$HOME` with `~`.
Fixes the output.
```
export XDG_CONFIG_HOME=~/test
ddev list
cp ~/.ddev/project_list.yaml $XDG_CONFIG_HOME/ddev/project_list.yaml
ddev list # look at the router
ddev help config global | grep "~/test"
```

fix: use real path to global config location, fixes #6328

---

.github/workflows/tests.yml

The nightly tests often interrupt in-progress builds because of our concurrency controls. That happens about 1am UTC, so probably @stasadev doesn't see it often and I do. 
Stop doing the nightly builds. We ignore then anyway, and we do enough builds all the time that we see shifts when they happen.

test: stop running nightly tests [skip ci]

---

pkg/ddevapp/hooks_test.go

* #6313
This has just failed so commonly it's worth figuring out
Perhaps the app.Stop() at end of the for loop is relevant. app.Stop() really isn't designed for repetitive use like it would otherwise be used here.

test: Attempt to debug TestProcessHooks intermittent failures, fixes #6313

---

.goreleaser.yml
cmd/ddev/cmd/config.go
cmd/ddev/cmd/debug-migrate-database.go
containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/etc/gai.conf
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/templates.go
pkg/versionconstants/versionconstants.go

From Discord https://discord.com/channels/664580571770388500/1252792407775514686
Something changed in Debian Bookworm, which results in ping being using IPv6 inside a container:
```
$ ddev exec ping -c 1 localhost
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.026 ms
--- localhost ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.026/0.026/0.026/0.000 ms
```
I don't have a pattern here, but I remember a time when it always used IPv4. We can make it more predictable to always prefer IPv4 over IPv6.
1. There is a commented section in `/etc/gai.conf`, that we can uncomment:
- https://wiki.archlinux.org/title/IPv6#Prefer_IPv4_over_IPv6
```
#
#
precedence ::ffff:0:0/96  100
```
2. …

build: use IPv4 inside a container, mariadb-client 11.4 for the webserver

---

cmd/ddev/cmd/composer-create.go
cmd/ddev/cmd/composer-create_test.go
cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/composer.json
cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/test-ddev-require-dev/composer.json
cmd/ddev/cmd/testdata/TestComposerCreateCmd/.ddev/test-ddev-composer-create/test-ddev-require/composer.json
docs/content/users/quickstart.md
docs/content/users/usage/developer-tools.md

- #6300
- #6246
- #5058
Composer options were not respected by `composer run-script`.
Makes `ddev composer create` fully compatible with all possible composer options. I removed all the hard-coded options.
Adds composer options to `composer run-script`.
Adds `--no-interaction` to CakePHP quickstart.
---
`--preserve-flags` (which doesn't add `--no-plugins` and `--no-scripts`) didn't work as expected, I decided to remove it.
This is not a breaking change, because `--preserve-flags` didn't work before (it was always `false`).
---
I moved `composer run-script post-create-project-cmd` outside the condition for `composer install`, to make it work the same way as in `composer create-project`.
---
If you passed `--no-scripts`, DDEV tried to run `composer run-script`, which was wrong behavior, …

fix: pass all valid options to nested commands in `ddev composer create`, fixes #6300, fixes #6246, for #5058

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md

Initial draft for adding a quickstart for joomla to https://ddev.readthedocs.io/en/latest/users/quickstart/ . Only downside unfortunately i havent found a static link for download the latest archive with curl. 
Use https://ddev--6255.org.readthedocs.build/en/6255/users/quickstart/#joomla

docs: Joomla Quickstart

---

containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
containers/ddev-webserver/tests/ddev-webserver/general.bats
pkg/ddevapp/ddevapp_test.go
pkg/versionconstants/versionconstants.go

* #6355
When installing custom-built mysql clients in ddev-webserver we only added `mysql` and `mysqldump`, but people also use `mysqladmin`
Add `mysqladmin`
With a mysql:8.0 or mysql:5.7 project use `ddev ssh` and `mysqladmin` or `ddev exec mysqladmin`
Added check to verify in both the container test and TestWebserverDBClient

fix: add mysqladmin to web container for mysql, fixes #6355

---

pkg/ddevapp/config.go

From Discord https://discord.com/channels/664580571770388500/1257256256989696021
```
$ ddev config --webimage-extra-packages software-properties-common && ddev restart
$ ddev logs -s web
...
+ exec /usr/bin/supervisord -n -c /etc/supervisor/supervisord-nginx-fpm.conf
...
PermissionError: [Errno 13] Permission denied: '/var/log/supervisord.log'
+ trap - SIGTERM
+ kill -- -1
```
Related issue with the same problem:
- #5898
Adds `chmod 777 /var/log`.
Some packages have default folder/file permissions described in `/usr/lib/tmpfiles.d/*.conf` files.
This may cause problems with previously set permissions when installing/upgrading packages.
```
$ cat /usr/lib/tmpfiles.d/var.conf | grep /var/log
d /var/log 0755 - - -
f /var/log/wtmp 0664 root utmp -
f /var/log/btmp 0660 root utmp -
f …
```

fix: add chmod for /var/log, for #5898

---

pkg/ddevapp/config.go

- #6362
I googled how people install PostGIS and found out that they have a really hard time with it because they don't know what packages they need to install to be able to use it.
I decided to provide complete installation instructions for each supported version of PostgreSQL in DDEV: https://stackoverflow.com/a/78691855/8097891
And I found that `dbimage_extra_packages` didn't work at all for PostgreSQL 9,10,11:
```
#13 [db  3/14] RUN (apt-get -qq update || true) && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests postgresql-11-postgis-2.5 postgresql-11-postgis-2.5-scripts postgis
#13 1.420 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release …
```

fix: install extra content in Dockerfile earlier, for #4394

---

pkg/ddevapp/hostname_mgt.go
pkg/netutil/netutil.go

In testing Let's Encrypt/Casual Hosting in
* https://github.com/ddev/ddev/pull/6317
I noted that even when the IP address of the machine was a local (non-localhost) address, it was still adding 127.0.0.1 to the /etc/hosts on that machine. For example, if the hostname DDEV wanted to use was `test.something.thefays.us` and `test.something.thefays.us` properly resolved to the current machine, DDEV would still add `test.something.thefays.us` to /etc/hosts as 127.0.0.1
This was a result of the logic in AddHostsEntriesIfNeeded() that said
```go
// If we had successful lookup and dockerIP matches
// with adding to hosts file.
if err == nil && len(hostIPs) > 0 && hostIPs[0] == dockerIP {
continue
}
```
Essentially, it was only allowing the looked-up value of 127.0.0.1 (typical dockerIP) as …

fix: Check to see if IP address is local to determine whether to add to hosts

---

pkg/ddevapp/backdrop.go
pkg/ddevapp/drupal.go
pkg/ddevapp/drupal/backdrop/settings.ddev.php
pkg/ddevapp/drupal/backdrop/settings.php

As described in https://github.com/ddev/ddev/issues/6090, if these settings are explicitly set in settings.ddev.php, trying to set them in settings.php or settings.local.php never takes.
This PR removes the lines in settings.ddev.php that explicitly set these two settings, which allows the values to be set in settings.php or settings.local.php (which unlike Drupal is provided by default OOTB in Backdrop).
1. Install a vanilla Backdrop CMS site using the DDEV recipe.
2. Edit your `settings.php` file or the `settings.local.php` file and set `$settings['backdrop_drupal_compatibility'] = FALSE;`.
3. Try reading that setting via `settings_get('backdrop_drupal_compatibility')` (for instance using the devel module and `dpm()` or something) -> regardless of how that setting is configured, it is …

fix: do not explicitly set the backdrop_drupal_compatibility and update_free_access settings, fixes #6090

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time for v1.23.3, mostly because we had trouble with permission on /var/log as described in
* https://github.com/ddev/ddev/pull/6363
This bumps the images to current as well as pulling in all of Debian 12.6, which is what caused the pain.

build: bump images to v1.23.3

---

.gitpod.yml

After release we have to bump the gitpod image for use with v1.23.3. This does it.

build: Bump gitpod image for DDEV v1.23.3 [skip ci]

---

containers/ddev-dbserver/Dockerfile
pkg/versionconstants/versionconstants.go

Percona seems to have changed their method of installing xtrabackup.
https://docs.percona.com/percona-software-repositories/percona-release.html
Add their new technique to Dockerfile.

build: percona xtrabackup changed install technique

---

.github/workflows/tests.yml

The nginx-proxy router is deprecated, and we've never seen problems with it. 
Stop running github tests for it.

test: stop testing deprecated nginx-proxy [skip ci]

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
pkg/versionconstants/versionconstants.go

TestWebserverDBClient fails fairly regularly on MariaDB 11.4
- https://github.com/ddev/ddev/actions/runs/9788192607/job/27025855851
- https://buildkite.com/ddev/ddev-macos-arm64-mutagen/builds/8122#01907bda-1be5-4dc2-a1cd-d1887c6e38d5
It seems that mariadb-client for 11.4 is not always installed, the offending line is:
```
timeout 30 mariadb_repo_setup --mariadb-server-version="mariadb-${MARIADB_VERSION}"
```
There are some problems with `mariadb_repo_setup`:
1. It adds three repos (server, tools, maxscale), but we only need the server:
```
$ ddev exec sudo apt update | grep mariadb
Hit:4 https://downloads.mariadb.com/Tools/debian bookworm InRelease
Hit:11 https://dlm.mariadb.com/repo/mariadb-server/10.11/repo/debian bookworm InRelease
Hit:12 …
```

fix: improve installation method for mariadb-client

---

cmd/ddev/cmd/scripts/test_ddev.sh

* #6339 
Don't emit warning on WSL2
Do `ddev debug test` on WSL2 with Docker Desktop. No warning should show.
For extreme extra credit, do `ddev debug test` on Linux with Docker Desktop for Linux. Warning should show.

fix: Don't warn about Docker Desktop on WSL2, fixes #6339 [skip ci]

---

markdown-link-check.json

https://github.com/ddev/ddev/actions/runs/9847531874/job/27190957328#step:11:348
```
ERROR: 1 dead links found!
[✖] https://aur.archlinux.org/packages/ddev-bin/ → Status: 0
```
This is not the first time we see an error for this link, time to ignore it.

docs: stop checking aur.archlinux.org link [skip ci]

---

.gitpod.yml

`omit_containers: [ddev-router]` is not written to global DDEV config after:
- #6315
It led to problems with add-ons:
- https://github.com/ddev/ddev-phpmyadmin/issues/15
This is caused by the fact that `/workspace` appears to be a special folder that is overridden by Gitpod. It doesn't pick up any content from the pre-built Docker image.
Omits the `ddev-router` on the project init.
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/ddev/ddev/pull/6390)
Confirm that `ddev config global | grep omit` contains `ddev-router`.
Stop the Gitpod workspace, start it again and confirm the same.

fix: omit ddev-router for Gitpod (for DDEV PRs) [skip ci]

---

pkg/ddevapp/global_dotddev_assets/commands/host/launch

- #6389
Replaces the `${DDEV_HOST_WEBSERVER_PORT}` in the URL for all possible scenarios
Try in Gitpod and Codespaces:
1. `ddev mailpit` - it should open Mailpit
2. `ddev launch :8027` - it should replace `8080` with `8027`, don't add `:8027` to the URL
3. `ddev launch :8027/test` - the same and preserve `/test`
4. `ddev launch https://full-url-here:8027` - it should replace `8080` with `8027`, don't add `:8027` to the URL
5. `ddev launch https://full-url-here:8027/test` - the same and preserve `/test`
6. `ddev launch https://example.com:8080/test` - it should remain the same
7. `ddev launch :8080` - it should open the same URL as for `ddev launch`

fix: make `ddev launch` fully compatible with Gitpod and Codespaces, fixes #6389

---

cmd/ddev/cmd/composer-create.go
cmd/ddev/cmd/composer-create_test.go

- #6380
```
The "--repository" option does not exist.
```
Ignores flags with `=` for `composer install` and `composer run-script`.
Try Magento 2 quickstart https://ddev.readthedocs.io/en/stable/users/quickstart/#magento

fix: make composer subcommands ignore invalid flags on any errors, fixes #6380

---

pkg/ddevapp/ddevapp.go
pkg/versionconstants/versionconstants.go

https://hub.docker.com/r/ddev/ddev-utilities is used in:
- `ddev debug test`
- `ddev launch`
- the docs
But we don't pull it.
Let's pull it to avoid a couple of seconds of waiting.
```
docker rmi ddev/ddev-utilities
DDEV_DEBUG=true ddev debug download-images
```

feat: add ddev/ddev-utilities to the pulled images

---

cmd/ddev/cmd/commands_test.go
pkg/ddevapp/global_dotddev_assets/commands/host/phpmyadmin

- #6342
Adds a global phpmyadmin command that asks the user if they want to install the phpmyadmin addon.
If the user answers yes then the ddev get ddev/ddev-phpmyadmin command is run.
Since this is global once the addon is installed it will override the phpmyadmin command.
Configure a new directory for ddev `ddev config`
Run `ddev phpmyadmin`
You should be asked if you want to install the addon
If you answer no running `ddev phpmyadmin` will ask if you want to install again
If you answer yes you should receive a success message and a subsequent `ddev phpmyadmin` will launch phpmyadmin
No tests added
Adds global phpmyadmin command.

feat: add global phpmyadmin install command, fixes #6342

---

docs/content/users/configuration/config.md
docs/content/users/extend/additional-services.md
pkg/dockerutil/docker_compose_version_test.go
pkg/globalconfig/global_config.go

* We support using an external docker-compose (from path) but would never hope for it to be used. 
* However, it was implemented so that `docker-compose` folks could implement DDEV in their automated tests, so doesn't make sense to remove
* Sometimes Docker Desktop moves things around (as they did in macOS DD v4.32.0) and they lose the external `docker-compose`, perhaps on purpose, because they want `compose` to be used as a docker plugin.
* Stop testing that requires external docker-compose
* Update docs to be more specific about this feature not being used

test: stop testing use_docker_compose_from_path, update related docs

---

pkg/ddevapp/ddevapp.go

* #6102 
Handling ports in HTTP is always a little complex, port 80 is default for http, port 443 for https. Codespaces seems to handle the Host header and X-Forwarded-Host incorrectly when it's forwarding a nonstandard (not port 80) port.
Use port 80 by default in codespaces. This seems to do no harm. It affects only Codespaces.
* Run this PR in Codespaces
* Start a project
* Install Drupal 10
* Log in. If it works, it's fixed

fix: Use port 80 to get better headers for Codespaces, fixes #6102

---

docs/content/users/quickstart.md

- wrong `ddev config` option for extra-packages
- documentation fix

docs: correct config used to add extra-packages

---

docs/content/users/extend/additional-services.md

Searching the docs for "opensearch" will give no results. This might lead some to believe that it is not officially supported.
Update the `ddev get --list` example output in the docs to include a mention of all supported additional services.
-
Changes are limited to docs, no testing needed.

docs: Update 'ddev get' example

---

.buildkite/test.sh

There were [quite](https://buildkite.com/ddev/macos-colima/builds/396#0190acea-35ee-4f1b-817b-e36e04d286e8) [a](https://buildkite.com/ddev/macos-colima-vz/builds/1292#0190b7e9-91cd-4a55-a719-17b5731a413a) [lot](https://buildkite.com/ddev/macos-colima-vz/builds/1308#0190c165-cc86-4048-8713-31d281a48c3c) of suspicious TestSSHAuth failures on colima-vz on tb-macos-arm64-6, so I finally thought I'd take a look. 
I found a lot of volumes, especially the SSH volumes, stuck there. 
It looks to me like we haven't been successful deleting volumes at test startup.
* Make sure to delete volumes after all containers are stopped
* Double-delete
* Stop ignoring the output.

test: make sure that volumes in buildkite are deleted at test start

---

cmd/ddev/cmd/config.go
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go

* #6206 
Drupal modules frequently contain underscores in the project names. It's annoying to have to specify a different project name, or manually convert underscores to hyphens, each time I create a DDEV project for one. It seems a bit arbitrary that underscores aren't allowed.
When getting the project name from the directory name, underscores are replaced with hyphens.
This needs an additional test to ensure that a project directory containing underscores now has the default project-name working.
https://github.com/ddev/ddev/issues/6206

feat: Replace underscores with hyphens in project-name, fixes #6206

---

README.md

We aren't running CircleCI tests any more, but of course the badge says we're failing.
Remove the badge

docs: remove CircleCI badge as we aren't running their tests

---

cmd/ddev/cmd/config-global.go
cmd/ddev/cmd/config-global_test.go
cmd/ddev/cmd/config.go
cmd/ddev/cmd/config_test.go
docs/content/users/usage/commands.md
pkg/ddevapp/config.go

* `ddev config --omit-containers=""` doesn't remove `omit_containers` from `.ddev/config.yaml` as expected (#6140).
* `ddev config --additional-hostnames` and `ddev config --additional-fqdns` have the same problem.
This PR clears `omit-containers` when an empty string is passed. It uses the `Changed` method, consistent with the global version of the command. Changes are made in `handleMainConfigArgs` in `cmd/ddev/cmd/config.go`.
Manual testing involves running `ddev config --omit-containers=db` and `ddev config --omit-containers=""` and checking `.ddev/config.yaml`. Automated tests will be added to verify the flag's functionality.
Fixes issue #6140.
No special deployment actions needed. This change doesn't affect other code.

fix: clear omit_containers, additional_fqdns, additional_hostnames config with empty flag, fixes #6140

---

containers/ddev-dbserver/files/etc/my.cnf
pkg/versionconstants/versionconstants.go

* #6244
Turn off innodb_doublewrite to improve import-db performance
Try `ddev import-db` with huge databases

fix: Use turn off innodb_doublewrite to improve import-db performance, fixes #6244

---

pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/snapshot.go
pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.intervalandretriesset.yaml
pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.intervalset.yaml
pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.longtimeout.yaml
pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.nohealthcheck.yaml
pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.withlongstartperiod.yaml
pkg/ddevapp/testdata/TestConfigDefaultContainerTimeout/docker-compose.withshortstartperiod.yaml

* #5133 - over and over again
`default_container_timeout` hasn't had the behavior we expect, even though we've changed that behavior lots of times.
Resolve the differences between the docker-compose `timeout` and what we need, `start_period` or defaults for `start_period`
* Read [blog on this](https://ddev.com/blog/ddev-and-docker-healthchecks-technote)
* Try `ddev snapshot restore` with a larger snapshot
* Try it with different `default_container_timeout` - larger ones should result in more time for the snapshot restore
* Try `docker-compose.*.yaml` with a variety of healthcheck values, especially `start_period` There are a number of these for examples in the TestConfigDefaultContainerTimeout directory.
New `TestConfigDefaultContainerTimeout`, maybe it can get me out of hell eventually. …

fix: default_container_timeout should work right, fixes #5133 again

---

pkg/ddevapp/ssh_auth_test.go

TestSSHAuth() has been [failing intermittently on Colima, tb-macos-arm64-6](https://buildkite.com/ddev/macos-colima-vz/builds/1347#0190e21d-6c10-4546-834d-fde7873a3182), and we really don't need to know what it's done. So disable on Colima.

test: Skip TestSSHAuth on Colima

---

pkg/ddevapp/config.go

* #6425
* #6419
If we can't download and install sqlite 3.45, just move on.
Most Drupal11 users don't need it anyway.
* Turn off internet
* Create new Drupal11 project
* `ddev start`
* ddev config --update
* `ddev restart`
`ddev exec dpkg -l sqlite3` should show older sqlite

fix: fail gently if sqlite3 can't be downloaded for drupal11, fixes #6425, for #6419

---

pkg/ddevapp/mutagen.go
pkg/ddevapp/mutagen_test.go

- #6421 
The app is unable to start without a mutagen-agents.tar.gz file in the global bin directory.
This PR adds a check to make sure the tarbell exists in the DownloadMutagenIfNeeded function, and if it does not, downloads mutagen. It also adds a test to test this functionality works.
Remove the tarbell file in the global bin directory e.g. rm ~/.ddev/bin/mutagen-agents.tar.gz and restart the app e.g. ddev restart
Adds the TestDownloadMutagen test which has the same setup as TestMutagenSimple but removes the tarbell if it exists, then starts the app. Then it verifies that the tarbell has been downloaded. Then it removes it again and restarts the app, and finally verifies that the tarbell has been downloaded again.

fix: create mutagen-agents tarball if it doesn't exist, fixes #6421 

---

docs/content/users/configuration/config.md
docs/content/users/extend/customization-extendibility.md
docs/content/users/quickstart.md

Probably the best way these days to provide environment variables to containers/services is to use the `.ddev/.env` file.
* Move the Environment variable section to the front page the page it's on
* Put the `.env` discussion first
* Push up the search preference value
I still don't get a good hit in search except with "variables", "environment variables" doesn't do much.
Rendered version is at https://ddev--6439.org.readthedocs.build/en/6439/users/extend/customization-extendibility/#environment-variables-for-containers-and-services

docs: improve placement of .env for environment variables

---

cmd/ddev/cmd/get.go
docs/content/users/extend/additional-services.md

While working on
- https://github.com/ddev/ddev-varnish/pull/28
I noticed that different add-on actions are performed in different contexts, which is confusing.
- `pre_install_actions` in `$DDEV_APPROOT`
- `post_install_actions` in `$DDEV_APPROOT/.ddev`
- `removal_actions` in `$DDEV_APPROOT/.ddev`
Related change:
- https://github.com/ddev/ddev-addon-template/pull/54
Fixes documentation.
```
mkdir miniaddon && echo "name: miniaddon\npre_install_actions:\n- pwd\npost_install_actions:\n- pwd\nremoval_actions:\n- pwd" > miniaddon/install.yaml
ddev get miniaddon
ddev get --remove miniaddon
```

docs: show actual running context in `install.yaml` for add-ons

---

cmd/ddev/cmd/get.go
cmd/ddev/cmd/get_test.go
cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
cmd/ddev/cmd/testdata/TestCmdGetDdevVersionConstraint/invalid_constraint_recipe/install.yaml
cmd/ddev/cmd/testdata/TestCmdGetDdevVersionConstraint/valid_constraint_recipe/install.yaml
docs/content/users/configuration/config.md
docs/content/users/extend/additional-services.md
pkg/ddevapp/addons.go
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/utils.go

- https://github.com/ddev/ddev-xhgui/pull/31
- #5969
The current approach when you need to add a version constraint to an add-on involves using `ddev debug capabilities`, which is not obvious.
This isn't good because capabilities aren't added for each DDEV release and you can't add a version constraint for some minor release.
Adds `ddev_version_constraint` to `install.yaml` for add-ons that allows you to check the semver constraint.
TODO:
- https://github.com/ddev/ddev-addon-template/pull/55
- https://github.com/ddev/ddev.com/pull/235
```
git clone https://github.com/ddev/ddev-phpmyadmin
echo "ddev_version_constraint: '>= v1.23.4'" >> ddev-phpmyadmin/install.yaml
ddev get ddev-phpmyadmin # should show error
sed -i 's/v1.23.4/v1.23.3/' ddev-phpmyadmin/install.yaml # lower the constraint …
```

feat: add `ddev_version_constraint` for add-ons, remove `#ddev-nodisplay`, fixes #5969

---

docs/content/users/quickstart.md

* #6452
Move Drupal 11 to first, update the tag on the composer create
Update other composer-based Drupal's to show `ddev launch $(ddev drush uli)`
Try it out.
Rendered quickstart is at https://ddev--6453.org.readthedocs.build/en/6453/users/quickstart/#drupal

docs: promote drupal 11 now that it's released, for #6452

---

pkg/ddevapp/ddevapp_test.go

* #6452 
Drupal 11 out, update test tarballs to match it. 
Update drupal11 test, if it works, it should be OK.

test: Update tests for Drupal11 to latest tarballs, fixes #6452

---

docs/content/users/quickstart.md

- #6448
- Updated the Magento1 quickstart to use a terminal approach like other quickstarts.
- Adds `ddev config --web-environment-add=MAGE_IS_DEVELOPER_MODE=1` for the Magento1 quickstart as requested.
- Adds `-f` to `rm` where it was not added.
I tried other quickstarts, and I noticed a problem with backdrop when running it in `zsh`:
```
$ mv -f ./backdrop/{.,}* .
mv: cannot stat './backdrop/.editorconfig': No such file or directory
mv: cannot stat './backdrop/.gitignore': No such file or directory
mv: cannot stat './backdrop/.htaccess': No such file or directory
```
- It actually worked, but `&& rm -rf backdrop` was not executed, fixed it with `; rm -rf backdrop`
Try Magento1 quickstart.
https://ddev--6449.org.readthedocs.build/en/6449/users/quickstart/#__tabbed_9_2

docs: update magento1 and backdrop quickstarts, fixes #6448

---

docs/content/users/quickstart.md

- #5932
The documentation says https://ddev.readthedocs.io/en/stable/users/quickstart/#magento
> Note that you can install the Adobe/Magento composer credentials in your global `~/.ddev/homeadditions/.composer/auth.json` and never have to find them again.
But the current quickstart doesn't check composer's global configuration for this auth, resulting in a situation where you have to add these credentials each time for each project.
Stores magento2 credentials in the global config `~/.ddev/homeadditions/.composer/auth.json` (and respects `$XDG_CONFIG_HOME`)
This is one-time action. If you run it again, it will simply check if your credentials are correct.
Review at https://ddev--6442.org.readthedocs.build/en/6442/users/quickstart/#magento
Try it out.

docs: store magento2 credentials in the global config, for #5932, for #6380

---

.buildkite/testbot_maintenance.sh
docs/content/developers/buildkite-testmachine-setup.md

Homebrew's mysql-client 9.0 just came out and is broken, https://buildkite.com/ddev/ddev-macos-arm64-mutagen/builds/8398#01911f62-d2cd-499c-897c-5ca0fd7a38ef/2586-2656
> ERROR 2059 (HY000): Authentication plugin 'mysql_native_password' cannot be loaded: dlopen(/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so, 0x0002): tried: '/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so' (no such file), '/opt/homebrew/Cellar/mysql-client/9.0.1/lib/plugin/mysql_native_password.so' (no such file)
 
Use mysql-client@8.0 instead
If the tests run it should be OK. However, machines that have mysql-client@9.0 will be sad.

test: mysql-client 9.0 in homebrew is broken, use 8.0

---

cmd/ddev/cmd/aliases.go
cmd/ddev/cmd/commands.go
cmd/ddev/cmd/commands_test.go
docs/content/users/extend/custom-commands.md
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/web/artisan

- #6443
Adds aliases for custom commands.
Adds `ddev art` alias for `ddev artisan`, this is the most used alias for Laravel.
Adds `ddev aliases` command:
```
$ ddev aliases
┌────────────────┬──────────────────┐
│ COMMAND        │ ALIASES          │
├────────────────┼──────────────────┤
│ artisan        │ art              │
├────────────────┼──────────────────┤
│ debug          │ d, dbg           │
├────────────────┼──────────────────┤
│ describe       │ status, st, desc │
├────────────────┼──────────────────┤
│ exec           │ .                │
├────────────────┼──────────────────┤
│ list           │ l, ls            │
├────────────────┼──────────────────┤
│ mutagen status │ mutagen st       │
├────────────────┼──────────────────┤
│ poweroff       │ powerdown        │ …
```

feat: add aliases for custom commands, `art` alias for `artisan`, `ddev aliases` command, fixes #6443

---

.buildkite/test.sh
containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/log-stderr.sh
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/n-install.sh
pkg/ddevapp/ddevapp.go
pkg/versionconstants/versionconstants.go

- #6451
- #6420
- Adds a new bash command `log-stderr.sh` that stores `stderr` output. (I've only used it for `n install` so far, I will add it to other commands later, after some testing and probably after the next DDEV release.)
- Adds `export DDEV_SKIP_NODEJS_TEST=true` for Buildkite tests.
- Changes `n` installation technique according to upstream recommendations.
- Optimizes error output for `n install` (removes `--offline` logging).
Look at the newer error output for:
```
$ ddev config --nodejs-version auto # when you don't have .nvmrc file or another file
...
Warning: Command 'n install auto' run as 'stas' failed with exit code 2:
Error: no file found for auto version (.n-node-version, .node-version, .nvmrc, or package.json)
$ ddev config --nodejs-version foobar # invalid version …
```

feat: add `log-stderr.sh` command, for #6451, for #6420

---

pkg/ddevapp/ddevapp.go
pkg/dockerutil/dockerutils.go
pkg/dockerutil/dockerutils_test.go

* In a complex project, there may be many containers we're waiting for. Show what we're waiting for when waiting for them
* Although we try hard with our error message, people seem not to read or understand it. Try to improve readability
* Show containers we're waiting for
* Improve error message
You can add a trivial failing extra service with `.ddev/docker-compose.longtimeout.yaml` with contents
```yaml
services:
longtimeout:
container_name: "ddev-${DDEV_SITENAME}-longtimeout"
image: debian:12
command: sleep infinity
labels:
com.ddev.site-name: ${DDEV_SITENAME}
com.ddev.approot: ${DDEV_APPROOT}
healthcheck:
start_period: "10s"
interval: "11s"
start_interval: "11s"
retries: 2
timeout: "15s"
test: "sleep 9 && false"
```
Or adjust as you like.
Nothing new.

fix: show containers we're waiting for and better error message on timeout/unhealthy

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time for v1.23.4 release.
Bumps:
- Images to v1.23.4
- `docker-compose` to v2.29.1
- Backdrop Drush Extension from 1.4.0 to [1.4.1](https://github.com/backdrop-contrib/backdrop-drush-extension/releases/tag/1.4.1) (maintenance release)

build: bump images to v1.23.4 and docker-compose to v2.29.1

---

mkdocs.yml

Tab anchors are unreadable.
For example, Drupal 11
Uses the latest available features from Tabbed https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
https://ddev--6464.org.readthedocs.build/en/6464/users/quickstart/#drupal-drupal-11

docs: add readable tab anchors

---

docs/content/users/topics/remote-docker.md

Links to Travis CI have been failing the docs tests today. But there's no actual reason to link there in the context. Just remove the links.

docs: Remove unnecessary and failing links to Travis CI

---

pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/testcommon/testcommon_test.go

Minor cleanup noted in 
* https://github.com/ddev/ddev/pull/6414
Try not to use literals for default ports "80" and "443". Instead used configured values
I don't think this will change anything, but it does make one test a bit better.

test: minor updates to avoid use of literals 80 and 443

---

cmd/ddev/cmd/debug-mutagen.go
cmd/ddev/cmd/debug-nfsmount.go
pkg/ddevapp/addons.go
pkg/ddevapp/apptypes_test.go
pkg/ddevapp/ddevapp.go
pkg/dockerutil/dockerutils.go
pkg/exec/exec.go
pkg/util/debug.go

- https://github.com/golang/go/issues/60529
```
golangci-lint: 
pkg/exec/exec.go:114:25: printf: non-constant format string in call to (*github.com/sirupsen/logrus.Logger).Printf (govet)
output.UserOut.Printf("RunHostCommand: " + command + " " + strings.Join(args, " "))
...
```
Pacifies golangci-lint.

ci: add new check from golangci-lint

---

pkg/ddevapp/drupal/drupal10/settings.ddev.php
pkg/ddevapp/drupal/drupal11/settings.ddev.php
pkg/ddevapp/drupal/drupal9/settings.ddev.php

Drupal #ddev slack https://drupal.slack.com/archives/C5TQRQZRR/p1723338555563719 points out that settings.ddev.php has
```
// Don't use Symfony's APCLoader. ddev includes APCu; Composer's APCu loader has
// better performance.
$settings['class_loader_auto_detect'] = FALSE;
```
but that comes from long ago. Apparently it's not needed in Drupal 9+, so can be removed. 
It was probably introduced in https://github.com/ddev/ddev/pull/1368 (https://github.com/ddev/ddev/pull/1368/commits/dd3b86188e13e14adce26c15ee35d82502fdcb81#diff-0196cec3f796f7d78f6e01b3d20405d825d0d874dd0aa9aff53930171d394217R161-R162) 
However, the need for it seems to have been removed in https://www.drupal.org/project/drupal/issues/3020296 (Drupal 9+)
* [Change record: Only Composer's classloader is …

fix: drupal class_loader_auto_detect no longer needed

---

docs/content/users/usage/offline.md

* https://github.com/moby/buildkit/issues/5214
After devs have been using `docker buildx` to push, they may have a builder with `docker-container` driver, preventing offline use
Mention this in offline docs.

docs: mention using docker builder for offline

---

docs/content/users/configuration/config.md
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/templates.go

- #6458
We can use the `$TZ` env and  the `/etc/localtime` symlink to get the timezone from the host.
`/etc/localtime` does not exist on traditional Windows, where users can set `$TZ` env.
Unset timezone if it is set:
```
ddev config --timezone=""
```
Run
```
DDEV_DEBUG=true ddev start
...
2024-08-07T12:41:13.739 Using automatically detected timezone: TZ=Europe/Kyiv
...
```
Check the timezone inside the container:
```
ddev exec 'echo $TZ'
ddev exec date
ddev php -r "var_dump(date_default_timezone_get());"
```
Retry `ddev start` after changing the time zone on the host to check for a different timezone.
Set `export TZ=Europe/Paris` and retry `ddev start`.

feat: automatic timezone detection from `$TZ` env or `/etc/localtime` symlink, fixes #6458

---

cmd/ddev/cmd/snapshot.go
cmd/ddev/cmd/snapshot_restore.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/snapshot.go

- #6116
`ddev snapshot --list` output is difficult to visually parse.
Output from `ddev snapshot --list` is now a table, which gives the name of the project, the name of the snapshot, and when the snapshot was created.
If no snapshots are available, the output is still in table format but clearly indicates there's no snapshots.
Make sure the various table formats display as expected (both `simple_formatting` and `table_style` in https://ddev.readthedocs.io/en/stable/users/configuration/config/#simple_formatting)
Make sure json output works as expected
Make sure it gives appropriate output with the various flags, and with a combination of projects with-and-without snapshots
There seem to be no existing tests for `ddev shapshot --list` and I haven't added any.
The json output of `ddev …

feat: output snapshot list as a table, fixes #6116

---

docs/content/users/configuration/config.md
docs/content/users/topics/hosting.md
docs/content/users/topics/index.md
docs/content/users/topics/remote-docker.md
docs/content/users/usage/commands.md
pkg/ddevapp/traefik.go
pkg/ddevapp/traefik_config_template.yaml

* #6486 
* Regular expressions were being used for hostnames in Host() statements for Let's Encrypt, but those are wrong
* We had `Host(hostname1, hostname2, hostname3)` when it should be `Host(hostname1) || Host(hostname2) || Host(hostname3)`
Previous incorrect formatting:
```
http:
routers:
d10-web-80-http:
entrypoints:
- http-80
rule: Host(`^d10\.traefik\.thefays\.us$`)
```
and 
```
routers:
d10-web-80-http:
entrypoints:
- http-80
rule: Host(`^d10\.traefik\.thefays\.us$`, `^one\.traefik\.thefays\.us$`, `^two\.traefik\.thefays\.us$`)
```
New formatting:
```
routers:
d10-web-80-http:
entrypoints:
- http-80
rule: Host(`d10.ddev.site`)
```
and
```
routers:
d10-web-80-http:
entrypoints:
- http-80
rule: Host(`d10.ddev.site`) || Host(`one.ddev.site`) || Host(`three.ddev.site`) || …
```

fix: Lets Encrypt traefik formatting was broken, fixes #6486

---

cmd/ddev/cmd/debug-test.go

After a support issue I was looking to make sure we bring up the "latest current version" thing.
This adds it to the front of `ddev debug test`, not sure that will help.
I'm going to leave this in draft for some time, if https://github.com/ddev/ddev/pull/6414 goes in there may be some adjusting to do here.

docs: ddev debug test should suggest current stable [skip ci]

---

docs/content/users/usage/offline.md

* #6499 
The docs on offline usage need to be stronger about `ddev start` on each project before going offline.
Review new page at https://ddev--6502.org.readthedocs.build/en/6502/users/usage/offline/

docs: clearer statement about `ddev start` before offline, for #6499

---

pkg/archive/archive_test.go
pkg/ddevapp/ddevapp_test.go
pkg/dockerutil/dockerutils_test.go
pkg/fileutil/files_test.go

* TestContainerWait was leaving dead containers behind. It turned out that the t.Cleanup() was re-using the last value of cID instead of the value at time of creation of the closure. This is a new problem to me.
* A number of tests were using os.MkdirTemp() where testcommon.CreateTmpDir() would be better. They had been noticed leaving things laying around on Windows, especially.
* TestArchiveTar and TestArchiveTarGz weren't deleting their tarballs.

test: Improve several tests, make sure containers get removed

---

pkg/ddevapp/router.go

* https://github.com/ddev/ddev/pull/6414
In there, trying to solve the problems with failed URLs on Lima/Colima/Rancher I inserted a wait for ports to be freed. But the logic there was wrong, and no ports were waited for. It was just wrong.
Get the ports that we need to wait for from the ddev-router itself by inspecting it.
Block ports 80 and 443, `nc -k -l 80` and `nc -k -l 443` to make it start new items all the time.
With DDEV_DEBUG=true you should see notification of all the related ports being checked.

fix: Make sure that we actually wait for bound ports to be released

---

cmd/ddev/cmd/ssh_test.go
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/router_test.go

* There were some tests that were creating URLs without respecting the actual URLs in use.  TestPHPConfig, TestPHPOverride. They were doing things like this with app.GetHostname(), etc:
`	_, _ = testcommon.EnsureLocalHTTPContent(t, "http://"+app.GetHostname()+"/phpinfo.php", `max_input_time</td><td class="v">999`, 60)`
* Those tests sometimes may fail on Rancher Desktop as they do on Colima/Lima, so stop testing there.
* TestHTTPSRedirection couldn't work properly with non-default ports. Adjusted it.

test: Rancher Desktop and other problems when non-default ports used

---

cmd/ddev/cmd/commands.go
pkg/ddevapp/addons.go
pkg/ddevapp/envfile_test.go
pkg/ddevapp/provider.go
pkg/fileutil/files.go
pkg/fileutil/files_test.go
pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/one.txt
pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/subdir/subdir-three.txt
pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/subdir/subdir2/subdir-four.txt
pkg/fileutil/testdata/TestListFilesInDirNoSubdirsFullPath/two.txt

Twice people have reported having trouble with `ddev pull pantheon --skip-files` where it tried to import files for some reason, or tried to import things that weren't there. 
* https://discord.com/channels/664580571770388500/1274137556858175642
* https://discord.com/channels/664580571770388500/1232668554550186024
We delete the .downloads directory before downloading, but we don't do a mutagen sync, so this all may happen too fast, and sync may be incomplete, leading to files being in the .downloads/files directory, messing up the import. 
This does a sync before recreating the .downloads directory
In addition, we should never be trying to import directories during a database import process, so it's an error to try to traverse directories as was shown in the Discord OP.
In …

fix: flush mutagen after deletion of .downloads directory

---

docs/content/users/extend/additional-services.md

- https://github.com/ddev/ddev/actions/runs/10590846300/job/29347254162#step:11:178
```
FILE: docs/content/users/extend/additional-services.md
[✖] https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml
32 links checked.
ERROR: 1 dead links found!
[✖] https://github.com/ddev/ddev/blob/master/cmd/ddev/cmd/testdata/TestCmdGetComplex/recipe/install.yaml → Status: 404
```
The test file was moved in:
- #6482
Updates the link.

docs: fix link for advanced add-ons, for #6482

---

pkg/ddevapp/extra_expose_test.go
pkg/ddevapp/hooks_test.go
pkg/ddevapp/router.go
pkg/netutil/netutil.go

In https://buildkite.com/ddev/macos-rancher-desktop/builds/957#01918e49-185d-4044-bcf0-8db01bb419df/10062-10136 I see that there is still some erroneous logic in tests when the primary URL may have a port.
> failed to get hit url https://testpkgdrupal10.ddev.site:33003:3000/testfile.html, out=, resp=<nil> err=Get "https://127.0.0.1:3000/testfile.html": dial tcp 127.0.0.1:3000: connect: connection refused
Note `https://testpkgdrupal10.ddev.site:33003:3000/testfile.html`
Add BaseURLFromFullURL() to get the base URL from any URL, without the port.

test: fix  TestExtraPortExpose with correct URL

---

.gitpod/images/Dockerfile
containers/ddev-dbserver/Dockerfile
containers/ddev-nginx-proxy-router/Dockerfile
containers/ddev-php-base/Dockerfile
containers/ddev-traefik-router/Dockerfile
containers/ddev-webserver/Dockerfile
containers/test-ssh-server/Dockerfile

- #6462
- https://docs.docker.com/reference/build-checks/from-as-casing/
```
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 6)
```
* uses the same casting for `FROM ... AS ...`
* removes extra lines at the end of files
* uses an indent of 4 spaces

build: fix FromAsCasing warning from Dockerfile, for #6462 [skip ci]

---

.buildkite/test.sh

The current buildkite test.sh tries to leave the docker context in a "sane" place by setting the context to "default"
However, something always deletes the `docker.sock` link on macstadium-m1. (/var/run/docker.sock). This can be fixed with `cd /var/run && sudo ln -s /Users/testbot/.docker/run/docker.sock` but it probably makes more sense to use the native context.
On exit of test.sh, if orb not installed, use `docker context use desktop-linux`

test: leave docker desktop context as desktop-linux [skip ci]

---

cmd/ddev/cmd/addon-get.go
cmd/ddev/cmd/addon-list.go
cmd/ddev/cmd/addon-remove.go
cmd/ddev/cmd/addon_test.go
cmd/ddev/cmd/get.go
docs/content/users/usage/commands.md

- #6513
There's currently no way to remove add-ons for a given project (other than the current working dir), and the use of the second argument in `ddev add-on get` for a project name blocks the opportunity to install multiple add-ons at once in the future.
1. Remove the second argument from `ddev add-on get` which is currently for a project name.
1. Add a `--project` flag to `ddev add-on get`, `ddev add-on remove`, and `ddev add-on list --installed`
1. In `ddev get`, make sure the second (and subsequent) argument is converted to a flag before proxying to the `add-on get` command.
Note that adding the flag to `ddev add-on list` wasn't originally mentioned in the issue, but I noticed while testing that it didn't make sense to _not_ have it.
I've added validation so that if the `--project` …

feat: add `--project` flag to `ddev add-on` commands, fixes #6513

---

containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/etc/ImageMagick-6/policy.xml
pkg/versionconstants/versionconstants.go

- #6518
SVG files are commonly used nowadays, yet the ImageMagick used in DDEV does not support converting SVG files.
Installs the package providing SVG conversion and configures ImageMagick to use it.
```
ddev php -r "echo (new Imagick())->queryFormats('SVG') ? 'SVG supported' : 'SVG not supported';"
```

feat: add SVG support for ImageMagick

---

.ci-scripts/linux_arm64_setup.sh
.github/workflows/linux-setup.sh
containers/check_key_expirations.sh
containers/ddev-dbserver/test/functions.sh
containers/ddev-dbserver/test/image_general.bats
containers/ddev-dbserver/test/test_dbserver.sh
containers/ddev-ssh-agent/Dockerfile
containers/ddev-ssh-agent/test/functions.sh
containers/ddev-ssh-agent/test/image_general.bats
containers/ddev-ssh-agent/test/test.sh
containers/ddev-webserver/tests/ddev-webserver/general.bats
containers/ddev-webserver/tests/ddev-webserver/test.sh
containers/testscripts/check_key_expirations.sh

* #5829 
Add a script that uses `gpg` to check expiration dates of both .gpg and .asc files
* Review the test output for the tests (Test Container) to see the keys and their expiration and/or
* In a supported project like ddev-dbserver, ddev-ssh-agent, ddev-webserver
To show success, with evaluation of all the keys:
```
export DDEV_MAX_DAYS_BEFORE_CERT_EXPIRATION=200
make test
```
To show a failure
```
export DDEV_MAX_DAYS_BEFORE_CERT_EXPIRATION=1000
make test
```
I didn't do `ddev-traefik-router` because it's apk based instead of debian
I didn't do `ddev-php-base` because everything in it is in `ddev-webserver`
It's ironic that I'm doing this now, when we're more than 500 days from any expiration, when we had TWO accidental expirations in the last several months. 
Right now, it shows all …

test: apt key expiration management, fixes #5829 [skip buildkite]

---

pkg/ddevapp/providerLagoon_test.go
pkg/versionconstants/versionconstants.go

* TestLagoonPush started failing when the latest `lagoon` cli got implemented
* @rocketeerbkw responded very quickly with #6524 Thanks!
* Because that was a forked PR, TestLagoonPush didn't get run because the secrets were not available
* Build the new released lagoon client v0.30.1 into ddev-webserver
* Run @rocketeerbkw original change
If TestLagoonPush runs here and succeeds, we're good.

test: Fix TestLagoonPush by upgrading lagoon CLI, replaces #6524

---

docs/content/developers/maintainers.md
markdown-link-check.json

We can't receive scheduled workflow notifications as a team. Only the user who created or disabled/enabled or changed the cron syntax receives such notifications.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/notifications-for-workflow-runs
Explains how we use GitHub to be able to receive notifications as a team.
https://ddev--6527.org.readthedocs.build/en/6527/developers/maintainers/

docs: maintainer info about GitHub notifications

---

.github/workflows/tests.yml
cmd/ddev/cmd/auth-ssh.go
docs/content/developers/secret-management.md
markdown-link-check.json
mkdocs.yml
pkg/ddevapp/providerAcquia_test.go
pkg/ddevapp/providerLagoon_test.go
pkg/ddevapp/providerPantheon_test.go
scripts/read-1password-secrets.sh

We'd like to use 1Password to manage secrets
This is a first step, using 1Password for the testing secrets, like TestAcquiaPull, etc.
Review the test logs. 
These secrets live in the `test-secrets` vault
The `test-secrets` vault allows access to the service account [`tests`](https://team-ddev.1password.com/developer-tools/infrastructure-secrets/serviceaccount/76URGQSBMVEUHPEWVHQRFJ4N3Q) whose auth token is in "1Password Service Account Auth Token: Tests"
The technique is documented in https://developer.1password.com/docs/ci-cd/github-actions/

test: Use 1password for test secrets [skip buildkite]

---

.github/workflows/tests.yml

* https://github.com/ddev/ddev/pull/6536#issuecomment-2348824760
With the addition of 1Password secrets to the tests workflow, forked PRs started failing
Don't load secrets on forked PRs

test: Make forked PRs skip loading secrets

---

pkg/versionconstants/versionconstants.go

This reverts commit b2e3801a8fed23e2cd445165a2985ebceb7a3fe8.
Moving from docker-compose 2.29.1  -> 2.29.3 has fundamental breakage on WSL2 Docker Desktop, see https://buildkite.com/ddev/wsl2-docker-desktop/builds/5626#0191fbdd-7474-4c79-a1a6-d4ecfa0b6691/291-501 - 
> Error response from daemon: path /var/lib/buildkite-agent/tmp/ddevtest/TestGetLocalHTTPResponse2320491494/.ddev is mounted on / but it is not a shared mount.'
 
Revert to previous previous docker-compose, v2.29.1
In future when testing docker-compose new versions, test on ddev/ddev, not a forked PR, so that all the permutations get run
I did test docker-compose v2.29.4 and it didn't seem to solve this.
We'll probably want to file an issue with github.com/docker/compose

build: Revert "build: bump docker-compose to 2.29.3 (#6538)"

---

docs/content/users/configuration/config.md

Ngrok moved their config docs, breaking link check

docs: fix link to ngrok agent config

---

pkg/versionconstants/versionconstants.go

- https://github.com/docker/compose/issues/12129
New docker-compose release https://github.com/docker/compose/releases/tag/v2.29.5 seems to have a fix.
Try it out.

build: bump docker-compose to 2.29.5

---

.github/workflows/master-build.yml
.github/workflows/push-tagged-dbimage.yml
.github/workflows/push-tagged-image.yml
.github/workflows/tests.yml
.goreleaser.yml
Makefile
docs/content/developers/release-management.md

It's really difficult to manage our secrets in github actions secrets
Manage most secrets in our team 1password account, and let Github Actions pull from that.
Review build from here and where it was tried out for
* [release](https://github.com/ddev-test/ddev/actions/runs/10856961949)
* [commit](https://github.com/ddev-test/ddev/actions/runs/10856949449)
* [push tagged image](https://github.com/ddev-test/ddev/actions/runs/10853648361)
* [push tagged dbimage](https://github.com/ddev-test/ddev/actions/runs/10853653152)
Most of the drama and learning was on 
* https://github.com/ddev-test/ddev/pull/5
And followup commits that show here and in https://github.com/ddev-test/ddev/commits/master/

build: Use 1password secrets for most push secrets instead of github secrets

---

pkg/ddevapp/compose_yaml.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.networks.yaml

- #5706
- #6376
Allows users to make modifications to the `ddev_default` and `default` networks, but with some limitations, that were allowed before, such as:
- it is now forbidden to change `ddev_default` and `default` networks name.
- it is now forbidden to change the `external` setting for `ddev_default` and `default` networks.
Allows users to add new networks to the Docker services.
Adds `com.ddev.platform` labels to all internal networks.
To test this, use the examples from the related issues description or create a new `.ddev/docker-compose.networks.yaml`:
```yaml
networks:
dummy:
name: dummy_name
ddev_default:
name: this_name_and_external_false_should_be_ignored_by_ddev
external: false
default:
name: this_name_and_external_true_should_be_ignored_by_ddev
external: true
services: …
```

fix: allow overrides for Docker networks, fixes #5706, fixes #6376

---

.spellcheckwordlist.txt
docs/content/users/usage/developer-tools.md

Add n98-magerun and n98-magerun2 to list of pre-installed tools in web container.
Only a small doc addition.

docs: add Magento tools to docs

---

cmd/ddev/cmd/scripts/test_ddev.sh

A user has customizations in .ddev/nginx/custom.conf that broke the site, but it didn't show up in `ddev debug test`
Make it show up
Do `ddev debug test` with and without a .ddev/nginx/custom.conf file

fix: ddev debug test - show customizations in .ddev/nginx if they exist [skip ci]

---

pkg/ddevapp/typo3.go

TYPO3 v12 changed the naming of the configuration files and also the place depending on the installation mode, which differs between composer and non-composer setups.
Since #4268 ddev already uses the correct files and places for composer based installations but not for non-composer mode setups, which includes also TYPO3 Core Development monorepo setups.
TYPO3 is going to remove the silent upgrade and also not writing the invalid `trustedHostsPattern` required for ddev. That means, that without the correct
pattern ddev setup for non-composer modes AND monorepo needs manual adjustmenst
and copy of the written file mainly because the default of typo3 no longer matches
the ddev variant. That means, the installer needs to be executed with `http` instead of `https`.
pkg/ddevapp/typo3.go` …

feat: streamline TYPO3 non-composer mode configuration support

---

.buildkite/testbot_maintenance.sh
docs/content/developers/buildkite-testmachine-setup.md
docs/content/users/install/ddev-installation.md

Buildkite WSL2 testbot_maintenance.sh: We no longer need or use homebrew here
Remove the check and update

test: Remove brew setup for linux from buildkite testbot_maintenance.sh [skip ci]

---

docs/content/users/configuration/config.md

Spotted this code highlighting issue while reading https://ddev.readthedocs.io/en/stable/users/configuration/config/#php_version

docs: Typo fix, incorrect code section usage

---

.buildkite/testbot_maintenance.sh

In 
* https://github.com/ddev/ddev/pull/6558 
~~I added an apt update/apt upgrade for Linux machines (WSL2) that actually hung, apparently waiting for user input.~~
~~Fix this with DEBIAN_FRONTEND=noninteractive and use `apt-get upgrade`~~
However, I tried that, and the buildkite-agent upgrade still hung and needed manual intervention (`sudo dpkg --configure -a`) so not trying that here any more. They'll get manually updated.

test: buildkite testbot_maintenance.sh apt upgrade hung on linux, remove it

---

pkg/ddevapp/app_compose_template.yaml

Drush launcher (deprecated a long time ago) used to care about this env variable. I dont know why we would have set this to 1 but we did. This env variable is now being repurposed by Drush itself at https://github.com/drush-ops/drush/pull/6119/files. So lets not manage the variable in DDEV anymore.

feat: Don't force Drush's Xdebug environment variable to 1

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

Some people use git inside the container, and I note that git autocompletion doesn't work there.
Because bash completion is not installed, it's likely that plenty of other autocompletes don't work
Add bash-completion.
Check out something inside the container and use git completion, especially of branches. For example, clone https://github.com/ddev/ddev and `git checkout 202409` and hit tab to get suggested branches.
This seems to add less than 1 MB to the image size, see https://hub.docker.com/r/ddev/ddev-webserver/tags

build: add bash-completion to standard packages

---

containers/ddev-dbserver/Dockerfile
pkg/ddevapp/config.go

When running `ddev debug refresh`:
```
WARN: InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 6)
```
https://docs.docker.com/reference/build-checks/invalid-default-arg-in-from/
Adds defaults, that will never be used, because we always pass the `ARG BASE_IMAGE`.
This PR goal is to silence this warning.
Run `ddev debug refresh`

build: fix Docker's InvalidDefaultArgInFrom warning

---

containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/dockerutil/dockerutils.go
pkg/versionconstants/versionconstants.go

- #6451
- #5073
Adds warnings for:
- mariadb-client
- mysql-client
- postgresql-client
- sqlite3 (Drupal 11)
- composer
Automatically runs `docker-compose build web --no-cache` on warnings if there is Internet available.
1. Disable internet.
2. Run `ddev debug refresh`, it should show warnings.
3. Enable internet.
4. Run `ddev restart`, it should rebuild web container without cache.
If you run `ddev start` instead, it will show a warning, which will disappear on one more start or restart:
```
Unable to delete sha256:a9ee9b4b2665f78697259e5b6a703ac6d24afb1dd8452c6b8d02ae48167fc0c5: Error response from daemon: conflict: unable to delete a9ee9b4b2665 (cannot be forced) - image is being used by running container cda3b436ea7d
```
5. Run `ddev restart` again, it should not trigger rebuild …

feat: show warnings from stderr, auto rebuild for web image w/o cache on warnings, fixes #6451, for #5073

---

cmd/ddev/cmd/debug-rebuild.go
cmd/ddev/cmd/debug-rebuild_test.go
cmd/ddev/cmd/debug-refresh.go
cmd/ddev/cmd/debug-refresh_test.go
cmd/ddev/cmd/scripts/test_ddev.sh
docs/content/users/extend/customizing-images.md
docs/content/users/usage/commands.md
docs/content/users/usage/troubleshooting.md
pkg/ddevapp/templates.go

`ddev debug refresh` is not flexible enough. It runs rebuild without cache only for the web service.
- adds `--service=name` and `--all` flag to build specified service.
- adds `--cache` flag that will not add `--no-cache` to the underlying `docker-compose build` command.
- adds `--progress plain` to `docker-compose build`, because it was squashed by default.
```
ddev debug refresh # this command is the same as it was before
ddev debug refresh --cache # should show cached output
ddev debug refresh --all # should rebuild all services (if you have web, db, redis: all of them should be rebuilt)
ddev debug refresh --service db # the same as usual command, but for the db service
```

feat: rename refresh to rebuild in `ddev debug refresh`, allow to build different services, add cache flag

---

pkg/ddevapp/ddevapp.go
pkg/dockerutil/dockerutils.go

- #6493
- #6422
Removes `web` and `db`, and hides the second waiting message if there are no additional containers.
```
ddev start
```
```
...
Waiting for containers to become ready: [web db] 
Starting ddev-router if necessary... 
Container ddev-router  Created 
Container ddev-router  Started
Waiting for additional project containers to become ready... 
All project containers are now ready.
...
```
```
ddev add-on get ddev/ddev-redis
ddev restart
```
```
...
Waiting for containers to become ready: [web db] 
Starting ddev-router if necessary... 
Container ddev-router  Created 
Container ddev-router  Started 
Waiting for additional project containers to become ready... 
Waiting 120s for additional project containers [ddev-d11-redis] to become ready... 
All project …
```

refactor: exclude web and db from waiting for containers, fixes #6493, for #6422

---

cmd/ddev/cmd/composer-create_test.go

* #6586 
Composer 2.8.1 introduces new probably unwanted behavior that breaks TestComposerCreateCmd
Upstream issue: 
* https://github.com/composer/composer/issues/12150
* Temporarily use composer 2.8.0 for that test.
* Use `require` instead of `assert` so we don't run along and use invalid data and get a panic
* Minor fiddles with test flow
Read the test output.
A comment about TestComposerCreateCmd: This is so impressive how much test coverage you built into this @stasadev, so great. In retrospect, I imagine all the if statements would be cleaner as a switch statement, or perhaps they could be a test matrix.

test: Use composer 2.8.0 for TestComposerCreateCmd until composer bug is fixed, for #6586

---

cmd/ddev/cmd/addon-get_test.go

I enabled `TestCmdAddonComplex` for all environments in:
- #6406
But it failed on Windows:
https://buildkite.com/ddev/ddev-windows-mutagen/builds/4820#01925524-771f-481c-a816-a38cd172e632/14772-14793
```
=== RUN   TestCmdAddonComplex
addon-get_test.go:77:
Error Trace:	C:/Users/testbot/tmp/buildkite/tb-win11-06-1/ddev/ddev-windows-mutagen/cmd/ddev/cmd/addon-get_test.go:77
Error:      	"\nExecuting pre-install actions:\nC:/Users/testbot/tmp/buildkite/tb-win11-06-1/ddev/ddev-windows-mutagen/.gotmp/bin/windows_amd64/ddev.exe\n\n\nInstalling project-level components:\n👍 junk_windows_amd64.txt\n👍 extra\\has-ddev-generated.txt\nNOT overwriting C:\\Users\\testbot\\tmp\\ddevtest\\TestCmdWordpress3774037344\\.ddev\\extra\\no-ddev-generated.txt. The #ddev-generated signature was not found in the …
```

test: fix Windows path in TestCmdAddonComplex

---

containers/ddev-webserver/Dockerfile

Errors weren't being adequately checked in the ddev-webserver Dockerfile.
Cherry-pick https://github.com/ddev/ddev/pull/6570/commits/bfdc677720e3cd458edcc28cfc0bf6ccd24e3460 from 
* https://github.com/ddev/ddev/pull/6570 
That PR may not land soon, and the error checking added is irrelevant to that PR.

build: ddev-webserver Dockerfile should check for bash errors

---

docs/content/users/usage/database-management.md

The database management page provides no details for removing the db container.
Adds a link the configuration.
I debated about putting a specific section about removing it. However, I felt this might lead to duplication. Linking the the option centralizes it as the single source of truth.

docs: Add link to "omit" DB configuration

---

docs/content/developers/buildkite-testmachine-setup.md

Always trying to catch up on buildkite setup. 
We no longer use homebrew on wsl2.

docs: wsl2 buildkite-agents no longer need homebrew

---

pkg/ddevapp/ddevapp.go
pkg/util/utils.go
pkg/util/utils_test.go

While attending today's contributor training on `ddev debug test`, I noticed a problem with timezone detection on Randy's MBP:
```
$ DDEV_DEBUG=true ddev start -y
...
2024-10-09T07:42:08.796 Unable to autodetect timezone: unable to read timezone from /usr/share/zoneinfo.default/America/Denver file
...
```
- #6468
After research, we found that `filepath.EvalSymlinks()` evaluates hidden symlinks on macOS:
```
$ ls -l /etc/localtime
lrwxr-xr-x  1 root  wheel  40 Oct  6 13:46 /etc/localtime -> /var/db/timezone/zoneinfo/America/Denver
```
```
$ ls -ltd /var/db/timezone/zoneinfo
lrwxr-xr-x  1 root  wheel  38 May 21 14:48 /var/db/timezone/zoneinfo -> /var/db/timezone/tz/2024a.1.0/zoneinfo
```
```
$ ls -ltd /var/db/timezone/zoneinfo
lrwxr-xr-x  1 root  wheel  27 Oct  6 13:45 …
```

fix: improve timezone detection, for #6468

---

pkg/ddevapp/schema.json

We don't have validation for database versions:
Adds validation:

feat: validation for database versions in `schema.json` [skip ci]

---

pkg/ddevapp/webserver_config_assets/nginx-site-backdrop.conf
pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal6.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal7.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal8.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf
pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
pkg/ddevapp/webserver_config_assets/nginx-site-magento.conf
pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf
pkg/ddevapp/webserver_config_assets/nginx-site-php.conf
pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
pkg/ddevapp/webserver_config_assets/nginx-site-wordpress.conf
pkg/ddevapp/webserver_config_assets/nginx_second_docroot_example-site-php.conf
pkg/versionconstants/versionconstants.go

- #6563
By default, nginx [does not pass the header field `X-Accel-...` from the response of a FastCGI server to a client](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_hide_header). It can be useful however during development for manual or automated testing of nginx-specific behavior. For example [Drupal's BigPipe test checks the value of the 'X-Accel-Buffering' header](https://git.drupalcode.org/project/drupal/-/blob/79a4904009909e83b94b6cbbfcc55600def67233/core/modules/big_pipe/tests/src/Functional/BigPipeTest.php#L346).
It uses `fastcgi_pass_header` to forward the headers to the client.
Visit a page that sets one of the headers and verify you can see it in your client. [This gist tests all the headers except …

feat: pass X-Accel-* headers to client, fixes #6563

---

docs/content/users/debugging-profiling/blackfire-profiling.md
docs/content/users/extend/customization-extendibility.md
docs/content/users/install/ddev-installation.md
docs/content/users/providers/acquia.md
docs/content/users/providers/index.md
docs/content/users/providers/lagoon.md
docs/content/users/providers/pantheon.md
docs/content/users/providers/platform.md
docs/content/users/providers/upsun.md
docs/content/users/usage/cms-settings.md
pkg/ddevapp/dotddev_assets/providers/README.txt
pkg/ddevapp/dotddev_assets/providers/acquia.yaml
pkg/ddevapp/dotddev_assets/providers/lagoon.yaml
pkg/ddevapp/dotddev_assets/providers/pantheon.yaml.example
pkg/ddevapp/dotddev_assets/providers/platform.yaml
pkg/ddevapp/dotddev_assets/providers/upsun.yaml
pkg/ddevapp/templates.go
pkg/globalconfig/global_config.go

- https://github.com/ddev/ddev/issues/6599
the yaml example for setting up pantheon integration did not have the correct amount of spacing and this change corrects that
Updated the yaml syntax. While editing the yaml I also converted the markdown syntax for lists so it will be easier to maintain moving forward. Lastly, the letter sub bullets do not format as expected. I took the initiative to reformat as I felt like 1a and 1b should be there own numbered items.
https://ddev--6600.org.readthedocs.build/en/6600/

docs: update `web_environment` usage, fixes #6599

---

markdown-link-check.json

`archive.org` has been under DDOS attack, and links are failing.
We don't need to check that one link.

docs: remove markdown link check on archive.org

---

docs/content/users/usage/commands.md

After `ddev get` was renamed to `ddev add-on`, it was not moved in the docs.
And when I added `ddev dotenv`, I saw `ddev add-on` and simply added my commands right after it.
Sorts commands alphabetically.
Adds missing aliases from `ddev aliases` to the docs.
See https://ddev--6607.org.readthedocs.build/en/6607/users/usage/commands/

docs: sort commands alphabetically, add missing aliases

---

containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
pkg/ddevapp/composer.go
pkg/versionconstants/versionconstants.go

- #6602
We should really prefer the COMPOSER_ROOT/vendor/bin in our $PATH instead of having it later in the PATH.
If composer/composer is in vendor/bin, it should be used from there when possible
* Change the PATH setup that the image uses
* Change `ddev composer` to use `Cmd` instead of `RawCmd` so it gets interpreted by bash
What I did was `ddev composer require composer/composer:v2.8.0` and then used `ddev composer --version` and `ddev exec composer --version` for testing.
Right now, this is experimental, since this could possibly affect things we don't expect to affect: It can certainly change behavior when composer/composer is required, but it could also change something where something is in vendor/bin otherwise and thus masks something elsewhere in the container.
This also makes …

fix: use Cmd instead of RawCmd to execute composer and put vendor/bin first in PATH, fixes #6602

---

cmd/ddev/cmd/restart.go
cmd/ddev/cmd/restart_test.go
cmd/ddev/cmd/start.go
cmd/ddev/cmd/start_test.go

- #6500 
We don't want to output the 127.0.0.1 URL when the router is enabled.
Only shows the primary URL when the app is started/restarted
Run `ddev stop && ddev start` or `ddev restart`. Then you should see the updated output on the final line:
"Your project can be reached at mysite.ddev.site - see ddev describe for alternate URLs"
With the router omitted you should see the 127.0.0.1 URL.
Run: `ddev config global --omit-containers=ddev-router && ddev restart`
Updated TestCmdRestart and TestCmdStart

feat: Remove 127.0.0.1 from start and restart message, place in one function, fixes #6500

---

pkg/ddevapp/hostname_mgt.go
pkg/dockerutil/dockerutils.go
pkg/globalconfig/global_config.go
pkg/globalconfig/global_config_test.go
pkg/netutil/netutil.go

- #6592
Checks only for IPv4 in DNS lookup.
It should work when local DNS is configured to resolve IPv4 and IPv6 for the same host at the same time.
I tested it with custom TLD `*.test` (to be sure it doesn't collide with online `*.ddev.site`) and `dnsmasq`:
dnsmasq config:
for IPv4:
```
address=/*.test/127.0.0.1
```
for IPv6:
```
address=/*.test/::1
```
DDEV config:
```
ddev config --project-tld test
```
Cases:
1. Resolve IPv4 `*.test` added, resolve IPv6 `*.test` added - `ddev start` works
2. Resolve IPv4 `*.test` added, resolve IPv6 `*.test` not added - `ddev start` works
3. Resolve IPv4 `*.test` not added, resolve IPv6 `*.test` added - `ddev start` asks for sudo as expected
4. Resolve IPv4 `*.test` not added, resolve IPv6 `*.test` not added - `ddev start` asks for sudo as expected

fix: check only for IPv4 in DNS lookup, fixes #6592

---

docs/content/users/quickstart.md

TYPO3 is reorganizing their docs and changing rendering styles.
I haven't been able to figure out where the link ended up that is failing, so removing it.

docs: Remove non-working DDEV doc reference in TYPO3 docs

---

docs/content/users/usage/troubleshooting.md
pkg/ddevapp/router.go

We're about to release a version of DDEV that automatically uses an available port instead of just complaining.
* Improve the message so it shows a link to the solution
* Upgrade the port conflict doc in general. 
```
rfay@rfay-mbp-2021:~/workspace/ddev$ ddev start d11
Network ddev_default created
Starting d11...
Port 80 is busy, using 33000 instead, see https://ddev.com/s/port-conflict
Port 443 is busy, using 33001 instead, see https://ddev.com/s/port-conflict
Port 8025 is busy, using 33002 instead, see https://ddev.com/s/port-conflict
Port 8026 is busy, using 33003 instead, see https://ddev.com/s/port-conflict
Container ddev-ssh-agent  Created
Container ddev-ssh-agent  Started
ssh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth …
```

docs: Improve port conflict documentation and provide a link to the issue

---

docs/content/users/configuration/config.md
docs/content/users/usage/commands.md
docs/content/users/usage/developer-tools.md

Docs on composer:
* https://github.com/ddev/ddev/pull/6604
* https://github.com/ddev/ddev/issues/6602
In those issues, we put vendor/bin first. If people require `composer/composer`, then the version they require will take precedence. 
Review rendered docs  by searching composer/composer:
* https://ddev--6611.org.readthedocs.build/en/6611/users/usage/developer-tools/#ddev-and-composer
* https://ddev--6611.org.readthedocs.build/en/6611/users/usage/commands/#config
* https://ddev--6611.org.readthedocs.build/en/6611/users/configuration/config/#composer_version

docs: show results of including composer/composer

---

pkg/ddevapp/router.go
pkg/netutil/netutil.go

I've been using Colima as Docker Provider for the last few days, and I kept seeing these unexpected warnings:
```
Unable to properly check port status: dial tcp 127.0.0.1:0: connect: can't assign requested address
```
It turns out that we were trying to wait for release of ports that weren't bound, and the reason was that GetRouterBoundPorts() was walking through the router's ports, and some of those were not actually bound. Port 80 in this case was active inside but not bound.  So on Lima/Colima/Rancher, when it waits for ports to be unbound, this was shown.
If port PublicPort is 0 (not externally bound) then don't include it in GetRouterBoundPorts()
Using Colima or Lima:
Force it to use alternate ports (so 80 doesn't get bound):
```
echo 80 443 8025 8026 | xargs -n 1 -P 4 -I{} nc -k -l …
```

fix: don't try to release not-bound ports

---

cmd/ddev/cmd/addon-get_test.go
cmd/ddev/cmd/dotenv-get.go
cmd/ddev/cmd/dotenv-set.go
cmd/ddev/cmd/dotenv_test.go
cmd/ddev/cmd/utils.go
pkg/appimport/appimport.go

- #6406
Users should be aware that they have passed invalid flags to the `ddev dotenv`, as it may be unclear why some flags are simply ignored.
Adds flag validation.
Fixes a small fail in the test, that was caused by random behavior from `util.RandString(4)`:
https://github.com/ddev/ddev/actions/runs/11346006773/job/31554123302?pr=6615#step:16:83
```
=== RUN   TestValidateAsset
appimport_test.go:38: 
Error Trace:	/home/runner/work/ddev/ddev/pkg/appimport/appimport_test.go:38
Error:      	Should be false
Test:       	TestValidateAsset
--- FAIL: TestValidateAsset (0.00s)
```
Before:
```
$ ddev dotenv set .env --test=123 -1asd=asd
Updated /home/stas/code/ddev/d11/.env with:
TEST="123"
$ ddev dotenv get .env --1asd
// shows help for the command without any error
```
After:
```
$ ddev dotenv …
```

feat: add validation for `ddev dotenv` flags, for #6406

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #6606
It's time for a new release.
- Updates Docker images to v1.23.5
- Updates docker-compose to v2.29.7

build: bump images to v1.23.5 and docker-compose to v2.29.7, fixes #6606

---

docs/content/users/providers/upsun.md
pkg/ddevapp/dotddev_assets/providers/upsun.yaml
pkg/ddevapp/providerUpsun_test.go

I was using the `upsun` CLI and noted that it doesn't respect UPSUN_PROJECT and UPSUN_ENVIRONMENT
Move to the PLATFORM_ environment variables.
`ddev pull upsun` and `ddev push upsun`
Everything should stay the same.

fix: Some UPSUN environment variables are now PLATFORM_ environment variables

---

containers/containers_shared.mk
containers/ddev-dbserver/build_image.sh
containers/ddev-gitpod-base/Dockerfile
containers/ddev-gitpod-base/Makefile
containers/ddev-nginx-proxy-router/Dockerfile
containers/ddev-nginx-proxy-router/Makefile
containers/ddev-php-base/Makefile
containers/ddev-ssh-agent/Dockerfile
containers/ddev-ssh-agent/Makefile
containers/ddev-traefik-router/Dockerfile
containers/ddev-traefik-router/Makefile
containers/ddev-webserver/Makefile
containers/test-ssh-server/Dockerfile
containers/test-ssh-server/Makefile

When we were reviewing the results of 
* https://github.com/ddev/ddev/pull/6613
today, Stas pointed out that
* `latest` didn't have the correct matching hash
* `ddev-dbserver` didn't get `latest` tag at all
I couldn't help but work on it a bit, so here it is.
This should not go into DDEV v1.23.5, and testing was done against ddevhq org
Use the web UI to push images.

build: make latest tag same hash, push latest for most

---

docs/content/users/usage/uninstall.md

I was trying to wipe the database and didn't know that volumes were being used. This is an attempt to surface that information for whoever comes across this next.

docs: add docker volumes to ddev uninstall docs

---

docs/content/users/usage/commands.md

- N/A
The `ddev add-on list` docs have a copy-paste error where the docs from `ddev add-on remove` were copied and not updated.
Updates the documentation to reference list, instead of remove.
Just read it and make sure it's sensible
N/A - docs only
N/A - docs only

docs: Fix copy-paste error in add-on list docs

---

pkg/testcommon/testcommon_test.go
pkg/versionconstants/versionconstants.go

Mutagen 0.18.0 has been released, and  @xenoscopic says it may benefit us and shouldn't hurt us. This should be a good point in release cycle to try it out.
Bump mutagen version.
Use it! Watch `ddev mutagen st -l`

build: try new mutagen 0.18.0

---

pkg/ddevapp/drupal.go

I noticed in testing another issue that a `drupal7` project (and probably `drupal6` could randomly be detected as a `drupal` project, due to two errors in logic:
1. Assumption that map would be traversed in stable order (it isn't in go)
2. IsDrupalApp() assumed that any "drupal" project was of type "drupal", not just drupal8+
IsDrupalApp() now checks to see if it's drupal8+
It's a little hard to test, but `ddev config --database=postgres:16` in a drupal7 project is how I discovered it. It complained that the project was of type drupal but was configured as drupal7.
I had to add `util.Debug()` statements to see the various attempts to discover project type. Debugging through it didn't help, as that provided a stable traversal of the map.

fix: make drupal detection only detect drupal8+

---

pkg/ddevapp/drupal.go
pkg/ddevapp/mutagen.go

* https://github.com/ddev/ddev/issues/6491#issuecomment-2336466328
The overall problem is an obscure interaction of Drupal install and mutagen:
* Drupal install (especially before drupal 8) setting sites/default/settings.php to read-only
* Edit settings.php on the host (which hasn't been synced)
* Mutagen can't then sync settings.php, so nothing happens inside the container, which is where it matters
```
ddev start
ddev drush si -y
ddev exec ls -l sites/default # See settings.php is read-only now
ddev mutagen st # will report the transitionProblem
ddev mutagen st -l # Will show failure as in issue
ddev restart
ddev exec ls -l sites/default # See settings.php is now writeable
ddev mutagen st -l. # will now be happy
```
I don't think anything needs to be added.

fix: help mutagen work with Drupal's read-only settings files, fixes #6491

---

cmd/ddev/cmd/composer.go
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/web/drush

- #6642
This adds command aliases for `ddev composer` and `ddev drush`: `ddev co` and `ddev dr` respectively.
I only had a few minutes to throw this together. Did I do it right?
I assume no tests are needed for a simple, non-functional change like this.

refactor: add `drush` and `composer` command aliases, fixes #6642

---

cmd/ddev/cmd/delete.go

From Drupal Slack https://drupal.slack.com/archives/C5TQRQZRR/p1729847516981059
Hi after updating ddev to the latest version i discovered that `ddev delete --all` command could probably be secured a bit (not talking of security).
If you try to run `ddev delete` with a name that doesn't exist, it will ask to delete the first project in your project list (i guess that if i type yes then it will cycle through the whole list.
I saw it by misspelling images in `ddev delete image --all` command.
See :
```
❯ ddev delete immages --all
OK to delete this project and its database?
myproject in /Volumes/Server/myproject/public_html
The code and its .ddev directory will not be touched.
A database snapshot will be made before the database is deleted.
OK to delete myproject? [Y/n] (yes): ^C
```
IMHO it …

fix: validate `--all` flag with args in `ddev delete`, for #6209

---

pkg/ddevapp/backdrop.go

- #6573
The text that appears after a Backdrop database import includes a link to Backdrop documentation that has since moved.
This PR replaces the old link with the new one.
* Create a ddev backdrop instance
* Import a databse
* Click the link in the returned text
Fixes 
* https://github.com/ddev/ddev/issues/6573

docs: update link to Backdrop documentation, fixes #6573

---

.github/workflows/colima-tests.yml
.github/workflows/tests.yml

Over in 
* https://github.com/ddev/ddev/pull/6645
we're struggling because the `ddev --version` is a hash instead of a proper version number
It turns out that tests.yml doesn't check out the repo with depth like almost every other github action.

test: tests.yml needs to check out full depth [skip ci]

---

cmd/ddev/cmd/cd.go
cmd/ddev/cmd/cd_test.go
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh

- #6639
Adds the `ddev cd` command.
I tested it with bash, zsh, fish on Linux.
```
ddev cd my-project
```

feat: add `ddev cd` command, fixes #6639

---

.github/workflows/tests.yml
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp_test.go
pkg/util/utils.go
pkg/util/utils_test.go

In studying the test run and coverage for 
* https://github.com/ddev/ddev/pull/6691
I was a little suspicious that not all PHP versions had been tested. 
Sure enough, we have a number of costly tests that only run the full set of possibilities when GOTEST_SHORT is empty.
So the only test that would have tried all my PHP versions was TestPHPConfig, and it was short-circuited in all our tests.
We only run the most costly tests without short circuits in GitHub tests.yml `pull-push-test-platforms`, so the tests that are like this have to be explicitly mentioned there. 
Then I discovered that the logic in some tests (most importantly TestPHPConfig) was incorrect, so when GOTEST_SHORT="" it wasn't running *any* of the PHP versions.
* Look for tests of this behavior
* Add them to the list
* …

test: run full tests that are sometimes short-circuited

---

.buildkite/macos-colima.yml
.buildkite/macos-colima_vz.yml
.buildkite/macos-lima.yml

Since Lima v1.0.0 dropped this morning, we haven't been able to succeed with any automated tests of Lima or Colima. We always get a hang, as shown here:
https://buildkite.com/ddev/macos-lima/builds/1819#0193036a-edb3-4cf3-9b38-8abf2d84d027
https://lima-vm.io/docs/config/port/ explains that there's a major change in port binding in v1, but that we can go back with `LIMA_SSH_PORT_FORWARDER=true limactl start`
We also have seen very serious problems with port binding, discussed in https://discord.com/channels/664580571770388500/1303763382343700634 and https://cloud-native.slack.com/archives/C043N6ZFV9S/p1730925198340189
For lima and colima buildkite builds, set the env var LIMA_SSH_PORT_FORWARDER to "true"

test: Try to get lima and colima sane with LIMA_SSH_PORT_FORWARDER

---

docs/content/users/configuration/config.md

I noticed that even if a `.nvmrc` file specifies the version of nodejs that ddev already has, that it is redownloaded and installed. I think this makes sense (so all specified versions are installed consistently), but it surprised me to see on my local that this added ~5 seconds of startup time for new projects. Surprisingly, this even happened given the global cache, so perhaps there's a bug lurking as well.
On a basic php project with no code, default settings for me give a startup time of ~14.5 seconds:
```
$ hyperfine --prepare 'ddev delete -Oy || true' 'ddev start'
Benchmark 1: ddev start
Time (mean ± σ):     14.525 s ±  0.122 s    [User: 0.561 s, System: 0.289 s]
Range (min … max):   14.358 s … 14.730 s    10 runs
```
But once a nodejs_version is set, it goes up:
```
$ hyperfine …
```

docs: note that setting a nodejs version always downloads something

---

docs/content/users/quickstart.md

From Discord https://discord.com/channels/664580571770388500/1303992169429860362
When you have a different router port, media is not loaded:
```yaml
router_https_port: "8443"
```
That's because Kirby needs an additional config for nginx https://getkirby.com/docs/cookbook/development-deployment/nginx
```
server {
...
location ~ \.php$ {
...
fastcgi_param SERVER_PORT 8443;
}
}
```
Uses Apache 2 instead, where it works out of the box.
Setup a new Kirby CMS project https://ddev.readthedocs.io/en/stable/users/quickstart/#kirby-cms
And run the below:
Before:
```
ddev config --router-http-port 8080 --router-https-port 8443
ddev restart
```
After:
```
ddev config --webserver-type=apache-fpm
ddev restart
```

docs: use apache-fpm for Kirby CMS

---

pkg/ddevapp/wordpress/wp-config-ddev.php

`wp_get_environment_type()` returns `production` (which is expected as nothing is telling WordPress otherwise). This PR sets DDEV projects to identify themselves as a `local` environment.
This PR defines your DDEV local site as a local environment using the `WP_ENVIRONMENT_TYPE` constant in the `wp-config-ddev.php` file. 
As outlined here: 
https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/
Execute `wp_get_environment_type()` anywhere and it should return `local`. 
N/A
This would only affect WordPress projects using `wp_get_environment_type()` and expecting their local site to be one of the other values `development | staging | production`

feat: add WordPress WP_ENVIRONMENT_TYPE support to wp-config-ddev.php

---

CONTRIBUTING.md
docs/content/developers/building-contributing.md

I can never find the PR docs because they're hiding in a page that says it's about setting up a local build and running tests, and in that page the information about PRs is split over different parts.
- makes the link say the page is also about making PRs.
- consolidates and reorganises the bits about making PRs

docs: rearrange documentation on making PRs

---

containers/ddev-php-base/Dockerfile
containers/ddev-php-base/generic-files/usr/local/bin/install_php_extensions.sh
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
containers/ddev-webserver/tests/ddev-webserver/test.sh
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/nodeps/php_values.go
pkg/versionconstants/versionconstants.go

- #5984 
Every new PHP version has been adding heft to the default ddev-webserver. We'd like it to be smaller, for faster download and extraction times. And we'd like it not to grow with every new year's PHP version.
* Only preinstall versions of PHP that are currently supported
* When earlier versions are required (like PHP 7.4) install them as needed during first-time project startup.
* This PR brings the ddev-webserver image size down significantly. In v1.23.5, we had 480MB compressed. After removing most locales, we had 425MB compressed, and now with this one we have 377MB compressed.
I think that all the normal test coverage remains the same. It will mean that when we test all PHP versions that the tests will be a bit slower.
We need to boast about how much smaller the image is :)

build: Remove unsupported PHP versions by default, fixes #5984

---

pkg/ddevapp/snapshot.go
pkg/ddevapp/snapshot_test.go

- #6694
Only matching a snapshot file by prefix can accidentally select a different snapshot that is lexicographically earlier.
Now a fully anchored regular expression is used to match the full filename. The regular expression is based on the one in `ListSnapshots`.
Create the snapshots `foo` and `foo-bar`. Attempt to delete the snapshot `foo`. List snapshots to see which actually got deleted.
Such a small change didn't seem like it needed its own test. If a test is desired anyway, `TestDdevSnapshotCleanup` can probably be extended to cover this case as well.
Should not have any effects or require any action.

fix: match snapshot using full filename, fixes #6694

---

pkg/ddevapp/provider.go
pkg/globalconfig/global_config_test.go

golangci-lint 1.62.0 added more checks:
```
golangci-lint: 
pkg/globalconfig/global_config_test.go:40:2: redefines-builtin-id: redefinition of the built-in function max (revive)
max := i + 100
^
pkg/ddevapp/provider.go:304:61: redefines-builtin-id: redefinition of the built-in type error (revive)
func (p *Provider) doFilesPullCommand() (filename []string, error error) {
^
pkg/ddevapp/provider.go:327:61: redefines-builtin-id: redefinition of the built-in type error (revive)
func (p *Provider) getDatabaseBackups() (filename []string, error error) {
^
make: *** [Makefile:290: golangci-lint] Error 1
```
Fixes it.

build: fix static errors from golangci-lint

---

pkg/ddevapp/ddevapp_test.go

TestGetAllURLs has been failing consistently with 5 URLs instead of 10 on tb-wsldd-16.  https://buildkite.com/ddev/wsl2-docker-desktop/builds/5721#01930e11-788c-4527-ab15-2db459abd3ec
This adds a little output on the fail that might help us understand why.

test: Fix TestGetAllURLs failure on tb-wsldd-16

---

pkg/ddevapp/config.go
pkg/ddevapp/config_test.go

After 
* https://github.com/ddev/ddev/pull/6691
The ddev-platformsh add-on tests started failing on HEAD, https://github.com/ddev/ddev-platformsh/actions/runs/11758075483/job/32757492720
I had to use tmate to debug, but it turned out that ddev-platformsh installs several php modules for drupal9 and drupal10. And those use php8.0, which is not there by default. 
After they install modules, /var/lib/php/modules is not writable, and ddev fails to start.
* chmod /var/lib/php later
* Add some test coverage by adding redis.

fix: not-included PHP version should work with webimage_extra_packages

---

pkg/ddevapp/config.go

From Drupal Slack https://drupal.slack.com/archives/C5TQRQZRR/p1731341586120089
```
Waiting for containers to become ready: [web db] 
Warning: command 'bash -c mkdir -p /tmp/sqlite3 && wget -O /tmp/sqlite3/sqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_arm64/v8.deb && wget -O /tmp/sqlite3/libsqlite3.deb https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/libsqlite3-0_3.45.1-1_arm64/v8.deb && apt-get install -y /tmp/sqlite3/*.deb && rm -rf /tmp/sqlite3' run as 'root' failed with exit code 8:
--2024-11-11 16:30:05--  https://snapshot.debian.org/archive/debian/20240203T152533Z/pool/main/s/sqlite3/sqlite3_3.45.1-1_arm64/v8.deb
Resolving snapshot.debian.org (snapshot.debian.org)... 185.213.153.170 …
```

fix: use TARGETARCH instead of TARGETPLATFORM in user Dockerfiles

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- https://github.com/tj/n/issues/809#issuecomment-2465891240
Uses new `n install --cleanup` flag instead of `n install && n rm`.
This is the same thing, but with only one command.
```
$ ddev exec 'ls -la /usr/local/n/versions/node' # should be no files here
total 8
drwxr-xr-x 2 root root 4096 Nov 12 20:48 .
drwxr-xr-x 3 root root 4096 Nov 12 20:48 ..
$ ddev exec 'sudo n install --cleanup 20'
installing : node-v20.18.0
mkdir : /usr/local/n/versions/node/20.18.0
fetch : https://nodejs.org/dist/v20.18.0/node-v20.18.0-linux-x64.tar.xz
copying : node/20.18.0
installed : v20.18.0 (with npm 10.8.2)
cleanup : removing cached node/20.18.0
$ ddev exec 'ls -la /usr/local/n/versions/node' # should be no files here
drwxr-xr-x 1 root root 4096 Nov 12 22:37 .
drwxr-xr-x 1 root root 4096 Nov 12 20:48 .. …
```

refactor: use `n install --cleanup`

---

cmd/ddev/cmd/auth-ssh.go
docs/content/users/usage/commands.md
pkg/dockerutil/dockerutils.go

- #5465
- #6677
- Allows single file or symlink to a file or directory to be passed in `ddev auth ssh`.
- Fixes a warning from `grep -l` by mounting only files.
- Allows to mount several files and directories.
I didn't add a new flag for the file, I decided it would only complicate the code.
```
mkdir ~/temp_ssh
cp ~/.ssh/id_ed25519 ~/temp_ssh/id_ed25519
cp ~/.ssh/id_ed25519 ~/temp_ssh/id_ed25519_copy
ln -s ~/.ssh/id_ed25519 ~/temp_ssh/id_ed25519_symlink
ln -s ~/.ssh ~/temp_ssh/.ssh
ddev auth ssh -d ~/.ssh
ddev auth ssh -d ~/temp_ssh
ddev auth ssh -d ~/temp_ssh/.ssh
ddev auth ssh -f ~/temp_ssh/id_ed25519
ddev auth ssh -f ~/temp_ssh/id_ed25519_copy -f ~/temp_ssh/id_ed25519_symlink
ddev auth ssh -f ~/temp_ssh/id_ed25519 -f ~/.ssh/id_ed25519
rm -r ~/temp_ssh
```

feat: allow files and symlinks in `ddev auth ssh`, fixes #5465, fixes #6677

---

pkg/ddevapp/hostname_mgt.go

fix: Improve clarity in explanation by removing awkward 'normally', fixes #6723

---

docs/content/users/extend/customization-extendibility.md

8.3 is not marked up as code. Also, we could add the DDEV PHP version strategy? Maybe it belongs somewhere else?

docs: fix 8.3 typo and adding PHP version strategy

---

pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf

- #6656
Updates nginx config with https://developer.shopware.com/docs/resources/references/config-reference/server/nginx.html to make Shopware Update work.
(It already works for `apache-fpm`.)
1. Use our quickstart for Shopware https://ddev.readthedocs.io/en/stable/users/quickstart/#shopware
2. Open `composer.json` in the project root and replace the version to make it older, e.g.:
```diff
-"shopware/core": "v6.6.8.2"
+"shopware/core": "v6.6.8.1"
```
3. Run `ddev exec "rm -f composer.lock && composer install"`
4. Open admin panel `ddev launch /admin`
5. Login with credentials (admin / shopware)
6. `ddev launch "/admin#/sw/settings/shopware/updates/wizard"` (or Settings > System > Shopware updates)
7. Click "Start Update", follow instructions, it should update Shopware to the latest …

fix: make "Shopware Update" work with nginx, fixes #6656

---

containers/ddev-php-base/Dockerfile
containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
containers/ddev-webserver/Dockerfile
pkg/ddevapp/config.go
pkg/ddevapp/hooks_test.go
pkg/versionconstants/versionconstants.go

- #6159
- #6181
@stasadev pointed out that we're still building a custom php8.0-xdebug for a small number of users that experienced a crash with xdebug.
It's time to let that go, since PHP 8.0 is no longer supported.
* Stop doing the build of php8.0-xdebug (move it to the user Dockerfile).
* Stop using the results (move it to the user Dockerfile).
Check that Xdebug 3.2.2 is installed for PHP 8.0, 8.1, 8.2.
```
ddev config --php-version=8.0
ddev restart
ddev xdebug
ddev php -v
PHP 8.0.30 (cli) (built: Sep 27 2024 04:08:13) ( NTS )
Zend Engine v4.0.30, Copyright (c) Zend Technologies
with Zend OPcache v8.0.30, Copyright (c), by Zend Technologies
with Xdebug v3.2.2, Copyright (c) 2002-2023, by Derick Rethans
ddev exec "ls -l /usr/lib/php/20200930/xdebug.so"
``` …

fix: Move the custom php8.0-xdebug build from ddev-webserver to user Dockerfile

---

containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/log-stderr.sh
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mysql-client-install.sh
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/n-install.sh
containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/versionconstants/versionconstants.go

From Discord https://discord.com/channels/664580571770388500/1303391707416498238
A colleague of mine receives the warning below when starting a ddev project:
```
Warning: command 'n install 14' run as '<user>' failed with exit code 124
Command 'n install 14' timed out after 30 seconds
```
`ddev exec 'sudo n install 14'` succeeds.
Using 16MBit/s internet. OS is Windows with WSL2
We should allow more timeouts.
This PR sets the timeout to 1/4 of `default_container_timeout`
Set timeout to 31 seconds (124 / 4):
```
ddev config --default-container-timeout=124
```
Set your bandwidth to a really low speed.
In my case I did in on router https://www.asus.com/support/faq/1013333/
And use non default config to trigger timeout:
```
ddev config --database=mysql:8.0
ddev debug rebuild
...
Warning: …
```

feat: add dynamic timeout for scripts on start

---

cmd/ddev/cmd/cmd_version_test.go

New DDEV devs have often been annoyed by the failure of TextCmdVersion when run in GoLand or vscode without a `make` build that embeds the version.
Don't check when built that way.

test: ignore TestCmdVersion when running in IDE without make [skip ci]

---

.github/workflows/master-build.yml
.goreleaser.yml
Makefile
docs/content/developers/building-contributing.md
docs/content/developers/release-management.md
scripts/install_ddev_head.sh

* #6156 
* #6623 
Normal users of ddev/ddev/ddev are forced to get make and go and their dependencies
Don't do that. Fixes goreleaser.yaml, makes the release build test-able, including furies and AUR
foreach macos-arm64 macos-amd64 linux-amd64; do
done
Doing a release is a resonable thing. I just did https://github.com/ddev-test/ddev/releases/tag/v1.23.25 from this branch. Build at https://github.com/ddev-test/ddev/actions/runs/11847489029

fix: don't require go and make for ordinary homebrew installation, fixes #6156, fixes #6623

---

pkg/ddevapp/ddevapp.go
pkg/dockerutil/dockerutils.go

https://github.com/ddev/ddev/actions/runs/11915882563/job/33207216994
```
=== RUN   TestPHPConfig
...
Building project images...
2024-11-19T15:17:48.612 Executing docker-compose -f /home/runner/tmp/ddevtest/TestPkgDrupal101551583127/.ddev/.ddev-docker-compose-full.yaml build --progress=plain
......................................panic: test timed out after 4h0m0s
running tests:
TestPHPConfig (3h55m4s)
...
```
We started to see tests randomly fail when running a `docker-compose build`, but we cannot debug it because we don't see where it is stuck.
Let's add a relatively large timeout of 1 hour to at least see where it doesn't work.

build: add timeout to `docker-compose build`

---

containers/ddev-webserver/Dockerfile
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/versionconstants/versionconstants.go

- #6735 
Sqlite 3.45 installation  per-project in Drupal 11 is fragile. We can control it better in the ddev-webserver Dockerfile, and it's unlikely to bother anybody else.

fix: Move sqlite3 3.45 installation into ddev-webserver, fixes #6735

---

.github/workflows/container-tests.yml
cmd/ddev/cmd/scripts/test_ddev.sh
containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
containers/ddev-php-base/generic-files/usr/local/bin/install_php_extensions.sh
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/mariadb-client-install.sh
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/versionconstants/versionconstants.go

- #6745
https://github.com/ddev/ddev/actions/runs/11927136921/job/33242061289?pr=6739
Stuck here:
```
RUN (apt-get -qq update || true) && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests dnsutils
```
I think the reason why it's stuck is that some repo, e.g. deb.sury downloads with a very low speed.
- Add more timeouts for `apt-get update` that are done on the user side:
- I used 30 seconds (1/4 of the `--default-container-timeout`) for single repo `apt-get update`
- And 120 seconds for full `apt-get update`.
- Removes `-qq` that hid the output
- Removes custom `php8.0-xdebug` build because multi-stage build can fail if you have slow connection.

build: add more timeouts for `apt-get update`, remove custom `php8.0-xdebug`, for #6745

---

cmd/ddev/cmd/service-disable.go
cmd/ddev/cmd/service-enable.go
cmd/ddev/cmd/service.go

- #6298 
Deprecate and hide `ddev service enable` and `ddev service disable` as long-since replaced by `ddev add-on`
* Verify that `ddev service` doesn't show up in `ddev` or `ddev help`
* Verify that these commands can still be used
* Verify that they show a warning.

fix: Deprecate and hide ddev service commands, fixes #6298

---

pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/fileutil/files.go

We had `ddev-windows-mutagen` failures https://buildkite.com/ddev/ddev-windows-mutagen/builds/4923
It failed on installing `npm install --global forever`.
The contents of `.ddev/web-build/Dockerfile.example` was added on Windows by mistake:
```dockerfile
#ddev-generated
RUN npm install --global forever
RUN echo "Built on $(date)" > /build-date.txt
```
The contents of `Dockerfile.example` should never be added to the final `Dockerfile`: fixed using the correct file path in Windows.
And I added a check for `forever`, it should not be installed.
I think that `filepath.Glob` worked fine, but I added `filepath.Join` to make sure the path is right for Windows.
Change `~\.ddev` to `~/.ddev` in `ddev list` on Windows.
```
Router │ healthy      │ ~\.ddev          │ http://127.0.0.1:10999 │ traefik …
```

fix: use correct path for Windows in custom configs

---

cmd/ddev/cmd/cd.go
cmd/ddev/cmd/cd_test.go
cmd/ddev/cmd/debug-cd.go
cmd/ddev/cmd/debug-cd_test.go
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.zsh

- #6737
Replaces global `ddev` function wrapper with `ddevcd` function while keeping autocompletion.
Hides top level `ddev cd` to `ddev debug cd`.
Follow instructions from `ddev debug cd`, restart your shell, and use `ddevcd <tab>`

refactor: use `ddevcd` function with `ddev debug cd` instead of `ddev cd`, fixes #6737

---

pkg/ddevapp/cakephp.go

- #6760 
The wrong connection string is set when using Postgres instead of default database
Changed to correct database driver for CakePHP, postgres instead of pgsql
To avoid inherit the wrong encoding from default database (utf8mb4) we need to specify utf8 explicit.
Follow instructions in the CMS Quickstarts part, but add --database param to the ddev config
```
mkdir my-cakephp-site && cd my-cakephp-site
ddev config --project-type=cakephp --docroot=webroot --database=postgres:14
ddev composer create --prefer-dist --no-interaction cakephp/app:~5.0
ddev launch
```
When the project launches, CakePHP should be able to connect to the database
I could not find any tests related to this DATABASE_URL setting.
Not that I am aware of, since this is limited to CakePHP only, and a non-working …

fix: Set correct DATABASE_URL for CakePHP project using Postgres, fixes #6760

---

docs/content/users/configuration/config.md
mkdocs.yml

- #6604
People keep asking why their `composer_version` doesn't work, and `vendor/bin/composer` is used instead.
Explains how to update/remove/override it in the docs.
https://ddev--6762.org.readthedocs.build/en/6762/users/configuration/config/#composer_version
```
ddev composer require composer/composer -W
ddev exec /usr/local/bin/composer remove composer/composer
ddev composer -V # Composer version 2.8.3 2024-11-17 13:13:04
ddev composer require composer/composer:v2.8.0
ddev composer -V # Composer version 2.8.0 2024-10-02 16:40:29
mkdir -p .ddev/homeadditions/.bashrc.d
echo 'export PATH=/usr/local/bin:$PATH' >.ddev/homeadditions/.bashrc.d/path.sh
ddev restart
ddev composer -V # Composer version 2.8.3 2024-11-17 13:13:04
```

docs: explain how to update/remove/override `vendor/bin/composer`, for #6604

---

.buildkite/macos-colima.yml
.buildkite/macos-colima_vz.yml
.buildkite/macos-docker-desktop-amd64.yml
.buildkite/macos-docker-desktop-arm64.yml
.buildkite/macos-lima.yml
.buildkite/macos-orbstack.yml
.buildkite/macos-rancher-desktop.yml
.buildkite/test.sh
.buildkite/windows10_container.yml
.buildkite/windows10dockerforwindows.yml
.buildkite/wsl2-docker-desktop.yml
.buildkite/wsl2-docker-inside.yml

All builds are waiting for agents to be available, and we have this check:
https://github.com/ddev/ddev/blob/aa269d58ea9b13c4a1ccb51b249e168cde314314/.buildkite/test.sh#L154-L158
It only runs when the agent is available, but we can do it with Buildkite itself without waiting for the agent:
```yaml
if: |
build.message !~ /\[(skip ci|skip buildkite)\]/
```
Adds conditional https://buildkite.com/docs/pipelines/configure/conditionals#conditionals-in-steps
Check if `[skip ci]` or `[skip buildkite]` will skip the test from running i.e. remove this endless waiting for the agent.
I mean these tests:

build: do not run `.buildkite/test.sh` if we want to skip

---

.spellcheckwordlist.txt
docs/content/users/debugging-profiling/xhprof-profiling.md

XHprof is great but its UI is minimalist.
WIth the official ddev-xhgui, we should promote a more user-friendly experience.
This PR adds a reference to the XHGui addon in the relevant profiling section.
Ideally, I would like to see the page inverted; xhgui being the main focus, with xhprof mentioned as fallback.
I consider this PR a bare-minimal approach. I encourage others to make suggestion and changes.

docs: add note about XHGui

---

pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf

* https://github.com/orgs/ddev/discussions/6751#discussion-7525209 
* #6774 
explain an issue with Glide and DDEV's current default nginx configuration file.
It is debatable if this should be improve via updating the quickstart guide or via configuration.
This PR updates the default nginx configuration for Laravel. 
- Fix Glide 404 errors in Statamic CMS
- Fix file upload errors in Livewire with Laravel
I opted for a configuration PR because it reduces the change of developers "skipping" the required steps. I feel this improves the out-of-the-box experience for Laravel/Statamic developers.
Will consider splitting this PR to address  the 2 seperate issues, if required.
Fixes #6774

refactor: Improve nginx config for Laravel, fixes #6774, fixes #6751

---

cmd/ddev/cmd/composer-create_test.go
cmd/ddev/cmd/composer.go
cmd/ddev/cmd/composer_test.go
containers/ddev-webserver/ddev-webserver-base-files/etc/bash.bashrc
containers/ddev-webserver/ddev-webserver-base-files/etc/bash.nointeractive.bashrc
docs/content/users/configuration/config.md
pkg/ddevapp/composer.go
pkg/versionconstants/versionconstants.go

- #6771
`vendor/bin/composer` doesn't seem to be what we want, it's confusing and people can't override it with `ddev config --composer-version=<version>`
Reverts behavior to use `/usr/local/bin/composer`.
Removes `vendor/bin/composer` from `$PATH` inside the container with `EXECIGNORE` https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html
This way it will use `/usr/local/bin/composer` instead of `/var/www/html/vendor/bin/composer` with `ddev ssh`.
(Prior to this PR, `ddev ssh` && `composer -V` had always preferred `vendor/bin/composer` no matter what.)
`vendor/bin/composer` can still be called directly.
https://ddev--6772.org.readthedocs.build/en/6772/users/configuration/config/#composer_version
```
ddev composer require composer/composer:v2.8.0
ddev composer -V
Composer …
```

build: always use /usr/local/bin/composer, fixes #6771

---

cmd/ddev/cmd/xdebug_test.go
containers/ddev-php-base/Dockerfile
containers/ddev-php-base/ddev-php-files/etc/php/8.4/mods-available/xdebug.ini
containers/ddev-php-base/generic-files/etc/php-packages.yaml
containers/ddev-php-base/generic-files/usr/local/bin/build_php_extension.sh
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp_test.go
pkg/versionconstants/versionconstants.go

- #6465
Add extensions from deb.sury.org: apcu imagick memcached redis uploadprogress xhprof xmlrpc
Installed with PECL: xdebug
```
ddev php -m
ddev xdebug
ddev xhprof
ddev php -m
```
The only missing thing is imagick.

build: add missing php8.4 extensions, use PECL for php8.4-xdebug, fixes #6465

---

.buildkite/test.sh
pkg/ddevapp/hardened_test.go

Since we started using drupal11 for buildkite tests, the Windows test is failing TestDdevImportFiles because the files tarball contains a directory with a `:` in it, which is odd. 
`archive extraction of C:\Users\testbot\.ddev\testcache\tarballs\8b642a48_files.tgz failed err=mkdir C:\Users\testbot\.ddev\testcache\8b642a48_files.tgz\php\twig\664a9388692f2_umami:card_w8ADP9JF68172bQEf0cJMFdyV: The directory name is invalid.`
 
On Windows, don't bother with Drupal 11, use WordPress instead.

test: use Wordpress for testing Windows

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

Xdebug has a stable release https://xdebug.org/announcements/2024-11-28
And `docker-compose` v2.31.0 is out https://github.com/docker/compose/releases/tag/v2.31.0
Bumps it.

build: bump Xdebug to 3.4.0 and docker-compose to v2.31.0

---

pkg/ddevapp/hardened_test.go

I excluded Lima from TestHardenedStart for random test failures. We have adequate coverage of this and it's normally used only on Linux anyway. Now it will still be tested on OrbStack. 
Add test exclusion

test: Exclude Colima from TestHardenedStart [skip ci]

---

cmd/ddev/cmd/debug-cd.go
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.zsh
pkg/globalconfig/global_config.go

- #6743
I noticed that I couldn't `ddevcd` to a project with a broken configuration, but DDEV should allow it.
- Disables project validation for `ddevcd`.
- Hides `stderr` from completions for `ddevcd`, I noticed that when I press `<TAB>` when `ddevcd` is available and when I use v1.23.5, it shows an error, but I didn't even press enter.
Break project config and run `ddevcd`:
```
ddevcd d11
vim .ddev/config.yaml
cd ~
ddevcd d11
```

fix: do not run project validation for `ddevcd`, for #6743

---

pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/dockerutil/dockerutils.go

- #6417
Adds validation to web_extra_exposed_ports.
Also I searched for a way to validate Traefik, and found only these:
- https://github.com/aminiun/traefik-validator
- https://github.com/otto-de/traefik-config-validator
Both of these projects seem to be unmaintained, and they are unofficial, I decided not to use them.
(Update: `traefik healthcheck --ping` seems to be working fine.)
Add this to `.ddev/config.yaml`:
```yaml
web_extra_exposed_ports:
- name: example1
container_port: 3000
http_port: 3000
https_port: 3001
- name: example2
container_port: 4000
http_port: 4000
https_port: 4001
```
Break the config above with duplicate ports, and run `ddev start`, for example:
```yaml
web_extra_exposed_ports:
- name: example1
container_port: 3000
http_port: 3000
https_port: 3001
- name: example2 …
```

fix: add validation to web_extra_exposed_ports, fixes #6417

---

containers/ddev-php-base/Dockerfile
containers/ddev-php-base/ddev-php-files/etc/php/8.4/mods-available/xdebug.ini
containers/ddev-php-base/generic-files/etc/php-packages.yaml
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time to build new images for v1.24.0.
Xdebug 3.4.0 is available in deb.sury.org.
This PR is based on
- #6787
Rebase it after that one is pulled.
---
I didn't remove `opcache.jit=disable` from `/etc/php/8.4/mods-available/xdebug.ini` because it still shows this warning: 
```
PHP Warning:  JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0
```

build: bump images to v1.24.0 for release

---

cmd/ddev/cmd/auth-ssh.go
docs/content/users/usage/commands.md

- #6795
- Makes `ddev auth ssh -f` and `ddev auth ssh -d` mutually exclusive/
- Clarifies that command can be run multiple times, and the flags can be passed multiple times.
- Explicitly says "private" for SSH keys (because they can be "public").
This should fail:
```
ddev auth ssh -d ~/.ssh -f ~/custom/path/to/ssh/id_ed25519
```

refactor: make `ddev auth ssh` flags mutually exclusive, fixes #6795

---

containers/ddev-traefik-router/test/testdata/.static_config.yaml
docs/content/users/extend/traefik-router.md
pkg/ddevapp/global_dotddev_assets/traefik/README.md
pkg/ddevapp/global_dotddev_assets/traefik/static_config.loglevel.yaml.example
pkg/ddevapp/testdata/TestTraefikStaticConfig/extraPlugin/expectation.yaml
pkg/ddevapp/testdata/TestTraefikStaticConfig/logChange/expectation.yaml
pkg/ddevapp/testdata/TestTraefikStaticConfig/logChange/static_config.log_change.yaml
pkg/ddevapp/traefik_static_config_template.yaml

In reviewing 
- #6787
I noted that we had loads of log info we don't need, and way too much (access logs) in general.
* Change the default log level to ERROR (affects traefik events like config fails, etc)
* Change access log to only "unusual" things like 300-510
Try `docker logs -f ddev-router` with a number of configurations.
Rendered Traefik configuration updates in https://ddev--6794.org.readthedocs.build/en/6794/users/extend/traefik-router/#traefik-static-configuration

fix: Change traefik log level to ERROR and limit accessLog

---

pkg/ddevapp/ddevapp_test.go

Rancher Desktop's sshfs filesystem is too slow for TestWriteableFilesDirectory. Exclude it from test.

test: Skip TestWriteableFilesDirectory on Rancher [skip ci]

---

pkg/ddevapp/global_dotddev_assets/commands/host/dbeaver

- #6730
- #6654
For #6730, I added `showSystemObjects=true|showUtilityObjects=true`, see https://github.com/dbeaver/dbeaver/issues/4440#issuecomment-431572518
For #6654, I installed different DBeaver versions on Windows to get the correct path.
```
ddev dbeaver
```

fix: show system databases in DBeaver, add more Windows binaries, fixes #6730, fixes #6654

---

cmd/ddev/cmd/scripts/test_ddev.sh

`RUN timeout 120 apt-get update || true` has too high timeout, people with network troubles may think that `ddev debug test` is stuck.
- Lowers the timeout.
- Adds info about `$JAVA_HOME` for mkcert (so we know if there is something wrong with it).
- Prints curl location (I remember there were some issues with curl installed with homebrew or other place).
- Shows customizations in `.ddev/traefik/config`.
Run
```
ddev debug test
```

fix: improve `ddev debug test`

---

containers/ddev-webserver/Dockerfile
docs/content/users/extend/customizing-images.md
pkg/versionconstants/versionconstants.go

Extend default locales with some spanish and portuguese variants.
```
$ docker build containers/ddev-webserver -t ddev-locales
...
$ docker run --rm ddev-locales locale -a
C
C.utf8
POSIX
de_AT.utf8
de_DE.utf8
en_CA.utf8
en_GB.utf8
en_US.utf8
es_ES.utf8
es_MX.utf8
fr_CA.utf8
fr_FR.utf8
ja_JP.utf8
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
```
This area is not tested afaik.
No.

build: extend default locales with es_ES, es_MX, pt_PT and pt_BR

---

.buildkite/sanetestbot.sh
.github/workflows/sanetestbot.sh
Makefile
docs/content/users/install/performance.md

* Our tests don't need to look for NFS being enabled any more, we don't test NFS. 
* Docs don't need to explain how to fiddle with Windows NFS. It's just a bad idea.

test: Stop testing for NFS capability

---

.github/ISSUE_TEMPLATE/config.yml
containers/ddev-dbserver/README.md
containers/ddev-gitpod-base/README.md
containers/ddev-nginx-proxy-router/README.md
containers/ddev-php-base/README.md
containers/ddev-ssh-agent/README.md
containers/ddev-traefik-router/README.md
containers/ddev-webserver/README.md
containers/image_readme_template.md
containers/test-ssh-server/README.md
docs/content/developers/maintainers.md
docs/content/users/extend/additional-services.md
docs/content/users/extend/custom-compose-files.md
docs/content/users/extend/customization-extendibility.md
docs/content/users/providers/index.md
docs/content/users/support.md
docs/content/users/usage/architecture.md
docs/content/users/usage/faq.md
mkdocs.yml

* https://github.com/ddev/ddev.com/pull/288
We now have a shortlink for discord, so we don't have to use the odd one. Update that.
I also discovered a number of probably inappropriate references to ddev-contrib, so trimmed some of those.
I imagine this will run tests, but don't want to short-circuit that.

docs: use shortlink for discord access

---

.spellcheckwordlist.txt
containers/ddev-webserver/Dockerfile
docs/content/users/usage/commands.md
pkg/ddevapp/config.go
pkg/versionconstants/versionconstants.go

- #6733
Removes leftovers that were added here, but not removed:
- #4768
The `ddev-webserver` image size is 3.5 MB smaller.

fix: remove python leftovers, for #6733

---

docs/content/users/quickstart.md
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/web/autocomplete/sake

1. Some of the documentation about the "silverstripe" project type needed a touch up
2. Silverstripe CMS 6 adds completion to the `sake` command, but that's not exposed via `ddev sake`
For the docs:
- "Silverstripe" usually refers to the company. The open source CMS and
framework is referred to as "Silverstripe CMS". These references are updated.
- Add link to developer docs, which will be more useful to devs than the user docs.
- Add new CMS 6 syntax for sake command examples (e.g. `sake db:build`)
For sake completion:
Adds a completion script. This script exits early if an older version of Silverstripe CMS is detected.
For CMS 6+ it forwards the completion request to sake.
Setup:
```bash
ddev config --project-type silverstripe --php-version 8.3
ddev start && ddev composer create …
```

feat: add CLI completion for sake for Silverstripe CMS 6+ (plus some docs changes)

---

containers/ddev-webserver/Dockerfile
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/versionconstants/versionconstants.go

- #6807
- #6738
Adding sqlite3 3.45.1 for everyone is not good because it can break some dependencies.
This PR pre-downloads `*.deb` for sqlite3 3.45.1 and installs it only for Drupal 11, the idea comes from:
- https://github.com/ddev/ddev/pull/6812#issuecomment-2521805065
It increases `ddev-webserver` size by 1 MB.
```
ddev config --project-type=drupal11 && ddev restart && echo && ddev exec sqlite3 --version
3.45.1
ddev config --project-type=php && ddev restart && echo && ddev exec sqlite3 --version
3.40.1
```

refactor: pre-download sqlite3 3.45.1 for Drupal 11, fixes #6807

---

cmd/ddev/cmd/describe.go

In doing some debugging on gitpod for
* https://github.com/ddev/ddev/pull/6589
I noted a panic in `ddev describe`. It's a result of trying to convert nil to string. 
Check before converting.
`ddev describe` on gitpod

fix: correct panic on ddev describe on gitpod

---

pkg/ddevapp/config_test.go
pkg/ddevapp/hardened_test.go

* We've seen some interesting behavior from Apple Silicon docker providers on TestHardenedStart, and there's really no reason to run it there.
* TestConfigDefaultContainerTimeout has been failing on lima with the below, we don't know why, but it doesn't seem to be worth chasing.  "Read-only file system"
> failed to 'cp -r /var/tmp/TestConfigDefaultContainerTimeout120-mariadb_10.11.gz /mnt/ddev_config/db_snapshots': command 'cp -r /var/tmp/TestConfigDefaultContainerTimeout120-mariadb_10.11.gz /mnt/ddev_config/db_snapshots' returned exit code 1, stdout=, stderr=cp: cannot create regular file '/mnt/ddev_config/db_snapshots/TestConfigDefaultContainerTimeout120-mariadb_10.11.gz': Read-only file system
 
This PR disables those tests for the relevant architectures.
Related:
* …

test: Remove a couple of tests from lima/colima/rancher execution

---

docs/content/users/quickstart.md

- https://github.com/ddev/ddev/pull/6784#pullrequestreview-2486662032
- https://gist.github.com/rpkoller/d0fa272b81b7705dd3f56c35e01c8f8a
@rpkoller pointed out some problems in our quickstarts.
Magento 2:
I didn't notice any issue, the quickstart works for my in the current state.
But I decided to update the admin URL to the persistent value: `/admin_ddev`
Pimcore:
They require `amqp` extension:
- https://github.com/pimcore/skeleton/issues/186
Sulu:
They changed the filename to `website.xml`:
- https://github.com/sulu/skeleton/pull/248
Additionally, I automated setting `<name>` and `<key>` with `xmlstarlet`.
Test these quickstarts:
- https://ddev--6822.org.readthedocs.build/en/6822/users/quickstart/#magento
- https://ddev--6822.org.readthedocs.build/en/6822/users/quickstart/#pimcore
- …

docs: update magento2, pimcore, sulu quickstarts

---

docs/content/users/extend/customization-extendibility.md
docs/content/users/extend/customizing-images.md

- #6835
Adds instruction to the docs.
https://ddev--6836.org.readthedocs.build/en/6836/users/extend/customizing-images/#adding-eol-versions-of-php

docs: how to add unsupported PHP versions without `ddev config`, fixes #6835

---

docs/content/users/usage/faq.md

It's no longer a known path to run DDEV on an old mac, at least not in the way shown in the FAQ/Stack Overflow
Remove
@rpkoller put this in there years ago and it's obsolete, although there may be other ways.

docs: Remove run-ddev-on-old-mac from faq

---

docs/content/users/extend/customizing-images.md
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/dotddev_assets/db-build/Dockerfile.example
pkg/ddevapp/dotddev_assets/db-build/README.txt
pkg/ddevapp/dotddev_assets/web-build/Dockerfile.example
pkg/ddevapp/dotddev_assets/web-build/README.txt
pkg/ddevapp/dotddev_assets/web-entrypoint.d/README.txt

- #6757
Creates example Dockerfiles in `.ddev/web-build` and `.ddev/db-build` on `ddev config` and `ddev start`. This lets people understand that they can customize Docker images when they get a project from someone else (i.e. they don't run `ddev config`).
Populates app assets on `ddev config` in addition to `ddev start`.
Adds README.txt to `.ddev/web-build`, `.ddev/db-build` and `.ddev/web-entrypoint.d`.
Skips all Dockerfiles that end on `*.example`, not only `Dockerfile.example`.
Updates tests.
```
$ rm -rf .ddev/web-build && ddev start
$ ls .ddev/web-build 
Dockerfile.example  README.txt
$ ls .ddev/.webimageBuild 
Dockerfile
$ touch .ddev/web-build/file && mkdir -p .ddev/web-build/folder && ddev start
$ ls .ddev/.webimageBuild 
Dockerfile  file  folder
```

fix: don't copy Dockerfiles to `*imageBuild` folder, add examples to assets, fixes #6757

---

cmd/ddev/cmd/auth-ssh.go

- #6832
OpenSSH uses a [hardcoded convention](https://github.com/openssh/openssh-portable/blob/bbc9c18e84de29c83fa03e69290979fcca54a2b2/authfile.c#L308) for `-cert.pub`, we can mount it if it exists.
```c
if (asprintf(&file, "%s-cert.pub", filename) == -1)
```
To generate such a certificate, I used https://goteleport.com/blog/how-to-configure-ssh-certificate-based-authentication/
```
mkdir ssh-test && cd ssh-test
ssh-keygen -t rsa -b 4096 -f host_ca -C host_ca
ssh-keygen -t rsa -b 4096 -f user_ca -C user_ca
ssh-keygen -f ssh_host_rsa_key -N '' -b 4096 -t rsa
ssh-keygen -s host_ca -I host.example.com -h -n host.example.com -V +52w ssh_host_rsa_key.pub
$ ddev auth ssh -f ssh_host_rsa_key
Identity added: ssh_host_rsa_key (stas@dev)
Certificate added: ssh_host_rsa_key-cert.pub …
```

fix: mount OpenSSH certificate for `auth ssh`, fixes #6832

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

* #6840 
As a _vim_ power user, you are used to typing `vim` to start your favorite editor.
The `vim-tiny` package only adds a `/usr/bin/vi` binary.
This PR explicitly adds the `vim-tiny` package and then adds an alternative name “vim” via Debian's alternative system.
If someone needs to install the full `vim` package (`vim-nox` etc), this will then take precedence without conflict.
Difference between v1.24.1 and this PR
```
docker run --rm -it ddev/ddev-webserver:v1.24.1 apt-mark showmanual > 1.24.1.txt
docker run --rm -it ddev/ddev-webserver-prod:v1.24.1 apt-mark showmanual > 1.24.1-prod.txt
docker run --rm -it ddev/ddev-webserver:20241212_wazum_vim-tiny-vi apt-mark showmanual > pr.txt
docker run --rm -it ddev/ddev-webserver-prod:20241212_wazum_vim-tiny-vi apt-mark showmanual > …
```

build: reorganize `ddev-webserver` packages, add `vim` alternative, fixes #6840

---

cmd/ddev/cmd/composer-create.go
cmd/ddev/cmd/composer-create_test.go
cmd/ddev/cmd/config.go
pkg/ddevapp/ddevapp.go

- #6766
- Makes `ddev composer create` fully compatible (except for installing into a subdirectory) with `composer create-project`.
- Removes two `ddev restart` from `ddev composer create` (to speed up the process).
- Creates `docroot` (if it doesn't exist) inside `ddev composer create`, and runs `ddev restart` in this case.
- Adds `ddev composer create-project` alias to `ddev composer create`.
- Moves some logic from the main function to smaller functions.
Use quickstarts https://ddev.readthedocs.io/en/latest/users/quickstart/
Use `[<package> [<directory> [<version>]]]` syntax when running `ddev composer create`
```
ddev composer create laravel/laravel
ddev composer create laravel/laravel .
ddev composer create laravel/laravel . "~11"
ddev composer create laravel/laravel . "^11"
ddev …
```

feat: accept all args in `ddev composer create`, add `create-project` alias, fixes #6766

---

pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/global_dotddev_assets/commands/db/mysql

Database CLI commands (`ddev mysql`, `ddev psql`) are not configured to use a pager. This results is text wrapping on smaller terminal windows.
MySQL: 
Postgres:
This PR configures the pager option for databases, improving the readability of output.
- A PAGER environmental variable is defined
- It uses `less`  (see [man less](https://man7.org/linux/man-pages/man1/less.1.html) for `-SFX` switch descriptions.
- If output wraps, the pager is invoked. Press <kbd>right-arrow</kbd> to page right, <kbd>left-arrow</kbd> to page left.
- If output does not wrap, no pager is used (aka current behavior).
> [!IMPORTANT] 
> This PR changes the default behavior of the database CLI, and therefore may be "controversial"
> This PR using an environmental variable, developers can override the value through …

feat: Add pager to database output

---

scripts/install_ddev.sh

I happened to notice that the install_ddev.sh is still downloading the NFS setup script... and always for macos.
Remove that.

fix: remove nfs setup script from install_ddev.sh [skip ci]

---

docs/content/users/quickstart.md

Laravel has its own installer, but it's distributed only with Composer.
This installer allows you to select a [starter kit](https://laravel.com/docs/11.x/starter-kits) with additional options when you create the app:
```
$ laravel new
_                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|
┌ Would you like to install a starter kit? ────────────────────┐
│   ○ No starter kit                                           │
│   ○ Laravel Breeze                                           │
│ › ● Laravel Jetstream                                        │
└──────────────────────────────────────────────────────────────┘
┌ Which Jetstream stack …
```

docs: add Laravel Installer quickstart

---

Makefile
docs/content/developers/testing-docs.md

I noted that the `make mkdocs-serve` docker technique was no longer working
Explain how to install `mkdocs` with proper requirements using pipx.
Rendered at https://ddev--6864.org.readthedocs.build/en/6864/developers/testing-docs/#preview-changes
I confirm that the existing macOS instructions still work.

docs: Update mkdocs installation as docker doesn't work [skip ci]

---

docs/content/users/usage/offline.md

The ddev.com article https://ddev.com/blog/ddev-name-resolution-wildcards/ gives lots of background that isn't really possible in the docs. Link to it.

docs: Add link to hostnames article on ddev.com

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md

Historically, [CiviCRM](https://civicrm.org/) required a CMS such as Drupal or Wordpress, but [CiviCRM Standalone](https://civicrm.org/blog/ufundo/next-steps-civicrm-standalone) allows running it without a CMS.
Adds CiviCRM Standalone to the [CMS Quickstarts](https://ddev.readthedocs.io/en/stable/users/quickstart) page.
https://ddev--6846.org.readthedocs.build/en/6846/users/quickstart/#civicrm-standalone

docs: add CiviCRM Standalone to quickstart.md

---

docs/content/users/usage/database-management.md

Sometimes, you need an empty database, for later usage. Maybe an install process requires a database present, but you don't want to import a huge database first, just for the install process to over-write it, and then import the big database again.
It is possible to create an empty database manually, as can be seen in [How can I create and load a second database in ddev?](https://stackoverflow.com/questions/49785023/how-can-i-create-and-load-a-second-database-in-ddev/49785024#49785024)
However it requires a few steps, and simply importing an empty text file is much easier.
**Future**: Maybe, in the future, the `ddev import-db` command could get a `--create-db` option, something like this?
```
ddev import-db --database=other_db --create-db
```
Adds a new section on the …

docs: Add database management examples including how to create empty database

---

.github/workflows/pr-build.yml
.github/workflows/push-tagged-dbimage.yml
.github/workflows/tests.yml
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/providerAcquia_test.go
pkg/ddevapp/providerLagoon_test.go
pkg/ddevapp/providerPantheon_test.go
pkg/testcommon/testcommon.go
pkg/testcommon/testcommon_test.go

- #6865 
We don't have enough room on disk. Try to resolve.
It may be that some test cleanup is in order as well.
* Clean up more things that aren't needed in test runner
* Switch to Ubuntu 24.04 runner
* "Just because" I switched pr-build and push-tagged-dbimage to 24.04 as well. docscheck remains at 22.04 because of misbehavior of one of the actions.
* Clean up after a couple of TestPull/Push tests that weren't being cleaned up
* Clean up after each test in TestDdevFullSiteSetup
* Disable drupal 6/8/9 in TestDdevFullSiteSetup
This gets us from 28GB available to 43GB available at the start. We'll see if it breaks anything.

test: get more disk space on hosted runner, switch to ubuntu 24.04, fixes #6865

---

pkg/ddevapp/app_compose_template.yaml

Working on
- #3782 
In ddev/ddev-xhprof, one of the possible things to do is to overwrite the xhprof-prepend.php inside the container, but because we mount it read-only that's not possible
Mount .ddev/xhprof read-write
I imagine we'll end up completely change this approach and not use a bind-mount.
`ddev ssh` and `touch /usr/local/bin/xhprof/x`. If it works, it works.

fix: Make xhprof-prepend.php mount writable, for #3782

---

.textlintrc

The stopword setup for "just" and "simply" aren't helpful. Remove them.
Adjust .textlintrc

docs: Stop checking stopwords 'just' and 'simply' [skip ci]

---

pkg/ddevapp/dotddev_assets/providers/acquia.yaml

If you have multiple databases, `acli pull:db acquia` doesn't automatically use the default (the one initially created for the site). This causes ddev pull to instead pull a non-default database.
It specifies the default database.
Have an Acquia site with two databases. Run the ddev pull command. Confirm that the default database is pulled.

fix: In acquia.yaml, specify default site source for ddev pull acquia.

---

containers/ddev-dbserver/Dockerfile
pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/ddevapp.go
pkg/ddevapp/hooks_test.go
pkg/versionconstants/versionconstants.go

- #6886 
This doesn't really fix that, I'm not sure there's a fix other than putting `db` as the user back into the .my.cnf, which takes precedence, or changing the passwords so root and db have the same, which would break lots of people.
- Stop using ENV in the Dockerfile on MYSQL_XXX environment variables so they don't bleed into the container
- Remove MYSQL_PWD from the app_config_yaml, as we should be using the password from .my.cnf
- Minor hook test fixup because of that change.

fix: DB container: Remove MYSQL_PWD, use ARG in mysql/mariadb Dockerfile, remove OPTIMIZE TABLES, fixes #6886

---

.github/workflows/quickstart.yml
docs/content/users/quickstart.md
docs/tests/typo3.bats

Initial draft for the composer based quickstart for setting up TYPO3. tested locally and it is working fine. the second available quickstart is missing so far for this PR since there is no github repo for a typo3  test install yet as far as i can see. 

test: Quickstart tests for TYPO3 quickstart 

---

.buildkite/sanetestbot.sh
docs/content/developers/buildkite-testmachine-setup.md
docs/content/developers/scripts/windows_buildkite_setup.sh
docs/content/developers/scripts/windows_buildkite_start.ps1
docs/content/developers/scripts/wsl2-test-runner-setup.sh

Improving WSL2 Docker Desktop setup instructions for buildkite. Developer only.
Rendered docs at https://ddev--6889.org.readthedocs.build/en/6889/developers/buildkite-testmachine-setup/#windows-test-agent-setup
I haven't tested the script for WSL2/docker-ce, but tested for Docker Desktop several times, should be ok. 
This simplifies the setup of a WSL2 test runner quite a lot

docs: Improve windows buildkite setup workflow

---

docs/content/users/quickstart.md

@stasadev noticed that the quickstart for the git based approach to install typo3 is still using the phantasy url instead of the test-typo3 repo on the ddev org. this PR updates that. 

docs: change the quickstart repo for typo3 to test-typo3

---

pkg/ddevapp/app_compose_template.yaml

- https://github.com/ddev/ddev/pull/6842#issuecomment-2590294868
We don't have a quick and easy way to override `PAGER` variable in the `web` and `db` containers.
Adds an optional environment variable `DDEV_PAGER`.
I'm unsure where to add information about DDEV_PAGER in the docs (should we?).
The section on [Environment Variables Provided](https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#environment-variables-provided) is not the right place, as it covers variables inside the container, whereas `DDEV_PAGER` is used outside the container.
```
ddev start
ddev exec 'echo $PAGER'
less -SFX
```
```
export DDEV_PAGER=less
ddev start
ddev exec 'echo $PAGER'
less
```
```
export DDEV_PAGER=
ddev start
ddev exec 'echo $PAGER'
<empty>
```
```
unset DDEV_PAGER
ddev start
ddev exec …
```

feat: override `PAGER` with `DDEV_PAGER` env variable, for #6842

---

.spellcheckwordlist.txt
docs/content/users/quickstart.md
docs/tests/wordpress.bats

* adding a bats test for the wp cli quickstart and one for the bedrock quickstart
* Improved docs, rendered at https://ddev--6897.org.readthedocs.build/en/6897/users/quickstart/#wordpress

test: Improve WP quickstart and add wordpress bats tests

---

containers/ddev-webserver/ddev-webserver-base-files/etc/bashrc/commandline-addons.bashrc
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/ddev
containers/ddev-webserver/tests/ddev-webserver/general.bats
pkg/ddevapp/global_dotddev_assets/commands/web/drush
pkg/ddevapp/global_dotddev_assets/commands/web/pint
pkg/ddevapp/global_dotddev_assets/commands/web/sake
pkg/ddevapp/global_dotddev_assets/commands/web/typo3
pkg/ddevapp/global_dotddev_assets/commands/web/wp
pkg/versionconstants/versionconstants.go

- #6574 
* People who work inside the web container like in the @ultimike technique often type `ddev <whatever>` and waste their keystrokes.
* Some commands like `xdebug on` would be useful inside the web container, and they're already there.
Add a simple `ddev` command. Works when things are available and when not available:
```
rfay@d11-web:/var/www/html$ ddev
You executed 'ddev ' inside the web container
but many DDEV commands are not available.
```
```
rfay@d11-web:/var/www/html$ ddev drush cr
You executed 'ddev drush cr' inside the web container
but many DDEV commands are not available.
However, you may be able to use just the command 'drush cr'
```
Also, specially for @ultimike :
```
rfay@d11-web:/var/www/html$ xdebug on
Enabled xdebug
rfay@d11-web:/var/www/html$ xdebug off
Disabled …
```

fix: provide a dummy ddev command inside container, allow web commands there, fixes #6574

---

pkg/versionconstants/versionconstants.go

We're preparing for a release and docker-compose 2.32.4 is out, https://github.com/docker/compose/releases/tag/v2.32.4
Bump it

build: bump docker-compose to 2.32.4

---

docs/content/users/quickstart.md
docs/tests/drupal.bats

(*disclaimer: did something stupid and pushed some changes to the branch for this PR, instead of the branch i created for it. :( but since both changes are about drupal CMS i rescoped this issue now.) 
this PR introduces two changes: 
1. per the request of @stasadev a small adjustment to the drupal cms quickstart and bats test adding the force flag to avoid option confirmation for people who activated that. plus the rest of the quickstarts are using that flag on remove operations as well. 
2. added a fixed link for the latest version of drupal cms zip file to the quickstart and test. got added to drupal cms in https://www.drupal.org/project/drupalorg/issues/3500098

test: add force flag to the remove cmd and a fixed dl link to the latest version of Drupal CMS

---

pkg/ddevapp/ddevapp.go
pkg/ddevapp/mutagen.go
pkg/dockerutil/dockerutils.go
pkg/util/utils.go

@rpkoller pointed out that we have some strange output on `ddev start`:
```
Building project images... 
. db  Built 
web  Built 
Project images built in 1s.
```
Previously it looked like this:
```
Building project images... 
.Project images built in 1s.
```
This noise was added with:
- #6905
1. Removes the noise.
2. Changes the output from:
```
Building project images...
........Project images built in 8s.
Starting Mutagen sync process...
........Mutagen sync flush completed in 8s.
```
to:
```
Building project images...........
Project images built in 8s.
Starting Mutagen sync process...........
Mutagen sync flush completed in 8s.
```
3. We use short names here:
```
Waiting for containers to become ready: [web db]
```
but not here:
```
Waiting 120s for additional project containers …
```

fix: remove noise from `docker-compose` on build and reformat `ddev start` output, for #6905

---

pkg/ddevapp/drupal/drupal7/settings.ddev.php
pkg/ddevapp/drupal/drupal7/settings.php

- Adds new Trusted Host Patterns to eliminate the warning on status report. 
- Adds `skip_permissions_hardening` conf
- Replaces settings.php contents with entire `default.settings.php` file from Drupal 7.103
Mutagen also fails if attempting to modify the settings.ddev.php files after installation if `$conf['skip_permissions_hardening']` is not set to `TRUE`.
Drupal 7 has added many features to the `default.settings.php` including a version of Trusted Host Patterns similar to D10/11 which cause an error on status reports:
```
{
"title": "Trusted Host Settings",
"value": "Not enabled",
"description": "The trusted_host_patterns setting is not configured in settings.php. This can  \nlead to security vulnerabilities. It is *highly recommended* that you  \nconfigure this. See Protecting …
```

fix: update Drupal 7 settings.ddev.php and settings.php to match Drupal 7.103

---

docs/content/developers/project-types.md
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/webserver_config_assets/nginx-site-cakephp.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal11.conf
pkg/ddevapp/webserver_config_assets/nginx-site-silverstripe.conf
pkg/ddevapp/webserver_config_assets/nginx-site-symfony.conf

- #6910
The correct nginx configuration (.ddev/nginx_full/nginx-site.conf) was not being installed for `drupal11` or `drupal` projects.
I didn't check, but I assume this was a regression in v1.24.0, when we introduced the `drupal11` project type.
Provide the nginx config.
`ddev start` in a `drupal11` or `drupal` project and inspect .ddev/nginx_full/nginx-site.conf

fix: nginx-site-drupal11.conf wasn't being installed, fixes #6910

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time for v1.24.2 release.
Bumps Docker images.
Bumps Xdebug to 3.4.1 for PHP 8.3 and 8.4 because of https://bugs.xdebug.org/view.php?id=2307
```
$ ddev start
$ ddev xdebug
Enabled xdebug
$ ddev exec php8.3 -v
PHP 8.3.16 (cli) (built: Jan 19 2025 13:29:20) (NTS)
Zend Engine v4.3.16, Copyright (c) Zend Technologies
with Zend OPcache v8.3.16, Copyright (c), by Zend Technologies
with Xdebug v3.4.1, Copyright (c) 2002-2025, by Derick Rethans
$ ddev exec php8.4 -v
PHP 8.4.3 (cli) (built: Jan 19 2025 18:22:53) (NTS)
Zend Engine v4.4.3, Copyright (c) Zend Technologies
with Zend OPcache v8.4.3, Copyright (c), by Zend Technologies
with Xdebug v3.4.1, Copyright (c) 2002-2025, by Derick Rethans
```

build: bump images to v1.24.2 for release

---

docs/content/developers/buildkite-testmachine-setup.md

Docs: Rancher Desktop should probably be set to VZ/VirtioFS for buildkite. That's what everything else uses.

docs: Update Rancher Desktop buildkite agent setup [skip ci]

---

.github/workflows/quickstart.yml

We'll be preparing more quickstart automated tests (thanks @rpkoller )
The Magento 2 tests require a composer secret set.
Provide the necessary secrets in that test

test: prepare for magento2 quickstarts by providing composer secrets [skip ci]

---

.buildkite/test.sh

- https://github.com/lima-vm/lima/issues/3145#issuecomment-2613728408
All our lima and colima tests are failing after Lima 1.0.4. This seems to be because orbstack was still running and it tries to take some action on the docker.sock, even though it's not the correct docker.sock.
Stop orbstack before running anything else

test: make lima/colima tests work after lima 1.0.4

---

pkg/ddevapp/config.go
pkg/ddevapp/config_test.go

- #6925
The problem is that when you upgrade from DDEV v1.24.1 to v1.24.2 and have a *running* project in a not allowed place, you will see panic:
```
$ ddev poweroff
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa67cf8]
goroutine 1 [running]:
github.com/ddev/ddev/pkg/ddevapp.GetActiveProjects()
/home/runner/work/ddev/ddev/pkg/ddevapp/utils.go:51 +0x238
...
```
---
The change was made in:
- #6852
Previously, the code was:
https://github.com/ddev/ddev/blob/4936e6958fec52fff844df64f2650db6148348d3/pkg/ddevapp/config.go#L79C1-L81C3
```go
if appRoot == filepath.Dir(globalconfig.GetGlobalDdevDir()) || app.AppRoot == homeDir {
return nil, fmt.Errorf("ddev config is not useful in your home directory (%s)", …
```

fix: don't panic when running project in not allowed location, fixes #6925

---

pkg/ddevapp/ddevapp.go

In very occasional cases, JAVA_HOME may be set incorrectly, leading to failure or hang of the `mkcert` command, which is used to create trusted certs. Examples in https://stackoverflow.com/questions/78865612/ddev-mkcert-install-fails-or-hangs-when-java-home-misconfigured
Disables `mkcert` if `JAVA_HOME` is incorrect.
`mkcert` fails to run if `JAVA_HOME` is set, and `$JAVA_HOME/lib/security/cacerts` or `$JAVA_HOME/jre/lib/security/cacerts` is not found.
Set JAVA_HOME to something that causes failure. Try `ddev start`, it should work with this PR, and fail with v1.24.2:
```
export JAVA_HOME=/usr
ddev start
```

fix: unset JAVA_HOME to prevent mkcert hang

---

cmd/ddev/cmd/config_test.go
pkg/ddevapp/config.go

- #6937
If users have existing projects in a forbidden place, let them run `ddev config` there.
```
$ mkdir -p ~/workspace/parent/subfolder/child/anotherdir
$ cd ~/workspace/parent/subfolder/child && ddev config --auto
Creating a new DDEV project config in the current directory (/home/stas/workspace/parent/subfolder/child) 
Once completed, your configuration will be written to /home/stas/workspace/parent/subfolder/child/.ddev/config.yaml
Configuring a 'php' project named 'child' with docroot '' at '/home/stas/workspace/parent/subfolder/child'.
For full details use 'ddev describe'. 
Configuration complete. You may now run 'ddev start'.
$ cd ~/workspace/parent && ddev config --auto
Could not create a new config: a project is not allowed in /home/stas/workspace/parent because another project …
```

fix: allow `ddev config` for existing parent projects, fixes #6937

---

.github/workflows/golangci-lint.yml

Sometimes `golangci-lint` introduces new rules that break our tests. This affects the people who contribute to DDEV because these errors show up in their PRs. Usually, we deal with this by doing a hotfix PR, merging it, and then rebasing other people's PRs.
Runs `golangci-lint` in the PR only for the actually modified code, the full check will still be done on the main branch.
I got the idea from #6953, where I tested the same thing for `linkspector`.
I tested this PR on `ddev-test`. It works!
Log from this PR https://github.com/ddev/ddev/actions/runs/13081600537/job/36506164694?pr=6954
```
run golangci-lint
only new issues on pull_request: /tmp/tmp-1924-DYZkqY0KDaC0/pull.patch
```

build: run golangci-lint only for changed code in PRs

---

.github/workflows/docscheck.yml

- #6860
I noticed that linkspector doesn't run for main branch:
https://github.com/ddev/ddev/actions/runs/13079915327/job/36500915400
```
Running linkspector with reviewdog :dog: ...
reviewdog: this is not PullRequest build.
```
Changes the reporter to make it check for broken links on the main branch as well.
I tested it on `ddev-test`.
In addition, I confirmed that `filter_mode: ${{ github.event_name == 'pull_request' && 'added' || 'nofilter' }}` allows us to check only for changed links.
This means that if some link somewhere in the project is broken, and PR didn't touch it, then it won't be reported (the error will be shown only on the main branch build).

build: run linkspector on the main branch, for #6860

---

Makefile

Before:
```
$ make linkspector
linkspector: 
if command -v linkspector >/dev/null 2>&1; then \
linkspector check; \
else \
echo "Not running linkspector because it's not installed"; \
fi
⠹ Checking docs/content/index.md...
```
After:
```
$ make linkspector
linkspector: 
⠼ Checking docs/content/index.md...
```

build: hide extra output from linkspector [skip ci]

---

.github/workflows/quickstart.yml
.spellcheckwordlist.txt
docs/content/users/quickstart.md
docs/tests/backdrop.bats
docs/tests/processwire.bats

Add Processwire CMS to quickstarts
* Add the quickstart
* Add the automated test
Review rendered docs at https://ddev--6879.org.readthedocs.build/en/6879/users/quickstart/#processwire
* Step through both types of quickstart and make sure they work right
* Review the automated test and make sure it properly tests the quickstart
Added processwire.bats.

docs: Add ProcessWire to the Quickstart List

---

cmd/ddev/cmd/import-files.go
pkg/ddevapp/ddevapp.go
pkg/util/prompt.go
pkg/util/utils_test.go

- #6938
Trims single quotes, double quotes, and spaces from user input where filepath is required.
Before
```
$ ddev import-db
Provide the path to the database you want to import. 
Path to file: 'db.sql.gz'
Error: failed to import database 'db' for php-2023: unable to validate import asset 'db.sql.gz': invalid asset: file not found
```
After:
```
$ ddev import-db
Provide the path to the database you want to import. 
Path to file: 'db.sql.gz'
1.22KiB 0:00:00 [19.2MiB/s] [================================>] 100%            
Successfully imported database 'db' for d11
```
Repeat the same with double quotes.
Before
```
$ ddev import-files
Provide the path to the source directory or archive you wish to import. 
Please note: if the destination directory exists, it will be emptied and replaced …
```

fix: trim single quotes, double quotes, and spaces from filepath input, fixes #6938

---

cmd/ddev/cmd/dotenv_test.go
cmd/ddev/cmd/utils.go

- #6949 
Changes the error message to make it clearer what is allowed.
```
$ ddev dotenv set .env --test_flag=foobar
Error reading command flags: the flag must consist of lowercase letters, numbers, and hyphens, and it must start with a letter, but received --test_flag=foobar
```

fix: improve error message for invalid env flag, fixes #6949

---

pkg/ddevapp/ddevapp.go
pkg/ddevapp/snapshot_test.go

- #6955
Checks if the snapshot title contains letters, numbers, hyphens, or underscores.
Instead, we could escape or replace incorrect characters, but the validation is simpler.
```
ddev snapshot --name="with spaces"
Failed to snapshot d11: invalid snapshot name 'with spaces': it may only contain letters, numbers, hyphens, periods, and underscores
```
```
ddev snapshot --name="single'quotes"
Failed to snapshot d11: invalid snapshot name 'single'quotes': it may only contain letters, numbers, hyphens, periods, and underscores
```
```
ddev snapshot --name="double\"quotes"
Failed to snapshot d11: invalid snapshot name 'double"quotes': it may only contain letters, numbers, hyphens, periods, and underscores
```
```
ddev snapshot --name="my_snapshot-123-test.name"
Creating database snapshot …
```

fix: check snapshot name for valid characters, fixes #6955

---

pkg/ddevapp/router_test.go

`TestUseEphemeralPort` fails from time to time, in this case it didn't use 33003 port (probably it was busy), which broke the test:
https://github.com/ddev/ddev/actions/runs/13180515366/job/36789882879
```
Port 28080 is busy, using 33000 instead, see https://ddev.com/s/port-conflict
2025-02-06T15:30:21.859 GetAvailableRouterPort(): proposedPort 28443 is not available, epheneralPort=33001 is available, use it
Port 28443 is busy, using 33001 instead, see https://ddev.com/s/port-conflict
2025-02-06T15:30:21.86 GetAvailableRouterPort(): proposedPort 8025 is not available, epheneralPort=33002 is available, use it
Port 8025 is busy, using 33002 instead, see https://ddev.com/s/port-conflict
2025-02-06T15:30:21.86 GetAvailableRouterPort(): proposedPort 8026 is not available, epheneralPort=33004 …
```

test: allow a margin of +2 for ephemeral port checks due to flakiness

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #6958
Add `patch` command (which was removed in v1.24.2) to the `ddev/ddev-webserver-prod` Docker image.
```
docker run --rm -it ddev/ddev-webserver-prod:20250204_stasadev_patch_hardened patch --version
```
or
```
ddev config global --use-hardened-images
ddev start
ddev exec patch --version
```

fix: add patch command to hardened prod web image, fixes #6958

---

pkg/ddevapp/compose_yaml.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/testdata/TestMultipleComposeFiles/.ddev/docker-compose.ports.yaml

- #6943
Adds Docker IP to the port, but only if the IP is not already set, making it a non-breaking change.
Default config should use `127.0.0.1`:
```
ddev config --bind-all-interfaces=false # default value
printf "services:\n  web:\n    ports:\n      - 12345:12345\n" > .ddev/docker-compose.web.yaml
ddev start
cat .ddev/.ddev-docker-compose-full.yaml | grep -B3 12345
- host_ip: 127.0.0.1
mode: ingress
protocol: tcp
published: "12345"
target: 12345
```
`bind-all-interfaces` uses `0.0.0.0`:
```
ddev config --bind-all-interfaces=true
printf "services:\n  web:\n    ports:\n      - 12345:12345\n" > .ddev/docker-compose.web.yaml
ddev start
cat .ddev/.ddev-docker-compose-full.yaml | grep -B3 12345
- host_ip: 0.0.0.0
mode: ingress
protocol: tcp
published: "12345"
target: 12345
```
Use default …

feat: bind IP to user-defined ports if not set, fixes #6943

---

containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
containers/ddev-webserver/ddev-webserver-prod-scripts/start.sh
pkg/versionconstants/versionconstants.go

- #6966
Switch Apache MPM (prefork > event) to handle concurrent requests
Switches to Apache mpm_event unconditionally
See issue (to reproduce section)
Covered by existing tests?
None required

feat: switch apache mpm_prefork to mpm_event, fixes #6966

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

I wanted to build an image for another PR, but got this error on `ddev-php-base` build (from https://github.com/ddev/ddev/commit/daaea4053f2ac7bf3dcdf4cdb1a385f1f9ef7a8e):
```
> [linux/amd64 base  6/15] RUN curl -s -I https://packages.sury.org/php/:
0.048 /bin/bash: line 1: curl: command not found
```
- Reverts https://github.com/ddev/ddev/commit/daaea4053f2ac7bf3dcdf4cdb1a385f1f9ef7a8e
- While I'm here, remove Xdebug 3.4.1 custom build

build: remove custom Xdebug 3.4.1

---

.envrc
Makefile

The [Makefile](https://github.com/ddev/ddev/blob/main/Makefile) suggests installing some tools globally, but it is better to install them in an isolated environment, accessible only within DDEV directory.
Adds a config file for `direnv` tool, that will autoinstall everything needed.
It is completely optional and not necessary, but I find it easy to use.
1. Install direnv: https://direnv.net/docs/installation.html
2. Hook direnv into your shell: https://direnv.net/docs/hook.html
3. Create the global config: https://github.com/direnv/direnv/blob/master/man/direnv.toml.1.md
where `~/workspace/ddev/.envrc` is the path to this file.
(Alternatively, `.envrc` file can be loaded with `direnv allow .`)
```  
$ cat ~/.config/direnv/direnv.toml
[global]
hide_env_diff = true
[whitelist]
exact = …
```

build: autoload Python and Node deps from Makefile with direnv [skip ci]

---

docs/content/users/extend/database-types.md

Reflecting blog post https://ddev.com/blog/database-improvements/, I've updated this page to show DDEV supports MySQL 8.4.

docs: add MySQL 8.4 to supported databases

---

containers/ddev-php-base/ddev-php-files/etc/php/7.3/fpm/pool.d/www.conf
containers/ddev-php-base/ddev-php-files/etc/php/7.4/fpm/pool.d/www.conf
containers/ddev-php-base/ddev-php-files/etc/php/8.0/fpm/pool.d/www.conf
containers/ddev-php-base/ddev-php-files/etc/php/8.1/fpm/pool.d/www.conf
containers/ddev-php-base/ddev-php-files/etc/php/8.2/fpm/pool.d/www.conf
containers/ddev-php-base/ddev-php-files/etc/php/8.3/fpm/pool.d/www.conf
containers/ddev-php-base/ddev-php-files/etc/php/8.4/fpm/pool.d/www.conf
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/tests/ddev-webserver/general.bats
containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
containers/ddev-webserver/tests/ddev-webserver/project_type.bats
pkg/versionconstants/versionconstants.go

By default php-fpm outputs logs like this:
```
[06-Feb-2025 12:04:23] WARNING: [pool www] child 1554 said into stderr: "{"message":"Matched route \"app_admin_schedule_index\".","context":{"route":"app_admin_schedule_index","route_parameters":{"_route":"app_admin_schedule_index","_controller":"App\\Controller\\Admin\\Event\\EventScheduleController::index","event":"2"},"request_uri":"https://myapp.ddev.site/admin/event/2/schedule/template","method":"GET"},"level":200,"level_name":"INFO","channel":"request","datetime":"2025-02-06T12:04:23.926697+01:00","extra":{}}"
[06-Feb-2025 12:04:23] WARNING: [pool www] child 1554 said into stderr: "{"message":"Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: \"\"App\\Entity\\Event\" object not found by …
```

feat: change php-fpm setting 'decorate_workers_output' to 'no'

---

cmd/ddev/cmd/config.go
cmd/ddev/cmd/config_test.go
docs/content/developers/quickstart-maintenance.md
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/util/utils.go

```
ddev config --docroot=web
ddev config --docroot=""
ddev config --docroot=.
ddev config --docroot="/test"
Could not create docroot at /test: the provided docroot /test is outside the project root
ddev config --docroot="/tmp"
```
- Normalizes docroot in `CreateDocroot` function.
- Accepts quoted input for docroot in `ddev config` (because we accept path here).
- Adds a test.
```
ddev config --docroot=web
ddev debug configyaml | grep docroot # docroot: web
ddev config --docroot=""
ddev debug configyaml | grep docroot # should return nothing
ddev config --docroot="."
ddev debug configyaml | grep docroot # should return nothing
ddev config --docroot="./"
ddev debug configyaml | grep docroot # should return nothing
ddev config --docroot="/test"
Could not create docroot at /test: the …
```

feat: normalize docroot usage in `ddev config`

---

containers/ddev-php-base/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

From Discord https://discord.com/channels/664580571770388500/1338908217094180935
A user experienced an issue with PHP 8.2 and Xdebug 3.2.2 when debugging was enabled.
Some time ago, we reverted Xdebug from 3.3.x to 3.2.2 in:
- #6181
Xdebug 3.4.1 is now available for PHP 8.1 and PHP 8.2.
Given that some time has passed, it's time to switch to the newer versions.
This PR removes the custom PECL Xdebug builds for the mentioned PHP versions.
It should show Xdebug 3.4.1:
```
$ ddev start
$ ddev xdebug
$ ddev exec php8.1 -v
PHP 8.1.31 (cli) (built: Nov 21 2024 10:26:13) (NTS)
Zend Engine v4.1.31, Copyright (c) Zend Technologies
with Zend OPcache v8.1.31, Copyright (c), by Zend Technologies
with Xdebug v3.4.1, Copyright (c) 2002-2025, by Derick Rethans
ddev exec …
```

build: remove Xdebug 3.2.2 builds for php8.1 and php8.2

---

containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/etc/apt/preferences.d/blackfire
docs/content/users/debugging-profiling/blackfire-profiling.md
pkg/versionconstants/versionconstants.go

* #6978 
* https://github.com/ddev/ddev/issues/6078
Blackfire installation was completely failing due to systemd.
They seem to have fixed that in the meantime, meaning that the `apt-get install` only screams bloody murder, but actually succeeds with a zero exit code.
* Remove the pin
* Remove the removal of the /etc/apt/sources.list.d/blackfire.list
* Push the image
* Add specification of the image in versionconstants.go
Try using blackfire using the keys we have available in 1password

build: go back to normal blackfire packaging, fixes #6078

---

docs/content/users/extend/additional-services.md

- #6383
- Adds a link for DDEV Add-on Registry
- Removes `ddev add-on list` output because we have a registry.
https://ddev--6989.org.readthedocs.build/en/6989/users/extend/additional-services/

docs: add link for DDEV Add-on Registry, fixes #6383

---

docs/tests/backdrop.bats
docs/tests/drupal.bats
docs/tests/processwire.bats
docs/tests/typo3.bats
docs/tests/wordpress.bats

ddev start and or ddev restart was missing the yes flag on several bats tests. without a test is stuck on the new version of ddev prompt and could never proceed

test: add yes flag to ddev start cmd

---

.buildkite/test.sh

Recent bats quickstart tests (which are in docs directory) have been running on buildkite, wasting millions of CPU cycles.
* Try to make the skip in test.sh a bit more explicit
* Move the `set -x` so maybe we can see what happened.

test: figure out why buildkite tests are running for quickstart bats tests

---

cmd/ddev/cmd/dotenv-set.go
pkg/ddevapp/mutagen.go

the problem surfaced during the creation of the sulu bats test. even though the env.local file was correctly created the admin console command was unable to pickup the correct datanbase credentials leading to failing tests on macos in bash and zsh while the tests ran properly on github actions. adding  `ddev mutagen sync` per randys suggestion fixed the problem 
```
run ddev dotenv set .env.local --app-env=dev --database-url="mysql://db:db@db:3306/db?serverVersion=8.0&charset=utf8mb4"
run ddev mutagen sync
assert_success
run ddev exec bin/adminconsole sulu:build dev --no-interaction
```
but instead of adding the mutagen sync statement in the quickstart and the tests it is better to run the mutagen sync within the scope of the command. randy provided the code and i've just quickly done the …

fix: add a mutagen sync at the end of the dotenv cmd

---

cmd/ddev/cmd/exec.go
cmd/ddev/cmd/exec_test.go
pkg/ddevapp/task.go
pkg/util/utils.go

- #5865
- #3603
Uses the same technique I tried in:
- #6627
But this time I fixed the command with pipes `ddev exec "set | grep IS_DDEV_PROJECT"`
TODO:
- ~~I marked the `--raw` flag hidden. Mark it deprecated, remove it from the docs?~~
- ~~Remove `--raw` from tests~~
- ~~Check the hooks, maybe we can get rid of `exec_raw`~~
Edit: I decided not to remove the `--raw` flag, this PR simply runs `ddev exec` with *multiple* (2+) arguments, as it could be run using `ddev exec --raw`.
---
And it fixes panic for the wrong syntax on `ddev start` (this is indirectly related to `exec`, so I decided to fix it here):
```yaml
hooks:
post-start:
- exec:
exec_raw: ls -la # the command should look like this [ls, la]
```
```
$ ddev start
...
panic: interface conversion: interface {} is string, not …
```

fix: handle args with spaces in `ddev exec`, don't panic about invalid syntax in `exec_raw`, fixes #5865

---

Makefile

In tests, especially buildkite, we rather often have the mysterious test failure:
```
make: *** 
[.gotmp/bin/linux_amd64/mkcert] Error 92
```
This is just curl failing to download mkcert from the github release
* Try 5 times, it will likely work the second time
* Use `-S` to show the error if there is one
I did also fiddle with some other curls in the Makefile that have not been noticeably problemmatic.
`rm -r .gotmp/bin/*/mkcert && make`

test: Makefile - try again if curl fails to download something it needs

---

pkg/ddevapp/backdrop.go

- #7013
DDEV provides helpful information regarding Backdrop's config after importing a database. As of Backdrop 1.28.0, this information is slightly outdated so I'd like to update it.
Minor touch to adjust language slightly and give additional context about config storage options.
1. Spin up a Backdrop site.
2. Export the database.
3. Import the database.
4. Read the message that DDEV provides.
No additional tests needed as it's just a minor text adjustment.
n/a

docs: change code refs to include info about Backdrop config storage options, fixes #7013

---

.github/workflows/pr-artifacts-comment.yml
.spellcheckwordlist.txt
README.md
docs/content/developers/building-contributing.md
docs/content/developers/release-management.md
docs/content/developers/writing-style-guide.md
docs/content/index.md
docs/content/users/install/ddev-installation.md
docs/content/users/install/ddev-upgrade.md
docs/content/users/install/docker-installation.md
docs/content/users/install/performance.md
docs/content/users/topics/sharing.md

- #6891 
This is the docs section of the removal.
* Remove docs
* Remove the helper on PRs

docs: Remove gitpod/drupalpod from docs, for #6891 [skip buildkite]

---

.github/workflows/quickstart.yml
cmd/ddev/cmd/exec.go
cmd/ddev/cmd/exec_test.go
docs/tests/civicrm.bats

- #6930
After merging the PR above, CiviCRM quickstart failed because the value of `$DDEV_PRIMARY_URL` was not expanded.
```
ddev exec cv core:install --cms-base-url='$DDEV_PRIMARY_URL' ...
...
...
```
The use of `ExecRaw` broke variable expansion.
We can't use `ExecRaw` because variable expansion doesn't work.
I can add `os.ExpandEnv`, but it's not the same as bash expansion:
- https://github.com/golang/go/issues/47187
This means that any existing `ddev exec` code that depends on bash expansion will be broken.
So I reverted this change and added a double quote wrapping, which should be an appropriate solution that still fixes the arguments with spaces.
Using DDEV v1.24.2:
```bash
$ ddev exec echo '$IS_DDEV_PROJECT ${FOO_BAR:-foobar}'
true foobar
$ echo 'for i; do echo $i; done' > …
```

fix: wrap args with spaces in `ddev exec` with double quotes instead of using raw, for #6930

---

docs/tests/contao.bats

Initial draft of bats tests for contao. the first test for composer fails on the following step `run ddev exec contao-console contao:migrate --no-interaction` when running the test locally (https://gist.github.com/rpkoller/4d4f09f6971db12d4f7cbd4d2ba4a7bf). I've created the PR already to test it with tmate in github action as well per the suggestion of @rfay (otherwise i wouldnt have considered pushing a PR at this point yet)

test: contao quickstart bats test

---

pkg/versionconstants/versionconstants.go

* #7015
Mutagen 0.18.0 doesn't work at all with Docker 28.0.0
@xenoscopic diagnosed and immediately responded with a new release, thanks!
Bump mutagen to 0.18.1
Try it out with mutagen.

fix: bump mutagen to 0.18.1, fixes #7015

---

cmd/ddev/cmd/scripts/test_ddev.sh
docs/content/users/install/docker-installation.md

From Discord https://discord.com/channels/664580571770388500/1343957710604992573
It's good to see all available contexts in `ddev debug test`.
Say explicitly that rootless mode is not supported.

docs: add a note about rootless mode, show context in ddev debug test

---

cmd/ddev/cmd/describe.go
pkg/ddevapp/list.go
pkg/ddevapp/router.go

- https://github.com/ddev/ddev/pull/6980#issuecomment-2664268292
Run `ddev list --continuous`, open a new terminal and run `ddev start`
Look at `ddev list --continuous` (but this is not an error!):
In a couple of seconds:
Run `docker exec -it ddev-router bash -c "killall traefik"` in a new terminal.
Look at `ddev list --continuous` (it's ugly):
- Makes the `ddev list` output fancier
- Adds router error to `ddev describe` output because people don't always notice the output from `ddev start`, so give them a second chance to see if there is a problem with router on `ddev describe`.
Run `ddev list --continuous`, open a new terminal and run `ddev start`
Look at `ddev list --continuous`:
In a couple of seconds:
Run `docker exec -it ddev-router bash -c "killall traefik"` in a new terminal.
Look …

fix: show router errors on `ddev list` and `ddev describe`, for #6980

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time for v1.24.3 release mostly because of:
- #7015
- Bumps Docker images to v1.24.3
Not every image build worked, I used [this workaround](https://github.com/actions/runner-images/issues/11561#issuecomment-2678571978):
```yaml
- name: Set up QEMU
uses: docker/setup-qemu-action@v3
with:
image: tonistiigi/binfmt:qemu-v7.0.0-28
````
- Bumps `docker-compose` to [v2.33.1](https://github.com/docker/compose/releases/tag/v2.33.1)

build: bump images to v1.24.3 for release, and docker-compose to v2.33.1

---

cmd/ddev/cmd/composer-create.go
cmd/ddev/cmd/config.go
cmd/ddev/cmd/config_test.go
pkg/ddevapp/apptypes.go
pkg/ddevapp/backdrop.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/drupal.go
pkg/ddevapp/magento.go
pkg/ddevapp/typo3.go
pkg/ddevapp/upload_dirs.go
pkg/ddevapp/wordpress.go

* #6998
* Validate the docroot to make sure it isn't absolute or start with ..
* I didn't try to update tests
* This now does more validating and less normalizing (it doesn't change the offered docroot)
Try awkward and wrong docroot manually edited in config.yaml
* /web
* ../something
* other?

fix: validate docroot instead of using it blindly, fixes #6998

---

pkg/ddevapp/addons.go

I just noticed that my [add-on's post install actions](https://github.com/hanoii/ddev-pimp-my-shell/blob/637a873275cff867d82b48e707644df0f1854905/install.yaml#L21-L54) were not showing the `#ddev-description` as I was used to.
I looked at the code and found that the regex was not finding it if the stanza was right next to `- |`. One more newline and it was picked up.
I added an extra newline on the last commit of that file, but trying it with the latest release of the add-on show showcase the issue.

fix: the `#ddev-description` stanza in add-on install actions not showing if it's the first line

---

pkg/version/version.go
pkg/version/version_test.go

- #7021
Adds the Go version that was used in the DDEV build.
```
$ ddev version
ITEM             VALUE                                    
DDEV version     v1.24.3-1-g9337adae4                     
architecture     amd64                                    
cgo_enabled      0                                        
db               ddev/ddev-dbserver-mariadb-10.11:v1.24.3 
ddev-ssh-agent   ddev/ddev-ssh-agent:v1.24.3              
docker           28.0.1                                   
docker-api       1.48                                     
docker-compose   v2.33.1                                  
docker-platform  linux-docker                             
global-ddev-dir  /home/stas/.ddev                         
go-version       go1.23.6                                 <= added …
```

feat: add `go-version` to `ddev version`, fixes #7021

---

README.md

We have a large Discord community which is a main channel for support.  
We include a subtle link on DDEV.com and ReadTheDocs, both in footer. Our GitHub page does not.
This PR adds live badge that
- displays current online members
- links to the Discord invite
It was generated at https://shields.io/badges/discord.

feat: Add live link to Discord

---

cmd/ddev/cmd/delete-images.go
pkg/docker/images.go
pkg/versionconstants/versionconstants.go

- #6326
The PR addresses two details. first it fixes #6326 by applying the same pattern used for db images. i've addressed the suggestion by @stasadev using constants instead of the image name. talking of constant i've also did a small cosmetic fix and use now also a constant for addressing the db images instead of the image name. now every if clause in the for loop uses constants instead of image names
```
docker pull ddev/ddev-ssh-agent:v1.24.2
docker pull ddev/ddev-traefik-router:v1.24.2
docker images | grep v1.24.2
ddev/ddev-traefik-router                  v1.24.2                        01f41d37afe2   6 weeks ago     229MB
ddev/ddev-ssh-agent                       v1.24.2                        bd674e56e923   6 weeks ago     136MB
ddev delete images
docker images | grep v1.24.2 …
```

fix: delete traefik images based on the pattern used for ddev-dbserver and use constants for targeting, fixes #6326

---

containers/ddev-traefik-router/test/containertest.sh
containers/ddev-traefik-router/traefik_healthcheck.sh
pkg/versionconstants/versionconstants.go

- #7044
- #6931
Caused by the healthcheck change in:
- #6787
Changes the Traefik healthcheck command to use `127.0.0.1:${TRAEFIK_MONITOR_PORT}` instead of `:${TRAEFIK_MONITOR_PORT}`.
Note: I tried to change it here, but then dashboard doesn't open in the browser:
https://github.com/ddev/ddev/blob/0951e7848b699f83166029aed7f61e27fb462e3c/pkg/ddevapp/traefik_static_config_template.yaml#L43-L45
`http://:10999/ping` doesn't work with proxy.
Traefik source code:
https://github.com/traefik/traefik/blob/fa76ed57d361a4f441a897639005000ec6ab6b1a/cmd/healthcheck/healthcheck.go#L48-L79
```go
return client.Head(protocol + "://" + pingEntryPoint.GetAddress() + path + "ping")
```
Before:
```
$ docker exec -it ddev-router bash -c "traefik healthcheck --ping …
```

fix: explicitly ping 127.0.0.1 in Traefik healthcheck to make proxying work, fixes #7044, fixes #6931

---

scripts/install_ddev_wsl2_docker_desktop.ps1
scripts/install_ddev_wsl2_docker_inside.ps1

* #7024 
In some new Windows 11 versions, `wmic.exe` is either not installed or not in the PATH.
It's also part of a deprecated subsystem.
* Remove the `refreshenv` that happened to call this from the two WSL2 install scripts
* Since WSL2 now uses systemd, there's no need for the `system service docker start` that was in there.
Use a fresh clean Ubuntu as the default WSL2.
Install in both contexts (docker-ce and Docker Desktop), with `wmic` out of the path, as described in the issue.
There is no testing for this.

fix: remove refreshenv from WSL2 install scripts, fixes #7024 [skip ci]

---

docs/content/users/usage/cms-settings.md

Backdrop's config storage options can be confusing with local development, so it would be good to have a short description of the options as discussed in https://github.com/ddev/ddev/pull/7014#issuecomment-2677157148
As well, it is worth mentioning Backdrop's command line tool, `bee`. 
Review rendered at https://ddev--7037.org.readthedocs.build/en/7037/users/usage/cms-settings/#backdrop-specifics

docs: add Backdrop-specific config considerations.

---

.github/workflows/main-build.yml
.github/workflows/pr-build.yml
.github/workflows/tests.yml

- #7051 
Hopefully this is for a short time, but there have been multiple reports (see #7051) of problems pulling images from go code compiled with go 1.24. We're not having trouble locally, but there's no ready that go v1.23 is not fine.
Use go 1.23
Review the PR build output to verify that it uses go 1.23*

build: don't use go 1.24 yet until docker issues resolved, fixes #7051

---

.github/workflows/quickstart.yml
cmd/ddev/cmd/debug-download-images.go
docs/tests/common-setup.bash

We've been running quickstarts in a linux workflow, but we might get more information running them with mutagen on. 
We may want to think about running them on macOS, but for now we can enable mutagen here.
Turn on mutagen for these tests

test: Run quickstart tests with mutagen enabled [skip buildkite]

---

docs/content/users/topics/hosting.md

I had TODOs around from a couple of debugging sessions with users using DDEV for hosting.
This tries to add the things we learned in those cases.
Rendered at https://ddev--7056.org.readthedocs.build/en/7056/users/topics/hosting/
Especially the troubleshooting section

docs: Improve troubleshooting docs for hosting

---

.buildkite/test.sh

I wondered why buildkite tests were run for:
- #7061
Buildkite's skip logic works well when you're always up to date, but not when you're pushing commits without rebasing.
Affected PRs are PRs for documentation.
This PR uses the base merge commit instead of the latest HEAD to compare changes, which helps reduce the carbon footprint.

build: skip testing with buildkite if diff is not from that branch

---

containers/ddev-webserver/Dockerfile
containers/ddev-webserver/tests/ddev-webserver/general.bats
pkg/versionconstants/versionconstants.go

- #7054
Make sure both git and ssh client are in both ddev-webserver and ddev-webserver-prod
```
docker run -it --rm ddev/ddev-webserver:20250307_rfay_add_hardened_ssh git --version
docker run -it --rm ddev/ddev-webserver-prod:20250307_rfay_add_hardened_ssh git --version
docker run -it --rm ddev/ddev-webserver:20250307_rfay_add_hardened_ssh ssh -V
docker run -it --rm ddev/ddev-webserver-prod:20250307_rfay_add_hardened_ssh ssh -V
I did add a check for git and ssh in the image. It doesn't specifically check hardened though.

build: put both git and ssh in both webserver images, fixes #7054

---

.github/workflows/push-tagged-image.yml

Regular failures of push-tagged-image due to "Cannot allocate memory" in arm64 apt-get install
Use specific binfmt workaround until this gets fixed upstream.

build: Use specific binfmt for qemu in push-tagged-image [skip ci]

---

cmd/ddev/cmd/debug-test.go

- https://drupal.slack.com/archives/C5TQRQZRR/p1741801391372109
User ran `ddev debug test` from the project subdirectory (there was misunderstanding with initial `ddev config`, that was run in `~/www` instead of `~/www/drupal-test-01`). And the result of running it in `~/www/drupal-test-01` is:
```
Output file written to:
/tmp/ddev-debug-test.txt
file:///tmp/ddev-debug-test.txt
Please provide the file for support in Discord or the issue queue.
Failed running test_ddev.sh: exit status 1
. You can run it manually with `curl -sL -O https://raw.githubusercontent.com/ddev/ddev/main/cmd/ddev/cmd/scripts/test_ddev.sh && bash test_ddev.sh`
```
I noticed the same error when you run `ddev debug test` outside of any project.
Adds check for active project.
Runs `cd` to approot before running script. …

fix: add check for app in `ddev debug test` and run it from approot

---

.github/PULL_REQUEST_TEMPLATE.md

I was looking for the pull request title specs and noticed that our pull request template had an obsolete link.

docs: Fix pull request title link in pull request template [skip ci]

---

.linkspector.yml

Currently docs check is failing link to https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html because they're doing a migration and will be down for a week.
Don't check that link

test: Disable link check on freedesktop.org since it will be out for a week

---

docs/content/users/usage/cms-settings.md

- #7039 
Adds a doc for this, as discussed in #7041
Review rendered at https://ddev--7080.org.readthedocs.build/en/7080/users/usage/cms-settings/#cms-specific-help-and-techniques

docs: add Wordpress special handling info about wp-cli.yml

---

.spellcheckwordlist.txt
docs/content/users/usage/database-management.md

This PR adds DevDb tip to database management documentation
https://ddev--7084.org.readthedocs.build/en/7084/users/usage/database-management/#database-guis

docs: add DevDb tip to database management documentation

---

docs/content/users/quickstart.md
docs/tests/ee.bats

i'Ve made a few adjustments to the quickstart. added `-y`to `ddev start`to keep it in line with the tests. for the config i'Ve added `--database=mysql:8.0`to the git based install. so far it was only for the zip based. and i've adjusted the git based quickstart. before we had git clone and then the cd. but that caused problems with the bats test. i now took the road of creating a test dir change into it and then git clone into the dir. that works. 
and as already noted via discord to randy and stas for the zip based approach i'Ve used the snippets used for backdrop. there i noticed that i ran into warning and error moving the expanded zip assets to the parent root. i found a way to fix it and to make things pass locally. i was using shell options. but that needs a …

test: bats tests for expression engine and adjustments to its quickstart

---

docs/content/users/quickstart.md
docs/tests/kirby.bats

… to it
bats test for the new project quickstart... for existing quickstart there wont be a quickstart necessary imho. it is basically identically to the new project quickstart except the composer create step is missing and an existing codebase is expected

test: adding kirby quickstart bats test

---

pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/router.go
pkg/ddevapp/router_compose_template.yaml
pkg/ddevapp/utils.go
pkg/globalconfig/global_config.go

I happened to notice that we had some code checking for traefik/non-traefik routers, and since that's obsolete, it's better to remove.
Review carefully, but this should have no impact.

fix: remove obsolete references to non-traefik router

---

docs/tests/common-setup.bash

@stasadev suggested in todays discussion adding 
```
export DDEV_NONINTERACTIVE=true
export DDEV_NO_INSTRUMENTATION=true
```
to the common-setup.bash. turned out DDEV_NO_INSTRUMENTATION was already there but this PR is adding the second eng variable alongside. 

fix: add ddev_nointeractive to common-setup.bash (per @stasadev)

---

docs/content/users/quickstart.md
docs/tests/symfony.bats

bats tests for the symfony composer and the symfony cli quickstart. also made small adjustments to the quickstarts. 
only nagging point, at the moment it is only possible to check ddev launch. it is impossible to check the install with curl. the default page that is shown is not an actual page but rather a "virtual" on... the webprofiler in the footer bar shows a 404 and curl returns no output. so uncertain how to reliably and more thoroughly check for a successful install. am a bit out of ideas and dont know symfony well enough. only idea would be if it is possible to create a page with symfony cli if that is possible and then check that page and route as a proof that symfony was properly set up. but i only found the manual set up of a page and that entailed several …

test: symfony bats tests

---

docs/content/users/quickstart.md
docs/tests/drupal.bats

The `launch-drupal-cms.sh` script mentioned in the docs is removed from Drupal CMS 1.1.0, which releases tomorrow. We should remove all mention of it from DDEV's docs as well.
N/A
N/A
N/A

docs: Update quickstart.md to remove Drupal CMS zip file instructions

---

docs/content/users/extend/customizing-images.md

It's not clear in the docs how great `ddev debug rebuild` is for debugging long builds.

docs: ddev debug rebuild is great for debugging [skip buildkite]

---

docs/content/users/quickstart.md
docs/tests/openmage.bats

- #7094 
* Split openmage into its own quickstart
* Use git clone instead of zipball download
* Add quickstart test for it
Rendered updated docs at:
- https://ddev--7091.org.readthedocs.build/en/7091/users/quickstart/#magento-2
- https://ddev--7091.org.readthedocs.build/en/7091/users/quickstart/#openmage

test: add OpenMage/Magento 1 quickstart test and split it from Magento 2, for #7094

---

pkg/ddevapp/config.go

I liked how custom configurations are now output and I realize I was missing `config.*.y*ml` files to see what is there and it what order so I thought it a nice addition to add config files as well to the report:
```
Using custom MySQL configuration: [
./.ddev/mysql/acquia.cnf
] 
Using custom PHP configuration: [
./.ddev/php/cc9.ini
] 
Using custom web-build configuration: [
./.ddev/web-build/Dockerfile
./.ddev/web-build/Dockerfile.pimp-my-shell
] 
Using custom web-entrypoint.d configuration: [
./.ddev/web-entrypoint.d/readme-nodedeps.sh
] 
Using custom config.*.yaml configuration: [
./.ddev/config.pimp-my-shell.yaml
./.ddev/config.readme.yaml
./.ddev/config.selenium-standalone-chrome.yaml
./.ddev/config.~overrides.yaml
] 
Custom configuration is updated on restart.
If you don't see your …
```

feat: show config.*.y*ml on ddev start

---

.linkspector.yml

From https://github.com/ddev/ddev/actions/runs/13953802513/job/39059819024?pr=7124
```
message:"Cannot reach ../install/performance.md#mutagen. Status: 404 Cannot find section: #mutagen in file: /home/runner/work/ddev/ddev/docs/content/users/install/performance.md." location:
```
Related:
- #6951
Our linkspector `ignorePatterns` never worked, we didn't see any errors only because we didn't touch the existing links. (And our action for linkspector used reviewdog, that check *only* for modified links.)
I tested it locally with `make linkspector` and I almost gave up trying to make any regex work. (It just didn't work.)
Finally, I removed all regex related symbols, and it started working properly. 
I removed unused patterns.
And including this pattern `".md#"` made linkspector ignore local …

fix: make linkspector ignorePatterns work properly, for #6951

---

docs/content/users/install/configuring-browsers.md
docs/content/users/install/ddev-installation.md
docs/content/users/install/index.md
mkdocs.yml

- #7067
Add documentation about configuring browser for DDEV HTTPS certificates by installing the DDEV root Certificate Authority.
Add a page with browsers configuring instructions.
https://ddev--7075.org.readthedocs.build/en/7075/users/install/configuring-browsers/
Not needed.
Added docs about configuring browser for DDEV HTTPS certificates

docs: Add docs about configuring browser for HTTPS certificates

---

docs/tests/openmage.bats

- #7091
according to randy tests were failing on main for the openmage bats test. turn out the assertion testing the frontend was failing the test. well turns out the fix by stas got already merged https://github.com/OpenMage/magento-lts/pull/4720 and due to the fact the test and quickstart is using `git clone https://github.com/OpenMage/magento-lts .`the fix was already available that way the demo site is completely different: 
adjusted the assertion to the now working demo content. only question is is it a good idea to recommend a quickstart that is living on the edge aka the head for openmage?  ( a good thing in case of the bug but in the long run for less technical folks getting in touch with openmage for the first time i am unsure)

test: adjust openmage bats test assertions to the now available demo content

---

cmd/ddev/cmd/scripts/test_ddev.sh
pkg/amplitude/amplitude.go

- `ddev debug test` creates test project, which is probably included to instrumentation
- `curl` on host runs without explicit timeout
- Adds `export DDEV_NO_INSTRUMENTATION=true` inside the script.
- Runs `DOCKER_HOST="" docker context ls` with empty DOCKER_HOST (because it always shown as a warning, but we set this variable ourselves in DDEV).
- Fixes `printf` warnings shown to me in the IDE.
- Adds `docker system df` output with tips how to clean it.
- Do not show warning about instrumentation in `ddev version` if `DDEV_NO_INSTRUMENTATION=true`.
- Adds `curl --connect-timeout 10 --max-time 20` on the host to prevent people from using `^C`.
Run `ddev debug test`

test: improve `ddev debug test`

---

.linkspector.yml

https://github.com/ddev/ddev/actions/runs/13957940211/job/39112163537#step:10:344
```
Pattern exceeds maximum safe length: https://www.drupaleasy.com/blogs/ultimike/2019/06/...
message:"Cannot reach https://mutagen.io/documentation/synchronization/symbolic-links. Status: 403" location:{path:"docs/content/users/usage/troubleshooting.md" range:{start:{line:345 column:180} end:{line:345 column:259}}} severity:ERROR source:{name:"linkspector" url:"https://github.com/UmbrellaDocs/linkspector"}
```
- Ignores `https://mutagen.io`
- Shortens the pattern for `https://www.drupaleasy.com`

docs: ignore mutagen links in linkspector

---

cmd/ddev/cmd/config.go
docs/content/users/usage/commands.md
pkg/ddevapp/apptypes.go
pkg/ddevapp/apptypes_test.go

- #7035
Ignores the app type detection for the `generic` type.
Follow any quickstart https://ddev.readthedocs.io/en/stable/users/quickstart/ and run:
```
ddev config --project-type=generic
ddev config --update
```

fix: don't override `generic` type in `ddev config --update`, fixes #7035

---

pkg/ddevapp/config.go

- #7144
```
cp: cannot stat '/var/www/html/.ddev/xhgui_prepend.php': No such file or directory
exit status 1
Task failed: Exec command 'cp /var/www/html/.ddev/xhgui_prepend.php /var/www/html/.ddev/xhprof/xhprof_prepend.php
' in container/service 'web': exit status 1 
A task failure does not mean that DDEV failed, but your hook configuration has a command that failed. 
```
Reloads the hooks after the add-on is removed.
Using this PR, there should be no error on `ddev start`:
```
ddev stop
ddev add-on get ddev/ddev-xhgui
ddev start
```

fix: reload app hooks after uninstalling ddev-xhgui add-on, fixes #7144

---

docs/content/users/extend/in-container-configuration.md
pkg/ddevapp/app_compose_template.yaml

- #6842
- #7032
- Reads `DDEV_PAGER` from environment outside of DDEV.
- Doesn't set `DDEV_PAGER` value by default.
- Updates documentation.
See https://ddev--7138.org.readthedocs.build/en/7138/users/extend/in-container-configuration/#using-pager-inside-containers
```
export DDEV_PAGER="less -SFXR"
ddev start
ddev exec 'echo $PAGER'
less -SFXR
```

fix: make `DDEV_PAGER` optional, update docs for `PAGER`, fixes #7032

---

pkg/ddevapp/drupal.go

@rfay noticed this:
```
$ ddev config --update
You are reconfiguring the project at /home/stas/code/ddev-quickstarts/d11.
The existing configuration will be updated and replaced.
Auto-updating project configuration because update is requested.
Configuring a 'drupal11' project with docroot 'web' at '/home/stas/code/ddev-quickstarts/d11/web'
Default database type is mariadb:10.11, but the current actual database type is postgres:16, you may want to migrate with 'ddev debug migrate-database mariadb:10.11'.
Configuration complete. You may now run 'ddev start'.
```
Where:
```
Default database type is mariadb:10.11, but the current actual database type is postgres:16, you may want to migrate with 'ddev debug migrate-database mariadb:10.11'.
```
We should not suggest changing the database unless …

fix: db warning on `config --update` should only be shown for default db type

---

containers/ddev-xhgui/Dockerfile
pkg/ddevapp/app_compose_template.yaml
pkg/versionconstants/versionconstants.go

- #7069
- https://github.com/perftools/xhgui/issues/505
XHGui creates a volume in the [Dockerfile](https://github.com/perftools/xhgui/blob/cec362839f001a7f2f7f681abbcadbe0a26a400b/Dockerfile#L108):
```dockerfile
VOLUME "/run/nginx"
```
Related:
- https://github.com/moby/buildkit/issues/4802#issuecomment-2182544924
- https://github.com/moby/moby/issues/3465#issuecomment-2179958180
Overrides the parent Dockerfile using this technique:
- https://stackoverflow.com/questions/44020785/remove-a-volume-in-a-dockerfile/78645904
```
docker volume ls
ddev start
ddev xhgui
docker volume ls
```

fix: remove XHGui volume for `/run/nginx`, for #7069

---

cmd/ddev/cmd/commands.go
docs/content/users/extend/custom-commands.md
pkg/ddevapp/global_dotddev_assets/commands/web/artisan
pkg/ddevapp/global_dotddev_assets/commands/web/cake
pkg/ddevapp/global_dotddev_assets/commands/web/console
pkg/ddevapp/global_dotddev_assets/commands/web/craft
pkg/ddevapp/global_dotddev_assets/commands/web/drush
pkg/ddevapp/global_dotddev_assets/commands/web/magento
pkg/ddevapp/global_dotddev_assets/commands/web/npm
pkg/ddevapp/global_dotddev_assets/commands/web/nvm
pkg/ddevapp/global_dotddev_assets/commands/web/php
pkg/ddevapp/global_dotddev_assets/commands/web/sake
pkg/ddevapp/global_dotddev_assets/commands/web/typo3
pkg/ddevapp/global_dotddev_assets/commands/web/wp
pkg/ddevapp/global_dotddev_assets/commands/web/yarn

- #7053
- https://github.com/backdrop-ops/ddev-backdrop-bee/pull/8
We need to have a way to run `ddev mutagen sync` automatically.
Adds `## MutagenSync: true` annotation.
I added it to the most of our bundled `web` commands.
(I'm not 100% sure of the changes I've made, but I think we'll be able to figure out where we need `MutagenSync` or not in the review.)
```
ddev config global --performance-mode=mutagen
```
And:
```
mkdir my-backdrop-site && cd my-backdrop-site
ddev config --project-type=backdrop
ddev add-on get backdrop-ops/ddev-backdrop-bee
ddev start
ddev bee download-core
ddev bee si --username=admin --password=admin --db-name=db --db-user=db --db-pass=db --db-host=db --auto
ddev launch
```
Mutagen Sync should run before and after each of `ddev bee` commands:
```
$ …
```

feat: add MutagenSync annotation for custom commands, for #7053

---

pkg/ddevapp/ddevapp.go

I've noticed that we're not showing some status colors correctly.
Fixes it.
```
ddev add-on get ddev/ddev-memcached
ddev restart
ddev exec -s memcached kill 1
ddev describe
```
Before:
After:
---
```
ddev exec -s db kill 1
ddev list
```
Before:
After:

fix: correct status color formatting in `ddev describe` and `ddev list`

---

cmd/ddev/cmd/xhgui.go
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/ddev-webserver-base-files/usr/local/bin/xhprof/xhprof_prepend.php
containers/ddev-webserver/tests/ddev-webserver/php_webserver.bats
docs/tests/typo3.bats
pkg/ddevapp/config.go
pkg/versionconstants/versionconstants.go

- #7170
The problem with TYPO3 can be solved by making only the following change:
```diff
-$globalAutoload = $homeDir . '/.composer/vendor/autoload.php';
+$globalAutoload = $homeDir . '/.composer/vendor/perftools/php-profiler/autoloader.php';
```
The above is recommended by the upstream https://github.com/perftools/php-profiler#autoloader
Global `~/.composer/vendor/autoload.php` affected TYPO3 files, which was wrong.
- We don't care about PHP version, [perftools/php-profiler](https://packagist.org/packages/perftools/php-profiler) can be used with `php: ^5.3.0 || ^7.0 || ^8.0`
- Previous usage of `ddev composer global require` is tricky and can break Composer for our users. We don't need to have global `composer.json` and use its autoloader, I moved the php-profiler to …

fix: use correct autoloader for XHGui php-profiler, preinstall it in ddev-webserver, fixes #7170

---

docs/content/users/quickstart.md
docs/tests/craftcms.bats

I didn't review this before it was merged:
- #7107 
Related:
- #6246
- https://dev.to/mandrasch/install-craft-cms-v5-alpha-with-one-command-via-ddev-4ne5
- Makes the quickstart for Craft CMS non-interactive.
- Removes not needed comments from Craft CMS quickstart.
- Removes not needed `-y` flag.
https://ddev--7160.org.readthedocs.build/en/7160/users/quickstart/#craft-cms

docs: update Craft CMS quickstart, for #7107

---

containers/ddev-webserver/ddev-webserver-base-scripts/start.sh
docs/content/users/quickstart.md
docs/tests/backdrop.bats

In an earlier PR, I was going to add instructions on how to install the Bee CLI add-on for Backdrop. It was suggested that it might be more useful to include it by default in the Backdrop Quickstart.
I'm not 100% sure that what I've done will work or is the right place for it, but I found a spot where it was doing some Drush-related processing and added the `ddev addon get` line there.
Run instructions from https://ddev--7053.org.readthedocs.build/en/7053/users/quickstart/#backdrop

feat: backdrop add bee to quickstart

---

containers/ddev-xhgui/Dockerfile
containers/ddev-xhgui/var/www/xhgui/config/config.php
pkg/versionconstants/versionconstants.go

XHGui doesn't have a Docker volume anymore:
- https://github.com/perftools/xhgui/pull/520
Removes workaround for xhgui volume.
This PR reverts:
- #7142
```
ddev xhgui
ddev logs -s xhgui -f
```

build: bump XHGui image to 0.23, for #7142

---

cmd/ddev/cmd/delete_test.go
cmd/ddev/cmd/testdata/TestDeleteCmd/busybox/busybox/Dockerfile
cmd/ddev/cmd/testdata/TestDeleteCmd/busybox/docker-compose.busybox.yaml
cmd/ddev/cmd/testdata/TestDeleteCmd/busybox/install.yaml
pkg/ddevapp/ddevapp.go

@rpkoller noticed that if you have an add-on and that add-on has its own `Dockerfile`, the create image is not deleted on `ddev delete -Oy`
It should remove created `ddev-<project-name>-solr` image, which is not removed in v1.24.3:
```
ddev add-on get ddev/ddev-solr
ddev start
ddev delete -Oy
$ docker images | grep solr
ddev-d11-solr
```
- Goes through each image with `com.docker.compose.project=<project-name>` label and removes it.
- Doesn't say `Volume ... was deleted` if that volume is already removed.
- Adds test coverage for `ddev delete`
```
ddev add-on get ddev/ddev-solr
ddev start
```
And
```
$ ddev delete -Oy
Container ddev-d11-db  Stopped 
Container ddev-d11-web  Stopped 
Container ddev-d11-solr  Stopped 
Container ddev-d11-web  Stopped 
Container ddev-d11-db  Stopped 
Container …
```

fix: delete third-party built images on `ddev delete`

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

It's time for v1.24.4 release mostly because of:
- #7069
- Bumps Docker images to v1.24.4
- Bumps `docker-compose` to [v2.34.0](https://github.com/docker/compose/releases/tag/v2.34.0)
XHGui image should be rebuilt if we decide to pull:
Add release notes for:

build: bump images to v1.24.4 for release, and docker-compose to v2.34.0, fixes #7131

---

cmd/ddev/cmd/scripts/test_ddev.sh

From Discord https://discord.com/channels/664580571770388500/1357034479956262993
When I looked at `ddev debug test` there, I noticed that the test project failed to start because of
```dockerfile
RUN curl -I https://www.google.com
```
Which didn't work under a proxy.
This resulted in a broken project, preventing us from seeing any project-related curl requests.
```
> [web  8/10] RUN curl -I https://www.google.com:
0     0    0     0    0     0      0      0 --:--:--  0:02:18 --:--:--     0
139.4 curl: (28) Failed to connect to www.google.com port 443 after 138939 ms: Couldn't connect to server
------
', stderr='failed to solve: process "/bin/bash -c curl -I https://www.google.com" did not complete successfully: exit code: 28'
============= ddev-tryddevproject-15383-web healthcheck run …
```

fix: ignore curl error in `Dockerfile.test` for `ddev debug test`

---

pkg/ddevapp/ddevapp.go
pkg/ddevapp/router.go
pkg/ddevapp/ssh_auth.go
pkg/ddevapp/utils.go
pkg/dockerutil/dockerutils.go
pkg/dockerutil/dockerutils_test.go

- #7146
Related:
- https://github.com/php-perfect/ddev-intellij-plugin/issues/408
- #6125
Possibly related:
- #6085
Filter them out by looking at the `com.docker.compose.oneoff` label.
I didn't find any documentation on this, but it's well documented in the source code:
- https://github.com/docker/compose/blob/7bedb5a02c8b5f6075806112bc051b3741b609ee/pkg/api/labels.go#L46-L47
```go
// OneoffLabel stores value 'True' for one-off containers created by `compose run`
OneoffLabel = "com.docker.compose.oneoff"
```
- https://github.com/docker/compose/pull/8960/files
```go
api.OneoffLabel: "False", // default, will be overridden by `run` command
```
Containers created by `docker-compose up` have `com.docker.compose.oneoff=False`
Containers created by `docker-compose run` have …

fix: don't wait for one-off containers from PhpStorm, fixes #7146

---

pkg/netutil/netutil.go

- #6245
WSL2 with networkingMode=mirrored seems to break port checks, as there is no response for the dial attempt and ddevs netutil IsPortActive waits around 5 minutes for each port to check when starting a project. This makes it quite unusable. The windows team seems not able to fix it in a reasonable time so im proposing this simple change as a workaround. 
Instead of waiting 5 minutes for each port check on WSL2 (mirrored networking mode), it waits for .2 second max per check.  The timeout approach is only used on WSL2, and it's possible that in NAT mode it doesn't hit it anyway, but if it did it should be no more than about 1s total added to `ddev start`.
Note that the delay in mirrored mode happens only when the port is *not* occupied, which is what's superbly annoying about this. …

fix: add timeout for netutil::IsPortActive check for WSL2 with "mirrored networking mode" as opposed to default "NAT mode", fixes #6245

---

pkg/ddevapp/webserver_config_assets/nginx-site-backdrop.conf
pkg/ddevapp/webserver_config_assets/nginx-site-cakephp.conf
pkg/ddevapp/webserver_config_assets/nginx-site-craftcms.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal10.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal11.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal6.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal7.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal8.conf
pkg/ddevapp/webserver_config_assets/nginx-site-drupal9.conf
pkg/ddevapp/webserver_config_assets/nginx-site-laravel.conf
pkg/ddevapp/webserver_config_assets/nginx-site-magento.conf
pkg/ddevapp/webserver_config_assets/nginx-site-magento2.conf
pkg/ddevapp/webserver_config_assets/nginx-site-shopware6.conf
pkg/ddevapp/webserver_config_assets/nginx-site-silverstripe.conf
pkg/ddevapp/webserver_config_assets/nginx-site-symfony.conf
pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf
pkg/ddevapp/webserver_config_assets/nginx-site-wordpress.conf
pkg/ddevapp/webserver_config_assets/nginx_second_docroot_example-site-php.conf

Media stanza in `nginx.conf` doesn't work as expected in some cases:
| Framework | 404 `.png` handled by | 404 `.txt` handled by | Description |
| --------- | -------------- | ----------- |  ----------- |
| Shopware6 | nginx (this PR: app) | app | without PR `.png` is handled by nginx (this is wrong) |
| Magento1 | nginx (this PR: app) | app | has the same problem as Shopware6 |
| Magento2 | nginx (this PR: app) | app | has the same problem as Shopware6 |
| Typo3 | nginx (this PR: app) | app | has the same problem as Shopware6 |
| Wordpress | nginx (this PR: app) | app | has the same problem as Shopware6 |
| Laravel | app | app | has `error_page 404 /index.php;` |
| Symfony | app | app | because nginx doesn't have `Media` stanza |
| Drupal | app | app | Media stanza has `try_files $uri …

fix: nginx.conf should let index.php handle 404 errors for media files

---

.github/RELEASE_NOTES_TEMPLATE.md
Makefile
docs/content/users/install/ddev-installation.md
docs/content/users/install/ddev-upgrade.md
docs/content/users/install/docker-installation.md
scripts/install_ddev_wsl2_docker_desktop.ps1
scripts/install_ddev_wsl2_docker_inside.ps1
winpkg/ddev.nsi

- #6636 
- #6344 (I think this is the final fix for Windows ARM64, stopping use of Choco)
We no longer need Chocolatey when installing inside WSL so let's remove it to prevent side effects that users are running into.
It removes the unnecessary dependency.
1. Run the script to install DDEV.
1. Ensure that there are no errors caused by Chocolatey not being installed.
1. Ensure that DDEV works.
TBD
TBD

build: stop installing chocolatey, fixes #6636, fixes #6344 [skip buildkite]

---

cmd/ddev/cmd/xhgui_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/xhprof_xhgui.go

- #7181 
This PR move the logic of building the xhgui url into the describe method, just like mailpit.
- ddev config global --router-http-port=8080 --router-https-port=8443
- ddev restart
- ddev xhgui launch
The launch should now work instead of throwing an error.
Automated test has been updated to validate values are properly filled in by the describe method.

fix: XHGui launch command support custom ports, fixes #7181

---

docs/content/users/quickstart.md

Minor correction of a typo "Grave" -> "Grav"

docs: fix minor typo in the Grav quickstart

---

cmd/ddev/cmd/config.go
cmd/ddev/cmd/config_test.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/templates.go

- #7060
```
mkdir foo && cd foo
ddev config --omit-containers=db
ddev delete -Oy
sed -i '1d' .ddev/config.yaml
echo "name: bar" > .ddev/config.local.yaml
ddev start
Starting bar...
ddev stop
this project root '/home/stas/code/ddev/foo' already contains a project named 'bar'. You may want to remove the existing project with "ddev stop --unlist bar"
ddev stop --unlist bar
ddev config --webserver-type apache-fpm
ddev start
Starting bar...
```
So you need to unlist the project before running `ddev config` to make it work.
But it must simply work with the `name` we already have from `.ddev/config.local.yaml`
- Sets app name to the appropriate value, so it won't throw an error.
- Doesn't write the `name` to `.ddev/config.yaml` if you already have it in `.ddev/config.*.yaml`. …

fix: make `ddev config` work with project name from `config.*.yaml`, fixes #7060

---

cmd/ddev/cmd/addon-get.go
pkg/archive/archive.go
pkg/archive/archive_test.go
pkg/ddevapp/mutagen.go
pkg/dockerutil/docker_compose_version_test.go
pkg/dockerutil/dockerutils.go
pkg/fileutil/files.go
pkg/fileutil/files_test.go
pkg/testcommon/testcommon.go
pkg/util/network.go
pkg/util/network_test.go

Discord: https://discord.com/channels/664580571770388500/1349663367178096650/1349755537377722520
A user upgraded to DDEV v1.24.3 and somehow got a bad version of the mutagen-agents.tar.gz which did not contain the linux agents.
```
rfay@rfay-mba-m4:~/Downloads/bin.bak$ tar -vtzf mutagen-agents.tar.gz
-rwxr-xr-x  0 0      0     9511958 Feb 24 15:34 aix_ppc64
-rwxr-xr-x  0 0      0     8176880 Feb 24 15:34 darwin_amd64
-rwxr-xr-x  0 0      0     7892416 Feb 24 15:34 darwin_arm64
-rwxr-xr-x  0 0      0     7848088 Feb 24 15:35 dragonfly_amd64
-rwxr-xr-x  0 0      0     7528610 Feb 24 15:35 freebsd_386
```
They did say they might have had internet troubles at the time, but I don't know how we could be untarring an agents file and getting different results.
This probably doesn't actually solve …

fix: make sure mutagen agents file is fresh on upgrade, add shasum testing, test shasum for mutagen+docker-compose

---

docs/tests/drupal.bats

So far it was only tested if the installer page was loaded. after that much could break. the PR adds a drush site install and a drush recipe to apple the blog recipe. that way it is possible to test if the site is actually installed properly, is able to be launched and if the recipes was correctly applied. 

test: make the drupal cms bats test a bit more robust and trustworthy

---

docs/content/users/extend/custom-commands.md
pkg/ddevapp/app_compose_template.yaml

- #7198 
Adds the variable to the web container.
```
ddev ssh
echo $DDEV_APPROOT
```
You should see "/var/www/html" as the output (without the quotes of course)

feat: add DDEV_APPROOT variable to web container and updates documentation, fixes #7198

---

containers/ddev-dbserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #6963 
It looks like percona updated repositories finally.
Use the official technique.

build: switch to official percona release for xtrabackup, fixes #6963

---

pkg/ddevapp/global_dotddev_assets/commands/web/xdebug
pkg/ddevapp/xhprof_xhgui.go

- #6191
- php-perfect/ddev-intellij-plugin#414
When xdebug is enabled, DDEV internal executions of PHP code are not excluded from debugging, causing unexpected debugging connections in the IDE.
- Add flags to disable xdebug connections for status checks of xdebug itself, works for xdebug 2 and 3.
- Add ENV to disable xdebug for status checks of xhprof, works only for xdebug 3.
For xdebug 2 support, we'd first need to figure out the xdebug version. Seeing as the composer command also implements the xdebug 3 only solution, this is what I went with here as well.
Setup:
Take any ddev project, can also be a completely new and blank one
ddev config global --xhprof-mode=xhgui
ddev start
ddev xdebug on
Enable xdebug listen in PhpStorm
Test the following commands. Running either causes a debug …

fix: disable xdebug trigger for xdebug and xhprof status checks, fixes #6191, fixes php-perfect/ddev-intellij-plugin#414

---

pkg/ddevapp/ddevapp.go

- #7098
During backup of postgresql, the export might be blocked for up to 5 minutes. This happens when the postgres checkpoint is being triggered. Since the checkpoint_timeout is set to 5 minutes, and postgres by default spreads out the writes across most of the timeout time, that's the maximum duration the backup might hang for.
Add `-c fast` during backup, which instructs postgres to immediately perform the checkpoint at maximum speed, instead of spreading the writes out.
Documentation:
Checkpoints: https://www.postgresql.org/docs/17/wal-configuration.html
Backup flags: https://www.postgresql.org/docs/17/app-pgbasebackup.html
```
mkdir d11
cd d11
ddev config --project-type=drupal11 --docroot=web --database postgres:16
ddev composer create-project drupal/recommended-project
ddev …
```

fix: Use fast checkpoint during postgresql backup, fixes #7098

---

docs/content/users/extend/customizing-images.md
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/dotddev_assets/db-build/README.txt
pkg/ddevapp/dotddev_assets/web-build/README.txt

We can customize the default Dockerfile by adding appending stuff to the end (through `Dockerfile* variants`), and by injecting something before ddev own customizations, but still in between ddev's own Dockerfile (through `pre.Dockerfile*` variants). But we cannot add anything before everything else, limiting other customization like being able to define other build stages. 
It adds a new `prepend.Dockerfile*` variant that gets added on top of everything before anything added by ddev.
1. create a `.ddev/web-build/prepend.Dockerfile.pr-7071` with:
```dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE AS build-stage-go
ARG uid
ARG gid
RUN set -eux; \
GO_VERSION=$(curl -fsSL "https://go.dev/dl/?mode=json" | jq -r ".[0].version"); \
AARCH=$(dpkg --print-architecture); \
wget -q …
```

feat: support prepend.Dockerfile* files for multi-stage builds

---

docs/content/users/usage/networking.md

- #7209
- https://github.com/ddev/ddev/issues/7211
Related:
* https://github.com/ddev/ddev/issues/4032
* https://github.com/ddev/ddev/pull/4049 (has test situation)
Needed improvements in 
Rendered at https://ddev--7212.org.readthedocs.build/en/7212/users/usage/networking/#corporate-packet-inspection-vpns-including-zscaler-and-global-protect

docs: Improvements to Zscaler instructions, fixes #7209, fixes #7211 [skip buildkite]

---

pkg/ddevapp/ddevapp.go
pkg/util/utils.go

- #7157
On start, check to see if docroot and index.* exist - or warn. Don't do it on generic webserver_type.
- nothing added

refactor: check for docroot/index.* on start, fixes #7157

---

cmd/ddev/cmd/composer-create-project.go
docs/content/users/quickstart.md
docs/tests/cakephp.bats
docs/tests/contao.bats
docs/tests/craftcms.bats
docs/tests/drupal.bats
docs/tests/frankenphp.bats
docs/tests/grav.bats
docs/tests/ibexa.bats
docs/tests/kirby.bats
docs/tests/laravel.bats
docs/tests/magento2.bats
docs/tests/moodle.bats
docs/tests/pimcore.bats
docs/tests/processwire.bats
docs/tests/shopware.bats
docs/tests/silverstripe.bats
docs/tests/statamic.bats
docs/tests/sulu.bats
docs/tests/symfony.bats
docs/tests/typo3.bats
docs/tests/wordpress.bats

- #6920
@stasadev finally got `ddev composer create-project` sorted out to be identical to `composer create-project` so we don't need the one-off `ddev composer create` any more. 
Update docs and CMS quickstart tests

docs: use ddev composer create-project everywhere, fixes #6920

---

.buildkite/test.sh
.buildkite/testbot_maintenance.sh

- #7176
Random docker or network fails shouldn't tie up the test runner forever.
Look carefully at buildkite output on mac, WSL2, Windows.

test: add timeout to buildkite maintenance, fixes #7176

---

docs/content/users/quickstart.md
docs/tests/drupal.bats
docs/tests/shopware.bats

When using Zsh, the `composer create ...` command will fail if using a caret symbol to specify the project version.
Drupal Slack conversation: https://drupal.slack.com/archives/C5TQRQZRR/p1745774586216839
Zsh issue:
- https://github.com/ohmyzsh/ohmyzsh/pull/3919
Wrapping the project and version number in quotes will prevent Zsh from globbing, and allow the command to execute as expected.
Review https://ddev--7237.org.readthedocs.build/en/7237/users/quickstart/

docs: wrap quotes around commands that use the caret symbol

---

docs/content/users/quickstart.md
docs/tests/pimcore.bats

- #7243 
Pimcore 12.0.0 came out today, and now you can't install without getting a product key.
Rendered quickstart at https://ddev--7245.org.readthedocs.build/en/7245/users/quickstart/#pimcore

docs: Remove --no-interaction from Pimcore, disable test, fixes #7243

---

docs/content/users/quickstart.md
docs/tests/common-setup.bash
docs/tests/typo3.bats
pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf

- #6944
TYPO3 docroot setup is changing.
TYPO3 v14 LTS is still a year away (April 2026), but v14 will appear in a few months.
Use nginx config that will support older and newer TYPO3.

fix: support TYPO3 v14 nginx configuration, fixes #6944

---

.goreleaser.yml

We've had a few reports of people using the old `drud/ddev` homebrew tap and not getting updated. It's been well over a year since that was valid, but we still get the reports.
Drupal slack: https://drupal.slack.com/archives/C5TQRQZRR/p1746000327117559
```
rfay@ubuntu-len:~/workspace/ddev$ brew install ddev-test/ddev/ddev
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Tapping ddev-test/ddev
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/ddev-test/homebrew-ddev'...
remote: Enumerating objects: 573, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 573 (delta 46), …
```

build: Reject the use of `drud/ddev/ddev` homebrew recipe

---

docs/content/users/extend/customizing-images.md
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go

- Follow up to #7071 
I started playing with this with HEAD and found an issue which took me a bit to figure out. All of my examples and even tests that worked before was because `ARG BASE_IMAGE="scratch"` was added on the prepend file but I just didn't as I was using a smaller base image for a build stage and the Dockerfile build failed because of https://docs.docker.com/reference/dockerfile/#understand-how-arg-and-from-interact.
That particular ARG has to be before that first FROM so it can be used in any FROM afterwards. While we can be documented and leave prepend as plain as possible, I think this might confuse those that are trying to use this feature (if any). I figured that as BASE_IMAGE is a very important ARG to have defined, so I think it's best this is added before everything …

fix: add BASE_IMAGE arg before everything else, for #7071

---

.github/workflows/docscheck.yml
.linkspector.yml

We get 429 from GitHub links for linkspector https://github.com/ddev/ddev/actions/runs/14861937842/attempts/2
It seems that GitHub changed some limits.
- https://github.com/UmbrellaDocs/action-linkspector/issues/43
I noticed that we use `GITHUB_TOKEN` for actions (this is not the env itself, it's name for custom action variable) instead of `github_token` (IDE highlighted it for me)
Adds an exception for 429 status.

fix: allow status code 429 for linkspector

---

scripts/install_ddev_wsl2_docker_desktop.ps1
scripts/install_ddev_wsl2_docker_inside.ps1

Discord: https://discord.com/channels/664580571770388500/1367962405237166233
Using the new (without chocolatey) script for WSL2 install, the PS script calls the Windows installer, and then waited only 10s for the completion.
Apparently the NSIS installer hands off installation of files to a child process and can run to completion before the child process is done. In this situation the reporter said it was an older computer. There are ways to wait for the child process, but it seems simpler just to increase the wait time, so we increase it from 10s to 60s here.
If we could reproduce on older computer it would be great.

fix: WSL2 install script should wait longer for DDEV Windows installer to complete [skip ci]

---

.buildkite/testbot_maintenance.sh
Makefile
pkg/util/network.go

- https://github.com/ddev/ddev/pull/7234
In CI on Buildkite, we're still seeing download failures, even though we implemented retries. 
I had a chat with ChatGPT about the setup, and it suggested implementing a CheckRetry function that would note the "context deadline exceeded" that we're often seeing, and retry in that case. 
I don't think this does any harm.
But the problems are probably CI network problems.
Also added improved curl syntax in the Makefile, where we regularly have similar failures downloading mkcert.

refactor: Make DownloadFile() retry logic more robust, improve curling in Makefile

---

pkg/ddevapp/drupal.go

From Drupal Slack https://drupal.slack.com/archives/C5TQRQZRR/p1746102793754109
When I did `ddev config` it said: `Unable to set permissions inside container on settings files: ''` <- empty string in the quotes
- Adds `stderr` redirect to `stdout`.
- Removes `-f` silent flag.
- Doesn't run `app.Exec()` without a running container.
Now it outputs this (I reproduced it using a dummy go command):
```
Unable to set permissions inside container on settings files:
chmod: cannot access '/var/www/html/web/sites/default': No such file or directory
chmod: cannot access '/var/www/html/web/sites/default/settings.php': No such file or directory
```

fix: correct warning output formatting (Drupal) and don't try to do exec when not running

---

cmd/ddev/cmd/composer-create-project.go

- ddev/ddev-intellij-plugin#414
We set `XDEBUG_MODE=off` for `ddev composer`, but not for `ddev composer create-project`.
Adds `XDEBUG_MODE=off` for `ddev composer create-project`.
See https://github.com/ddev/ddev-intellij-plugin/issues/414#issuecomment-2848884444

fix: set `XDEBUG_MODE=off` for `ddev composer create-project`, fixes ddev/ddev-intellij-plugin#414

---

.github/workflows/colima-tests.yml
.github/workflows/container-tests.yml
.github/workflows/golangci-lint.yml
.github/workflows/main-build.yml
.github/workflows/pr-build.yml
.github/workflows/tests.yml

- #7057
- https://github.com/moby/moby/issues/49513
Upstream has a fix for go, which is already included in Arch Linux. (I'm already using it.)
The bug only affected Linux with kernel 6.11+
And I don't think DDEV has ever been affected by this bug seen in Docker.
---
I used `go-version: '>=1.23'` everywhere because this is what we have in `go.mod`:
https://github.com/ddev/ddev/blob/19a3e5fb27ca1793c4d2c4a809816b3245cd75dd/go.mod#L85
---
Adding `check-latest: true`, because it still used `go1.23.7` from cache.
Not needed.

build: remove <1.24 constraint for go, for #7057

---

cmd/ddev/cmd/addon-get_test.go
cmd/ddev/cmd/testdata/TestCmdAddonActionsOutput/recipe/install.yaml
docs/content/users/extend/additional-services.md
pkg/ddevapp/addons.go

This is just an idea on improving slightly the `ddev add-on get` output.
I was working on hanoii/ddev-pimp-my-shell and wanted to support installing it in both pre-1.24.5 and later so that I can keep for a while maintaining the two approaches (single stage/multi-stage).
I noticed something that was bothering me before as well, it is unrelated to the above, but it was what triggered it.
First, when an action outputs something, it stays above the description:
which is confusing, I rather have it below.
Also, I would have loved to have something other than 👍🏻  and 👎🏻  to make it visually clear that is neither success, nor error (call it a warning).
So I come up with this PR which translates to this:
It doesn't report as error either.
It relies on a a new annotation like `#ddev-description`: …

refactor: improve `ddev add-on get` output, add warning exit code annotation

---

docs/content/users/usage/cms-settings.md
docs/content/users/usage/commands.md
docs/tests/wordpress.bats
pkg/ddevapp/global_dotddev_assets/commands/web/wp

- #7241
This was done using my working time, please, consider giving credit to www.nazaries.com 
Adds `--path` to `$DDEV_DOCROOT` when `--path` is not present, `$DDEV_DOCROOT` is set, and there is no `path` in `wp-cli.yml` (or other config file), so it´s always executed in the right path.
1. `mkdir my-wp-site && cd my-wp-site`
2. `ddev config --project-type=wordpress --docroot=web`
3. Everything will be installed in `web`
Added a wordpress bats tests, which is a copy of a regular one with `--docroot`.
Make sure `wp` script is updated

fix: Add path to docroot in wp parameters when not set, fixes #7241

---

cmd/ddev/cmd/scripts/test_ddev.sh
docs/content/index.md
docs/content/users/install/ddev-installation.md
pkg/ddevapp/config.go
pkg/dockerutil/dockerutils.go
pkg/nodeps/wsl.go

- #7272
WSL2 Mirrored Mode is yet another kink in the already complex WSL2 landscape. Containers can only connect to Windows-side IP addresses, not to, for example. `docker0` in WSL2.
* Derive a candidate Windows-side IP address to connect to and provide it as host.docker.internal
* Update `ddev debug test` to give this kind of information.
* See https://github.com/ddev/ddev/issues/7272#issuecomment-2862942816
```
[wsl2]
networkingMode=mirrored
[experimental]
hostAddressLoopback=true
```
* No changed tests at this point, and we'll be forced to run a mirrored mode WSL2 test runner at some point.
This passes manual run of TestDdevXdebugEnabled and TestCmdXdebug on WSL2 as configured above

fix: make xdebug work with WSL2 mirrored mode, fixes #7272

---

pkg/ddevapp/apptypes.go
pkg/ddevapp/craftcms.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/envfile.go

- #7233
Craft CMS settings for DDEV would be better in the .ddev namespace
Move DB settings and the like into .ddev/.env.web. Could be improved with better naming, see
* #7235 
Use the [DDEV Craft CMS Quickstart](https://ddev.readthedocs.io/en/stable/users/quickstart/#craft-cms)
Note that the `composer create-project craftcms/craft` absolutely insists on creating a project-level .env with these values. It takes the correct values as default that have already been set by the .ddev/.env.web, but then they're place in the project .env, which is a pain.
Existing tests should behave the same

refactor: Use `.ddev/.env.web` for Craft CMS DDEV settings, fixes #7233

---

Makefile

I don't want to remember how to bump dependencies in `go.mod`.
Adds `make go-mod-update`.
```
make go-mod-update
make
```
I don't bump the dependencies here because I don't want to overload this PR with changed lines.
And I probably won't bump it for v1.24.5, I don't see any reason for that.

build: add `make go-mod-update` 

---

pkg/versionconstants/versionconstants.go

`docker-compose` v2.36.0 is out.
See https://github.com/docker/compose/releases
Uses it.

build: bump docker-compose to v2.36.0

---

cmd/ddev/cmd/auth-ssh.go
cmd/ddev/cmd/debug-rebuild.go
cmd/ddev/cmd/utils.go
docs/content/users/usage/commands.md

From StackOverflow https://stackoverflow.com/questions/79522674/how-to-restart-a-single-ddev-service-docker-container-without-restarting-the-f/79523060?noredirect=1#comment140420056_79523060
Improves `ddev debug rebuild`, so it doesn't restart the entire project when it's not needed.
```
ddev add-on get ddev/ddev-opensearch
ddev add-on get ddev/ddev-phpmyadmin
ddev restart
ddev exec -s opensearch kill 1
ddev exec -s phpmyadmin kill 1
ddev describe
ddev debug rebuild -s opensearch --cache
ddev describe
ddev debug rebuild -s phpmyadmin
ddev describe
```

feat: restart only specified service in `ddev debug rebuild`

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #7250
It's time for v1.24.5 release.
Bumps Docker images.

build: bump images to v1.24.5 for release, fixes #7250

---

cmd/ddev/cmd/autocompletion_test.go
cmd/ddev/cmd/debug-rebuild.go
cmd/ddev/cmd/exec.go
cmd/ddev/cmd/logs.go
cmd/ddev/cmd/ssh.go
pkg/ddevapp/utils.go

We don't have autocompletion for services.
Adds it.
```
ddev start
ddev exec -s <TAB><TAB>
ddev logs -s <TAB><TAB>
ddev ssh -s <TAB><TAB>
ddev debug rebuild -s <TAB><TAB> # should contain all services
ddev logs d11 -s <TAB><TAB>
ddev ssh d11 -s <TAB><TAB>
ddev debug rebuild d11 -s <TAB><TAB> # should contain all services
```
```
ddev add-on get ddev/ddev-redis
ddev restart
ddev exec -s <TAB><TAB> # see redis
```
```
ddev stop
ddev exec -s <TAB><TAB> # should be empty
ddev logs -s <TAB><TAB> # should be empty
ddev ssh -s <TAB><TAB> # should be empty
ddev debug rebuild -s <TAB><TAB> # should contain all services
ddev logs d11 -s <TAB><TAB> # should be empty
ddev ssh d11 -s <TAB><TAB> # should be empty
ddev debug rebuild d11 -s <TAB><TAB> # should contain all services
```

feat: add shell completion for --service (-s) flag

---

.goreleaser.yml

- #7297
See:
- https://github.com/ddev/homebrew-ddev/pull/51
- https://github.com/ddev/homebrew-ddev-edge/pull/4
`initialize` doesn't seem to know about `uninstall`. And moving the check to `install` didn't help.
We can remove the formula repo before removing the `ddev` binary.
```
brew install drud/ddev/ddev
cd "$(brew --repo drud/homebrew-ddev)"
git reset --hard HEAD~1
brew install drud/ddev/ddev
cd ~
brew update
brew uninstall -f ddev
rm -rf "$(brew --repo drud/homebrew-ddev)"
brew uninstall -f ddev
brew install ddev/ddev/ddev
```
Testing the instructions update in `ddev-test`:
```
brew install ddev-test/ddev-edge/ddev
cd "$(brew --repo ddev-test/homebrew-ddev-edge)"
brew install ddev-test/ddev-edge/ddev
git checkout c1d0f9b725a50ddd58043ca3b7d4f01d9b61aecf
$ ddev -v
ddev version …
```

build: update brew instructions for old formula, fixes #7297

---

cmd/ddev/cmd/debug-download-images.go
pkg/ddevapp/ddevapp.go
pkg/util/network.go

- #7298 
On slower networks, the download of docker-compose times out in just 20s and gives an odd message
I used network conditioning in Parallels to slow the download speed to 20Mbps to reproduce this.
Running TestDockerComposeDownload with the network slowed down shows the failure at 20s, but it succeed with this fix.

fix: change download timeout to 5 minutes instead of 20s, fixes #7298

---

pkg/ddevapp/apptypes.go
pkg/ddevapp/ddevapp.go

- #7236
- Discord (breakage of .ddev/.gitignore on craft in v1.24.5): https://discord.com/channels/664580571770388500/1372597483443589264
In https://github.com/ddev/ddev/pull/7236#issuecomment-2876493614 @stasadev pointed out that now that we're using .ddev/.env* for settings (instead of using php application-defined settings load techniques) the settings/env values may be loaded too late (after containers are up) in some situations.
Before #7236 I believe that all explicit use of settings, including project types that used project-level .env (loaded by PHP dotenv for example) were application-loaded, which meant that it didn't matter that we wrote the .env late (post-start). But now with #7236 we're using DDEV's .ddev/.env.* so those only get loaded during `docker-compose up`, and need …

fix: Make sure env-type settings are populated before start, don't override `.ddev/.gitignore` file, for #7236

---

docs/tests/typo3.bats
pkg/ddevapp/webserver_config_assets/nginx-site-typo3.conf

- #7299
Culprit:
- #7230
Uses a different nginx technique. Spent long hours with ChatGPT.
Try TYPO3 quickstart for v11, v12, v13, v14 (full install with login)
https://ddev.readthedocs.io/en/stable/users/quickstart/#typo3
v14:
```
git clone git@github.com:TYPO3/TYPO3.CMS.BaseDistribution.git my-typo3-site14
cd my-typo3-site14
ddev config --project-type=typo3 --docroot=public --php-version=8.3
ddev composer install
ddev config --auto # create TYPO3 settings after TYPO3 classes are installed in vendor
ddev exec touch public/FIRST_INSTALL
ddev launch /typo3/install.php
```
v13:
```
PROJECT_NAME=my-typo3-site13
mkdir ${PROJECT_NAME} && cd ${PROJECT_NAME}
ddev config --project-type=typo3 --docroot=public --php-version=8.3
ddev start
ddev composer create-project …
```

fix: make TYPO3 nginx config work with TYPO3 v12, fixes #7299, for #7230

---

pkg/versionconstants/versionconstants.go

`docker-compose` [v2.36.1](https://github.com/docker/compose/releases/tag/v2.36.1) is out.
Bumps it.

build: bump docker-compose to v2.36.1

---

docs/content/users/quickstart.md
docs/tests/typo3.bats

the test for v12 will fail in current HEAD, it requires https://github.com/ddev/ddev/pull/7301

test: adding quickstarts for typo3 v13 and v12 plus bats tests

---

cmd/ddev/cmd/describe.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/router.go
pkg/ddevapp/router_test.go

While working on #7152, I discovered that ephemeral ports don't work properly with the `generic` webserver.
Using svetlekit quickstart https://ddev.readthedocs.io/en/stable/users/quickstart/#nodejs
```
$ ddev poweroff
$ docker run -it --rm -p 80:80 -p 443:443 busybox sh
$ ddev start
Starting my-sveltekit-site... 
Port 80 is busy, using 33000 instead, see https://ddev.com/s/port-conflict 
Port 443 is busy, using 33001 instead, see https://ddev.com/s/port-conflict 
Building project images....
Project images built in 2s. 
Network ddev-my-sveltekit-site_default  Created 
Container ddev-my-sveltekit-site-web  Created 
Container ddev-my-sveltekit-site-db  Created 
Container ddev-my-sveltekit-site-db  Started 
Container ddev-my-sveltekit-site-web  Started 
Waiting for containers to become ready: …
```

feat: make generic webserver work with ephemeral ports

---

cmd/ddev/cmd/describe.go
cmd/ddev/cmd/start.go
pkg/ddevapp/router.go

We have `generic` webserver added in:
- #6935
But if we don't use `web_extra_exposed_ports`:
- #7313
- https://github.com/ddev/ddev/pull/7171#issuecomment-2794803633
- https://github.com/ddev/ddev/pull/7171#issuecomment-2797299320
```
$ mkdir generic-no-ports && cd generic-no-ports
$ ddev config --webserver-type=generic --omit-containers=db
$ ddev start
...
Unable to properly check port status for 127.0.0.1:: err=dial tcp 127.0.0.1:0: connect: can't assign requested address
Unable to properly check port status for 127.0.0.1:: err=dial tcp 127.0.0.1:0: connect: can't assign requested address
^ warnings on macOS
...
Successfully started generic-no-ports 
Your project can be reached at             <= this is wrong
See 'ddev describe' for alternate URLs.
...
$ ddev describe
... …
```

fix: add checks for "generic" webserver without 80/443 ports, for #6935, fixes #7313

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #7310
Using:
- https://github.com/docker/buildx/issues/1744#issuecomment-1896645786
I pushed the existing v1.24.5 images as v1.24.6:
```
docker buildx imagetools create -t ddev/ddev-dbserver-mariadb-10.0:v1.24.6 ddev/ddev-dbserver-mariadb-10.0:v1.24.5
docker buildx imagetools create -t ddev/ddev-dbserver-mariadb-10.1:v1.24.6 ddev/ddev-dbserver-mariadb-10.1:v1.24.5
docker buildx imagetools create -t ddev/ddev-dbserver-mariadb-10.2:v1.24.6 ddev/ddev-dbserver-mariadb-10.2:v1.24.5
docker buildx imagetools create -t ddev/ddev-dbserver-mariadb-10.3:v1.24.6 ddev/ddev-dbserver-mariadb-10.3:v1.24.5
docker buildx imagetools create -t ddev/ddev-dbserver-mariadb-10.4:v1.24.6 ddev/ddev-dbserver-mariadb-10.4:v1.24.5
docker buildx imagetools create -t ddev/ddev-dbserver-mariadb-10.5:v1.24.6 …
```

build: bump images to v1.24.6 for release, fixes #7310

---

pkg/ddevapp/templates.go

I noticed this trailing space on a project.

docs: trailing whitespace on template

---

containers/ddev-dbserver/Dockerfile
pkg/ddevapp/config.go
pkg/versionconstants/versionconstants.go

- #7320
- installs or updates `debian-archive-keyring`, which fixes the problem with Debian gpg keys
- no need to remove obsolete MySQL 5.5/5.6 Jessie and before keys, we don't check them with `check_key_expirations.sh`
- unifies PostgreSQL logic; adding new Debian EOL releases to the `if` condition is now simpler
- removes non-working `/etc/apt/sources.list.d/mysql.list` from `mysql:5.6`
- adds debian-security updates repo for stretch
- uses `vim-tiny` instead of `vim` for PostgreSQL `db` image
- replaces `<distro>-pgdg main` with `<distro>-pgdg-archive main` for PostgreSQL
(pgdg-archive has more packages, see https://apt-archive.postgresql.org/)
Using AMD64 machine, test MySQL 5.5:
See errors here:
```
$ docker run --rm -it --entrypoint=bash ddev/ddev-dbserver-mysql-5.5:v1.24.6 -c …
```

build: update debian-archive-keyring for archived debian repos, fixes #7320

---

docs/content/users/install/phpstorm.md

From Discord https://discord.com/channels/664580571770388500/1376055542048358481/1376055542048358481
I'm trying to test out Junie in PHPStorm, but it's complaining that I don't have a CLI interpreter set. I have the DDEV plugin installed, but it doesn't make a difference.
I suppose this can happen when installing the DDEV Integration plugin *after* opening the project in PhpStorm.
In this case, the CLI interpreter does not change automatically.
This PR adds a tip about it.
https://ddev--7331.org.readthedocs.build/en/7331/users/install/phpstorm/#ddev-integration-plugin

docs: add tip on initial PhpStorm plugin setup

---

pkg/ddevapp/ddevapp.go

- #7330
```
$ ddev start
Starting missing-docroot-test...
The index.php or index.html does not yet exist in
/home/stas/code/ddev/missing-docroot-test/index.*
so you may get 403 errors 'permission denied' from the browser until it does.
Don't worry about this if a later action 
(like `ddev composer install`) will create the file.
...
```
- Adds a change suggested by @GuySartorelli
- Replaces `ddev composer install` with `ddev composer create-project` (this is the command that downloads all files)
```
mkdir missing-docroot-test && cd missing-docroot-test
ddev start
```
See:
```
$ ddev start
Starting missing-docroot-test...
The index.php or index.html does not yet exist at this path:
/home/stas/code/ddev/missing-docroot-test/index.*
You may get 403 errors 'permission …
```

refactor: improve message about missing docroot on `ddev start`

---

cmd/ddev/cmd/composer-create-project.go
docs/tests/shopware.bats

- https://github.com/ddev/ddev/pull/7323#pullrequestreview-2861494051
stdin doesn't seem to work properly with `ddev composer create-project`.
I.e. `echo x | ddev composer create-project shopware/production` doesn't pass `x`, Composer thinks there is no TTY, and doesn't ask any question.
And there is no error on failed `composer run-script`.
We want to have better test coverage by using stdin in our quickstart tests.
I investaged the problem and found out that:
1. `os.Stdin` is empty after it's passed to the first `app.Exec()` call, nothing there afterwards.
2. Composer doesn't recognize TTY at all when using pipes.
So I used `os.Pipe` to pass `os.Stdin` for each `app.Exec()` call and wrapped Composer commands in preudo-TTY with `script`:
- `composer run-script post-root-package-install` …

fix: make `ddev composer create-project` work with stdin

---

docs/tests/silverstripe.bats

The quickstart test for Silverstripe CMS is failing because of the new template in today's 6.0.0 release.
https://www.silverstripe.org/blog/silverstripe-cms-6-0/
Fixes it.

test: update check for starter page in Silverstripe CMS

---

containers/ddev-traefik-router/Dockerfile
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #7282
Xdebug 3.4.4 is available in `deb.sury.org` https://salsa.debian.org/php-team/pecl/xdebug
~~But it has some regressions:~~
~~- https://github.com/oerdnj/deb.sury.org/issues/2316~~
- Pushes `ddev-php-base` with `ddev-webserver`
- Adds `--no-cache` to `ddev-traefik-router` to make it 2.5 MB smaller.
```
$ ddev config --php-version=8.4 && ddev restart && ddev xdebug on && ddev php -v
PHP 8.4.8 (cli) (built: Jun  9 2025 13:42:27) (NTS)
Zend Engine v4.4.8, Copyright (c) Zend Technologies
with Zend OPcache v8.4.8, Copyright (c), by Zend Technologies
with Xdebug v3.4.4, Copyright (c) 2002-2025, by Derick Rethans
$ ddev config --php-version=8.3 && ddev restart && ddev xdebug on && ddev php -v
PHP 8.3.22 (cli) (built: Jun  9 2025 13:58:34) (NTS)
Copyright (c) …
```

build: bump ddev-webserver and ddev-traefik-router, for #7282

---

cmd/ddev/cmd/addon_test.go

I noticed some files in my `~/.ddev` from 2023. Turns out I ran `TestCmdAddon` back then, and it left some leftovers.
Removes them.

test: remove `TestCmdAddon` leftovers in `~/.ddev`

---

docs/content/users/usage/architecture.md
pkg/ddevapp/config.go

- Similar to #7355, we don't show any customizations, and our docs don't mention them.
- Adds a message about it on `ddev start`.
- Updates the docs.
Review https://ddev--7388.org.readthedocs.build/en/7388/users/usage/architecture/#hidden-global-files
```
$ cat <<'EOF' > ~/.ddev/ssh-auth-compose.test.yaml
services:
ddev-ssh-agent:
environment:
- TEST=foobar
EOF
$ ddev start
...
Using custom global ssh-auth-compose configuration (use `docker logs ddev-ssh-agent` for troubleshooting):
- /home/stas/.ddev/ssh-auth-compose.test.yaml
...
$ docker exec -it ddev-ssh-agent bash -c 'echo $TEST'
foobar
```

feat: display user-defined `ssh-auth-compose.*.yaml` on `ddev start`

---

.github/workflows/colima-tests.yml
.github/workflows/container-tests.yml
.github/workflows/docscheck.yml
.github/workflows/main-build.yml
.github/workflows/pr-build.yml
.github/workflows/quickstart.yml
.github/workflows/tests.yml

Homebrew recently updated the default branch from `master` to `main` for homebrew/actions repo, so this PR updates the default branch refs in here.

test: use `main` for  setup-homebrew action instead of `master`

---

cmd/ddev/cmd/debug-cd.go
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.fish
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.sh
pkg/ddevapp/global_dotddev_assets/commands/host/shells/ddev.zsh

@rfay noticed this:
```
$ ddevcd -h
ddevcd:cd:1: no such file or directory: To enable the 'ddevcd' function, source the ddev.sh script from your rc-script.\n\nFor bash:\n\nprintf '\n[ -f "/home/stas/.ddev/commands/host/shells/ddev.sh" ] && source "/home/stas/.ddev/commands/host/shells/ddev.sh"\n' >> ~/.bashrc\n\nFor zsh:\n\nprintf '\n[ -f "/home/stas/.ddev/commands/host/shells/ddev.zsh" ] && source "/home/stas/.ddev/commands/host/shells/ddev.zsh"\n' >> ~/.zshrc\n\nFor fish:\n\nprintf '\n[ -f "/home/stas/.ddev/commands/host/shells/ddev.fish" ] && source "/home/stas/.ddev/commands/host/shells/ddev.fish"\n' >> ~/.config/fish/config.fish\n\nRestart your shell, and use 'ddevcd project-name'.\n\nUsage:\n  ddev debug cd [flags]\n\nExamples:\n  ddev debug cd\n  ddevcd project-name\n\n\nFlags:\n …
```

fix: treat argument as literal in `ddevcd` despite leading dash

---

cmd/ddev/cmd/addon-get.go

- #7154
This bug may not be important, if we change the add-on logic (see #7316), but the fix is quick and shouldn't affect anything.
Marshals and unmarshals the app to get a complete configuration.
```
$ ddev config --web-environment="TEST=foo"
$ cat <<'EOF' > .ddev/config.db-php.yaml
php_version: "8.4"
database:
type: mysql
version: "8.0"
EOF
$ cat <<'EOF' > .ddev/config.override.yaml
override_config: true
web_environment:
- TEST=bar
EOF
$ cat <<'EOF' > install.yaml
name: test
pre_install_actions:
- |
echo "{{ range $k, $v := .DdevProjectConfig }}{{ $k }}: {{ $v }}
{{ end }}"
EOF
$ ddev add-on get .
```
Compare the output for `ddev add-on get .` to see the difference in `DdevProjectConfig`:
DDEV HEAD:
```yaml
additional_fqdns: []
additional_hostnames: []
composer_version: 2 …
```

fix: make DdevProjectConfig include overrides, fixes #7154

---

.goreleaser.yml
docs/content/users/install/ddev-installation.md
pkg/ddevapp/global_dotddev_assets/commands/host/launch
scripts/install_ddev_wsl2_docker_desktop.ps1
scripts/install_ddev_wsl2_docker_inside.ps1

Our use of xdg-open works fine in Debian/Ubuntu/Fedora, but on WSL2 it adds a huge dependency chain with all of Linux's gui features. It's also sometimes not reliable on WSL2 (can't find default browser, etc)
* Make xdg-utils a suggested dependency (and don't add it in WSL2)
* Add `--install-suggests` in docs for regular Linux install (or equivalent dnf for Fedora/etc) (but not on WSL2)
* In `ddev launch` prefer explorer.exe for launching instead of xdg-open
```
deb [trusted=yes] https://apt.fury.io/rfay/ * *
```

fix: make xdg-utils optional, use explorer.exe on WSL2 [skip buildkite]

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/config/remoteconfig/state.go
pkg/config/remoteconfig/types/remote_config_storage.go
pkg/config/state/types/state.go
pkg/config/state/types/state_storage.go
pkg/config/types/xhprof_mode.go
pkg/globalconfig/types/types.go
pkg/globalconfig/xhprof_mode.go
pkg/util/errcheck.go

There are some more warnings related to:
- #7415
And @rfay pointed out that behavior added in the PR below is confusing:
- #6954
- Uses `skip-package-name-checks` to disable this check. It often reports inconsistent results, likely due to caching issues (`golangci-lint cache clean && make golangci-lint`)
- Reverts changes made in #7415 as not needed.
- Removes `only-new-issues`, so full lint checks run on PRs.
- Pins for `golangci-lint` to v2.2.1, which avoids future breakage from upstream changes. This adds some maintenance since we need to bump it manually, but it prevents unexpected linter failures.

ci: use `skip-package-name-checks`, pin `golangci-lint` to v2.2.1, remove `only-new-issues`, for #7415

---

mkdocs.yml

From Discord https://discord.com/channels/664580571770388500/1361580318665998426
> There should be an easy and conspicuous way to access https://ddev.com/ from https://ddev.readthedocs.io/
Adds links for blog and add-on registry to navigation.
https://ddev--7427.org.readthedocs.build/en/7427/

docs: add blog and add-on registry to navigation

---

.github/dependabot.yml

New Dependabot "cooldown" feature.
* https://github.blog/changelog/2025-07-01-dependabot-supports-configuration-of-a-minimum-package-age/
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
Slow down dependabot so we don't see too many updates we don't care about.

build: Use new cooldown to slow dependabot updates [skip ci]

---

cmd/ddev/cmd/config-global.go
docs/content/users/configuration/config.md
docs/content/users/extend/in-container-configuration.md
docs/content/users/usage/commands.md
pkg/ddevapp/compose_yaml.go
pkg/ddevapp/ddevapp_test.go
pkg/globalconfig/global_config.go
pkg/output/output_setup.go
pkg/util/utils.go

- #7058
See https://no-color.org/
- Passes `NO_COLOR` from the host to containers.
- Sets `NO_COLOR=1` when `ddev config global --simple-formatting`
Search for `NO_COLOR` in the docs https://ddev--7419.org.readthedocs.build/en/7419/
Should be no colored output here:
```
NO_COLOR=1 ddev start
ddev composer -V
```
Should be no colored output here:
```
ddev config global --simple-formatting
ddev start
ddev composer -V
```
`NO_COLOR` should be set inside the containers:
```
$ ddev exec printenv NO_COLOR
1
$ ddev exec -s db printenv NO_COLOR
1
```
Create a PR here about `NO_COLOR` support in DDEV after v1.24.7 release:
- https://github.com/jcs/no_color

feat: add `NO_COLOR` variable support, fixes #7058

---

cmd/ddev/cmd/aliases.go
cmd/ddev/cmd/commands.go
cmd/ddev/cmd/dotenv-get.go
pkg/ddevapp/config.go
pkg/ddevapp/config_test.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/snapshot.go
pkg/util/utils.go

- #7403
I noticed more places without correct JSON output.
In addition, interactive `ddev config` didn't ask for `docroot` and `type` again, it failed immediately:
This should be a warning, not an error, DDEV should ask for docroot again, like it's done for project name:
```
echo "test_test\n\n/test" | ddev config
```
This should be a warning, not an error, DDEV should ask for app type again, like it's done for project name:
```
echo "\ntest\nfoo\n" | ddev config
```
```bash
ddev aliases -j | jq .raw
ddev config
ddev dotenv set .ddev/.env.tmp --test=123
ddev dotenv get .ddev/.env.tmp --test -j
```
Colored warnings as expected:
```
echo "test_test\n\n/test\ntest\nfoo\nphp\n" | ddev config
```

fix: use `output.UserOut` for JSON output, retry on invalid input in interactive `ddev config`, for #7403

---

cmd/ddev/cmd/root.go

There is no JSON output:
```
$ ddev -vj
ddev version v1.24.6
```
Modifies the version template for JSON.
```
$ ddev -vj 
{"level":"info","msg":"ddev version v1.24.6-47-g8113029ac","raw":{"version":"v1.24.6-47-g8113029ac"},"time":"2025-07-07T13:27:20+03:00"}
$ ddev --version -j | jq -r .raw.version
v1.24.6-47-g8113029ac
```

feat: add JSON output to `ddev -v`

---

cmd/ddev/cmd/exec.go
docs/content/users/usage/commands.md

- #3518
DDEV adds by default an command line text `Failed to execute command  ...` to stderr.
- Returns the exit code from the subcommand in `ddev exec`
- Adds a flag to suppress  `Failed to execute command  ...` with a command line flag for command `ddev exec`.
Usual output:
```
$ ddev exec "echo stdout; echo >&2 stderr; exit 42"
stdout
stderr
Failed to execute command `echo stdout; echo >&2 stderr; exit 42`: exit status 42
$ echo $?
42
```
Using quiet:
```
$ ddev exec -q "echo stdout; echo >&2 stderr; exit 42"
stdout
stderr
$ echo $?
42
```
---
Previously, this logic could be used to suppress the error message:
```
$ ddev exec "echo stdout; echo >&2 stderr; exit 42" 2>/dev/null
stdout
stderr
```

feat: return real exit code from `ddev exec` and add quiet flag to it, fixes #3518

---

.github/workflows/main-build.yml
.github/workflows/pr-build.yml

- #7420 
The upstream/main tarballs (done on every commit to main) didn't have ddev-hostname in them.
Add it, same as in PR build.
I'll pull this into main on ddev-test and we can see what happens.

fix: Include ddev-hostname in main build zipballs, fixes #7420

---

cmd/ddev/cmd/utils.go

I noticed a flaw in `cmd.prettyCmd()`:
https://go.dev/play/p/EVaaARj1uYn
```
cmd := []string{"bash", "-c", `echo "test"`}
fmt.Printf("original cmd: %v\n", cmd)            # original cmd: [bash -c echo "test"]
fmt.Printf("  pretty cmd: %v\n", prettyCmd(cmd)) #   pretty cmd: bash -c "echo "test""
fmt.Printf("original cmd: %v\n", cmd)            # original cmd: [bash -c "echo "test""] - bad
```
Makes a copy, escapes double quotes.
https://go.dev/play/p/ZDcMH1TgqE1
```
cmd := []string{"bash", "-c", `echo "test"`}
fmt.Printf("original cmd: %v\n", cmd)            # original cmd: [bash -c echo "test"]
fmt.Printf("  pretty cmd: %v\n", prettyCmd(cmd)) #   pretty cmd: bash -c "echo \"test\""
fmt.Printf("original cmd: %v\n", cmd)            # original cmd: [bash -c echo "test"] - good
```

fix: avoid mutating input slice in `cmd.prettyCmd()`

---

docs/content/users/install/ddev-installation.md
winpkg/ddev_windows_installer.nsi

- #7450
* Improper behavior on error in apt-get, etc
* Gentler response to apt-get update failure

fix: Improve Windows installer behavior (actually exit on errors)

---

cmd/ddev/cmd/commands.go

- #7409
Create a `.ddev/commands/host/test-example` or `.ddev/commands/web/test-example` (the important part is `## Flags: []`):
```bash
#!/usr/bin/env bash
echo $1
```
And run it:
```
ddev test-example '- h'
```
Shows hidden error.
This PR doesn't really fix the described behavior in the issue, but it's not a DDEV problem.
Before (shows help only, which is confusing):
```bash
$ ddev test-example '- h'
test-example (shell host container command)
Usage:
ddev test-example <input> [flags]
...
```
After (shows hidden error and help):
```bash
$ ddev test-example '- h'
Error: unknown shorthand flag: ' ' in - h
Usage:
ddev test-example <input> [flags]
...
```

fix: show errors for custom commands when flags are parsed, fixes #7409

---

containers/ddev-dbserver/files/docker-entrypoint.sh
pkg/versionconstants/versionconstants.go

- #7457
Makes sure that the custom config files are writeable before attempting to write them on startup.
Before:
```
$ ddev stop
$ touch .ddev/mysql/test.cnf
$ ddev start
$ ddev exec -s db ls -la /etc/mysql/conf.d 
total 12
drwxrwxrwx 1 root root  4096 Jul 17 18:59 .
drwxr-xr-x 1 root root  4096 Jul 16 19:58 ..
-rwxrwxrwx 1 root root     0 Jul 16 19:58 .gitmanaged
-r--r--r-- 1 stas mysql    0 Jul 17 18:59 test.cnf
$ ddev debug rebuild -s db --cache
...
Troubleshoot this with these commands:
- ddev logs -s db
...
$ ddev logs -s db
+ cp /mnt/ddev_config/mysql/test.cnf /etc/mysql/conf.d
cp: cannot create regular file '/etc/mysql/conf.d/test.cnf': Permission denied
```
After:
```
$ ddev stop
$ touch .ddev/mysql/test.cnf
$ cat <<'EOF' > .ddev/docker-compose.db-entrypoint.yaml
services:
db: …
```

fix: temporarily allow write to `/etc/mysql/conf.d/*` for `db` container restart, fixes #7457

---

cmd/ddev/cmd/delete_test.go
containers/ddev-dbserver/README.md
containers/ddev-php-base/README.md
containers/ddev-ssh-agent/README.md
containers/ddev-traefik-router/README.md
containers/ddev-webserver/Dockerfile
containers/ddev-webserver/README.md
containers/test-ssh-server/README.md
pkg/ddevapp/ddevapp.go
pkg/versionconstants/versionconstants.go

- #7383
- Bumps Docker images to v1.24.7
- Updates some Docker Hub README.md
- Bumps `docker-compose` to v2.38.2 (and sets `COMPOSE_BAKE=false` to restore the old behavior we rely on)

build: bump images to v1.24.7 for release, docker-compose v2.38.2 (`COMPOSE_BAKE=false`), fixes #7383

---

docs/content/index.md

It may be unclear what needs to be done for mirrored networking mode in WSL2.
Adds an example.
https://ddev--7463.org.readthedocs.build/en/7463/#system-requirements-windows-wsl2

docs: add `.wslconfig` example for mirrored networking mode in WSL2

---

docs/content/developers/network-test-environments.md
docs/content/developers/testing-docs.md
docs/content/users/install/ddev-installation.md

Minor docs fails in the manual installation section of DDEV Windows Installation
Thanks to @stasadev for carefully reading all this and catching the problems.
Rendered: https://ddev--7465.org.readthedocs.build/en/7465/users/install/ddev-installation/#ddev-installation-windows

docs: minor update to manual ddev instructions and use apt-get

---

docs/tests/ibexa.bats

the ibexa tests were failing according to @rfay . turned out that the `ddev exec console ibexa:install` now requires the manual entry of an admin password. it was probably added recently but according to https://doc.ibexa.co/en/latest/getting_started/install_ibexa_dxp/#create-a-database it is possible to override that with a no-interaction flag in the context of for example CI process like in this case. 

test: add a no-interaction flag to the install command in ibexa bats file

---

docs/content/users/extend/custom-commands.md

From:
- Discord https://discord.com/channels/664580571770388500/1397344938072735996/1397344938072735996
- Drupal Slack https://drupal.slack.com/archives/C5TQRQZRR/p1753284625736569
- #7451
Explains the usage for `Flags` annotation.
https://ddev--7478.org.readthedocs.build/en/7478/users/extend/custom-commands/#flags-annotation

docs: note about `Flags` annotation with unknown flags, for #7451

---

docs/content/users/extend/custom-compose-files.md

When you don't have an `image` with `build` stage, your DDEV can't work offline:
- https://github.com/ddev/ddev-addon-template/pull/81
Explains it.
https://ddev--7480.org.readthedocs.build/en/7480/users/extend/custom-compose-files/#conventions-for-defining-additional-services

docs: explain how to make `build` stage in `docker-compose.*.yaml` work offline

---

cmd/ddev/cmd/debug-download-images.go
docs/content/users/usage/commands.md
pkg/ddevapp/compose_yaml.go
pkg/ddevapp/ddevapp.go
pkg/dockerutil/composeutils.go
pkg/dockerutil/dockerutils.go
pkg/dockerutil/dockerutils_test.go
pkg/util/yamltools.go

- #7163
- Removes `docker pull` completely
- Uses `docker-compose pull` everywhere
- Refactors `ddev debug download-images`:
- Make it always pull, even if the image exists
- Add optional project arg
- Add `--all` flag to pull everything for all projects
Speed comparison for pulling basic images (Linux AMD64):
```
ddev delete images --all --yes && docker builder prune -f
start=$(date +%s%N)
ddev debug download-images
echo "Elapsed time: $((($(date +%s%N) - start) / 1000000)) ms"
```
Before (three retries):
```
Elapsed time: 46599 ms
Elapsed time: 47083 ms
Elapsed time: 53672 ms
```
After (three retries):
```
Elapsed time: 25162 ms
Elapsed time: 24964 ms
Elapsed time: 22870 ms
```
---
Check out:
```
ddev debug download-images
cd d11 && ddev debug download-images
cd ~ && ddev debug …
```

feat: parallel `docker-compose pull`, improve `ddev debug download-images`, fixes #7163

---

.github/workflows/linux-setup.sh
docs/content/developers/scripts/wsl2-test-runner-setup.sh

ngrok seems to have changed their Debian/Ubuntu support without a good path forward; deleted their existing package.
They "moved" to "bookworm support"
Use "bookworm" instead of "buster" in the ngrok installation.

test: ngrok broke their installation moving to bookworm, fix it

---

.buildkite/sanetestbot.sh
.github/workflows/nfstest.sh
.github/workflows/sanetestbot.sh
cmd/ddev/cmd/scripts/test_ddev.sh
docs/content/developers/scripts/windows_buildkite_setup.sh
docs/content/developers/scripts/windows_github_agent_setup.sh
docs/content/users/install/docker-installation.md
pkg/ddevapp/db.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/poweroff.go
pkg/dockerutil/dockerutils_test.go
pkg/fileutil/file_hash_test.go
pkg/globalconfig/global_config_test.go
pkg/versionconstants/versionconstants.go
scripts/debian_ubuntu_linux_ddev_nfs_setup.sh
scripts/macos_ddev_nfs_setup.sh
scripts/windows_ddev_nfs_setup.sh

- #7499
We already require ddev/ddev-utilities and have it downloaded. Using it will help us to better manage images that we control.
* Use ddev/ddev-utilities in user-facing activities
* I avoided changes to tests, as they would be intrusive and not useful
* busybox is still used widely in docs and examples, and it's fine there.

build: use ddev/ddev-utilities instead of busybox, fixes #7499

---

scripts/install_ddev_wsl2_docker_desktop.ps1
scripts/install_ddev_wsl2_docker_inside.ps1

- #7464
The Windows installer in v1.24.7+ obsoletes the installer scripts, but they remain simple examples to follow for manual installation of DDEV.
* Add warning at top (use installer)
* Remove installation of windows-side ddev
* Rework mkcert install to use wsl2-side mkcert.exe
Try running using the instructions at the top (instructions have been removed from docs)
No testing

fix: Update obsolete WSL2 install scripts to reflect new ddev-wsl2 and not needing ddev.exe, fixes #7464 [skip ci]

---

docs/content/users/install/ddev-installation.md

When installing DDEV, I got an error message saying that DDEV can't be installed. After [a discussion and troubleshooting on Discord](https://discord.com/channels/664580571770388500/1397288639503007825), re-installing the WSL with `wsl --install` and updating with `wsl --update` solved the problem. DDEV was installed smoothly.
Based on this, in some cases, running `wsl --update` command after installing WSL on Windows might be required to install DDEV successfully. 
This PR adds the command to appropriate parts of the docs.
https://ddev--7476.org.readthedocs.build/en/7476/users/install/ddev-installation/#ddev-installation-windows

docs(wsl): add `wsl --update` command for Windows

---

cmd/ddev-hostname/elevate.go
docs/content/developers/buildkite-testmachine-setup.md
pkg/ddevapp/hostname_mgt.go
pkg/hostname/hostname.go

- #7510
With a Linux homebrew installation, `ddev-hostname` elevation does not succeed
* Run `sudo /absolute/path/to/ddev-hostname` to make sure sudo doesn't stumble finding the target
* Minor docs changes to use "elevate" or "elevation" instead of "escalation", which is usually about security problems.
On linux AND macOS, with homebrew-installed ddev (but overwritten with the ddev from this PR)
```
ddev config --additional-fqdns=2.example.com
ddev start
```
We don't have a strategy for testing things that use sudo; we used to allow passwordless sudo on the buildkite machines, but that hid other problems. Maybe there's a way to solve this with a temporary overwrite of the /etc/sudoers.d/something

fix(ddev-hostname): sudo can't find ddev-hostname in linuxbrew, fixes #7510

---

cmd/ddev/cmd/root_test.go
cmd/ddev/cmd/start_test.go
cmd/ddev/cmd/testdata/TestCmdStartOptionalProfiles/docker-compose.busybox.yaml
pkg/ddevapp/compose_yaml.go
pkg/ddevapp/router.go
pkg/ddevapp/router_test.go
pkg/fileutil/embed.go

- https://github.com/ddev/ddev-mongo/issues/24
Router doesn't become healthy because of missing Traefik entrypoints for optional services.
- Adds host port detection for Traefik entrypoint by reading `.ddev/.ddev-docker-compose-full.yaml`
- Removes hardcoded XHGui ports, they are now read from YAML.
- Optimizes file writes for `.ddev/.ddev-docker-compose-base.yaml` and `.ddev/.ddev-docker-compose-full.yaml` if the content is not changed.
Start a project with optional profiles:
```
ddev add-on get ddev/ddev-mongo
ddev start
```
Check `~/.ddev/traefik/.static_config.yaml`:
```yaml
entryPoints:
http-80:
address: :80
http-443:
address: :443
http-8025:
address: :8025
http-8026:
address: :8026
http-8142:                 <= comes from xhgui
address: :8142
http-8143::                <= comes from …
```

fix(traefik): improve router port discovery and optimize YAML writes, fixes ddev/ddev-mongo#24

---

.envrc
docs/content/developers/building-contributing.md
docs/content/developers/testing-docs.md

Every time I switch into a ddev directory (a lot) I get several seconds of useless work being done:
```
direnv: loading ~/workspace/ddev/.envrc
Initializing python nodeenv...
Requirement already satisfied: nodeenv in ./.gotmp/env/python/lib/python3.13/site-packages (1.9.1)
[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
* Environment already exists: .gotmp/env/node
./.envrc:47: .gotmp/env/node/bin/activate: No such file or directory
Installing markdownlint...
changed 104 packages in 2s
54 packages are looking for funding
run `npm fund` for details
Installing linkspector...
⠼direnv: ([/opt/homebrew/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
changed 231 packages in 5s
93 packages are looking for …
```

build(direnv): Make direnv .envrc idempotent so it doesn't do all that work all the time

---

containers/ddev-dbserver/files/etc/mysql/version-conf.d/mariadb_10.6.cnf.txt
containers/ddev-dbserver/test/testdata/database_config/mariadb_10.6.ini
pkg/versionconstants/versionconstants.go

Our nightly container build/test [started failing last night](https://github.com/ddev/ddev/actions/runs/16924325047). Only the mariadb:10.6 test was failing, and it was failing because we expected to see 
On server startup `docker logs` you could see:
```
2025-08-13 21:04:08 0 [Warning] mysqld: io_uring_queue_init() failed with EPERM: sysctl kernel.io_uring_disabled has the value 2, or 1 and the user of the process is not a member of sysctl kernel.io_uring_group. (see man 2 io_uring_setup).
2025-08-13 21:04:08 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
```
It turns out we had seen this before, and it was noted in more than one of our configs for mariadb, for example, [mariadb:10.11](https://github.com/ddev/ddev/blob/main/containers/ddev-dbserver/files/ …

build(mariadb): turn off innodb_use_native_aio for mariadb:10.6

---

cmd/ddev/cmd/auth-ssh.go
cmd/ddev/cmd/auth-ssh_test.go
pkg/ddevapp/mutagen.go
pkg/dockerutil/dockerutils.go
pkg/exec/exec.go
pkg/exec/exec_test.go

- #6720
I couldn't reopen the closed PR, so this is a new attempt.
Replace the `docker run` approach with direct Docker client API calls for better control over container I/O and error handling. This enables proper support for both interactive terminal usage and piped input scenarios.
Key improvements:
- Use Docker client API instead of `docker run` for container management
- Add proper terminal raw mode handling to hide passphrase input
- Preserve `ssh-add` error codes and provide more detailed error messages
- Remove `xargs` because it doesn't work with stdin
- Add non-interactive stdin (I didn't add this feature to the docs, because I don't think we should encourage people to use it.)
Prepare keys:
- `key 0` has "key 0" passphrase
- `key_1` has "key_1" passphrase
- `key_2` has no …

feat: replace `docker run` in `ddev auth ssh` with Docker API and accept stdin

---

pkg/config/remoteconfig/messages.go

I didn't like the 1-space difference between the two lines of the sponsorship update.
Remove a space.
This could have been done by changing the source data for the second line, but we might as well do this now.
There are probably other ways we could improve this, probably the two hearts aren't necessary. But we can change the bulk of that without changing DDEV.

docs: fiddle with sponsorship title [skip ci]

---

go.mod
go.sum
pkg/ddevapp/ddevapp.go
pkg/versionconstants/versionconstants.go
vendor/github.com/compose-spec/compose-go/v2/dotenv/env.go
vendor/github.com/compose-spec/compose-go/v2/loader/loader.go
vendor/github.com/compose-spec/compose-go/v2/loader/reset.go
vendor/github.com/compose-spec/compose-go/v2/loader/validate.go
vendor/github.com/compose-spec/compose-go/v2/schema/compose-spec.json
vendor/github.com/compose-spec/compose-go/v2/template/variables.go
vendor/github.com/compose-spec/compose-go/v2/transform/canonical.go
vendor/github.com/compose-spec/compose-go/v2/transform/defaults.go
vendor/github.com/compose-spec/compose-go/v2/types/command.go
vendor/github.com/compose-spec/compose-go/v2/types/derived.gen.go
vendor/github.com/compose-spec/compose-go/v2/types/mapping.go
vendor/github.com/compose-spec/compose-go/v2/types/project.go
vendor/github.com/compose-spec/compose-go/v2/types/types.go
vendor/modules.txt

There is a new warning in `docker-compose` v2.39.0+:
- https://github.com/docker/compose/pull/13065
```
$ ddev start
Starting l12...
Building project images....time="2025-08-21T10:43:30+03:00" level=warning msg="COMPOSE_BAKE=false is deprecated, support for internal compose builder will be removed in next release"
...
```
I added `COMPOSE_BAKE=false` for `docker-compose` v2.38.2 in:
- #7456
- bumps `docker-compose` to v2.39.2
- bumps `github.com/compose-spec/compose-go/v2` to v2.8.1 (the same library version as used in `docker-compose` v2.39.2)
- removes `COMPOSE_BAKE=false`
There is no need to manually add the `com.docker.compose.project` label to the built images, as it's already fixed in:
- https://github.com/docker/compose/pull/13049

chore(deps): bump docker-compose to v2.39.2, remove `COMPOSE_BAKE=false`

---

mkdocs.yml

The Blog link is currently redirect users to the front page instead of the blog section directly.
Rendered: https://ddev--7566.org.readthedocs.build/en/7566/

docs: Fix blog link in main nav

---

containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- https://github.com/netz98/n98-magerun2/issues/1773
> The Debian bash autocomplete `n98-magerun2.phar` uses `local` where it can't be used, so everybody doing a `ddev ssh` in DDEV gets this since latest release:
> 
> ```
> rfay@ubuntu-len:~/workspace/d11$ ddev ssh
> bash: local: can only be used in a function
> bash: local: can only be used in a function
> ```
Uses the stable `master` branch as recommended in https://github.com/netz98/n98-magerun2/issues/1773#issuecomment-3224697637:
> > Is that what you'd recommend? It's been a lot of years. Is that still the recommended install technique?
> 
> The phar file is from stable release. The completion script is from unstable release. It whould be better to load the completion from stable "master" branch to have the completion compatible.
``` …
```

fix(magerun): use stable branch for autocompletion

---

.buildkite/test.sh
.buildkite/testbot_maintenance.sh

* I noticed that testbot_maintenance.sh was taking more than a minute on some neglected macos amd64 machines (mostly because it had failed to do the cleanup previously
* We were trying to `brew install gtimeout` but that's not valid. gtimeout comes with the coreutils package
Increase timeout, install coreutils
If test runs things should be fine. It's minor.

test(buildkite): Minor fixup for buildkite timeout

---

mkdocs.yml

- #6027
The `privacy` plugin generates `.cache` directory locally, but:
I don't like it because if it's cached, we can't see if there are any issues with external sources while working locally (and I don't like having one more `.cache` here because if I checkout some old git commit, this directory appears in unstaged files.)
- Used variable: https://docs.readthedocs.com/platform/stable/reference/environment-variables.html#envvar-READTHEDOCS
- Material for MkDocs config https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.enabled
> If you want to disable the plugin, e.g., for local builds, you can use an environment variable in mkdocs.yml
- I didn't remove `.cache` from `.gitignore`
Remotely, nothing changes for loaded sources:
---
Run this locally:
```
make mkdocs …
```

chore(mkdocs): disable privacy plugin for local builds, for #6027 [skip ci]

---

pkg/ddevapp/ddevapp.go
pkg/ddevapp/xhprof_xhgui.go

- #7557
Add XHGui ports to the ephemeral port resolution, and fix the incorrect TargetPortFromExposeVariable calls
Start other service on the default XHGui port 8142, e.g. via `nc -kl 8142`
ddev start
ddev xhgui
This will open up the browser showing xhgui using a port in the ephemeral range (33000-35000).

fix: add missing ephemeral port handling to xhgui service, fixes #7557

---

cmd/ddev/cmd/push.go
docs/content/users/providers/index.md
pkg/ddevapp/dotddev_assets/providers/README.txt
pkg/ddevapp/dotddev_assets/providers/acquia.yaml
pkg/ddevapp/dotddev_assets/providers/lagoon.yaml
pkg/ddevapp/dotddev_assets/providers/pantheon.yaml
pkg/ddevapp/dotddev_assets/providers/platform.yaml
pkg/ddevapp/dotddev_assets/providers/rsync.yaml.example
pkg/ddevapp/dotddev_assets/providers/upsun.yaml

As I've been working with providers recently (upsun, pantheon, platform) I've found `ddev push` to be very useful to non-production environments. It's a great way to push a db/files for testing.
The same caveats remain for pushing to production environments.
Soften the language about how to use `ddev push`

docs(provider): soften language about use of provider push

---

cmd/ddev/cmd/commands.go
cmd/ddev/cmd/debug-dockercheck.go
cmd/ddev/cmd/delete-images.go
cmd/ddev/cmd/networks_test.go
cmd/ddev/cmd/pull.go
cmd/ddev/cmd/push.go
cmd/ddev/cmd/snapshot_restore.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp.go
pkg/ddevapp/ddevapp_test.go
pkg/ddevapp/mutagen.go
pkg/ddevapp/router.go
pkg/ddevapp/utils.go
pkg/dockerutil/dockerutils.go
pkg/dockerutil/dockerutils_test.go
pkg/util/capture.go
pkg/util/utils.go
pkg/util/utils_test.go
pkg/version/version.go

- #7472  
While working on #7572, repeated calls to `ddevapp.fixupComposeYaml()` broke the output for `DDEV_DEBUG=true ddev launch`.
- Adds caching for warnings with the new `util.WarningOnce()` function (other functions can easily use the same approach if needed).  
- Removes `ddevapp.fixupComposeYaml()` from `ddevapp.NewApp()`, it's replaced by `app.ReadDockerComposeYAML()`
- Replaces several `ddevapp.NewApp()` calls with `&ddevapp.DdevApp{}` to simplify the logic.
- Adds error checks for all `dockerutil.GetDockerClient()`:
For context, why it was done: I switched from `ddevapp.GetActiveApp()` to `ddevapp.GetActiveAppRoot()` + `ddevapp.NewApp()` in #7403. The reason was that `ddevapp.GetActiveApp()` calls `ddevapp.FindContainerByType()`, which could panic if no `DockerClient` was …

fix: cache `WarningOnce`, reduce `NewApp` calls, handle `GetDockerClient` errors, for #7472

---

.buildkite/test.sh

When we pulled the updated docker singleton PR yesterday, several runners timed out because there were updated Postgres images.
Give testbot_maintenance.sh some more time to run. Some manual image deletion might be in order as well.

test(buildkite): buildkite can take a few minutes to pull new images [skip ci]

---

pkg/ddevapp/app_compose_template.yaml
pkg/ddevapp/compose_yaml.go
pkg/ddevapp/config.go
pkg/ddevapp/ddevapp_test.go
pkg/dockerutil/host_docker_internal.go
pkg/dockerutil/nfs.go

- Fixes #7537
Consolidates `host.docker.internal` configuration by moving it from template-time to compose post-processing.
- Remove `.HostDockerInternalIP` and `.UseHostDockerInternalExtraHosts` from the template 
- Add `host.docker.internal` handling in `fixupComposeYaml()` for all services
- Add `HOST_DOCKER_INTERNAL_IP` env variable for all services
```
ddev config --webserver-type=generic
ddev add-on get stasadev/ddev-frankenphp
ddev restart
for s in $(ddev describe -j | docker run -i --rm ddev/ddev-utilities jq -r '.raw.services | keys[]'); do
echo "Service: $s"
ddev exec -s "$s" getent hosts host.docker.internal
ddev exec -s "$s" 'echo HOST_DOCKER_INTERNAL_IP=$HOST_DOCKER_INTERNAL_IP'
echo
done
```
Testing on Linux:
v1.24.7:
```
Service: db
Failed to execute command `getent hosts …
```

feat: provide `host.docker.internal` for all services, fixes #7537

---

cmd/ddev/cmd/xhgui_test.go
pkg/ddevapp/mailpit_test.go
pkg/ddevapp/router_test.go
pkg/ddevapp/xhprof_xhgui_test.go
pkg/testcommon/testcommon.go

- #7543
`TestCmdXHGui` started failing too often:
```
xhgui_test.go:63:
Error Trace:	/Users/testbot/tmp/buildkite-agent/builds/macstadium-m1-1-local-1/ddev/ddev-macos-arm64-mutagen/cmd/ddev/cmd/xhgui_test.go:63
Error:      	Received unexpected error:
http status code for 'https://127.0.0.1' was 403, not 200
Test:       	TestCmdXHGui
Messages:   	failed to get http response from https://testcmdwordpress.ddev.site
```
- https://buildkite.com/ddev/ddev-macos-arm64-mutagen/builds/11333
- https://buildkite.com/ddev/ddev-macos-arm64-mutagen/builds/11393
- Uses `ddev restart` instead of `ddev start` in `xhgui_test.go`
- Adds `testcommon.HTTPRequestOpts`, function signature is backward compatible.
- Adds more retries, just like it is done in `mailpit_test.go`.
- Enables …

test(xhgui): add more retries for GetLocalHTTPResponse, for #7543

---

docs/content/users/extend/additional-hostnames.md

This fixes a typo in the docs, changing `additional_fqdn` to the correct `additional_fqdns` configuration.

docs: fix typo in documentation

---

containers/ddev-php-base/ddev-php-files/etc/php/8.4/apache2/php.ini
containers/ddev-php-base/ddev-php-files/etc/php/8.4/cli/php.ini
containers/ddev-php-base/ddev-php-files/etc/php/8.4/fpm/php.ini
containers/ddev-webserver/Dockerfile
pkg/versionconstants/versionconstants.go

- #7616 
A few "sid" related configurations were deprecated in php8.4 and we don't seem to have caught this last year when updating config for php8.4 and they slipped in as copy from php8.3.
Remove the relevant `sid` configurations
The behavior is all the same, we just won't see the warnings.
See #7616 
I don't think we need to change anything

fix(ddev-php-base): Remove php8.4-obsolete config, fixes #7616

---

docs/content/users/install/phpstorm.md

The DDEV PhpStorm docs "Prerequisite" section seems redundant in 2025.
https://docs.ddev.com/en/stable/users/install/phpstorm/#prerequisite
- https://github.com/ddev/ddev-intellij-plugin/issues/442
It removes the "Prerequisite" section.
It also updates "Preferences" to "Settings" and adds a link to the Drupal PhpStorm DDEV doc page

docs: remove Prerequisite section

---

cmd/ddev/cmd/commands_test.go
docs/content/users/usage/cli.md
docs/content/users/usage/commands.md
pkg/ddevapp/global_dotddev_assets/commands/web/npx

* `npx` is not an existing ddev command.
* `npx` is an alias of `npm exec --` that comes with the npm package, so no new code is needed.
* `npx` is used to run JS code without installing it, which is often for setup, init, demos, config, and other one time executions.
This allows users to `ddev npx` in the same way they can do `ddev npm` without having to do `ddev exec npx`.
1. `ddev config`
2. `ddev start`
3. `ddev npx -c 'echo hello'` will say hello. Or any npx command like `ddev npx @biomejs/biome init` which will setup biomejs config in your project.
* The change is minor in the way that this is an alias of another command, npm, that already has  a test, so if the npm test passes this should as well. 
* There is also the consideration of how to make it not be flaky since it largely …

feat: add `ddev npx` command

---

.goreleaser.yml

- #7545
DDEV [v1.24.8](https://github.com/ddev/ddev/releases/tag/v1.24.8) uses `docker-compose` v2.39.3, which requires `docker-buildx` https://archlinux.org/packages/extra/x86_64/docker-buildx/
(`docker-compose` [v2.37.0](https://github.com/docker/compose/releases/tag/v2.37.0) switched to Bake builder by default.)
Adds missing AUR dependency.

build(aur): add docker-buildx dependency

---

pkg/dockerutil/networks_test.go

- #7657
- Uses require instead of assert for network tests
- Fixes assign for app1 and app2 - that's why tests failed sometimes
- Runs `TestNetworkAliases` everywhere, I don't think that we can get "connection reset by peer" inside containers.

test: fix TestNetworkAliases, fixes #7657

---

pkg/ddevapp/cakephp.go

Today, I cloned an internal CakePHP4 project.
It appeared to work but some translation strings were not displaying correctly.
DDEV generated a `config/.env` based on `config/.env.example`.
DDEV (correctly) overrode `DATABASE_URL` & `EMAIL_TRANSPORT_DEFAULT_URL` to point to itself.
However, it overrides `APP_DEFAULT_LOCALE` to `en_US` which resulted in CakePHP looking for English translation instead of using the Japanese.
Since DDEV does NOT override `APP_DEFAULT_TIMEZONE`, this feels like unexpected.
The PR does not explicitly set `APP_DEFAULT_LOCALE`, thus falling back to `config/.env.example` settings.
Tested on CakePHP4 & CakePHP5
1. Check DDEV version
```shell
ddev -v
ddev version v1.24.7
```
1. Create a new CakePHP project following current quickstart guide.
```shell
mkdir …
```

fix(cakephp): do not override APP_DEFAULT_LOCALE

---

pkg/ddevapp/config.go

- #7661
With the arrival of postgres 18, postgresql-client always installs 18 apparently
Temp hack, to be reverted:
Uninstall postgresql-client:18 after the required client is installed
```
ddev config --database=postgres:15
ddev delete -Oy
ddev start -y
ddev exec psql --version # should get 15
```

fix(hack-postgres): hack postgres client since postgresql-client:18 is misbehaving, for #7661

---

pkg/ddevapp/config.go

- #7663
The issue with `postgresql-client-18` appeared because we install `postgresql-client` in `ddev-webserver`.
The current `ddev-webserver` has `postgresql-client` and its dependency `postgresql-client-17` installed.
When `postgresql-client-18` was released, it became the new dependency for `postgresql-client`, so removing `postgresql-client-17` automatically installed `postgresql-client-18`.
Removes `postgresql-client` with its dependencies.
```
ddev delete -Oy
ddev config --database=postgres:15
ddev start
ddev psql --version    # psql (PostgreSQL) 15.14
```

fix(postgres): uninstall postgresql-client with its dependencies, for #7663

---

docs/content/users/quickstart.md
docs/tests/moodle.bats

- #7692 
Moodle quickstart just broke; I didn't find the reason. I think they might have shifted underneath us some time ago, but just added validation about using "public" at the end of URL, no longer allowed.
Don't use `composer_root`
Check out the quickstart.
For extra credit, find the moodle change notice.

docs(moodle): update moodle quickstart to have composer_root in root, fixes #7692 [skip buildkite]

---

cmd/ddev/cmd/addon-get.go
cmd/ddev/cmd/exec.go
pkg/dockerutil/docker_compose.go
pkg/exec/exec.go

- #7671
- Adds `Env` to `dockerutils.ComposeCmdOpts`
- Adds `COMPOSE_DISABLE_ENV_FILE=1` for `docker-compose pull`, see https://github.com/compose-spec/compose-go/pull/510
- Skips `docker-compose pull` when there is nothing to pull (previously it ran every time)
- Removes unused `getInjectedEnv`
- Appends to `Env` instead of full overriding in different places.
```
echo "FOO=\$BAR" > .env
docker rmi ddev/ddev-utilities
ddev start
```
v1.24.8:
```
$ ddev start
Starting project... 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BAR" variable is not set. Defaulting to a blank string. 
[+] Pulling 3/3
✔ …
```

fix: disable `.env` parsing for `docker-compose pull`, fixes #7671
